ct::models::HyQ::HyQWithContactModelLinearizedForward Class Reference
ct::models::HyQ::HyQWithContactModelLinearizedForward Class Reference
#include <HyQWithContactModelLinearizedForward.h>
Public Types
typedef ct::core::LinearSystem< 36, 12, double > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::state_matrix_t state_matrix_t
typedef Base::state_control_matrix_t state_control_matrix_t
Public Types inherited from ct::core::LinearSystem< 36, 12, double >
typedef Base::time_t time_t
typedef StateVector< 36, double > state_vector_t
typedef ControlVector< 12, double > control_vector_t
typedef StateMatrix< 36, double > state_matrix_t
typedef StateControlMatrix< 36, 12, double > state_control_matrix_t
Public Types inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, SCALAR >
typedef SCALAR time_t
Public Types inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, double > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, double >
typedef double time_t
Public Member Functions
HyQWithContactModelLinearizedForward (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
HyQWithContactModelLinearizedForward (const HyQWithContactModelLinearizedForward &other)
virtual ~HyQWithContactModelLinearizedForward ()
virtual HyQWithContactModelLinearizedForward * clone () const override
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const double t=double(0.0)) override
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const double t=double(0.0)) override
Public Member Functions inherited from ct::core::LinearSystem< 36, 12, double >
LinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
virtual ~LinearSystem ()
virtual void computeControlledDynamics (const state_vector_t &state, const time_t &t, const control_vector_t &control, state_vector_t &derivative) override
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
virtual void getDerivatives (state_matrix_t &A, state_control_matrix_t &B, const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))
Public Member Functions inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
ControlledSystem (const ControlledSystem &arg)
virtual ~ControlledSystem ()
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative) override
virtual void computeControlledDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< STATE_DIM, SCALAR > &derivative)=0
ControlVector< CONTROL_DIM, SCALAR > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, SCALAR >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
System (const System &other)
virtual ~System ()
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative)=0
SYSTEM_TYPE getType () const
virtual bool isSymplectic () const
Public Member Functions inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, double >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
ControlledSystem (const ControlledSystem &arg)
virtual ~ControlledSystem ()
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double >> &controller)
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double >> &controller) const
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double > > getController ()
virtual void computeDynamics (const StateVector< STATE_DIM, double > &state, const time_t &t, StateVector< STATE_DIM, double > &derivative) override
virtual void computeControlledDynamics (const StateVector< STATE_DIM, double > &state, const time_t &t, const ControlVector< CONTROL_DIM, double > &control, StateVector< STATE_DIM, double > &derivative)=0
ControlVector< CONTROL_DIM, double > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, double >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
System (const System &other)
virtual ~System ()
virtual void computeDynamics (const StateVector< STATE_DIM, double > &state, const time_t &t, StateVector< STATE_DIM, double > &derivative)=0
SYSTEM_TYPE getType () const
virtual bool isSymplectic () const
Additional Inherited Members
Public Attributes inherited from ct::core::LinearSystem< 36, 12, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem< 36, 12, double > Base
Public Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, SCALAR > Base
Public Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef SCALAR S
Public Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, double > Base
Public Attributes inherited from ct::core::System< STATE_DIM, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef double S
Protected Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
ControlVector< CONTROL_DIM, SCALAR > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
SYSTEM_TYPE type_
Protected Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double > > controller_
ControlVector< CONTROL_DIM, double > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, double >
SYSTEM_TYPE type_
Member Typedef Documentation
typedef ct::core::LinearSystem<36, 12, double> ct::models::HyQ::HyQWithContactModelLinearizedForward::Base
typedef Base::state_vector_t ct::models::HyQ::HyQWithContactModelLinearizedForward::state_vector_t
typedef Base::control_vector_t ct::models::HyQ::HyQWithContactModelLinearizedForward::control_vector_t
typedef Base::state_matrix_t ct::models::HyQ::HyQWithContactModelLinearizedForward::state_matrix_t
typedef Base::state_control_matrix_t ct::models::HyQ::HyQWithContactModelLinearizedForward::state_control_matrix_t
Constructor & Destructor Documentation
ct::models::HyQ::HyQWithContactModelLinearizedForward::HyQWithContactModelLinearizedForward (const ct::core::SYSTEM_TYPE & type = ct::core::SYSTEM_TYPE::GENERAL) inline
Referenced by clone().
ct::models::HyQ::HyQWithContactModelLinearizedForward::HyQWithContactModelLinearizedForward (const HyQWithContactModelLinearizedForward & other) inline
virtual ct::models::HyQ::HyQWithContactModelLinearizedForward::~HyQWithContactModelLinearizedForward () inline virtual
Member Function Documentation
virtual HyQWithContactModelLinearizedForward* ct::models::HyQ::HyQWithContactModelLinearizedForward::clone () const inline override virtual
Implements ct::core::LinearSystem< 36, 12, double >.
References getDerivativeControl(), getDerivativeState(), HyQWithContactModelLinearizedForward(), t, u, and x.
const HyQWithContactModelLinearizedForward::state_matrix_t & ct::models::HyQ::HyQWithContactModelLinearizedForward::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const double t = double(0.0)) override virtual
Referenced by clone().
const HyQWithContactModelLinearizedForward::state_control_matrix_t & ct::models::HyQ::HyQWithContactModelLinearizedForward::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const double t = double(0.0)) override virtual
Referenced by clone().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQWithContactModelLinearizedForward.h
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQWithContactModelLinearizedForward.cpp