ct::models::HyQ::HyQInverseDynJacForward Class Reference
ct::models::HyQ::HyQInverseDynJacForward Class Reference
#include <HyQInverseDynJacForward.h>
Public Types
typedef Eigen::Matrix< double, 18, 54 > JAC_TYPE
typedef Eigen::Matrix< double, 54, 1 > X_TYPE
Public Types inherited from ct::core::Derivatives< 54, 18, double >
typedef Eigen::Matrix< double, 54, 1 > IN_TYPE
typedef Eigen::Matrix< double, 18, 1 > OUT_TYPE
typedef Eigen::Matrix< double, 18, 54 > JAC_TYPE
typedef Eigen::Matrix< double, 54, 54 > HES_TYPE
Public Member Functions
HyQInverseDynJacForward ()
HyQInverseDynJacForward (const HyQInverseDynJacForward &other)
virtual ~HyQInverseDynJacForward ()
HyQInverseDynJacForward * clone () const override
JAC_TYPE jacobian (const Eigen::VectorXd &x_in) override
Public Member Functions inherited from ct::core::Derivatives< 54, 18, double >
Derivatives ()
virtual ~Derivatives ()
virtual OUT_TYPE forwardZero (const Eigen::VectorXd &x)
virtual void sparseJacobian (const Eigen::VectorXd &x, Eigen::VectorXd &jac, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseJacobianValues (const Eigen::VectorXd &x)
virtual HES_TYPE hessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
virtual void sparseHessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda, Eigen::VectorXd &hes, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseHessianValues (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Member Typedef Documentation
typedef Eigen::Matrix<double, 18, 54> ct::models::HyQ::HyQInverseDynJacForward::JAC_TYPE
typedef Eigen::Matrix<double, 54, 1> ct::models::HyQ::HyQInverseDynJacForward::X_TYPE
Constructor & Destructor Documentation
ct::models::HyQ::HyQInverseDynJacForward::HyQInverseDynJacForward () inline
Referenced by clone().
ct::models::HyQ::HyQInverseDynJacForward::HyQInverseDynJacForward (const HyQInverseDynJacForward & other) inline
virtual ct::models::HyQ::HyQInverseDynJacForward::~HyQInverseDynJacForward () inline virtual
Member Function Documentation
HyQInverseDynJacForward* ct::models::HyQ::HyQInverseDynJacForward::clone () const inline override virtual
Implements ct::core::Derivatives< 54, 18, double >.
References HyQInverseDynJacForward(), and jacobian().
HyQInverseDynJacForward::JAC_TYPE ct::models::HyQ::HyQInverseDynJacForward::jacobian (const Eigen::VectorXd & x_in) override virtual
Reimplemented from ct::core::Derivatives< 54, 18, double >.
Referenced by clone(), and timing().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQInverseDynJacForward.h
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQInverseDynJacForward.cpp