iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT > Class Template Reference
iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT > Class Template Reference
#include <forward_dynamics.h>
Public Types
typedef iit::rbd::Core< SCALAR > CoreS
typedef LinkDataMap< typename CoreS::ForceVector > ExtForces
typedef CoreS::ForceVector Force
typedef CoreS::VelocityVector Velocity
typedef CoreS::VelocityVector Acceleration
typedef CoreS::Column6D Column6DS
typedef iit::ct_quadrotor::tpl::JointState< SCALAR > JointState
typedef CoreS::Matrix66 Matrix66S
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > InertiaMatrix
typedef iit::ct_quadrotor::tpl::MotionTransforms< TRAIT > MTransforms
Public Member Functions
ForwardDynamics (iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT > &in, MotionTransforms &tr)
void setJointStatus (const JointState &q) const
Forward dynamics
The Articulated-Body-Algorithm to compute the joint accelerations
void fd (JointState &qdd, Acceleration &body_a, const Velocity &body_v, const Acceleration &g, const JointState &q, const JointState &qd, const JointState &tau, const ExtForces &fext=zeroExtForces)
void fd (JointState &qdd, Acceleration &body_a, const Velocity &body_v, const Acceleration &g, const JointState &qd, const JointState &tau, const ExtForces &fext=zeroExtForces)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar SCALAR
Member Typedef Documentation
template<typename TRAIT > typedef iit::rbd::Core<SCALAR> iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::CoreS
template<typename TRAIT > typedef LinkDataMap<typename CoreS::ForceVector> iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::ExtForces
template<typename TRAIT > typedef CoreS::ForceVector iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::Force
template<typename TRAIT > typedef CoreS::VelocityVector iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::Velocity
template<typename TRAIT > typedef CoreS::VelocityVector iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::Acceleration
template<typename TRAIT > typedef CoreS::Column6D iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::Column6DS
template<typename TRAIT > typedef iit::ct_quadrotor::tpl::JointState<SCALAR> iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::JointState
template<typename TRAIT > typedef CoreS::Matrix66 iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::Matrix66S
template<typename TRAIT > typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::InertiaMatrix
template<typename TRAIT > typedef iit::ct_quadrotor::tpl::MotionTransforms<TRAIT> iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::MTransforms
Constructor & Destructor Documentation
template<typename TRAIT > iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::ForwardDynamics (iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT > & in, MotionTransforms & tr)
Default constructor
Parameters
in the inertia properties of the links
tr the container of all the spatial motion transforms of the robot ct_quadrotor, which will be used by this instance to compute the dynamics.
Member Function Documentation
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::fd (JointState & qdd, Acceleration & body_a, const Velocity & body_v, const Acceleration & g, const JointState & q, const JointState & qd, const JointState & tau, const ExtForces & fext = zeroExtForces) inline
Parameters
qdd the joint accelerations vector (output parameter).
body_a
body_v
g the gravity acceleration vector, expressed in the base coordinates
q the joint status vector
qd the joint velocities vector
tau the joint forces (torque or force)
fext the external forces, optional. Each force must be expressed in the reference frame of the link it is exerted on.
References iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::setJointStatus().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::fd (JointState & qdd, Acceleration & body_a, const Velocity & body_v, const Acceleration & g, const JointState & qd, const JointState & tau, const ExtForces & fext = zeroExtForces)
Parameters
qdd the joint accelerations vector (output parameter).
body_a
body_v
g the gravity acceleration vector, expressed in the base coordinates
q the joint status vector
qd the joint velocities vector
tau the joint forces (torque or force)
fext the external forces, optional. Each force must be expressed in the reference frame of the link it is exerted on.
References iit::rbd::AZ, iit::ct_quadrotor::BODY, iit::rbd::compute_Ia_revolute(), ctransform_Ia_revolute(), iit::ct_quadrotor::JA, iit::ct_quadrotor::JB, iit::ct_quadrotor::LINK1, iit::ct_quadrotor::LINK2, and iit::rbd::vxIv().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::setJointStatus (const JointState & q) const inline
Updates all the kinematics transforms used by this instance.
Referenced by iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::fd().
Member Data Documentation
template<typename TRAIT > EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::ct_quadrotor::dyn::tpl::ForwardDynamics< TRAIT >::SCALAR
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/forward_dynamics.h
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/forward_dynamics.impl.h