iit::ct_HyA::JointDataMap< T > Class Template Reference
iit::ct_HyA::JointDataMap< T > Class Template Reference
#include <joint_data_map.h>
Public Member Functions
JointDataMap ()
JointDataMap (const T &defaultValue)
JointDataMap (const JointDataMap &rhs)
JointDataMap & operator= (const JointDataMap &rhs)
JointDataMap & operator= (const T &rhs)
T & operator[] (JointIdentifiers which)
const T & operator[] (JointIdentifiers which) const
Detailed Description
template<typename T>
class iit::ct_HyA::JointDataMap< T >
A very simple container to associate a generic data item to each joint
Constructor & Destructor Documentation
JointDataMap() [1/3]
template<typename T > iit::ct_HyA::JointDataMap< T >::JointDataMap () inline
References iit::ct_HyA::JointDataMap< T >::operator=(), and iit::ct_HyA::JointDataMap< T >::operator[]().
JointDataMap() [2/3]
template<typename T > iit::ct_HyA::JointDataMap< T >::JointDataMap (const T & defaultValue) inline
JointDataMap() [3/3]
template<typename T > iit::ct_HyA::JointDataMap< T >::JointDataMap (const JointDataMap< T > & rhs) inline
Member Function Documentation
operator=() [1/2]
template<typename T > JointDataMap< T > & iit::ct_HyA::JointDataMap< T >::operator= (const JointDataMap< T > & rhs) inline
Referenced by iit::ct_HyA::JointDataMap< T >::JointDataMap().
operator=() [2/2]
template<typename T > JointDataMap< T > & iit::ct_HyA::JointDataMap< T >::operator= (const T & rhs) inline
operator[]() [1/2]
template<typename T > T & iit::ct_HyA::JointDataMap< T >::operator[] (JointIdentifiers which) inline
Referenced by iit::ct_HyA::JointDataMap< T >::JointDataMap().
operator[]() [2/2]
template<typename T > const T & iit::ct_HyA::JointDataMap< T >::operator[] (JointIdentifiers which) const inline
References iit::ct_HyA::EFE, iit::ct_HyA::HR, iit::ct_HyA::SAA, iit::ct_HyA::SFE, iit::ct_HyA::WFE, and iit::ct_HyA::WR.
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyA/generated/joint_data_map.h