iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
#include <inertia_properties.h>
Public Types
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > IMatrix
typedef Eigen::Matrix< SCALAR, 3, 1 > Vec3d
Public Member Functions
InertiaProperties ()
~InertiaProperties ()
const IMatrix & getTensor_Shoulder_AA () const
const IMatrix & getTensor_Shoulder_FE () const
const IMatrix & getTensor_Humerus_R () const
const IMatrix & getTensor_Elbow_FE () const
const IMatrix & getTensor_Wrist_R () const
const IMatrix & getTensor_Wrist_FE () const
SCALAR getMass_Shoulder_AA () const
SCALAR getMass_Shoulder_FE () const
SCALAR getMass_Humerus_R () const
SCALAR getMass_Elbow_FE () const
SCALAR getMass_Wrist_R () const
SCALAR getMass_Wrist_FE () const
const Vec3d & getCOM_Shoulder_AA () const
const Vec3d & getCOM_Shoulder_FE () const
const Vec3d & getCOM_Humerus_R () const
const Vec3d & getCOM_Elbow_FE () const
const Vec3d & getCOM_Wrist_R () const
const Vec3d & getCOM_Wrist_FE () const
SCALAR getTotalMass () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar SCALAR
Member Typedef Documentation
IMatrix
template<typename TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::IMatrix
Vec3d
template<typename TRAIT> typedef Eigen::Matrix<SCALAR, 3, 1> iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::Vec3d
Constructor & Destructor Documentation
InertiaProperties()
template<typename TRAIT > iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::InertiaProperties ()
~InertiaProperties()
template<typename TRAIT > iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::~InertiaProperties () inline
Member Function Documentation
getTensor_Shoulder_AA()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Shoulder_AA () const inline
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::update().
getTensor_Shoulder_FE()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Shoulder_FE () const inline
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::update().
getTensor_Humerus_R()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Humerus_R () const inline
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::update().
getTensor_Elbow_FE()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Elbow_FE () const inline
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::update().
getTensor_Wrist_R()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Wrist_R () const inline
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::update().
getTensor_Wrist_FE()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Wrist_FE () const inline
getMass_Shoulder_AA()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getMass_Shoulder_AA () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_Shoulder_FE()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getMass_Shoulder_FE () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_Humerus_R()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getMass_Humerus_R () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_Elbow_FE()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getMass_Elbow_FE () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_Wrist_R()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getMass_Wrist_R () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_Wrist_FE()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getMass_Wrist_FE () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getCOM_Shoulder_AA()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Shoulder_AA () const inline
getCOM_Shoulder_FE()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Shoulder_FE () const inline
getCOM_Humerus_R()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Humerus_R () const inline
getCOM_Elbow_FE()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Elbow_FE () const inline
getCOM_Wrist_R()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Wrist_R () const inline
getCOM_Wrist_FE()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Wrist_FE () const inline
getTotalMass()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTotalMass () const inline
Member Data Documentation
SCALAR
template<typename TRAIT> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::SCALAR
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyA/generated/inertia_properties.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyA/generated/inertia_properties.impl.h