iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT > Class Template Reference
iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT > Class Template Reference
#include <jsim.h>
Public Types
typedef TRAIT::Scalar SCALAR
typedef Base::Index Index
typedef Eigen::Matrix< SCALAR, 8, 8 > MatrixType
typedef const Eigen::Block< const MatrixType, 6, 2 > BlockF_t
typedef const Eigen::Block< const MatrixType, 2, 2 > BlockFixedBase_t
typedef InertiaProperties< TRAIT > IProperties
typedef iit::ct_quadrotor::tpl::ForceTransforms< TRAIT > FTransforms
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > InertiaMatrix
Public Types inherited from iit::rbd::StateDependentMatrix< iit::ct_quadrotor::JointState, 8, 8, JSIM< TRAIT > >
typedef Base::Index Index
typedef Base MatrixType
Public Member Functions
JSIM (IProperties &, FTransforms &)
~JSIM ()
const JSIM & update (const iit::ct_quadrotor::JointState &)
void computeL ()
void computeInverse ()
const MatrixType & getL () const
const MatrixType & getInverse () const
const InertiaMatrix & getWholeBodyInertia () const
const BlockF_t getF () const
const BlockFixedBase_t getFixedBaseBlock () const
Public Member Functions inherited from iit::rbd::StateDependentMatrix< iit::ct_quadrotor::JointState, 8, 8, JSIM< TRAIT > >
StateDependentMatrix ()
~StateDependentMatrix ()
StateDependentMatrix & operator= (const MatrixBase< OtherDerived > &other)
Public Member Functions inherited from iit::rbd::StateDependentBase< iit::ct_quadrotor::JointState, JSIM< TRAIT > >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW const JSIM< TRAIT > & operator() (iit::ct_quadrotor::JointStateconst &state)
const JSIM< TRAIT > & update (iit::ct_quadrotor::JointStateconst &state)
Protected Member Functions
void computeLInverse ()
Additional Inherited Members
Public Attributes inherited from iit::rbd::StateDependentMatrix< iit::ct_quadrotor::JointState, 8, 8, JSIM< TRAIT > >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Base::Scalar Scalar
Detailed Description
template<class TRAIT>
class iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >
The type of the Joint Space Inertia Matrix (JSIM) of the robot ct_quadrotor.
Member Typedef Documentation
template<class TRAIT> typedef TRAIT::Scalar iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::SCALAR
template<class TRAIT> typedef Base::Index iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::Index
template<class TRAIT> typedef Eigen::Matrix<SCALAR,8,8> iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::MatrixType
template<class TRAIT> typedef const Eigen::Block<const MatrixType,6,2> iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::BlockF_t
The type of the F sub-block of the floating-base JSIM
template<class TRAIT> typedef const Eigen::Block<const MatrixType,2,2> iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::BlockFixedBase_t
The type of the fixed-base sub-block of the JSIM
template<class TRAIT> typedef InertiaProperties<TRAIT> iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::IProperties
template<class TRAIT> typedef iit::ct_quadrotor::tpl::ForceTransforms<TRAIT> iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::FTransforms
template<class TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::InertiaMatrix
Constructor & Destructor Documentation
template<typename TRAIT > iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::JSIM (IProperties & inertiaProperties, FTransforms & forceTransforms)
template<class TRAIT> iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM () inline
References iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::computeInverse(), iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::computeL(), iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::computeLInverse(), iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getF(), iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getFixedBaseBlock(), iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getInverse(), iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getL(), iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getWholeBodyInertia(), and iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::update().
Member Function Documentation
template<typename TRAIT > const iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT > & iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::update (const iit::ct_quadrotor::JointState & state)
References iit::rbd::AZ, DATA, F, Fcol, iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getTensor_body(), iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link1(), iit::ct_quadrotor::JA, iit::ct_quadrotor::JB, and iit::rbd::transformInertia().
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::computeL ()
Computes and saves the matrix L of the L^T L factorization of this JSIM.
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::computeInverse ()
Computes and saves the inverse of this JSIM. This function assumes that computeL() has been called already, since it uses L to compute the inverse. The algorithm takes advantage of the branch induced sparsity of the robot, if any.
References iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::computeLInverse().
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<class TRAIT > const JSIM< TRAIT >::MatrixType & iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getL () const inline
Returns an unmodifiable reference to the matrix L. See also computeL()
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<class TRAIT > const JSIM< TRAIT >::MatrixType & iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getInverse () const inline
Returns an unmodifiable reference to the inverse of this JSIM
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<class TRAIT > const JSIM< TRAIT >::InertiaMatrix & iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getWholeBodyInertia () const inline
The spatial composite-inertia tensor of the robot base, ie the inertia of the whole robot for the current configuration. According to the convention of this class about the layout of the floating-base JSIM, this tensor is the 6x6 upper left corner of the JSIM itself.
Returns
the 6x6 InertiaMatrix that correspond to the spatial inertia tensor of the whole robot, according to the last joints configuration used to update this JSIM
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<class TRAIT > const JSIM< TRAIT >::BlockF_t iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getF () const inline
The matrix that maps accelerations in the actual joints of the robot to the spatial force acting on the floating-base of the robot. This matrix is the F sub-block of the JSIM in Featherstone's notation.
Returns
the 6x2 upper right block of this JSIM
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<class TRAIT > const JSIM< TRAIT >::BlockFixedBase_t iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::getFixedBaseBlock () const inline
The submatrix of this JSIM related only to the actual joints of the robot (as for a fixed-base robot). This matrix is the H sub-block of the JSIM in Featherstone's notation.
Returns
the 2x2 lower right block of this JSIM, which correspond to the fixed-base JSIM
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::computeLInverse () protected
Computes and saves the inverse of the matrix L. See also computeL()
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::computeInverse(), and iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::~JSIM().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/jsim.h
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/jsim.impl.h