iit::HyQ::JointDataMap< T > Class Template Reference
iit::HyQ::JointDataMap< T > Class Template Reference
#include <joint_data_map.h>
Public Member Functions
JointDataMap ()
JointDataMap (const T &defaultValue)
JointDataMap (const JointDataMap &rhs)
JointDataMap & operator= (const JointDataMap &rhs)
JointDataMap & operator= (const T &rhs)
T & operator[] (JointIdentifiers which)
const T & operator[] (JointIdentifiers which) const
Detailed Description
template<typename T>
class iit::HyQ::JointDataMap< T >
A very simple container to associate a generic data item to each joint
Constructor & Destructor Documentation
template<typename T > iit::HyQ::JointDataMap< T >::JointDataMap () inline
References iit::HyQ::JointDataMap< T >::operator=(), and iit::HyQ::JointDataMap< T >::operator[]().
template<typename T > iit::HyQ::JointDataMap< T >::JointDataMap (const T & defaultValue) inline
template<typename T > iit::HyQ::JointDataMap< T >::JointDataMap (const JointDataMap< T > & rhs) inline
Member Function Documentation
template<typename T > JointDataMap< T > & iit::HyQ::JointDataMap< T >::operator= (const JointDataMap< T > & rhs) inline
Referenced by iit::HyQ::JointDataMap< T >::JointDataMap().
template<typename T > JointDataMap< T > & iit::HyQ::JointDataMap< T >::operator= (const T & rhs) inline
template<typename T > T & iit::HyQ::JointDataMap< T >::operator[] (JointIdentifiers which) inline
Referenced by iit::HyQ::JointDataMap< T >::JointDataMap().
template<typename T > const T & iit::HyQ::JointDataMap< T >::operator[] (JointIdentifiers which) const inline
References iit::HyQ::LF_HAA, iit::HyQ::LF_HFE, iit::HyQ::LF_KFE, iit::HyQ::LH_HAA, iit::HyQ::LH_HFE, iit::HyQ::LH_KFE, iit::HyQ::RF_HAA, iit::HyQ::RF_HFE, iit::HyQ::RF_KFE, iit::HyQ::RH_HAA, iit::HyQ::RH_HFE, and iit::HyQ::RH_KFE.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyQ/generated/joint_data_map.h