ct::models::HyA::HyAInverseDynJacForward Class Reference
ct::models::HyA::HyAInverseDynJacForward Class Reference
#include <HyAInverseDynJacForward.h>
Public Types
typedef Eigen::Matrix< double, 6, 12 > JAC_TYPE
typedef Eigen::Matrix< double, 12, 1 > X_TYPE
Public Types inherited from ct::core::Derivatives< 12, 6, double >
typedef Eigen::Matrix< double, 12, 1 > IN_TYPE
typedef Eigen::Matrix< double, 6, 1 > OUT_TYPE
typedef Eigen::Matrix< double, 6, 12 > JAC_TYPE
typedef Eigen::Matrix< double, 12, 12 > HES_TYPE
Public Member Functions
HyAInverseDynJacForward ()
HyAInverseDynJacForward (const HyAInverseDynJacForward &other)
virtual ~HyAInverseDynJacForward ()
HyAInverseDynJacForward * clone () const override
JAC_TYPE jacobian (const Eigen::VectorXd &x_in) override
Public Member Functions inherited from ct::core::Derivatives< 12, 6, double >
Derivatives ()
virtual ~Derivatives ()
virtual OUT_TYPE forwardZero (const Eigen::VectorXd &x)
virtual void sparseJacobian (const Eigen::VectorXd &x, Eigen::VectorXd &jac, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseJacobianValues (const Eigen::VectorXd &x)
virtual HES_TYPE hessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
virtual void sparseHessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda, Eigen::VectorXd &hes, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseHessianValues (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Member Typedef Documentation
JAC_TYPE
typedef Eigen::Matrix<double, 6, 12> ct::models::HyA::HyAInverseDynJacForward::JAC_TYPE
X_TYPE
typedef Eigen::Matrix<double, 12, 1> ct::models::HyA::HyAInverseDynJacForward::X_TYPE
Constructor & Destructor Documentation
HyAInverseDynJacForward() [1/2]
ct::models::HyA::HyAInverseDynJacForward::HyAInverseDynJacForward () inline
Referenced by clone().
HyAInverseDynJacForward() [2/2]
ct::models::HyA::HyAInverseDynJacForward::HyAInverseDynJacForward (const HyAInverseDynJacForward & other) inline
~HyAInverseDynJacForward()
virtual ct::models::HyA::HyAInverseDynJacForward::~HyAInverseDynJacForward () inline virtual
Member Function Documentation
clone()
HyAInverseDynJacForward* ct::models::HyA::HyAInverseDynJacForward::clone () const inline override virtual
Implements ct::core::Derivatives< 12, 6, double >.
References HyAInverseDynJacForward(), and jacobian().
jacobian()
HyAInverseDynJacForward::JAC_TYPE ct::models::HyA::HyAInverseDynJacForward::jacobian (const Eigen::VectorXd & x_in) override virtual
Reimplemented from ct::core::Derivatives< 12, 6, double >.
Referenced by clone(), and timingInverseDynamics().
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyA/codegen/HyAInverseDynJacForward.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyA/codegen/HyAInverseDynJacForward.cpp