iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT > Class Template Reference
iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT > Class Template Reference
#include <jsim.h>
Public Types
typedef TRAIT::Scalar Scalar
typedef iit::ct_DoubleInvertedPendulum::tpl::JointState< Scalar > JointState
typedef iit::rbd::Core< Scalar > CoreS
typedef Base::Index Index
typedef iit::rbd::PlainMatrix< Scalar, 2, 2 > MatrixType
typedef InertiaProperties< TRAIT > IProperties
typedef iit::ct_DoubleInvertedPendulum::tpl::ForceTransforms< TRAIT > FTransforms
typedef iit::rbd::tpl::InertiaMatrixDense< Scalar > InertiaMatrix
typedef CoreS::ForceVector ForceVector
Public Types inherited from iit::rbd::StateDependentMatrix< iit::ct_DoubleInvertedPendulum::tpl::JointState< TRAIT::Scalar >, 2, 2, JSIM< TRAIT > >
typedef Base::Index Index
typedef Base MatrixType
Public Member Functions
JSIM (IProperties &, FTransforms &)
~JSIM ()
const JSIM & update (const JointState &)
void computeL ()
void computeInverse ()
const MatrixType & getL () const
const MatrixType & getInverse () const
Public Member Functions inherited from iit::rbd::StateDependentMatrix< iit::ct_DoubleInvertedPendulum::tpl::JointState< TRAIT::Scalar >, 2, 2, JSIM< TRAIT > >
StateDependentMatrix ()
~StateDependentMatrix ()
StateDependentMatrix & operator= (const MatrixBase< OtherDerived > &other)
Public Member Functions inherited from iit::rbd::StateDependentBase< iit::ct_DoubleInvertedPendulum::tpl::JointState< TRAIT::Scalar >, JSIM< TRAIT > >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW const JSIM< TRAIT > & operator() (iit::ct_DoubleInvertedPendulum::tpl::JointState< TRAIT::Scalar > const &state)
const JSIM< TRAIT > & update (iit::ct_DoubleInvertedPendulum::tpl::JointState< TRAIT::Scalar > const &state)
Protected Member Functions
void computeLInverse ()
Additional Inherited Members
Public Attributes inherited from iit::rbd::StateDependentMatrix< iit::ct_DoubleInvertedPendulum::tpl::JointState< TRAIT::Scalar >, 2, 2, JSIM< TRAIT > >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Base::Scalar Scalar
Detailed Description
template<typename TRAIT>
class iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >
The type of the Joint Space Inertia Matrix (JSIM) of the robot ct_DoubleInvertedPendulum.
Member Typedef Documentation
Scalar
template<typename TRAIT> typedef TRAIT::Scalar iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::Scalar
JointState
template<typename TRAIT> typedef iit::ct_DoubleInvertedPendulum::tpl::JointState<Scalar> iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::JointState
CoreS
template<typename TRAIT> typedef iit::rbd::Core<Scalar> iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::CoreS
Index
template<typename TRAIT> typedef Base::Index iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::Index
MatrixType
template<typename TRAIT> typedef iit::rbd::PlainMatrix<Scalar, 2, 2> iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::MatrixType
IProperties
template<typename TRAIT> typedef InertiaProperties<TRAIT> iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::IProperties
FTransforms
template<typename TRAIT> typedef iit::ct_DoubleInvertedPendulum::tpl::ForceTransforms<TRAIT> iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::FTransforms
InertiaMatrix
template<typename TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<Scalar> iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::InertiaMatrix
ForceVector
template<typename TRAIT> typedef CoreS::ForceVector iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::ForceVector
Constructor & Destructor Documentation
JSIM()
template<typename TRAIT > iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::JSIM (IProperties & inertiaProperties, FTransforms & forceTransforms)
~JSIM()
template<typename TRAIT> iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::~JSIM () inline
References iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::computeInverse(), iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::computeL(), iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::computeLInverse(), iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::getInverse(), iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::getL(), and iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::update().
Member Function Documentation
update()
template<typename TRAIT > const iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT > & iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::update (const JointState & state)
References iit::rbd::AZ, DATA, F, iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Link1(), iit::ct_DoubleInvertedPendulum::JOINT1, and iit::ct_DoubleInvertedPendulum::JOINT2.
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::~JSIM().
computeL()
template<typename TRAIT > void iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::computeL ()
Computes and saves the matrix L of the L^T L factorization of this JSIM.
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::~JSIM().
computeInverse()
template<typename TRAIT > void iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::computeInverse ()
Computes and saves the inverse of this JSIM. This function assumes that computeL() has been called already, since it uses L to compute the inverse. The algorithm takes advantage of the branch induced sparsity of the robot, if any.
References iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::computeLInverse().
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::~JSIM().
getL()
template<typename TRAIT > const JSIM< TRAIT >::MatrixType & iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::getL () const inline
Returns an unmodifiable reference to the matrix L. See also computeL()
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::~JSIM().
getInverse()
template<typename TRAIT > const JSIM< TRAIT >::MatrixType & iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::getInverse () const inline
Returns an unmodifiable reference to the inverse of this JSIM
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::~JSIM().
computeLInverse()
template<typename TRAIT > void iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::computeLInverse () protected
Computes and saves the inverse of the matrix L. See also computeL()
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::computeInverse(), and iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::~JSIM().
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/DoubleInvertedPendulum/generated/jsim.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/DoubleInvertedPendulum/generated/jsim.impl.h