iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT > Class Template Reference
iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT > Class Template Reference
#include <forward_dynamics.h>
Public Types
typedef iit::rbd::Core< Scalar > CoreS
typedef CoreS::ForceVector Force
typedef CoreS::VelocityVector Velocity
typedef CoreS::VelocityVector Acceleration
typedef CoreS::Column6D Column6DS
typedef CoreS::Matrix66 Matrix66S
typedef LinkDataMap< Force > ExtForces
typedef iit::ct_DoubleInvertedPendulum::tpl::JointState< Scalar > JointState
typedef iit::ct_DoubleInvertedPendulum::tpl::MotionTransforms< TRAIT > MTransforms
Public Member Functions
ForwardDynamics (InertiaProperties< TRAIT > &in, MTransforms &tr)
void setJointStatus (const JointState &q) const
Forward dynamics
The Articulated-Body-Algorithm to compute the joint accelerations
void fd (JointState &qdd, const JointState &q, const JointState &qd, const JointState &tau, const ExtForces &fext=zeroExtForces)
void fd (JointState &qdd, const JointState &qd, const JointState &tau, const ExtForces &fext=zeroExtForces)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar Scalar
Member Typedef Documentation
CoreS
template<typename TRAIT > typedef iit::rbd::Core<Scalar> iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::CoreS
Force
template<typename TRAIT > typedef CoreS::ForceVector iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::Force
Velocity
template<typename TRAIT > typedef CoreS::VelocityVector iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::Velocity
Acceleration
template<typename TRAIT > typedef CoreS::VelocityVector iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::Acceleration
Column6DS
template<typename TRAIT > typedef CoreS::Column6D iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::Column6DS
Matrix66S
template<typename TRAIT > typedef CoreS::Matrix66 iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::Matrix66S
ExtForces
template<typename TRAIT > typedef LinkDataMap<Force> iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::ExtForces
JointState
template<typename TRAIT > typedef iit::ct_DoubleInvertedPendulum::tpl::JointState<Scalar> iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::JointState
MTransforms
template<typename TRAIT > typedef iit::ct_DoubleInvertedPendulum::tpl::MotionTransforms<TRAIT> iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::MTransforms
Constructor & Destructor Documentation
ForwardDynamics()
template<typename TRAIT > iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::ForwardDynamics (InertiaProperties< TRAIT > & in, MTransforms & tr)
Default constructor
Parameters
in the inertia properties of the links
tr the container of all the spatial motion transforms of the robot ct_DoubleInvertedPendulum, which will be used by this instance to compute the dynamics.
Member Function Documentation
fd() [1/2]
template<typename TRAIT > void iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::fd (JointState & qdd, const JointState & q, const JointState & qd, const JointState & tau, const ExtForces & fext = zeroExtForces) inline
Parameters
qdd the joint accelerations vector (output parameter).
q the joint status vector
qd the joint velocities vector
tau the joint forces (torque or force)
fext the external forces, optional. Each force must be expressed in the reference frame of the link it is exerted on.
References iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::setJointStatus().
fd() [2/2]
template<typename TRAIT > void iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::fd (JointState & qdd, const JointState & qd, const JointState & tau, const ExtForces & fext = zeroExtForces)
Parameters
qdd the joint accelerations vector (output parameter).
q the joint status vector
qd the joint velocities vector
tau the joint forces (torque or force)
fext the external forces, optional. Each force must be expressed in the reference frame of the link it is exerted on.
References iit::rbd::AZ, iit::rbd::compute_Ia_revolute(), ctransform_Ia_revolute(), iit::ct_DoubleInvertedPendulum::JOINT1, iit::ct_DoubleInvertedPendulum::JOINT2, iit::ct_DoubleInvertedPendulum::LINK1, iit::ct_DoubleInvertedPendulum::LINK2, iit::rbd::LZ, iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::Scalar, and iit::rbd::vxIv().
setJointStatus()
template<typename TRAIT > void iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::setJointStatus (const JointState & q) const inline
Updates all the kinematics transforms used by this instance.
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::fd().
Member Data Documentation
Scalar
template<typename TRAIT > EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::Scalar
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::ForwardDynamics< TRAIT >::fd().
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/DoubleInvertedPendulum/generated/forward_dynamics.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/DoubleInvertedPendulum/generated/forward_dynamics.impl.h