iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT > Class Template Reference
iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT > Class Template Reference
#include <inverse_dynamics.h>
Public Types
typedef iit::rbd::Core< SCALAR > CoreS
typedef CoreS::ForceVector Force
typedef LinkDataMap< Force > ExtForces
typedef CoreS::VelocityVector Velocity
typedef CoreS::VelocityVector Acceleration
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > InertiaMatrix
typedef iit::ct_HyA::tpl::JointState< SCALAR > JointState
typedef CoreS::Matrix66 Matrix66s
typedef iit::ct_HyA::tpl::MotionTransforms< TRAIT > MTransforms
typedef InertiaProperties< TRAIT > IProperties
Public Member Functions
InverseDynamics (IProperties &in, MTransforms &tr)
void setJointStatus (const JointState &q) const
Inverse dynamics
The full Newton-Euler algorithm for the inverse dynamics of this robot.
Parameters
[out] jForces the joint force vector required to achieve the desired accelerations
[in] q the joint position vector
[in] qd the joint velocity vector
[in] qdd the desired joint acceleration vector
[in] fext the external forces acting on the links; this parameters defaults to zero
void id (JointState &jForces, const JointState &q, const JointState &qd, const JointState &qdd, const ExtForces &fext=zeroExtForces)
void id (JointState &jForces, const JointState &qd, const JointState &qdd, const ExtForces &fext=zeroExtForces)
Gravity terms
The joint forces (linear or rotational) required to compensate for the effect of gravity, in a specific configuration.
void G_terms (JointState &jForces, const JointState &q)
void G_terms (JointState &jForces)
Centrifugal and Coriolis terms
The forces (linear or rotational) acting on the joints due to centrifugal and Coriolis effects, for a specific configuration.
void C_terms (JointState &jForces, const JointState &q, const JointState &qd)
void C_terms (JointState &jForces, const JointState &qd)
Getters
These functions return various spatial quantities used internally by the inverse dynamics routines, like the spatial acceleration of the links.
The getters can be useful to retrieve the additional data that is not returned explicitly by the inverse dynamics routines even though it is computed. For example, after a call to the inverse dynamics, the spatial velocity of all the links has been determined and can be accessed.
However, beware that certain routines might not use some of the spatial quantities, which therefore would retain their last value without being updated nor reset (for example, the spatial velocity of the links is unaffected by the computation of the gravity terms).
const Velocity & getVelocity_Shoulder_AA () const
const Acceleration & getAcceleration_Shoulder_AA () const
const Force & getForce_Shoulder_AA () const
const Velocity & getVelocity_Shoulder_FE () const
const Acceleration & getAcceleration_Shoulder_FE () const
const Force & getForce_Shoulder_FE () const
const Velocity & getVelocity_Humerus_R () const
const Acceleration & getAcceleration_Humerus_R () const
const Force & getForce_Humerus_R () const
const Velocity & getVelocity_Elbow_FE () const
const Acceleration & getAcceleration_Elbow_FE () const
const Force & getForce_Elbow_FE () const
const Velocity & getVelocity_Wrist_R () const
const Acceleration & getAcceleration_Wrist_R () const
const Force & getForce_Wrist_R () const
const Velocity & getVelocity_Wrist_FE () const
const Acceleration & getAcceleration_Wrist_FE () const
const Force & getForce_Wrist_FE () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar SCALAR
Protected Member Functions
void firstPass (const JointState &qd, const JointState &qdd, const ExtForces &fext)
void secondPass (JointState &jForces)
Member Typedef Documentation
CoreS
template<typename TRAIT > typedef iit::rbd::Core<SCALAR> iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::CoreS
Force
template<typename TRAIT > typedef CoreS::ForceVector iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::Force
ExtForces
template<typename TRAIT > typedef LinkDataMap<Force> iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::ExtForces
Velocity
template<typename TRAIT > typedef CoreS::VelocityVector iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::Velocity
Acceleration
template<typename TRAIT > typedef CoreS::VelocityVector iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::Acceleration
InertiaMatrix
template<typename TRAIT > typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::InertiaMatrix
JointState
template<typename TRAIT > typedef iit::ct_HyA::tpl::JointState<SCALAR> iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::JointState
Matrix66s
template<typename TRAIT > typedef CoreS::Matrix66 iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::Matrix66s
MTransforms
template<typename TRAIT > typedef iit::ct_HyA::tpl::MotionTransforms<TRAIT> iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::MTransforms
IProperties
template<typename TRAIT > typedef InertiaProperties<TRAIT> iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::IProperties
Constructor & Destructor Documentation
InverseDynamics()
template<typename TRAIT > iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::InverseDynamics (IProperties & in, MTransforms & tr)
Default constructor
Parameters
in the inertia properties of the links
tr the container of all the spatial motion transforms of the robot ct_HyA, which will be used by this instance to compute inverse-dynamics.
Member Function Documentation
id() [1/2]
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::id (JointState & jForces, const JointState & q, const JointState & qd, const JointState & qdd, const ExtForces & fext = zeroExtForces) inline
References iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus().
id() [2/2]
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::id (JointState & jForces, const JointState & qd, const JointState & qdd, const ExtForces & fext = zeroExtForces)
References iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::firstPass(), and iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::secondPass().
G_terms() [1/2]
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::G_terms (JointState & jForces, const JointState & q) inline
References iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus().
G_terms() [2/2]
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::G_terms (JointState & jForces)
References iit::rbd::LZ, iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::SCALAR, and iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::secondPass().
C_terms() [1/2]
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::C_terms (JointState & jForces, const JointState & q, const JointState & qd) inline
References iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus().
C_terms() [2/2]
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::C_terms (JointState & jForces, const JointState & qd)
References iit::rbd::AZ, iit::ct_HyA::EFE, iit::ct_HyA::HR, iit::ct_HyA::SAA, iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::secondPass(), iit::ct_HyA::SFE, iit::rbd::vxIv(), iit::ct_HyA::WFE, and iit::ct_HyA::WR.
setJointStatus()
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus (const JointState & q) const inline
Updates all the kinematics transforms used by the inverse dynamics routine.
Referenced by iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::C_terms(), iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::G_terms(), and iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::id().
getVelocity_Shoulder_AA()
template<typename TRAIT > const Velocity& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getVelocity_Shoulder_AA () const inline
getAcceleration_Shoulder_AA()
template<typename TRAIT > const Acceleration& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getAcceleration_Shoulder_AA () const inline
getForce_Shoulder_AA()
template<typename TRAIT > const Force& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getForce_Shoulder_AA () const inline
getVelocity_Shoulder_FE()
template<typename TRAIT > const Velocity& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getVelocity_Shoulder_FE () const inline
getAcceleration_Shoulder_FE()
template<typename TRAIT > const Acceleration& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getAcceleration_Shoulder_FE () const inline
getForce_Shoulder_FE()
template<typename TRAIT > const Force& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getForce_Shoulder_FE () const inline
getVelocity_Humerus_R()
template<typename TRAIT > const Velocity& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getVelocity_Humerus_R () const inline
getAcceleration_Humerus_R()
template<typename TRAIT > const Acceleration& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getAcceleration_Humerus_R () const inline
getForce_Humerus_R()
template<typename TRAIT > const Force& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getForce_Humerus_R () const inline
getVelocity_Elbow_FE()
template<typename TRAIT > const Velocity& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getVelocity_Elbow_FE () const inline
getAcceleration_Elbow_FE()
template<typename TRAIT > const Acceleration& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getAcceleration_Elbow_FE () const inline
getForce_Elbow_FE()
template<typename TRAIT > const Force& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getForce_Elbow_FE () const inline
getVelocity_Wrist_R()
template<typename TRAIT > const Velocity& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getVelocity_Wrist_R () const inline
getAcceleration_Wrist_R()
template<typename TRAIT > const Acceleration& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getAcceleration_Wrist_R () const inline
getForce_Wrist_R()
template<typename TRAIT > const Force& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getForce_Wrist_R () const inline
getVelocity_Wrist_FE()
template<typename TRAIT > const Velocity& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getVelocity_Wrist_FE () const inline
getAcceleration_Wrist_FE()
template<typename TRAIT > const Acceleration& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getAcceleration_Wrist_FE () const inline
getForce_Wrist_FE()
template<typename TRAIT > const Force& iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getForce_Wrist_FE () const inline
References iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::firstPass(), and iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::secondPass().
firstPass()
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::firstPass (const JointState & qd, const JointState & qdd, const ExtForces & fext) protected
References iit::rbd::AZ, iit::ct_HyA::EFE, iit::ct_HyA::ELBOW_FE, iit::ct_HyA::HR, iit::ct_HyA::HUMERUS_R, iit::rbd::LZ, iit::ct_HyA::SAA, iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::SCALAR, iit::ct_HyA::SFE, iit::ct_HyA::SHOULDER_AA, iit::ct_HyA::SHOULDER_FE, iit::rbd::vxIv(), iit::ct_HyA::WFE, iit::ct_HyA::WR, iit::ct_HyA::WRIST_FE, and iit::ct_HyA::WRIST_R.
Referenced by iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getForce_Wrist_FE(), and iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::id().
secondPass()
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::secondPass (JointState & jForces) protected
References iit::rbd::AZ, iit::ct_HyA::EFE, iit::ct_HyA::HR, iit::ct_HyA::SAA, iit::ct_HyA::SFE, iit::ct_HyA::WFE, and iit::ct_HyA::WR.
Referenced by iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::C_terms(), iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::G_terms(), iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::getForce_Wrist_FE(), and iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::id().
Member Data Documentation
SCALAR
template<typename TRAIT > EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::SCALAR
Referenced by iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::firstPass(), and iit::ct_HyA::dyn::tpl::InverseDynamics< TRAIT >::G_terms().
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyA/generated/inverse_dynamics.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyA/generated/inverse_dynamics.impl.h