iit::ct_HyA::dyn::tpl::JSIM< TRAIT > Class Template Reference
iit::ct_HyA::dyn::tpl::JSIM< TRAIT > Class Template Reference
#include <jsim.h>
Public Types
typedef TRAIT::Scalar SCALAR
typedef Base::Index Index
typedef Eigen::Matrix< SCALAR, 6, 6 > MatrixType
typedef InertiaProperties< TRAIT > IProperties
typedef iit::ct_HyA::tpl::ForceTransforms< TRAIT > FTransforms
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > InertiaMatrix
typedef iit::ct_HyA::tpl::JointState< SCALAR > JointState
typedef iit::rbd::Core< SCALAR >::ForceVector ForceVector
Public Types inherited from iit::rbd::StateDependentMatrix< iit::ct_HyA::tpl::JointState< TRAIT::Scalar >, 6, 6, JSIM< TRAIT > >
typedef Base::Index Index
typedef Base MatrixType
Public Member Functions
JSIM (IProperties &, FTransforms &)
~JSIM ()
const JSIM & update (const JointState &)
void computeL ()
void computeInverse ()
const MatrixType & getL () const
const MatrixType & getInverse () const
Public Member Functions inherited from iit::rbd::StateDependentMatrix< iit::ct_HyA::tpl::JointState< TRAIT::Scalar >, 6, 6, JSIM< TRAIT > >
StateDependentMatrix ()
~StateDependentMatrix ()
StateDependentMatrix & operator= (const MatrixBase< OtherDerived > &other)
Public Member Functions inherited from iit::rbd::StateDependentBase< iit::ct_HyA::tpl::JointState< TRAIT::Scalar >, JSIM< TRAIT > >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW const JSIM< TRAIT > & operator() (iit::ct_HyA::tpl::JointState< TRAIT::Scalar >const &state)
const JSIM< TRAIT > & update (iit::ct_HyA::tpl::JointState< TRAIT::Scalar >const &state)
Protected Member Functions
void computeLInverse ()
Additional Inherited Members
Public Attributes inherited from iit::rbd::StateDependentMatrix< iit::ct_HyA::tpl::JointState< TRAIT::Scalar >, 6, 6, JSIM< TRAIT > >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Base::Scalar Scalar
Detailed Description
template<class TRAIT>
class iit::ct_HyA::dyn::tpl::JSIM< TRAIT >
The type of the Joint Space Inertia Matrix (JSIM) of the robot ct_HyA.
Member Typedef Documentation
template<class TRAIT> typedef TRAIT::Scalar iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::SCALAR
template<class TRAIT> typedef Base::Index iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::Index
template<class TRAIT> typedef Eigen::Matrix<SCALAR,6,6> iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::MatrixType
template<class TRAIT> typedef InertiaProperties<TRAIT> iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::IProperties
template<class TRAIT> typedef iit::ct_HyA::tpl::ForceTransforms<TRAIT> iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::FTransforms
template<class TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::InertiaMatrix
template<class TRAIT> typedef iit::ct_HyA::tpl::JointState<SCALAR> iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::JointState
template<class TRAIT> typedef iit::rbd::Core<SCALAR>::ForceVector iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::ForceVector
Constructor & Destructor Documentation
template<typename TRAIT > iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::JSIM (IProperties & inertiaProperties, FTransforms & forceTransforms)
template<class TRAIT> iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::~JSIM () inline
References iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::computeInverse(), iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::computeL(), iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::computeLInverse(), iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::getInverse(), iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::getL(), and iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::update().
Member Function Documentation
template<typename TRAIT > const iit::ct_HyA::dyn::tpl::JSIM< TRAIT > & iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::update (const JointState & state)
References iit::rbd::AZ, DATA, iit::ct_HyA::EFE, F, iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Elbow_FE(), iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Humerus_R(), iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Shoulder_AA(), iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Shoulder_FE(), iit::ct_HyA::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Wrist_R(), iit::ct_HyA::HR, iit::ct_HyA::SAA, iit::ct_HyA::SFE, iit::rbd::transformInertia(), iit::ct_HyA::WFE, and iit::ct_HyA::WR.
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::computeL ()
Computes and saves the matrix L of the L^T L factorization of this JSIM.
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::computeInverse ()
Computes and saves the inverse of this JSIM. This function assumes that computeL() has been called already, since it uses L to compute the inverse. The algorithm takes advantage of the branch induced sparsity of the robot, if any.
References iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::computeLInverse().
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<class TRAIT > const JSIM< TRAIT >::MatrixType & iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::getL () const inline
Returns an unmodifiable reference to the matrix L. See also computeL()
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<class TRAIT > const JSIM< TRAIT >::MatrixType & iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::getInverse () const inline
Returns an unmodifiable reference to the inverse of this JSIM
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::~JSIM().
template<typename TRAIT > void iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::computeLInverse () protected
Computes and saves the inverse of the matrix L. See also computeL()
Referenced by iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::computeInverse(), and iit::ct_HyA::dyn::tpl::JSIM< TRAIT >::~JSIM().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyA/generated/jsim.h
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyA/generated/jsim.impl.h