ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION > Class Template Reference
ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION > Class Template Reference
#include <QuadrotorWithLoadFDSystem.h>
Public Types
using Dynamics = RBDDynamics
using Kinematics = typename RBDDynamics::Kinematics_t
typedef RBDDynamics::SCALAR SCALAR
typedef core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Types inherited from ct::core::ControlledSystem< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR >
typedef std::shared_ptr< ControlledSystem< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, SCALAR >
typedef SCALAR time_t
Public Member Functions
QuadrotorWithLoadFDSystem ()
QuadrotorWithLoadFDSystem (const QuadrotorWithLoadFDSystem &arg)
virtual ~QuadrotorWithLoadFDSystem ()
virtual RBDDynamics & dynamics () override
virtual const RBDDynamics & dynamics () const override
void computeControlledDynamics (const core::StateVector< STATE_DIM, SCALAR > &state, const core::Time &t, const core::ControlVector< CONTROL_DIM, SCALAR > &control, core::StateVector< STATE_DIM, SCALAR > &derivative) override
void mapControlInputsToLinkForces (const typename RBDDynamics::RBDState_t &state, const core::ControlVector< CONTROL_DIM, SCALAR > &control, typename RBDDynamics::ExtLinkForces_t &linkForces)
RBDDynamics::RBDState_t RBDStateFromVector (const core::StateVector< STATE_DIM, SCALAR > &state)
template<bool T>
RBDDynamics::RBDState_t RBDStateFromVectorImpl (const core::StateVector< STATE_DIM, SCALAR > &state, typename std::enable_if< T, bool >::type=true)
template<bool T>
RBDDynamics::RBDState_t RBDStateFromVectorImpl (const core::StateVector< STATE_DIM, SCALAR > &state, typename std::enable_if<!T, bool >::type=true)
template<bool T>
core::StateVector< STATE_DIM > toStateDerivative (const typename RBDDynamics::RBDAcceleration_t &acceleration, const typename RBDDynamics::RBDState_t &state, typename std::enable_if< T, bool >::type=true)
template<bool T>
core::StateVector< STATE_DIM > toStateDerivative (const typename RBDDynamics::RBDAcceleration_t &acceleration, const typename RBDDynamics::RBDState_t &state, typename std::enable_if<!T, bool >::type=true)
virtual QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION > * clone () const override
Public Member Functions inherited from ct::rbd::RBDSystem< RBDDynamics, QUAT_INTEGRATION >
RBDSystem ()
virtual ~RBDSystem ()
Public Member Functions inherited from ct::core::ControlledSystem< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
ControlledSystem (std::shared_ptr< ct::core::Controller< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
ControlledSystem (const ControlledSystem &arg)
virtual ~ControlledSystem ()
void setController (const std::shared_ptr< Controller< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR >> &controller)
void getController (std::shared_ptr< Controller< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR >> &controller) const
std::shared_ptr< Controller< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR > > getController ()
virtual void computeDynamics (const StateVector< RBDDynamics::NSTATE+QUAT_INTEGRATION, RBDDynamics::SCALAR > &state, const time_t &t, StateVector< RBDDynamics::NSTATE+QUAT_INTEGRATION, RBDDynamics::SCALAR > &derivative) override
virtual void computeControlledDynamics (const StateVector< RBDDynamics::NSTATE+QUAT_INTEGRATION, RBDDynamics::SCALAR > &state, const time_t &t, const ControlVector< 4, RBDDynamics::SCALAR > &control, StateVector< RBDDynamics::NSTATE+QUAT_INTEGRATION, RBDDynamics::SCALAR > &derivative)=0
ControlVector< 4, RBDDynamics::SCALAR > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, SCALAR >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
System (const System &other)
virtual ~System ()
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative)=0
SYSTEM_TYPE getType () const
virtual bool isSymplectic () const
Static Public Attributes
static const size_t STATE_DIM = RBDDynamics::NSTATE + QUAT_INTEGRATION
static const size_t CONTROL_DIM = 4
Additional Inherited Members
Public Attributes inherited from ct::core::ControlledSystem< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< RBDDynamics::NSTATE+QUAT_INTEGRATION, RBDDynamics::SCALAR > Base
Public Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef SCALAR S
Protected Attributes inherited from ct::core::ControlledSystem< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR >
std::shared_ptr< Controller< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR > > controller_
ControlVector< 4, RBDDynamics::SCALAR > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
SYSTEM_TYPE type_
Member Typedef Documentation
template<class RBDDynamics , bool QUAT_INTEGRATION = false> using ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::Dynamics = RBDDynamics
template<class RBDDynamics , bool QUAT_INTEGRATION = false> using ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::Kinematics = typename RBDDynamics::Kinematics_t
template<class RBDDynamics , bool QUAT_INTEGRATION = false> typedef RBDDynamics::SCALAR ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::SCALAR
template<class RBDDynamics , bool QUAT_INTEGRATION = false> typedef core::ControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::Base
Constructor & Destructor Documentation
template<class RBDDynamics , bool QUAT_INTEGRATION = false> ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::QuadrotorWithLoadFDSystem () inline
Referenced by ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::clone().
template<class RBDDynamics , bool QUAT_INTEGRATION = false> ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::QuadrotorWithLoadFDSystem (const QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION > & arg) inline
template<class RBDDynamics , bool QUAT_INTEGRATION = false> virtual ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::~QuadrotorWithLoadFDSystem () inline virtual
Member Function Documentation
template<class RBDDynamics , bool QUAT_INTEGRATION = false> virtual RBDDynamics& ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::dynamics () inline override virtual
Implements ct::rbd::RBDSystem< RBDDynamics, QUAT_INTEGRATION >.
template<class RBDDynamics , bool QUAT_INTEGRATION = false> virtual const RBDDynamics& ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::dynamics () const inline override virtual
Implements ct::rbd::RBDSystem< RBDDynamics, QUAT_INTEGRATION >.
template<class RBDDynamics , bool QUAT_INTEGRATION = false> void ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::computeControlledDynamics (const core::StateVector< STATE_DIM, SCALAR > & state, const core::Time & t, const core::ControlVector< CONTROL_DIM, SCALAR > & control, core::StateVector< STATE_DIM, SCALAR > & derivative) inline override
References ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::mapControlInputsToLinkForces(), ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::RBDStateFromVector(), and x.
template<class RBDDynamics , bool QUAT_INTEGRATION = false> void ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::mapControlInputsToLinkForces (const typename RBDDynamics::RBDState_t & state, const core::ControlVector< CONTROL_DIM, SCALAR > & control, typename RBDDynamics::ExtLinkForces_t & linkForces) inline
Referenced by ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::computeControlledDynamics().
template<class RBDDynamics , bool QUAT_INTEGRATION = false> RBDDynamics::RBDState_t ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::RBDStateFromVector (const core::StateVector< STATE_DIM, SCALAR > & state) inline
Referenced by ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::computeControlledDynamics().
template<class RBDDynamics , bool QUAT_INTEGRATION = false> template<bool T> RBDDynamics::RBDState_t ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::RBDStateFromVectorImpl (const core::StateVector< STATE_DIM, SCALAR > & state, typename std::enable_if< T, bool >::type = true) inline
References ct::rbd::tpl::RigidBodyPose< SCALAR >::QUAT, and x.
template<class RBDDynamics , bool QUAT_INTEGRATION = false> template<bool T> RBDDynamics::RBDState_t ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::RBDStateFromVectorImpl (const core::StateVector< STATE_DIM, SCALAR > & state, typename std::enable_if<!T, bool >::type = true) inline
References ct::rbd::tpl::RigidBodyPose< SCALAR >::EULER, and x.
template<class RBDDynamics , bool QUAT_INTEGRATION = false> template<bool T> core::StateVector<STATE_DIM> ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::toStateDerivative (const typename RBDDynamics::RBDAcceleration_t & acceleration, const typename RBDDynamics::RBDState_t & state, typename std::enable_if< T, bool >::type = true) inline
template<class RBDDynamics , bool QUAT_INTEGRATION = false> template<bool T> core::StateVector<STATE_DIM> ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::toStateDerivative (const typename RBDDynamics::RBDAcceleration_t & acceleration, const typename RBDDynamics::RBDState_t & state, typename std::enable_if<!T, bool >::type = true) inline
template<class RBDDynamics , bool QUAT_INTEGRATION = false> virtual QuadrotorWithLoadFDSystem<RBDDynamics, QUAT_INTEGRATION>* ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::clone () const inline override virtual
Implements ct::core::ControlledSystem< RBDDynamics::NSTATE+QUAT_INTEGRATION, 4, RBDDynamics::SCALAR >.
References ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::QuadrotorWithLoadFDSystem().
Member Data Documentation
template<class RBDDynamics , bool QUAT_INTEGRATION = false> const size_t ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::STATE_DIM = RBDDynamics::NSTATE + QUAT_INTEGRATION static
template<class RBDDynamics , bool QUAT_INTEGRATION = false> const size_t ct::rbd::QuadrotorWithLoadFDSystem< RBDDynamics, QUAT_INTEGRATION >::CONTROL_DIM = 4 static
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/QuadrotorWithLoadFDSystem.h