ct::models::HyQ::HyQInverseDynJacReverse Class Reference
ct::models::HyQ::HyQInverseDynJacReverse Class Reference
#include <HyQInverseDynJacReverse.h>
Public Types
typedef Eigen::Matrix< double, 18, 54 > JAC_TYPE
typedef Eigen::Matrix< double, 54, 1 > X_TYPE
Public Types inherited from ct::core::Derivatives< 54, 18, double >
typedef Eigen::Matrix< double, 54, 1 > IN_TYPE
typedef Eigen::Matrix< double, 18, 1 > OUT_TYPE
typedef Eigen::Matrix< double, 18, 54 > JAC_TYPE
typedef Eigen::Matrix< double, 54, 54 > HES_TYPE
Public Member Functions
HyQInverseDynJacReverse ()
HyQInverseDynJacReverse (const HyQInverseDynJacReverse &other)
virtual ~HyQInverseDynJacReverse ()
HyQInverseDynJacReverse * clone () const override
JAC_TYPE jacobian (const Eigen::VectorXd &x_in) override
Public Member Functions inherited from ct::core::Derivatives< 54, 18, double >
Derivatives ()
virtual ~Derivatives ()
virtual OUT_TYPE forwardZero (const Eigen::VectorXd &x)
virtual void sparseJacobian (const Eigen::VectorXd &x, Eigen::VectorXd &jac, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseJacobianValues (const Eigen::VectorXd &x)
virtual HES_TYPE hessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
virtual void sparseHessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda, Eigen::VectorXd &hes, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseHessianValues (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Member Typedef Documentation
JAC_TYPE
typedef Eigen::Matrix<double, 18, 54> ct::models::HyQ::HyQInverseDynJacReverse::JAC_TYPE
X_TYPE
typedef Eigen::Matrix<double, 54, 1> ct::models::HyQ::HyQInverseDynJacReverse::X_TYPE
Constructor & Destructor Documentation
HyQInverseDynJacReverse() [1/2]
ct::models::HyQ::HyQInverseDynJacReverse::HyQInverseDynJacReverse () inline
Referenced by clone().
HyQInverseDynJacReverse() [2/2]
ct::models::HyQ::HyQInverseDynJacReverse::HyQInverseDynJacReverse (const HyQInverseDynJacReverse & other) inline
~HyQInverseDynJacReverse()
virtual ct::models::HyQ::HyQInverseDynJacReverse::~HyQInverseDynJacReverse () inline virtual
Member Function Documentation
clone()
HyQInverseDynJacReverse* ct::models::HyQ::HyQInverseDynJacReverse::clone () const inline override virtual
Implements ct::core::Derivatives< 54, 18, double >.
References HyQInverseDynJacReverse(), and jacobian().
jacobian()
HyQInverseDynJacReverse::JAC_TYPE ct::models::HyQ::HyQInverseDynJacReverse::jacobian (const Eigen::VectorXd & x_in) override virtual
Reimplemented from ct::core::Derivatives< 54, 18, double >.
Referenced by clone(), and timing().
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQInverseDynJacReverse.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQInverseDynJacReverse.cpp