iit::ct_InvertedPendulum::LinkDataMap< T > Class Template Reference
iit::ct_InvertedPendulum::LinkDataMap< T > Class Template Reference
#include <link_data_map.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW LinkDataMap ()
LinkDataMap (const T &defaultValue)
LinkDataMap (const LinkDataMap &rhs)
LinkDataMap & operator= (const LinkDataMap &rhs)
LinkDataMap & operator= (const T &rhs)
T & operator[] (LinkIdentifiers which)
const T & operator[] (LinkIdentifiers which) const
Detailed Description
template<typename T>
class iit::ct_InvertedPendulum::LinkDataMap< T >
A very simple container to associate a generic data item to each link
Constructor & Destructor Documentation
LinkDataMap() [1/3]
template<typename T > EIGEN_MAKE_ALIGNED_OPERATOR_NEW iit::ct_InvertedPendulum::LinkDataMap< T >::LinkDataMap () inline
References iit::ct_InvertedPendulum::LinkDataMap< T >::operator=(), and iit::ct_InvertedPendulum::LinkDataMap< T >::operator[]().
LinkDataMap() [2/3]
template<typename T > iit::ct_InvertedPendulum::LinkDataMap< T >::LinkDataMap (const T & defaultValue) inline
LinkDataMap() [3/3]
template<typename T > iit::ct_InvertedPendulum::LinkDataMap< T >::LinkDataMap (const LinkDataMap< T > & rhs) inline
Member Function Documentation
operator=() [1/2]
template<typename T > LinkDataMap< T > & iit::ct_InvertedPendulum::LinkDataMap< T >::operator= (const LinkDataMap< T > & rhs) inline
Referenced by iit::ct_InvertedPendulum::LinkDataMap< T >::LinkDataMap().
operator=() [2/2]
template<typename T > LinkDataMap< T > & iit::ct_InvertedPendulum::LinkDataMap< T >::operator= (const T & rhs) inline
operator[]() [1/2]
template<typename T > T & iit::ct_InvertedPendulum::LinkDataMap< T >::operator[] (LinkIdentifiers which) inline
Referenced by iit::ct_InvertedPendulum::LinkDataMap< T >::LinkDataMap().
operator[]() [2/2]
template<typename T > const T & iit::ct_InvertedPendulum::LinkDataMap< T >::operator[] (LinkIdentifiers which) const inline
References iit::ct_InvertedPendulum::INVERTEDPENDULUMBASE, and iit::ct_InvertedPendulum::LINK1.
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/InvertedPendulum/generated/link_data_map.h