iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
#include <inertia_properties.h>
Public Types
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > IMatrix
typedef Eigen::Matrix< SCALAR, 3, 1 > Vec3d
Public Member Functions
InertiaProperties ()
~InertiaProperties ()
const IMatrix & getTensor_body () const
const IMatrix & getTensor_link1 () const
const IMatrix & getTensor_link2 () const
SCALAR getMass_body () const
SCALAR getMass_link1 () const
SCALAR getMass_link2 () const
const Vec3d & getCOM_body () const
const Vec3d & getCOM_link1 () const
const Vec3d & getCOM_link2 () const
SCALAR getTotalMass () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar SCALAR
Member Typedef Documentation
IMatrix
template<typename TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::IMatrix
Vec3d
template<typename TRAIT> typedef Eigen::Matrix<SCALAR, 3, 1> iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::Vec3d
Constructor & Destructor Documentation
InertiaProperties()
template<typename TRAIT > iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::InertiaProperties ()
~InertiaProperties()
template<typename TRAIT > iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::~InertiaProperties () inline
Member Function Documentation
getTensor_body()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getTensor_body () const inline
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::update().
getTensor_link1()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link1 () const inline
Referenced by iit::ct_quadrotor::dyn::tpl::JSIM< TRAIT >::update().
getTensor_link2()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link2 () const inline
getMass_body()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getMass_body () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_link1()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getMass_link1 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_link2()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getMass_link2 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getCOM_body()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getCOM_body () const inline
getCOM_link1()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getCOM_link1 () const inline
getCOM_link2()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getCOM_link2 () const inline
getTotalMass()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::getTotalMass () const inline
Member Data Documentation
SCALAR
template<typename TRAIT> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::ct_quadrotor::dyn::tpl::InertiaProperties< TRAIT >::SCALAR
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/inertia_properties.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/inertia_properties.impl.h