iit::HyQ::LinkDataMap< T > Class Template Reference
iit::HyQ::LinkDataMap< T > Class Template Reference
#include <link_data_map.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW LinkDataMap ()
LinkDataMap (const T &defaultValue)
LinkDataMap (const LinkDataMap &rhs)
LinkDataMap & operator= (const LinkDataMap &rhs)
LinkDataMap & operator= (const T &rhs)
T & operator[] (LinkIdentifiers which)
const T & operator[] (LinkIdentifiers which) const
Detailed Description
template<typename T>
class iit::HyQ::LinkDataMap< T >
A very simple container to associate a generic data item to each link
Constructor & Destructor Documentation
template<typename T > EIGEN_MAKE_ALIGNED_OPERATOR_NEW iit::HyQ::LinkDataMap< T >::LinkDataMap () inline
References iit::HyQ::LinkDataMap< T >::operator=(), and iit::HyQ::LinkDataMap< T >::operator[]().
template<typename T > iit::HyQ::LinkDataMap< T >::LinkDataMap (const T & defaultValue) inline
template<typename T > iit::HyQ::LinkDataMap< T >::LinkDataMap (const LinkDataMap< T > & rhs) inline
Member Function Documentation
template<typename T > LinkDataMap< T > & iit::HyQ::LinkDataMap< T >::operator= (const LinkDataMap< T > & rhs) inline
Referenced by iit::HyQ::LinkDataMap< T >::LinkDataMap().
template<typename T > LinkDataMap< T > & iit::HyQ::LinkDataMap< T >::operator= (const T & rhs) inline
template<typename T > T & iit::HyQ::LinkDataMap< T >::operator[] (LinkIdentifiers which) inline
Referenced by iit::HyQ::LinkDataMap< T >::LinkDataMap().
template<typename T > const T & iit::HyQ::LinkDataMap< T >::operator[] (LinkIdentifiers which) const inline
References iit::HyQ::LF_HIPASSEMBLY, iit::HyQ::LF_LOWERLEG, iit::HyQ::LF_UPPERLEG, iit::HyQ::LH_HIPASSEMBLY, iit::HyQ::LH_LOWERLEG, iit::HyQ::LH_UPPERLEG, iit::HyQ::RF_HIPASSEMBLY, iit::HyQ::RF_LOWERLEG, iit::HyQ::RF_UPPERLEG, iit::HyQ::RH_HIPASSEMBLY, iit::HyQ::RH_LOWERLEG, iit::HyQ::RH_UPPERLEG, and iit::HyQ::TRUNK.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyQ/generated/link_data_map.h