ct::models::HyQ::HyQForwardKinJacForward Class Reference
ct::models::HyQ::HyQForwardKinJacForward Class Reference
#include <HyQForwardKinJacForward.h>
Public Types
typedef Eigen::Matrix< double, 24, 36 > JAC_TYPE
typedef Eigen::Matrix< double, 36, 1 > X_TYPE
Public Types inherited from ct::core::Derivatives< 36, 24, double >
typedef Eigen::Matrix< double, 36, 1 > IN_TYPE
typedef Eigen::Matrix< double, 24, 1 > OUT_TYPE
typedef Eigen::Matrix< double, 24, 36 > JAC_TYPE
typedef Eigen::Matrix< double, 36, 36 > HES_TYPE
Public Member Functions
HyQForwardKinJacForward ()
HyQForwardKinJacForward (const HyQForwardKinJacForward &other)
virtual ~HyQForwardKinJacForward ()
HyQForwardKinJacForward * clone () const override
JAC_TYPE jacobian (const Eigen::VectorXd &x_in) override
Public Member Functions inherited from ct::core::Derivatives< 36, 24, double >
Derivatives ()
virtual ~Derivatives ()
virtual OUT_TYPE forwardZero (const Eigen::VectorXd &x)
virtual void sparseJacobian (const Eigen::VectorXd &x, Eigen::VectorXd &jac, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseJacobianValues (const Eigen::VectorXd &x)
virtual HES_TYPE hessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
virtual void sparseHessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda, Eigen::VectorXd &hes, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseHessianValues (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Member Typedef Documentation
JAC_TYPE
typedef Eigen::Matrix<double, 24, 36> ct::models::HyQ::HyQForwardKinJacForward::JAC_TYPE
X_TYPE
typedef Eigen::Matrix<double, 36, 1> ct::models::HyQ::HyQForwardKinJacForward::X_TYPE
Constructor & Destructor Documentation
HyQForwardKinJacForward() [1/2]
ct::models::HyQ::HyQForwardKinJacForward::HyQForwardKinJacForward () inline
Referenced by clone().
HyQForwardKinJacForward() [2/2]
ct::models::HyQ::HyQForwardKinJacForward::HyQForwardKinJacForward (const HyQForwardKinJacForward & other) inline
~HyQForwardKinJacForward()
virtual ct::models::HyQ::HyQForwardKinJacForward::~HyQForwardKinJacForward () inline virtual
Member Function Documentation
clone()
HyQForwardKinJacForward* ct::models::HyQ::HyQForwardKinJacForward::clone () const inline override virtual
Implements ct::core::Derivatives< 36, 24, double >.
References HyQForwardKinJacForward(), and jacobian().
jacobian()
HyQForwardKinJacForward::JAC_TYPE ct::models::HyQ::HyQForwardKinJacForward::jacobian (const Eigen::VectorXd & x_in) override virtual
Reimplemented from ct::core::Derivatives< 36, 24, double >.
Referenced by clone(), and timing().
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQForwardKinJacForward.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQForwardKinJacForward.cpp