iit::ct_DoubleInvertedPendulum::JointDataMap< T > Class Template Reference
iit::ct_DoubleInvertedPendulum::JointDataMap< T > Class Template Reference
#include <joint_data_map.h>
Public Member Functions
JointDataMap ()
JointDataMap (const T &defaultValue)
JointDataMap (const JointDataMap &rhs)
JointDataMap & operator= (const JointDataMap &rhs)
JointDataMap & operator= (const T &rhs)
T & operator[] (JointIdentifiers which)
const T & operator[] (JointIdentifiers which) const
Detailed Description
template<typename T>
class iit::ct_DoubleInvertedPendulum::JointDataMap< T >
A very simple container to associate a generic data item to each joint
Constructor & Destructor Documentation
template<typename T > iit::ct_DoubleInvertedPendulum::JointDataMap< T >::JointDataMap () inline
References iit::ct_DoubleInvertedPendulum::JointDataMap< T >::operator=(), and iit::ct_DoubleInvertedPendulum::JointDataMap< T >::operator[]().
template<typename T > iit::ct_DoubleInvertedPendulum::JointDataMap< T >::JointDataMap (const T & defaultValue) inline
template<typename T > iit::ct_DoubleInvertedPendulum::JointDataMap< T >::JointDataMap (const JointDataMap< T > & rhs) inline
Member Function Documentation
template<typename T > JointDataMap< T > & iit::ct_DoubleInvertedPendulum::JointDataMap< T >::operator= (const JointDataMap< T > & rhs) inline
Referenced by iit::ct_DoubleInvertedPendulum::JointDataMap< T >::JointDataMap().
template<typename T > JointDataMap< T > & iit::ct_DoubleInvertedPendulum::JointDataMap< T >::operator= (const T & rhs) inline
template<typename T > T & iit::ct_DoubleInvertedPendulum::JointDataMap< T >::operator[] (JointIdentifiers which) inline
Referenced by iit::ct_DoubleInvertedPendulum::JointDataMap< T >::JointDataMap().
template<typename T > const T & iit::ct_DoubleInvertedPendulum::JointDataMap< T >::operator[] (JointIdentifiers which) const inline
References iit::ct_DoubleInvertedPendulum::JOINT1, and iit::ct_DoubleInvertedPendulum::JOINT2.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/DoubleInvertedPendulum/generated/joint_data_map.h