iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
#include <inertia_properties.h>
Public Types
typedef iit::rbd::Core< Scalar > CoreS
typedef iit::rbd::tpl::InertiaMatrixDense< Scalar > IMatrix
typedef CoreS::Vector3 Vec3d
Public Member Functions
InertiaProperties ()
~InertiaProperties ()
const IMatrix & getTensor_Link1 () const
const IMatrix & getTensor_Link2 () const
Scalar getMass_Link1 () const
Scalar getMass_Link2 () const
const Vec3d & getCOM_Link1 () const
const Vec3d & getCOM_Link2 () const
Scalar getTotalMass () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar Scalar
Member Typedef Documentation
CoreS
template<typename TRAIT> typedef iit::rbd::Core<Scalar> iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::CoreS
IMatrix
template<typename TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<Scalar> iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::IMatrix
Vec3d
template<typename TRAIT> typedef CoreS::Vector3 iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::Vec3d
Constructor & Destructor Documentation
InertiaProperties()
template<typename TRAIT > iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::InertiaProperties ()
~InertiaProperties()
template<typename TRAIT > iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::~InertiaProperties () inline
Member Function Documentation
getTensor_Link1()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Link1 () const inline
Referenced by iit::ct_DoubleInvertedPendulum::dyn::tpl::JSIM< TRAIT >::update().
getTensor_Link2()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getTensor_Link2 () const inline
getMass_Link1()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getMass_Link1 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::ct_DoubleInvertedPendulum::getWholeBodyCOM().
getMass_Link2()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getMass_Link2 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::ct_DoubleInvertedPendulum::getWholeBodyCOM().
getCOM_Link1()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Link1 () const inline
Referenced by iit::ct_DoubleInvertedPendulum::getWholeBodyCOM().
getCOM_Link2()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Link2 () const inline
Referenced by iit::ct_DoubleInvertedPendulum::getWholeBodyCOM().
getTotalMass()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getTotalMass () const inline
Referenced by iit::ct_DoubleInvertedPendulum::getWholeBodyCOM().
Member Data Documentation
Scalar
template<typename TRAIT> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::Scalar
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/DoubleInvertedPendulum/generated/inertia_properties.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/DoubleInvertedPendulum/generated/inertia_properties.impl.h