ct::rbd::Irb4600InverseKinematics< SCALAR > Class Template Reference
ct::rbd::Irb4600InverseKinematics< SCALAR > Class Template Reference
#include <Irb4600InverseKinematics.h>
Public Types
using BASE = InverseKinematicsBase< 6, SCALAR >
using JointPosition_t = typename BASE::JointPosition_t
using JointPositionsVector_t = typename BASE::JointPositionsVector_t
using RigidBodyPoseTpl = typename BASE::RigidBodyPoseTpl
Public Member Functions
Irb4600InverseKinematics ()=default
~Irb4600InverseKinematics ()=default
bool computeInverseKinematics (JointPositionsVector_t &res, const RigidBodyPoseTpl &eeBasePose, const std::vector< size_t > &freeJoints=std::vector< size_t >()) override
bool computeInverseKinematics (JointPositionsVector_t &res, const RigidBodyPoseTpl &eeWorldPose, const RigidBodyPoseTpl &baseWorldPose, const std::vector< size_t > &freeJoints=std::vector< size_t >()) override
Member Typedef Documentation
BASE
template<typename SCALAR = double> using ct::rbd::Irb4600InverseKinematics< SCALAR >::BASE = InverseKinematicsBase<6, SCALAR>
JointPosition_t
template<typename SCALAR = double> using ct::rbd::Irb4600InverseKinematics< SCALAR >::JointPosition_t = typename BASE::JointPosition_t
JointPositionsVector_t
template<typename SCALAR = double> using ct::rbd::Irb4600InverseKinematics< SCALAR >::JointPositionsVector_t = typename BASE::JointPositionsVector_t
RigidBodyPoseTpl
template<typename SCALAR = double> using ct::rbd::Irb4600InverseKinematics< SCALAR >::RigidBodyPoseTpl = typename BASE::RigidBodyPoseTpl
Constructor & Destructor Documentation
Irb4600InverseKinematics()
template<typename SCALAR = double> ct::rbd::Irb4600InverseKinematics< SCALAR >::Irb4600InverseKinematics () default
~Irb4600InverseKinematics()
template<typename SCALAR = double> ct::rbd::Irb4600InverseKinematics< SCALAR >::~Irb4600InverseKinematics () default
Member Function Documentation
computeInverseKinematics() [1/2]
template<typename SCALAR = double> bool ct::rbd::Irb4600InverseKinematics< SCALAR >::computeInverseKinematics (JointPositionsVector_t & res, const RigidBodyPoseTpl & eeBasePose, const std::vector< size_t > & freeJoints = std::vector<size_t>()) inline override
References ComputeIk(), GetNumFreeParameters(), ikfast::IkSolutionList< class >::GetNumSolutions(), ct::rbd::JointState< NJOINTS, SCALAR >::getPositions(), ikfast::IkSolutionList< class >::GetSolution(), ikfast::IkSolutionBase< class >::GetSolution(), and i.
Referenced by TEST().
computeInverseKinematics() [2/2]
template<typename SCALAR = double> bool ct::rbd::Irb4600InverseKinematics< SCALAR >::computeInverseKinematics (JointPositionsVector_t & res, const RigidBodyPoseTpl & eeWorldPose, const RigidBodyPoseTpl & baseWorldPose, const std::vector< size_t > & freeJoints = std::vector<size_t>()) inline override
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/include/ct/models/Irb4600/Irb4600InverseKinematics.h