iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT > Class Template Reference
iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT > Class Template Reference
#include <inverse_dynamics.h>
Public Types
typedef iit::rbd::Core< SCALAR > CoreS
typedef CoreS::ForceVector Force
typedef LinkDataMap< Force > ExtForces
typedef CoreS::VelocityVector Velocity
typedef CoreS::VelocityVector Acceleration
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > InertiaMatrix
typedef iit::ct_quadrotor::tpl::JointState< SCALAR > JointState
typedef CoreS::Matrix66 Matrix66s
typedef iit::ct_quadrotor::tpl::MotionTransforms< TRAIT > MTransforms
typedef InertiaProperties< TRAIT > IProperties
Public Member Functions
InverseDynamics (IProperties &in, MTransforms &tr)
void setJointStatus (const JointState &q) const
Inverse dynamics
The full algorithm for the inverse dynamics of this robot.
All the spatial vectors in the parameters are expressed in base coordinates, besides the external forces: each force must be expressed in the reference frame of the link it is acting on.
Parameters
[out] jForces the joint force vector required to achieve the desired accelerations
[out] baseAccel the spatial acceleration of the robot base
[in] g the gravity acceleration, as a spatial vector; gravity implicitly specifies the orientation of the base in space
[in] body_v the spatial velocity of the base
[in] q the joint position vector
[in] qd the joint velocity vector
[in] qdd the desired joint acceleration vector
[in] fext the external forces acting on the links; this parameters defaults to zero
void id (JointState &jForces, Acceleration &body_a, const Acceleration &g, const Velocity &body_v, const JointState &q, const JointState &qd, const JointState &qdd, const ExtForces &fext=zeroExtForces)
void id (JointState &jForces, Acceleration &body_a, const Acceleration &g, const Velocity &body_v, const JointState &qd, const JointState &qdd, const ExtForces &fext=zeroExtForces)
Inverse dynamics, fully actuated base
The inverse dynamics algorithm for the floating base robot, in the assumption of a fully actuated base.
All the spatial vectors in the parameters are expressed in base coordinates, besides the external forces: each force must be expressed in the reference frame of the link it is acting on.
Parameters
[out] baseWrench the spatial force to be applied to the robot base to achieve the desired accelerations
[out] jForces the joint force vector required to achieve the desired accelerations
[in] g the gravity acceleration, as a spatial vector; gravity implicitly specifies the orientation of the base in space
[in] body_v the spatial velocity of the base
[in] baseAccel the desired spatial acceleration of the robot base
[in] q the joint position vector
[in] qd the joint velocity vector
[in] qdd the desired joint acceleration vector
[in] fext the external forces acting on the links; this parameters defaults to zero
void id_fully_actuated (Force &baseWrench, JointState &jForces, const Acceleration &g, const Velocity &body_v, const Acceleration &baseAccel, const JointState &q, const JointState &qd, const JointState &qdd, const ExtForces &fext=zeroExtForces)
void id_fully_actuated (Force &baseWrench, JointState &jForces, const Acceleration &g, const Velocity &body_v, const Acceleration &baseAccel, const JointState &qd, const JointState &qdd, const ExtForces &fext=zeroExtForces)
Gravity terms, fully actuated base
void G_terms_fully_actuated (Force &baseWrench, JointState &jForces, const Acceleration &g, const JointState &q)
void G_terms_fully_actuated (Force &baseWrench, JointState &jForces, const Acceleration &g)
Centrifugal and Coriolis terms, fully actuated base
These functions take only velocity inputs, that is, they assume a zero spatial acceleration of the base (in addition to zero acceleration at the actuated joints). Note that this is NOT the same as imposing zero acceleration at the virtual 6-dof-floting-base joint, which would result, in general, in a non-zero spatial acceleration of the base, due to velocity product terms.
void C_terms_fully_actuated (Force &baseWrench, JointState &jForces, const Velocity &body_v, const JointState &q, const JointState &qd)
void C_terms_fully_actuated (Force &baseWrench, JointState &jForces, const Velocity &body_v, const JointState &qd)
Getters
These functions return various spatial quantities used internally by the inverse dynamics routines, like the spatial acceleration of the links.
The getters can be useful to retrieve the additional data that is not returned explicitly by the inverse dynamics routines even though it is computed. For example, after a call to the inverse dynamics, the spatial velocity of all the links has been determined and can be accessed.
However, beware that certain routines might not use some of the spatial quantities, which therefore would retain their last value without being updated nor reset (for example, the spatial velocity of the links is unaffected by the computation of the gravity terms).
const Force & getForce_body () const
const Velocity & getVelocity_link1 () const
const Acceleration & getAcceleration_link1 () const
const Force & getForce_link1 () const
const Velocity & getVelocity_link2 () const
const Acceleration & getAcceleration_link2 () const
const Force & getForce_link2 () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar SCALAR
Protected Member Functions
void secondPass_fullyActuated (JointState &jForces)
Member Typedef Documentation
template<typename TRAIT > typedef iit::rbd::Core<SCALAR> iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::CoreS
template<typename TRAIT > typedef CoreS::ForceVector iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::Force
template<typename TRAIT > typedef LinkDataMap<Force> iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::ExtForces
template<typename TRAIT > typedef CoreS::VelocityVector iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::Velocity
template<typename TRAIT > typedef CoreS::VelocityVector iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::Acceleration
template<typename TRAIT > typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::InertiaMatrix
template<typename TRAIT > typedef iit::ct_quadrotor::tpl::JointState<SCALAR> iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::JointState
template<typename TRAIT > typedef CoreS::Matrix66 iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::Matrix66s
template<typename TRAIT > typedef iit::ct_quadrotor::tpl::MotionTransforms<TRAIT> iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::MTransforms
template<typename TRAIT > typedef InertiaProperties<TRAIT> iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::IProperties
Constructor & Destructor Documentation
template<typename TRAIT > iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::InverseDynamics (IProperties & in, MTransforms & tr)
Default constructor
Parameters
in the inertia properties of the links
tr the container of all the spatial motion transforms of the robot ct_quadrotor, which will be used by this instance to compute inverse-dynamics.
Member Function Documentation
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::id (JointState & jForces, Acceleration & body_a, const Acceleration & g, const Velocity & body_v, const JointState & q, const JointState & qd, const JointState & qdd, const ExtForces & fext = zeroExtForces) inline
References iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::id (JointState & jForces, Acceleration & body_a, const Acceleration & g, const Velocity & body_v, const JointState & qd, const JointState & qdd, const ExtForces & fext = zeroExtForces)
References iit::rbd::AZ, iit::ct_quadrotor::BODY, iit::ct_quadrotor::JA, iit::ct_quadrotor::JB, iit::ct_quadrotor::LINK1, iit::ct_quadrotor::LINK2, and iit::rbd::vxIv().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::id_fully_actuated (Force & baseWrench, JointState & jForces, const Acceleration & g, const Velocity & body_v, const Acceleration & baseAccel, const JointState & q, const JointState & qd, const JointState & qdd, const ExtForces & fext = zeroExtForces) inline
References iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::id_fully_actuated (Force & baseWrench, JointState & jForces, const Acceleration & g, const Velocity & body_v, const Acceleration & baseAccel, const JointState & qd, const JointState & qdd, const ExtForces & fext = zeroExtForces)
References iit::rbd::AZ, iit::ct_quadrotor::BODY, iit::ct_quadrotor::JA, iit::ct_quadrotor::JB, iit::ct_quadrotor::LINK1, iit::ct_quadrotor::LINK2, iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::secondPass_fullyActuated(), and iit::rbd::vxIv().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::G_terms_fully_actuated (Force & baseWrench, JointState & jForces, const Acceleration & g, const JointState & q) inline
References iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::G_terms_fully_actuated (Force & baseWrench, JointState & jForces, const Acceleration & g)
References iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::secondPass_fullyActuated().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::C_terms_fully_actuated (Force & baseWrench, JointState & jForces, const Velocity & body_v, const JointState & q, const JointState & qd) inline
References iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::C_terms_fully_actuated (Force & baseWrench, JointState & jForces, const Velocity & body_v, const JointState & qd)
References iit::rbd::AZ, iit::ct_quadrotor::JA, iit::ct_quadrotor::JB, iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::secondPass_fullyActuated(), and iit::rbd::vxIv().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::setJointStatus (const JointState & q) const inline
Updates all the kinematics transforms used by the inverse dynamics routine.
Referenced by iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::C_terms_fully_actuated(), iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::G_terms_fully_actuated(), iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::id(), and iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::id_fully_actuated().
template<typename TRAIT > const Force& iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::getForce_body () const inline
template<typename TRAIT > const Velocity& iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::getVelocity_link1 () const inline
template<typename TRAIT > const Acceleration& iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::getAcceleration_link1 () const inline
template<typename TRAIT > const Force& iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::getForce_link1 () const inline
template<typename TRAIT > const Velocity& iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::getVelocity_link2 () const inline
template<typename TRAIT > const Acceleration& iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::getAcceleration_link2 () const inline
template<typename TRAIT > const Force& iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::getForce_link2 () const inline
References iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::secondPass_fullyActuated().
template<typename TRAIT > void iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::secondPass_fullyActuated (JointState & jForces) protected
References iit::rbd::AZ, iit::ct_quadrotor::JA, and iit::ct_quadrotor::JB.
Referenced by iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::C_terms_fully_actuated(), iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::G_terms_fully_actuated(), iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::getForce_link2(), and iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::id_fully_actuated().
Member Data Documentation
template<typename TRAIT > EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::ct_quadrotor::dyn::tpl::InverseDynamics< TRAIT >::SCALAR
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/inverse_dynamics.h
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/inverse_dynamics.impl.h