ct::models::HyQ::HyQForwardZero Class Reference
ct::models::HyQ::HyQForwardZero Class Reference
#include <HyQForwardZero.h>
Public Types
typedef Eigen::Matrix< double, 36, 1 > OUT_TYPE
typedef Eigen::Matrix< double, 49, 1 > X_TYPE
Public Types inherited from ct::core::Derivatives< 49, 36, double >
typedef Eigen::Matrix< double, 49, 1 > IN_TYPE
typedef Eigen::Matrix< double, 36, 1 > OUT_TYPE
typedef Eigen::Matrix< double, 36, 49 > JAC_TYPE
typedef Eigen::Matrix< double, 49, 49 > HES_TYPE
Public Member Functions
HyQForwardZero ()
HyQForwardZero (const HyQForwardZero &other)
virtual ~HyQForwardZero ()
HyQForwardZero * clone () const override
OUT_TYPE forwardZero (const Eigen::VectorXd &x_in) override
Public Member Functions inherited from ct::core::Derivatives< 49, 36, double >
Derivatives ()
virtual ~Derivatives ()
virtual JAC_TYPE jacobian (const Eigen::VectorXd &x)
virtual void sparseJacobian (const Eigen::VectorXd &x, Eigen::VectorXd &jac, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseJacobianValues (const Eigen::VectorXd &x)
virtual HES_TYPE hessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
virtual void sparseHessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda, Eigen::VectorXd &hes, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual Eigen::VectorXd sparseHessianValues (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Member Typedef Documentation
typedef Eigen::Matrix<double, 36, 1> ct::models::HyQ::HyQForwardZero::OUT_TYPE
typedef Eigen::Matrix<double, 49, 1> ct::models::HyQ::HyQForwardZero::X_TYPE
Constructor & Destructor Documentation
ct::models::HyQ::HyQForwardZero::HyQForwardZero () inline
Referenced by clone().
ct::models::HyQ::HyQForwardZero::HyQForwardZero (const HyQForwardZero & other) inline
virtual ct::models::HyQ::HyQForwardZero::~HyQForwardZero () inline virtual
Member Function Documentation
HyQForwardZero* ct::models::HyQ::HyQForwardZero::clone () const inline override virtual
Implements ct::core::Derivatives< 49, 36, double >.
References forwardZero(), and HyQForwardZero().
HyQForwardZero::OUT_TYPE ct::models::HyQ::HyQForwardZero::forwardZero (const Eigen::VectorXd & x_in) override virtual
Reimplemented from ct::core::Derivatives< 49, 36, double >.
Referenced by clone(), ct::models::HyQ::HyQContactModelForwardZeroSystem::computeVdot(), and timing().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQForwardZero.h
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/HyQ/codegen/HyQForwardZero.cpp