/home/adrl/code/src/control-toolbox/ct_models/src/HyA/codegen/compareForwardReverse.cpp File Reference
compareForwardReverse.cpp File Reference
#include <ct/rbd/rbd.h>
#include <ct/models/HyA/HyA.h>
#include <ct/models/HyA/codegen/HyALinearizedForward.h>
#include <ct/models/HyA/codegen/HyALinearizedReverse.h>
#include <ct/models/HyA/codegen/HyAInverseDynJacForward.h>
#include <ct/models/HyA/codegen/HyAInverseDynJacReverse.h>
Functions
void timingForwardDynamics ()
void timingInverseDynamics ()
int main (int argc, char *argv[])
Function Documentation
void timingForwardDynamics ()
References ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::models::HyA::HyALinearizedForward::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), ct::models::HyA::HyALinearizedForward::getDerivativeState(), ct::models::HyA::HyALinearizedReverse::getDerivativeState(), i, linearizer(), u, x, and X.
Referenced by main().
void timingInverseDynamics ()
References i, ct::models::HyA::HyAInverseDynJacReverse::jacobian(), ct::models::HyA::HyAInverseDynJacForward::jacobian(), X, and x.
Referenced by main().
int main (int argc, char * argv[])
References timingForwardDynamics(), and timingInverseDynamics().