/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/src/HyQ/codegen/compareForwardReverseFD.cpp File Reference
compareForwardReverseFD.cpp File Reference
#include <ct/rbd/rbd.h>
#include <ct/models/HyQ/HyQ.h>
#include <ct/models/HyQ/codegen/HyQWithContactModelLinearizedForward.h>
#include <ct/models/HyQ/codegen/HyQWithContactModelLinearizedReverse.h>
#include <ct/models/HyQ/codegen/HyQBareModelLinearizedForward.h>
#include <ct/models/HyQ/codegen/HyQBareModelLinearizedReverse.h>
Functions
void timing (bool useContactModel)
int main (int argc, char *argv[])
Function Documentation
timing()
void timing (bool useContactModel)
References ct::rbd::FloatingBaseFDSystem< RBDDynamics, QUAT_INTEGRATION, EE_ARE_CONTROL_INPUTS >::CONTROL_DIM, ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeState(), i, linearizer(), ct::rbd::FloatingBaseFDSystem< RBDDynamics, QUAT_INTEGRATION, EE_ARE_CONTROL_INPUTS >::STATE_DIM, u, x, and X.
Referenced by main().
main()
int main (int argc, char * argv[])
References timing().