/home/adrl/code/src/control-toolbox/ct_models/src/HyA/transform6d.cpp File Reference
transform6d.cpp File Reference
#include "ikfast.h"
#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>
#include <stdexcept>
#include <sstream>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
Classes
struct CheckValue< T >
class IKSolver
Macros
#define IKFAST_HAS_LIBRARY
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
#define __PRETTY_FUNCTION__ __func__
#define IKFAST_ASSERT(b) { if(!(b)) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#define IK2PI ((IkReal)6.28318530717959)
#define IKPI ((IkReal)3.14159265358979)
#define IKPI_2 ((IkReal)1.57079632679490)
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#define IKFAST_EVALCOND_THRESH ((IkReal)0.00001)
Functions
IKFAST_COMPILE_ASSERT (IKFAST_VERSION==0x1000004a)
void dgetrf_ (const int *m, const int *n, double *a, const int *lda, int *ipiv, int *info)
void zgetrf_ (const int *m, const int *n, std::complex< double > *a, const int *lda, int *ipiv, int *info)
void dgetri_ (const int *n, const double *a, const int *lda, int *ipiv, double *work, const int *lwork, int *info)
void dgesv_ (const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info)
void dgetrs_ (const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info)
void dgeev_ (const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi, double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info)
float IKabs (float f)
double IKabs (double f)
float IKsqr (float f)
double IKsqr (double f)
float IKlog (float f)
double IKlog (double f)
float IKasin (float f)
double IKasin (double f)
float IKfmod (float x, float y)
double IKfmod (double x, double y)
float IKacos (float f)
double IKacos (double f)
float IKsin (float f)
double IKsin (double f)
float IKcos (float f)
double IKcos (double f)
float IKtan (float f)
double IKtan (double f)
float IKsqrt (float f)
double IKsqrt (double f)
float IKatan2Simple (float fy, float fx)
float IKatan2 (float fy, float fx)
double IKatan2Simple (double fy, double fx)
double IKatan2 (double fy, double fx)
template<typename T >
CheckValue< T > IKatan2WithCheck (T fy, T fx, T epsilon)
float IKsign (float f)
double IKsign (double f)
template<typename T >
CheckValue< T > IKPowWithIntegerCheck (T f, int n)
IKFAST_API void ComputeFk (const IkReal *j, IkReal *eetrans, IkReal *eerot)
IKFAST_API int GetNumFreeParameters ()
IKFAST_API int * GetFreeParameters ()
IKFAST_API int GetNumJoints ()
IKFAST_API int GetIkRealSize ()
IKFAST_API int GetIkType ()
IKFAST_API bool ComputeIk (const IkReal *eetrans, const IkReal *eerot, const IkReal *pfree, IkSolutionListBase< IkReal > &solutions)
IKFAST_API bool ComputeIk2 (const IkReal *eetrans, const IkReal *eerot, const IkReal *pfree, IkSolutionListBase< IkReal > &solutions, void *pOpenRAVEManip)
IKFAST_API const char * GetKinematicsHash ()
IKFAST_API const char * GetIkFastVersion ()
int main (int argc, char **argv)
Macro Definition Documentation
#define IKFAST_HAS_LIBRARY
autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
Author
Rosen Diankov
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
ikfast version 0x1000004a generated on 2018-01-21 23:37:30.503597 Generated using solver transform6d To compile with gcc: gcc -lstdc++ ik.cpp To compile without any main function as a shared object (might need -llapack): gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp
#define IKFAST_COMPILE_ASSERT (x) extern int __dummy[(int)x]
#define __PRETTY_FUNCTION__ __func__
#define IKFAST_ASSERT (b) { if(!(b)) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }
Referenced by IKacos(), IKasin(), IKatan2(), IKSolver::polyroots3(), IKSolver::polyroots4(), IKSolver::polyroots5(), IKSolver::polyroots6(), IKSolver::polyroots7(), and IKSolver::polyroots8().
#define IKFAST_ALIGNED16 (x) x __attribute((aligned(16)))
#define IK2PI ((IkReal)6.28318530717959)
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
#define IKPI ((IkReal)3.14159265358979)
Referenced by IKSolver::ComputeIk(), IKacos(), and IKSolver::rotationfunction0().
#define IKPI_2 ((IkReal)1.57079632679490)
Referenced by IKasin(), and IKatan2().
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
Referenced by IKSolver::ComputeIk(), IKacos(), IKasin(), and IKSolver::rotationfunction0().
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
Referenced by IKSolver::ComputeIk(), IKatan2WithCheck(), and IKSolver::rotationfunction0().
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
#define IKFAST_EVALCOND_THRESH ((IkReal)0.00001)
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
Function Documentation
IKFAST_COMPILE_ASSERT (IKFAST_VERSION = =0x1000004a)
void dgetrf_ (const int * m, const int * n, double * a, const int * lda, int * ipiv, int * info)
void zgetrf_ (const int * m, const int * n, std::complex< double > * a, const int * lda, int * ipiv, int * info)
void dgetri_ (const int * n, const double * a, const int * lda, int * ipiv, double * work, const int * lwork, int * info)
void dgesv_ (const int * n, const int * nrhs, double * a, const int * lda, int * ipiv, double * b, const int * ldb, int * info)
void dgetrs_ (const char * trans, const int * n, const int * nrhs, double * a, const int * lda, int * ipiv, double * b, const int * ldb, int * info)
void dgeev_ (const char * jobvl, const char * jobvr, const int * n, double * a, const int * lda, double * wr, double * wi, double * vl, const int * ldvl, double * vr, const int * ldvr, double * work, const int * lwork, int * info)
float IKabs (float f) inline
Referenced by IKSolver::ComputeIk(), IKatan2WithCheck(), IKSolver::polyroots3(), IKSolver::polyroots4(), IKSolver::polyroots5(), IKSolver::polyroots6(), IKSolver::polyroots7(), IKSolver::polyroots8(), and IKSolver::rotationfunction0().
double IKabs (double f) inline
float IKsqr (float f) inline
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
double IKsqr (double f) inline
float IKlog (float f) inline
double IKlog (double f) inline
float IKasin (float f) inline
References IKFAST_ASSERT, IKFAST_SINCOS_THRESH, and IKPI_2.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
double IKasin (double f) inline
References IKFAST_ASSERT, IKFAST_SINCOS_THRESH, and IKPI_2.
float IKfmod (float x, float y) inline
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
double IKfmod (double x, double y) inline
float IKacos (float f) inline
References IKFAST_ASSERT, IKFAST_SINCOS_THRESH, and IKPI.
Referenced by IKSolver::rotationfunction0().
double IKacos (double f) inline
References IKFAST_ASSERT, IKFAST_SINCOS_THRESH, and IKPI.
float IKsin (float f) inline
Referenced by ComputeFk(), IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
double IKsin (double f) inline
float IKcos (float f) inline
Referenced by ComputeFk(), IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
double IKcos (double f) inline
float IKtan (float f) inline
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
double IKtan (double f) inline
float IKsqrt (float f) inline
Referenced by IKSolver::ComputeIk(), IKSolver::polyroots2(), and IKSolver::rotationfunction0().
double IKsqrt (double f) inline
float IKatan2Simple (float fy, float fx) inline
Referenced by IKatan2WithCheck().
float IKatan2 (float fy, float fx) inline
References IKFAST_ASSERT, and IKPI_2.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
double IKatan2Simple (double fy, double fx) inline
double IKatan2 (double fy, double fx) inline
References IKFAST_ASSERT, and IKPI_2.
template<typename T > CheckValue<T> IKatan2WithCheck (T fy, T fx, T epsilon) inline
References IKabs(), IKatan2Simple(), IKFAST_ATAN2_MAGTHRESH, CheckValue< T >::valid, and CheckValue< T >::value.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
float IKsign (float f) inline
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
double IKsign (double f) inline
template<typename T > CheckValue<T> IKPowWithIntegerCheck (T f, int n) inline
References CheckValue< T >::valid, and CheckValue< T >::value.
Referenced by IKSolver::ComputeIk(), and IKSolver::rotationfunction0().
IKFAST_API void ComputeFk (const IkReal * j, IkReal * eetrans, IkReal * eerot)
solves the forward kinematics equations.
Parameters
pfree is an array specifying the free joints of the chain.
References IKcos(), IKsin(), and x0.
Referenced by TEST().
IKFAST_API int GetNumFreeParameters ()
Referenced by ct::rbd::Irb4600InverseKinematics< SCALAR >::computeInverseKinematics(), ct::rbd::HyAInverseKinematics< SCALAR >::computeInverseKinematics(), and main().
IKFAST_API int* GetFreeParameters ()
IKFAST_API int GetNumJoints ()
Referenced by main().
IKFAST_API int GetIkRealSize ()
IKFAST_API int GetIkType ()
IKFAST_API bool ComputeIk (const IkReal * eetrans, const IkReal * eerot, const IkReal * pfree, IkSolutionListBase< IkReal > & solutions)
solves the inverse kinematics equations.
Parameters
pfree is an array specifying the free joints of the chain.
References IKSolver::ComputeIk().
Referenced by ct::rbd::Irb4600InverseKinematics< SCALAR >::computeInverseKinematics(), ct::rbd::HyAInverseKinematics< SCALAR >::computeInverseKinematics(), and main().
IKFAST_API bool ComputeIk2 (const IkReal * eetrans, const IkReal * eerot, const IkReal * pfree, IkSolutionListBase< IkReal > & solutions, void * pOpenRAVEManip)
References IKSolver::ComputeIk().
IKFAST_API const char* GetKinematicsHash ()
IKFAST_API const char* GetIkFastVersion ()
References IKFAST_NAMESPACE.
int main (int argc, char ** argv)
References ComputeIk(), ikfast::IkSolutionBase< class >::GetFree(), GetNumFreeParameters(), GetNumJoints(), ikfast::IkSolutionList< class >::GetNumSolutions(), ikfast::IkSolutionBase< class >::GetSolution(), ikfast::IkSolutionList< class >::GetSolution(), and i.