/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/test/HyA/HyATest.cpp File Reference
HyATest.cpp File Reference
#include <memory>
#include <array>
#include <iostream>
#include <Eigen/Dense>
#include <gtest/gtest.h>
#include <ct/core/core.h>
#include <ct/rbd/rbd.h>
#include "ct/models/HyA/HyA.h"
Macros
#define Debug
Functions
TEST (HyaLinearizerTest, NumDiffComparison)
TEST (CodegenLinearizerTest, NumDiffComparison)
TEST (IntegratorTest, IntegratorTestHya)
int main (int argc, char **argv)
Macro Definition Documentation
Debug
#define Debug
Function Documentation
TEST() [1/3]
TEST (HyaLinearizerTest , NumDiffComparison)
References ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeState(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), i, u, and x.
TEST() [2/3]
TEST (CodegenLinearizerTest , NumDiffComparison)
References ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeControl(), ct::models::HyA::HyALinearizedForward::getDerivativeControl(), ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeState(), ct::models::HyA::HyALinearizedForward::getDerivativeState(), i, u, and x.
TEST() [3/3]
TEST (IntegratorTest , IntegratorTestHya)
References dt, ct::core::EULER, ct::core::EULERCT, i, ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::core::RK4, and ct::core::RK4CT.
main()
int main (int argc, char ** argv)