/home/adrl/code/src/control-toolbox/ct_models/src/HyQ/codegen/HyQLinearizationCodegen.cpp File Reference
HyQLinearizationCodegen.cpp File Reference
#include <ct/optcon/optcon.h>
#include <ct/rbd/rbd.h>
#include <ct/models/HyQ/HyQ.h>
#include <ct/models/CodegenOutputDirs.h>
#include "helperFunctions.h"
Typedefs
typedef CppAD::AD< CppAD::cg::CG< double > > SCALAR
typedef SCALAR::value_type AD_ValueType
typedef ct::rbd::FloatingBaseFDSystem< ct::rbd::HyQ::tpl::Dynamics< SCALAR >, false > HyQSystemAD
Functions
void generateInverseDynamics ()
void generateForwardKinematics ()
void generateForwardZeroForwardDynamics ()
void generateFDLinearization (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
const size_t state_dim = HyQSystemAD::STATE_DIM
const size_t control_dim = HyQSystemAD::CONTROL_DIM
const size_t njoints = HyQSystemAD::Kinematics::NJOINTS
Typedef Documentation
typedef CppAD::AD<CppAD::cg::CG<double> > SCALAR
typedef SCALAR::value_type AD_ValueType
typedef ct::rbd::FloatingBaseFDSystem<ct::rbd::HyQ::tpl::Dynamics<SCALAR>, false> HyQSystemAD
Function Documentation
void generateInverseDynamics ()
References ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateJacobianSource().
Referenced by main().
void generateForwardKinematics ()
References ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateJacobianSource().
Referenced by main().
void generateForwardZeroForwardDynamics ()
References ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateForwardZeroSource().
Referenced by main().
void generateFDLinearization (int argc, char * argv[])
References ct::core::ADCodegenLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::generateCode().
Referenced by main().
int main (int argc, char * argv[])
References generateFDLinearization(), generateForwardKinematics(), generateForwardZeroForwardDynamics(), and generateInverseDynamics().
Variable Documentation
const size_t state_dim = HyQSystemAD::STATE_DIM
const size_t control_dim = HyQSystemAD::CONTROL_DIM
const size_t njoints = HyQSystemAD::Kinematics::NJOINTS