/home/adrl/code/src/control-toolbox/ct_models/test/IKFast/IKFastTestIrb4600.cpp File Reference
IKFastTestIrb4600.cpp File Reference
#include <ct/models/Irb4600/Irb4600InverseKinematics.h>
#include <ct/rbd/rbd.h>
#include <ct/rbd/state/JointState.h>
#include <gtest/gtest.h>
Functions
TEST (Irb4600IKTest, IKFastTest)
int main (int argc, char **argv)
Function Documentation
TEST (Irb4600IKTest , IKFastTest)
References ComputeFk(), ct::rbd::Irb4600InverseKinematics< SCALAR >::computeInverseKinematics(), i, ct::rbd::tpl::RigidBodyPose< SCALAR >::position(), and ct::rbd::JointState< NJOINTS, SCALAR >::setRandom().
int main (int argc, char ** argv)