/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/test/IKFast/IKFastTestHyA.cpp File Reference
IKFastTestHyA.cpp File Reference
#include <ct/models/HyA/HyAInverseKinematics.h>
#include <ct/rbd/rbd.h>
#include <ct/rbd/state/JointState.h>
#include <ct/models/HyA/HyA.h>
#include <gtest/gtest.h>
Functions
TEST (HyAIKTest, FKTest)
TEST (HyAIKTest, IKFastTest)
TEST (HyAIKTest, IKFastTest_closeTo)
int main (int argc, char **argv)
Function Documentation
TEST() [1/3]
TEST (HyAIKTest , FKTest)
References ComputeFk(), i, and ct::rbd::JointState< NJOINTS, SCALAR >::setRandom().
TEST() [2/3]
TEST (HyAIKTest , IKFastTest)
References ct::rbd::HyAInverseKinematics< SCALAR >::computeInverseKinematics(), i, ct::rbd::tpl::RigidBodyPose< SCALAR >::setIdentity(), and ct::rbd::JointState< NJOINTS, SCALAR >::setRandom().
TEST() [3/3]
TEST (HyAIKTest , IKFastTest_closeTo)
References ct::rbd::InverseKinematicsBase< 6, SCALAR >::computeInverseKinematicsCloseTo(), i, ct::rbd::tpl::RigidBodyPose< SCALAR >::setIdentity(), and ct::rbd::JointState< NJOINTS, SCALAR >::setRandom().
main()
int main (int argc, char ** argv)