/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/CMakeLists.txt File Reference
/home/adrl/code/src/control-toolbox/ct_models/include/ct/models/QuadrotorWithLoad/generated/CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 2.8) project(gen_ct_quadrotor) set(EIGEN_ROOT $ENV
CACHE PATH Path to Eigen headers set (IIT_RBD_ROOT $ENV{IIT_RBD_ROOT}CACHE PATH"Path to iit-rbd headers") set(HEADER_INSTALL_ROOT/usr/local/include/CACHE PATH"Where to install ct_quadrotor headers") set(LIB_INSTALL_ROOT/usr/local/lib/CACHE PATH"Where to install ct_quadrotor library") set(LIB_NAME iitgenct_quadrotor) set(HEADERS./declarations.h./link_data_map.h./joint_data_map.h./transforms.h./kinematics_parameters.h./jacobians.h./traits.h./jsim.h./inverse_dynamics.h./forward_dynamics.h./inertia_properties.h./dynamics_parameters.h./miscellaneous.h) set(SOURCES./transforms.cpp./jacobians.cpp./jsim.cpp./inverse_dynamics.cpp./forward_dynamics.cpp./inertia_properties.cpp./miscellaneous.cpp) include_directories($
include_directories (${IIT_RBD_ROOT}) add_library($
Function Documentation
cmake_minimum_required (VERSION 2. 8)
CACHE PATH Path to Eigen headers set (IIT_RBD_ROOT $ENV{IIT_RBD_ROOT}CACHE PATH"Path to iit-rbd headers")
References include(), include_directories(), and lib.
include_directories (${IIT_RBD_ROOT})
References add_library(), and the.