ct::models::HyQ Namespace Reference
ct::models::HyQ Namespace Reference
Classes
class HyQBareModelLinearizedForward
class HyQBareModelLinearizedReverse
class HyQContactModelForwardZeroSystem
A floating base rigid body system that uses forward dynamics. The input vector is assumed to consist of joint torques and end-effector forces expressed in the world.
class HyQForwardKinJacForward
class HyQForwardKinJacReverse
class HyQForwardZero
class HyQInverseDynJacForward
class HyQInverseDynJacReverse
class HyQWithContactModelLinearizedForward
class HyQWithContactModelLinearizedReverse
Typedefs
typedef ct::rbd::FloatingBaseFDSystem< ct::rbd::HyQ::tpl::Dynamics< double >, false > HyQSystem
template<typename SCALAR >
using ContactModel = ct::rbd::EEContactModel< ct::rbd::HyQ::tpl::Kinematics< SCALAR > >
Functions
template<typename SCALAR >
Eigen::Matrix< SCALAR, control_dim+6, 1 > hyqInverseDynamics (const Eigen::Matrix< SCALAR, state_dim+18, 1 > &x)
template<typename SCALAR >
Eigen::Matrix< SCALAR, nEE *6, 1 > hyqForwardKinematics (const Eigen::Matrix< SCALAR, state_dim, 1 > &x)
template<typename SCALAR >
Eigen::Matrix< SCALAR, state_dim, 1 > hyqContactModelForwardDynamics (const Eigen::Matrix< SCALAR, state_dim+control_dim+1, 1 > &x)
Variables
const size_t state_dim = HyQSystem::STATE_DIM
const size_t control_dim = HyQSystem::CONTROL_DIM
const size_t njoints = HyQSystem::Kinematics::NJOINTS
const size_t nEE = HyQSystem::Kinematics::NUM_EE
Typedef Documentation
HyQSystem
typedef ct::rbd::FloatingBaseFDSystem<ct::rbd::HyQ::tpl::Dynamics<double>, false> ct::models::HyQ::HyQSystem
ContactModel
template<typename SCALAR > using ct::models::HyQ::ContactModel = typedef ct::rbd::EEContactModel<ct::rbd::HyQ::tpl::Kinematics<SCALAR> >
Function Documentation
hyqInverseDynamics()
template<typename SCALAR > Eigen::Matrix<SCALAR, control_dim + 6, 1> ct::models::HyQ::hyqInverseDynamics (const Eigen::Matrix< SCALAR, state_dim+18, 1 > & x)
References ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorEulerXyz(), and u.
hyqForwardKinematics()
template<typename SCALAR > Eigen::Matrix<SCALAR, nEE * 6, 1> ct::models::HyQ::hyqForwardKinematics (const Eigen::Matrix< SCALAR, state_dim, 1 > & x)
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorEulerXyz(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), and nEE.
hyqContactModelForwardDynamics()
template<typename SCALAR > Eigen::Matrix<SCALAR, state_dim, 1> ct::models::HyQ::hyqContactModelForwardDynamics (const Eigen::Matrix< SCALAR, state_dim+control_dim+1, 1 > & x)
References ct::rbd::FloatingBaseFDSystem< RBDDynamics, QUAT_INTEGRATION, EE_ARE_CONTROL_INPUTS >::setContactModel().
Variable Documentation
state_dim
const size_t ct::models::HyQ::state_dim = HyQSystem::STATE_DIM
Referenced by timing().
control_dim
const size_t ct::models::HyQ::control_dim = HyQSystem::CONTROL_DIM
Referenced by timing().
njoints
const size_t ct::models::HyQ::njoints = HyQSystem::Kinematics::NJOINTS
nEE
const size_t ct::models::HyQ::nEE = HyQSystem::Kinematics::NUM_EE
Referenced by hyqForwardKinematics(), and timing().