ct::models Namespace Reference
ct::models Namespace Reference
Namespaces
DoubleInvertedPendulum
HyA
HyQ
InvertedPendulum
quadrotor
Classes
class Quadrotor
class QuadrotorLinear
Functions
quadrotor::state_matrix_t A_quadrotor (const quadrotor::state_vector_t &x, const quadrotor::control_vector_t &u)
quadrotor::control_gain_matrix_t B_quadrotor (const quadrotor::state_vector_t &x, const quadrotor::control_vector_t &u)
quadrotor::state_vector_t quadrotor_ode (const quadrotor::state_vector_t &x, const quadrotor::control_vector_t &u)
quadrotor::control_gain_matrix_t C_quadrotor (const quadrotor::state_vector_t &x, const quadrotor::control_vector_t &u)
Function Documentation
quadrotor::state_matrix_t ct::models::A_quadrotor (const quadrotor::state_vector_t & x, const quadrotor::control_vector_t & u)
References ct::models::quadrotor::mQ, ct::models::quadrotor::Thxxyy, and ct::models::quadrotor::Thzz.
Referenced by ct::models::QuadrotorLinear::getDerivativeState().
quadrotor::control_gain_matrix_t ct::models::B_quadrotor (const quadrotor::state_vector_t & x, const quadrotor::control_vector_t & u)
References ct::models::quadrotor::mQ, ct::models::quadrotor::Thxxyy, and ct::models::quadrotor::Thzz.
Referenced by ct::models::QuadrotorLinear::getDerivativeControl().
quadrotor::state_vector_t ct::models::quadrotor_ode (const quadrotor::state_vector_t & x, const quadrotor::control_vector_t & u)
References ct::models::quadrotor::mQ, ct::models::quadrotor::Thxxyy, and ct::models::quadrotor::Thzz.
Referenced by ct::models::Quadrotor::computeControlledDynamics().
quadrotor::control_gain_matrix_t ct::models::C_quadrotor (const quadrotor::state_vector_t & x, const quadrotor::control_vector_t & u)
References ct::models::quadrotor::mQ, ct::models::quadrotor::Thxxyy, and ct::models::quadrotor::Thzz.