iit::ct_DoubleInvertedPendulum Namespace Reference
iit::ct_DoubleInvertedPendulum Namespace Reference
Namespaces
dyn
tpl
Classes
class JointDataMap
class LinkDataMap
Typedefs
using Column2d = tpl::Column2d< double >
typedef Column2d JointState
typedef tpl::Traits< double > Traits
Enumerations
enum JointIdentifiers { JOINT1 = 0, JOINT2 }
enum LinkIdentifiers { DOUBLEINVERTEDPENDULUMBASE = 0, LINK1, LINK2 }
Functions
template<typename T >
std::ostream & operator<< (std::ostream &out, const JointDataMap< T > &map)
template<typename T >
std::ostream & operator<< (std::ostream &out, const LinkDataMap< T > &map)
Center of mass calculation
Computes the Center Of Mass (COM) position of the whole robot, in base coordinates.
Common parameters are the inertia properties of the robot and the set of homogeneous coordinate transforms. If a joint status variable is also passed, then the transforms are updated accordingly; otherwise, they are not modified before being used.
iit::rbd::Vector3d getWholeBodyCOM (const dyn::InertiaProperties &inertia, const HomogeneousTransforms &transforms)
iit::rbd::Vector3d getWholeBodyCOM (const dyn::InertiaProperties &inertia, const JointState &q, HomogeneousTransforms &transforms)
Typedef Documentation
Column2d
using iit::ct_DoubleInvertedPendulum::Column2d = typedef tpl::Column2d<double>
JointState
typedef Column2d iit::ct_DoubleInvertedPendulum::JointState
Traits
typedef tpl::Traits<double> iit::ct_DoubleInvertedPendulum::Traits
Enumeration Type Documentation
JointIdentifiers
enum iit::ct_DoubleInvertedPendulum::JointIdentifiers
Enumerator
JOINT1
JOINT2
LinkIdentifiers
enum iit::ct_DoubleInvertedPendulum::LinkIdentifiers
Enumerator
DOUBLEINVERTEDPENDULUMBASE
LINK1
LINK2
Function Documentation
operator<<() [1/2]
template<typename T > std::ostream& iit::ct_DoubleInvertedPendulum::operator<< (std::ostream & out, const JointDataMap< T > & map) inline
References JOINT1, and JOINT2.
operator<<() [2/2]
template<typename T > std::ostream& iit::ct_DoubleInvertedPendulum::operator<< (std::ostream & out, const LinkDataMap< T > & map) inline
References DOUBLEINVERTEDPENDULUMBASE, LINK1, and LINK2.
getWholeBodyCOM() [1/2]
iit::rbd::Vector3d iit::ct_DoubleInvertedPendulum::getWholeBodyCOM (const dyn::InertiaProperties & inertia, const HomogeneousTransforms & transforms)
Parameters
inertia the inertia properties of the links of the robot
transforms the homogeneous coordinate transforms of the robot
Returns
the position of the Center Of Mass of the whole robot, expressed in base coordinates
References iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Link1(), iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getCOM_Link2(), iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getMass_Link1(), iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getMass_Link2(), iit::ct_DoubleInvertedPendulum::dyn::tpl::InertiaProperties< TRAIT >::getTotalMass(), and iit::rbd::Utils::transform().
Referenced by getWholeBodyCOM().
getWholeBodyCOM() [2/2]
iit::rbd::Vector3d iit::ct_DoubleInvertedPendulum::getWholeBodyCOM (const dyn::InertiaProperties & inertia, const JointState & q, HomogeneousTransforms & transforms)
Parameters
inertia the inertia properties of the links of the robot
q the joint status vector describing the configuration of the robot
transforms the homogeneous coordinate transforms of the robot
Returns
the position of the Center Of Mass of the whole robot, expressed in base coordinates
References getWholeBodyCOM().