/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_models/examples/mpc/InvertedPendulum/NLOC_MPC.cpp File Reference
NLOC_MPC.cpp File Reference
#include <ct/rbd/rbd.h>
#include "../../exampleDir.h"
#include <ct/models/InvertedPendulum/InvertedPendulum.h>
Classes
class MPCSimulator
Typedefs
using RobotState_t = ct::rbd::FixBaseRobotState< njoints, actuator_state_dim >
using IPDynamics = ct::rbd::InvertedPendulum::tpl::Dynamics< double >
using IPSystem = ct::rbd::FixBaseFDSystem< IPDynamics, actuator_state_dim, false >
using LinearSystem = ct::core::LinearSystem< state_dim, control_dim, double >
using InvertedPendulumNLOC = FixBaseNLOC< IPSystem >
Functions
int main (int argc, char *argv[])
Variables
const size_t njoints = ct::rbd::InvertedPendulum::Kinematics::NJOINTS
const size_t actuator_state_dim = 1
Typedef Documentation
RobotState_t
using RobotState_t = ct::rbd::FixBaseRobotState<njoints, actuator_state_dim>
IPDynamics
using IPDynamics = ct::rbd::InvertedPendulum::tpl::Dynamics<double>
IPSystem
using IPSystem = ct::rbd::FixBaseFDSystem<IPDynamics, actuator_state_dim, false>
LinearSystem
using LinearSystem = ct::core::LinearSystem<state_dim, control_dim, double>
InvertedPendulumNLOC
using InvertedPendulumNLOC = FixBaseNLOC<IPSystem>
Function Documentation
main()
int main (int argc, char * argv[])
References ct::optcon::mpc_settings::coldStart_, costFunctionFile, ct::optcon::mpc_settings::delayMeasurementMultiplier_, ct::core::ControlSimulator< class >::finish(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVector(), i, ct::optcon::NLOptConSettings::load(), ct::core::loadMatrix(), ct::core::loadScalar(), ct::optcon::NLOptConSettings::max_iterations, ct::optcon::mpc_settings::measureDelay_, ct::optcon::mpc_settings::minimumTimeHorizonMpc_, ct::optcon::mpc_settings::mpc_mode, ct::optcon::mpc_settings::postTruncation_, ct::optcon::MPC< OPTCON_SOLVER >::printMpcSummary(), ct::optcon::MPC< OPTCON_SOLVER >::setInitialGuess(), ct::core::ControlSimulator< class >::simulate(), ct::optcon::mpc_settings::stateForwardIntegration_, timeHorizon, ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVector(), verbose, x0, and ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::x_ref().
Variable Documentation
njoints
const size_t njoints = ct::rbd::InvertedPendulum::Kinematics::NJOINTS
actuator_state_dim
const size_t actuator_state_dim = 1