ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference abstract
Constraint
Base class for the constraints used in this toolbox.
#include <ConstraintBase.h>
Public Types
typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > MatrixXs
Public Member Functions
ConstraintBase (std::string name="Unnamed")
Custom constructor.
ConstraintBase (const ConstraintBase &arg)
Copy constructor.
virtual ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const =0
Creates a new instance of the object with same properties than original.
virtual ~ConstraintBase ()
Destructor.
virtual VectorXs evaluate (const state_vector_t &x, const control_vector_t &u, const SCALAR t)=0
The evaluation of the constraint violation. Note this method is SCALAR typed.
virtual Eigen::Matrix< ct::core::ADCGScalar, Eigen::Dynamic, 1 > evaluateCppadCg (const core::StateVector< STATE_DIM, ct::core::ADCGScalar > &x, const core::ControlVector< CONTROL_DIM, ct::core::ADCGScalar > &u, ct::core::ADCGScalar t)
The evaluate method used for jit compilation in constraint container ad.
virtual size_t getConstraintSize () const =0
Returns the number of constraints.
virtual MatrixXs jacobianState (const state_vector_t &x, const control_vector_t &u, const SCALAR t)
Returns the constraint jacobian wrt state.
virtual MatrixXs jacobianInput (const state_vector_t &x, const control_vector_t &u, const SCALAR t)
Returns the constraint jacobian wrt input.
virtual VectorXs getLowerBound () const
Returns the lower constraint bound.
virtual VectorXs getUpperBound () const
Returns the upper constraint bound.
void getName (std::string &constraintName) const
Returns the constraint name.
void setName (const std::string constraintName)
Sets the constraint name.
virtual size_t getNumNonZerosJacobianState () const
Returns the number of nonzeros in the jacobian wrt state. The default implementation assumes a dense matrix with only nonzero elements.
virtual size_t getNumNonZerosJacobianInput () const
Returns the number of nonzeros in the jacobian wrt control input. The default implementation assumes a dense matrix with only nonzero elements.
virtual VectorXs jacobianStateSparse (const state_vector_t &x, const control_vector_t &u, const SCALAR t)
Returns the constraint jacobian wrt state in sparse structure. The default implementation maps the JacobianState matrix to a vector.
virtual VectorXs jacobianInputSparse (const state_vector_t &x, const control_vector_t &u, const SCALAR t)
Returns the constraint jacobian wrt control input in sparse structure. The default implementation maps the JacobianState matrix to a vector.
virtual void sparsityPatternState (Eigen::VectorXi &rows, Eigen::VectorXi &cols)
Generates the sparsity pattern of the jacobian wrt state. The default implementation returns a vector of ones corresponding to the dense jacobianState.
virtual void sparsityPatternInput (Eigen::VectorXi &rows, Eigen::VectorXi &cols)
Generates the sparsity pattern of the jacobian wrt control input. The default implementation returns a vector of ones corresponding to the dense jacobianInput.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::tpl::TraitSelector< SCALAR >::Trait Trait
Static Protected Member Functions
static void genDiagonalIndices (const size_t num_elements, Eigen::VectorXi &iRow_vec, Eigen::VectorXi &jCol_vec)
upper bound on the constraints
static void genSparseDiagonalIndices (const Eigen::VectorXi &diag_sparsity, Eigen::VectorXi &iRow_vec, Eigen::VectorXi &jCol_vec)
Generates indices of a sparse diagonal square matrix.
static void genBlockIndices (const size_t num_rows, const size_t num_cols, Eigen::VectorXi &iRow_vec, Eigen::VectorXi &jCol_vec)
Generates indices of a full matrix.
Protected Attributes
VectorXs lb_
VectorXs ub_
lower bound on the constraints
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >
Base class for the constraints used in this toolbox.
Template Parameters
STATE_DIM The state dimension
CONTROL_DIM The control dimension
SCALAR The Scalar type
Examples:
ConstraintComparison.h, ConstraintTest.h, and NLOC_generalConstrained.cpp.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::StateVector<STATE_DIM, SCALAR> ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, Eigen::Dynamic> ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintBase (std::string name = "Unnamed")
Custom constructor.
Parameters
[in] name The name of the constraint
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintBase (const ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR > & arg)
Copy constructor.
Parameters
[in] arg The object to be copied
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::~ConstraintBase () virtual
Destructor.
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ConstraintBase<STATE_DIM, CONTROL_DIM, SCALAR>* ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const pure virtual
Creates a new instance of the object with same properties than original.
Returns
Copy of this object.
Implemented in StateGenConstraint, ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ControlInputGenConstraint, ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ConstraintTerm1D, ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::PureStateConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ObstacleConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and StateSumConstraint.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual VectorXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate (const state_vector_t & x, const control_vector_t & u, const SCALAR t) pure virtual
The evaluation of the constraint violation. Note this method is SCALAR typed.
Parameters
[in] x The state vector
[in] u The control vector
[in] t The time
Returns
The constraint violation
Implemented in ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::PureStateConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::ObstacleConstraint< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > Eigen::Matrix< ct::core::ADCGScalar, Eigen::Dynamic, 1 > ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateCppadCg (const core::StateVector< STATE_DIM, ct::core::ADCGScalar > & x, const core::ControlVector< CONTROL_DIM, ct::core::ADCGScalar > & u, ct::core::ADCGScalar t) virtual
The evaluate method used for jit compilation in constraint container ad.
Parameters
[in] x The state vector
[in] u The control vector
[in] t The time
Returns
The constraint violation
Reimplemented in ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::PureStateConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual size_t ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getConstraintSize () const pure virtual
Returns the number of constraints.
Returns
The number of constraints
Implemented in ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >, StateGenConstraint, ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ControlInputGenConstraint, ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ConstraintTerm1D, ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::PureStateConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ObstacleConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and StateSumConstraint.
Referenced by ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getNumNonZerosJacobianInput(), ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getNumNonZerosJacobianState(), ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInput(), and ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianState (const state_vector_t & x, const control_vector_t & u, const SCALAR t) virtual
Returns the constraint jacobian wrt state.
Returns
The constraint jacobian
Reimplemented in ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::PureStateConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::ObstacleConstraint< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparse().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInput (const state_vector_t & x, const control_vector_t & u, const SCALAR t) virtual
Returns the constraint jacobian wrt input.
Returns
The constraint jacobian
Reimplemented in ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::ObstacleConstraint< STATE_DIM, CONTROL_DIM, SCALAR >.
Examples:
ConstraintTest.h.
Referenced by ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparse().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getLowerBound () const virtual
Returns the lower constraint bound.
Returns
The lower constraint bound
References ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::lb_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getUpperBound () const virtual
Returns the upper constraint bound.
Returns
The upper constraint bound
References ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::ub_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getName (std::string & constraintName) const
Returns the constraint name.
Parameters
[out] constraintName The constraint name
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::setName (const std::string constraintName)
Sets the constraint name.
Parameters
[in] constraintName The constraint name
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getNumNonZerosJacobianState () const virtual
Returns the number of nonzeros in the jacobian wrt state. The default implementation assumes a dense matrix with only nonzero elements.
Returns
The number of non zeros
Reimplemented in ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getConstraintSize().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getNumNonZerosJacobianInput () const virtual
Returns the number of nonzeros in the jacobian wrt control input. The default implementation assumes a dense matrix with only nonzero elements.
Returns
The number of non zeros
Reimplemented in ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getConstraintSize().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparse (const state_vector_t & x, const control_vector_t & u, const SCALAR t) virtual
Returns the constraint jacobian wrt state in sparse structure. The default implementation maps the JacobianState matrix to a vector.
Returns
The sparse constraint jacobian
Reimplemented in ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparse (const state_vector_t & x, const control_vector_t & u, const SCALAR t) virtual
Returns the constraint jacobian wrt control input in sparse structure. The default implementation maps the JacobianState matrix to a vector.
Returns
The sparse constraint jacobian
Reimplemented in ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< CONTROL_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::BoxConstraintBase< STATE_DIM, STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInput().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternState (Eigen::VectorXi & rows, Eigen::VectorXi & cols) virtual
Generates the sparsity pattern of the jacobian wrt state. The default implementation returns a vector of ones corresponding to the dense jacobianState.
Parameters
rows The vector of the row indices containing non zero elements in the constraint jacobian
cols The vector of the column indices containing non zero elements in the constraint jacobian
References ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::genBlockIndices(), and ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getConstraintSize().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInput (Eigen::VectorXi & rows, Eigen::VectorXi & cols) virtual
Generates the sparsity pattern of the jacobian wrt control input. The default implementation returns a vector of ones corresponding to the dense jacobianInput.
Parameters
rows The vector of the row indices containing non zero elements in the constraint jacobian
cols The vector of the column indices containing non zero elements in the constraint jacobian
References ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::genBlockIndices(), and ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getConstraintSize().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::genDiagonalIndices (const size_t num_elements, Eigen::VectorXi & iRow_vec, Eigen::VectorXi & jCol_vec) static protected
upper bound on the constraints
Generates indices of a diagonal square matrix
Parameters
[in] num_elements The number of elements
[out] iRow_vec The row vector
[out] jCol_vec The column vector
References count, and i.
Referenced by ct::optcon::TerminalConstraint< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::genSparseDiagonalIndices (const Eigen::VectorXi & diag_sparsity, Eigen::VectorXi & iRow_vec, Eigen::VectorXi & jCol_vec) static protected
Generates indices of a sparse diagonal square matrix.
Parameters
[in] diag_sparsity Sparsity pattern for the diagonal (Example: [0 1 0 0 1 1])
[out] iRow_vec The row vector
[out] jCol_vec The column vector
References count, and i.
Referenced by ct::optcon::BoxConstraintBase< DERIVED_DIM, STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternSparseJacobian().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::genBlockIndices (const size_t num_rows, const size_t num_cols, Eigen::VectorXi & iRow_vec, Eigen::VectorXi & jCol_vec) static protected
Generates indices of a full matrix.
Parameters
[in] num_rows The number of rows of the matrix
[in] num_cols The number columns of the matrix
[out] iRow_vec The row vector
[out] jCol_vec The col vector
References count.
Referenced by ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInput(), and ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternState().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::tpl::TraitSelector<SCALAR>::Trait ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::Trait
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> VectorXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::lb_ protected
Examples:
ConstraintComparison.h, and ConstraintTest.h.
Referenced by ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintTerm1D(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintTerm2D(), ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getLowerBound(), ct::optcon::ObstacleConstraint< STATE_DIM, CONTROL_DIM, SCALAR >::ObstacleConstraint(), ct::optcon::example::PureStateConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >::PureStateConstraint_Example(), and ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >::StateInputConstraint_Example().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> VectorXs ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::ub_ protected
lower bound on the constraints
Examples:
ConstraintComparison.h, and ConstraintTest.h.
Referenced by ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintTerm1D(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintTerm2D(), ct::optcon::ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >::getUpperBound(), ct::optcon::ObstacleConstraint< STATE_DIM, CONTROL_DIM, SCALAR >::ObstacleConstraint(), ct::optcon::example::PureStateConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >::PureStateConstraint_Example(), and ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >::StateInputConstraint_Example().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/constraint/term/ConstraintBase.h
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/constraint/term/ConstraintBase-impl.h