ct::optcon::IpoptSettings Class Reference
ct::optcon::IpoptSettings Class Reference
NLP
IPOPT settings. Details about the parameters can be found in the IPOPT documentation.
#include <NlpSolverSettings.h>
Public Member Functions
IpoptSettings ()
Default constructor, sets the parameters to default values.
void print ()
Prints out information about the settings.
bool parametersOk () const
Checks whether to settings are filled with meaningful values.
void load (const std::string &filename, bool verbose=true, const std::string &ns="dms.nlp.ipopt")
Loads the settings from a .info file.
Static Public Member Functions
template<typename TYPE >
static void setParameterIfExists (const boost::property_tree::ptree &pt, TYPE &param, const std::string &param_name, const std::string &ns)
Public Attributes
double tol_
double constr_viol_tol_
int max_iter_
double restoTol_
double acceptableTol_
double restoAcceptableTol_
std::string linear_scaling_on_demand_
std::string hessian_approximation_
std::string nlp_scaling_method_
int printLevel_
std::string print_user_options_
int print_frequency_iter_
std::string printInfoString_
std::string derivativeTest_
double derivativeTestTol_
double derivativeTestPerturbation_
double point_perturbation_radius_
std::string checkDerivativesForNaninf_
std::string derivativeTestPrintAll_
std::string linearSystemScaling_
std::string linear_solver_
std::string jacobianApproximation_
Detailed Description
IPOPT settings. Details about the parameters can be found in the IPOPT documentation.
Constructor & Destructor Documentation
IpoptSettings()
ct::optcon::IpoptSettings::IpoptSettings () inline
Default constructor, sets the parameters to default values.
Member Function Documentation
print()
void ct::optcon::IpoptSettings::print () inline
Prints out information about the settings.
Referenced by ct::optcon::NlpSolverSettings::print().
parametersOk()
bool ct::optcon::IpoptSettings::parametersOk () const inline
Checks whether to settings are filled with meaningful values.
Returns
Returns true of the parameters are ok
Referenced by ct::optcon::NlpSolverSettings::parametersOk().
load()
void ct::optcon::IpoptSettings::load (const std::string & filename, bool verbose = true, const std::string & ns = "dms.nlp.ipopt") inline
Loads the settings from a .info file.
Parameters
[in] filename The filename
[in] verbose True if parameters to be printed out
[in] ns The namespace in the .info fil
Referenced by ct::optcon::NlpSolverSettings::load().
setParameterIfExists()
template<typename TYPE > static void ct::optcon::IpoptSettings::setParameterIfExists (const boost::property_tree::ptree & pt, TYPE & param, const std::string & param_name, const std::string & ns) inline static
Member Data Documentation
tol_
double ct::optcon::IpoptSettings::tol_
constr_viol_tol_
double ct::optcon::IpoptSettings::constr_viol_tol_
max_iter_
int ct::optcon::IpoptSettings::max_iter_
restoTol_
double ct::optcon::IpoptSettings::restoTol_
acceptableTol_
double ct::optcon::IpoptSettings::acceptableTol_
restoAcceptableTol_
double ct::optcon::IpoptSettings::restoAcceptableTol_
linear_scaling_on_demand_
std::string ct::optcon::IpoptSettings::linear_scaling_on_demand_
hessian_approximation_
std::string ct::optcon::IpoptSettings::hessian_approximation_
Referenced by main().
nlp_scaling_method_
std::string ct::optcon::IpoptSettings::nlp_scaling_method_
printLevel_
int ct::optcon::IpoptSettings::printLevel_
print_user_options_
std::string ct::optcon::IpoptSettings::print_user_options_
print_frequency_iter_
int ct::optcon::IpoptSettings::print_frequency_iter_
printInfoString_
std::string ct::optcon::IpoptSettings::printInfoString_
derivativeTest_
std::string ct::optcon::IpoptSettings::derivativeTest_
Referenced by main().
derivativeTestTol_
double ct::optcon::IpoptSettings::derivativeTestTol_
derivativeTestPerturbation_
double ct::optcon::IpoptSettings::derivativeTestPerturbation_
point_perturbation_radius_
double ct::optcon::IpoptSettings::point_perturbation_radius_
checkDerivativesForNaninf_
std::string ct::optcon::IpoptSettings::checkDerivativesForNaninf_
derivativeTestPrintAll_
std::string ct::optcon::IpoptSettings::derivativeTestPrintAll_
linearSystemScaling_
std::string ct::optcon::IpoptSettings::linearSystemScaling_
linear_solver_
std::string ct::optcon::IpoptSettings::linear_solver_
jacobianApproximation_
std::string ct::optcon::IpoptSettings::jacobianApproximation_
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/nlp/solver/NlpSolverSettings.h