ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
Constraint
A container for switching linear constraint containers.
#include <SwitchedLinearConstraintContainer.h>
Public Types
typedef core::ControlVector< CONTROL_DIM, SCALAR > input_vector_t
typedef SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > * SwitchedLinearConstraintContainer_Raw_Ptr_t
typedef std::shared_ptr< LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > > LinearConstraintContainer_Ptr_t
typedef core::Switched< LinearConstraintContainer_Ptr_t > SwitchedLinearConstraintContainers
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > MatrixXs
typedef core::PhaseSequence< std::size_t, SCALAR > ModeSequence_t
Public Types inherited from ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
typedef core::ControlVector< CONTROL_DIM, SCALAR > input_vector_t
typedef LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > * LinearConstraintContainer_Raw_Ptr_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > MatrixXs
Public Types inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
typedef core::ControlVector< CONTROL_DIM, SCALAR > input_vector_t
typedef ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR > * ConstraintBase_Raw_Ptr_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
Public Member Functions
SwitchedLinearConstraintContainer (const SwitchedLinearConstraintContainers &switchedLinearConstraintContainers, const ModeSequence_t &continuousModeSequence)
Default constructor.
SwitchedLinearConstraintContainer (const SwitchedLinearConstraintContainer &arg)
Copy constructor.
virtual ~SwitchedLinearConstraintContainer ()
Destructor.
virtual SwitchedLinearConstraintContainer_Raw_Ptr_t clone () const override
virtual VectorXs evaluateIntermediate () override
Evaluates the intermediate constraints.
virtual VectorXs evaluateTerminal () override
Evaluates the terminal constraints.
virtual size_t getIntermediateConstraintsCount () override
Retrieves the number of intermediate constraints.
virtual size_t getTerminalConstraintsCount () override
Retrieves the number of final constraints.
virtual VectorXs jacobianStateSparseIntermediate () override
Evaluates the constraint jacobian wrt the state using sparse representation.
virtual MatrixXs jacobianStateIntermediate () override
Evaluates the constraint jacobian wrt the state.
virtual VectorXs jacobianStateSparseTerminal () override
Evaluates the constraint jacobian wrt the state using sparse representation.
virtual MatrixXs jacobianStateTerminal () override
Evaluates the constraint jacobian wrt the state.
virtual VectorXs jacobianInputSparseIntermediate () override
Evaluates the constraint jacobian wrt the control input using sparse representation.
virtual MatrixXs jacobianInputIntermediate () override
Evaluates the constraint jacobian wrt the control input.
virtual VectorXs jacobianInputSparseTerminal () override
Evaluates the constraint jacobian wrt the control input using sparse representation.
virtual MatrixXs jacobianInputTerminal () override
Evaluates the constraint jacobian wrt the control input.
virtual void sparsityPatternStateIntermediate (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols) override
Returns the sparsity pattern for the jacobian wrt state.
virtual void sparsityPatternStateTerminal (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols) override
Returns the sparsity pattern for the jacobian wrt state.
virtual void sparsityPatternInputIntermediate (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols) override
Returns the sparsity pattern for the jacobian wrt control.
virtual void sparsityPatternInputTerminal (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols) override
Returns the sparsity pattern for the jacobian wrt control.
virtual size_t getJacobianStateNonZeroCountIntermediate () override
Returns the number of non zero elements in the constraint jacobian wrt state.
virtual size_t getJacobianStateNonZeroCountTerminal () override
Returns the number of non zero elements in the constraint jacobian wrt state.
virtual size_t getJacobianInputNonZeroCountIntermediate () override
Returns the number of non zero elements in the constraint jacobian wrt input.
virtual size_t getJacobianInputNonZeroCountTerminal () override
Returns the number of non zero elements in the constraint jacobian wrt input.
virtual bool initializeIntermediate () override
Initializes the intermediate constraints.
virtual bool initializeTerminal () override
Initializes the terminal constraints.
Public Member Functions inherited from ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
LinearConstraintContainer ()
Default constructor.
LinearConstraintContainer (const LinearConstraintContainer &arg)
Copy constructor.
virtual ~LinearConstraintContainer ()
Destructor.
size_t getJacNonZeroCount ()
Returns the number of non zeros in the constraint jacobian wrt to state and input.
void initialize ()
Initializes the constraint container.
bool isInitialized ()
Checks if the constraint container is initialized.
void printout ()
Print out sparsity patterns, jacobians, etc. Serves for quick visual inspection.
Public Member Functions inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
ConstraintContainerBase ()
Default constructor.
ConstraintContainerBase (const ConstraintContainerBase &arg)
copy constructor
virtual ~ConstraintContainerBase ()
Destructor.
virtual void setCurrentStateAndControl (const state_vector_t &x, const input_vector_t &u, const SCALAR t=SCALAR(0.0))
size_t getConstraintsCount ()
Retrieves the total number of constraints.
VectorXs getLowerBoundsIntermediate () const
Retrieves the lower constraint bound on the intermediate constraints.
VectorXs getLowerBoundsTerminal () const
Retrieves the lower constraint bound on the terminal constraints.
VectorXs getUpperBoundsIntermediate () const
Retrieves the upper constraint bound on the intermediate constraints.
VectorXs getUpperBoundsTerminal () const
Retrieves the upper constraint bound on the terminal constraints.
VectorXs getUpperBoundsViolationIntermediate ()
Retrieves the violation of the upper constraint bound on the intermediate constraints.
VectorXs getLowerBoundsViolationIntermediate ()
Retrieves the violation of the lower constraint bound on the intermediate constraints.
VectorXs getUpperBoundsViolationTerminal ()
Retrieves the violation of the upper constraint bound on the terminal constraints.
VectorXs getLowerBoundsViolationTerminal ()
Retrieves the violation of the lower constraint bound on the terminal constraints.
VectorXs getTotalBoundsViolationIntermediate ()
Retrieves the total violation of the constraints bounds on the intermediate constraints.
VectorXs getTotalBoundsViolationTerminal ()
Retrieves the total violation of the constraints bounds on the terminal constraints.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Public Attributes inherited from ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Public Attributes inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Additional Inherited Members
Protected Attributes inherited from ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
bool initializedIntermediate_
bool initializedTerminal_
Protected Attributes inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
state_vector_t x_
input_vector_t u_
SCALAR t_
VectorXs lowerBoundsIntermediate_
VectorXs lowerBoundsTerminal_
VectorXs upperBoundsIntermediate_
VectorXs upperBoundsTerminal_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
A container for switching linear constraint containers.
The LinearConstraintBase Class is the base class for defining the non-linear optimization constraints. This class switches between several of them based on a predefined sequence.
Template Parameters
STATE_DIM Dimension of the state vector
CONTROL_DIM Dimension of the control input vector
Examples:
switched_continuous_optcon.cpp.
Member Typedef Documentation
input_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::input_vector_t
SwitchedLinearConstraintContainer_Raw_Ptr_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef SwitchedLinearConstraintContainer<STATE_DIM, CONTROL_DIM, SCALAR>* ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearConstraintContainer_Raw_Ptr_t
LinearConstraintContainer_Ptr_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef std::shared_ptr<LinearConstraintContainer<STATE_DIM, CONTROL_DIM, SCALAR> > ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::LinearConstraintContainer_Ptr_t
SwitchedLinearConstraintContainers
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::Switched<LinearConstraintContainer_Ptr_t> ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearConstraintContainers
VectorXs
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs
MatrixXs
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, Eigen::Dynamic> ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs
ModeSequence_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::PhaseSequence<std::size_t, SCALAR> ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::ModeSequence_t
Constructor & Destructor Documentation
SwitchedLinearConstraintContainer() [1/2]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearConstraintContainer (const SwitchedLinearConstraintContainers & switchedLinearConstraintContainers, const ModeSequence_t & continuousModeSequence)
Default constructor.
Referenced by ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::clone().
SwitchedLinearConstraintContainer() [2/2]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearConstraintContainer (const SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > & arg)
Copy constructor.
Parameters
[in] arg The object to be copied
References ct::core::PhaseSequence< Phase, Time >::getFinalPhase().
~SwitchedLinearConstraintContainer()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::~SwitchedLinearConstraintContainer () virtual
Destructor.
Member Function Documentation
clone()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearConstraintContainer_Raw_Ptr_t ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const override virtual
Clones the linear constraint class
Returns
pointer to the clone
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearConstraintContainer().
evaluateIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate () override virtual
Evaluates the intermediate constraints.
Returns
The evaluation of the intermediate constraints
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
evaluateTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal () override virtual
Evaluates the terminal constraints.
Returns
The evaluation of the terminal constraints
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
getIntermediateConstraintsCount()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateConstraintsCount () override virtual
Retrieves the number of intermediate constraints.
Returns
The number of intermediate constraints
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
getTerminalConstraintsCount()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getTerminalConstraintsCount () override virtual
Retrieves the number of final constraints.
Returns
The number of final constraints
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
jacobianStateSparseIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseIntermediate () override virtual
Evaluates the constraint jacobian wrt the state using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
jacobianStateIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateIntermediate () override virtual
Evaluates the constraint jacobian wrt the state.
Returns
The jacobian wrt state
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
jacobianStateSparseTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseTerminal () override virtual
Evaluates the constraint jacobian wrt the state using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
jacobianStateTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateTerminal () override virtual
Evaluates the constraint jacobian wrt the state.
Returns
The jacobian wrt state
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
jacobianInputSparseIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseIntermediate () override virtual
Evaluates the constraint jacobian wrt the control input using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
jacobianInputIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputIntermediate () override virtual
Evaluates the constraint jacobian wrt the control input.
Returns
The jacobian wrt control
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
jacobianInputSparseTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseTerminal () override virtual
Evaluates the constraint jacobian wrt the control input using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
jacobianInputTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputTerminal () override virtual
Evaluates the constraint jacobian wrt the control input.
Returns
The jacobian wrt control
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
sparsityPatternStateIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateIntermediate (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) override virtual
Returns the sparsity pattern for the jacobian wrt state.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
sparsityPatternStateTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateTerminal (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) override virtual
Returns the sparsity pattern for the jacobian wrt state.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
sparsityPatternInputIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputIntermediate (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) override virtual
Returns the sparsity pattern for the jacobian wrt control.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
sparsityPatternInputTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputTerminal (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) override virtual
Returns the sparsity pattern for the jacobian wrt control.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
getJacobianStateNonZeroCountIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountIntermediate () override virtual
Returns the number of non zero elements in the constraint jacobian wrt state.
Returns
The number of the non zeros
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
getJacobianStateNonZeroCountTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountTerminal () override virtual
Returns the number of non zero elements in the constraint jacobian wrt state.
Returns
The number of the non zeros
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
getJacobianInputNonZeroCountIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountIntermediate () override virtual
Returns the number of non zero elements in the constraint jacobian wrt input.
Returns
The number of the non zeros
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
getJacobianInputNonZeroCountTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountTerminal () override virtual
Returns the number of non zero elements in the constraint jacobian wrt input.
Returns
The number of the non zeros
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
initializeIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > bool ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializeIntermediate () override virtual
Initializes the intermediate constraints.
Returns
Returns true if the initialization was successful
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
initializeTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > bool ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal () override virtual
Initializes the terminal constraints.
Returns
Returns true if the initialization was successful
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::PhaseSequence< Phase, Time >::getPhaseFromTime(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::lowerBoundsIntermediate_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::lowerBoundsTerminal_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::upperBoundsIntermediate_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::upperBoundsTerminal_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Member Data Documentation
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector<STATE_DIM, SCALAR> ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/constraint/SwitchedLinearConstraintContainer.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/constraint/SwitchedLinearConstraintContainer-impl.h