ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference abstract
CostFunction
Describes a cost function with a quadratic approximation, i.e. one that can compute first and second order derivatives with respect to state and control input. This does NOT mean it has to be a purely quadratic cost function. If you are looking for a purely quadratic cost function, check CostFunctionQuadraticSimple.
#include <CostFunctionQuadratic.hpp>
Public Types
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
typedef CostFunction< STATE_DIM, CONTROL_DIM, SCALAR > BASE
Public Types inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Member Functions
CostFunctionQuadratic ()
CostFunctionQuadratic (const CostFunctionQuadratic &arg)
virtual CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const =0
virtual ~CostFunctionQuadratic ()
virtual size_t addIntermediateTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR >> term, bool verbose=false)
Adds an intermediate term.
virtual void addIntermediateADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, ct::core::ADCGScalar >> term, bool verbose=false)
virtual size_t addFinalTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR >> term, bool verbose=false)
Adds a final term.
virtual void addFinalADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, ct::core::ADCGScalar >> term, bool verbose=false)
virtual void loadFromConfigFile (const std::string &filename, bool verbose=false)
Loads cost function from config file.
virtual state_vector_t stateDerivativeIntermediate ()=0
Computes intermediate-cost first-order derivative with respect to state.
virtual state_vector_t stateDerivativeTerminal ()=0
virtual state_matrix_t stateSecondDerivativeIntermediate ()=0
Computes intermediate-cost second-order derivative with respect to state.
virtual state_matrix_t stateSecondDerivativeTerminal ()=0
Computes final-cost second-order derivative with respect to state.
virtual control_vector_t controlDerivativeIntermediate ()=0
Computes intermediate-cost first-order derivative with respect to control.
virtual control_vector_t controlDerivativeTerminal ()
Computes terminal-cost first-order derivative with respect to control.
virtual control_matrix_t controlSecondDerivativeIntermediate ()=0
Computes intermediate-cost second-order derivative with respect to input.
virtual control_matrix_t controlSecondDerivativeTerminal ()
Computes final-cost second-order derivative with respect to input.
virtual control_state_matrix_t stateControlDerivativeIntermediate ()=0
Computes intermediate-cost derivative with respect to state and control.
virtual control_state_matrix_t stateControlDerivativeTerminal ()
Computes final-cost derivative with respect to state and control.
virtual void updateReferenceState (const state_vector_t &x_ref)
update the reference state for intermediate cost terms
virtual void updateFinalState (const state_vector_t &x_final)
update the reference state for final cost terms
virtual void updateReferenceControl (const control_vector_t &u_ref)
update the reference control for intermediate cost terms
bool stateDerivativeIntermediateTest (bool verbose=false)
compare the state derivative against numerical differentiation
bool controlDerivativeIntermediateTest (bool verbose=false)
compare the control derivative against numerical differentiation
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getIntermediateTermById (const size_t id)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getFinalTermById (const size_t id)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getIntermediateTermByName (const std::string &name)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getFinalTermByName (const std::string &name)
virtual void initialize ()
initialize the cost function (e.g. to be used in CostFunctionAD)
Public Member Functions inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
CostFunction ()
Default constructor.
virtual ~CostFunction ()
Destructor.
CostFunction (const CostFunction &arg)
Copy constructor.
virtual void setCurrentStateAndControl (const state_vector_t &x, const control_vector_t &u, const SCALAR &t=SCALAR(0.0))
virtual void getCurrentStateAndControl (Eigen::Matrix< SCALAR, STATE_DIM, 1 > &x, Eigen::Matrix< SCALAR, CONTROL_DIM, 1 > &u, SCALAR &t) const
sets current state, control and time
virtual SCALAR evaluateIntermediate ()=0
evaluate intermediate costs
virtual SCALAR evaluateTerminal ()=0
evaluate terminal costs
virtual void shiftTime (const SCALAR t)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix< SCALAR, STATE_DIM, STATE_DIM > state_matrix_t
Public Attributes inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Protected Member Functions
SCALAR evaluateIntermediateBase ()
evaluate intermediate analytical cost terms
SCALAR evaluateTerminalBase ()
evaluate terminal analytical cost terms
state_vector_t stateDerivativeIntermediateBase ()
evaluate intermediate analytical state derivatives
state_vector_t stateDerivativeTerminalBase ()
evaluate terminal analytical state derivatives
state_matrix_t stateSecondDerivativeIntermediateBase ()
evaluate intermediate analytical state second derivatives
state_matrix_t stateSecondDerivativeTerminalBase ()
evaluate terminal analytical state second derivatives
control_vector_t controlDerivativeIntermediateBase ()
evaluate intermediate analytical control derivatives
control_vector_t controlDerivativeTerminalBase ()
evaluate terminal analytical control derivatives
control_matrix_t controlSecondDerivativeIntermediateBase ()
evaluate intermediate analytical control second derivatives
control_matrix_t controlSecondDerivativeTerminalBase ()
evaluate terminal analytical control second derivatives
control_state_matrix_t stateControlDerivativeIntermediateBase ()
evaluate intermediate analytical control mixed state control derivatives
control_state_matrix_t stateControlDerivativeTerminalBase ()
evaluate terminal analytical control mixed state control derivatives
state_vector_t stateDerivativeIntermediateNumDiff ()
compute the state derivative by numerical differentiation (can be used for testing)
control_vector_t controlDerivativeIntermediateNumDiff ()
compute the control derivative by numerical differentiation (can be used for testing)
Protected Attributes
SCALAR eps_
stepsize for numerical differentiation
bool doubleSidedDerivative_ = true
use double sided derivatives in numerical differentiation
std::vector< std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > > intermediateCostAnalytical_
std::vector< std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > > finalCostAnalytical_
Protected Attributes inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
state_vector_t x_
control_vector_t u_
SCALAR t_
SCALAR t_shift_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
Describes a cost function with a quadratic approximation, i.e. one that can compute first and second order derivatives with respect to state and control input. This does NOT mean it has to be a purely quadratic cost function. If you are looking for a purely quadratic cost function, check CostFunctionQuadraticSimple.
A cost function is assumed to be a sum of intermediate and final terms, i.e. These terms can have arbitrary form.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, CONTROL_DIM, CONTROL_DIM> ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, CONTROL_DIM, STATE_DIM> ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::StateVector<STATE_DIM, SCALAR> ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef CostFunction<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::BASE
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionQuadratic ()
Constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionQuadratic (const CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR > & arg)
Copy constructor
Parameters
arg other cost function
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, i, and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::~CostFunctionQuadratic () virtual
Destructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual CostFunctionQuadratic<STATE_DIM, CONTROL_DIM, SCALAR>* ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const pure virtual
Clones the cost function.
Returns
Implements ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >.
Implemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> size_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR >> term, bool verbose = false) virtual
Adds an intermediate term.
Parameters
term intermediate term
verbose verbosity flag which enables printout
Returns
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_.
Referenced by ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> void ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, ct::core::ADCGScalar >> term, bool verbose = false) virtual
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> size_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addFinalTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR >> term, bool verbose = false) virtual
Adds a final term.
Parameters
term final term
verbose verbosity flag which enables printout
Returns
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_.
Referenced by ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> void ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addFinalADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, ct::core::ADCGScalar >> term, bool verbose = false) virtual
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile (const std::string & filename, bool verbose = false) virtual
Loads cost function from config file.
Parameters
filename config file location
verbose verbosity flag which enables printout
Reimplemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual state_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate () pure virtual
Computes intermediate-cost first-order derivative with respect to state.
Returns
derivative vector (Jacobian)
Implemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), ct::optcon::example::printCostFunctionOutput(), ct::optcon::LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setFromTimeInvariantLinearQuadraticProblem(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateTest().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual state_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminal () pure virtual
Computes terminal-cost first-order derivative with respect to state
Returns
derivative vector (Jacobian)
Implemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), ct::optcon::example::printCostFunctionOutput(), and ct::optcon::LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setFromTimeInvariantLinearQuadraticProblem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual state_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediate () pure virtual
Computes intermediate-cost second-order derivative with respect to state.
Returns
derivative matrix (Jacobian)
Implemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), ct::optcon::example::printCostFunctionOutput(), and ct::optcon::LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setFromTimeInvariantLinearQuadraticProblem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual state_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminal () pure virtual
Computes final-cost second-order derivative with respect to state.
Returns
derivative matrix (Jacobian)
Implemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), ct::optcon::example::printCostFunctionOutput(), and ct::optcon::LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setFromTimeInvariantLinearQuadraticProblem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual control_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate () pure virtual
Computes intermediate-cost first-order derivative with respect to control.
Returns
derivative vector (Jacobian)
Implemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateTest(), ct::optcon::example::printCostFunctionOutput(), and ct::optcon::LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setFromTimeInvariantLinearQuadraticProblem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminal () virtual
Computes terminal-cost first-order derivative with respect to control.
Not available for all cost functions. Throws an exception if not available.
Returns
derivative vector (Jacobian)
Reimplemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), and ct::optcon::example::printCostFunctionOutput().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual control_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediate () pure virtual
Computes intermediate-cost second-order derivative with respect to input.
Returns
derivative matrix (Jacobian)
Implemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), ct::optcon::example::printCostFunctionOutput(), and ct::optcon::LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setFromTimeInvariantLinearQuadraticProblem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminal () virtual
Computes final-cost second-order derivative with respect to input.
Not available for all cost functions. Throws an exception if not available.
Returns
derivative matrix (Jacobian)
Reimplemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), and ct::optcon::example::printCostFunctionOutput().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual control_state_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediate () pure virtual
Computes intermediate-cost derivative with respect to state and control.
Returns
derivative matrix (Jacobian)
Implemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), ct::optcon::example::printCostFunctionOutput(), and ct::optcon::LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setFromTimeInvariantLinearQuadraticProblem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminal () virtual
Computes final-cost derivative with respect to state and control.
Returns
derivative matrix (Jacobian)
Reimplemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::example::compareCostFunctionOutput(), and ct::optcon::example::printCostFunctionOutput().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::updateReferenceState (const state_vector_t & x_ref) virtual
update the reference state for intermediate cost terms
Reimplemented in ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::updateFinalState (const state_vector_t & x_final) virtual
update the reference state for final cost terms
Reimplemented in ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::updateReferenceControl (const control_vector_t & u_ref) virtual
update the reference control for intermediate cost terms
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > bool ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateTest (bool verbose = false)
compare the state derivative against numerical differentiation
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateNumDiff().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > bool ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateTest (bool verbose = false)
compare the control derivative against numerical differentiation
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateNumDiff().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateTermById (const size_t id)
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::getFinalTermById (const size_t id)
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateTermByName (const std::string & name)
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::getFinalTermByName (const std::string & name)
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::initialize () virtual
initialize the cost function (e.g. to be used in CostFunctionAD)
do nothing at all
Reimplemented in ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SCALAR ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediateBase () protected
evaluate intermediate analytical cost terms
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_, and y.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SCALAR ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminalBase () protected
evaluate terminal analytical cost terms
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_, and y.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateBase () protected
evaluate intermediate analytical state derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminalBase () protected
evaluate terminal analytical state derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminal(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminal().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediateBase () protected
evaluate intermediate analytical state second derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediate(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediate().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminalBase () protected
evaluate terminal analytical state second derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminal(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminal().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateBase () protected
evaluate intermediate analytical control derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminalBase () protected
evaluate terminal analytical control derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminal(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminal().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediateBase () protected
evaluate intermediate analytical control second derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediate(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediate().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminalBase () protected
evaluate terminal analytical control second derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminal(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminal().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediateBase () protected
evaluate intermediate analytical control mixed state control derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediate(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediate().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminalBase () protected
evaluate terminal analytical control mixed state control derivatives
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminal(), and ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminal().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateNumDiff () protected
compute the state derivative by numerical differentiation (can be used for testing)
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::doubleSidedDerivative_, ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::eps_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::getCurrentStateAndControl(), i, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl().
Referenced by ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateTest().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateNumDiff () protected
compute the control derivative by numerical differentiation (can be used for testing)
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::doubleSidedDerivative_, ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::eps_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::getCurrentStateAndControl(), i, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl().
Referenced by ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateTest().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix<SCALAR, STATE_DIM, STATE_DIM> ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> SCALAR ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::eps_ protected
stepsize for numerical differentiation
Referenced by ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateNumDiff(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateNumDiff().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> bool ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::doubleSidedDerivative_ = true protected
use double sided derivatives in numerical differentiation
Referenced by ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateNumDiff(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateNumDiff().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> std::vector<std::shared_ptr<TermBase<STATE_DIM, CONTROL_DIM, SCALAR> > > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_ protected
list of intermediate cost terms for which analytic derivatives are available
Referenced by ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateTerm(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediateBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionQuadratic(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediateBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateTermById(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateTermByName(), ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediateBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediateBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::updateReferenceControl(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::updateReferenceState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> std::vector<std::shared_ptr<TermBase<STATE_DIM, CONTROL_DIM, SCALAR> > > ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_ protected
list of final cost terms for which analytic derivatives are available
Referenced by ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addFinalTerm(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminalBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminalBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionQuadratic(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminalBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::getFinalTermById(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::getFinalTermByName(), ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminalBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminalBase(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminalBase(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::updateFinalState().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/costfunction/CostFunctionQuadratic.hpp
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/costfunction/CostFunctionQuadratic-impl.hpp