ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
DMS
Evaluates the cost at the shots and performs some interpolation in between.
#include <CostEvaluatorSimple.h>
Public Types
typedef DIMENSIONS::state_vector_t state_vector_t
typedef DIMENSIONS::control_vector_t control_vector_t
Public Member Functions
CostEvaluatorSimple ()=delete
CostEvaluatorSimple (std::shared_ptr< ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >> costFct, std::shared_ptr< OptVectorDms< STATE_DIM, CONTROL_DIM, SCALAR >> w, std::shared_ptr< tpl::TimeGrid< SCALAR >> timeGrid, DmsSettings settings)
Custom constructor.
~CostEvaluatorSimple () override=default
SCALAR eval () override
Evaluates the cost function.
void evalGradient (size_t grad_length, Eigen::Map< Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 >> &grad) override
Evaluates the cost gradient.
Public Member Functions inherited from ct::optcon::tpl::DiscreteCostEvaluatorBase< SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW DiscreteCostEvaluatorBase ()=default
Default constructor.
virtual ~DiscreteCostEvaluatorBase ()=default
Destructor.
virtual void getSparsityPatternHessian (Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
virtual void sparseHessianValues (const Eigen::VectorXd &optVec, const Eigen::VectorXd &lambda, Eigen::VectorXd &hes)
Evaluates the cost hessian.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions< STATE_DIM, CONTROL_DIM, SCALAR > DIMENSIONS
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >
Evaluates the cost at the shots and performs some interpolation in between.
Template Parameters
STATE_DIM The state dimension
CONTROL_DIM The control dimension
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_vector_t ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::control_vector_t ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::CostEvaluatorSimple () delete
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::CostEvaluatorSimple (std::shared_ptr< ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >> costFct, std::shared_ptr< OptVectorDms< STATE_DIM, CONTROL_DIM, SCALAR >> w, std::shared_ptr< tpl::TimeGrid< SCALAR >> timeGrid, DmsSettings settings) inline
Custom constructor.
Parameters
[in] costFct The cost function
[in] w The optimization variables
[in] timeGrid The time grid
[in] settings The dms settings
References ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::eval(), ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::evalGradient(), ct::optcon::DmsSettings::N_, and ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::~CostEvaluatorSimple().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::~CostEvaluatorSimple () override default
Referenced by ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::CostEvaluatorSimple().
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SCALAR ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::eval () override virtual
Evaluates the cost function.
Returns
The evaluates cost function
Implements ct::optcon::tpl::DiscreteCostEvaluatorBase< SCALAR >.
References i, and ct::optcon::DmsSettings::N_.
Referenced by ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::CostEvaluatorSimple().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::evalGradient (size_t grad_length, Eigen::Map< Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 >> & grad) override virtual
Evaluates the cost gradient.
Parameters
[in] grad_length The size of the gradient vector
[out] grad The values of the gradient
Implements ct::optcon::tpl::DiscreteCostEvaluatorBase< SCALAR >.
References i, ct::optcon::DmsSettings::N_, ct::optcon::DmsSettings::PIECEWISE_LINEAR, ct::optcon::DmsSettings::splineType_, and ct::optcon::DmsSettings::ZERO_ORDER_HOLD.
Referenced by ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::CostEvaluatorSimple().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::CostEvaluatorSimple< STATE_DIM, CONTROL_DIM, SCALAR >::DIMENSIONS
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/dms/dms_core/cost_evaluator/CostEvaluatorSimple.h