ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR > Class Template Reference
ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR > Class Template Reference
interface class for optimal control algorithms
#include <OptconContinuousSystemInterface.h>
Public Types
typedef Base::control_vector_t control_vector_t
typedef Base::state_vector_t state_vector_t
typedef Base::state_matrix_t state_matrix_t
typedef Base::state_control_matrix_t state_control_matrix_t
typedef ct::core::SystemDiscretizer< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR > discretizer_t
typedef std::shared_ptr< discretizer_t > system_discretizer_ptr_t
typedef ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR > Sensitivity_t
typedef std::shared_ptr< Sensitivity_t > SensitivityPtr
typedef Base::StateVectorArrayPtr StateVectorArrayPtr
typedef Base::StateSubstepsPtr StateSubstepsPtr
typedef Base::ControlVectorArrayPtr ControlVectorArrayPtr
typedef Base::ControlSubstepsPtr ControlSubstepsPtr
typedef Base::optConProblem_t optConProblem_t
typedef Base::settings_t settings_t
Public Types inherited from ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >
typedef ct::core::StateVector< STATE_DIM, SCALAR > state_vector_t
typedef ct::core::StateMatrix< STATE_DIM, SCALAR > state_matrix_t
typedef ct::core::StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
typedef ct::core::StateVectorArray< STATE_DIM, SCALAR > StateVectorArray
typedef std::shared_ptr< StateVectorArray > StateVectorArrayPtr
typedef std::vector< StateVectorArrayPtr, Eigen::aligned_allocator< StateVectorArrayPtr > > StateSubsteps
typedef std::shared_ptr< StateSubsteps > StateSubstepsPtr
typedef ct::core::ControlVectorArray< CONTROL_DIM, SCALAR > ControlVectorArray
typedef std::shared_ptr< ControlVectorArray > ControlVectorArrayPtr
typedef std::vector< ControlVectorArrayPtr, Eigen::aligned_allocator< ControlVectorArrayPtr > > ControlSubsteps
typedef std::shared_ptr< ControlSubsteps > ControlSubstepsPtr
typedef ct::core::ConstantController< STATE_DIM, CONTROL_DIM, SCALAR > constant_controller_t
typedef std::shared_ptr< constant_controller_t > ConstantControllerPtr
typedef ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR > optConProblem_t
typedef NLOptConSettings settings_t
Public Member Functions
OptconContinuousSystemInterface (const optConProblem_t &problem, const settings_t &settings)
constructor
virtual ~OptconContinuousSystemInterface ()
destructor
virtual void initialize () override
perform necessary setup work
virtual void configure (const settings_t &settings) override
virtual void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t subSteps, state_matrix_t &A, state_control_matrix_t &B, const size_t threadId) override
retrieve discrete-time linear system matrices A and B.
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext, const size_t threadId) override
propagate discrete-time dynamics
virtual void changeNonlinearSystem (const typename optConProblem_t::DynamicsPtr_t &dyn) override
virtual void changeLinearSystem (const typename optConProblem_t::LinearPtr_t &lin) override
virtual void changeNumStages (const int numStages) override
set the number of stages/time steps
virtual void getSubstates (StateVectorArrayPtr &subStepsX, const size_t threadId) override
virtual void getSubcontrols (ControlVectorArrayPtr &subStepsU, const size_t threadId) override
virtual void setSubstepTrajectoryReference (const StateSubstepsPtr &xSubsteps, const ControlSubstepsPtr &uSubsteps, const size_t threadId) override
Public Member Functions inherited from ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >
OptconSystemInterface (const optConProblem_t &problem, const settings_t &settings)
constructor
virtual void configure (const settings_t &settings)
virtual void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t subSteps, state_matrix_t &A, state_control_matrix_t &B, const size_t threadId)=0
retrieve discrete-time linear system matrices A and B.
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext, const size_t threadId)=0
propagate discrete-time dynamics
const optConProblem_t & getOptConProblem ()
std::vector< typename optConProblem_t::DynamicsPtr_t > & getNonlinearSystemsInstances ()
std::vector< typename optConProblem_t::LinearPtr_t > & getLinearSystemsInstances ()
virtual void changeNonlinearSystem (const typename optConProblem_t::DynamicsPtr_t &dyn)=0
virtual void changeLinearSystem (const typename optConProblem_t::LinearPtr_t &lin)=0
virtual void getSubstates (StateVectorArrayPtr &subStepsX, const size_t threadId)
virtual void getSubcontrols (ControlVectorArrayPtr &subStepsU, const size_t threadId)
virtual void setSubstepTrajectoryReference (const StateSubstepsPtr &xSubsteps, const ControlSubstepsPtr &uSubsteps, const size_t threadId)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR > Base
Public Attributes inherited from ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Additional Inherited Members
Protected Attributes inherited from ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >
std::vector< typename optConProblem_t::DynamicsPtr_t > systems_
std::vector< typename optConProblem_t::LinearPtr_t > linearSystems_
std::vector< ConstantControllerPtr, Eigen::aligned_allocator< ConstantControllerPtr > > controller_
optConProblem_t optConProblem_
the constant controller for forward-integration during one time-step
settings_t settings_
instance of the optconProblem
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double>
class ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >
interface class for optimal control algorithms
Defines the unified interface for optimal control solvers used in conjuction with a continuous optimal control problem. It bundles the optcon problem with system integrators and sensitivities.
Template Parameters
STATE_DIM size of state vector
CONTROL_DIM size of input vector
P_DIM size for symplectic integrator
V_DIM size for symplectic integrator
SCALAR the underlying scalar type
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::control_vector_t ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::state_vector_t ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::state_matrix_t ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::state_control_matrix_t ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::state_control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef ct::core::SystemDiscretizer<STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR> ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::discretizer_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef std::shared_ptr<discretizer_t> ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::system_discretizer_ptr_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef ct::core::Sensitivity<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::Sensitivity_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef std::shared_ptr<Sensitivity_t> ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::SensitivityPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::StateVectorArrayPtr ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::StateVectorArrayPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::StateSubstepsPtr ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::StateSubstepsPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::ControlVectorArrayPtr ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::ControlVectorArrayPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::ControlSubstepsPtr ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::ControlSubstepsPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::optConProblem_t ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::optConProblem_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Base::settings_t ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::settings_t
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::OptconContinuousSystemInterface (const optConProblem_t & problem, const settings_t & settings)
constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> virtual ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface () inline virtual
destructor
References ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::changeLinearSystem(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::changeNonlinearSystem(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::changeNumStages(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::configure(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::getAandB(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::getSubcontrols(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::getSubstates(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::initialize(), n, ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::propagateControlledDynamics(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::setSubstepTrajectoryReference(), u, and x.
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::initialize () override virtual
perform necessary setup work
Reimplemented from ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >.
References ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::controller_, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::getLinearSystem(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::getNonlinearSystem(), ct::optcon::NLOptConSettings::getSimulationTimestep(), i, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_sim, ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::linearSystems_, ct::optcon::NLOptConSettings::nThreads, ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::optConProblem_, ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::settings_, ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::systems_, ct::optcon::NLOptConSettings::timeVaryingDiscretization, and ct::optcon::NLOptConSettings::useSensitivityIntegrator.
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::configure (const settings_t & settings) override virtual
References i, and ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::settings_.
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::getAandB (const state_vector_t & x, const control_vector_t & u, const state_vector_t & x_next, const int n, size_t subSteps, state_matrix_t & A, state_control_matrix_t & B, const size_t threadId) override virtual
retrieve discrete-time linear system matrices A and B.
Parameters
x the state setpoint
u the control setpoint
x_next the next state
n the time setpoint
subSteps number of substeps of trajectory for which to get the sensitivity for
A the resulting linear system matrix A
B the resulting linear system matrix B
threadId which thread specific instantiations to use
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::propagateControlledDynamics (const state_vector_t & state, const time_t n, const control_vector_t & control, state_vector_t & stateNext, const size_t threadId) override virtual
propagate discrete-time dynamics
Parameters
state start state to propagate from
n discrete time index to propagate the dynamics at
control the control input to apply. This is a constant control input applied during the discretization interval
stateNext the resulting propagated state
threadId which thread specific instantiations to use
References ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::controller_.
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::changeNonlinearSystem (const typename optConProblem_t::DynamicsPtr_t & dyn) override virtual
References ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::controller_, ct::optcon::NLOptConSettings::dt, i, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_sim, ct::optcon::NLOptConSettings::nThreads, ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::settings_, and ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::systems_.
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::changeLinearSystem (const typename optConProblem_t::LinearPtr_t & lin) override virtual
References i, ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::linearSystems_, ct::optcon::NLOptConSettings::nThreads, and ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::settings_.
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::changeNumStages (const int numStages) override virtual
set the number of stages/time steps
Reimplemented from ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >.
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::getSubstates (StateVectorArrayPtr & subStepsX, const size_t threadId) override virtual
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::getSubcontrols (ControlVectorArrayPtr & subStepsU, const size_t threadId) override virtual
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR > void ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::setSubstepTrajectoryReference (const StateSubstepsPtr & xSubsteps, const ControlSubstepsPtr & uSubsteps, const size_t threadId) override virtual
Referenced by ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef OptconSystemInterface<STATE_DIM, CONTROL_DIM, ContinuousOptConProblem<STATE_DIM, CONTROL_DIM, SCALAR>, SCALAR> ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::Base
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/system_interface/OptconContinuousSystemInterface.h
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/system_interface/OptconContinuousSystemInterface-impl.h