ct::optcon::example::MatFilesGenerator Class Reference
ct::optcon::example::MatFilesGenerator Class Reference
Public Types
typedef DmsDimensions< 2, 1 > OscDimensions
Public Member Functions
MatFilesGenerator ()
void initialize ()
void generateMatFilesIPOPT ()
void generateMatFilesSNOPT ()
Member Typedef Documentation
typedef DmsDimensions<2, 1> ct::optcon::example::MatFilesGenerator::OscDimensions
Constructor & Destructor Documentation
ct::optcon::example::MatFilesGenerator::MatFilesGenerator () inline
References ct::optcon::DmsSettings::FULL, ct::optcon::DmsSettings::KEEP_TIME_AND_GRID, ct::optcon::DmsSettings::PIECEWISE_LINEAR, and ct::optcon::DmsSettings::RK4.
Member Function Documentation
void ct::optcon::example::MatFilesGenerator::initialize () inline
Referenced by main().
void ct::optcon::example::MatFilesGenerator::generateMatFilesIPOPT () inline
References ct::optcon::IPOPT, ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setGeneralConstraints(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setInitialState(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setTimeHorizon(), ct::core::ScalarArray< SCALAR >::toEigenTrajectory(), and ct::core::DiscreteArray< T, Alloc >::toImplementation().
Referenced by main().
void ct::optcon::example::MatFilesGenerator::generateMatFilesSNOPT () inline
References i, ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setGeneralConstraints(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setInitialState(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setTimeHorizon(), ct::optcon::SNOPT, ct::core::ScalarArray< SCALAR >::toEigenTrajectory(), and ct::core::DiscreteArray< T, Alloc >::toImplementation().
Referenced by main().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/test/dms/oscillator/matfiles/matFilesGenerator.cpp