ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
CostFunction
Cost Function with Auto-Diff support.
#include <CostFunctionAD.hpp>
Public Types
typedef JacCG::CG_SCALAR CGScalar
typedef Eigen::Matrix< CGScalar, 1, 1 > MatrixCg
typedef Eigen::Matrix< SCALAR, STATE_DIM, STATE_DIM > state_matrix_t
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > MatrixXs
Public Types inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
typedef CostFunction< STATE_DIM, CONTROL_DIM, SCALAR > BASE
Public Types inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Member Functions
CostFunctionAD ()
Basic constructor.
CostFunctionAD (const std::string &filename, bool verbose=false)
Constructor loading function from file.
CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const
CostFunctionAD (const CostFunctionAD &arg)
Copy constructor.
virtual ~CostFunctionAD ()
Destructor.
virtual void initialize () override
Initializes the AD costfunction, generates and compiles source code.
void addIntermediateADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, CGScalar >> term, bool verbose=false) override
Add an intermediate, auto-differentiable term.
void addFinalADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, CGScalar >> term, bool verbose=false) override
Add a final, auto-differentiable term.
void setCurrentStateAndControl (const state_vector_t &x, const control_vector_t &u, const SCALAR &t=0.0) override
void loadFromConfigFile (const std::string &filename, bool verbose=false) override
Loads cost function from config file.
SCALAR evaluateIntermediate () override
evaluate intermediate costs
SCALAR evaluateTerminal () override
evaluate terminal costs
state_vector_t stateDerivativeIntermediate () override
Computes intermediate-cost first-order derivative with respect to state.
state_vector_t stateDerivativeTerminal () override
control_vector_t controlDerivativeIntermediate () override
Computes intermediate-cost first-order derivative with respect to control.
control_vector_t controlDerivativeTerminal () override
Computes terminal-cost first-order derivative with respect to control.
state_matrix_t stateSecondDerivativeIntermediate () override
Computes intermediate-cost second-order derivative with respect to state.
state_matrix_t stateSecondDerivativeTerminal () override
Computes final-cost second-order derivative with respect to state.
control_matrix_t controlSecondDerivativeIntermediate () override
Computes intermediate-cost second-order derivative with respect to input.
control_matrix_t controlSecondDerivativeTerminal () override
Computes final-cost second-order derivative with respect to input.
control_state_matrix_t stateControlDerivativeIntermediate () override
Computes intermediate-cost derivative with respect to state and control.
control_state_matrix_t stateControlDerivativeTerminal () override
Computes final-cost derivative with respect to state and control.
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, CGScalar > > getIntermediateADTermById (const size_t id)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, CGScalar > > getFinalADTermById (const size_t id)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, CGScalar > > getIntermediateADTermByName (const std::string &name)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, CGScalar > > getFinalADTermByName (const std::string &name)
Public Member Functions inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
CostFunctionQuadratic ()
CostFunctionQuadratic (const CostFunctionQuadratic &arg)
virtual ~CostFunctionQuadratic ()
virtual size_t addIntermediateTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR >> term, bool verbose=false)
Adds an intermediate term.
virtual void addIntermediateADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, ct::core::ADCGScalar >> term, bool verbose=false)
virtual size_t addFinalTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR >> term, bool verbose=false)
Adds a final term.
virtual void addFinalADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, ct::core::ADCGScalar >> term, bool verbose=false)
virtual void updateReferenceState (const state_vector_t &x_ref)
update the reference state for intermediate cost terms
virtual void updateFinalState (const state_vector_t &x_final)
update the reference state for final cost terms
virtual void updateReferenceControl (const control_vector_t &u_ref)
update the reference control for intermediate cost terms
bool stateDerivativeIntermediateTest (bool verbose=false)
compare the state derivative against numerical differentiation
bool controlDerivativeIntermediateTest (bool verbose=false)
compare the control derivative against numerical differentiation
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getIntermediateTermById (const size_t id)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getFinalTermById (const size_t id)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getIntermediateTermByName (const std::string &name)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getFinalTermByName (const std::string &name)
Public Member Functions inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
CostFunction ()
Default constructor.
virtual ~CostFunction ()
Destructor.
CostFunction (const CostFunction &arg)
Copy constructor.
virtual void setCurrentStateAndControl (const state_vector_t &x, const control_vector_t &u, const SCALAR &t=SCALAR(0.0))
virtual void getCurrentStateAndControl (Eigen::Matrix< SCALAR, STATE_DIM, 1 > &x, Eigen::Matrix< SCALAR, CONTROL_DIM, 1 > &u, SCALAR &t) const
sets current state, control and time
virtual void shiftTime (const SCALAR t)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::DerivativesCppadJIT< STATE_DIM+CONTROL_DIM+1, 1 > JacCG
Public Attributes inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix< SCALAR, STATE_DIM, STATE_DIM > state_matrix_t
Public Attributes inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Additional Inherited Members
Protected Member Functions inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
SCALAR evaluateIntermediateBase ()
evaluate intermediate analytical cost terms
SCALAR evaluateTerminalBase ()
evaluate terminal analytical cost terms
state_vector_t stateDerivativeIntermediateBase ()
evaluate intermediate analytical state derivatives
state_vector_t stateDerivativeTerminalBase ()
evaluate terminal analytical state derivatives
state_matrix_t stateSecondDerivativeIntermediateBase ()
evaluate intermediate analytical state second derivatives
state_matrix_t stateSecondDerivativeTerminalBase ()
evaluate terminal analytical state second derivatives
control_vector_t controlDerivativeIntermediateBase ()
evaluate intermediate analytical control derivatives
control_vector_t controlDerivativeTerminalBase ()
evaluate terminal analytical control derivatives
control_matrix_t controlSecondDerivativeIntermediateBase ()
evaluate intermediate analytical control second derivatives
control_matrix_t controlSecondDerivativeTerminalBase ()
evaluate terminal analytical control second derivatives
control_state_matrix_t stateControlDerivativeIntermediateBase ()
evaluate intermediate analytical control mixed state control derivatives
control_state_matrix_t stateControlDerivativeTerminalBase ()
evaluate terminal analytical control mixed state control derivatives
state_vector_t stateDerivativeIntermediateNumDiff ()
compute the state derivative by numerical differentiation (can be used for testing)
control_vector_t controlDerivativeIntermediateNumDiff ()
compute the control derivative by numerical differentiation (can be used for testing)
Protected Attributes inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
SCALAR eps_
stepsize for numerical differentiation
bool doubleSidedDerivative_ = true
use double sided derivatives in numerical differentiation
std::vector< std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > > intermediateCostAnalytical_
std::vector< std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > > finalCostAnalytical_
Protected Attributes inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
state_vector_t x_
control_vector_t u_
SCALAR t_
SCALAR t_shift_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >
Cost Function with Auto-Diff support.
This cost function can work with both, analytical terms as well as auto-diff terms. For analytical terms it will use provided derivatives and for auto-diff terms derivatives will be computed using auto-diff.
Unit test ADTest.cpp illustrates the use of a CostFunctionAD.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef JacCG::CG_SCALAR ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CGScalar
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<CGScalar, 1, 1> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixCg
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, STATE_DIM, STATE_DIM> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, CONTROL_DIM, CONTROL_DIM> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, CONTROL_DIM, STATE_DIM> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::StateVector<STATE_DIM, SCALAR> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, Eigen::Dynamic> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAD ()
Basic constructor.
References ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::JacCG, ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::clone().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAD (const std::string & filename, bool verbose = false)
Constructor loading function from file.
Parameters
filename config file location
verbose flag enabling printouts
References ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAD (const CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR > & arg)
Copy constructor.
Parameters
arg cost function to copy
References i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::~CostFunctionAD () virtual
Destructor.
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR > * ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const virtual
Deep-cloning of cost function
Returns
base pointer to clone
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAD().
Referenced by ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::initialize () override virtual
Initializes the AD costfunction, generates and compiles source code.
@ todo: this should probably become an option (eg. IPOPT can work without cost Hessians)
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::DerivativesCppadSettings::createForwardZero_, ct::core::DerivativesCppadSettings::createHessian_, and ct::core::DerivativesCppadSettings::createJacobian_.
Referenced by ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> void ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, CGScalar >> term, bool verbose = false) override
Add an intermediate, auto-differentiable term.
Use this function to add an auto-differentiable, intermediate term to the cost function.
Parameters
term The term to be added
verbose Flag enabling printouts
Returns
Referenced by ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> void ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::addFinalADTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, CGScalar >> term, bool verbose = false) override
Add a final, auto-differentiable term.
Use this function to add an auto-differentiable, final term to the cost function.
Parameters
term The term to be added
verbose Flag enabling printouts
Returns
Referenced by ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR> void ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl (const state_vector_t & x, const control_vector_t & u, const SCALAR & t = 0.0) override
References t, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::t_, u, ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::u_, x, and ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
Referenced by ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAD(), and ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile (const std::string & filename, bool verbose = false) override virtual
Loads cost function from config file.
Parameters
filename config file location
verbose verbosity flag which enables printout
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::addADTerm(), CT_LOADABLE_TERMS, ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, i, and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_.
Referenced by ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAD().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SCALAR ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate () override virtual
evaluate intermediate costs
Evaluates the running/intermediate cost function for the control, state and time set in setCurrentStateAndControl()
Returns
costs
Implements ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediateBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SCALAR ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal () override virtual
evaluate terminal costs
Evaluates the terminal cost for a given state and control set in setCurrentStateAndControl(). This usually ignores time.
Returns
costs
Implements ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminalBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate () override virtual
Computes intermediate-cost first-order derivative with respect to state.
Returns
derivative vector (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminal () override virtual
Computes terminal-cost first-order derivative with respect to state
Returns
derivative vector (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminalBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate () override virtual
Computes intermediate-cost first-order derivative with respect to control.
Returns
derivative vector (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminal () override virtual
Computes terminal-cost first-order derivative with respect to control.
Not available for all cost functions. Throws an exception if not available.
Returns
derivative vector (Jacobian)
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminalBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediate () override virtual
Computes intermediate-cost second-order derivative with respect to state.
Returns
derivative matrix (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediateBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminal () override virtual
Computes final-cost second-order derivative with respect to state.
Returns
derivative matrix (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminalBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediate () override virtual
Computes intermediate-cost second-order derivative with respect to input.
Returns
derivative matrix (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediateBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminal () override virtual
Computes final-cost second-order derivative with respect to input.
Not available for all cost functions. Throws an exception if not available.
Returns
derivative matrix (Jacobian)
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminalBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediate () override virtual
Computes intermediate-cost derivative with respect to state and control.
Returns
derivative matrix (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediateBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminal () override virtual
Computes final-cost derivative with respect to state and control.
Returns
derivative matrix (Jacobian)
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminalBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > std::shared_ptr< ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, SCALAR, typename CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CGScalar > > ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateADTermById (const size_t id)
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > std::shared_ptr< ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, SCALAR, typename CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CGScalar > > ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::getFinalADTermById (const size_t id)
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, typename CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CGScalar > > ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateADTermByName (const std::string & name)
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR, typename CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CGScalar > > ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::getFinalADTermByName (const std::string & name)
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::DerivativesCppadJIT<STATE_DIM + CONTROL_DIM + 1, 1> ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::JacCG
Referenced by ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAD().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/costfunction/CostFunctionAD.hpp
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/costfunction/CostFunctionAD-impl.hpp