ct::optcon::example::OscDms Class Reference
ct::optcon::example::OscDms Class Reference
Public Member Functions
OscDms ()
~OscDms ()
void getIpoptMatlabTrajectories ()
void getSnoptMatlabTrajectories ()
void initialize ()
void getIpoptSolution ()
void getSnoptSolution ()
void compareIpoptSolutions ()
void compareSnoptSolutions ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions< 2, 1 > OscDimensions
Constructor & Destructor Documentation
ct::optcon::example::OscDms::OscDms () inline
Examples:
oscDMSTest.cpp.
References ct::optcon::DmsSettings::absErrTol_, ct::optcon::DmsSettings::costEvaluationType_, DATA_DIR, ct::optcon::DmsSettings::dt_sim_, ct::optcon::DmsSettings::FULL, ct::optcon::DmsSettings::h_min_, ct::optcon::DmsSettings::integrationType_, ct::optcon::DmsSettings::KEEP_TIME_AND_GRID, ct::optcon::DmsSettings::N_, ct::optcon::DmsSettings::nThreads_, ct::optcon::DmsSettings::objectiveType_, ct::optcon::DmsSettings::PIECEWISE_LINEAR, ct::optcon::DmsSettings::print(), ct::optcon::DmsSettings::relErrTol_, ct::optcon::DmsSettings::RK4, ct::optcon::DmsSettings::splineType_, and ct::optcon::DmsSettings::T_.
ct::optcon::example::OscDms::~OscDms () inline
Examples:
oscDMSTest.cpp.
Member Function Documentation
void ct::optcon::example::OscDms::getIpoptMatlabTrajectories () inline
Examples:
oscDMSTest.cpp.
Referenced by ct::optcon::example::TEST().
void ct::optcon::example::OscDms::getSnoptMatlabTrajectories () inline
Examples:
oscDMSTest.cpp.
Referenced by ct::optcon::example::TEST().
void ct::optcon::example::OscDms::initialize () inline
Examples:
oscDMSTest.cpp.
Referenced by ct::optcon::example::TEST().
void ct::optcon::example::OscDms::getIpoptSolution () inline
Examples:
oscDMSTest.cpp.
References ct::optcon::IPOPT, ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setGeneralConstraints(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setInitialState(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setTimeHorizon(), ct::optcon::DmsSettings::solverSettings_, ct::optcon::NlpSolverSettings::solverType_, ct::optcon::DmsSettings::T_, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::tSolution_, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::uSolution_, and ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::xSolution_.
Referenced by ct::optcon::example::TEST().
void ct::optcon::example::OscDms::getSnoptSolution () inline
Examples:
oscDMSTest.cpp.
References ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setGeneralConstraints(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setInitialState(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setTimeHorizon(), ct::optcon::SNOPT, ct::optcon::DmsSettings::solverSettings_, ct::optcon::NlpSolverSettings::solverType_, ct::optcon::DmsSettings::T_, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::tSolution_, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::uSolution_, and ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::xSolution_.
Referenced by ct::optcon::example::TEST().
void ct::optcon::example::OscDms::compareIpoptSolutions () inline
Examples:
oscDMSTest.cpp.
References ASSERT_TRUE, and i.
Referenced by ct::optcon::example::TEST().
void ct::optcon::example::OscDms::compareSnoptSolutions () inline
Examples:
oscDMSTest.cpp.
References ASSERT_TRUE, i, ct::optcon::DmsSettings::N_, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::uSolution_, and ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::xSolution_.
Referenced by ct::optcon::example::TEST().
Member Data Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions<2, 1> ct::optcon::example::OscDms::OscDimensions
Examples:
oscDMSTest.cpp.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/test/dms/oscillator/oscDMSTest.cpp