ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS > Class Template Reference
ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS > Class Template Reference
#include <NLOptConSolver.hpp>
Public Types
typedef OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, typename NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS > Base
typedef NLOptConSettings Settings_t
typedef SCALAR Scalar_t
typedef Base::OptConProblem_t OptConProblem_t
typedef NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS > NLOCAlgorithm_t
typedef NLOCAlgorithm_t::Policy_t Policy_t
typedef NLOCAlgorithm_t::Backend_t Backend_t
Public Types inherited from ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >
typedef NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t Policy_t
typedef NLOptConSettings Settings_t
typedef NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS > Derived
typedef SCALAR Scalar_t
Public Member Functions
NLOptConSolver (const OptConProblem_t &optConProblem, const Settings_t &settings)
constructor
NLOptConSolver (const OptConProblem_t &optConProblem, const std::string &settingsFile, bool verbose=true, const std::string &ns="alg")
constructor
virtual ~NLOptConSolver ()
destructor
void initialize (const OptConProblem_t &optConProblem, const Settings_t &settings)
void configure (const Settings_t &settings) override
virtual void prepareIteration ()
virtual bool finishIteration ()
virtual void prepareMPCIteration ()
virtual bool finishMPCIteration ()
virtual bool runIteration () override
void setInitialGuess (const Policy_t &initialGuess) override
virtual bool solve () override
virtual const Policy_t & getSolution () override
virtual const core::StateTrajectory< STATE_DIM, SCALAR > getStateTrajectory () const override
virtual const core::ControlTrajectory< CONTROL_DIM, SCALAR > getControlTrajectory () const override
virtual const core::tpl::TimeArray< SCALAR > & getTimeArray () const override
virtual SCALAR getTimeHorizon () const override
Get the time horizon the solver currently operates on.
virtual void changeTimeHorizon (const SCALAR &tf) override
Change the time horizon the solver operates on.
virtual void changeInitialState (const core::StateVector< STATE_DIM, SCALAR > &x0) override
Change the initial state for the optimal control problem.
virtual void changeCostFunction (const typename OptConProblem_t::CostFunctionPtr_t &cf) override
Change the cost function.
virtual void changeNonlinearSystem (const typename OptConProblem_t::DynamicsPtr_t &dyn) override
Change the nonlinear system.
virtual void changeLinearSystem (const typename OptConProblem_t::LinearPtr_t &lin) override
Change the linear system.
virtual SCALAR getCost () const override
const Settings_t & getSettings ()
get a reference to the current settings
const std::shared_ptr< Backend_t > & getBackend ()
get a reference to the backend (
std::vector< typename OptConProblem_t::DynamicsPtr_t > & getNonlinearSystemsInstances () override
get reference to the nonlinear system
const std::vector< typename OptConProblem_t::DynamicsPtr_t > & getNonlinearSystemsInstances () const override
get constant reference to the nonlinear system
std::vector< typename OptConProblem_t::LinearPtr_t > & getLinearSystemsInstances () override
get reference to the linearized system
const std::vector< typename OptConProblem_t::LinearPtr_t > & getLinearSystemsInstances () const override
get constant reference to the linearized system
std::vector< typename OptConProblem_t::CostFunctionPtr_t > & getCostFunctionInstances () override
get reference to the cost function
const std::vector< typename OptConProblem_t::CostFunctionPtr_t > & getCostFunctionInstances () const override
get constant reference to the cost function
std::vector< typename OptConProblem_t::ConstraintPtr_t > & getBoxConstraintsInstances () override
get reference to the box constraints
const std::vector< typename OptConProblem_t::ConstraintPtr_t > & getBoxConstraintsInstances () const override
get constant reference to the boxconstraints
std::vector< typename OptConProblem_t::ConstraintPtr_t > & getGeneralConstraintsInstances () override
get reference to the general constraints
const std::vector< typename OptConProblem_t::ConstraintPtr_t > & getGeneralConstraintsInstances () const override
get constant reference to the general constraints
void logSummaryToMatlab (const std::string &fileName)
logging a short summary to matlab
Public Member Functions inherited from ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >
OptConSolver ()
virtual ~OptConSolver ()
virtual void setProblem (const OptConProblem_t &optConProblem)
Assigns the optimal control problem to the solver.
void configureFromFile (const std::string &filename, bool verbose=true, const std::string &ns=NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::SolverName)
virtual void setInitialGuess (const Policy_t &initialGuess)=0
virtual void changeBoxConstraints (const typename OptConProblem_t::ConstraintPtr_t con)
Change the box constraints.
virtual void changeGeneralConstraints (const typename OptConProblem_t::ConstraintPtr_t con)
Change the general constraints.
virtual void generateAndCompileCode (const ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar > &problemCG, const ct::core::DerivativesCppadSettings &settings)
Generates and compiles AD source code which can be used in the solver. This method can be called just before solving the problem, i.e. it can be called from the same executable than the actual solve.
virtual void generateCode (const ct::core::DerivativesCppadSettings &settings)
Generates source AD source code which can be used in the solver. This method needs to be called ahead of actually solving the problem (e.g. from a different executable)
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t STATE_D = STATE_DIM
static const size_t CONTROL_D = CONTROL_DIM
static const size_t POS_DIM = P_DIM
static const size_t VEL_DIM = V_DIM
Static Public Attributes inherited from ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >
static const size_t STATE_D
static const size_t CONTROL_D
Protected Attributes
std::shared_ptr< Backend_t > nlocBackend_
the backend holding all the math operations
std::shared_ptr< NLOCAlgorithm_t > nlocAlgorithm_
the algorithm for sequencing the math operations in correct manner
Additional Inherited Members
Public Attributes inherited from ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::conditional< CONTINUOUS, ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR > >::type OptConProblem_t
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true>
class ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >
Examples:
LinearSystemTest.h, NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_generalConstrained.cpp, NLOC_MPC.cpp, NonlinearSystemTest.h, switched_continuous_optcon.cpp, and SymplecticTest.h.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> typedef OptConSolver<NLOptConSolver<STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS>, typename NLOCAlgorithm<STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS>::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS> ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Base
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> typedef NLOptConSettings ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Settings_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> typedef SCALAR ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Scalar_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> typedef Base::OptConProblem_t ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> typedef NLOCAlgorithm<STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS> ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::NLOCAlgorithm_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> typedef NLOCAlgorithm_t::Policy_t ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> typedef NLOCAlgorithm_t::Backend_t ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Backend_t
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::NLOptConSolver (const OptConProblem_t & optConProblem, const Settings_t & settings)
constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::NLOptConSolver (const OptConProblem_t & optConProblem, const std::string & settingsFile, bool verbose = true, const std::string & ns = "alg")
constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::~NLOptConSolver () virtual
destructor
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocAlgorithm_, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_, and ct::optcon::NLOptConSettings::nlocp_algorithm.
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::initialize (const OptConProblem_t & optConProblem, const Settings_t & settings)
configures the solver
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_, and ct::optcon::NLOptConSettings::nThreads.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure (const Settings_t & settings) override virtual
configures the solver
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
Examples:
LinearSystemTest.h, NonlinearSystemTest.h, and SymplecticTest.h.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_, and ct::optcon::NLOptConSettings::nThreads.
Referenced by ct::optcon::example::symplecticTest(), and ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareIteration () virtual
execute preparation steps for an iteration, e.g. computation of defects
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocAlgorithm_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> bool ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishIteration () virtual
execute finishing step for an iteration, e.g. solving Riccati backward pass.
Returns
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocAlgorithm_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareMPCIteration () virtual
execute preparation steps for an iteration, e.g. computation of defects
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocAlgorithm_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> bool ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishMPCIteration () virtual
execute finishing step for an iteration, e.g. solving Riccati backward pass.
Returns
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocAlgorithm_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> bool ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration () override virtual
run a single iteration of the solver
Returns
true if a better solution was found
Reimplemented from ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
Examples:
LinearSystemTest.h, and SymplecticTest.h.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocAlgorithm_.
Referenced by ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), ct::optcon::example::symplecticTest(), and ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess (const Policy_t & initialGuess) override
Set the initial guess used by the solver (not all solvers might support initial guesses)
Examples:
LinearSystemTest.h, NonlinearSystemTest.h, and SymplecticTest.h.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
Referenced by generateSolver(), main(), ct::optcon::example::symplecticTest(), and ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> bool ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve () override virtual
solve the optimal control problem
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
Examples:
NonlinearSystemTest.h.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSettings(), and ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration().
Referenced by main(), and ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution () override virtual
Get the optimized control policy to the optimal control problem
Returns
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
Referenced by main(), and ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const core::StateTrajectory< STATE_DIM, SCALAR > ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getStateTrajectory () const override virtual
Get the optimized trajectory to the optimal control problem
Returns
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
Examples:
NonlinearSystemTest.h, and SymplecticTest.h.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
Referenced by ct::optcon::example::symplecticTest(), and ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const core::ControlTrajectory< CONTROL_DIM, SCALAR > ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getControlTrajectory () const override virtual
Get the optimal feedforward control input corresponding to the optimal trajectory
Returns
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
Examples:
NonlinearSystemTest.h, and SymplecticTest.h.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
Referenced by ct::optcon::example::symplecticTest(), and ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const core::tpl::TimeArray< SCALAR > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getTimeArray () const override virtual
Get the time indices corresponding to the solution
Returns
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> SCALAR ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getTimeHorizon () const override virtual
Get the time horizon the solver currently operates on.
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeTimeHorizon (const SCALAR & tf) override virtual
Change the time horizon the solver operates on.
This function does not need to be called if setOptConProblem() has been called with an OptConProblem that had the correct time horizon set.
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeInitialState (const core::StateVector< STATE_DIM, SCALAR > & x0) override virtual
Change the initial state for the optimal control problem.
This function does not need to be called if setOptConProblem() has been called with an OptConProblem that had the correct initial state set
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeCostFunction (const typename OptConProblem_t::CostFunctionPtr_t & cf) override virtual
Change the cost function.
This function does not need to be called if setOptConProblem() has been called with an OptConProblem that had the correct cost function
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeNonlinearSystem (const typename OptConProblem_t::DynamicsPtr_t & dyn) override virtual
Change the nonlinear system.
This function does not need to be called if setOptConProblem() has been called with an OptConProblem that had the correct nonlinear system
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeLinearSystem (const typename OptConProblem_t::LinearPtr_t & lin) override virtual
Change the linear system.
This function does not need to be called if setOptConProblem() has been called with an OptConProblem that had the correct linear system
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> SCALAR ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getCost () const override virtual
Reimplemented from ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Settings_t & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSettings ()
get a reference to the current settings
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
Referenced by ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const std::shared_ptr< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Backend_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getBackend ()
get a reference to the backend (
Todo:
this is not optimal, allows the user too much access)
Examples:
LinearSystemTest.h.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
Referenced by ct::optcon::example::TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::DynamicsPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getNonlinearSystemsInstances () override virtual
get reference to the nonlinear system
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::DynamicsPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getNonlinearSystemsInstances () const override virtual
get constant reference to the nonlinear system
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::LinearPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getLinearSystemsInstances () override virtual
get reference to the linearized system
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::LinearPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getLinearSystemsInstances () const override virtual
get constant reference to the linearized system
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::CostFunctionPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getCostFunctionInstances () override virtual
get reference to the cost function
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::CostFunctionPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getCostFunctionInstances () const override virtual
get constant reference to the cost function
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::ConstraintPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getBoxConstraintsInstances () override virtual
get reference to the box constraints
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::ConstraintPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getBoxConstraintsInstances () const override virtual
get constant reference to the boxconstraints
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::ConstraintPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getGeneralConstraintsInstances () override virtual
get reference to the general constraints
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> const std::vector< typename NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::OptConProblem_t::ConstraintPtr_t > & ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getGeneralConstraintsInstances () const override virtual
get constant reference to the general constraints
Implements ct::optcon::OptConSolver< NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >, NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t, NLOptConSettings, STATE_DIM, CONTROL_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::logSummaryToMatlab (const std::string & fileName)
logging a short summary to matlab
References ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_.
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::STATE_D = STATE_DIM static
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> const size_t ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::CONTROL_D = CONTROL_DIM static
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> const size_t ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::POS_DIM = P_DIM static
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> const size_t ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::VEL_DIM = V_DIM static
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> std::shared_ptr<Backend_t> ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocBackend_ protected
the backend holding all the math operations
Referenced by ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeCostFunction(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeInitialState(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeLinearSystem(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeNonlinearSystem(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeTimeHorizon(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getBackend(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getBoxConstraintsInstances(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getControlTrajectory(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getCost(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getCostFunctionInstances(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getGeneralConstraintsInstances(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getLinearSystemsInstances(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getNonlinearSystemsInstances(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSettings(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getStateTrajectory(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getTimeArray(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getTimeHorizon(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::initialize(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::logSummaryToMatlab(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), and ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::~NLOptConSolver().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double, bool CONTINUOUS = true> std::shared_ptr<NLOCAlgorithm_t> ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::nlocAlgorithm_ protected
the algorithm for sequencing the math operations in correct manner
Referenced by ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishMPCIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareMPCIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration(), and ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::~NLOptConSolver().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/solver/NLOptConSolver.hpp
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/solver/NLOptConSolver-impl.hpp