ct::optcon::NlpSolverSettings Class Reference
ct::optcon::NlpSolverSettings Class Reference
NLP
Contains the NLP solver settings.
#include <NlpSolverSettings.h>
Public Member Functions
NlpSolverSettings ()
Default constructor, set default settings.
void print ()
Prints out settings.
bool parametersOk () const
Checks whether to settings are filled with meaningful values.
void load (const std::string &filename, bool verbose=true, const std::string &ns="solver")
Loads the settings from a .info file.
Public Attributes
NlpSolverType solverType_
bool useGeneratedCostGradient_
bool useGeneratedConstraintJacobian_
SnoptSettings snoptSettings_
IpoptSettings ipoptSettings_
Detailed Description
Contains the NLP solver settings.
Constructor & Destructor Documentation
ct::optcon::NlpSolverSettings::NlpSolverSettings () inline
Default constructor, set default settings.
Member Function Documentation
void ct::optcon::NlpSolverSettings::print () inline
Prints out settings.
References ct::optcon::IPOPT, ct::optcon::SnoptSettings::print(), ct::optcon::IpoptSettings::print(), and ct::optcon::SNOPT.
Referenced by ct::optcon::DmsSettings::print().
bool ct::optcon::NlpSolverSettings::parametersOk () const inline
Checks whether to settings are filled with meaningful values.
Returns
Returns true of the parameters are ok
References ct::optcon::IPOPT, ct::optcon::SnoptSettings::parametersOk(), ct::optcon::IpoptSettings::parametersOk(), and ct::optcon::SNOPT.
Referenced by ct::optcon::DmsSettings::parametersOk().
void ct::optcon::NlpSolverSettings::load (const std::string & filename, bool verbose = true, const std::string & ns = "solver") inline
Loads the settings from a .info file.
Parameters
[in] filename The filename
[in] verbose True if parameters to be printed out
[in] ns The namespace in the .info fil
References ct::optcon::IPOPT, ct::optcon::SnoptSettings::load(), ct::optcon::IpoptSettings::load(), ct::optcon::SNOPT, and ct::optcon::example::verbose.
Referenced by ct::optcon::DmsSettings::load().
Member Data Documentation
NlpSolverType ct::optcon::NlpSolverSettings::solverType_
Examples:
DMS.cpp, and oscDMSTest.cpp.
Referenced by ct::optcon::example::OscDms::getIpoptSolution(), ct::optcon::example::OscDms::getSnoptSolution(), main(), and ct::optcon::example::TEST().
bool ct::optcon::NlpSolverSettings::useGeneratedCostGradient_
Referenced by ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::generateAndCompileCode().
bool ct::optcon::NlpSolverSettings::useGeneratedConstraintJacobian_
Referenced by ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::generateAndCompileCode().
SnoptSettings ct::optcon::NlpSolverSettings::snoptSettings_
IpoptSettings ct::optcon::NlpSolverSettings::ipoptSettings_
Referenced by main().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/nlp/solver/NlpSolverSettings.h