ct::optcon::tpl::NlpSolver< SCALAR > Class Template Reference
ct::optcon::tpl::NlpSolver< SCALAR > Class Template Reference abstract
NLP
Abstract base class for the NLP solvers.
#include <NlpSolver.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW NlpSolver ()
Default constructor.
NlpSolver (std::shared_ptr< Nlp< SCALAR >> nlp)
Custom Constructor 1.
NlpSolver (std::shared_ptr< Nlp< SCALAR >> nlp, NlpSolverSettings settings)
Custom constructor 2.
virtual ~NlpSolver ()=default
Destructor.
void configure (const NlpSolverSettings &settings)
Configures the solver with new settings.
virtual void configureDerived (const NlpSolverSettings &settings)=0
Forwards the settings to the corresponding nlp solver.
virtual bool solve ()=0
Solves the nlp.
virtual void prepareWarmStart (const size_t maxIterations)=0
Prepares the solver for a warmstarting scenario with available (good) initial guess.
bool isInitialized ()
Protected Attributes
std::shared_ptr< Nlp< SCALAR > > nlp_
NlpSolverSettings settings_
bool isInitialized_
Detailed Description
template<typename SCALAR>
class ct::optcon::tpl::NlpSolver< SCALAR >
Abstract base class for the NLP solvers.
Constructor & Destructor Documentation
template<typename SCALAR > EIGEN_MAKE_ALIGNED_OPERATOR_NEW ct::optcon::tpl::NlpSolver< SCALAR >::NlpSolver () inline
Default constructor.
template<typename SCALAR > ct::optcon::tpl::NlpSolver< SCALAR >::NlpSolver (std::shared_ptr< Nlp< SCALAR >> nlp) inline
Custom Constructor 1.
Parameters
[in] nlp The nlp
template<typename SCALAR > ct::optcon::tpl::NlpSolver< SCALAR >::NlpSolver (std::shared_ptr< Nlp< SCALAR >> nlp, NlpSolverSettings settings) inline
Custom constructor 2.
Parameters
[in] nlp The nlp
[in] settings Custom user settings
References ct::optcon::tpl::NlpSolver< SCALAR >::~NlpSolver().
template<typename SCALAR > virtual ct::optcon::tpl::NlpSolver< SCALAR >::~NlpSolver () virtual default
Destructor.
Referenced by ct::optcon::tpl::NlpSolver< SCALAR >::NlpSolver().
Member Function Documentation
template<typename SCALAR > void ct::optcon::tpl::NlpSolver< SCALAR >::configure (const NlpSolverSettings & settings) inline
Configures the solver with new settings.
Parameters
[in] settings The nlp solver settings
References ct::optcon::tpl::NlpSolver< SCALAR >::configureDerived(), ct::optcon::tpl::NlpSolver< SCALAR >::prepareWarmStart(), ct::optcon::tpl::NlpSolver< SCALAR >::settings_, and ct::optcon::tpl::NlpSolver< SCALAR >::solve().
template<typename SCALAR > virtual void ct::optcon::tpl::NlpSolver< SCALAR >::configureDerived (const NlpSolverSettings & settings) pure virtual
Forwards the settings to the corresponding nlp solver.
Parameters
[in] settings The nlp settings
Implemented in ct::optcon::SnoptSolver, and ct::optcon::tpl::IpoptSolver< SCALAR >.
Referenced by ct::optcon::tpl::NlpSolver< SCALAR >::configure().
template<typename SCALAR > virtual bool ct::optcon::tpl::NlpSolver< SCALAR >::solve () pure virtual
Solves the nlp.
Returns
Returns true of solve succeeded
Implemented in ct::optcon::SnoptSolver, and ct::optcon::tpl::IpoptSolver< SCALAR >.
Referenced by ct::optcon::tpl::NlpSolver< SCALAR >::configure().
template<typename SCALAR > virtual void ct::optcon::tpl::NlpSolver< SCALAR >::prepareWarmStart (const size_t maxIterations) pure virtual
Prepares the solver for a warmstarting scenario with available (good) initial guess.
Parameters
[in] maxIterations Specifies the maximum number of nlp iteration the user is willing to spend
Implemented in ct::optcon::SnoptSolver, and ct::optcon::tpl::IpoptSolver< SCALAR >.
Referenced by ct::optcon::tpl::NlpSolver< SCALAR >::configure().
template<typename SCALAR > bool ct::optcon::tpl::NlpSolver< SCALAR >::isInitialized () inline
References ct::optcon::tpl::NlpSolver< SCALAR >::isInitialized_.
Member Data Documentation
template<typename SCALAR > std::shared_ptr<Nlp<SCALAR> > ct::optcon::tpl::NlpSolver< SCALAR >::nlp_ protected
The non linear program
template<typename SCALAR > NlpSolverSettings ct::optcon::tpl::NlpSolver< SCALAR >::settings_ protected
The nlp settings
Referenced by ct::optcon::tpl::NlpSolver< SCALAR >::configure().
template<typename SCALAR > bool ct::optcon::tpl::NlpSolver< SCALAR >::isInitialized_ protected
Indicates whether the solver is initialized
Referenced by ct::optcon::tpl::NlpSolver< SCALAR >::isInitialized().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/nlp/solver/NlpSolver.h