ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR > Class Template Reference
ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR > Class Template Reference abstract
interface base class for optimal control algorithms
#include <OptconSystemInterface.h>
Public Types
typedef ct::core::StateVector< STATE_DIM, SCALAR > state_vector_t
typedef ct::core::StateMatrix< STATE_DIM, SCALAR > state_matrix_t
typedef ct::core::StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
typedef ct::core::StateVectorArray< STATE_DIM, SCALAR > StateVectorArray
typedef std::shared_ptr< StateVectorArray > StateVectorArrayPtr
typedef std::vector< StateVectorArrayPtr, Eigen::aligned_allocator< StateVectorArrayPtr > > StateSubsteps
typedef std::shared_ptr< StateSubsteps > StateSubstepsPtr
typedef ct::core::ControlVectorArray< CONTROL_DIM, SCALAR > ControlVectorArray
typedef std::shared_ptr< ControlVectorArray > ControlVectorArrayPtr
typedef std::vector< ControlVectorArrayPtr, Eigen::aligned_allocator< ControlVectorArrayPtr > > ControlSubsteps
typedef std::shared_ptr< ControlSubsteps > ControlSubstepsPtr
typedef ct::core::ConstantController< STATE_DIM, CONTROL_DIM, SCALAR > constant_controller_t
typedef std::shared_ptr< constant_controller_t > ConstantControllerPtr
typedef OPTCONPROBLEM optConProblem_t
typedef NLOptConSettings settings_t
Public Member Functions
OptconSystemInterface (const optConProblem_t &problem, const settings_t &settings)
constructor
virtual void initialize ()
perform any required setup work
virtual void configure (const settings_t &settings)
virtual void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t subSteps, state_matrix_t &A, state_control_matrix_t &B, const size_t threadId)=0
retrieve discrete-time linear system matrices A and B.
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext, const size_t threadId)=0
propagate discrete-time dynamics
virtual void changeNumStages (const int numStages)
set the number of stages/time steps
const optConProblem_t & getOptConProblem ()
std::vector< typename optConProblem_t::DynamicsPtr_t > & getNonlinearSystemsInstances ()
std::vector< typename optConProblem_t::LinearPtr_t > & getLinearSystemsInstances ()
virtual void changeNonlinearSystem (const typename optConProblem_t::DynamicsPtr_t &dyn)=0
virtual void changeLinearSystem (const typename optConProblem_t::LinearPtr_t &lin)=0
virtual void getSubstates (StateVectorArrayPtr &subStepsX, const size_t threadId)
virtual void getSubcontrols (ControlVectorArrayPtr &subStepsU, const size_t threadId)
virtual void setSubstepTrajectoryReference (const StateSubstepsPtr &xSubsteps, const ControlSubstepsPtr &uSubsteps, const size_t threadId)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Protected Attributes
std::vector< typename optConProblem_t::DynamicsPtr_t > systems_
std::vector< typename optConProblem_t::LinearPtr_t > linearSystems_
std::vector< ConstantControllerPtr, Eigen::aligned_allocator< ConstantControllerPtr > > controller_
optConProblem_t optConProblem_
the constant controller for forward-integration during one time-step
settings_t settings_
instance of the optconProblem
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double>
class ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >
interface base class for optimal control algorithms
Defines the unified interface for optimal control solvers. It bundles the optimal control problem with required tools to propagate the system dynamics and provide corresponding sensitivities.
Template Parameters
STATE_DIM size of state vector
CONTROL_DIM size of input vector
OPTCONPROBLEM type of the optConProblem (continuous or discrete)
SCALAR the underlying scalar type
Member Typedef Documentation
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef ct::core::StateVector<STATE_DIM, SCALAR> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::state_vector_t
state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef ct::core::StateMatrix<STATE_DIM, SCALAR> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::state_matrix_t
state_control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef ct::core::StateControlMatrix<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::state_control_matrix_t
StateVectorArray
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef ct::core::StateVectorArray<STATE_DIM, SCALAR> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::StateVectorArray
StateVectorArrayPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef std::shared_ptr<StateVectorArray> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::StateVectorArrayPtr
StateSubsteps
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef std::vector<StateVectorArrayPtr, Eigen::aligned_allocator<StateVectorArrayPtr> > ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::StateSubsteps
StateSubstepsPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef std::shared_ptr<StateSubsteps> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::StateSubstepsPtr
ControlVectorArray
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef ct::core::ControlVectorArray<CONTROL_DIM, SCALAR> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::ControlVectorArray
ControlVectorArrayPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef std::shared_ptr<ControlVectorArray> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::ControlVectorArrayPtr
ControlSubsteps
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef std::vector<ControlVectorArrayPtr, Eigen::aligned_allocator<ControlVectorArrayPtr> > ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::ControlSubsteps
ControlSubstepsPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef std::shared_ptr<ControlSubsteps> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::ControlSubstepsPtr
constant_controller_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef ct::core::ConstantController<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::constant_controller_t
ConstantControllerPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef std::shared_ptr<constant_controller_t> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::ConstantControllerPtr
optConProblem_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef OPTCONPROBLEM ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::optConProblem_t
settings_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> typedef NLOptConSettings ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::settings_t
Constructor & Destructor Documentation
OptconSystemInterface()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::OptconSystemInterface (const optConProblem_t & problem, const settings_t & settings) inline
constructor
Member Function Documentation
initialize()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::initialize () inline virtual
perform any required setup work
Reimplemented in ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >, and ct::optcon::OptconDiscreteSystemInterface< STATE_DIM, CONTROL_DIM, SCALAR >.
configure()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::configure (const settings_t & settings) inline virtual
getAandB()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::getAandB (const state_vector_t & x, const control_vector_t & u, const state_vector_t & x_next, const int n, size_t subSteps, state_matrix_t & A, state_control_matrix_t & B, const size_t threadId) pure virtual
retrieve discrete-time linear system matrices A and B.
Parameters
x the state setpoint
u the control setpoint
x_next the next state
n the time setpoint
subSteps number of substeps of trajectory for which to get the sensitivity for
A the resulting linear system matrix A
B the resulting linear system matrix B
threadId which thread specific instantiations to use
Referenced by ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::configure().
propagateControlledDynamics()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::propagateControlledDynamics (const state_vector_t & state, const time_t n, const control_vector_t & control, state_vector_t & stateNext, const size_t threadId) pure virtual
propagate discrete-time dynamics
Parameters
state start state to propagate from
n discrete time index to propagate the dynamics at
control the control input to apply. This is a constant control input applied during the discretization interval
stateNext the resulting propagated state
threadId which thread specific instantiations to use
Referenced by ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::configure().
changeNumStages()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::changeNumStages (const int numStages) inline virtual
set the number of stages/time steps
Reimplemented in ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >.
getOptConProblem()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> const optConProblem_t& ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::getOptConProblem () inline
getNonlinearSystemsInstances()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> std::vector<typename optConProblem_t::DynamicsPtr_t>& ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::getNonlinearSystemsInstances () inline
getLinearSystemsInstances()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> std::vector<typename optConProblem_t::LinearPtr_t>& ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::getLinearSystemsInstances () inline
changeNonlinearSystem()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::changeNonlinearSystem (const typename optConProblem_t::DynamicsPtr_t & dyn) pure virtual
Referenced by ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::getLinearSystemsInstances().
changeLinearSystem()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::changeLinearSystem (const typename optConProblem_t::LinearPtr_t & lin) pure virtual
Referenced by ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::getLinearSystemsInstances().
getSubstates()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::getSubstates (StateVectorArrayPtr & subStepsX, const size_t threadId) inline virtual
getSubcontrols()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::getSubcontrols (ControlVectorArrayPtr & subStepsU, const size_t threadId) inline virtual
setSubstepTrajectoryReference()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> virtual void ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::setSubstepTrajectoryReference (const StateSubstepsPtr & xSubsteps, const ControlSubstepsPtr & uSubsteps, const size_t threadId) inline virtual
Member Data Documentation
control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::control_vector_t
systems_
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> std::vector<typename optConProblem_t::DynamicsPtr_t> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::systems_ protected
of the following objects, we have nThreads+1 instantiations in form of a vector. Every instantiation is dedicated to a certain thread in the multi-thread implementation
Referenced by ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::getNonlinearSystemsInstances().
linearSystems_
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> std::vector<typename optConProblem_t::LinearPtr_t> ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::linearSystems_ protected
Referenced by ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::getLinearSystemsInstances().
controller_
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> std::vector<ConstantControllerPtr, Eigen::aligned_allocator<ConstantControllerPtr> > ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::controller_ protected
Referenced by ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::OptconSystemInterface().
optConProblem_
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> optConProblem_t ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::optConProblem_ protected
the constant controller for forward-integration during one time-step
Referenced by ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::getOptConProblem().
settings_
template<size_t STATE_DIM, size_t CONTROL_DIM, typename OPTCONPROBLEM, typename SCALAR = double> settings_t ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, OPTCONPROBLEM, SCALAR >::settings_ protected
instance of the optconProblem
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/system_interface/OptconSystemInterface.h