ct::optcon::SnoptSettings Class Reference
ct::optcon::SnoptSettings Class Reference
NLP
SnoptSolver settings. Details about the parameters can be found in the SNOPT documentation.
#include <NlpSolverSettings.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW SnoptSettings ()
Default constructor, sets the parameters to default values.
void print ()
Prints out information about the settings.
bool parametersOk () const
Checks whether to settings are filled with meaningful values.
void load (const std::string &filename, bool verbose=true, const std::string &ns="dms.solver.snopt")
Loads the settings from a .info file.
Public Attributes
int scale_option_param_
int derivative_option_param_
int verify_level_param_
int major_iteration_limit_param_
int minor_iteration_limit_param_
int iteration_limit_param_
double major_optimality_tolerance_param_
double major_feasibility_tolerance_param_
double minor_feasibility_tolerance_param_
int print_file_param_
int minor_print_level_param_
int major_print_level_param_
int new_basis_file_param_
int old_basis_file_param_
int backup_basis_file_param_
double line_search_tolerance_param_
int crash_option_
int hessian_updates_
Detailed Description
SnoptSolver settings. Details about the parameters can be found in the SNOPT documentation.
Constructor & Destructor Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW ct::optcon::SnoptSettings::SnoptSettings () inline
Default constructor, sets the parameters to default values.
Member Function Documentation
void ct::optcon::SnoptSettings::print () inline
Prints out information about the settings.
Referenced by ct::optcon::NlpSolverSettings::print().
bool ct::optcon::SnoptSettings::parametersOk () const inline
Checks whether to settings are filled with meaningful values.
Returns
Returns true of the parameters are ok
Referenced by ct::optcon::NlpSolverSettings::parametersOk().
void ct::optcon::SnoptSettings::load (const std::string & filename, bool verbose = true, const std::string & ns = "dms.solver.snopt") inline
Loads the settings from a .info file.
Parameters
[in] filename The filename
[in] verbose True if parameters to be printed out
[in] ns The namespace in the .info file
Referenced by ct::optcon::NlpSolverSettings::load().
Member Data Documentation
int ct::optcon::SnoptSettings::scale_option_param_
int ct::optcon::SnoptSettings::derivative_option_param_
int ct::optcon::SnoptSettings::verify_level_param_
int ct::optcon::SnoptSettings::major_iteration_limit_param_
int ct::optcon::SnoptSettings::minor_iteration_limit_param_
int ct::optcon::SnoptSettings::iteration_limit_param_
double ct::optcon::SnoptSettings::major_optimality_tolerance_param_
double ct::optcon::SnoptSettings::major_feasibility_tolerance_param_
double ct::optcon::SnoptSettings::minor_feasibility_tolerance_param_
int ct::optcon::SnoptSettings::print_file_param_
int ct::optcon::SnoptSettings::minor_print_level_param_
int ct::optcon::SnoptSettings::major_print_level_param_
int ct::optcon::SnoptSettings::new_basis_file_param_
int ct::optcon::SnoptSettings::old_basis_file_param_
int ct::optcon::SnoptSettings::backup_basis_file_param_
double ct::optcon::SnoptSettings::line_search_tolerance_param_
int ct::optcon::SnoptSettings::crash_option_
int ct::optcon::SnoptSettings::hessian_updates_
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/nlp/solver/NlpSolverSettings.h