ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference abstract
#include <LQOCSolver.hpp>
Public Member Functions
LQOCSolver (const std::shared_ptr< LQOCProblem_t > &lqocProblem=nullptr)
virtual ~LQOCSolver ()
destructor
void setProblem (std::shared_ptr< LQOCProblem_t > lqocProblem)
virtual void configure (const NLOptConSettings &settings)=0
virtual void configureBoxConstraints (std::shared_ptr< LQOCProblem< STATE_DIM, CONTROL_DIM >> lqocProblem)
setup and configure the box constraints
virtual void configureGeneralConstraints (std::shared_ptr< LQOCProblem< STATE_DIM, CONTROL_DIM >> lqocProblem)
setup and configure the general (in)equality constraints
virtual void initializeAndAllocate ()=0
a method reserved for memory allocation (e.g. required for HPIPM)
virtual void solve ()=0
solve the LQOC problem
virtual void extractLQSolution ()
extract the solution (can be overriden if additional extraction steps required in specific solver)
virtual void solveSingleStage (int N)
virtual SCALAR getSmallestEigenvalue ()
const ct::core::StateVectorArray< STATE_DIM, SCALAR > & getSolutionState ()
const ct::core::ControlVectorArray< CONTROL_DIM, SCALAR > & getSolutionControl ()
const ct::core::FeedbackArray< STATE_DIM, CONTROL_DIM, SCALAR > & getSolutionFeedback ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR > LQOCProblem_t
Protected Member Functions
virtual void setProblemImpl (std::shared_ptr< LQOCProblem_t > lqocProblem)=0
Protected Attributes
std::shared_ptr< LQOCProblem_t > lqocProblem_
core::StateVectorArray< STATE_DIM, SCALAR > x_sol_
core::ControlVectorArray< CONTROL_DIM, SCALAR > u_sol_
ct::core::FeedbackArray< STATE_DIM, CONTROL_DIM, SCALAR > L_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >
Base class for solvers to solve an LQOCProblem (both constrained / unconstrained, etc.)
Todo:
uncouple from NLOptConSettings
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::LQOCSolver (const std::shared_ptr< LQOCProblem_t > & lqocProblem = nullptr) inline
Constructor. Initialize by handing over an LQOCProblem, or otherwise by calling setProblem()
Parameters
lqocProblem shared_ptr to the LQOCProblem to be solved.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::~LQOCSolver () inline virtual
destructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::setProblem (std::shared_ptr< LQOCProblem_t > lqocProblem) inline
set a new problem update the shared_ptr to the LQOCProblem instance and call initialize instance deriving from this class.
Parameters
lqocProblem
References ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::configure(), ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::lqocProblem_, and ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::setProblemImpl().
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::configure (const NLOptConSettings & settings) pure virtual
Implemented in ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::setProblem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::configureBoxConstraints (std::shared_ptr< LQOCProblem< STATE_DIM, CONTROL_DIM >> lqocProblem) inline virtual
setup and configure the box constraints
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::configureGeneralConstraints (std::shared_ptr< LQOCProblem< STATE_DIM, CONTROL_DIM >> lqocProblem) inline virtual
setup and configure the general (in)equality constraints
References ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::initializeAndAllocate(), and ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::solve().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::initializeAndAllocate () pure virtual
a method reserved for memory allocation (e.g. required for HPIPM)
Implemented in ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::configureGeneralConstraints().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::solve () pure virtual
solve the LQOC problem
Implemented in ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::configureGeneralConstraints().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::extractLQSolution () inline virtual
extract the solution (can be overriden if additional extraction steps required in specific solver)
Reimplemented in ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::solveSingleStage (int N) inline virtual
Reimplemented in ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual SCALAR ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSmallestEigenvalue () inline virtual
Reimplemented in ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const ct::core::StateVectorArray<STATE_DIM, SCALAR>& ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionState () inline
References ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::x_sol_.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const ct::core::ControlVectorArray<CONTROL_DIM, SCALAR>& ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionControl () inline
References ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::u_sol_.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const ct::core::FeedbackArray<STATE_DIM, CONTROL_DIM, SCALAR>& ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionFeedback () inline
References ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::L_, and ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::setProblemImpl().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::setProblemImpl (std::shared_ptr< LQOCProblem_t > lqocProblem) protected pure virtual
Referenced by ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionFeedback(), and ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::setProblem().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef LQOCProblem<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::LQOCProblem_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> std::shared_ptr<LQOCProblem_t> ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::lqocProblem_ protected
Referenced by ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::computeCostToGo(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::designController(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::extractLQSolution(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::initializeCostToGo(), ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::setProblem(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::solve(), and ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::solveSingleStage().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> core::StateVectorArray<STATE_DIM, SCALAR> ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::x_sol_ protected
Referenced by ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::changeNumberOfStages(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::extractLQSolution(), and ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> core::ControlVectorArray<CONTROL_DIM, SCALAR> ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::u_sol_ protected
Referenced by ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::changeNumberOfStages(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::extractLQSolution(), and ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionControl().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::FeedbackArray<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::L_ protected
Referenced by ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::changeNumberOfStages(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::computeCostToGo(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::designController(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::extractLQSolution(), ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionFeedback(), and ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::logToMatlab().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/solver/lqp/LQOCSolver.hpp