ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
CostFunction
A cost function which contains only terms that have analytical derivatives.
#include <CostFunctionAnalytical.hpp>
Public Types
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Types inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
typedef CostFunction< STATE_DIM, CONTROL_DIM, SCALAR > BASE
Public Types inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
typedef core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Member Functions
CostFunctionAnalytical ()
Basic constructor.
CostFunctionAnalytical (const CostFunctionAnalytical &arg)
Copy constructor.
CostFunctionAnalytical (const std::string &filename, bool verbose=false)
Constructor loading function from file.
CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override
~CostFunctionAnalytical ()
SCALAR evaluateIntermediate () override
evaluate intermediate costs
SCALAR evaluateTerminal () override
evaluate terminal costs
state_vector_t stateDerivativeIntermediate () override
Computes intermediate-cost first-order derivative with respect to state.
state_vector_t stateDerivativeTerminal () override
state_matrix_t stateSecondDerivativeIntermediate () override
Computes intermediate-cost second-order derivative with respect to state.
state_matrix_t stateSecondDerivativeTerminal () override
Computes final-cost second-order derivative with respect to state.
control_vector_t controlDerivativeIntermediate () override
Computes intermediate-cost first-order derivative with respect to control.
control_vector_t controlDerivativeTerminal () override
Computes terminal-cost first-order derivative with respect to control.
control_matrix_t controlSecondDerivativeIntermediate () override
Computes intermediate-cost second-order derivative with respect to input.
control_matrix_t controlSecondDerivativeTerminal () override
Computes final-cost second-order derivative with respect to input.
control_state_matrix_t stateControlDerivativeIntermediate () override
Computes intermediate-cost derivative with respect to state and control.
control_state_matrix_t stateControlDerivativeTerminal () override
Computes final-cost derivative with respect to state and control.
void loadFromConfigFile (const std::string &filename, bool verbose=false) override
Loads cost function from config file.
Public Member Functions inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
CostFunctionQuadratic ()
CostFunctionQuadratic (const CostFunctionQuadratic &arg)
virtual ~CostFunctionQuadratic ()
virtual size_t addIntermediateTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR >> term, bool verbose=false)
Adds an intermediate term.
virtual size_t addFinalTerm (std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR >> term, bool verbose=false)
Adds a final term.
virtual void updateReferenceState (const state_vector_t &x_ref)
update the reference state for intermediate cost terms
virtual void updateFinalState (const state_vector_t &x_final)
update the reference state for final cost terms
virtual void updateReferenceControl (const control_vector_t &u_ref)
update the reference control for intermediate cost terms
bool stateDerivativeIntermediateTest (bool verbose=false)
compare the state derivative against numerical differentiation
bool controlDerivativeIntermediateTest (bool verbose=false)
compare the control derivative against numerical differentiation
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getIntermediateTermById (const size_t id)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getFinalTermById (const size_t id)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getIntermediateTermByName (const std::string &name)
std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > getFinalTermByName (const std::string &name)
virtual void initialize ()
initialize the cost function (e.g. to be used in CostFunctionAD)
Public Member Functions inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
CostFunction ()
Default constructor.
virtual ~CostFunction ()
Destructor.
CostFunction (const CostFunction &arg)
Copy constructor.
virtual void setCurrentStateAndControl (const state_vector_t &x, const control_vector_t &u, const SCALAR &t=SCALAR(0.0))
virtual void getCurrentStateAndControl (Eigen::Matrix< SCALAR, STATE_DIM, 1 > &x, Eigen::Matrix< SCALAR, CONTROL_DIM, 1 > &u, SCALAR &t) const
sets current state, control and time
virtual void shiftTime (const SCALAR t)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix< SCALAR, STATE_DIM, STATE_DIM > state_matrix_t
Public Attributes inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix< SCALAR, STATE_DIM, STATE_DIM > state_matrix_t
Public Attributes inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Additional Inherited Members
Protected Member Functions inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
SCALAR evaluateIntermediateBase ()
evaluate intermediate analytical cost terms
SCALAR evaluateTerminalBase ()
evaluate terminal analytical cost terms
state_vector_t stateDerivativeIntermediateBase ()
evaluate intermediate analytical state derivatives
state_vector_t stateDerivativeTerminalBase ()
evaluate terminal analytical state derivatives
state_matrix_t stateSecondDerivativeIntermediateBase ()
evaluate intermediate analytical state second derivatives
state_matrix_t stateSecondDerivativeTerminalBase ()
evaluate terminal analytical state second derivatives
control_vector_t controlDerivativeIntermediateBase ()
evaluate intermediate analytical control derivatives
control_vector_t controlDerivativeTerminalBase ()
evaluate terminal analytical control derivatives
control_matrix_t controlSecondDerivativeIntermediateBase ()
evaluate intermediate analytical control second derivatives
control_matrix_t controlSecondDerivativeTerminalBase ()
evaluate terminal analytical control second derivatives
control_state_matrix_t stateControlDerivativeIntermediateBase ()
evaluate intermediate analytical control mixed state control derivatives
control_state_matrix_t stateControlDerivativeTerminalBase ()
evaluate terminal analytical control mixed state control derivatives
state_vector_t stateDerivativeIntermediateNumDiff ()
compute the state derivative by numerical differentiation (can be used for testing)
control_vector_t controlDerivativeIntermediateNumDiff ()
compute the control derivative by numerical differentiation (can be used for testing)
Protected Attributes inherited from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >
SCALAR eps_
stepsize for numerical differentiation
bool doubleSidedDerivative_ = true
use double sided derivatives in numerical differentiation
std::vector< std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > > intermediateCostAnalytical_
std::vector< std::shared_ptr< TermBase< STATE_DIM, CONTROL_DIM, SCALAR > > > finalCostAnalytical_
Protected Attributes inherited from ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >
state_vector_t x_
control_vector_t u_
SCALAR t_
SCALAR t_shift_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >
A cost function which contains only terms that have analytical derivatives.
This class provides functions to evaluate a cost function and computes its first and second order derivatives. This cost function assumes that analytical derivatives for all terms are available.
Examples:
DMS.cpp, NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_generalConstrained.cpp, NLOC_MPC.cpp, and NonlinearSystemTest.h.
Member Typedef Documentation
control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, CONTROL_DIM, CONTROL_DIM> ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t
control_state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, CONTROL_DIM, STATE_DIM> ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::StateVector<STATE_DIM, SCALAR> ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
Constructor & Destructor Documentation
CostFunctionAnalytical() [1/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAnalytical ()
Basic constructor.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::clone().
CostFunctionAnalytical() [2/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAnalytical (const CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > & arg)
Copy constructor.
Parameters
arg cost function to copy
CostFunctionAnalytical() [3/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAnalytical (const std::string & filename, bool verbose = false)
Constructor loading function from file.
Parameters
filename config file location
verbose flag enabling printouts
References ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile().
~CostFunctionAnalytical()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::~CostFunctionAnalytical ()
Destructor
Member Function Documentation
clone()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > * ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const override virtual
Deep-cloning of cost function
Returns
base pointer to clone
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAnalytical().
evaluateIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SCALAR ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate () override virtual
evaluate intermediate costs
Evaluates the running/intermediate cost function for the control, state and time set in setCurrentStateAndControl()
Returns
costs
Implements ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediateBase().
evaluateTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > SCALAR ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal () override virtual
evaluate terminal costs
Evaluates the terminal cost for a given state and control set in setCurrentStateAndControl(). This usually ignores time.
Returns
costs
Implements ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminalBase().
stateDerivativeIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate () override virtual
Computes intermediate-cost first-order derivative with respect to state.
Returns
derivative vector (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediateBase().
Referenced by ct::optcon::example::TEST().
stateDerivativeTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminal () override virtual
Computes terminal-cost first-order derivative with respect to state
Returns
derivative vector (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminalBase().
Referenced by ct::optcon::example::TEST().
stateSecondDerivativeIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediate () override virtual
Computes intermediate-cost second-order derivative with respect to state.
Returns
derivative matrix (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediateBase().
Referenced by ct::optcon::example::TEST().
stateSecondDerivativeTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminal () override virtual
Computes final-cost second-order derivative with respect to state.
Returns
derivative matrix (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminalBase().
Referenced by ct::optcon::example::TEST().
controlDerivativeIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate () override virtual
Computes intermediate-cost first-order derivative with respect to control.
Returns
derivative vector (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediateBase().
Referenced by ct::optcon::example::TEST().
controlDerivativeTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminal () override virtual
Computes terminal-cost first-order derivative with respect to control.
Not available for all cost functions. Throws an exception if not available.
Returns
derivative vector (Jacobian)
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminalBase().
controlSecondDerivativeIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediate () override virtual
Computes intermediate-cost second-order derivative with respect to input.
Returns
derivative matrix (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediateBase().
Referenced by ct::optcon::example::TEST().
controlSecondDerivativeTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminal () override virtual
Computes final-cost second-order derivative with respect to input.
Not available for all cost functions. Throws an exception if not available.
Returns
derivative matrix (Jacobian)
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminalBase().
stateControlDerivativeIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediate () override virtual
Computes intermediate-cost derivative with respect to state and control.
Returns
derivative matrix (Jacobian)
Implements ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediateBase().
stateControlDerivativeTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::control_state_matrix_t ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminal () override virtual
Computes final-cost derivative with respect to state and control.
Returns
derivative matrix (Jacobian)
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminalBase().
loadFromConfigFile()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile (const std::string & filename, bool verbose = false) override virtual
Loads cost function from config file.
Parameters
filename config file location
verbose verbosity flag which enables printout
Reimplemented from ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::addTerm(), CT_LOADABLE_TERMS, ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::finalCostAnalytical_, i, and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::intermediateCostAnalytical_.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::CostFunctionAnalytical().
Member Data Documentation
state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix<SCALAR, STATE_DIM, STATE_DIM> ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/costfunction/CostFunctionAnalytical.hpp
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/costfunction/CostFunctionAnalytical-impl.hpp