ct::optcon::example::OscillatorDms Class Reference
ct::optcon::example::OscillatorDms Class Reference
Public Member Functions
OscillatorDms ()
~OscillatorDms ()
void initialize (const DmsSettings settings)
void getSolution ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions< 2, 1 > OscDimensions
Constructor & Destructor Documentation
ct::optcon::example::OscillatorDms::OscillatorDms () inline
Examples:
oscDMSTestAllVariants.cpp.
ct::optcon::example::OscillatorDms::~OscillatorDms () inline
Examples:
oscDMSTestAllVariants.cpp.
Member Function Documentation
void ct::optcon::example::OscillatorDms::initialize (const DmsSettings settings) inline
Examples:
oscDMSTestAllVariants.cpp.
References ct::optcon::DmsSettings::print(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setGeneralConstraints(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setInitialState(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setTimeHorizon(), and ct::optcon::DmsSettings::T_.
Referenced by ct::optcon::example::TEST().
void ct::optcon::example::OscillatorDms::getSolution () inline
Examples:
oscDMSTestAllVariants.cpp.
References i, ct::optcon::DmsSettings::N_, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::uSolution_, and ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::xSolution_.
Referenced by ct::optcon::example::TEST().
Member Data Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions<2, 1> ct::optcon::example::OscillatorDms::OscDimensions
Examples:
oscDMSTestAllVariants.cpp.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/test/dms/oscillator/oscDMSTestAllVariants.cpp