ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference abstract
Constraint
A base function for linear constraint functions which have a first derivative.
#include <LinearConstraintContainer.h>
Public Types
typedef core::ControlVector< CONTROL_DIM, SCALAR > input_vector_t
typedef LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > * LinearConstraintContainer_Raw_Ptr_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > MatrixXs
Public Types inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
typedef core::ControlVector< CONTROL_DIM, SCALAR > input_vector_t
typedef ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR > * ConstraintBase_Raw_Ptr_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
Public Member Functions
LinearConstraintContainer ()
Default constructor.
LinearConstraintContainer (const LinearConstraintContainer &arg)
Copy constructor.
virtual ~LinearConstraintContainer ()
Destructor.
virtual LinearConstraintContainer_Raw_Ptr_t clone () const =0
virtual VectorXs jacobianStateSparseIntermediate ()=0
Evaluates the constraint jacobian wrt the state using sparse representation.
virtual MatrixXs jacobianStateIntermediate ()=0
Evaluates the constraint jacobian wrt the state.
virtual VectorXs jacobianStateSparseTerminal ()=0
Evaluates the constraint jacobian wrt the state using sparse representation.
virtual MatrixXs jacobianStateTerminal ()=0
Evaluates the constraint jacobian wrt the state.
virtual VectorXs jacobianInputSparseIntermediate ()=0
Evaluates the constraint jacobian wrt the control input using sparse representation.
virtual MatrixXs jacobianInputIntermediate ()=0
Evaluates the constraint jacobian wrt the control input.
virtual VectorXs jacobianInputSparseTerminal ()=0
Evaluates the constraint jacobian wrt the control input using sparse representation.
virtual MatrixXs jacobianInputTerminal ()=0
Evaluates the constraint jacobian wrt the control input.
virtual void sparsityPatternStateIntermediate (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols)=0
Returns the sparsity pattern for the jacobian wrt state.
virtual void sparsityPatternStateTerminal (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols)=0
Returns the sparsity pattern for the jacobian wrt state.
virtual void sparsityPatternInputIntermediate (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols)=0
Returns the sparsity pattern for the jacobian wrt control.
virtual void sparsityPatternInputTerminal (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols)=0
Returns the sparsity pattern for the jacobian wrt control.
virtual size_t getJacobianStateNonZeroCountIntermediate ()=0
Returns the number of non zero elements in the constraint jacobian wrt state.
virtual size_t getJacobianStateNonZeroCountTerminal ()=0
Returns the number of non zero elements in the constraint jacobian wrt state.
virtual size_t getJacobianInputNonZeroCountIntermediate ()=0
Returns the number of non zero elements in the constraint jacobian wrt input.
virtual size_t getJacobianInputNonZeroCountTerminal ()=0
Returns the number of non zero elements in the constraint jacobian wrt input.
size_t getJacNonZeroCount ()
Returns the number of non zeros in the constraint jacobian wrt to state and input.
void initialize ()
Initializes the constraint container.
virtual bool initializeIntermediate ()=0
Initializes the intermediate constraints.
virtual bool initializeTerminal ()=0
Initializes the terminal constraints.
bool isInitialized ()
Checks if the constraint container is initialized.
void printout ()
Print out sparsity patterns, jacobians, etc. Serves for quick visual inspection.
Public Member Functions inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
ConstraintContainerBase ()
Default constructor.
ConstraintContainerBase (const ConstraintContainerBase &arg)
copy constructor
virtual ~ConstraintContainerBase ()
Destructor.
virtual void setCurrentStateAndControl (const state_vector_t &x, const input_vector_t &u, const SCALAR t=SCALAR(0.0))
virtual VectorXs evaluateIntermediate ()=0
Evaluates the intermediate constraints.
virtual VectorXs evaluateTerminal ()=0
Evaluates the terminal constraints.
virtual size_t getIntermediateConstraintsCount ()=0
Retrieves the number of intermediate constraints.
virtual size_t getTerminalConstraintsCount ()=0
Retrieves the number of final constraints.
size_t getConstraintsCount ()
Retrieves the total number of constraints.
VectorXs getLowerBoundsIntermediate () const
Retrieves the lower constraint bound on the intermediate constraints.
VectorXs getLowerBoundsTerminal () const
Retrieves the lower constraint bound on the terminal constraints.
VectorXs getUpperBoundsIntermediate () const
Retrieves the upper constraint bound on the intermediate constraints.
VectorXs getUpperBoundsTerminal () const
Retrieves the upper constraint bound on the terminal constraints.
VectorXs getUpperBoundsViolationIntermediate ()
Retrieves the violation of the upper constraint bound on the intermediate constraints.
VectorXs getLowerBoundsViolationIntermediate ()
Retrieves the violation of the lower constraint bound on the intermediate constraints.
VectorXs getUpperBoundsViolationTerminal ()
Retrieves the violation of the upper constraint bound on the terminal constraints.
VectorXs getLowerBoundsViolationTerminal ()
Retrieves the violation of the lower constraint bound on the terminal constraints.
VectorXs getTotalBoundsViolationIntermediate ()
Retrieves the total violation of the constraints bounds on the intermediate constraints.
VectorXs getTotalBoundsViolationTerminal ()
Retrieves the total violation of the constraints bounds on the terminal constraints.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Public Attributes inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Protected Attributes
bool initializedIntermediate_
bool initializedTerminal_
Protected Attributes inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
state_vector_t x_
input_vector_t u_
SCALAR t_
VectorXs lowerBoundsIntermediate_
VectorXs lowerBoundsTerminal_
VectorXs upperBoundsIntermediate_
VectorXs upperBoundsTerminal_
Additional Inherited Members
Protected Member Functions inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
virtual void update ()=0
Gets called by the setCurrentStateAndControl method. Can be used to update container properties.
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
A base function for linear constraint functions which have a first derivative.
The LinearConstraintBase Class is the base class for defining the non-linear optimization constraints.
Template Parameters
STATE_DIM Dimension of the state vector
CONTROL_DIM Dimension of the control input vector
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::input_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef LinearConstraintContainer<STATE_DIM, CONTROL_DIM, SCALAR>* ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::LinearConstraintContainer_Raw_Ptr_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, Eigen::Dynamic> ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::LinearConstraintContainer ()
Default constructor.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::LinearConstraintContainer (const LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > & arg)
Copy constructor.
Parameters
[in] arg The object to be copied
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::~LinearConstraintContainer () virtual
Destructor.
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual LinearConstraintContainer_Raw_Ptr_t ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const pure virtual
Clones the linear constraint class
Returns
pointer to the clone
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
Implemented in ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual VectorXs ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseIntermediate () pure virtual
Evaluates the constraint jacobian wrt the state using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual MatrixXs ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateIntermediate () pure virtual
Evaluates the constraint jacobian wrt the state.
Returns
The jacobian wrt state
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual VectorXs ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseTerminal () pure virtual
Evaluates the constraint jacobian wrt the state using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual MatrixXs ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateTerminal () pure virtual
Evaluates the constraint jacobian wrt the state.
Returns
The jacobian wrt state
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual VectorXs ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseIntermediate () pure virtual
Evaluates the constraint jacobian wrt the control input using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual MatrixXs ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputIntermediate () pure virtual
Evaluates the constraint jacobian wrt the control input.
Returns
The jacobian wrt control
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual VectorXs ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseTerminal () pure virtual
Evaluates the constraint jacobian wrt the control input using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual MatrixXs ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputTerminal () pure virtual
Evaluates the constraint jacobian wrt the control input.
Returns
The jacobian wrt control
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateIntermediate (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) pure virtual
Returns the sparsity pattern for the jacobian wrt state.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateTerminal (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) pure virtual
Returns the sparsity pattern for the jacobian wrt state.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputIntermediate (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) pure virtual
Returns the sparsity pattern for the jacobian wrt control.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputTerminal (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) pure virtual
Returns the sparsity pattern for the jacobian wrt control.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual size_t ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountIntermediate () pure virtual
Returns the number of non zero elements in the constraint jacobian wrt state.
Returns
The number of the non zeros
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacNonZeroCount(), and ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual size_t ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountTerminal () pure virtual
Returns the number of non zero elements in the constraint jacobian wrt state.
Returns
The number of the non zeros
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacNonZeroCount(), and ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual size_t ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountIntermediate () pure virtual
Returns the number of non zero elements in the constraint jacobian wrt input.
Returns
The number of the non zeros
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacNonZeroCount(), and ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual size_t ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountTerminal () pure virtual
Returns the number of non zero elements in the constraint jacobian wrt input.
Returns
The number of the non zeros
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacNonZeroCount(), and ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacNonZeroCount ()
Returns the number of non zeros in the constraint jacobian wrt to state and input.
Returns
The number of the non zeros
References ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountIntermediate(), and ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountTerminal().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initialize ()
Initializes the constraint container.
References ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedIntermediate_, ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedTerminal_, ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializeIntermediate(), and ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual bool ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializeIntermediate () pure virtual
Initializes the intermediate constraints.
Returns
Returns true if the initialization was successful
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initialize().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual bool ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal () pure virtual
Initializes the terminal constraints.
Returns
Returns true if the initialization was successful
Implemented in ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >, ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::optcon::SwitchedLinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initialize().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > bool ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::isInitialized ()
Checks if the constraint container is initialized.
Returns
Returns true if initialized
References ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedIntermediate_, and ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedTerminal_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::printout ()
Print out sparsity patterns, jacobians, etc. Serves for quick visual inspection.
References ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountTerminal(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::getLowerBoundsIntermediate(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::getLowerBoundsTerminal(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::getUpperBoundsIntermediate(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::getUpperBoundsTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateIntermediate(), and ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateTerminal().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector<STATE_DIM, SCALAR> ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> bool ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedIntermediate_ protected
Referenced by ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateConstraint(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateConstraint(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountIntermediate(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountIntermediate(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initialize(), ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::isInitialized(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputIntermediate(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateIntermediate(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseIntermediate(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputIntermediate(), and ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateIntermediate().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> bool ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedTerminal_ protected
Referenced by ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::addTerminalConstraint(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::addTerminalConstraint(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountTerminal(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initialize(), ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::isInitialized(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseTerminal(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputTerminal(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseTerminal(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateTerminal(), ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputTerminal(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputTerminal(), ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateTerminal(), and ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateTerminal().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/constraint/LinearConstraintContainer.h
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/constraint/LinearConstraintContainer-impl.h