ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
DMS
This class sets up the DMS problem.
#include <DmsProblem.h>
Public Types
typedef DIMENSIONS::state_vector_t state_vector_t
typedef DIMENSIONS::control_vector_array_t control_vector_array_t
typedef DIMENSIONS::control_vector_t control_vector_t
typedef DIMENSIONS::state_vector_array_t state_vector_array_t
typedef DIMENSIONS::time_array_t time_array_t
typedef ContinuousOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR > OptConProblem_t
Public Types inherited from ct::optcon::tpl::Nlp< SCALAR >
using VectorXs = Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 >
using VectorXi = Eigen::Matrix< int, Eigen::Dynamic, 1 >
using MapVecXs = Eigen::Map< VectorXs >
using MapVecXi = Eigen::Map< VectorXi >
using MapConstVecXs = Eigen::Map< const VectorXs >
Public Member Functions
DmsProblem (DmsSettings settings, std::vector< typename OptConProblem_t::DynamicsPtr_t > systemPtrs, std::vector< typename OptConProblem_t::LinearPtr_t > linearPtrs, std::vector< typename OptConProblem_t::CostFunctionPtr_t > costPtrs, std::vector< typename OptConProblem_t::ConstraintPtr_t > boxConstraints, std::vector< typename OptConProblem_t::ConstraintPtr_t > generalConstraints, const state_vector_t &x0)
Custom constructor, sets up the objects needed for the Dms algorithm depending on the settings.
void generateAndCompileCode (std::vector< std::shared_ptr< core::ControlledSystem< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> systemPtrs, std::vector< std::shared_ptr< core::LinearSystem< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> linearPtrs, std::vector< std::shared_ptr< optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> costPtrs, std::vector< std::shared_ptr< optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> boxConstraints, std::vector< std::shared_ptr< optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> generalConstraints, const ct::core::StateVector< STATE_DIM, ct::core::ADCGScalar > &x0)
~DmsProblem () override=default
Destructor.
void updateProblem () override
{ This method gets called at each update of the Optimization variables. This can be used to distribute or rearrange the optimization variables appropriately }
void configure (const DmsSettings &settings)
Updates the settings.
const state_vector_array_t & getStateSolution ()
Retrieves the solution state trajectory at every shot.
const control_vector_array_t & getInputSolution ()
Retrieves the solution control trajectory at every shot.
const time_array_t & getTimeSolution ()
Retrieves the solution time trajectory at every shot.
const state_vector_array_t & getStateTrajectory ()
Retrieves a dense state solution trajectory.
const control_vector_array_t & getInputTrajectory ()
Retrieves a dense input solution trajectory.
const time_array_t & getTimeArray ()
Retrieves a dense time solution trajectory.
void setInitialGuess (const state_vector_array_t &x_init_guess, const control_vector_array_t &u_init_guess, const time_array_t &t_init_guess=time_array_t(0.0))
Sets the initial guess of the optimization.
const core::Time getTimeHorizon () const
Return the timehorizon of the problem.
void changeTimeHorizon (const SCALAR tf)
Updates the timehorizon.
void changeInitialState (const state_vector_t &x0)
Updates the initial state.
void printSolution ()
Prints the solution trajectories.
Public Member Functions inherited from ct::optcon::tpl::Nlp< SCALAR >
Nlp ()=default
Default constructor.
virtual ~Nlp ()=default
Destructor.
SCALAR evaluateCostFun ()
{ Evaluates the costfunction at the current nlp iteration }
void evaluateCostGradient (const size_t n, MapVecXs &grad)
{ Evaluates the gradient of the costfunction}
void evaluateConstraints (MapVecXs &values)
{ Evaluates the constraints }
void evaluateConstraintJacobian (const int nele_jac, MapVecXs &jac)
{ Evaluates the constraint jacobian }
void evaluateHessian (const int nele_hes, MapVecXs &hes, const SCALAR obj_fac, MapConstVecXs &lambda)
Evaluates the hessian of the lagrangian.
void getSparsityPatternJacobian (const int nele_jac, MapVecXi &iRow, MapVecXi &jCol) const
Gets the sparsity pattern.
void getSparsityPatternHessian (const int nele_hes, MapVecXi &iRow, MapVecXi &jCol) const
Gets the sparsity pattern of the Hessian of the Lagrangian.
size_t getConstraintsCount () const
Returns the number of constraints in the NLP.
size_t getNonZeroJacobianCount () const
Returns the number of the non zero elements of the constraint jacobian.
size_t getNonZeroHessianCount ()
Returns the number of non zeros in the Hessian.
void getConstraintBounds (MapVecXs &lowerBound, MapVecXs &upperBound, const size_t m) const
Reads the bounds of the constraints.
size_t getVarCount () const
Returns the number of Optimization optimization variables.
void getVariableBounds (MapVecXs &lowerBound, MapVecXs &upperBound, const size_t n) const
Reads the bounds on the Optimization optimization variables.
void extractOptimizationVars (const MapConstVecXs &x, bool isNew)
{Extracts the Optimization optimization variables from the nlp solvers between nlp iterations}
void getInitialGuess (const size_t n, MapVecXs &x) const
Gets the Optimization variables.
void getOptimizationMultState (const size_t n, MapVecXs &xMul, MapVecXi &xState) const
Gets the variable multiplier and the variable state, used in the NLP solver SNOPT. See the snopt documentation for further explanations.
void getConstraintsMultState (const size_t m, MapVecXs &zMul, MapVecXi &zState) const
Gets the constraint multiplier and state, used in the NLP solver SNOPT.
void getBoundMultipliers (size_t n, MapVecXs &zLow, MapVecXs &zUp) const
Gets the bound multipliers used in the NLP solver IPOPT.
void getLambdaVars (size_t m, MapVecXs &lambda) const
Gets the values of the constraint multipliers.
void extractIpoptSolution (const MapConstVecXs &x, const MapConstVecXs &zL, const MapConstVecXs &zU, const MapConstVecXs &lambda)
{ Extracts the solution values from IPOPT }
void extractSnoptSolution (const MapVecXs &x, const MapVecXs &xMul, const MapVecXi &xState, const MapVecXs &fMul, const MapVecXi &fState)
{ Extracts the solution values from SNOPT }
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions< STATE_DIM, CONTROL_DIM, SCALAR > DIMENSIONS
Additional Inherited Members
Protected Attributes inherited from ct::optcon::tpl::Nlp< SCALAR >
std::shared_ptr< DiscreteCostEvaluatorBase< SCALAR > > costEvaluator_
Ptr to cost evaluator, which approximates the cost evaluation for the discrete problem.
std::shared_ptr< OptVector< SCALAR > > optVariables_
Ptr to optimization variable container, which holds the optimization variables used in the NLP solvers.
std::shared_ptr< DiscreteConstraintContainerBase< SCALAR > > constraints_
Ptr to constraint container, which contains the discretized constraints for the problem.
std::shared_ptr< ct::core::DerivativesCppadJIT<-1, 1 > > costCodegen_
Ptr to code-generated cost (optional)
std::shared_ptr< ct::core::DerivativesCppadJIT<-1,-1 > > constraintsCodegen_
Ptr to code-generated constraints (optional)
Eigen::VectorXi iRowHessianCost_
helper containers for calculating the sparsity patterns
Eigen::VectorXi iRowHessianConstraints_
Eigen::VectorXi jColHessianCost_
Eigen::VectorXi jColHessianConstraints_
Eigen::VectorXi iRowHessian_
combined Hessian sparsity pattern gets stored here
Eigen::VectorXi jColHessian_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >
This class sets up the DMS problem.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_vector_t ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::control_vector_array_t ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_array_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::control_vector_t ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_vector_array_t ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_array_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::time_array_t ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::time_array_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef ContinuousOptConProblem<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::OptConProblem_t
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::DmsProblem (DmsSettings settings, std::vector< typename OptConProblem_t::DynamicsPtr_t > systemPtrs, std::vector< typename OptConProblem_t::LinearPtr_t > linearPtrs, std::vector< typename OptConProblem_t::CostFunctionPtr_t > costPtrs, std::vector< typename OptConProblem_t::ConstraintPtr_t > boxConstraints, std::vector< typename OptConProblem_t::ConstraintPtr_t > generalConstraints, const state_vector_t & x0) inline
Custom constructor, sets up the objects needed for the Dms algorithm depending on the settings.
Parameters
[in] settings The Dms settings
[in] systemPtrs The non linear systems
[in] linearPtrs The linearized systems
[in] costPtrs The cost function
[in] boxConstraints The box constraints
[in] generaConstraints The general constraints
[in] x0 The initial state
References ct::optcon::tpl::Nlp< SCALAR >::constraints_, ct::optcon::DmsSettings::costEvaluationType_, ct::optcon::tpl::Nlp< SCALAR >::costEvaluator_, ct::optcon::DmsSettings::dt_sim_, ct::optcon::DmsSettings::FULL, ct::optcon::tpl::Nlp< SCALAR >::getConstraintsCount(), ct::optcon::DmsSettings::N_, ct::optcon::DmsSettings::objectiveType_, ct::optcon::DmsSettings::OPTIMIZE_GRID, ct::optcon::tpl::Nlp< SCALAR >::optVariables_, ct::optcon::DmsSettings::parametersOk(), ct::optcon::DmsSettings::PIECEWISE_LINEAR, ct::optcon::DmsSettings::SIMPLE, ct::optcon::DmsSettings::splineType_, ct::optcon::DmsSettings::T_, x0, and ct::optcon::DmsSettings::ZERO_ORDER_HOLD.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::~DmsProblem () override default
Destructor.
Referenced by ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::generateAndCompileCode().
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::generateAndCompileCode (std::vector< std::shared_ptr< core::ControlledSystem< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> systemPtrs, std::vector< std::shared_ptr< core::LinearSystem< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> linearPtrs, std::vector< std::shared_ptr< optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> costPtrs, std::vector< std::shared_ptr< optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> boxConstraints, std::vector< std::shared_ptr< optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, ct::core::ADCGScalar >>> generalConstraints, const ct::core::StateVector< STATE_DIM, ct::core::ADCGScalar > & x0) inline
References ct::optcon::tpl::Nlp< SCALAR >::constraintsCodegen_, ct::optcon::tpl::Nlp< SCALAR >::costCodegen_, ct::optcon::DmsSettings::costEvaluationType_, ct::optcon::DmsSettings::cppadSettings_, ct::core::DerivativesCppadSettings::createJacobian_, ct::optcon::DmsSettings::dt_sim_, ct::optcon::DmsSettings::FULL, ct::optcon::tpl::Nlp< SCALAR >::getConstraintsCount(), ct::optcon::tpl::Nlp< SCALAR >::getVarCount(), ct::optcon::DmsSettings::N_, ct::optcon::DmsSettings::PIECEWISE_LINEAR, ct::optcon::ConstraintDiscretizer< STATE_DIM, CONTROL_DIM, SCALAR >::setBoxConstraints(), ct::optcon::DmsSettings::SIMPLE, ct::optcon::DmsSettings::solverSettings_, ct::optcon::DmsSettings::splineType_, ct::optcon::DmsSettings::T_, ct::optcon::NlpSolverSettings::useGeneratedConstraintJacobian_, ct::optcon::NlpSolverSettings::useGeneratedCostGradient_, ct::optcon::DmsSettings::ZERO_ORDER_HOLD, and ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::~DmsProblem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::updateProblem () inline override virtual
{ This method gets called at each update of the Optimization variables. This can be used to distribute or rearrange the optimization variables appropriately }
Implements ct::optcon::tpl::Nlp< SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::configure (const DmsSettings & settings) inline
Updates the settings.
Parameters
[in] settings New dms settings
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_vector_array_t& ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::getStateSolution () inline
Retrieves the solution state trajectory at every shot.
Returns
The state solution trajectory
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const control_vector_array_t& ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::getInputSolution () inline
Retrieves the solution control trajectory at every shot.
Returns
The control solution trajectory
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const time_array_t& ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::getTimeSolution () inline
Retrieves the solution time trajectory at every shot.
Returns
The time solution trajectory
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_vector_array_t& ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::getStateTrajectory () inline
Retrieves a dense state solution trajectory.
Returns
The dense state solution trajectory
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const control_vector_array_t& ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::getInputTrajectory () inline
Retrieves a dense input solution trajectory.
Returns
The dense control solution trajectory
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const time_array_t& ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::getTimeArray () inline
Retrieves a dense time solution trajectory.
Returns
The dense time solution trajectory
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setInitialGuess (const state_vector_array_t & x_init_guess, const control_vector_array_t & u_init_guess, const time_array_t & t_init_guess = time_array_t(0.0)) inline
Sets the initial guess of the optimization.
Parameters
[in] x_init_guess The state trajectory initial guess
[in] u_init_guess The control trajectory initial guess
[in] t_init_guess The time trajectory initial guess
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const core::Time ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::getTimeHorizon () const inline
Return the timehorizon of the problem.
Returns
The time horizon
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::changeTimeHorizon (const SCALAR tf) inline
Updates the timehorizon.
Parameters
[in] tf The new time horizon
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::changeInitialState (const state_vector_t & x0) inline
Updates the initial state.
Parameters
[in] x0 The new inital state
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::printSolution () inline
Prints the solution trajectories.
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::DIMENSIONS
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/dms/dms_core/DmsProblem.h