ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
DMS
This class performs the state and the sensitivity integration on a shot.
#include <ShotContainer.h>
Public Types
typedef DIMENSIONS::state_vector_t state_vector_t
typedef DIMENSIONS::control_vector_t control_vector_t
typedef DIMENSIONS::state_vector_array_t state_vector_array_t
typedef DIMENSIONS::control_vector_array_t control_vector_array_t
typedef DIMENSIONS::time_array_t time_array_t
typedef DIMENSIONS::state_matrix_t state_matrix_t
typedef DIMENSIONS::state_control_matrix_t state_control_matrix_t
typedef DIMENSIONS::state_matrix_array_t state_matrix_array_t
typedef DIMENSIONS::state_control_matrix_array_t state_control_matrix_array_t
Public Member Functions
ShotContainer ()=delete
ShotContainer (std::shared_ptr< ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >> controlledSystem, std::shared_ptr< ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> linearSystem, std::shared_ptr< ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >> costFct, std::shared_ptr< OptVectorDms< STATE_DIM, CONTROL_DIM, SCALAR >> w, std::shared_ptr< SplinerBase< control_vector_t, SCALAR >> controlSpliner, std::shared_ptr< tpl::TimeGrid< SCALAR >> timeGrid, size_t shotNr, DmsSettings settings, size_t nIntegrationSteps)
Custom constructor.
void integrateShot ()
Performs the state integration between the shots.
void integrateCost ()
void integrateSensitivities ()
Performs the state and the sensitivity integration between the shots.
void integrateCostSensitivities ()
void reset ()
const state_vector_t & getStateIntegrated ()
Returns the integrated state.
const SCALAR getIntegrationTimeFinal ()
Returns the end time of the integration.
const state_matrix_t & getdXdSiIntegrated ()
Returns the integrated ODE sensitivity with respect to the discretized state s_i.
const state_control_matrix_t & getdXdQiIntegrated ()
Returns the integrated ODE sensitivity with respect to the discretized inputs q_i.
const state_control_matrix_t & getdXdQip1Integrated ()
Returns the integrated ODE sensitivity with respect to the discretized inputs q_{i+1}.
const state_vector_array_t & getXHistory () const
Returns the integrated ODE sensitivity with respect to the time segments h_i.
const control_vector_array_t & getUHistory ()
Returns the control input trajectory used during the state integration.
const time_array_t & getTHistory () const
Returns the time trajectory used during the integration.
const SCALAR getCostIntegrated () const
Gets the cost integrated.
const state_vector_t & getdLdSiIntegrated () const
Returns the cost gradient with respect to s_i integrated over the shot.
const control_vector_t & getdLdQiIntegrated () const
Returns the cost gradient with respect to q_i integrated over the shot.
const control_vector_t & getdLdQip1Integrated () const
Returns to cost gradient with respect to q_{i+1} integrated over the shot.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions< STATE_DIM, CONTROL_DIM, SCALAR > DIMENSIONS
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >
This class performs the state and the sensitivity integration on a shot.
Template Parameters
STATE_DIM The state dimension
CONTROL_DIM The control dimension
Member Typedef Documentation
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_vector_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::control_vector_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
state_vector_array_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_vector_array_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_array_t
control_vector_array_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::control_vector_array_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_array_t
time_array_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::time_array_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::time_array_t
state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_matrix_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
state_control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_control_matrix_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::state_control_matrix_t
state_matrix_array_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_matrix_array_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_array_t
state_control_matrix_array_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DIMENSIONS::state_control_matrix_array_t ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::state_control_matrix_array_t
Constructor & Destructor Documentation
ShotContainer() [1/2]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::ShotContainer () delete
ShotContainer() [2/2]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::ShotContainer (std::shared_ptr< ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >> controlledSystem, std::shared_ptr< ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> linearSystem, std::shared_ptr< ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >> costFct, std::shared_ptr< OptVectorDms< STATE_DIM, CONTROL_DIM, SCALAR >> w, std::shared_ptr< SplinerBase< control_vector_t, SCALAR >> controlSpliner, std::shared_ptr< tpl::TimeGrid< SCALAR >> timeGrid, size_t shotNr, DmsSettings settings, size_t nIntegrationSteps) inline
Custom constructor.
Parameters
[in] controlledSystem The nonlinear system
[in] linearSystem The linearized system
[in] costFct The costfunction
[in] w The optimization vector
[in] controlSpliner The control input spliner
[in] timeGrid The timegrid
[in] shotNr The shot number
[in] settings The dms settings
References ct::optcon::DmsSettings::costEvaluationType_, ct::optcon::DmsSettings::EULER, ct::core::EULERCT, ct::optcon::DmsSettings::FULL, ct::optcon::DmsSettings::integrationType_, ct::optcon::DmsSettings::N_, ct::optcon::DmsSettings::RK4, ct::core::RK4CT, and ct::optcon::DmsSettings::RK5.
Member Function Documentation
integrateShot()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateShot () inline
Performs the state integration between the shots.
References ct::optcon::DmsSettings::dt_sim_.
Referenced by ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateCost(), and ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateSensitivities().
integrateCost()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateCost () inline
References ct::optcon::DmsSettings::dt_sim_, and ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateShot().
integrateSensitivities()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateSensitivities () inline
Performs the state and the sensitivity integration between the shots.
References ct::optcon::DmsSettings::dt_sim_, ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateShot(), ct::optcon::DmsSettings::PIECEWISE_LINEAR, and ct::optcon::DmsSettings::splineType_.
Referenced by ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateCostSensitivities().
integrateCostSensitivities()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateCostSensitivities () inline
References ct::optcon::DmsSettings::dt_sim_, ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::integrateSensitivities(), ct::optcon::DmsSettings::PIECEWISE_LINEAR, and ct::optcon::DmsSettings::splineType_.
reset()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::reset () inline
getStateIntegrated()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_vector_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getStateIntegrated () inline
Returns the integrated state.
Returns
The integrated state
getIntegrationTimeFinal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const SCALAR ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getIntegrationTimeFinal () inline
Returns the end time of the integration.
Returns
The end time of the integration.
getdXdSiIntegrated()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_matrix_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getdXdSiIntegrated () inline
Returns the integrated ODE sensitivity with respect to the discretized state s_i.
Returns
The integrated sensitivity
getdXdQiIntegrated()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_control_matrix_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getdXdQiIntegrated () inline
Returns the integrated ODE sensitivity with respect to the discretized inputs q_i.
Returns
The integrated sensitivity
getdXdQip1Integrated()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_control_matrix_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getdXdQip1Integrated () inline
Returns the integrated ODE sensitivity with respect to the discretized inputs q_{i+1}.
Returns
The integrated sensitivity
getXHistory()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_vector_array_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getXHistory () const inline
Returns the integrated ODE sensitivity with respect to the time segments h_i.
Returns
The integrated sensitivity Gets the full integrated state trajectory.
The integrated state trajectory
getUHistory()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const control_vector_array_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getUHistory () inline
Returns the control input trajectory used during the state integration.
Returns
The control trajectory
References t.
getTHistory()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const time_array_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getTHistory () const inline
Returns the time trajectory used during the integration.
Returns
The time trajectory
getCostIntegrated()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const SCALAR ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getCostIntegrated () const inline
Gets the cost integrated.
Returns
The integrated cost.
getdLdSiIntegrated()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_vector_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getdLdSiIntegrated () const inline
Returns the cost gradient with respect to s_i integrated over the shot.
Returns
The cost gradient
getdLdQiIntegrated()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const control_vector_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getdLdQiIntegrated () const inline
Returns the cost gradient with respect to q_i integrated over the shot.
Returns
The cost gradient
getdLdQip1Integrated()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const control_vector_t& ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getdLdQip1Integrated () const inline
Returns to cost gradient with respect to q_{i+1} integrated over the shot.
Returns
The cost gradient
Member Data Documentation
DIMENSIONS
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DmsDimensions<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::DIMENSIONS
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/dms/dms_core/ShotContainer.h