ct::optcon::ZeroOrderHoldSpliner< T, SCALAR > Class Template Reference
ct::optcon::ZeroOrderHoldSpliner< T, SCALAR > Class Template Reference
DMS
The spline implementation for the zero order hold spliner.
#include <ZeroOrderHoldSpliner.h>
Public Types
typedef Eigen::Matrix< SCALAR, T::DIM, T::DIM > matrix_t
typedef std::vector< vector_t, Eigen::aligned_allocator< vector_t > > vector_array_t
Public Types inherited from ct::optcon::SplinerBase< T, SCALAR >
typedef T vector_t
typedef Eigen::Matrix< SCALAR, T::DIM, T::DIM > matrix_t
typedef std::vector< vector_t, Eigen::aligned_allocator< vector_t > > vector_array_t
Public Member Functions
ZeroOrderHoldSpliner ()=delete
ZeroOrderHoldSpliner (std::shared_ptr< tpl::TimeGrid< SCALAR >> grid)
Custom constructor.
~ZeroOrderHoldSpliner () override=default
void computeSpline (const vector_array_t &points) override
Updates the vector on the shots.
vector_t evalSpline (const SCALAR time, const size_t shotIdx) override
Depending on the spline type, this method evaluates the control input between the shots.
vector_t splineDerivative_t (const SCALAR time, const size_t shotIdx) const override
Returns the spline derivatives with respect to time.
vector_t splineDerivative_h_i (const SCALAR time, const size_t shotIdx) const override
Returns the spline derivatives with respect to the time segment between the shots.
matrix_t splineDerivative_q_i (const SCALAR time, const size_t shotIdx) const override
Return the spline derivative with respect to the control input at shot i.
matrix_t splineDerivative_q_iplus1 (const SCALAR time, const size_t shotIdx) const override
Returns the spline derivative with respect to the control input at shot i+1.
Public Member Functions inherited from ct::optcon::SplinerBase< T, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW SplinerBase ()=default
Default constructor.
virtual ~SplinerBase ()=default
Destructor.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef T vector_t
Detailed Description
template<class T, typename SCALAR = double>
class ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >
The spline implementation for the zero order hold spliner.
Template Parameters
T The vector type to be splined
Member Typedef Documentation
template<class T , typename SCALAR = double> typedef Eigen::Matrix<SCALAR, T::DIM, T::DIM> ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::matrix_t
template<class T , typename SCALAR = double> typedef std::vector<vector_t, Eigen::aligned_allocator<vector_t> > ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::vector_array_t
Constructor & Destructor Documentation
template<class T , typename SCALAR = double> ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::ZeroOrderHoldSpliner () delete
template<class T , typename SCALAR = double> ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::ZeroOrderHoldSpliner (std::shared_ptr< tpl::TimeGrid< SCALAR >> grid) inline
Custom constructor.
Parameters
[in] grid The DMS timegrid
References grid(), and ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::~ZeroOrderHoldSpliner().
template<class T , typename SCALAR = double> ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::~ZeroOrderHoldSpliner () override default
Referenced by ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::ZeroOrderHoldSpliner().
Member Function Documentation
template<class T , typename SCALAR = double> void ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::computeSpline (const vector_array_t & points) inline override virtual
Updates the vector on the shots.
Parameters
[in] points Updated vector array
Implements ct::optcon::SplinerBase< T, SCALAR >.
template<class T , typename SCALAR = double> vector_t ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::evalSpline (const SCALAR time, const size_t shotIdx) inline override virtual
Depending on the spline type, this method evaluates the control input between the shots.
Parameters
[in] time The evaluation time
[in] shotIdx The shot number
Returns
The splined vector
Implements ct::optcon::SplinerBase< T, SCALAR >.
template<class T , typename SCALAR = double> vector_t ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::splineDerivative_t (const SCALAR time, const size_t shotIdx) const inline override virtual
Returns the spline derivatives with respect to time.
Parameters
[in] time The evaluation time
[in] shotIdx The shot number
Returns
The time derivative
Implements ct::optcon::SplinerBase< T, SCALAR >.
template<class T , typename SCALAR = double> vector_t ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::splineDerivative_h_i (const SCALAR time, const size_t shotIdx) const inline override virtual
Returns the spline derivatives with respect to the time segment between the shots.
Parameters
[in] time The evaluation time
[in] shotIdx The shot number
Returns
The resulting derivative
Implements ct::optcon::SplinerBase< T, SCALAR >.
template<class T , typename SCALAR = double> matrix_t ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::splineDerivative_q_i (const SCALAR time, const size_t shotIdx) const inline override virtual
Return the spline derivative with respect to the control input at shot i.
Parameters
[in] time The evaluation time
[in] shotIdx The shot number
Returns
The resulting derivative
Implements ct::optcon::SplinerBase< T, SCALAR >.
template<class T , typename SCALAR = double> matrix_t ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::splineDerivative_q_iplus1 (const SCALAR time, const size_t shotIdx) const inline override virtual
Returns the spline derivative with respect to the control input at shot i+1.
Parameters
[in] time The evaluation time
[in] shotIdx The shot number
Returns
The resulting derivative
Implements ct::optcon::SplinerBase< T, SCALAR >.
Member Data Documentation
template<class T , typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef T ct::optcon::ZeroOrderHoldSpliner< T, SCALAR >::vector_t
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/dms/dms_core/spline/ZeroOrderHold/ZeroOrderHoldSpliner.h