ct::optcon::StateFeedbackPolicyHandler< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::StateFeedbackPolicyHandler< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
the default policy handler for iLQR
#include <StateFeedbackPolicyHandler.h>
Public Member Functions
StateFeedbackPolicyHandler (const SCALAR &dt)
virtual ~StateFeedbackPolicyHandler ()
virtual void designWarmStartingPolicy (const SCALAR &delay, const SCALAR &newTimeHorizon, StateFeedbackController_t &policy) override
virtual void truncateSolutionFront (const SCALAR &delay, StateFeedbackController_t &policy, SCALAR &effectivelyTruncated) override
Public Member Functions inherited from ct::optcon::PolicyHandler< core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >, STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW PolicyHandler ()
virtual ~PolicyHandler ()
virtual void designWarmStartingPolicy (const SCALAR &delay, const SCALAR &TimeHorizon, core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR > &policy)
design a warm-starting policy for the optimal control problem solver
virtual void truncateSolutionFront (const SCALAR &delay, core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR > &policy, SCALAR &effectivelyTruncated)
a method required for additional post-truncation.
void setPolicy (const core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR > &newPolicy)
set new policy to policy handler
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR > StateFeedbackController_t
Additional Inherited Members
Protected Attributes inherited from ct::optcon::PolicyHandler< core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >, STATE_DIM, CONTROL_DIM, SCALAR >
core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR > initialPolicy_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR>
class ct::optcon::StateFeedbackPolicyHandler< STATE_DIM, CONTROL_DIM, SCALAR >
the default policy handler for iLQR
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::StateFeedbackPolicyHandler< STATE_DIM, CONTROL_DIM, SCALAR >::StateFeedbackPolicyHandler (const SCALAR & dt)
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::StateFeedbackPolicyHandler< STATE_DIM, CONTROL_DIM, SCALAR >::~StateFeedbackPolicyHandler () virtual
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::StateFeedbackPolicyHandler< STATE_DIM, CONTROL_DIM, SCALAR >::designWarmStartingPolicy (const SCALAR & delay, const SCALAR & newTimeHorizon, StateFeedbackController_t & policy) override virtual
References ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::back(), ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::eraseFront(), ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::getIndexFromTime(), i, ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::pop_back(), ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::push_back(), and ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::size().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::StateFeedbackPolicyHandler< STATE_DIM, CONTROL_DIM, SCALAR >::truncateSolutionFront (const SCALAR & delay, StateFeedbackController_t & policy, SCALAR & effectivelyTruncated) override virtual
required for additional post-truncation.
Parameters
delay the delay which is to be truncated away
policy the resulting, truncated policy
effectivelyTruncated the time which was effectively truncated away (can be different from the input in discrete-time case, for example)
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateFeedbackController<STATE_DIM, CONTROL_DIM, SCALAR> ct::optcon::StateFeedbackPolicyHandler< STATE_DIM, CONTROL_DIM, SCALAR >::StateFeedbackController_t
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/mpc/policyhandler/default/StateFeedbackPolicyHandler.h
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/mpc/policyhandler/default/StateFeedbackPolicyHandler-impl.h