ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS > Class Template Reference
ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS > Class Template Reference
#include <iLQR.hpp>
Public Types
typedef NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS > Base
typedef Base::Policy_t Policy_t
typedef Base::Settings_t Settings_t
typedef Base::Backend_t Backend_t
typedef SCALAR Scalar_t
Public Types inherited from ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >
typedef NLOCBackendBase< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS > Backend_t
typedef NLOptConSettings Settings_t
typedef SCALAR Scalar_t
Public Member Functions
iLQR (std::shared_ptr< Backend_t > &backend_, const Settings_t &settings)
constructor
virtual ~iLQR ()
destructor
virtual void configure (const Settings_t &settings) override
configure the solver
virtual void setInitialGuess (const Policy_t &initialGuess) override
set an initial guess
virtual bool runIteration () override
runIteration combines prepareIteration and finishIteration
virtual void prepareIteration () override
virtual bool finishIteration () override
virtual void prepareMPCIteration () override
virtual bool finishMPCIteration () override
Public Member Functions inherited from ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >
NLOCAlgorithm (const std::shared_ptr< Backend_t > &backend)
virtual ~NLOCAlgorithm ()
virtual void setInitialGuess (const Policy_t &initialGuess)=0
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t STATE_D = STATE_DIM
static const size_t CONTROL_D = CONTROL_DIM
Additional Inherited Members
Public Attributes inherited from ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR > Policy_t
Protected Attributes inherited from ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >
std::shared_ptr< Backend_t > backend_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR = double, bool CONTINUOUS = true>
class ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >
Examples:
NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_MPC.cpp, and switched_continuous_optcon.cpp.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR = double, bool CONTINUOUS = true> typedef NLOCAlgorithm<STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS> ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Base
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR = double, bool CONTINUOUS = true> typedef Base::Policy_t ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Policy_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR = double, bool CONTINUOUS = true> typedef Base::Settings_t ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Settings_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR = double, bool CONTINUOUS = true> typedef Base::Backend_t ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Backend_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR = double, bool CONTINUOUS = true> typedef SCALAR ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::Scalar_t
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::iLQR (std::shared_ptr< Backend_t > & backend_, const Settings_t & settings)
constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::~iLQR () virtual
destructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure (const Settings_t & settings) override virtual
configure the solver
Implements ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::backend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess (const Policy_t & initialGuess) override virtual
set an initial guess
References ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::backend_.
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> bool ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration () override virtual
runIteration combines prepareIteration and finishIteration
For iLQR the separation between prepareIteration and finishIteration would actually not be necessary
Returns
Implements ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishIteration(), and ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareIteration().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareIteration () override virtual
for iLQR, as it is a purely sequential approach, we cannot prepare anything prior to solving,
Implements ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::backend_.
Referenced by ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareMPCIteration(), and ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> bool ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishIteration () override virtual
for iLQR, finishIteration contains the whole main iLQR iteration.
Returns
Implements ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::backend_.
Referenced by ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishMPCIteration(), and ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> void ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareMPCIteration () override virtual
for iLQR, as it is a purely sequential approach, we cannot prepare anything prior to solving,
Implements ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::prepareIteration().
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR , bool CONTINUOUS> bool ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishMPCIteration () override virtual
for iLQR, finishIteration contains the whole main iLQR iteration.
Returns
Todo:
: in MPC always returning true. Unclear how user wants to deal with varying costs, etc.
Implements ct::optcon::NLOCAlgorithm< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >.
References ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::finishIteration().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR = double, bool CONTINUOUS = true> EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::STATE_D = STATE_DIM static
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM, size_t V_DIM, typename SCALAR = double, bool CONTINUOUS = true> const size_t ct::optcon::iLQR< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::CONTROL_D = CONTROL_DIM static
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/nloc/algorithms/ilqr/iLQR.hpp
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/nloc/algorithms/ilqr/iLQR-impl.hpp