ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
This class can integrate a controlled system and a costfunction. Furthermore, it provides first order derivatives with respect to initial state and control.
#include <SensitivityIntegratorCT.h>
Public Types
typedef ct::core::ControlVector< CONTROL_DIM, SCALAR > control_vector
typedef Eigen::Matrix< SCALAR, STATE_DIM, STATE_DIM > state_matrix
typedef Eigen::Matrix< SCALAR, CONTROL_DIM, CONTROL_DIM > control_matrix
typedef Eigen::Matrix< SCALAR, STATE_DIM, CONTROL_DIM > state_control_matrix
Public Member Functions
SensitivityIntegratorCT (const std::shared_ptr< ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >> &system, const ct::core::IntegrationType stepperType=ct::core::IntegrationType::EULERCT)
Constructor.
~SensitivityIntegratorCT ()=default
Destroys the object.
void initializeDerived (const ct::core::IntegrationType stepperType)
Initializes the steppers.
void setLinearSystem (const std::shared_ptr< ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> &linearSystem)
Prepares the integrator to provide first order sensitivity generation by setting a linearsystem, enabling state caching and settings up the function objects.
void setControlledSystem (const std::shared_ptr< ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >> &controlledSystem)
Changes the controlledsystem to be integrated.
void setCostFunction (const std::shared_ptr< CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >> costFun)
Prepares the integrator to provide cost integration and first order cost derivatives. This is done by enabling sensitivity caching and setting up the function objects.
void integrate (state_vector &state, const SCALAR startTime, const size_t numSteps, const SCALAR dt, ct::core::StateVectorArray< STATE_DIM, SCALAR > &stateTrajectory, ct::core::tpl::TimeArray< SCALAR > &timeTrajectory)
Integrates the system starting from state and startTime for numSteps integration steps. Returns the full state and time trajectories.
void integrate (state_vector &state, const SCALAR startTime, const size_t numSteps, const SCALAR dt)
Integrates the system starting from state and startTime for numSteps integration steps. Returns only the final state and time.
void integrateSensitivityDX0 (state_matrix &dX0, const SCALAR startTime, const size_t numSteps, const SCALAR dt)
Integrates the sensitivity ODE of the integrator with respec to the initial state x0.
void integrateSensitivityDU0 (state_control_matrix &dU0, const SCALAR startTime, const size_t numSteps, const SCALAR dt)
Integrates the sensitivity ODE of the integrator with respec to the initial control input u0.
void integrateSensitivityDUf (state_control_matrix &dUf, const SCALAR startTime, const size_t numSteps, const SCALAR dt)
Integrates the sensitivity ODE of the integrator with respec to the final control input uf.
void integrateCost (SCALAR &cost, const SCALAR startTime, const size_t numSteps, const SCALAR dt)
Integrates the costfunction using the states and controls from the costintegration.
void integrateCostSensitivityDX0 (state_vector &dX0, const SCALAR startTime, const size_t numSteps, const SCALAR dt)
Integrates the sensitivity of the cost with respect to the initial state x0.
void integrateCostSensitivityDU0 (control_vector &dU0, const SCALAR startTime, const size_t numSteps, const SCALAR dt)
Integrates the sensitivity of the cost with respect to the initial control input u0.
void integrateCostSensitivityDUf (control_vector &dUf, const SCALAR &startTime, const size_t numSteps, const SCALAR dt)
Integrates the sensitivity of the cost with respect to the final control input uF.
void linearize ()
Linearizes the system around the rollout from the state interation.
void clearStates ()
Clears the cached states, controls and times.
void clearSensitivities ()
Clears the cached sensitivities.
void clearLinearization ()
Clears the linearized matrices.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::StateVector< STATE_DIM, SCALAR > state_vector
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >
This class can integrate a controlled system and a costfunction. Furthermore, it provides first order derivatives with respect to initial state and control.
Template Parameters
STATE_DIM The state dimension
CONTROL_DIM The control dimension
SCALAR The scalar type
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef ct::core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, STATE_DIM, STATE_DIM> ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, CONTROL_DIM, CONTROL_DIM> ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::control_matrix
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, STATE_DIM, CONTROL_DIM> ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::state_control_matrix
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::SensitivityIntegratorCT (const std::shared_ptr< ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >> & system, const ct::core::IntegrationType stepperType = ct::core::IntegrationType::EULERCT) inline
Constructor.
Parameters
[in] system The controlled system
[in] stepperType The integration stepper type
References ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::initializeDerived(), ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::setControlledSystem(), and ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::~SensitivityIntegratorCT().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::~SensitivityIntegratorCT () default
Destroys the object.
Referenced by ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::SensitivityIntegratorCT().
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::initializeDerived (const ct::core::IntegrationType stepperType) inline
Initializes the steppers.
Parameters
[in] stepperType The desired integration stepper type
Referenced by ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::SensitivityIntegratorCT().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::setLinearSystem (const std::shared_ptr< ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> & linearSystem) inline
Prepares the integrator to provide first order sensitivity generation by setting a linearsystem, enabling state caching and settings up the function objects.
Parameters
[in] linearSystem The linearized system
References t.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::setControlledSystem (const std::shared_ptr< ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >> & controlledSystem) inline
Changes the controlledsystem to be integrated.
Parameters
[in] controlledSystem The new controlled system
References t, and x.
Referenced by ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::SensitivityIntegratorCT().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::setCostFunction (const std::shared_ptr< CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >> costFun) inline
Prepares the integrator to provide cost integration and first order cost derivatives. This is done by enabling sensitivity caching and setting up the function objects.
Parameters
[in] costFun The new costfunction
References t.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrate (state_vector & state, const SCALAR startTime, const size_t numSteps, const SCALAR dt, ct::core::StateVectorArray< STATE_DIM, SCALAR > & stateTrajectory, ct::core::tpl::TimeArray< SCALAR > & timeTrajectory) inline
Integrates the system starting from state and startTime for numSteps integration steps. Returns the full state and time trajectories.
Parameters
[in,out] state The initial state for integration
[in] startTime The start time
[in] numSteps The number steps
[in] dt The integration timestep
[out] stateTrajectory The output state trajectory
[out] timeTrajectory The output time trajectory
References ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::clearLinearization(), ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::clearStates(), dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrate (state_vector & state, const SCALAR startTime, const size_t numSteps, const SCALAR dt) inline
Integrates the system starting from state and startTime for numSteps integration steps. Returns only the final state and time.
Parameters
References ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::clearLinearization(), ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::clearStates(), dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrateSensitivityDX0 (state_matrix & dX0, const SCALAR startTime, const size_t numSteps, const SCALAR dt) inline
Integrates the sensitivity ODE of the integrator with respec to the initial state x0.
Parameters
[in,out] dX0 The sensitivity matrix wrt x0
[in] startTime The start time
[in] numSteps The number of integration steps
[in] dt The integration timestep
References dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrateSensitivityDU0 (state_control_matrix & dU0, const SCALAR startTime, const size_t numSteps, const SCALAR dt) inline
Integrates the sensitivity ODE of the integrator with respec to the initial control input u0.
Parameters
[in,out] dU0 The sensitivity matrix wrt u0
[in] startTime The start time
[in] numSteps The number of integration steps
[in] dt The integration timestep
References dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrateSensitivityDUf (state_control_matrix & dUf, const SCALAR startTime, const size_t numSteps, const SCALAR dt) inline
Integrates the sensitivity ODE of the integrator with respec to the final control input uf.
Parameters
[in,out] dUF The sensitivity matrix wrt uF
[in] startTime The start time
[in] numSteps The number of integration steps
[in] dt The integration timestep
References dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrateCost (SCALAR & cost, const SCALAR startTime, const size_t numSteps, const SCALAR dt) inline
Integrates the costfunction using the states and controls from the costintegration.
Parameters
[in,out] cost The initial cost
[in] startTime The start time
[in] numSteps The number of integration steps
[in] dt The integration time step
References dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrateCostSensitivityDX0 (state_vector & dX0, const SCALAR startTime, const size_t numSteps, const SCALAR dt) inline
Integrates the sensitivity of the cost with respect to the initial state x0.
Parameters
[in,out] dX0 The initial cost sensitivity vector
[in] startTime The start time
[in] numSteps The number of integration steps
[in] dt The integration time step
References dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrateCostSensitivityDU0 (control_vector & dU0, const SCALAR startTime, const size_t numSteps, const SCALAR dt) inline
Integrates the sensitivity of the cost with respect to the initial control input u0.
Parameters
[in,out] dU0 The initial cost sensitivity vector
[in] startTime The start time
[in] numSteps The number of integration steps
[in] dt The integration time step
References dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrateCostSensitivityDUf (control_vector & dUf, const SCALAR & startTime, const size_t numSteps, const SCALAR dt) inline
Integrates the sensitivity of the cost with respect to the final control input uF.
Parameters
[in,out] dUf The initial cost sensitivity vector
[in] startTime The start time
[in] numSteps The number of integration steps
[in] dt The integration time step
References dt, and i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::linearize () inline
Linearizes the system around the rollout from the state interation.
References i.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::clearStates () inline
Clears the cached states, controls and times.
Referenced by ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrate().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::clearSensitivities () inline
Clears the cached sensitivities.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::clearLinearization () inline
Clears the linearized matrices.
Referenced by ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::integrate().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::StateVector<STATE_DIM, SCALAR> ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/dms/dms_core/SensitivityIntegratorCT.h