ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
Constraint
Contains all the constraints using analytically calculated jacobians.
#include <ConstraintContainerAnalytical.h>
Public Types
typedef core::ControlVector< CONTROL_DIM, SCALAR > input_vector_t
typedef ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > * ConstraintContainerAnalytical_Raw_Ptr_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > MatrixXs
Public Types inherited from ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
typedef core::ControlVector< CONTROL_DIM, SCALAR > input_vector_t
typedef LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR > * LinearConstraintContainer_Raw_Ptr_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, Eigen::Dynamic > MatrixXs
Public Types inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
typedef core::ControlVector< CONTROL_DIM, SCALAR > input_vector_t
typedef ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR > * ConstraintBase_Raw_Ptr_t
typedef Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 > VectorXs
Public Member Functions
ConstraintContainerAnalytical ()
ConstraintContainerAnalytical (const state_vector_t &x, const input_vector_t &u, const SCALAR &t=0.0)
Constructor using state, control and time.
ConstraintContainerAnalytical (const ConstraintContainerAnalytical &arg)
Copy constructor.
virtual ConstraintContainerAnalytical_Raw_Ptr_t clone () const override
Deep-cloning of Constraint.
virtual ~ConstraintContainerAnalytical ()
Destructor.
void addIntermediateConstraint (std::shared_ptr< ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >> constraint, bool verbose)
Adds an intermedaite constraint.
void addTerminalConstraint (std::shared_ptr< ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >> constraint, bool verbose)
Adds a terminal constraint.
virtual VectorXs evaluateIntermediate () override
Evaluates the intermediate constraints.
virtual VectorXs evaluateTerminal () override
Evaluates the terminal constraints.
virtual size_t getIntermediateConstraintsCount () override
Retrieves the number of intermediate constraints.
virtual size_t getTerminalConstraintsCount () override
Retrieves the number of final constraints.
virtual VectorXs jacobianStateSparseIntermediate () override
Evaluates the constraint jacobian wrt the state using sparse representation.
virtual MatrixXs jacobianStateIntermediate () override
Evaluates the constraint jacobian wrt the state.
virtual VectorXs jacobianStateSparseTerminal () override
Evaluates the constraint jacobian wrt the state using sparse representation.
virtual MatrixXs jacobianStateTerminal () override
Evaluates the constraint jacobian wrt the state.
virtual VectorXs jacobianInputSparseIntermediate () override
Evaluates the constraint jacobian wrt the control input using sparse representation.
virtual MatrixXs jacobianInputIntermediate () override
Evaluates the constraint jacobian wrt the control input.
virtual VectorXs jacobianInputSparseTerminal () override
Evaluates the constraint jacobian wrt the control input using sparse representation.
virtual MatrixXs jacobianInputTerminal () override
Evaluates the constraint jacobian wrt the control input.
virtual void sparsityPatternStateIntermediate (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols) override
Returns the sparsity pattern for the jacobian wrt state.
virtual void sparsityPatternStateTerminal (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols) override
Returns the sparsity pattern for the jacobian wrt state.
virtual void sparsityPatternInputIntermediate (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols) override
Returns the sparsity pattern for the jacobian wrt control.
virtual void sparsityPatternInputTerminal (Eigen::VectorXi &iRows, Eigen::VectorXi &jCols) override
Returns the sparsity pattern for the jacobian wrt control.
virtual size_t getJacobianStateNonZeroCountIntermediate () override
Returns the number of non zero elements in the constraint jacobian wrt state.
virtual size_t getJacobianStateNonZeroCountTerminal () override
Returns the number of non zero elements in the constraint jacobian wrt state.
virtual size_t getJacobianInputNonZeroCountIntermediate () override
Returns the number of non zero elements in the constraint jacobian wrt input.
virtual size_t getJacobianInputNonZeroCountTerminal () override
Returns the number of non zero elements in the constraint jacobian wrt input.
virtual bool initializeIntermediate () override
Initializes the intermediate constraints.
virtual bool initializeTerminal () override
Initializes the terminal constraints.
Public Member Functions inherited from ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
LinearConstraintContainer ()
Default constructor.
LinearConstraintContainer (const LinearConstraintContainer &arg)
Copy constructor.
virtual ~LinearConstraintContainer ()
Destructor.
size_t getJacNonZeroCount ()
Returns the number of non zeros in the constraint jacobian wrt to state and input.
void initialize ()
Initializes the constraint container.
bool isInitialized ()
Checks if the constraint container is initialized.
void printout ()
Print out sparsity patterns, jacobians, etc. Serves for quick visual inspection.
Public Member Functions inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
ConstraintContainerBase ()
Default constructor.
ConstraintContainerBase (const ConstraintContainerBase &arg)
copy constructor
virtual ~ConstraintContainerBase ()
Destructor.
virtual void setCurrentStateAndControl (const state_vector_t &x, const input_vector_t &u, const SCALAR t=SCALAR(0.0))
size_t getConstraintsCount ()
Retrieves the total number of constraints.
VectorXs getLowerBoundsIntermediate () const
Retrieves the lower constraint bound on the intermediate constraints.
VectorXs getLowerBoundsTerminal () const
Retrieves the lower constraint bound on the terminal constraints.
VectorXs getUpperBoundsIntermediate () const
Retrieves the upper constraint bound on the intermediate constraints.
VectorXs getUpperBoundsTerminal () const
Retrieves the upper constraint bound on the terminal constraints.
VectorXs getUpperBoundsViolationIntermediate ()
Retrieves the violation of the upper constraint bound on the intermediate constraints.
VectorXs getLowerBoundsViolationIntermediate ()
Retrieves the violation of the lower constraint bound on the intermediate constraints.
VectorXs getUpperBoundsViolationTerminal ()
Retrieves the violation of the upper constraint bound on the terminal constraints.
VectorXs getLowerBoundsViolationTerminal ()
Retrieves the violation of the lower constraint bound on the terminal constraints.
VectorXs getTotalBoundsViolationIntermediate ()
Retrieves the total violation of the constraints bounds on the intermediate constraints.
VectorXs getTotalBoundsViolationTerminal ()
Retrieves the total violation of the constraints bounds on the terminal constraints.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Public Attributes inherited from ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Public Attributes inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector< STATE_DIM, SCALAR > state_vector_t
Additional Inherited Members
Protected Attributes inherited from ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >
bool initializedIntermediate_
bool initializedTerminal_
Protected Attributes inherited from ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >
state_vector_t x_
input_vector_t u_
SCALAR t_
VectorXs lowerBoundsIntermediate_
VectorXs lowerBoundsTerminal_
VectorXs upperBoundsIntermediate_
VectorXs upperBoundsTerminal_
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >
Contains all the constraints using analytically calculated jacobians.
Template Parameters
STATE_DIM The state dimension
CONTROL_DIM The control dimension
Examples:
ConstraintComparison.h, ConstraintTest.h, DMS.cpp, NLOC_boxConstrained.cpp, oscDMSTest.cpp, and oscDMSTestAllVariants.cpp.
Member Typedef Documentation
input_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef core::ControlVector<CONTROL_DIM, SCALAR> ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::input_vector_t
ConstraintContainerAnalytical_Raw_Ptr_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef ConstraintContainerAnalytical<STATE_DIM, CONTROL_DIM, SCALAR>* ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintContainerAnalytical_Raw_Ptr_t
VectorXs
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, 1> ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs
MatrixXs
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, Eigen::Dynamic, Eigen::Dynamic> ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs
Constructor & Destructor Documentation
ConstraintContainerAnalytical() [1/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintContainerAnalytical ()
ConstraintContainerAnalytical() [2/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintContainerAnalytical (const state_vector_t & x, const input_vector_t & u, const SCALAR & t = 0.0)
Constructor using state, control and time.
Parameters
x state vector
u control vector
t time
ConstraintContainerAnalytical() [3/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintContainerAnalytical (const ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR > & arg)
Copy constructor.
Parameters
arg constraint class to copy
References i.
~ConstraintContainerAnalytical()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::~ConstraintContainerAnalytical () virtual
Destructor.
Member Function Documentation
clone()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintContainerAnalytical_Raw_Ptr_t ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const override virtual
Deep-cloning of Constraint.
Returns
Copy of this object.
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
addIntermediateConstraint()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateConstraint (std::shared_ptr< ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >> constraint, bool verbose)
Adds an intermedaite constraint.
Parameters
[in] constraint The constraint to be added
[in] verbose Flag indicating whether verbosity is on or off
References ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedIntermediate_.
addTerminalConstraint()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::addTerminalConstraint (std::shared_ptr< ConstraintBase< STATE_DIM, CONTROL_DIM, SCALAR >> constraint, bool verbose)
Adds a terminal constraint.
Parameters
[in] constraint The constraint to be added
[in] verbose Flag indicating whether verbosity is on or off
References ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedTerminal_.
evaluateIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate () override virtual
Evaluates the intermediate constraints.
Returns
The evaluation of the intermediate constraints
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
evaluateTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal () override virtual
Evaluates the terminal constraints.
Returns
The evaluation of the terminal constraints
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
getIntermediateConstraintsCount()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateConstraintsCount () override virtual
Retrieves the number of intermediate constraints.
Returns
The number of intermediate constraints
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeIntermediate().
getTerminalConstraintsCount()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getTerminalConstraintsCount () override virtual
Retrieves the number of final constraints.
Returns
The number of final constraints
Implements ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal().
jacobianStateSparseIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseIntermediate () override virtual
Evaluates the constraint jacobian wrt the state using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
jacobianStateIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateIntermediate () override virtual
Evaluates the constraint jacobian wrt the state.
Returns
The jacobian wrt state
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
jacobianStateSparseTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateSparseTerminal () override virtual
Evaluates the constraint jacobian wrt the state using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
jacobianStateTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianStateTerminal () override virtual
Evaluates the constraint jacobian wrt the state.
Returns
The jacobian wrt state
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
jacobianInputSparseIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseIntermediate () override virtual
Evaluates the constraint jacobian wrt the control input using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
jacobianInputIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputIntermediate () override virtual
Evaluates the constraint jacobian wrt the control input.
Returns
The jacobian wrt control
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
jacobianInputSparseTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::VectorXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputSparseTerminal () override virtual
Evaluates the constraint jacobian wrt the control input using sparse representation.
Parameters
jacVec The sparse jacobian vector
count The size of jacVec
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
jacobianInputTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::MatrixXs ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInputTerminal () override virtual
Evaluates the constraint jacobian wrt the control input.
Returns
The jacobian wrt control
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::t_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::u_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::x_.
sparsityPatternStateIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateIntermediate (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) override virtual
Returns the sparsity pattern for the jacobian wrt state.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
sparsityPatternStateTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternStateTerminal (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) override virtual
Returns the sparsity pattern for the jacobian wrt state.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedTerminal_.
sparsityPatternInputIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputIntermediate (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) override virtual
Returns the sparsity pattern for the jacobian wrt control.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
sparsityPatternInputTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > void ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::sparsityPatternInputTerminal (Eigen::VectorXi & iRows, Eigen::VectorXi & jCols) override virtual
Returns the sparsity pattern for the jacobian wrt control.
Parameters
iRows The vector of the row indices containing non zero elements in the constraint jacobian
jCols The vector of the column indices containing non zero elements in the constraint jacobian
Returns
The size of iRow and jCols
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedTerminal_.
getJacobianStateNonZeroCountIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountIntermediate () override virtual
Returns the number of non zero elements in the constraint jacobian wrt state.
Returns
The number of the non zeros
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeIntermediate().
getJacobianStateNonZeroCountTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountTerminal () override virtual
Returns the number of non zero elements in the constraint jacobian wrt state.
Returns
The number of the non zeros
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal().
getJacobianInputNonZeroCountIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountIntermediate () override virtual
Returns the number of non zero elements in the constraint jacobian wrt input.
Returns
The number of the non zeros
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeIntermediate().
getJacobianInputNonZeroCountTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > size_t ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountTerminal () override virtual
Returns the number of non zero elements in the constraint jacobian wrt input.
Returns
The number of the non zeros
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal().
initializeIntermediate()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > bool ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeIntermediate () override virtual
Initializes the intermediate constraints.
Returns
Returns true if the initialization was successful
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getIntermediateConstraintsCount(), ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountIntermediate(), ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountIntermediate(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::lowerBoundsIntermediate_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::upperBoundsIntermediate_.
initializeTerminal()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR > bool ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::initializeTerminal () override virtual
Initializes the terminal constraints.
Returns
Returns true if the initialization was successful
Implements ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianInputNonZeroCountTerminal(), ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getJacobianStateNonZeroCountTerminal(), ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::getTerminalConstraintsCount(), ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedIntermediate_, ct::optcon::LinearConstraintContainer< STATE_DIM, CONTROL_DIM, SCALAR >::initializedTerminal_, ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::lowerBoundsTerminal_, and ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::upperBoundsTerminal_.
Member Data Documentation
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef core::StateVector<STATE_DIM, SCALAR> ct::optcon::ConstraintContainerAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/constraint/ConstraintContainerAnalytical.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/constraint/ConstraintContainerAnalytical-impl.h