/home/adrl/code/src/control-toolbox/ct_optcon/test/nloc/constrained/ConstrainedNLOCTest.cpp File Reference
ConstrainedNLOCTest.cpp File Reference
#include <ct/optcon/optcon.h>
#include "nloc_test_dir.h"
#include <gtest/gtest.h>
Classes
class ControlInputGenConstraint
class StateGenConstraint
Functions
std::shared_ptr< ct::core::ControlledSystem< state_dim, control_dim > > oscillatorDynamics (new ct::core::SecondOrderSystem(w_n, zeta))
std::shared_ptr< ct::core::SystemLinearizer< state_dim, control_dim > > linearizer (new ct::core::SystemLinearizer< state_dim, control_dim >(oscillatorDynamics))
void compareSolutions (const ct::core::StateFeedbackController< state_dim, control_dim > &sol1, const ct::core::StateFeedbackController< state_dim, control_dim > &sol2)
NLOptConSolver< state_dim, control_dim > generateSolver (ContinuousOptConProblem< state_dim, control_dim > ocp)
ContinuousOptConProblem< state_dim, control_dim > generateUnconstrainedOCP ()
TEST (Constrained_NLOC_Test, comparePureControlConstraints)
TEST (Constrained_NLOC_Test, comparePureStateConstraints)
int main (int argc, char **argv)
Variables
const bool verbose = false
const size_t state_dim = ct::core::SecondOrderSystem::STATE_DIM
const size_t control_dim = ct::core::SecondOrderSystem::CONTROL_DIM
StateVector< state_dim > x0 = StateVector<state_dim>::Zero()
ct::core::Time timeHorizon = 3.0
const double w_n = 0.1
const double zeta = 5.0
std::string nloc_test_dir = std::string(NLOC_TEST_DIR)
Function Documentation
std::shared_ptr<ct::core::ControlledSystem<state_dim, control_dim> > oscillatorDynamics (new ct::core::SecondOrderSystemw_n, zeta)
Examples:
LQR.cpp, NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_generalConstrained.cpp, and NLOC_MPC.cpp.
Referenced by generateUnconstrainedOCP(), and main().
std::shared_ptr<ct::core::SystemLinearizer<state_dim, control_dim> > linearizer (new ct::core::SystemLinearizer< state_dim, control_dim > oscillatorDynamics)
Examples:
KalmanDisturbanceFiltering.cpp, and KalmanFiltering.cpp.
Referenced by generateUnconstrainedOCP(), and main().
void compareSolutions (const ct::core::StateFeedbackController< state_dim, control_dim > & sol1, const ct::core::StateFeedbackController< state_dim, control_dim > & sol2)
References control_dim, n, state_dim, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::uff(), and ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::x_ref().
Referenced by TEST().
NLOptConSolver<state_dim, control_dim> generateSolver (ContinuousOptConProblem< state_dim, control_dim > ocp)
References ct::optcon::LineSearchSettings::active, ct::optcon::NLOptConSettings::computeK(), ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqoc_solver_settings, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::LQOCSolverSettings::num_lqoc_iterations, ct::optcon::NLOptConSettings::printSummary, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), and timeHorizon.
Referenced by TEST().
ContinuousOptConProblem<state_dim, control_dim> generateUnconstrainedOCP ()
References linearizer(), oscillatorDynamics(), timeHorizon, verbose, and x0.
Referenced by TEST().
TEST (Constrained_NLOC_Test , comparePureControlConstraints)
References compareSolutions(), control_dim, generateSolver(), generateUnconstrainedOCP(), and verbose.
TEST (Constrained_NLOC_Test , comparePureStateConstraints)
References compareSolutions(), generateSolver(), generateUnconstrainedOCP(), state_dim, and verbose.
int main (int argc, char ** argv)
Variable Documentation
const bool verbose = false
Referenced by generateUnconstrainedOCP(), and TEST().
const size_t state_dim = ct::core::SecondOrderSystem::STATE_DIM
Referenced by compareSolutions(), and TEST().
const size_t control_dim = ct::core::SecondOrderSystem::CONTROL_DIM
Referenced by compareSolutions(), and TEST().
StateVector<state_dim> x0 = StateVector<state_dim>::Zero()
Examples:
LinearSystemTest.h, NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_generalConstrained.cpp, NLOC_MPC.cpp, NonlinearSystemTest.h, switched_continuous_optcon.cpp, and SymplecticTest.h.
Referenced by ct::optcon::OptVectorDms< STATE_DIM, CONTROL_DIM, SCALAR >::changeInitialState(), ct::optcon::NLOCBackendBase< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::changeInitialState(), ct::optcon::DmsSolver< STATE_DIM, CONTROL_DIM, SCALAR >::changeInitialState(), ct::optcon::DmsProblem< STATE_DIM, CONTROL_DIM, SCALAR >::DmsProblem(), generateUnconstrainedOCP(), main(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::OptConProblemBase(), ct::optcon::OptConSolver< DmsSolver< STATE_DIM, CONTROL_DIM, SCALAR >, DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >, DmsSettings, STATE_DIM, CONTROL_DIM, SCALAR >::runIteration(), ct::optcon::LQOCProblem< STATE_DIM, CONTROL_DIM, SCALAR >::setFromTimeInvariantLinearQuadraticProblem(), ct::optcon::OptVectorDms< STATE_DIM, CONTROL_DIM, SCALAR >::setInitGuess(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setInitialState(), ct::optcon::example::symplecticTest(), ct::optcon::example::TEST(), TEST(), timeSingleSolve(), and ct::optcon::InitStateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >::updateConstraint().
ct::core::Time timeHorizon = 3.0
Examples:
NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_generalConstrained.cpp, NLOC_MPC.cpp, and switched_continuous_optcon.cpp.
Referenced by ct::optcon::tpl::TimeGrid< SCALAR >::changeTimeHorizon(), generateSolver(), generateUnconstrainedOCP(), main(), and ct::optcon::example::TEST().
const double w_n = 0.1
Examples:
DMS.cpp, KalmanDisturbanceFiltering.cpp, KalmanFiltering.cpp, LQR.cpp, NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_generalConstrained.cpp, and NLOC_MPC.cpp.
Referenced by main().
const double zeta = 5.0
Examples:
DMS.cpp, NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_generalConstrained.cpp, and NLOC_MPC.cpp.
Referenced by main().
std::string nloc_test_dir = std::string(NLOC_TEST_DIR)
Referenced by macro().