/home/adrl/code/src/control-toolbox/ct_optcon/examples/DMS.cpp File Reference
DMS.cpp File Reference
#include <ct/optcon/optcon.h>
#include "exampleDir.h"
#include "plotResultsOscillator.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
STEP 1 : set up the optimal control problem
STEP 2 : determine solver settings
STEP 3 : Calculate an appropriate initial guess
STEP 4: solve DMS with IPOPT
Examples:
DMS.cpp.
References ct::optcon::DmsSettings::absErrTol_, control_dim, ct::optcon::DmsSettings::costEvaluationType_, ct::optcon::DmsSettings::dt_sim_, ct::optcon::DmsSettings::FULL, ct::optcon::DmsSettings::h_min_, i, ct::optcon::DmsSettings::integrationType_, ct::optcon::IPOPT, ct::optcon::DmsSettings::KEEP_TIME_AND_GRID, ct::optcon::DmsSettings::N_, ct::optcon::DmsSettings::nThreads_, ct::optcon::DmsSettings::objectiveType_, ct::optcon::DmsSettings::PIECEWISE_LINEAR, ct::optcon::DmsSettings::print(), ct::optcon::DmsSettings::relErrTol_, ct::optcon::DmsSettings::RK4, ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setGeneralConstraints(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setInitialState(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setTimeHorizon(), ct::optcon::DmsSettings::solverSettings_, ct::optcon::NlpSolverSettings::solverType_, ct::optcon::DmsSettings::splineType_, state_dim, ct::optcon::DmsSettings::T_, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::tSolution_, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::uSolution_, w_n, ct::optcon::DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >::xSolution_, and zeta.