/home/adrl/code/src/control-toolbox/ct_optcon/include/ct/optcon/nloc/algorithms/gnms/matlab/gnmsPlot.m File Reference
gnmsPlot.m File Reference
Functions
figure () subplot(2
plot (t, x(1,:), 'kx', 'MarkerSize', 1) hold on
plot (t, xShot(1,:), 'bx', 'MarkerSize', 1) legend('x *'
xlabel ('t[sec]') ylabel('x[m]') title('positions')
subplot (2, 2, 2) plot(t
x (2,:)
plot (t, xShot(2,:), 'b') legend('v *'
subplot(2, 2, 3) plot(t(1 hold on plot (t, lx(2,:))
hold on title ('state update') xlabel('t[sec]') ylabel('dx[m]') legend('x update'
plot (t(1:end-1), d(1,:))
Variables
clear all close all load ct GNMSLog0 mat reformat t = squeeze(t)
lv = squeeze(lv)
x init
k hold on
Function Documentation
hold on v update figure ()
plot (t , x(1,:) , 'kx' , 'MarkerSize' , 1)
plot (t , xShot(1,:) , 'bx' , 'MarkerSize' , 1)
xlabel ('t' [sec])
subplot (2 , 2 , 2)
x (2 , :)
plot (t , xShot(2,:) , 'b')
subplot (2,2,3) plot(t(1 hold on plot (t , lx(2,:))
hold on title ('state update')
plot (t(1:end-1) , d(1,:))
Variable Documentation
clear all close all load ct GNMSLog0 mat reformat t = squeeze(t)
Examples:
ConstraintComparison.h, ConstraintTest.h, KalmanDisturbanceFiltering.cpp, LQR.cpp, NLOC_generalConstrained.cpp, NLOC_MPC.cpp, and SymplecticTest.h.
Referenced by ct::optcon::CTSystemModel< STATE_DIM, CONTROL_DIM, SCALAR >::computeDerivativeState(), ct::optcon::CTSystemModel< STATE_DIM, CONTROL_DIM, SCALAR >::computeDynamics(), ct::optcon::UnscentedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::computeSigmaPointMeasurements(), ct::optcon::UnscentedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::computeSigmaPointTransition(), ct::optcon::UnscentedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::computeStatePrediction(), ct::optcon::EstimatorBase< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::EstimatorBase(), ct::optcon::example::TestTerm< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evalLocal(), ct::optcon::TermLinear< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermSmoothAbs< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermQuadTracking< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermMixed< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermQuadMult< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermQuadratic< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::example::TestTerm< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermLinear< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermSmoothAbs< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermMixed< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermQuadMult< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermQuadratic< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::example::TestTerm< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::ShotContainer< STATE_DIM, CONTROL_DIM, SCALAR >::getUHistory(), main(), ct::optcon::ExtendedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::predict(), ct::optcon::SteadyStateKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::predict(), ct::optcon::UnscentedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::predict(), ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::setControlledSystem(), ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::setCostFunction(), ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::setLinearSystem(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::shiftTime(), ct::optcon::example::TEST(), ct::optcon::ExtendedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::update(), ct::optcon::SteadyStateKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::update(), ct::optcon::UnscentedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::update(), and ct::optcon::MeasurementModelBase< OUTPUT_DIM, STATE_DIM, SCALAR >::~MeasurementModelBase().
lv = squeeze(lv)
v init
hold on