/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/test/solver/linear/HPIPMInterfaceTest.h File Reference
HPIPMInterfaceTest.h File Reference
#include "../../testSystems/LinkedMasses.h"
Functions
TEST (HPIPMInterfaceTest, compareSolvers)
Function Documentation
TEST()
TEST (HPIPMInterfaceTest , compareSolvers)
This unit test compares HPIPM and the custom GNRiccati solver using custom defined system with state dimension 8 and control dimension 3.
Warning
This example is not intuitive. For a better introduction into the solver-framework, visit the tutorial.
References ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::compute_lv(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::computeFeedbackMatrices(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::computeStatesAndControls(), control_dim, dt, ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::get_lv(), ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionControl(), ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionFeedback(), ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::getSolutionState(), i, ct::optcon::LQOCSolver< STATE_DIM, CONTROL_DIM, SCALAR >::setProblem(), ct::optcon::GNRiccatiSolver< STATE_DIM, CONTROL_DIM, SCALAR >::solve(), state_dim, and x0.