/home/adrl/code/src/control-toolbox/ct_optcon/examples/KalmanFiltering.cpp File Reference
KalmanFiltering.cpp File Reference
#include <ct/optcon/optcon.h>
#include <ct/core/examples/CustomController.h>
#include "exampleDir.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Examples:
KalmanFiltering.cpp.
References ct::core::tpl::SecondOrderSystem< class >::CONTROL_DIM, control_dim, dt, i, ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::core::plot::labelPlot(), ct::core::plot::legend(), linearizer(), ct::core::loadMatrix(), ct::core::GaussianNoise::noisify(), output_dim, ct::optcon::ExtendedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::predict(), ct::core::plot::show(), ct::core::tpl::SecondOrderSystem< class >::STATE_DIM, state_dim, ct::core::plot::subplot(), ct::optcon::ExtendedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::update(), w_n, x, ct::core::plot::xlabel(), and ct::core::plot::ylabel().