/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/examples/KalmanDisturbanceFiltering.cpp File Reference
KalmanDisturbanceFiltering.cpp File Reference
#include <ct/optcon/optcon.h>
#include "exampleDir.h"
Classes
class CustomController
An example controller, in which we artifically add a time-varying disturbance.
Functions
int main (int argc, char **argv)
Variables
const size_t state_dim = ct::core::SecondOrderSystem::STATE_DIM
const size_t control_dim = ct::core::SecondOrderSystem::CONTROL_DIM
const size_t output_dim = state_dim
const size_t dist_dim = control_dim
Function Documentation
main()
int main (int argc, char ** argv)
Examples:
KalmanDisturbanceFiltering.cpp.
References CustomController::CustomController(), dt, ct::optcon::ExtendedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::getCovarianceMatrix(), i, ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::core::plot::labelPlot(), ct::core::plot::legend(), linearizer(), ct::core::loadMatrix(), ct::core::loadScalar(), ct::core::GaussianNoise::noisify(), ct::optcon::ExtendedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::predict(), ct::core::plot::show(), ct::core::plot::subplot(), ct::optcon::ExtendedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::update(), w_n, x, ct::core::plot::xlabel(), and ct::core::plot::ylabel().
Variable Documentation
state_dim
const size_t state_dim = ct::core::SecondOrderSystem::STATE_DIM
Examples:
KalmanDisturbanceFiltering.cpp.
control_dim
const size_t control_dim = ct::core::SecondOrderSystem::CONTROL_DIM
Examples:
KalmanDisturbanceFiltering.cpp.
output_dim
const size_t output_dim = state_dim
Examples:
KalmanDisturbanceFiltering.cpp, and KalmanFiltering.cpp.
Referenced by main().
dist_dim
const size_t dist_dim = control_dim
Examples:
KalmanDisturbanceFiltering.cpp.