/home/adrl/code/src/control-toolbox/ct_optcon/test/costfunction/LoadFromFileTest.cpp File Reference
LoadFromFileTest.cpp File Reference
#include <gtest/gtest.h>
#include <ct/optcon/optcon.h>
#include "compareCostFunctions.h"
#include "costfunction_test_dir.h"
Namespaces
ct
ct::optcon
ct::optcon::example
Functions
ct::optcon::example::TEST (LoadCostFromFileTest, LoadAnalyticalDirect)
Test case: trying to load analytical cost function directly from file.
ct::optcon::example::TEST (LoadCostFromFileTest, LoadAnalyticalViaTerms)
Test case: trying to load analytical cost terms separately and then add them cost function.
ct::optcon::example::TEST (LoadCostFromFileTest, LoadADViaTerms)
Test case: trying to load AD cost terms separately and then add them to the cost function.
ct::optcon::example::TEST (LoadCostFromFileTest, LoadADDirect1)
Test case: trying to load AD cost directly, but calling standard constructor first.
ct::optcon::example::TEST (LoadCostFromFileTest, LoadADDirect2)
Test case: trying to load AD cost directly.
int main (int argc, char **argv)
Variables
std::string costFunctionFile = std::string(COSTFUNCTION_TEST_DIR) + "/example_cost_file.info"
const bool verbose = false
const size_t state_dim = 12
const size_t control_dim = 6
ct::core::StateVector< state_dim > x = ct::core::StateVector<state_dim>::Random()
ct::core::ControlVector< control_dim > u = ct::core::ControlVector<control_dim>::Random()
double t = 0.0
Function Documentation
int main (int argc, char ** argv)
References testing::InitGoogleTest(), and RUN_ALL_TESTS().
Variable Documentation
std::string costFunctionFile = std::string(COSTFUNCTION_TEST_DIR) + "/example_cost_file.info"
Examples:
NonlinearSystemTest.h.
Referenced by ct::optcon::example::TEST().
const bool verbose = false
const size_t state_dim = 12
const size_t control_dim = 6
ct::core::StateVector<state_dim> x = ct::core::StateVector<state_dim>::Random()
Examples:
ConstraintComparison.h, ConstraintTest.h, KalmanDisturbanceFiltering.cpp, KalmanFiltering.cpp, LQR.cpp, NLOC_generalConstrained.cpp, and SymplecticTest.h.
Referenced by ct::optcon::CTSystemModel< STATE_DIM, CONTROL_DIM, SCALAR >::computeDynamics(), ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::configure(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintContainerAD(), StateSumConstraint::evaluate(), ct::optcon::TermLinear< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermSmoothAbs< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermStateBarrier< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermQuadTracking< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermMixed< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate(), ConstraintTerm1D::evaluate(), ct::optcon::example::PureStateConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate(), ct::optcon::TermQuadMult< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::StateConstraint< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate(), ct::optcon::TermQuadratic< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::example::TestTerm< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), StateGenConstraint::evaluate(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate(), StateSumConstraint::evaluateCppadCg(), ct::optcon::TermLinear< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermStateBarrier< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermSmoothAbs< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermMixed< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermQuadMult< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateCppadCg(), ConstraintTerm1D::evaluateCppadCg(), ct::optcon::TermQuadratic< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::example::TestTerm< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), StateGenConstraint::evaluateCppadCg(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateCppadCg(), ct::optcon::MPC< OPTCON_SOLVER >::finishIteration(), ct::optcon::example::LinearizedSystem::getDerivativeState(), ct::optcon::example::DiehlSystemLinear::getDerivativeState(), ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInput(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianInput(), ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianState(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianState(), main(), ct::optcon::SensitivityIntegratorCT< STATE_DIM, CONTROL_DIM, SCALAR >::setControlledSystem(), ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::EstimatorBase< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::setEstimate(), ct::optcon::tpl::OptVector< SCALAR >::setNewIpoptSolution(), ct::optcon::tpl::OptVector< SCALAR >::setNewSnoptSolution(), ct::optcon::tpl::OptVector< SCALAR >::setOptimizationVars(), ct::optcon::example::TEST(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface(), and ct::optcon::OptconDiscreteSystemInterface< STATE_DIM, CONTROL_DIM, SCALAR >::~OptconDiscreteSystemInterface().
ct::core::ControlVector<control_dim> u = ct::core::ControlVector<control_dim>::Random()
Examples:
ConstraintComparison.h, ConstraintTest.h, LQR.cpp, NLOC_generalConstrained.cpp, and SymplecticTest.h.
Referenced by ct::optcon::CTSystemModel< STATE_DIM, CONTROL_DIM, SCALAR >::computeDerivativeState(), ct::optcon::CTSystemModel< STATE_DIM, CONTROL_DIM, SCALAR >::computeDynamics(), ct::optcon::UnscentedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::computeSigmaPointTransition(), ct::optcon::UnscentedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::computeStatePrediction(), ct::optcon::OptconSystemInterface< STATE_DIM, CONTROL_DIM, DiscreteOptConProblem< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >::configure(), ct::optcon::ConstraintContainerAD< STATE_DIM, CONTROL_DIM, SCALAR >::ConstraintContainerAD(), ct::optcon::TermQuadTracking< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::controlDerivative(), ct::optcon::EstimatorBase< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::EstimatorBase(), ct::optcon::TermLinear< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evalLocal(), ct::optcon::TermQuadTracking< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evalLocal(), ct::optcon::TermLinear< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermSmoothAbs< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermQuadTracking< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::TermMixed< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate(), ConstraintTerm1D::evaluate(), ct::optcon::TermQuadMult< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::ControlInputConstraint< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate(), ct::optcon::TermQuadratic< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ct::optcon::example::TestTerm< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluate(), ControlInputGenConstraint::evaluate(), ct::optcon::example::StateInputConstraint_Example< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::evaluate(), ct::optcon::TermLinear< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermSmoothAbs< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermMixed< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::TermQuadMult< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateCppadCg(), ConstraintTerm1D::evaluateCppadCg(), ct::optcon::TermQuadratic< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ct::optcon::example::TestTerm< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::evaluateCppadCg(), ControlInputGenConstraint::evaluateCppadCg(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateCppadCg(), ct::optcon::example::ConstraintTerm1D< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianState(), ct::optcon::example::ConstraintTerm2D< STATE_DIM, CONTROL_DIM, SCALAR >::jacobianState(), main(), ct::optcon::ExtendedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::predict(), ct::optcon::SteadyStateKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::predict(), ct::optcon::UnscentedKalmanFilter< STATE_DIM, CONTROL_DIM, OUTPUT_DIM, SCALAR >::predict(), ct::optcon::CostFunctionQuadraticSimple< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::ConstraintContainerBase< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::example::TEST(), ct::optcon::OptconContinuousSystemInterface< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~OptconContinuousSystemInterface(), and ct::optcon::OptconDiscreteSystemInterface< STATE_DIM, CONTROL_DIM, SCALAR >::~OptconDiscreteSystemInterface().
double t = 0.0
Referenced by ct::optcon::example::TEST().