/home/adrl/code/src/control-toolbox/ct_optcon/test/dms/oscillator/matfiles/matFilesGenerator.cpp File Reference
matFilesGenerator.cpp File Reference
#include <ct/optcon/optcon.h>
#include "oscDMSTest_settings.h"
Classes
class ct::optcon::example::MatFilesGenerator
Namespaces
ct
ct::optcon
ct::optcon::example
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
This executable is used to generate the reference matfiles for the unit tests.
References ct::optcon::example::MatFilesGenerator::generateMatFilesIPOPT(), ct::optcon::example::MatFilesGenerator::generateMatFilesSNOPT(), and ct::optcon::example::MatFilesGenerator::initialize().