ct::optcon Namespace Reference
ct::optcon Namespace Reference
Namespaces
example
tpl
Classes
class BoxConstraintBase
Base for box constraint, templated on dimension of the decision vector of the derived class.
class CARE
Continuous-Time Algebraic Riccati Equation.
class Cholesky
Cholesky square root decomposition of a symmetric positive-definite matrix.
class ConstraintBase
Base class for the constraints used in this toolbox.
class ConstraintContainerAnalytical
Contains all the constraints using analytically calculated jacobians.
class ConstraintContainerBase
The ConstraintBase Class is the base class for defining the non-linear optimization constraints.
class ConstraintDiscretizer
The class takes continuous constraints defined with the constraint toolbox and discretizes them over the DMS shots. These discretized constraints can then be used in the NLP module.
class ConstraintsContainerDms
Container class for the constraints used in DMS.
class ContinuityConstraint
Implementation of the DMS continuity constraints.
class ControlInputConstraint
Class for control input box constraint term.
class ControllerDms
DMS controller class.
class CostEvaluatorFull
Performs the full cost integration over the shots.
class CostEvaluatorSimple
Evaluates the cost at the shots and performs some interpolation in between.
class CostFunction
A base function for cost functions. All cost functions should derive from this.
class CostFunctionAnalytical
A cost function which contains only terms that have analytical derivatives.
class CostFunctionQuadratic
Describes a cost function with a quadratic approximation, i.e. one that can compute first and second order derivatives with respect to state and control input. This does NOT mean it has to be a purely quadratic cost function. If you are looking for a purely quadratic cost function, check CostFunctionQuadraticSimple.
class CostFunctionQuadraticSimple
A simple quadratic cost function.
class CTSystemModel
System model adapted to CT. System model encapsulates the integrator, so it is able to propagate the system, but also computes derivatives w.r.t. both state and noise. When propagating the system, CTSystemModel does not use the specified control input, but uses the assigned system controller instead.
class DARE
Discrete-Time Algebraic Riccati Equation.
class DisturbedSystem
Disturbed system augments the nominal system so that all the CT interfaces and dimensions are satisfied. What is done is basically augmenting the state with the assumed disturbance with specified dimensionality.
class DisturbedSystemController
Disturbed controller allows us to augment the controller so that all the CT interfaces and dimensions are satisfied. Augmenting is done in such a way that the nominal controller is wrapped and all the nominal states are controlled in the same way as before augmenting the state. The augmented state (the disturbance part) is assumed constant, thus the computed derivates of that part of the state are set to zero.
class DmsDimensions
Defines basic types used in the DMS algorithm.
struct DmsPolicy
The DMS policy used as a solution container.
class DmsProblem
This class sets up the DMS problem.
class DmsSettings
Defines the DMS settings.
class DmsSolver
Class to solve a specfic DMS problem.
class DynamicRiccatiEquation
Dynamic Riccati Equation.
class EstimatorBase
Estimator base.
class ExtendedKalmanFilter
Extended Kalman Filter implementation. For an algorithmic overview, see also https://en.wikipedia.org/wiki/Extended_Kalman_filter.
struct ExtendedKalmanFilterSettings
Settings for setting up an ExtendedKF.
class FHDTLQR
Finite-Horizon Discrete Time LQR.
class GNRiccatiSolver
class InitStateConstraint
The implementation of the DMS initial state constraint.
class InputDisturbedSystem
Implementation of an input disturbed system where, the dimension of the disturbance is equal to the dimension of the control input, thus DIST_DIM = CONTROL_DIM. This is a special case, however it occurs often and is convenient to have as separate class.
class IpoptSettings
IPOPT settings. Details about the parameters can be found in the IPOPT documentation.
class LinearConstraintContainer
A base function for linear constraint functions which have a first derivative.
class LinearMeasurementModel
Linear Measurement Model is an interface for linear measurement models most commonly used in practice.
class LinearSpliner
The linear spline implementation.
struct LineSearchSettings
GNMS Line Search Settings.
class LQOCProblem
Defines a Linear-Quadratic Optimal Control Problem, which is optionally constrained.
class LQOCSolver
struct LQOCSolverSettings
LQOC Solver settings.
class LQR
continuous-time infinite-horizon LQR
class LTIMeasurementModel
Linear Time-Invariant measurement model is simply a linear measurement model for which the matrix C is constant in time.
class MeasurementModelBase
class MPC
Main MPC class.
struct mpc_settings
MPC Settings struct.
class MultipleShooting
class NLOCAlgorithm
class NLOCBackendBase
C++ implementation of GNMS.
class NLOCBackendMP
class NLOCBackendST
class NLOptConSettings
Settings for the NLOptCon algorithm.
class NLOptConSolver
class NlpSolverSettings
Contains the NLP solver settings.
class ObstacleConstraint
Class for obstacle constraint.
class OptconContinuousSystemInterface
interface class for optimal control algorithms
class OptconDiscreteSystemInterface
interface class for optimal control algorithms
class OptConProblemBase
class OptConSolver
class OptconSystemInterface
interface base class for optimal control algorithms
class OptVectorDms
This class is a wrapper around the NLP Optvector. It wraps the Vectors from the NLP solvers into state, control and time trajectories.
class PolicyHandler
class RKnDerivatives
This class implements analytical sensitivity generation for the euler and rk4 integration scheme.
class SensitivityIntegratorCT
This class can integrate a controlled system and a costfunction. Furthermore, it provides first order derivatives with respect to initial state and control.
class ShotContainer
This class performs the state and the sensitivity integration on a shot.
class SingleShooting
class SnoptSettings
SnoptSolver settings. Details about the parameters can be found in the SNOPT documentation.
class SnoptSolver
class SplinerBase
Abstract base class for the control input splining between the DMS shots.
class StateConstraint
Class for state box constraint.
class StateFeedbackPolicyHandler
the default policy handler for iLQR
struct StateObserverSettings
Settings for setting up a StateObserver.
class SteadyStateKalmanFilter
Steady State Kalman Filter is a time invariant linear estimator. It starts with the same update rule as the standard Kalman Filter, but instead of propagating the covariance and estimate through time, it assumes convergence reducing the problem to solving an Algebraic Ricatti Equation.
struct SteadyStateKalmanFilterSettings
Settings for setting up a SteadyStateKF.
class SwitchedLinearConstraintContainer
A container for switching linear constraint containers.
class SystemModelBase
System model is an interface that encapsulates the integrator to be able to propagate the system, but is also able to compute derivatives w.r.t. both state and noise.
class TermBase
An interface for a term, supporting both analytical and auto-diff terms.
class TerminalConstraint
Class for terminal constraint.
class TermLinear
A linear term of type .
class TermMixed
A basic quadratic term of type .
class TermQuadMult
A multiplicative term of type .
class TermQuadratic
A basic quadratic term of type .
class TermQuadTracking
A quadratic tracking term of type .
class TermSmoothAbs
A smooth absolute term of type where this calculation is performed component-wise and summed with individual weighting factors a[i], b[i].
class TermStateBarrier
A state barrier term (could also be considered a soft constraint) Note that this term explicitly excludes controls, as there are better ways to limit control effort in a "soft" way, e.g. through the use of sigmoid functions.
class UnscentedKalmanFilter
Unscented Kalman Filter is a nonlinear estimator best suited for highly nonlinear systems. It combines the principles of EKF and particle filter. The downside is the computation complexity.
struct UnscentedKalmanFilterSettings
Settings for setting up an UnscentedKF.
class ZeroOrderHoldSpliner
The spline implementation for the zero order hold spliner.
Typedefs
typedef tpl::TimeGrid< double > TimeGrid
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double>
using DisturbanceObserverSettings = StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >
Settings for setting up a DisturbanceObserver.
typedef tpl::MpcTimeKeeper< double > MpcTimeKeeper
typedef tpl::MpcTimeHorizon< double > MpcTimeHorizon
using DiscreteConstraintBase = tpl::DiscreteConstraintBase< double >
using DiscreteConstraintContainerBase = tpl::DiscreteConstraintContainerBase< double >
using DiscreteCostEvaluatorBase = tpl::DiscreteCostEvaluatorBase< double >
using Nlp = tpl::Nlp< double >
using OptVector = tpl::OptVector< double >
using IpoptSolver = tpl::IpoptSolver< double >
using NlpSolver = tpl::NlpSolver< double >
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
using ContinuousOptConProblem = OptConProblemBase< STATE_DIM, CONTROL_DIM, core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >, core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >, core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
using DiscreteOptConProblem = OptConProblemBase< STATE_DIM, CONTROL_DIM, core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >, core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >, core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >, SCALAR >
Enumerations
enum MPC_MODE { FIXED_FINAL_TIME = 0, CONSTANT_RECEDING_HORIZON, FIXED_FINAL_TIME_WITH_MIN_TIME_HORIZON, RECEDING_HORIZON_WITH_FIXED_FINAL_TIME }
select a mode in which MPC is supposed to run
enum NlpSolverType : uint8_t { NlpSolverType::IPOPT = 0, NlpSolverType::SNOPT = 1, NlpSolverType::num_types_solver }
The available types of NLP solvers.
Functions
template<typename SCALAR >
void loadScalarCF (const std::string &filename, const std::string &scalarName, SCALAR &scalar, const std::string &termName="")
template<typename SCALAR >
void loadScalarOptionalCF (const std::string &filename, const std::string &scalarName, SCALAR &scalar, const std::string &termName, const SCALAR &defaultValue)
template<typename SCALAR , int ROW, int COL>
void loadMatrixCF (const std::string &filename, const std::string &matrixName, Eigen::Matrix< SCALAR, ROW, COL > &matrix, const std::string &termName="")
template<typename TERM_PTR , typename costFuncType >
void addTerm (const std::string &filename, std::string &currentTerm, int currentTermType, TERM_PTR term, costFuncType *costFunc, bool verbose=false)
template<typename TERM_PTR , typename costFuncType >
void addADTerm (const std::string &filename, std::string &currentTerm, int currentTermType, TERM_PTR term, costFuncType *costFunc, bool verbose=false)
void loadMpcSettings (const std::string &filename, mpc_settings &settings)
load the mpc settings from file
Typedef Documentation
TimeGrid
typedef tpl::TimeGrid<double> ct::optcon::TimeGrid
DisturbanceObserverSettings
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> using ct::optcon::DisturbanceObserverSettings = typedef StateObserverSettings<OUTPUT_DIM, STATE_DIM, SCALAR>
Settings for setting up a DisturbanceObserver.
The DisturbanceObserver settings are designed to make the initialization smoother and possible through a file configuration.
MpcTimeKeeper
typedef tpl::MpcTimeKeeper<double> ct::optcon::MpcTimeKeeper
MpcTimeHorizon
typedef tpl::MpcTimeHorizon<double> ct::optcon::MpcTimeHorizon
DiscreteConstraintBase
using ct::optcon::DiscreteConstraintBase = typedef tpl::DiscreteConstraintBase<double>
DiscreteConstraintContainerBase
using ct::optcon::DiscreteConstraintContainerBase = typedef tpl::DiscreteConstraintContainerBase<double>
DiscreteCostEvaluatorBase
using ct::optcon::DiscreteCostEvaluatorBase = typedef tpl::DiscreteCostEvaluatorBase<double>
Nlp
using ct::optcon::Nlp = typedef tpl::Nlp<double>
OptVector
using ct::optcon::OptVector = typedef tpl::OptVector<double>
IpoptSolver
using ct::optcon::IpoptSolver = typedef tpl::IpoptSolver<double>
NlpSolver
using ct::optcon::NlpSolver = typedef tpl::NlpSolver<double>
ContinuousOptConProblem
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> using ct::optcon::ContinuousOptConProblem = typedef OptConProblemBase<STATE_DIM, CONTROL_DIM, core::ControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR>, core::LinearSystem<STATE_DIM, CONTROL_DIM, SCALAR>, core::SystemLinearizer<STATE_DIM, CONTROL_DIM, SCALAR>, SCALAR>
DiscreteOptConProblem
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> using ct::optcon::DiscreteOptConProblem = typedef OptConProblemBase<STATE_DIM, CONTROL_DIM, core::DiscreteControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR>, core::DiscreteLinearSystem<STATE_DIM, CONTROL_DIM, SCALAR>, core::DiscreteSystemLinearizer<STATE_DIM, CONTROL_DIM, SCALAR>, SCALAR>
Enumeration Type Documentation
MPC_MODE
enum ct::optcon::MPC_MODE
select a mode in which MPC is supposed to run
There are four default implementations for time horizon strategies in MPC, which can be selected using the following "MPC_MODE" enum.
FIXED_FINAL_TIME plan until a fixed final time T is reached. Time Horizon will continuously shrink and eventually be zero.
FIXED_FINAL_TIME_WITH_MIN_TIME_HORIZON this option continuously shrinks the time horizon from the initil time horizon until some minimum time is reached. This minimum time can be specified in the mpc_settings struct as "minimumTimeHorizonMpc_"
CONSTANT_RECEDING_HORIZON Time Horizon remains constant for all times and is equal to the initial time horizon specified in the optimal control problem.
RECEDING_HORIZON_WITH_FIXED_FINAL_TIME Time Horizon remains constant until a fixed final time is near. It shrinks and eventually becomes zero. The overall time horizon gets set trough the initial problem time horizon. The smaller, receding time horizon can be specified in the mpc_settings struct as "minimumTimeHorizonMpc_"
Enumerator
FIXED_FINAL_TIME
FIXED_FINAL_TIME.
CONSTANT_RECEDING_HORIZON
CONSTANT_RECEDING_HORIZON.
FIXED_FINAL_TIME_WITH_MIN_TIME_HORIZON
FIXED_FINAL_TIME_WITH_MIN_TIME_HORIZON.
RECEDING_HORIZON_WITH_FIXED_FINAL_TIME
RECEDING_HORIZON_WITH_FIXED_FINAL_TIME.
NlpSolverType
enum ct::optcon::NlpSolverType : uint8_t strong
The available types of NLP solvers.
Enumerator
IPOPT
SNOPT
num_types_solver
Function Documentation
loadScalarCF()
template<typename SCALAR > void ct::optcon::loadScalarCF (const std::string & filename, const std::string & scalarName, SCALAR & scalar, const std::string & termName = "")
Referenced by ct::optcon::TermSmoothAbs< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::loadConfigFile().
loadScalarOptionalCF()
template<typename SCALAR > void ct::optcon::loadScalarOptionalCF (const std::string & filename, const std::string & scalarName, SCALAR & scalar, const std::string & termName, const SCALAR & defaultValue)
loadMatrixCF()
template<typename SCALAR , int ROW, int COL> void ct::optcon::loadMatrixCF (const std::string & filename, const std::string & matrixName, Eigen::Matrix< SCALAR, ROW, COL > & matrix, const std::string & termName = "")
References i.
Referenced by ct::optcon::TermStateBarrier< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::loadConfigFile(), ct::optcon::TermLinear< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::loadConfigFile(), ct::optcon::TermQuadTracking< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::loadConfigFile(), ct::optcon::TermSmoothAbs< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::loadConfigFile(), ct::optcon::TermMixed< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::loadConfigFile(), ct::optcon::TermQuadMult< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::loadConfigFile(), and ct::optcon::TermQuadratic< STATE_DIM, CONTROL_DIM, SCALAR_EVAL, SCALAR >::loadConfigFile().
addTerm()
template<typename TERM_PTR , typename costFuncType > void ct::optcon::addTerm (const std::string & filename, std::string & currentTerm, int currentTermType, TERM_PTR term, costFuncType * costFunc, bool verbose = false)
References ct::optcon::example::verbose.
Referenced by ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::loadFromConfigFile().
addADTerm()
template<typename TERM_PTR , typename costFuncType > void ct::optcon::addADTerm (const std::string & filename, std::string & currentTerm, int currentTermType, TERM_PTR term, costFuncType * costFunc, bool verbose = false)
References ct::optcon::example::verbose.
loadMpcSettings()
void ct::optcon::loadMpcSettings (const std::string & filename, mpc_settings & settings) inline
load the mpc settings from file
Parameters
filename path of the file you wish to load from
settings the loaded settings
Todo:
make part of mpc_settings struct
References ct::optcon::mpc_settings::additionalDelayUs_, ct::optcon::mpc_settings::coldStart_, ct::optcon::mpc_settings::delayMeasurementMultiplier_, ct::optcon::mpc_settings::fixedDelayUs_, ct::optcon::mpc_settings::measureDelay_, ct::optcon::mpc_settings::minimumTimeHorizonMpc_, ct::optcon::mpc_settings::postTruncation_, ct::optcon::mpc_settings::stateForwardIntegration_, ct::optcon::mpc_settings::stateForwardIntegration_dt_, ct::optcon::mpc_settings::stateForwardIntegratorType_, and ct::optcon::mpc_settings::useExternalTiming_.