ct::optcon::example Namespace Reference
ct::optcon::example Namespace Reference
Namespaces
tpl
Classes
class ConstraintTerm1D
A simple example with an 1d constraint.
class ConstraintTerm2D
A simple example with a 2d constraint.
class DiehlSystem
Dynamics class for the Diehl system.
class DiehlSystemLinear
Linear system class for the Diehl system.
class Dynamics
Dynamics class for the GNMS unit test, slightly nonlinear dynamics.
class LinearizedSystem
Linear system class for the GNMS unit test.
class MatFilesGenerator
class MIMOIntegrator
Dynamics class for the GNMS unit test.
class MIMOIntegratorLinear
Linear system class for the GNMS unit test.
class OscDms
class OscillatorDms
class PureStateConstraint_Example
A pure state constraint term.
class SpringLoadedMass
Dynamics class for the GNMS unit test.
class SpringLoadedMassLinear
Linear system class for the GNMS unit test.
class StateInputConstraint_Example
A state input constraint term.
class TestTerm
Typedefs
typedef tpl::LinearOscillator< double > LinearOscillator
typedef tpl::LinearOscillatorLinear< double > LinearOscillatorLinear
Functions
TEST (ConstraintComparison, comparisonAnalyticAD)
TEST (pureStateConstraintTest, pureStateConstraintTest)
TEST (stateInputConstraintTest, stateInputConstraintTest)
TEST (AD_TEST_TIME_VAR, AD_TEST_TIME_VAR)
template<size_t state_dim, size_t control_dim>
void compareCostFunctionOutput (CostFunctionQuadratic< state_dim, control_dim > &costFunction, CostFunctionQuadratic< state_dim, control_dim > &costFunction2)
This method is called from different unit tests in order to compare the cost, first and second order gradients of two cost functions.
template<size_t state_dim, size_t control_dim>
void printCostFunctionOutput (CostFunctionQuadratic< state_dim, control_dim > &costFunction, CostFunctionQuadratic< state_dim, control_dim > &costFunction2)
TEST (CostFunctionTest, ADQuadraticTest)
TEST (CostFunctionTest, ADQuadMultTest)
TEST (CostFunctionTest, TrackingTermTest)
TEST (CostFunctionTest, TermSmoothAbsTest)
TEST (LoadCostFromFileTest, LoadAnalyticalDirect)
Test case: trying to load analytical cost function directly from file.
TEST (LoadCostFromFileTest, LoadAnalyticalViaTerms)
Test case: trying to load analytical cost terms separately and then add them cost function.
TEST (LoadCostFromFileTest, LoadADViaTerms)
Test case: trying to load AD cost terms separately and then add them to the cost function.
TEST (LoadCostFromFileTest, LoadADDirect1)
Test case: trying to load AD cost directly, but calling standard constructor first.
TEST (LoadCostFromFileTest, LoadADDirect2)
Test case: trying to load AD cost directly.
TEST (DmsTest, OscDmsTest)
TEST (DmsTest, OscillatorDmsTestAllVariants)
TEST (LQRTest, DARETest)
TEST (LQRTest, quadTest)
TEST (MPCTestA, ForwardIntegratorTest)
TEST (MPCTestB, NLOC_MPC_DoublePrecision)
TEST (LinearSystemsSolverComparison, LinearSystemsSolverComparison)
TEST (LinearSystemsTest, NLOCSolverTest)
TEST (ILQRTestA, InstancesComparison)
TEST (ILQRTestB, MultiThreadingTest)
TEST (ILQRTestC, PolicyComparison)
TEST (NLOCTest, NonlinearSystemAlgorithmComparison)
std::shared_ptr< CostFunctionQuadratic< state_dim, control_dim > > createCostFunction (Eigen::Vector2d &x_final)
Create a cost function for the GNMS unit test.
void symplecticTest ()
TEST (SystemInterfaceTest, ContinuousSystemInterface)
TEST (SystemInterfaceTest, DiscreteSystemInterface)
std::shared_ptr< CostFunctionQuadratic< 1, 1 > > createDiehlCostFunction (const core::StateVector< 1 > &x_final)
create a cost function of appropriate Dimensions for the Diehl system
template<size_t state_dim, size_t control_dim>
std::shared_ptr< CostFunctionQuadratic< state_dim, control_dim > > createMIMOIntegratorCostFunction (const core::StateVector< state_dim > &x_final)
std::shared_ptr< CostFunctionQuadratic< 2, 1 > > createSpringLoadedMassCostFunction (const core::StateVector< 2 > &x_final)
Variables
const bool verbose = true
const size_t state_dim = 3
const size_t control_dim = 3
const double kStiffness = 1
Typedef Documentation
typedef tpl::LinearOscillator<double> ct::optcon::example::LinearOscillator
Examples:
LinearSystemTest.h.
typedef tpl::LinearOscillatorLinear<double> ct::optcon::example::LinearOscillatorLinear
Examples:
LinearSystemTest.h.
Function Documentation
ct::optcon::example::TEST (ConstraintComparison , comparisonAnalyticAD)
Examples:
ConstraintComparison.h, ConstraintTest.h, LinearSystemTest.h, LqrTest.h, NonlinearSystemTest.h, oscDMSTest.cpp, and oscDMSTestAllVariants.cpp.
References ASSERT_TRUE.
Referenced by TEST().
ct::optcon::example::TEST (pureStateConstraintTest , pureStateConstraintTest)
References ASSERT_TRUE, and i.
ct::optcon::example::TEST (stateInputConstraintTest , stateInputConstraintTest)
References ASSERT_TRUE.
ct::optcon::example::TEST (AD_TEST_TIME_VAR , AD_TEST_TIME_VAR)
References ASSERT_TRUE, t, u, and x.
template<size_t state_dim, size_t control_dim> void ct::optcon::example::compareCostFunctionOutput (CostFunctionQuadratic< state_dim, control_dim > & costFunction, CostFunctionQuadratic< state_dim, control_dim > & costFunction2)
This method is called from different unit tests in order to compare the cost, first and second order gradients of two cost functions.
Parameters
costFunction the first cost function to be compared
costFunction2 the second cost function to be compared
References ASSERT_NEAR, ASSERT_TRUE, ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminal(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediate(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminal(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediate(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminal(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminal(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediate(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminal().
Referenced by TEST().
template<size_t state_dim, size_t control_dim> void ct::optcon::example::printCostFunctionOutput (CostFunctionQuadratic< state_dim, control_dim > & costFunction, CostFunctionQuadratic< state_dim, control_dim > & costFunction2)
References ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeTerminal(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediate(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeTerminal(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateIntermediate(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::evaluateTerminal(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeIntermediate(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateControlDerivativeTerminal(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminal(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediate(), and ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminal().
ct::optcon::example::TEST (CostFunctionTest , ADQuadraticTest)
References ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::addFinalADTerm(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addFinalTerm(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateADTerm(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateTerm(), ASSERT_TRUE, ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::clone(), compareCostFunctionOutput(), ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlDerivativeIntermediate(), ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::controlSecondDerivativeIntermediate(), FAIL, i, ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::initialize(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeIntermediate(), ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateDerivativeTerminal(), ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeIntermediate(), ct::optcon::CostFunctionAnalytical< STATE_DIM, CONTROL_DIM, SCALAR >::stateSecondDerivativeTerminal(), u, and x.
ct::optcon::example::TEST (CostFunctionTest , ADQuadMultTest)
References ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateADTerm(), ct::optcon::CostFunctionQuadratic< STATE_DIM, CONTROL_DIM, SCALAR >::addIntermediateTerm(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::clone(), compareCostFunctionOutput(), FAIL, i, ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::initialize(), ct::optcon::CostFunction< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), ct::optcon::CostFunctionAD< STATE_DIM, CONTROL_DIM, SCALAR >::setCurrentStateAndControl(), t, u, and x.
ct::optcon::example::TEST (CostFunctionTest , TrackingTermTest)
References ASSERT_TRUE, control_dim, i, ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::push_back(), state_dim, t, u, and x.
ct::optcon::example::TEST (CostFunctionTest , TermSmoothAbsTest)
Test the TermSmoothAbs term for first and second order derivatives
References ASSERT_TRUE, compareCostFunctionOutput(), control_dim, i, state_dim, t, u, and x.
ct::optcon::example::TEST (LoadCostFromFileTest , LoadAnalyticalDirect)
Test case: trying to load analytical cost function directly from file.
References ASSERT_TRUE, costFunctionFile, t, and verbose.
ct::optcon::example::TEST (LoadCostFromFileTest , LoadAnalyticalViaTerms)
Test case: trying to load analytical cost terms separately and then add them cost function.
References ASSERT_TRUE, costFunctionFile, t, and verbose.
ct::optcon::example::TEST (LoadCostFromFileTest , LoadADViaTerms)
Test case: trying to load AD cost terms separately and then add them to the cost function.
References ASSERT_TRUE, costFunctionFile, t, and verbose.
ct::optcon::example::TEST (LoadCostFromFileTest , LoadADDirect1)
Test case: trying to load AD cost directly, but calling standard constructor first.
References ASSERT_TRUE, costFunctionFile, t, and verbose.
ct::optcon::example::TEST (LoadCostFromFileTest , LoadADDirect2)
Test case: trying to load AD cost directly.
References ASSERT_TRUE, costFunctionFile, t, and verbose.
ct::optcon::example::TEST (DmsTest , OscDmsTest)
References ct::optcon::example::OscDms::compareIpoptSolutions(), ct::optcon::example::OscDms::compareSnoptSolutions(), ct::optcon::example::OscDms::getIpoptMatlabTrajectories(), ct::optcon::example::OscDms::getIpoptSolution(), ct::optcon::example::OscDms::getSnoptMatlabTrajectories(), ct::optcon::example::OscDms::getSnoptSolution(), and ct::optcon::example::OscDms::initialize().
ct::optcon::example::TEST (DmsTest , OscillatorDmsTestAllVariants)
References ct::optcon::DmsSettings::absErrTol_, ct::optcon::DmsSettings::costEvaluationType_, ct::optcon::DmsSettings::dt_sim_, ct::optcon::example::OscillatorDms::getSolution(), ct::optcon::DmsSettings::h_min_, ct::optcon::example::OscillatorDms::initialize(), ct::optcon::DmsSettings::integrationType_, ct::optcon::IPOPT, ct::optcon::DmsSettings::N_, ct::optcon::DmsSettings::nThreads_, ct::optcon::DmsSettings::objectiveType_, ct::optcon::DmsSettings::relErrTol_, ct::optcon::DmsSettings::RK4, ct::optcon::SNOPT, ct::optcon::DmsSettings::solverSettings_, ct::optcon::NlpSolverSettings::solverType_, ct::optcon::DmsSettings::splineType_, and ct::optcon::DmsSettings::T_.
ct::optcon::example::TEST (LQRTest , DARETest)
References ASSERT_LT, and ct::optcon::DARE< STATE_DIM, CONTROL_DIM, SCALAR >::computeSteadyStateRiccatiMatrix().
ct::optcon::example::TEST (LQRTest , quadTest)
References ASSERT_LT, ASSERT_TRUE, ct::optcon::LQR< STATE_DIM, CONTROL_DIM >::compute(), i, and TEST().
ct::optcon::example::TEST (MPCTestA , ForwardIntegratorTest)
Test the MPC forward integrator
required for this test
Run the first MPC cycle, in which the pre-integrator should not be active at all. after one mpc cycle the solution must still be the same (time horizon unchanged, state unchanged)
Test the forward integration scheme employing a 'custom controller'. In this test,
we select the custom controller to be equal to the previously optimized policy
we integrate systematically across shifting time intervals
the integrated solutions need to match the original trajectories with numerical accuracy.
Warning
This test is only reasonnable for dt_sim = 1, and is generally problematic since the solver's forward integration is implemented step-wise.
References ASSERT_EQ, ASSERT_NEAR, ct::optcon::NLOptConSettings::closedLoopShooting, ct::optcon::NLOptConSettings::computeK(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), ct::optcon::NLOptConSettings::discretization, ct::optcon::MPC< OPTCON_SOLVER >::doForwardIntegration(), ct::optcon::NLOptConSettings::dt, FAIL, ct::optcon::MPC< OPTCON_SOLVER >::finishIteration(), ct::core::SensitivityApproximationSettings::FORWARD_EULER, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::getFeedforwardTrajectory(), ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::getReferenceStateTrajectory(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getStateTrajectory(), i, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_sim, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::mpc_settings::postTruncation_, ct::optcon::MPC< OPTCON_SOLVER >::prepareIteration(), ct::optcon::NLOptConSettings::printSummary, ct::optcon::MPC< OPTCON_SOLVER >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), ct::optcon::mpc_settings::stateForwardIntegration_, ct::optcon::mpc_settings::stateForwardIntegration_dt_, ct::optcon::mpc_settings::stateForwardIntegratorType_, t, timeHorizon, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::uff(), and x0.
ct::optcon::example::TEST (MPCTestB , NLOC_MPC_DoublePrecision)
References ct::optcon::LineSearchSettings::active, ct::optcon::mpc_settings::additionalDelayUs_, ASSERT_GT, ASSERT_LT, ct::optcon::NLOptConSettings::closedLoopShooting, ct::optcon::mpc_settings::coldStart_, ct::optcon::NLOptConSettings::computeK(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), DATA_DIR_MPC, ct::optcon::NLOptConSettings::debugPrint, ct::optcon::mpc_settings::delayMeasurementMultiplier_, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::eval(), FAIL, ct::optcon::MPC< OPTCON_SOLVER >::finishIteration(), ct::optcon::FIXED_FINAL_TIME, ct::optcon::mpc_settings::fixedDelayUs_, ct::core::SensitivityApproximationSettings::FORWARD_EULER, ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::front(), ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::getReferenceStateTrajectory(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), i, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_shot, ct::optcon::NLOptConSettings::K_sim, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::mpc_settings::measureDelay_, ct::optcon::NLOptConSettings::min_cost_improvement, ct::optcon::mpc_settings::mpc_mode, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::NLOptConSettings::nThreadsEigen, ct::optcon::mpc_settings::postTruncation_, ct::optcon::MPC< OPTCON_SOLVER >::prepareIteration(), ct::optcon::MPC< OPTCON_SOLVER >::printMpcSummary(), ct::optcon::NLOptConSettings::printSummary, ct::optcon::MPC< OPTCON_SOLVER >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), ct::optcon::mpc_settings::stateForwardIntegration_, ct::optcon::mpc_settings::stateForwardIntegration_dt_, ct::optcon::mpc_settings::stateForwardIntegratorType_, t, timeHorizon, ct::optcon::MPC< OPTCON_SOLVER >::timeHorizonReached(), ct::optcon::mpc_settings::useExternalTiming_, and x0.
ct::optcon::example::TEST (LinearSystemsSolverComparison , LinearSystemsSolverComparison)
This unit test considers a variety of different solver/algorithm options for NLOC, and explicitly compares HPIPM and GNRiccati solvers against each other.
run two iterations to solve LQ problem
run two iterations to solve LQ problem
retrieve summaries
check that all logs from both solvers are identical
References ct::optcon::LineSearchSettings::active, ASSERT_NEAR, ct::optcon::NLOptConSettings::closedLoopShooting, ct::optcon::NLOptConSettings::computeK(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), control_dim, SummaryAllIterations< SCALAR >::defect_l1_norms, SummaryAllIterations< SCALAR >::defect_l2_norms, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSettings::epsilon, ct::optcon::NLOptConSettings::fixedHessianCorrection, ct::core::SensitivityApproximationSettings::FORWARD_EULER, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getBackend(), ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_shot, ct::optcon::NLOptConSettings::K_sim, kStiffness, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqocp_solver, SummaryAllIterations< SCALAR >::lu_norms, SummaryAllIterations< SCALAR >::lx_norms, SummaryAllIterations< SCALAR >::merits, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::NLOptConSettings::printSummary, ct::optcon::NLOptConSettings::recordSmallestEigenvalue, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), state_dim, ct::optcon::NLOptConSettings::useSensitivityIntegrator, and x0.
ct::optcon::example::TEST (LinearSystemsTest , NLOCSolverTest)
run two iterations to solve LQ problem
retrieve summary of the optimization
check that the policy improved in the first iteration
check that we are converged after the first iteration
References ct::optcon::LineSearchSettings::active, ASSERT_GT, ASSERT_LT, ct::optcon::NLOptConSettings::closedLoopShooting, ct::optcon::NLOptConSettings::computeK(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), control_dim, SummaryAllIterations< SCALAR >::defect_l1_norms, SummaryAllIterations< SCALAR >::defect_l2_norms, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSettings::epsilon, ct::optcon::NLOptConSettings::fixedHessianCorrection, ct::core::SensitivityApproximationSettings::FORWARD_EULER, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getBackend(), ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_shot, ct::optcon::NLOptConSettings::K_sim, kStiffness, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqocp_solver, SummaryAllIterations< SCALAR >::lu_norms, SummaryAllIterations< SCALAR >::lx_norms, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::NLOptConSettings::printSummary, ct::optcon::NLOptConSettings::recordSmallestEigenvalue, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), state_dim, ct::optcon::NLOptConSettings::useSensitivityIntegrator, and x0.
ct::optcon::example::TEST (ILQRTestA , InstancesComparison)
check that if retrieving solution now, we exactly get back the init guess.
References ct::optcon::LineSearchSettings::active, ASSERT_EQ, ASSERT_NEAR, ct::optcon::NLOptConSettings::closedLoopShooting, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), costFunctionFile, ct::optcon::LineSearchSettings::debugPrint, ct::optcon::NLOptConSettings::debugPrint, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSettings::epsilon, FAIL, ct::optcon::NLOptConSettings::fixedHessianCorrection, ct::core::SensitivityApproximationSettings::FORWARD_EULER, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), i, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_shot, ct::optcon::NLOptConSettings::K_sim, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::min_cost_improvement, NLOC_TEST_DIR, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::NLOptConSettings::printSummary, ct::optcon::NLOptConSettings::recordSmallestEigenvalue, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), and x0.
ct::optcon::example::TEST (ILQRTestB , MultiThreadingTest)
References ct::optcon::LineSearchSettings::active, ASSERT_EQ, ASSERT_LT, ct::core::SensitivityApproximationSettings::BACKWARD_EULER, ct::optcon::NLOptConSettings::closedLoopShooting, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), costFunctionFile, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSettings::epsilon, FAIL, ct::optcon::NLOptConSettings::fixedHessianCorrection, ct::core::SensitivityApproximationSettings::FORWARD_EULER, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getBackend(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getControlTrajectory(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getStateTrajectory(), i, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::min_cost_improvement, NLOC_TEST_DIR, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::NLOptConSettings::printSummary, ct::optcon::NLOptConSettings::recordSmallestEigenvalue, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::size(), ct::core::SensitivityApproximationSettings::TUSTIN, and x0.
ct::optcon::example::TEST (ILQRTestC , PolicyComparison)
References ct::optcon::LineSearchSettings::active, ASSERT_LT, ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::back(), ct::optcon::NLOptConSettings::closedLoopShooting, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), costFunctionFile, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSettings::epsilon, FAIL, ct::optcon::NLOptConSettings::fixedHessianCorrection, ct::core::SensitivityApproximationSettings::FORWARD_EULER, ct::optcon::NLOptConSettings::getSimulationTimestep(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getStateTrajectory(), i, ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::min_cost_improvement, NLOC_TEST_DIR, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::NLOptConSettings::printSummary, ct::optcon::NLOptConSettings::recordSmallestEigenvalue, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), and x0.
ct::optcon::example::TEST (NLOCTest , NonlinearSystemAlgorithmComparison)
References ASSERT_NEAR, ct::optcon::NLOptConSettings::computeK(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), costFunctionFile, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getControlTrajectory(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getStateTrajectory(), i, ct::optcon::NLOptConSettings::load(), ct::core::loadMatrix(), ct::core::loadScalar(), NLOC_TEST_DIR, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::core::DiscreteTrajectoryBase< T, Alloc, SCALAR >::size(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), and x0.
std::shared_ptr<CostFunctionQuadratic<state_dim, control_dim> > ct::optcon::example::createCostFunction (Eigen::Vector2d & x_final)
Create a cost function for the GNMS unit test.
Examples:
SymplecticTest.h.
Referenced by symplecticTest().
void ct::optcon::example::symplecticTest ()
Examples:
SymplecticTest.h.
References ct::optcon::LineSearchSettings::active, ct::optcon::NLOptConSettings::closedLoopShooting, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::configure(), control_dim, createCostFunction(), ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSettings::epsilon, ct::optcon::NLOptConSettings::fixedHessianCorrection, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getControlTrajectory(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getStateTrajectory(), i, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_shot, ct::optcon::NLOptConSettings::K_sim, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::loggingPrefix, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::min_cost_improvement, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::NLOptConSettings::printSummary, ct::optcon::NLOptConSettings::recordSmallestEigenvalue, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::runIteration(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), state_dim, ct::optcon::NLOptConSettings::useSensitivityIntegrator, and x0.
Referenced by main().
ct::optcon::example::TEST (SystemInterfaceTest , ContinuousSystemInterface)
References ASSERT_TRUE, control_dim, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSettings::getSimulationTimestep(), i, ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::K_sim, state_dim, ct::optcon::NLOptConSettings::timeVaryingDiscretization, and ct::optcon::NLOptConSettings::useSensitivityIntegrator.
ct::optcon::example::TEST (SystemInterfaceTest , DiscreteSystemInterface)
std::shared_ptr<CostFunctionQuadratic<1, 1> > ct::optcon::example::createDiehlCostFunction (const core::StateVector< 1 > & x_final)
create a cost function of appropriate Dimensions for the Diehl system
template<size_t state_dim, size_t control_dim> std::shared_ptr<CostFunctionQuadratic<state_dim, control_dim> > ct::optcon::example::createMIMOIntegratorCostFunction (const core::StateVector< state_dim > & x_final)
std::shared_ptr<CostFunctionQuadratic<2, 1> > ct::optcon::example::createSpringLoadedMassCostFunction (const core::StateVector< 2 > & x_final)
Referenced by TEST().
Variable Documentation
const bool ct::optcon::example::verbose = true
Examples:
ConstraintComparison.h, ConstraintTest.h, NLOC.cpp, NLOC_boxConstrained.cpp, NLOC_generalConstrained.cpp, NLOC_MPC.cpp, and switched_continuous_optcon.cpp.
Referenced by ct::optcon::addADTerm(), ct::optcon::addTerm(), ct::optcon::OptConSolver< DmsSolver< STATE_DIM, CONTROL_DIM, SCALAR >, DmsPolicy< STATE_DIM, CONTROL_DIM, SCALAR >, DmsSettings, STATE_DIM, CONTROL_DIM, SCALAR >::configureFromFile(), ct::optcon::LineSearchSettings::load(), ct::optcon::LQOCSolverSettings::load(), ct::optcon::DmsSettings::load(), ct::optcon::NlpSolverSettings::load(), ct::optcon::NLOptConSettings::load(), main(), TEST(), and TEST().
const size_t ct::optcon::example::state_dim = 3
Examples:
ConstraintComparison.h, ConstraintTest.h, LinearSystemTest.h, and SymplecticTest.h.
Referenced by ct::optcon::example::MIMOIntegrator< state_dim, control_dim >::computeControlledDynamics(), symplecticTest(), and TEST().
const size_t ct::optcon::example::control_dim = 3
Examples:
ConstraintComparison.h, ConstraintTest.h, LinearSystemTest.h, and SymplecticTest.h.
Referenced by ct::optcon::example::MIMOIntegrator< state_dim, control_dim >::computeControlledDynamics(), symplecticTest(), and TEST().
const double ct::optcon::example::kStiffness = 1
Examples:
LinearSystemTest.h, and SymplecticTest.h.
Referenced by ct::optcon::example::tpl::LinearOscillatorLinear< SCALAR >::getDerivativeState(), ct::optcon::example::LinearizedSystem::getDerivativeState(), and TEST().