/home/adrl/code/src/control-toolbox/ct_optcon/examples/NLOC_generalConstrained.cpp File Reference
NLOC_generalConstrained.cpp File Reference
#include <ct/optcon/optcon.h>
#include "exampleDir.h"
#include "plotResultsOscillator.h"
Classes
class ConstraintTerm1D
A simple 1d constraint term.
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Examples:
NLOC_generalConstrained.cpp.
References ct::optcon::LineSearchSettings::active, ct::optcon::NLOptConSettings::computeK(), ct::optcon::LineSearchSettings::debugPrint, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqoc_solver_settings, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::min_cost_improvement, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::LQOCSolverSettings::num_lqoc_iterations, oscillatorDynamics(), ct::optcon::NLOptConSettings::printSummary, ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setGeneralConstraints(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::time(), timeHorizon, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::uff(), ct::optcon::example::verbose, w_n, x0, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::x_ref(), and zeta.