/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/examples/NLOC_boxConstrained.cpp File Reference
NLOC_boxConstrained.cpp File Reference
#include <ct/optcon/optcon.h>
#include "exampleDir.h"
#include "plotResultsOscillator.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Examples:
NLOC_boxConstrained.cpp.
References ct::optcon::NLOptConSettings::computeK(), ct::core::tpl::SecondOrderSystem< class >::CONTROL_DIM, control_dim, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), ct::optcon::NLOptConSettings::integrator, ct::optcon::NLOptConSettings::lqoc_solver_settings, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::LQOCSolverSettings::num_lqoc_iterations, oscillatorDynamics(), ct::optcon::NLOptConSettings::printSummary, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setInputBoxConstraints(), ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setStateBoxConstraints(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), ct::core::tpl::SecondOrderSystem< class >::STATE_DIM, state_dim, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::time(), timeHorizon, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::uff(), ct::optcon::example::verbose, w_n, x0, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::x_ref(), and zeta.