/home/adrl/code/src/control-toolbox/ct_optcon/examples/NLOC.cpp File Reference
NLOC.cpp File Reference
#include <ct/optcon/optcon.h>
#include "exampleDir.h"
#include "plotResultsOscillator.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Examples:
NLOC.cpp.
References ct::optcon::NLOptConSettings::computeK(), ct::core::tpl::SecondOrderSystem< class >::CONTROL_DIM, control_dim, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), ct::optcon::NLOptConSettings::load(), oscillatorDynamics(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), ct::core::tpl::SecondOrderSystem< class >::STATE_DIM, state_dim, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::time(), timeHorizon, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::uff(), ct::optcon::example::verbose, w_n, x0, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::x_ref(), and zeta.