/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/examples/plotResultsOscillator.h File Reference
plotResultsOscillator.h File Reference
Functions
template<size_t STATE_DIM, size_t CONTROL_DIM>
void plotResultsOscillator (const ct::core::StateVectorArray< STATE_DIM > &stateArray, const ct::core::ControlVectorArray< CONTROL_DIM > &controlArray, const ct::core::TimeArray &timeArray)
Function Documentation
plotResultsOscillator()
template<size_t STATE_DIM, size_t CONTROL_DIM> void plotResultsOscillator (const ct::core::StateVectorArray< STATE_DIM > & stateArray, const ct::core::ControlVectorArray< CONTROL_DIM > & controlArray, const ct::core::TimeArray & timeArray)
References ct::core::plot::figure(), ct::core::plot::ion(), ct::core::plot::plot(), ct::core::plot::show(), ct::core::plot::subplot(), and ct::core::plot::title().