ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR > Struct Template Reference
ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR > Struct Template Reference
Settings for setting up a StateObserver.
#include <FilterSettings.h>
Public Member Functions
StateObserverSettings ()
default constructor for the state Observer settings
bool parametersOk () const
check if the currently set parameters are meaningful
void print () const
print the current settings
void load (const std::string &filename, bool verbose, const std::string &ns)
load settings from file
Public Attributes
ct::core::OutputStateMatrix< OUTPUT_DIM, STATE_DIM, SCALAR > C
ct::core::StateMatrix< STATE_DIM, SCALAR > Q
ct::core::OutputMatrix< OUTPUT_DIM, SCALAR > R
ct::core::StateMatrix< STATE_DIM, SCALAR > dFdv
Detailed Description
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double>
struct ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >
Settings for setting up a StateObserver.
The StateObserver settings are designed to make the initialization smoother and possible through a file configuration.
Constructor & Destructor Documentation
StateObserverSettings()
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::StateObserverSettings () inline
default constructor for the state Observer settings
Member Function Documentation
parametersOk()
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> bool ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::parametersOk () const inline
check if the currently set parameters are meaningful
print()
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> void ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::print () const inline
print the current settings
Referenced by ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::load(), ct::optcon::SteadyStateKalmanFilterSettings< STATE_DIM, SCALAR >::load(), ct::optcon::ExtendedKalmanFilterSettings< STATE_DIM, SCALAR >::load(), and ct::optcon::UnscentedKalmanFilterSettings< STATE_DIM, SCALAR >::load().
load()
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> void ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::load (const std::string & filename, bool verbose, const std::string & ns) inline
load settings from file
References ct::core::loadMatrix(), and ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::print().
Member Data Documentation
C
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> ct::core::OutputStateMatrix<OUTPUT_DIM, STATE_DIM, SCALAR> ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::C
Observation matrix C time.
Q
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> ct::core::StateMatrix<STATE_DIM, SCALAR> ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::Q
Weighing matrix Q.
R
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> ct::core::OutputMatrix<OUTPUT_DIM, SCALAR> ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::R
Weighing matrix R.
dFdv
template<size_t OUTPUT_DIM, size_t STATE_DIM, typename SCALAR = double> ct::core::StateMatrix<STATE_DIM, SCALAR> ct::optcon::StateObserverSettings< OUTPUT_DIM, STATE_DIM, SCALAR >::dFdv
The documentation for this struct was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/include/ct/optcon/filter/FilterSettings.h