/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_optcon/examples/switched_systems_optcon/switched_continuous_optcon.cpp File Reference
switched_continuous_optcon.cpp File Reference
#include <ct/optcon/optcon.h>
#include "TestLinearSystem.h"
#include "StateSumConstraint.h"
#include "plotResultsSwitched.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Examples:
switched_continuous_optcon.cpp.
References PhaseSequence< std::size_t, double >::addPhase(), ct::optcon::NLOptConSettings::computeK(), ct::optcon::LineSearchSettings::debugPrint, ct::optcon::NLOptConSettings::discretization, ct::optcon::NLOptConSettings::dt, ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::getSolution(), ct::optcon::NLOptConSettings::integrator, ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, class >::LinearSystemPtr, ct::optcon::NLOptConSettings::lineSearchSettings, ct::optcon::NLOptConSettings::lqoc_solver_settings, ct::optcon::NLOptConSettings::lqocp_solver, ct::optcon::NLOptConSettings::max_iterations, ct::optcon::NLOptConSettings::meritFunctionRhoConstraints, ct::optcon::NLOptConSettings::min_cost_improvement, ct::optcon::NLOptConSettings::nlocp_algorithm, ct::optcon::NLOptConSettings::nThreads, ct::optcon::LQOCSolverSettings::num_lqoc_iterations, plotResults(), ct::optcon::NLOptConSettings::printSummary, ct::optcon::OptConProblemBase< STATE_DIM, CONTROL_DIM, SYSTEM_T, LINEAR_SYSTEM_T, LINEARIZER_T, SCALAR >::setGeneralConstraints(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::setInitialGuess(), ct::optcon::NLOptConSolver< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR, CONTINUOUS >::solve(), ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::time(), timeHorizon, ct::optcon::LineSearchSettings::type, ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::uff(), ct::optcon::example::verbose, x0, and ct::core::StateFeedbackController< STATE_DIM, CONTROL_DIM, SCALAR >::x_ref().