/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/test/AutoDiffLinearizerTest.cpp File Reference
AutoDiffLinearizerTest.cpp File Reference
#include <ct/core/core.h>
#include "system/TestNonlinearSystem.h"
#include "system/TestDiscreteNonlinearSystem.h"
#include <gtest/gtest.h>
Functions
TEST (AutoDiffLinearizerTest, SystemLinearizerComparison)
TEST (AutoDiffDiscreteLinearizerTest, DiscreteSystemLinearizerComparison)
TEST (AutoDiffLinearizerTestMP, SystemLinearizerComparisonMP)
int main (int argc, char **argv)
Function Documentation
TEST() [1/3]
TEST (AutoDiffLinearizerTest , SystemLinearizerComparison)
Examples:
AutoDiffLinearizerTest.cpp.
References control_dim, ct::core::tpl::TestNonlinearSystem< SCALAR >::CONTROL_DIM, ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), i, state_dim, ct::core::tpl::TestNonlinearSystem< SCALAR >::STATE_DIM, t, u, w_n, and x.
TEST() [2/3]
TEST (AutoDiffDiscreteLinearizerTest , DiscreteSystemLinearizerComparison)
References control_dim, ct::core::tpl::TestDiscreteNonlinearSystem< SCALAR >::CONTROL_DIM, ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), i, n, state_dim, ct::core::tpl::TestDiscreteNonlinearSystem< SCALAR >::STATE_DIM, u, and x.
TEST() [3/3]
TEST (AutoDiffLinearizerTestMP , SystemLinearizerComparisonMP)
References ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::clone(), control_dim, ct::core::tpl::TestNonlinearSystem< SCALAR >::CONTROL_DIM, i, n, state_dim, ct::core::tpl::TestNonlinearSystem< SCALAR >::STATE_DIM, t, u, w_n, and x.
main()
int main (int argc, char ** argv)
Examples:
AutoDiffLinearizerTest.cpp.