/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/CMakeLists.txt File Reference
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/CMakeLists.txt File Reference
Functions
option (gmock_build_tests"Build all of Google Mock's own tests."OFF) if(EXISTS"$
gtest CMakeLists txt set (gtest_dir gtest) else() set(gtest_dir../googletest) endif() include("$
cmake hermetic_build cmake OPTIONAL if (COMMAND pre_project_set_up_hermetic_build) pre_project_set_up_hermetic_build() endif() if(CMAKE_VERSION VERSION_LESS 3.0) project(gmock CXX C) else() cmake_policy(SET CMP0048 NEW) project(gmock VERSION $
Function Documentation
option (gmock_build_tests"Build all of Google Mock's own tests." OFF)
Referenced by if().
gtest CMakeLists txt set (gtest_dir gtest)
cmake hermetic_build cmake OPTIONAL if (COMMAND pre_project_set_up_hermetic_build)
References cmake_minimum_required(), gmock_output_test::COMMAND, endif(), gtest, GTEST_HAS_PTHREAD, include_directories(), option(), gtest_skip_environment_check_output_test::OUTPUT, set_target_properties(), target_link_libraries(), test(), and the.