/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/CMakeLists.txt File Reference
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/CMakeLists.txt File Reference
Functions
option (gtest_force_shared_crt"Use shared (DLL) run-time lib even when Google Test is built as static lib."OFF) option(gtest_build_tests"Build all of gtest's own tests."OFF) option(gtest_build_samples"Build gtest's sample programs."OFF) option(gtest_disable_pthreads"Disable uses of pthreads in gtest."OFF) option(gtest_hide_internal_symbols"Build gtest with internal symbols hidden in shared libraries."OFF) include(cmake/hermetic_build.cmake OPTIONAL) if(COMMAND pre_project_set_up_hermetic_build) pre_project_set_up_hermetic_build() endif() if(CMAKE_VERSION VERSION_LESS 3.0) project(gtest CXX C) set(PROJECT_VERSION $
else () cmake_policy(SET CMP0048 NEW) project(gtest VERSION $
LANGUAGES CXX C endif () cmake_minimum_required(VERSION 2.6.4) if(POLICY CMP0063) cmake_policy(SET CMP0063 NEW) endif(POLICY CMP0063) if(COMMAND set_up_hermetic_build) set_up_hermetic_build() endif() if(CMAKE_PROJECT_NAME STREQUAL"gtest"OR CMAKE_PROJECT_NAME STREQUAL"googletest-distribution") option(BUILD_SHARED_LIBS"Build shared libraries (DLLs)."OFF) else() mark_as_advanced(gtest_force_shared_crt gtest_build_tests gtest_build_samples gtest_disable_pthreads gtest_hide_internal_symbols) endif() if(gtest_hide_internal_symbols) set(CMAKE_CXX_VISIBILITY_PRESET hidden) set(CMAKE_VISIBILITY_INLINES_HIDDEN 1) endif() include(cmake/internal_utils.cmake) config_compiler_and_linker() if(INSTALL_GTEST) include(CMakePackageConfigHelpers) set(cmake_package_name GTest) set(targets_export_name $
Targets CACHE INTERNAL set (generated_dir"${CMAKE_CURRENT_BINARY_DIR}/generated"CACHE INTERNAL"") set(cmake_files_install_dir"$
Function Documentation
option (gtest_force_shared_crt"Use shared (DLL) run-time lib even when Google Test is built as static lib." OFF)
else ()
Referenced by testing::internal::TEST().
LANGUAGES CXX C endif ()
Referenced by find_package(), testing::internal::GetTimeInMillis(), if(), macro(), and set().
Targets CACHE INTERNAL set (generated_dir"${CMAKE_CURRENT_BINARY_DIR}/generated"CACHE INTERNAL"")
References versiongenerate::config_file, endif(), gtest, include_directories(), list, googletest-output-test::message, on, gtest_skip_environment_check_output_test::OUTPUT, gmock_output_test::output, set_target_properties(), target_link_libraries(), test(), the, and versiongenerate::version_file.