ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR > Class Template Reference
ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR > Class Template Reference
This class can integrate a controlled system Furthermore, it provides first order derivatives with respect to initial state and control.
#include <SensitivityIntegrator.h>
Public Types
typedef ct::core::ControlVector< CONTROL_DIM, SCALAR > control_vector_t
typedef StateMatrix< STATE_DIM, SCALAR > state_matrix_t
state Jacobian type
typedef ControlMatrix< CONTROL_DIM, SCALAR > control_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
input Jacobian type
typedef Eigen::Matrix< SCALAR, STATE_DIM, STATE_DIM+CONTROL_DIM > sensitivities_matrix_t
Public Types inherited from ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR >
typedef std::shared_ptr< ControlVectorArray< CONTROL_DIM, SCALAR > > ControlVectorArrayPtr
Public Types inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef Base::time_t time_t
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef StateMatrix< STATE_DIM, SCALAR > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::time_t time_t
Public Types inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef int time_t
the type of the time variable
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Member Functions
SensitivityIntegrator (const SCALAR dt, const std::shared_ptr< ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> &linearSystem, const std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller, const ct::core::IntegrationType stepperType=ct::core::IntegrationType::EULERCT, bool timeVarying=true)
Constructor.
~SensitivityIntegrator () override=default
Destroys the object.
void setStepper (const ct::core::IntegrationType stepperType)
Initializes the steppers.
virtual void setLinearSystem (const std::shared_ptr< ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> &linearSystem) override
Prepares the integrator to provide first order sensitivity generation by setting a linearsystem, enabling state caching and settings up the function objects.
virtual void setTimeDiscretization (const SCALAR &dt) override
update the time discretization
void integrateSensitivity (const size_t k, const size_t numSteps, state_matrix_t &A, state_control_matrix_t &B)
Integrates the sensitivity ODE of the integrator with respect to the initial state x0.
virtual void getAandB (const StateVector< STATE_DIM, SCALAR > &x, const ControlVector< CONTROL_DIM, SCALAR > &u, const StateVector< STATE_DIM, SCALAR > &x_next, const int n, const size_t numSteps, state_matrix_t &A, state_control_matrix_t &B) override
Public Member Functions inherited from ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR >
Sensitivity ()
virtual ~Sensitivity ()
virtual Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override
deep cloning
virtual void setLinearSystem (const std::shared_ptr< LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> &linearSystem)=0
virtual void setApproximation (const SensitivityApproximationSettings::APPROXIMATION &approx)
update the approximation type for the discrete-time system
void setSubstepTrajectoryReference (std::vector< StateVectorArrayPtr, Eigen::aligned_allocator< StateVectorArrayPtr >> *xSubstep, std::vector< ControlVectorArrayPtr, Eigen::aligned_allocator< ControlVectorArrayPtr >> *uSubstep)
virtual void getAandB (const StateVector< STATE_DIM, SCALAR > &x, const ControlVector< CONTROL_DIM, SCALAR > &u, const StateVector< STATE_DIM, SCALAR > &x_next, const int n, size_t numSteps, StateMatrix< STATE_DIM, SCALAR > &A, StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > &B) override=0
Public Member Functions inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteLinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~DiscreteLinearSystem ()
destructor
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext) override
compute the system dynamics
virtual void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t subSteps, state_matrix_t &A, state_control_matrix_t &B)=0
retrieve discrete-time linear system matrices A and B.
void getAandB (const state_vector_t &x, const control_vector_t &u, const int n, state_matrix_t &A, state_control_matrix_t &B)
Public Member Functions inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
DiscreteControlledSystem (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
DiscreteControlledSystem (const ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > &arg)
copy constructor
virtual ~DiscreteControlledSystem ()=default
destructor
void setController (const std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void propagateDynamics (const state_vector_t &state, const time_t n, state_vector_t &stateNext) override
propagates the system dynamics forward by one step
Public Member Functions inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteSystem (const SYSTEM_TYPE &type=GENERAL)
constructor
virtual ~DiscreteSystem ()
desctructor
virtual void propagateDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t n, StateVector< STATE_DIM, SCALAR > &stateNext)=0
propagates the system dynamics forward by one step
SYSTEM_TYPE getType () const
get the type of system
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::StateVector< STATE_DIM, SCALAR > state_vector_t
Public Attributes inherited from ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< StateVectorArray< STATE_DIM, SCALAR > > StateVectorArrayPtr
Public Attributes inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
Additional Inherited Members
Protected Attributes inherited from ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR >
std::vector< StateVectorArrayPtr, Eigen::aligned_allocator< StateVectorArrayPtr > > * xSubstep_
std::vector< ControlVectorArrayPtr, Eigen::aligned_allocator< ControlVectorArrayPtr > > * uSubstep_
Protected Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
Protected Attributes inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double>
class ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >
This class can integrate a controlled system Furthermore, it provides first order derivatives with respect to initial state and control.
Template Parameters
STATE_DIM The state dimension
CONTROL_DIM The control dimension
SCALAR The scalar type
Member Typedef Documentation
control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef ct::core::ControlVector<CONTROL_DIM, SCALAR> ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::control_vector_t
state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef StateMatrix<STATE_DIM, SCALAR> ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::state_matrix_t
state Jacobian type
control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef ControlMatrix<CONTROL_DIM, SCALAR> ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::control_matrix_t
state Jacobian type
state_control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef StateControlMatrix<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::state_control_matrix_t
input Jacobian type
sensitivities_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, STATE_DIM, STATE_DIM + CONTROL_DIM> ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::sensitivities_matrix_t
Constructor & Destructor Documentation
SensitivityIntegrator()
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::SensitivityIntegrator (const SCALAR dt, const std::shared_ptr< ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> & linearSystem, const std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, SCALAR >> & controller, const ct::core::IntegrationType stepperType = ct::core::IntegrationType::EULERCT, bool timeVarying = true) inline
Constructor.
Parameters
[in] system The controlled system
[in] stepperType The integration stepper type
References ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::setLinearSystem(), ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::setStepper(), and ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~SensitivityIntegrator().
~SensitivityIntegrator()
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::~SensitivityIntegrator () override default
Destroys the object.
Referenced by ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::SensitivityIntegrator().
Member Function Documentation
setStepper()
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> void ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::setStepper (const ct::core::IntegrationType stepperType) inline
Initializes the steppers.
Parameters
[in] stepperType The desired integration stepper type
References ct::core::EULER, ct::core::EULER_SYM, ct::core::EULERCT, ct::core::RK4, and ct::core::RK4CT.
Referenced by ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::SensitivityIntegrator().
setLinearSystem()
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> virtual void ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::setLinearSystem (const std::shared_ptr< ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >> & linearSystem) inline override virtual
Prepares the integrator to provide first order sensitivity generation by setting a linearsystem, enabling state caching and settings up the function objects.
Parameters
[in] linearSystem The linearized system
Referenced by ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::SensitivityIntegrator().
setTimeDiscretization()
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> virtual void ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::setTimeDiscretization (const SCALAR & dt) inline override virtual
update the time discretization
Implements ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR >.
integrateSensitivity()
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> void ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::integrateSensitivity (const size_t k, const size_t numSteps, state_matrix_t & A, state_control_matrix_t & B) inline
Integrates the sensitivity ODE of the integrator with respect to the initial state x0.
Parameters
[in] startTime The start time
[in] numSteps The number of integration steps
[out] A Sensitivity with respect to state
[out] B Sensitivity with respect to control
References i.
Referenced by ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::getAandB().
getAandB()
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> virtual void ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::getAandB (const StateVector< STATE_DIM, SCALAR > & x, const ControlVector< CONTROL_DIM, SCALAR > & u, const StateVector< STATE_DIM, SCALAR > & x_next, const int n, const size_t numSteps, state_matrix_t & A, state_control_matrix_t & B) inline override virtual
retrieve discrete-time linear system matrices A and B.
Parameters
x the state setpoint
u the control setpoint
n the time setpoint
numSteps number of timesteps of trajectory for which to get the sensitivity for
A the resulting linear system matrix A
B the resulting linear system matrix B
References ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::integrateSensitivity(), n, SYMPLECTIC_DISABLED, SYMPLECTIC_ENABLED, t, u, ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR >::uSubstep_, x, and ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR >::xSubstep_.
Member Data Documentation
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, size_t P_DIM = STATE_DIM / 2, size_t V_DIM = STATE_DIM / 2, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::StateVector<STATE_DIM, SCALAR> ct::core::SensitivityIntegrator< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::state_vector_t
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/integration/sensitivity/SensitivityIntegrator.h