testing::gmock_function_mocker_test::MockFoo Class Reference
testing::gmock_function_mocker_test::MockFoo Class Reference
Public Member Functions
MockFoo ()
MOCK_METHOD (void, VoidReturning,(int n))
MOCK_METHOD (int, Nullary,())
MOCK_METHOD (bool, Unary,(int))
MOCK_METHOD (long, Binary,(short, int))
MOCK_METHOD (int, Decimal,(bool, char, short, int, long, float, double, unsigned, char *, const std::string &str),(override))
MOCK_METHOD (bool, TakesNonConstReference,(int &))
MOCK_METHOD (std::string, TakesConstReference,(const int &))
MOCK_METHOD (bool, TakesConst,(const int))
MOCK_METHOD ((std::map< int, std::string >), ReturnTypeWithComma,(),())
MOCK_METHOD ((std::map< int, std::string >), ReturnTypeWithComma,(int),(const))
MOCK_METHOD (int, OverloadedOnArgumentNumber,())
MOCK_METHOD (int, OverloadedOnArgumentNumber,(int))
MOCK_METHOD (int, OverloadedOnArgumentType,(int))
MOCK_METHOD (char, OverloadedOnArgumentType,(char))
MOCK_METHOD (int, OverloadedOnConstness,(),(override))
MOCK_METHOD (char, OverloadedOnConstness,(),(override, const))
MOCK_METHOD (int, TypeWithHole,(int(*)()),())
MOCK_METHOD (int, TypeWithComma,((const std::map< int, std::string > &)))
MOCK_METHOD (int, TypeWithTemplatedCopyCtor,(const TemplatedCopyable< int > &))
Public Member Functions inherited from testing::gmock_function_mocker_test::FooInterface
virtual ~FooInterface ()
virtual void VoidReturning (int x)=0
virtual int Nullary ()=0
virtual bool Unary (int x)=0
virtual long Binary (short x, int y)=0
virtual int Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char *j, const std::string &k)=0
virtual bool TakesNonConstReference (int &n)=0
virtual std::string TakesConstReference (const int &n)=0
virtual bool TakesConst (const int x)=0
virtual int OverloadedOnArgumentNumber ()=0
virtual int OverloadedOnArgumentNumber (int n)=0
virtual int OverloadedOnArgumentType (int n)=0
virtual char OverloadedOnArgumentType (char c)=0
virtual int OverloadedOnConstness ()=0
virtual char OverloadedOnConstness () const =0
virtual int TypeWithHole (int(*func)())=0
virtual int TypeWithComma (const std::map< int, std::string > &a_map)=0
virtual int TypeWithTemplatedCopyCtor (const TemplatedCopyable< int > &)=0
Constructor & Destructor Documentation
testing::gmock_function_mocker_test::MockFoo::MockFoo () inline
References testing::gmock_generated_actions_test::Binary(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, MOCK_METHOD, n, testing::gmock_generated_actions_test::Nullary(), and testing::gmock_more_actions_test::Unary().
Member Function Documentation
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (void , VoidReturning , (int n))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , Nullary , ())
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (bool , Unary , (int))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (long , Binary , (short, int))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , Decimal , (bool, char, short, int, long, float, double, unsigned, char *, const std::string &str) , (override))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (bool , TakesNonConstReference , (int &))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (std::string , TakesConstReference , (const int &))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (bool , TakesConst , (const int))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD ((std::map< int, std::string >) , ReturnTypeWithComma , () , ())
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD ((std::map< int, std::string >) , ReturnTypeWithComma , (int) , (const))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , OverloadedOnArgumentNumber , ())
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , OverloadedOnArgumentNumber , (int))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , OverloadedOnArgumentType , (int))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (char , OverloadedOnArgumentType , (char))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , OverloadedOnConstness , () , (override))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (char , OverloadedOnConstness , () , (override, const))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , TypeWithHole , (int(*)()) , ())
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , TypeWithComma , ((const std::map< int, std::string > &)))
testing::gmock_function_mocker_test::MockFoo::MOCK_METHOD (int , TypeWithTemplatedCopyCtor , (const TemplatedCopyable< int > &))
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/test/gmock-function-mocker_test.cc