testing::CurrentTestInfoTest Class Reference
testing::CurrentTestInfoTest Class Reference
Static Protected Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
Additional Inherited Members
Public Member Functions inherited from testing::Test
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestSuite ()
static void TearDownTestSuite ()
static void TearDownTestCase ()
static void SetUpTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool IsSkipped ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions inherited from testing::Test
Test ()
virtual void SetUp ()
virtual void TearDown ()
Member Function Documentation
static void testing::CurrentTestInfoTest::SetUpTestSuite () inline static protected
References testing::UnitTest::current_test_info(), EXPECT_TRUE, and testing::UnitTest::GetInstance().
static void testing::CurrentTestInfoTest::TearDownTestSuite () inline static protected
References testing::UnitTest::current_test_info(), EXPECT_TRUE, and testing::UnitTest::GetInstance().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/gtest_unittest.cc