ct::core::internal::CGHelpers Class Reference
ct::core::internal::CGHelpers Class Reference
Utility class for Auto-Diff code generation.
#include <CGHelpers.h>
Public Member Functions
CGHelpers ()
default constructor
virtual ~CGHelpers ()
destructor
Static Public Member Functions
template<typename AD_SCALAR , typename SCALAR = double>
static std::string generateJacobianSource (CppAD::ADFun< AD_SCALAR > &f, SparsityPattern &pattern, const size_t jacDim, size_t &maxTempVarCount, bool useReverse=false, bool ignoreZero=true, std::string jacName="jac", std::string inputName="x_in", std::string tempName="v_", std::string scalarName="double")
generate source code for Jacobian
template<typename AD_SCALAR >
static std::string generateForwardZeroSource (CppAD::ADFun< AD_SCALAR > &f, size_t &maxTempVarCount, bool ignoreZero=true, std::string jacName="forwardZero", std::string inputName="x_in", std::string tempName="v_")
Generates code for the "zero order" derivative.
template<typename AD_SCALAR >
static std::string generateHessianSource (CppAD::ADFun< AD_SCALAR > &f, SparsityPattern &pattern, const size_t hesDim, size_t &maxTempVarCount, bool ignoreZero=true, std::string jacName="hes", std::string inputName="x_in", std::string tempName="v_")
generate source code for Hessian
static void replaceAll (std::string &text, const std::string &placeholder, const std::string replaceWith)
replaces all occurrences of a (sub-)string in a string with a replacement string
static void replaceOnce (std::string &text, const std::string &placeholder, const std::string replaceWith)
replaces the first occurrence of a (sub-)string in a string with a replacement string
static void writeFile (const std::string &outputFile, const std::string &content)
write a string to file
static std::string parseFile (const std::string &filename)
read the contents of a file to string
template<typename SC = double>
static std::shared_ptr< CppAD::cg::DynamicLib< SC > > loadDynamicLibCppad (const std::string &libName)
load a previously generated dynamic library by name
Detailed Description
Utility class for Auto-Diff code generation.
Constructor & Destructor Documentation
ct::core::internal::CGHelpers::CGHelpers () inline
default constructor
virtual ct::core::internal::CGHelpers::~CGHelpers () inline virtual
destructor
Member Function Documentation
template<typename AD_SCALAR , typename SCALAR = double> static std::string ct::core::internal::CGHelpers::generateJacobianSource (CppAD::ADFun< AD_SCALAR > & f, SparsityPattern & pattern, const size_t jacDim, size_t & maxTempVarCount, bool useReverse = false, bool ignoreZero = true, std::string jacName = "jac", std::string inputName = "x_in", std::string tempName = "v_", std::string scalarName = "double") inline static
generate source code for Jacobian
This method generates C source code for a Jacobian generated by Auto Differentiation.
It generates C source code but does not write it to file. A sparsity pattern can be provided to only get certain elements of the Jacobian. Zero entries in the Jacobian are automatically detected and do not need to be defined sparse. Optionally, a flag can be set to explicitely ignore the zero entries of the Jacobian. If so, it is assumed that all entries of the Jacobian are set to zero outside of the generated code.
Parameters
f Auto-Diff function
x_dim input dimension of independent (input) variable
jac returns the resulting Jacobian
pattern sparsity pattern defining which entries of the Jacobian to generate
maxTempVarCount number of temporary variables in the resulting source code
useReverse if true, Auto-Diff reverse mode will be used
ignoreZero if true, the source code will not set zero entries in the Jacobian
jacName name of the Jacobian variable in the source code
inputName name of the independent (input) variable of the Jacobian
tempName name of temporary variables (i.e. an array / vector)
Returns
generated C source code
Template Parameters
AD_SCALAR Auto-Diff scalar type which is either a normal AD type or a codegen type
SCALAR underlying primitive type
References ct::core::internal::SparsityPattern::col(), i, n, ct::core::internal::SparsityPattern::row(), ct::core::internal::SparsityPattern::sparsity(), and ct::core::internal::SparsityPattern::workJacobian().
Referenced by ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateJacobianSource().
template<typename AD_SCALAR > static std::string ct::core::internal::CGHelpers::generateForwardZeroSource (CppAD::ADFun< AD_SCALAR > & f, size_t & maxTempVarCount, bool ignoreZero = true, std::string jacName = "forwardZero", std::string inputName = "x_in", std::string tempName = "v_") inline static
Generates code for the "zero order" derivative.
This method generates C code for the "zero order" derivative, i.e. the original function/model itself. While this seems unusual at first, Auto-Diff can optimize regular function calls and generate more efficient code. The resulting code should have comparable numerical accuracy as the original model.
Parameters
f The function to generate source code for
x_dim input dimension of independent (input) variable
jac zero-order Jacobian
maxTempVarCount number of temporary variables in the resulting source code
ignoreZero if true, the source code will not set zero entries in the Jacobian
jacName name of the Jacobian variable in the source code
inputName name of the independent (input) variable of the Jacobian
tempName name of temporary variables (i.e. an array / vector)
Returns
Template Parameters
AD_SCALAR Auto-Diff scalar type which is either a normal AD type or a codegen type
References i, and n.
Referenced by ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateForwardZeroSource().
template<typename AD_SCALAR > static std::string ct::core::internal::CGHelpers::generateHessianSource (CppAD::ADFun< AD_SCALAR > & f, SparsityPattern & pattern, const size_t hesDim, size_t & maxTempVarCount, bool ignoreZero = true, std::string jacName = "hes", std::string inputName = "x_in", std::string tempName = "v_") inline static
generate source code for Hessian
This method generates C source code for a Hessian generated by Auto Differentiation.
It generates C source code but does not write it to file. A sparsity pattern can be provided to only get certain elements of the Hessian. Zero entries in the Hessian are automatically detected and do not need to be defined sparse. Optionally, a flag can be set to explicitely ignore the zero entries of the Hessian. If so, it is assumed that all entries of the Hessian are set to zero outside of the generated code.
Parameters
f Auto-Diff function
pattern sparsity pattern defining which entries of the Hessian to generate
hesDim the dimension of the Hessian to generate
maxTempVarCount number of temporary variables in the resulting source code
useReverse if true, Auto-Diff reverse mode will be used
ignoreZero if true, the source code will not set zero entries in the Hessian
jacName name of the Hessian variable in the source code
inputName name of the independent (input) variable of the Hessian
tempName name of temporary variables (i.e. an array / vector)
Returns
generated C source code
Template Parameters
AD_SCALAR Auto-Diff scalar type which is either a normal AD type or a codegen type
References ct::core::internal::SparsityPattern::col(), i, m, n, ct::core::internal::SparsityPattern::row(), ct::core::internal::SparsityPattern::sparsity(), and ct::core::internal::SparsityPattern::workHessian().
Referenced by ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateHessianSource().
static void ct::core::internal::CGHelpers::replaceAll (std::string & text, const std::string & placeholder, const std::string replaceWith) inline static
replaces all occurrences of a (sub-)string in a string with a replacement string
Parameters
text the string to modify
placeholder the substring to search for and replace
replaceWith the string replacing the found pattern with
Referenced by ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateHessianSource(), ct::core::ADCodegenLinearizer< state_dim, control_dim >::getLinearizer(), and ct::core::DiscreteSystemLinearizerADCG< STATE_DIM, CONTROL_DIM, SCALAR >::getLinearizer().
static void ct::core::internal::CGHelpers::replaceOnce (std::string & text, const std::string & placeholder, const std::string replaceWith) inline static
replaces the first occurrence of a (sub-)string in a string with a replacement string
Parameters
text the string to modify
placeholder the substring to search for and replace
replaceWith the string replacing the found pattern with
Referenced by ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateHessianSource(), ct::core::ADCodegenLinearizer< state_dim, control_dim >::getLinearizer(), and ct::core::DiscreteSystemLinearizerADCG< STATE_DIM, CONTROL_DIM, SCALAR >::getLinearizer().
static void ct::core::internal::CGHelpers::writeFile (const std::string & outputFile, const std::string & content) inline static
write a string to file
writes a text to a new file
Parameters
outputFile path of the file to write
content content to write to the file
Referenced by ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateHessianSource(), ct::core::ADCodegenLinearizer< state_dim, control_dim >::getLinearizer(), and ct::core::DiscreteSystemLinearizerADCG< STATE_DIM, CONTROL_DIM, SCALAR >::getLinearizer().
static std::string ct::core::internal::CGHelpers::parseFile (const std::string & filename) inline static
read the contents of a file to string
Opens a file and reads all its content to a string
Parameters
filename path of the file to read
Returns
content of the file
References t.
Referenced by ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateHessianSource(), ct::core::ADCodegenLinearizer< state_dim, control_dim >::getLinearizer(), and ct::core::DiscreteSystemLinearizerADCG< STATE_DIM, CONTROL_DIM, SCALAR >::getLinearizer().
template<typename SC = double> static std::shared_ptr<CppAD::cg::DynamicLib<SC> > ct::core::internal::CGHelpers::loadDynamicLibCppad (const std::string & libName) inline static
load a previously generated dynamic library by name
Parameters
libName name of the library
Returns
pointer to a loaded instance of the library
Note
This loading function is inspired by the CppAD dynamic library processor, see CppAD::cg::DynamicModelLibraryProcessor
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/internal/autodiff/CGHelpers.h