testing::internal::EventRecordingListener Class Reference
testing::internal::EventRecordingListener Class Reference
Public Member Functions
EventRecordingListener (const char *name)
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
virtual void OnTestSuiteStart (const TestSuite &)
virtual void OnTestSuiteEnd (const TestSuite &)
Protected Member Functions
void OnTestProgramStart (const UnitTest &) override
void OnTestIterationStart (const UnitTest &, int iteration) override
void OnEnvironmentsSetUpStart (const UnitTest &) override
void OnEnvironmentsSetUpEnd (const UnitTest &) override
void OnTestCaseStart (const TestCase &) override
void OnTestStart (const TestInfo &) override
void OnTestPartResult (const TestPartResult &) override
void OnTestEnd (const TestInfo &) override
void OnTestCaseEnd (const TestCase &) override
void OnEnvironmentsTearDownStart (const UnitTest &) override
void OnEnvironmentsTearDownEnd (const UnitTest &) override
void OnTestIterationEnd (const UnitTest &, int iteration) override
void OnTestProgramEnd (const UnitTest &) override
Constructor & Destructor Documentation
testing::internal::EventRecordingListener::EventRecordingListener (const char * name) inline explicit
Referenced by main().
Member Function Documentation
void testing::internal::EventRecordingListener::OnTestProgramStart (const UnitTest &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnTestIterationStart (const UnitTest & , int iteration) inline override protected virtual
Implements testing::TestEventListener.
References g_events, testing::Message::GetString(), and googletest-output-test::message.
void testing::internal::EventRecordingListener::OnEnvironmentsSetUpStart (const UnitTest &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnEnvironmentsSetUpEnd (const UnitTest &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnTestCaseStart (const TestCase &) inline override protected virtual
Reimplemented from testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnTestStart (const TestInfo &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnTestPartResult (const TestPartResult &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnTestEnd (const TestInfo &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnTestCaseEnd (const TestCase &) inline override protected virtual
Reimplemented from testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnEnvironmentsTearDownStart (const UnitTest &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnEnvironmentsTearDownEnd (const UnitTest &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
void testing::internal::EventRecordingListener::OnTestIterationEnd (const UnitTest & , int iteration) inline override protected virtual
Implements testing::TestEventListener.
References g_events, testing::Message::GetString(), and googletest-output-test::message.
void testing::internal::EventRecordingListener::OnTestProgramEnd (const UnitTest &) inline override protected virtual
Implements testing::TestEventListener.
References g_events.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/googletest-listener-test.cc