ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
Computes the linearization of a general non-linear ControlledSystem using numerical differentiation.
#include <SystemLinearizer.h>
Public Types
typedef Base::state_vector_t state_vector_t
state vector type
typedef Base::control_vector_t control_vector_t
input vector type
typedef Base::state_matrix_t state_matrix_t
state Jacobian type
typedef Base::state_control_matrix_t state_control_matrix_t
input Jacobian type
typedef ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > system_t
type of system to be linearized
Public Types inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef Base::time_t time_t
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
state vector type
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
input vector type
typedef StateMatrix< STATE_DIM, SCALAR > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, SCALAR >
typedef SCALAR time_t
the type of the time variable
Public Member Functions
SystemLinearizer (std::shared_ptr< system_t > nonlinearSystem, bool doubleSidedDerivative=true)
default constructor
SystemLinearizer (const SystemLinearizer &arg)
copy constructor
virtual ~SystemLinearizer ()
destructor
SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override
deep cloning
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const double t=0.0) override
get the Jacobian with respect to the state
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const double t=0.0) override
get the Jacobian with respect to the input
Public Member Functions inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
LinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~LinearSystem ()
destructor
virtual void computeControlledDynamics (const state_vector_t &state, const time_t &t, const control_vector_t &control, state_vector_t &derivative) override
compute the system dynamics
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
get the A matrix of a linear system
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
get the B matrix of a linear system
virtual void getDerivatives (state_matrix_t &A, state_control_matrix_t &B, const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))
Get both linear system matrices A and B in one call.
Public Member Functions inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
ControlledSystem (const ControlledSystem &arg)
copy constructor
virtual ~ControlledSystem ()
destructor
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative) override
compute the dynamics of the system
virtual void computeControlledDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< STATE_DIM, SCALAR > &derivative)=0
ControlVector< CONTROL_DIM, SCALAR > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, SCALAR >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
System (const System &other)
copy constructor
virtual ~System ()
destructor
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative)=0
computes the system dynamics
SYSTEM_TYPE getType () const
get the type of system
virtual bool isSymplectic () const
Determines if the system is in symplectic form.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Base class type.
Public Attributes inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, SCALAR > Base
Public Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef SCALAR S
the scalar type
Protected Attributes
std::shared_ptr< system_t > nonlinearSystem_
instance of non-linear system
DynamicsLinearizerNumDiff< STATE_DIM, CONTROL_DIM, SCALAR, SCALAR > linearizer_
instance of numerical-linearizer
state_matrix_t dFdx_
Jacobian wrt state.
state_control_matrix_t dFdu_
Jacobian wrt input.
bool isSecondOrderSystem_
flag if system is a second order system
Protected Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
ControlVector< CONTROL_DIM, SCALAR > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >
Computes the linearization of a general non-linear ControlledSystem using numerical differentiation.
This class takes a non-linear ControlledSystem and computes the linearization around a certain point , .
where
In case the ControlledSystem is a pure second-order system, the upper half of A is not explicitely computed but A is assumed to be of the following form
Examples for using the SystemLinearizer (and the Auto-diff Linearizer) can be found in AutoDiffLinearizerTest.cpp
Note
In case your ControlledSystem is templated on scalar type, we suggest using the ADCodegenLinearizer for highest efficiency and accuracy. If this is not the case but your system is a RigidBodySystem you can fall back to the ct::rbd::RBDLinearizer for good accuracy and speed.
Template Parameters
STATE_DIM dimension of state vector
CONTROL_DIM dimension of control vector
SCALAR underlying scalar type of the system
Examples:
AutoDiffLinearizerTest.cpp.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_vector_t ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
state vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::control_vector_t ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
input vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_matrix_t ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
state Jacobian type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_control_matrix_t ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::state_control_matrix_t
input Jacobian type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef ControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::system_t
type of system to be linearized
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::SystemLinearizer (std::shared_ptr< system_t > nonlinearSystem, bool doubleSidedDerivative = true) inline
default constructor
Initializes the linearizer with a non-linear system.
Parameters
nonlinearSystem non-linear system to linearize
doubleSidedDerivative if true, double sided numerical differentiation is used
References ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_, ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_, ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::isSecondOrderSystem_, and ct::core::SECOND_ORDER.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::SystemLinearizer (const SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR > & arg) inline
copy constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::~SystemLinearizer () inline virtual
destructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> SystemLinearizer<STATE_DIM, CONTROL_DIM, SCALAR>* ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const inline override virtual
deep cloning
Implements ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual const state_matrix_t& ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const double t = 0.0) inline override virtual
get the Jacobian with respect to the state
This computes the linearization of the system with respect to the state at a given point , , i.e. it computes
Parameters
x state to linearize at
u control to linearize at
t time
Returns
Jacobian wrt state
References ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_, ct::core::DynamicsLinearizerNumDiff< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeState(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::isSecondOrderSystem_, ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_, and t.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual const state_control_matrix_t& ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const double t = 0.0) inline override virtual
get the Jacobian with respect to the input
This computes the linearization of the system with respect to the input at a given point , , i.e. it computes
Parameters
x state to linearize at
u control to linearize at
t time
Returns
Jacobian wrt input
References ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_, ct::core::DynamicsLinearizerNumDiff< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::isSecondOrderSystem_, ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_, and t.
Referenced by TEST().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef LinearSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::Base
Base class type.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> std::shared_ptr<system_t> ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::nonlinearSystem_ protected
instance of non-linear system
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> DynamicsLinearizerNumDiff<STATE_DIM, CONTROL_DIM, SCALAR, SCALAR> ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_ protected
instance of numerical-linearizer
Referenced by ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), and ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> state_matrix_t ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_ protected
Jacobian wrt state.
Referenced by ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), and ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::SystemLinearizer().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> state_control_matrix_t ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_ protected
Jacobian wrt input.
Referenced by ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), and ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::SystemLinearizer().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> bool ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::isSecondOrderSystem_ protected
flag if system is a second order system
Referenced by ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), and ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::SystemLinearizer().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/systems/continuous_time/linear/SystemLinearizer.h