testing::internal::TestEventRepeater Class Reference
testing::internal::TestEventRepeater Class Reference
Public Member Functions
TestEventRepeater ()
~TestEventRepeater () override
void Append (TestEventListener *listener)
TestEventListener * Release (TestEventListener *listener)
bool forwarding_enabled () const
void set_forwarding_enabled (bool enable)
void OnTestProgramStart (const UnitTest &unit_test) override
void OnTestIterationStart (const UnitTest &unit_test, int iteration) override
void OnEnvironmentsSetUpStart (const UnitTest &unit_test) override
void OnEnvironmentsSetUpEnd (const UnitTest &unit_test) override
void OnTestCaseStart (const TestSuite &parameter) override
void OnTestSuiteStart (const TestSuite &parameter) override
void OnTestStart (const TestInfo &test_info) override
void OnTestPartResult (const TestPartResult &result) override
void OnTestEnd (const TestInfo &test_info) override
void OnTestCaseEnd (const TestSuite &parameter) override
void OnTestSuiteEnd (const TestSuite &parameter) override
void OnEnvironmentsTearDownStart (const UnitTest &unit_test) override
void OnEnvironmentsTearDownEnd (const UnitTest &unit_test) override
void OnTestIterationEnd (const UnitTest &unit_test, int iteration) override
void OnTestProgramEnd (const UnitTest &unit_test) override
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestCaseEnd (const TestCase &)
Constructor & Destructor Documentation
testing::internal::TestEventRepeater::TestEventRepeater () inline
testing::internal::TestEventRepeater::~TestEventRepeater () override
Member Function Documentation
void testing::internal::TestEventRepeater::Append (TestEventListener * listener)
Referenced by testing::TestEventListeners::Append().
TestEventListener * testing::internal::TestEventRepeater::Release (TestEventListener * listener)
References i.
Referenced by testing::TestEventListeners::Release().
bool testing::internal::TestEventRepeater::forwarding_enabled () const inline
Referenced by testing::TestEventListeners::Release().
void testing::internal::TestEventRepeater::set_forwarding_enabled (bool enable) inline
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
Referenced by testing::TestEventListeners::Release().
void testing::internal::TestEventRepeater::OnTestProgramStart (const UnitTest & unit_test) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestIterationStart (const UnitTest & unit_test, int iteration) override virtual
Implements testing::TestEventListener.
References i.
void testing::internal::TestEventRepeater::OnEnvironmentsSetUpStart (const UnitTest & unit_test) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnEnvironmentsSetUpEnd (const UnitTest & unit_test) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestCaseStart (const TestSuite & parameter) override
void testing::internal::TestEventRepeater::OnTestSuiteStart (const TestSuite & parameter) override virtual
Reimplemented from testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestStart (const TestInfo & test_info) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestPartResult (const TestPartResult & result) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestEnd (const TestInfo & test_info) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestCaseEnd (const TestSuite & parameter) override
void testing::internal::TestEventRepeater::OnTestSuiteEnd (const TestSuite & parameter) override virtual
Reimplemented from testing::TestEventListener.
void testing::internal::TestEventRepeater::OnEnvironmentsTearDownStart (const UnitTest & unit_test) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnEnvironmentsTearDownEnd (const UnitTest & unit_test) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestIterationEnd (const UnitTest & unit_test, int iteration) override virtual
Implements testing::TestEventListener.
void testing::internal::TestEventRepeater::OnTestProgramEnd (const UnitTest & unit_test) override virtual
Implements testing::TestEventListener.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc