testing::Action< F > Class Template Reference
testing::Action< F > Class Template Reference
#include <gmock-actions.h>
Public Types
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
Public Member Functions
Action ()
template<typename G , typename = typename ::std::enable_if< ::std::is_constructible<::std::function<F>, G>::value>::type>
Action (G &&fun)
Action (ActionInterface< F > *impl)
template<typename Func >
Action (const Action< Func > &action)
bool IsDoDefault () const
Result Perform (ArgumentTuple args) const
Friends
template<typename G >
class Action
Member Typedef Documentation
template<typename F> typedef internal::Function<F>::Result testing::Action< F >::Result
template<typename F> typedef internal::Function<F>::ArgumentTuple testing::Action< F >::ArgumentTuple
Constructor & Destructor Documentation
template<typename F> testing::Action< F >::Action () inline
template<typename F> template<typename G , typename = typename ::std::enable_if< ::std::is_constructible<::std::function<F>, G>::value>::type> testing::Action< F >::Action (G && fun) inline
template<typename F> testing::Action< F >::Action (ActionInterface< F > * impl) inline explicit
template<typename F> template<typename Func > testing::Action< F >::Action (const Action< Func > & action) inline explicit
Member Function Documentation
template<typename F> bool testing::Action< F >::IsDoDefault () const inline
template<typename F> Result testing::Action< F >::Perform (ArgumentTuple args) const inline
Referenced by testing::internal::WithArgsAction< InnerAction, I >::operator Action<R(), testing::internal::DoAllAction< Actions >::operator Action<R(), testing::gmock_generated_actions_test::TEST(), and testing::gmock_more_actions_test::TEST().
Friends And Related Function Documentation
template<typename F> template<typename G > friend class Action friend
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/include/gmock/gmock-actions.h