DogAdder Class Reference
DogAdder Class Reference
Public Member Functions
DogAdder (const char *a_value)
DogAdder (const DogAdder &other)
DogAdder operator= (const DogAdder &other)
DogAdder operator+ (const DogAdder &other) const
bool operator< (const DogAdder &other) const
const std::string & value () const
Constructor & Destructor Documentation
DogAdder::DogAdder (const char * a_value) inline explicit
Referenced by operator+(), and TEST().
DogAdder::DogAdder (const DogAdder & other) inline
Member Function Documentation
DogAdder DogAdder::operator= (const DogAdder & other) inline
Referenced by NonDefaultConstructAssignString::str().
DogAdder DogAdder::operator+ (const DogAdder & other) const inline
References DogAdder().
bool DogAdder::operator< (const DogAdder & other) const inline
const std::string& DogAdder::value () const inline
Referenced by StatefulNamingFunctor::operator()().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/googletest-param-test-test.cc