ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME > Class Template Reference
ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME > Class Template Reference
Base class for Auto-Diff and Auto-Diff Codegen linearization for system dynamics.
#include <DynamicsLinearizerADBase.h>
Public Types
typedef std::conditional<(std::is_same< SCALAR, CppAD::AD< double >>::value)||(std::is_same< SCALAR, CppAD::AD< CppAD::cg::CG< double >>>::value), double, float >::type OUT_SCALAR
scalar type of resulting linear system
typedef StateVector< STATE_DIM, OUT_SCALAR > state_vector_t
typedef ControlVector< CONTROL_DIM, OUT_SCALAR > control_vector_t
typedef StateVector< STATE_DIM, SCALAR > state_vector_ad_t
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_ad_t
typedef StateMatrix< STATE_DIM, OUT_SCALAR > state_matrix_t
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, OUT_SCALAR > state_control_matrix_t
typedef std::function< void(const state_vector_ad_t &, const TIME &, const control_vector_ad_t &, state_vector_ad_t &)> dynamics_fct_t
dynamics function signature
Public Member Functions
DynamicsLinearizerADBase (dynamics_fct_t dyn)
default constructor
DynamicsLinearizerADBase (const DynamicsLinearizerADBase &arg)
copy constructor
template<typename T = std::string>
std::enable_if< std::is_same< OUT_SCALAR, double >::value, T >::type getOutScalarType () const
template<typename T = std::string>
std::enable_if< std::is_same< OUT_SCALAR, float >::value, T >::type getOutScalarType () const
virtual ~DynamicsLinearizerADBase ()
destructor
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
void initialize ()
initialize all utilities
void recordTerms ()
record the model
void setupSparsityA ()
setup the sparsity of the state Jacobian
void setupSparsityB ()
setup the sparsity of the input Jacobian
Protected Attributes
const size_t A_entries = STATE_DIM * STATE_DIM
number of entries in the state Jacobian
const size_t B_entries = STATE_DIM * CONTROL_DIM
number of entries in the input Jacobian
const size_t FullJac_entries
number of entries in the stacked Jacobian
dynamics_fct_t dynamics_fct_
function handle to system dynamics
CppAD::ADFun< typename SCALAR::value_type > f_
Auto-Diff function.
SparsityPattern sparsityA_
sparsity pattern of the state Jacobian
SparsityPattern sparsityB_
sparsity pattern of the input Jacobian
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME>
class ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >
Base class for Auto-Diff and Auto-Diff Codegen linearization for system dynamics.
This class contains shared code between Auto-Diff and Auto-Diff Codegen linearization.
Template Parameters
STATE_DIM dimension of state vector
CONTROL_DIM dimension of control vector
SCALAR scalar type
TIME type of time variable of dynamics
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef std::conditional<(std::is_same<SCALAR, CppAD::AD<double>>::value) || (std::is_same<SCALAR, CppAD::AD<CppAD::cg::CG<double>>>::value), double, float>::type ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::OUT_SCALAR
scalar type of resulting linear system
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef StateVector<STATE_DIM, OUT_SCALAR> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef ControlVector<CONTROL_DIM, OUT_SCALAR> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef StateVector<STATE_DIM, SCALAR> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::state_vector_ad_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef ControlVector<CONTROL_DIM, SCALAR> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::control_vector_ad_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef StateMatrix<STATE_DIM, OUT_SCALAR> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef StateControlMatrix<STATE_DIM, CONTROL_DIM, OUT_SCALAR> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::state_control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef std::function<void(const state_vector_ad_t&, const TIME&, const control_vector_ad_t&, state_vector_ad_t&)> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::dynamics_fct_t
dynamics function signature
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::DynamicsLinearizerADBase (dynamics_fct_t dyn) inline
default constructor
Parameters
dyn non-linear system to linearize
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::DynamicsLinearizerADBase (const DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME > & arg) inline
copy constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> virtual ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::~DynamicsLinearizerADBase () inline virtual
destructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> template<typename T = std::string> std::enable_if<std::is_same<OUT_SCALAR, double>::value, T>::type ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getOutScalarType () const inline
Referenced by ct::core::ADCodegenLinearizer< state_dim, control_dim >::getLinearizer(), and ct::core::DiscreteSystemLinearizerADCG< STATE_DIM, CONTROL_DIM, SCALAR >::getLinearizer().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> template<typename T = std::string> std::enable_if<std::is_same<OUT_SCALAR, float>::value, T>::type ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getOutScalarType () const inline
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> void ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::initialize () inline protected
initialize all utilities
Records the model function and sets up the sparsity patterns for the Jacobians.
Referenced by ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::DynamicsLinearizerADBase().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> void ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::recordTerms () inline protected
record the model
Referenced by ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::initialize().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> void ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::setupSparsityA () inline protected
setup the sparsity of the state Jacobian
Referenced by ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::DynamicsLinearizerADBase(), and ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::initialize().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> void ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::setupSparsityB () inline protected
setup the sparsity of the input Jacobian
Referenced by ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::DynamicsLinearizerADBase(), and ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::initialize().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> const size_t ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::A_entries = STATE_DIM * STATE_DIM protected
number of entries in the state Jacobian
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeA().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> const size_t ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::B_entries = STATE_DIM * CONTROL_DIM protected
number of entries in the input Jacobian
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeB().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> const size_t ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::FullJac_entries protected
Initial value:
=
        (STATE_DIM + CONTROL_DIM) * STATE_DIM
number of entries in the stacked Jacobian
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> dynamics_fct_t ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::dynamics_fct_ protected
function handle to system dynamics
Referenced by ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::recordTerms().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> CppAD::ADFun<typename SCALAR::value_type> ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::f_ protected
Auto-Diff function.
Referenced by ct::core::DynamicsLinearizerADCG< STATE_DIM, CONTROL_DIM, ADCGScalar, ADCGScalar >::compileJIT(), ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeA(), ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeB(), ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::DynamicsLinearizerADBase(), ct::core::DynamicsLinearizerADCG< STATE_DIM, CONTROL_DIM, ADCGScalar, ADCGScalar >::generateCode(), and ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::recordTerms().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> SparsityPattern ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::sparsityA_ protected
sparsity pattern of the state Jacobian
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeA(), ct::core::DynamicsLinearizerADCG< STATE_DIM, CONTROL_DIM, ADCGScalar, ADCGScalar >::generateCode(), and ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::setupSparsityA().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> SparsityPattern ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::sparsityB_ protected
sparsity pattern of the input Jacobian
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeB(), ct::core::DynamicsLinearizerADCG< STATE_DIM, CONTROL_DIM, ADCGScalar, ADCGScalar >::generateCode(), and ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::setupSparsityB().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/systems/linearizer/DynamicsLinearizerADBase.h