testing::ParseFlagsTest Class Reference
testing::ParseFlagsTest Class Reference
Protected Member Functions
void SetUp () override
Protected Member Functions inherited from testing::Test
Test ()
virtual void TearDown ()
Static Protected Member Functions
template<typename CharType >
static void AssertStringArrayEq (int size1, CharType **array1, int size2, CharType **array2)
static void CheckFlags (const Flags &expected)
template<typename CharType >
static void TestParsingFlags (int argc1, const CharType **argv1, int argc2, const CharType **argv2, const Flags &expected, bool should_print_help)
Additional Inherited Members
Public Member Functions inherited from testing::Test
virtual ~Test ()
Static Public Member Functions inherited from testing::Test
static void SetUpTestSuite ()
static void TearDownTestSuite ()
static void TearDownTestCase ()
static void SetUpTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool IsSkipped ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Member Function Documentation
void testing::ParseFlagsTest::SetUp () inline override protected virtual
Reimplemented from testing::Test.
References GTEST_FLAG, and gmock_output_test::output.
Referenced by testing::TEST_F().
template<typename CharType > static void testing::ParseFlagsTest::AssertStringArrayEq (int size1, CharType ** array1, int size2, CharType ** array2) inline static protected
References ASSERT_EQ, ASSERT_STREQ, and i.
static void testing::ParseFlagsTest::CheckFlags (const Flags & expected) inline static protected
References testing::Flags::also_run_disabled_tests, testing::Flags::break_on_failure, testing::Flags::catch_exceptions, testing::Flags::death_test_use_fork, EXPECT_EQ, EXPECT_STREQ, testing::Flags::filter, GTEST_FLAG, testing::Flags::list_tests, gmock_output_test::output, testing::Flags::output, testing::Flags::print_time, testing::Flags::random_seed, testing::Flags::repeat, testing::Flags::shuffle, testing::Flags::stack_trace_depth, testing::Flags::stream_result_to, and testing::Flags::throw_on_failure.
template<typename CharType > static void testing::ParseFlagsTest::TestParsingFlags (int argc1, const CharType ** argv1, int argc2, const CharType ** argv2, const Flags & expected, bool should_print_help) inline static protected
References testing::internal::CaptureStdout(), EXPECT_EQ, EXPECT_PRED_FORMAT2, testing::internal::g_help_flag, testing::internal::GetCapturedStdout(), testing::IsNotSubstring(), testing::IsSubstring(), and testing::internal::ParseGoogleTestFlagsOnly().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/gtest_unittest.cc