testing::gmock_function_mocker_test::StackInterface< T > Class Template Reference
testing::gmock_function_mocker_test::StackInterface< T > Class Template Reference abstract
Public Member Functions
virtual ~StackInterface ()
virtual void Push (const T &value)=0
virtual void Pop ()=0
virtual int GetSize () const =0
virtual const T & GetTop () const =0
Constructor & Destructor Documentation
template<typename T > virtual testing::gmock_function_mocker_test::StackInterface< T >::~StackInterface () inline virtual
References value.
Member Function Documentation
template<typename T > virtual void testing::gmock_function_mocker_test::StackInterface< T >::Push (const T & value) pure virtual
Referenced by testing::gmock_function_mocker_test::TEST().
template<typename T > virtual void testing::gmock_function_mocker_test::StackInterface< T >::Pop () pure virtual
Referenced by testing::gmock_function_mocker_test::TEST().
template<typename T > virtual int testing::gmock_function_mocker_test::StackInterface< T >::GetSize () const pure virtual
Referenced by testing::gmock_function_mocker_test::TEST().
template<typename T > virtual const T& testing::gmock_function_mocker_test::StackInterface< T >::GetTop () const pure virtual
Referenced by testing::gmock_function_mocker_test::TEST().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/test/gmock-function-mocker_test.cc