ct::core::internal::StepperCTBase< MATRIX, SCALAR > Class Template Reference
ct::core::internal::StepperCTBase< MATRIX, SCALAR > Class Template Reference abstract
The stepper interface for custom steppers.
#include <SteppersCT.h>
Public Member Functions
virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW void integrate_n_steps (const std::function< void(const MATRIX &, MATRIX &, SCALAR)> &rhs, MATRIX &state, const SCALAR &startTime, size_t numSteps, SCALAR dt) override
Performs numSteps integration steps.
virtual void integrate_n_steps (std::function< void(const MATRIX &x, const SCALAR &t)> observe, const std::function< void(const MATRIX &, MATRIX &, SCALAR)> &rhs, MATRIX &state, const SCALAR &startTime, size_t numSteps, SCALAR dt) override
Performs numSteps integration steps.
virtual void do_step (const std::function< void(const MATRIX &, MATRIX &, SCALAR)> &rhs, MATRIX &stateInOut, const SCALAR time, const SCALAR dt)=0
Implements a single step of the integration scheme.
Public Member Functions inherited from ct::core::internal::StepperBase< MATRIX, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW StepperBase ()
virtual ~StepperBase ()
virtual void integrate_const (const std::function< void(const MATRIX &, MATRIX &, SCALAR)> &rhs, MATRIX &state, const SCALAR &startTime, const SCALAR &finalTime, SCALAR dt)
Equidistant integration based on initial and final time as well as step length.
virtual void integrate_const (std::function< void(const MATRIX &x, const SCALAR &t)> observer, const std::function< void(const MATRIX &, MATRIX &, SCALAR)> &rhs, MATRIX &state, const SCALAR &startTime, const SCALAR &finalTime, SCALAR dt)
Equidistant integration based on initial and final time as well as step length.
virtual void integrate_adaptive (const std::function< void(const MATRIX &, MATRIX &, SCALAR)> &rhs, MATRIX &state, const SCALAR &startTime, const SCALAR &finalTime, SCALAR dtInitial=SCALAR(0.01))
Integrates forward in time from an initial to a final time. If an adaptive stepper is used, the time step is adjusted according to the error tolerances. If a fixed step integrator is used, this function will do fixed step integration.
virtual void integrate_adaptive (std::function< void(const MATRIX &x, const SCALAR &t)> observer, const std::function< void(const MATRIX &, MATRIX &, SCALAR)> &rhs, MATRIX &state, const SCALAR &startTime, const SCALAR &finalTime, const SCALAR dtInitial=SCALAR(0.01))
Integrates forward in time from an initial to a final time. If an adaptive stepper is used, the time step is adjusted according to the error tolerances. If a fixed step integrator is used, this function will do fixed step integration.
virtual void integrate_times (std::function< void(const MATRIX &x, const SCALAR &t)> observer, const std::function< void(const MATRIX &, MATRIX &, SCALAR)> &rhs, MATRIX &state, const tpl::TimeArray< SCALAR > &timeTrajectory, SCALAR dtInitial=SCALAR(0.01))
Integrates a system using a given time sequence.
void setAdaptiveErrorTolerances (const SCALAR absErrTol, const SCALAR &relErrTol)
Sets the adaptive error tolerances.
Additional Inherited Members
Protected Attributes inherited from ct::core::internal::StepperBase< MATRIX, SCALAR >
SCALAR absErrTol_
SCALAR relErrTol_
Detailed Description
template<typename MATRIX, typename SCALAR = double>
class ct::core::internal::StepperCTBase< MATRIX, SCALAR >
The stepper interface for custom steppers.
Template Parameters
MATRIX The Matrix type to be integrated
SCALAR The scalar type
Member Function Documentation
template<typename MATRIX , typename SCALAR = double> virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW void ct::core::internal::StepperCTBase< MATRIX, SCALAR >::integrate_n_steps (const std::function< void(const MATRIX &, MATRIX &, SCALAR)> & rhs, MATRIX & state, const SCALAR & startTime, size_t numSteps, SCALAR dt) inline override virtual
Performs numSteps integration steps.
Parameters
[in] rhs The ODE to be integrated
[in,out] state The state
[in] startTime The start time
[in] numSteps The number of integration steps
[in] dt The integration timestep
Reimplemented from ct::core::internal::StepperBase< MATRIX, SCALAR >.
References ct::core::internal::StepperCTBase< MATRIX, SCALAR >::do_step(), and i.
template<typename MATRIX , typename SCALAR = double> virtual void ct::core::internal::StepperCTBase< MATRIX, SCALAR >::integrate_n_steps (std::function< void(const MATRIX &x, const SCALAR &t)> observer, const std::function< void(const MATRIX &, MATRIX &, SCALAR)> & rhs, MATRIX & state, const SCALAR & startTime, size_t numSteps, SCALAR dt) inline override virtual
Performs numSteps integration steps.
Parameters
[in] observer The observer
[in] rhs The ODE to be integrated
[in,out] state The state
[in] startTime The start time
[in] numSteps The number steps
[in] dt The integration timestep
Reimplemented from ct::core::internal::StepperBase< MATRIX, SCALAR >.
References ct::core::internal::StepperCTBase< MATRIX, SCALAR >::do_step(), dt, and i.
template<typename MATRIX , typename SCALAR = double> virtual void ct::core::internal::StepperCTBase< MATRIX, SCALAR >::do_step (const std::function< void(const MATRIX &, MATRIX &, SCALAR)> & rhs, MATRIX & stateInOut, const SCALAR time, const SCALAR dt) pure virtual
Implements a single step of the integration scheme.
Parameters
[in] rhs The ODE
[in,out] stateInOut The state
[in] time The integration time
[in] dt The integration timestep
Referenced by ct::core::internal::StepperCTBase< MATRIX, SCALAR >::integrate_n_steps(), ct::core::internal::StepperEulerCT< MATRIX, SCALAR >::StepperEulerCT(), and ct::core::internal::StepperRK4CT< MATRIX, SCALAR >::StepperRK4CT().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/integration/internal/SteppersCT.h