ct::core::internal::SparsityPattern Class Reference
ct::core::internal::SparsityPattern Class Reference
Convenience class to handle sparsity patterns, e.g. in Jacobians.
#include <SparsityPattern.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW SparsityPattern ()=default
virtual ~SparsityPattern ()=default
template<int ROWS, int COLS>
void initPattern (const Eigen::Matrix< bool, ROWS, COLS > &sparsity)
initialize the pattern
const CppAD::vector< bool > & sparsity () const
returns the sparsity pattern as a vector (row-major)
const CppAD::vector< size_t > & row () const
returns the row indices of a row-column sparsity representation
const CppAD::vector< size_t > & col () const
returns the column indices of a row-column sparsity representation
CppAD::sparse_jacobian_work & workJacobian ()
work area for CppAD
CppAD::sparse_hessian_work & workHessian ()
void clearWork ()
Clears the cppad internal work done on the sparsity pattern.
Detailed Description
Convenience class to handle sparsity patterns, e.g. in Jacobians.
Constructor & Destructor Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW ct::core::internal::SparsityPattern::SparsityPattern () default
virtual ct::core::internal::SparsityPattern::~SparsityPattern () virtual default
Member Function Documentation
template<int ROWS, int COLS> void ct::core::internal::SparsityPattern::initPattern (const Eigen::Matrix< bool, ROWS, COLS > & sparsity) inline
initialize the pattern
Initializes the pattern given a binary matrix. A "true" entry in the matrix means that there is a non-zero entry in the Jacobian.
Parameters
sparsity The sparsity pattern
Template Parameters
ROWS number of rows in matrix
COLS number of columns in matrix
References clearWork(), i, and sparsity().
Referenced by ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateHessianSource(), ct::core::DerivativesCppadCG< IN_DIM, OUT_DIM >::generateJacobianSource(), ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::setupSparsityA(), and ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::setupSparsityB().
const CppAD::vector<bool>& ct::core::internal::SparsityPattern::sparsity () const inline
returns the sparsity pattern as a vector (row-major)
Returns
sparsity pattern vector
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeA(), ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeB(), ct::core::internal::CGHelpers::generateHessianSource(), ct::core::internal::CGHelpers::generateJacobianSource(), and initPattern().
const CppAD::vector<size_t>& ct::core::internal::SparsityPattern::row () const inline
returns the row indices of a row-column sparsity representation
In a row-column representation, only the non-zero entries get saved. This method returns the row indices of the row-column representation. Since there can be several non-zero entries in the same row, the same row index can appear repeatedly in this vector.
Returns
row indeces of row-column representation
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeA(), ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeB(), ct::core::internal::CGHelpers::generateHessianSource(), and ct::core::internal::CGHelpers::generateJacobianSource().
const CppAD::vector<size_t>& ct::core::internal::SparsityPattern::col () const inline
returns the column indices of a row-column sparsity representation
In a row-column representation, only the non-zero entries get saved. This method returns the column indices of the row-column representation. Since there can be several non-zero entries in the same column, the same column index can appear repeatedly in this vector.
Returns
column indeces of row-column representation
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeA(), ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeB(), ct::core::internal::CGHelpers::generateHessianSource(), and ct::core::internal::CGHelpers::generateJacobianSource().
CppAD::sparse_jacobian_work& ct::core::internal::SparsityPattern::workJacobian () inline
work area for CppAD
CppAD can make use of previous results from a sparsity analysis. This method returns the "work" area of CppAD sparsity
Returns
CppAD sparsity work
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeA(), ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeB(), and ct::core::internal::CGHelpers::generateJacobianSource().
CppAD::sparse_hessian_work& ct::core::internal::SparsityPattern::workHessian () inline
Referenced by ct::core::internal::CGHelpers::generateHessianSource().
void ct::core::internal::SparsityPattern::clearWork () inline
Clears the cppad internal work done on the sparsity pattern.
Referenced by ct::core::DynamicsLinearizerADCG< STATE_DIM, CONTROL_DIM, ADCGScalar, ADCGScalar >::generateCode(), initPattern(), ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::setupSparsityA(), and ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, ADScalar, int >::setupSparsityB().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/internal/autodiff/SparsityPattern.h