ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR > Class Template Reference
ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR > Class Template Reference
This class wraps the symplectic integrators from boost to this toolbox.
#include <IntegratorSymplectic.h>
Public Types
typedef std::shared_ptr< EventHandler< POS_DIM+VEL_DIM, SCALAR > > EventHandlerPtr
typedef std::vector< EventHandlerPtr, Eigen::aligned_allocator< EventHandlerPtr > > EventHandlerPtrVector
Public Member Functions
IntegratorSymplectic (const std::shared_ptr< SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >> system, const EventHandlerPtrVector &eventHandlers=EventHandlerPtrVector(0))
The constructor. This integrator can only treat symplectic systems.
IntegratorSymplectic (const std::shared_ptr< SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >> system, const EventHandlerPtr &eventHandler)
The constructor. This integrator can only treat symplectic systems.
void integrate_n_steps (StateVector< POS_DIM+VEL_DIM, SCALAR > &state, const SCALAR &startTime, size_t numSteps, SCALAR dt, StateVectorArray< POS_DIM+VEL_DIM, SCALAR > &stateTrajectory, tpl::TimeArray< SCALAR > &timeTrajectory)
Equidistant integration based on number of time steps and step length.
void integrate_n_steps (StateVector< POS_DIM+VEL_DIM, SCALAR > &state, const SCALAR &startTime, size_t numSteps, SCALAR dt)
Equidistant integration based on number of time steps and step length.
void reset ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::pair< Eigen::Matrix< SCALAR, POS_DIM, 1 >, Eigen::Matrix< SCALAR, VEL_DIM, 1 > > pair_t
Detailed Description
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper, typename SCALAR = double>
class ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >
This class wraps the symplectic integrators from boost to this toolbox.
Template Parameters
POS_DIM The position dimension
VEL_DIM The velocity dimension
CONTROL_DIM The control dimension
Stepper The stepper type
Member Typedef Documentation
EventHandlerPtr
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper, typename SCALAR = double> typedef std::shared_ptr<EventHandler<POS_DIM + VEL_DIM, SCALAR> > ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::EventHandlerPtr
EventHandlerPtrVector
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper, typename SCALAR = double> typedef std::vector<EventHandlerPtr, Eigen::aligned_allocator<EventHandlerPtr> > ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::EventHandlerPtrVector
Constructor & Destructor Documentation
IntegratorSymplectic() [1/2]
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper , typename SCALAR > ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::IntegratorSymplectic (const std::shared_ptr< SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >> system, const EventHandlerPtrVector & eventHandlers = EventHandlerPtrVector(0))
The constructor. This integrator can only treat symplectic systems.
Parameters
[in] system A core::system
IntegratorSymplectic() [2/2]
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper , typename SCALAR > ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::IntegratorSymplectic (const std::shared_ptr< SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >> system, const EventHandlerPtr & eventHandler)
The constructor. This integrator can only treat symplectic systems.
Parameters
[in] system A core::system
Member Function Documentation
integrate_n_steps() [1/2]
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper , typename SCALAR > void ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::integrate_n_steps (StateVector< POS_DIM+VEL_DIM, SCALAR > & state, const SCALAR & startTime, size_t numSteps, SCALAR dt, StateVectorArray< POS_DIM+VEL_DIM, SCALAR > & stateTrajectory, tpl::TimeArray< SCALAR > & timeTrajectory)
Equidistant integration based on number of time steps and step length.
Parameters
[in,out] state The initial state, gets updated during integration
[in] startTime The starting time of the integration
[in] numSteps The number of integration steps
[in] dt The integration time step
[out] stateTrajectory The resulting state trajectory
[out] timeTrajectory The resulting time trajectory
References i, ct::core::Observer< STATE_DIM, SCALAR >::observeInternal(), and ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::pair_t.
integrate_n_steps() [2/2]
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper , typename SCALAR > void ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::integrate_n_steps (StateVector< POS_DIM+VEL_DIM, SCALAR > & state, const SCALAR & startTime, size_t numSteps, SCALAR dt)
Equidistant integration based on number of time steps and step length.
Parameters
[in,out] state The initial state, gets updated during integration
[in] startTime The starting time of the integration
[in] numSteps The number of integration steps
[in] dt The integration time step
References i, ct::core::Observer< STATE_DIM, SCALAR >::observeInternal(), and ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::pair_t.
reset()
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper , typename SCALAR > void ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::reset ()
References ct::core::Observer< STATE_DIM, SCALAR >::reset(), and x.
Member Data Documentation
pair_t
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, class Stepper, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::pair<Eigen::Matrix<SCALAR, POS_DIM, 1>, Eigen::Matrix<SCALAR, VEL_DIM, 1> > ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::pair_t
Referenced by ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::integrate_n_steps().
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/integration/IntegratorSymplectic.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/integration/IntegratorSymplectic-impl.h