Widget Class Reference
Widget Class Reference
#include <widget.h>
Public Member Functions
Widget (int number, const std::string &name)
~Widget ()
float GetFloatValue () const
int GetIntValue () const
std::string GetStringValue () const
void GetCharPtrValue (char *buffer, size_t max_size) const
Constructor & Destructor Documentation
Widget::Widget (int number, const std::string & name)
Widget::~Widget ()
Member Function Documentation
float Widget::GetFloatValue () const
Referenced by TEST().
int Widget::GetIntValue () const
Referenced by TEST().
std::string Widget::GetStringValue () const
Referenced by TEST().
void Widget::GetCharPtrValue (char * buffer, size_t max_size) const
Referenced by TEST().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/xcode/Samples/FrameworkSample/widget.h
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/xcode/Samples/FrameworkSample/widget.cc