googletest-json-output-unittest.GTestJsonOutputUnitTest Class Reference
googletest-json-output-unittest.GTestJsonOutputUnitTest Class Reference
Public Member Functions
def testNonEmptyJsonOutput (self)
def testEmptyJsonOutput (self)
def testTimestampValue (self)
def testDefaultOutputFile (self)
def testSuppressedJsonOutput (self)
def testFilteredTestJsonOutput (self)
Detailed Description
Unit test for Google Test's JSON output functionality.
Member Function Documentation
def googletest-json-output-unittest.GTestJsonOutputUnitTest.testNonEmptyJsonOutput (self)
Verifies JSON output for a Google Test binary with non-empty output.
Runs a test program that generates a non-empty JSON output, and
tests that the JSON output is expected.
References googletest-json-output-unittest.GTestJsonOutputUnitTest._TestJsonOutput().
def googletest-json-output-unittest.GTestJsonOutputUnitTest.testEmptyJsonOutput (self)
Verifies JSON output for a Google Test binary without actual tests.
Runs a test program that generates an empty JSON output, and
tests that the JSON output is expected.
References googletest-json-output-unittest.GTestJsonOutputUnitTest._TestJsonOutput().
def googletest-json-output-unittest.GTestJsonOutputUnitTest.testTimestampValue (self)
Checks whether the timestamp attribute in the JSON output is valid.
Runs a test program that generates an empty JSON output, and checks if
the timestamp attribute in the testsuites tag is valid.
References googletest-json-output-unittest.GTestJsonOutputUnitTest._GetJsonOutput().
def googletest-json-output-unittest.GTestJsonOutputUnitTest.testDefaultOutputFile (self)
Verifies the default output file name.
Confirms that Google Test produces an JSON output file with the expected
default name if no name is explicitly specified.
References gtest_test_utils.GetTempDir(), and gtest_test_utils.GetTestExecutablePath().
def googletest-json-output-unittest.GTestJsonOutputUnitTest.testSuppressedJsonOutput (self)
Verifies that no JSON output is generated.
Tests that no JSON file is generated if the default JSON listener is
shut down before RUN_ALL_TESTS is invoked.
References gtest_test_utils.GetTempDir().
def googletest-json-output-unittest.GTestJsonOutputUnitTest.testFilteredTestJsonOutput (self)
Verifies JSON output when a filter is applied.
Runs a test program that executes only some tests and verifies that
non-selected tests do not show up in the JSON output.
References googletest-json-output-unittest.GTestJsonOutputUnitTest._GetJsonOutput(), googletest-json-output-unittest.GTestJsonOutputUnitTest._TestJsonOutput(), gtest_test_utils.GetTempDir(), gtest_test_utils.GetTestExecutablePath(), gtest_test_utils.Main(), and gtest_json_test_utils.normalize().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/googletest-json-output-unittest.py