ct::core::Observer< STATE_DIM, SCALAR > Class Template Reference
ct::core::Observer< STATE_DIM, SCALAR > Class Template Reference
Observer for Integrator.
#include <Observer.h>
Public Types
typedef std::vector< std::shared_ptr< EventHandler< STATE_DIM, SCALAR > >, Eigen::aligned_allocator< std::shared_ptr< EventHandler< STATE_DIM, SCALAR > > > > EventHandlerPtrVector
Public Member Functions
Observer (const EventHandlerPtrVector &eventHandlers)
default constructor
void reset ()
reset the observer
void observe (const StateVector< STATE_DIM, SCALAR > &x, const SCALAR &t)
void log (const StateVector< STATE_DIM, SCALAR > &x, const SCALAR &t)
void observeInternal (const StateVector< STATE_DIM, SCALAR > &x, const SCALAR &t)
Friends
class Integrator< STATE_DIM, SCALAR >
Detailed Description
template<size_t STATE_DIM, typename SCALAR = double>
class ct::core::Observer< STATE_DIM, SCALAR >
Observer for Integrator.
Implements a general observer as required by boost::odeint. This wraps all event handlers and calls them. Furthermore, this class records state and time trajectories during integration.
Template Parameters
STATE_DIM The size of the state vector
Member Typedef Documentation
template<size_t STATE_DIM, typename SCALAR = double> typedef std::vector<std::shared_ptr<EventHandler<STATE_DIM, SCALAR> >, Eigen::aligned_allocator<std::shared_ptr<EventHandler<STATE_DIM, SCALAR> > > > ct::core::Observer< STATE_DIM, SCALAR >::EventHandlerPtrVector
Constructor & Destructor Documentation
template<size_t STATE_DIM, typename SCALAR > ct::core::Observer< STATE_DIM, SCALAR >::Observer (const EventHandlerPtrVector & eventHandlers)
default constructor
Parameters
eventHandlers vector of event handlers
References ct::core::Observer< STATE_DIM, SCALAR >::log(), ct::core::Observer< STATE_DIM, SCALAR >::observe(), t, and x.
Member Function Documentation
template<size_t STATE_DIM, typename SCALAR > void ct::core::Observer< STATE_DIM, SCALAR >::reset ()
reset the observer
References i.
Referenced by ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::reset().
template<size_t STATE_DIM, typename SCALAR> void ct::core::Observer< STATE_DIM, SCALAR >::observe (const StateVector< STATE_DIM, SCALAR > & x, const SCALAR & t)
References i.
Referenced by ct::core::Observer< STATE_DIM, SCALAR >::Observer().
template<size_t STATE_DIM, typename SCALAR> void ct::core::Observer< STATE_DIM, SCALAR >::log (const StateVector< STATE_DIM, SCALAR > & x, const SCALAR & t)
Referenced by ct::core::Observer< STATE_DIM, SCALAR >::Observer().
template<size_t STATE_DIM, typename SCALAR> void ct::core::Observer< STATE_DIM, SCALAR >::observeInternal (const StateVector< STATE_DIM, SCALAR > & x, const SCALAR & t)
References i.
Referenced by ct::core::IntegratorSymplectic< POS_DIM, VEL_DIM, CONTROL_DIM, Stepper, SCALAR >::integrate_n_steps().
Friends And Related Function Documentation
template<size_t STATE_DIM, typename SCALAR = double> friend class Integrator< STATE_DIM, SCALAR > friend
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/integration/Observer.h
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/integration/Observer-impl.h