ct::core::plotQwt::Figure Class Reference
ct::core::plotQwt::Figure Class Reference
#include <plotQwt.h>
Public Member Functions
Figure ()
void plot (const std::vector< double > &y)
void draw ()
void hold (bool hold=true)
void title (const std::string &title)
void setDimensions (size_t dimX_pixels, size_t dimY_pixels)
Constructor & Destructor Documentation
Figure()
ct::core::plotQwt::Figure::Figure () inline
Referenced by ct::core::plotQwt::detail::_application::createFigure().
Member Function Documentation
plot()
void ct::core::plotQwt::Figure::plot (const std::vector< double > & y) inline
References x.
draw()
void ct::core::plotQwt::Figure::draw () inline
hold()
void ct::core::plotQwt::Figure::hold (bool hold = true) inline
References hold().
Referenced by hold().
title()
void ct::core::plotQwt::Figure::title (const std::string & title) inline
setDimensions()
void ct::core::plotQwt::Figure::setDimensions (size_t dimX_pixels, size_t dimY_pixels) inline
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/plot/plotQwt.h