ct::core::generated::TestDiscreteNonlinearSystemLinearized Class Reference
ct::core::generated::TestDiscreteNonlinearSystemLinearized Class Reference
#include <TestDiscreteNonlinearSystemLinearized.h>
Public Types
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::state_matrix_t state_matrix_t
typedef Base::state_control_matrix_t state_control_matrix_t
Public Types inherited from ct::core::DiscreteLinearSystem< 2, 1, double >
typedef Base::time_t time_t
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef StateMatrix< STATE_DIM, double > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, double > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >
typedef DiscreteSystem< STATE_DIM, CONTROL_DIM, double > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::time_t time_t
Public Types inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, double >
typedef int time_t
the type of the time variable
typedef StateVector< STATE_DIM, double > state_vector_t
typedef ControlVector< CONTROL_DIM, double > control_vector_t
Public Member Functions
TestDiscreteNonlinearSystemLinearized (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
TestDiscreteNonlinearSystemLinearized (const TestDiscreteNonlinearSystemLinearized &other)
virtual ~TestDiscreteNonlinearSystemLinearized ()
virtual TestDiscreteNonlinearSystemLinearized * clone () const override
deep cloning
void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t numSteps, state_matrix_t &A, state_control_matrix_t &B) override
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const int t=0)
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const int t=0)
Public Member Functions inherited from ct::core::DiscreteLinearSystem< 2, 1, double >
DiscreteLinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~DiscreteLinearSystem ()
destructor
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext) override
compute the system dynamics
virtual void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t subSteps, state_matrix_t &A, state_control_matrix_t &B)=0
retrieve discrete-time linear system matrices A and B.
void getAandB (const state_vector_t &x, const control_vector_t &u, const int n, state_matrix_t &A, state_control_matrix_t &B)
Public Member Functions inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >
DiscreteControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
DiscreteControlledSystem (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, double >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
DiscreteControlledSystem (const ControlledSystem< STATE_DIM, CONTROL_DIM, double > &arg)
copy constructor
virtual ~DiscreteControlledSystem ()=default
destructor
void setController (const std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, double >> &controller)
set a new controller
void getController (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, double >> &controller) const
get the controller instance
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, double > > getController ()
get the controller instace
virtual void propagateDynamics (const state_vector_t &state, const time_t n, state_vector_t &stateNext) override
propagates the system dynamics forward by one step
Public Member Functions inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, double >
DiscreteSystem (const SYSTEM_TYPE &type=GENERAL)
constructor
virtual ~DiscreteSystem ()
desctructor
SYSTEM_TYPE getType () const
get the type of system
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::DiscreteLinearSystem< 2, 1, double > Base
Public Attributes inherited from ct::core::DiscreteLinearSystem< 2, 1, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double > Base
Public Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double > > Ptr
Additional Inherited Members
Protected Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, double > > controller_
the controller instance
Protected Attributes inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, double >
SYSTEM_TYPE type_
type of system
Member Typedef Documentation
state_vector_t
typedef Base::state_vector_t ct::core::generated::TestDiscreteNonlinearSystemLinearized::state_vector_t
control_vector_t
typedef Base::control_vector_t ct::core::generated::TestDiscreteNonlinearSystemLinearized::control_vector_t
state_matrix_t
typedef Base::state_matrix_t ct::core::generated::TestDiscreteNonlinearSystemLinearized::state_matrix_t
state_control_matrix_t
typedef Base::state_control_matrix_t ct::core::generated::TestDiscreteNonlinearSystemLinearized::state_control_matrix_t
Constructor & Destructor Documentation
TestDiscreteNonlinearSystemLinearized() [1/2]
ct::core::generated::TestDiscreteNonlinearSystemLinearized::TestDiscreteNonlinearSystemLinearized (const ct::core::SYSTEM_TYPE & type = ct::core::SYSTEM_TYPE::GENERAL) inline
Referenced by clone().
TestDiscreteNonlinearSystemLinearized() [2/2]
ct::core::generated::TestDiscreteNonlinearSystemLinearized::TestDiscreteNonlinearSystemLinearized (const TestDiscreteNonlinearSystemLinearized & other) inline
~TestDiscreteNonlinearSystemLinearized()
virtual ct::core::generated::TestDiscreteNonlinearSystemLinearized::~TestDiscreteNonlinearSystemLinearized () inline virtual
Member Function Documentation
clone()
virtual TestDiscreteNonlinearSystemLinearized* ct::core::generated::TestDiscreteNonlinearSystemLinearized::clone () const inline override virtual
deep cloning
Implements ct::core::DiscreteLinearSystem< 2, 1, double >.
References TestDiscreteNonlinearSystemLinearized().
getAandB()
void ct::core::generated::TestDiscreteNonlinearSystemLinearized::getAandB (const state_vector_t & x, const control_vector_t & u, const state_vector_t & x_next, const int n, size_t numSteps, state_matrix_t & A, state_control_matrix_t & B) inline override
References getDerivativeControl(), getDerivativeState(), t, u, and x.
getDerivativeState()
const TestDiscreteNonlinearSystemLinearized::state_matrix_t & ct::core::generated::TestDiscreteNonlinearSystemLinearized::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const int t = 0) virtual
Referenced by getAandB().
getDerivativeControl()
const TestDiscreteNonlinearSystemLinearized::state_control_matrix_t & ct::core::generated::TestDiscreteNonlinearSystemLinearized::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const int t = 0) virtual
Referenced by getAandB().
Member Data Documentation
Base
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::DiscreteLinearSystem<2, 1, double> ct::core::generated::TestDiscreteNonlinearSystemLinearized::Base
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/generated/TestDiscreteNonlinearSystemLinearized.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/generated/TestDiscreteNonlinearSystemLinearized_A.cpp
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/generated/TestDiscreteNonlinearSystemLinearized_B.cpp