testing::internal::UnitTestHelper Class Reference
testing::internal::UnitTestHelper Class Reference
Static Public Member Functions
static TestSuite const ** GetSortedTestSuites ()
static const TestSuite * FindTestSuite (const char *name)
static TestInfo const ** GetSortedTests (const TestSuite *test_suite)
Member Function Documentation
static TestSuite const** testing::internal::UnitTestHelper::GetSortedTestSuites () inline static
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestSuite(), i, and testing::UnitTest::total_test_suite_count().
Referenced by testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::TEST().
static const TestSuite* testing::internal::UnitTestHelper::FindTestSuite (const char * name) inline static
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestSuite(), i, testing::TestSuite::name(), and testing::UnitTest::total_test_suite_count().
Referenced by testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::TEST().
static TestInfo const** testing::internal::UnitTestHelper::GetSortedTests (const TestSuite * test_suite) inline static
References testing::gmock_generated_actions_test::Dummy(), testing::TestSuite::GetTestInfo(), i, testing::internal::kTypedTests, testing::internal::kTypedTestSuites, testing::TestSuite::total_test_count(), testing::TYPED_TEST(), and testing::TYPED_TEST_SUITE().
Referenced by testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::TEST().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/gtest-unittest-api_test.cc