testing::TestSuite Class Reference
testing::TestSuite Class Reference
#include <gtest.h>
Public Member Functions
TestSuite (const char *name, const char *a_type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc)
virtual ~TestSuite ()
const char * name () const
const char * type_param () const
bool should_run () const
int successful_test_count () const
int skipped_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int test_to_run_count () const
int total_test_count () const
bool Passed () const
bool Failed () const
TimeInMillis elapsed_time () const
const TestInfo * GetTestInfo (int i) const
const TestResult & ad_hoc_test_result () const
Friends
class Test
class internal::UnitTestImpl
Constructor & Destructor Documentation
testing::TestSuite::TestSuite (const char * name, const char * a_type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc)
testing::TestSuite::~TestSuite () virtual
Member Function Documentation
const char* testing::TestSuite::name () const inline
Referenced by testing::internal::UnitTestHelper::FindTestSuite(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::TestSuiteNameIs::operator()(), and testing::internal::TEST().
const char* testing::TestSuite::type_param () const inline
Referenced by testing::internal::ColoredPrintf(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart(), and testing::internal::TEST().
bool testing::TestSuite::should_run () const inline
Referenced by testing::internal::Random::Generate(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), and testing::internal::TEST().
int testing::TestSuite::successful_test_count () const
Referenced by testing::internal::GetTestTypeId().
int testing::TestSuite::skipped_test_count () const
Referenced by testing::internal::GetTestTypeId(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), and testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd().
int testing::TestSuite::failed_test_count () const
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::GetTestTypeId(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
int testing::TestSuite::reportable_disabled_test_count () const
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::GetTestTypeId(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
int testing::TestSuite::disabled_test_count () const
Referenced by testing::internal::GetTestTypeId(), and testing::internal::TEST().
int testing::TestSuite::reportable_test_count () const
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::GetTestTypeId(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
int testing::TestSuite::test_to_run_count () const
Referenced by testing::internal::GetTestTypeId(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart(), and testing::internal::TEST().
int testing::TestSuite::total_test_count () const
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::UnitTestHelper::GetSortedTests(), GetTestInfo(), testing::TestInfoTest::GetTestInfo(), testing::internal::GetTestTypeId(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::JsonUnitTestResultPrinter::PrintJsonTestList(), testing::internal::XmlUnitTestResultPrinter::PrintXmlTestsList(), and testing::internal::TEST().
bool testing::TestSuite::Passed () const inline
Referenced by testing::internal::Random::Generate().
bool testing::TestSuite::Failed () const inline
Referenced by testing::internal::Random::Generate().
TimeInMillis testing::TestSuite::elapsed_time () const inline
References i.
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
const TestInfo * testing::TestSuite::GetTestInfo (int i) const
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::COLOR_YELLOW, count, testing::internal::FormatFileLocation(), testing::UnitTest::GetInstance(), testing::internal::GetTimeInMillis(), testing::internal::HandleExceptionsInMethodIfSupported(), i, internal::UnitTestImpl, testing::UnitTest::listeners(), testing::TestEventListener::OnTestCaseEnd(), testing::TestEventListener::OnTestCaseStart(), testing::TestEventListener::OnTestSuiteEnd(), testing::TestEventListener::OnTestSuiteStart(), testing::internal::StreamableToString(), total_test_count(), and upload::type.
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::UnitTestHelper::GetSortedTests(), testing::TestInfoTest::GetTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::TEST(), and TEST().
const TestResult& testing::TestSuite::ad_hoc_test_result () const inline
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), and TEST_F().
Friends And Related Function Documentation
friend class Test friend
friend class internal::UnitTestImpl friend
Referenced by GetTestInfo().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/include/gtest/gtest.h
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc