ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
interface class for a general switched linear system or linearized system
#include <SwitchedLinearSystem.h>
Public Types
typedef Switched< LinearSystemPtr > SwitchedLinearSystems
typedef ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
typedef Base::time_t time_t
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
state vector type
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
input vector type
typedef StateMatrix< STATE_DIM, SCALAR > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef Base::time_t time_t
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
state vector type
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
input vector type
typedef StateMatrix< STATE_DIM, SCALAR > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, SCALAR >
typedef SCALAR time_t
the type of the time variable
Public Member Functions
SwitchedLinearSystem (const SwitchedLinearSystems &switchedLinearSystems, const ContinuousModeSequence &continuousModeSequence, const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
SwitchedLinearSystem (const SwitchedLinearSystem &arg)
copy constructor
virtual ~SwitchedLinearSystem ()
destructor
virtual SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override
deep cloning
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0)) override
get the A matrix of a linear system
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0)) override
get the B matrix of a linear system
Public Member Functions inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
LinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~LinearSystem ()
destructor
virtual void computeControlledDynamics (const state_vector_t &state, const time_t &t, const control_vector_t &control, state_vector_t &derivative) override
compute the system dynamics
virtual void getDerivatives (state_matrix_t &A, state_control_matrix_t &B, const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))
Get both linear system matrices A and B in one call.
Public Member Functions inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
ControlledSystem (const ControlledSystem &arg)
copy constructor
virtual ~ControlledSystem ()
destructor
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative) override
compute the dynamics of the system
virtual void computeControlledDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< STATE_DIM, SCALAR > &derivative)=0
ControlVector< CONTROL_DIM, SCALAR > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, SCALAR >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
System (const System &other)
copy constructor
virtual ~System ()
destructor
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative)=0
computes the system dynamics
SYSTEM_TYPE getType () const
get the type of system
virtual bool isSymplectic () const
Determines if the system is in symplectic form.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > > LinearSystemPtr
Public Attributes inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, SCALAR > Base
Public Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef SCALAR S
the scalar type
Additional Inherited Members
Protected Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
ControlVector< CONTROL_DIM, SCALAR > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
interface class for a general switched linear system or linearized system
Defines the interface for a switched linear system
Template Parameters
STATE_DIM size of state vector
CONTROL_DIM size of input vector
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Switched<LinearSystemPtr> ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearSystems
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef ControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::Base
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::time_t ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::time_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef StateVector<STATE_DIM, SCALAR> ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
state vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef ControlVector<CONTROL_DIM, SCALAR> ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
input vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef StateMatrix<STATE_DIM, SCALAR> ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
state Jacobian type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef StateControlMatrix<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::state_control_matrix_t
input Jacobian type
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearSystem (const SwitchedLinearSystems & switchedLinearSystems, const ContinuousModeSequence & continuousModeSequence, const ct::core::SYSTEM_TYPE & type = ct::core::SYSTEM_TYPE::GENERAL) inline
default constructor
Parameters
type system type
Referenced by ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::clone().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearSystem (const SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > & arg) inline
copy constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::~SwitchedLinearSystem () inline virtual
destructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual SwitchedLinearSystem<STATE_DIM, CONTROL_DIM, SCALAR>* ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const inline override virtual
deep cloning
Implements ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedLinearSystem().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual const state_matrix_t& ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const time_t t = time_t(0.0)) inline override virtual
get the A matrix of a linear system
Parameters
x state vector (required for linearizing non-linear systems, ignored for pure linear system)
u input vector (required for linearizing non-linear systems, ignored for pure linear system)
t current time
Returns
A matrix
Implements ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::PhaseSequence< Phase, Time >::getPhaseFromTime(), and t.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual const state_control_matrix_t& ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const time_t t = time_t(0.0)) inline override virtual
get the B matrix of a linear system
Parameters
x state vector (required for linearizing non-linear systems, ignored for pure linear system)
u input vector (required for linearizing non-linear systems, ignored for pure linear system)
t current time
Returns
B matrix
Implements ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::PhaseSequence< Phase, Time >::getPhaseFromTime(), and t.
Referenced by TEST().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr<LinearSystem<STATE_DIM, CONTROL_DIM, SCALAR> > ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::LinearSystemPtr
Referenced by TEST().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/systems/continuous_time/linear/SwitchedLinearSystem.h