ct::core::Interpolation< Data_T, Alloc_Data, SCALAR > Class Template Reference
ct::core::Interpolation< Data_T, Alloc_Data, SCALAR > Class Template Reference
Class that performs interpolation of data in time.
#include <Interpolation.h>
Public Member Functions
Interpolation (const InterpolationType &type=LIN)
Default constructor.
Interpolation (const Interpolation &arg)
Copy Constructor.
void interpolate (const tpl::TimeArray< SCALAR > &timeArray, const DiscreteArray_t &dataArray, const SCALAR &enquiryTime, Data_T &enquiryData, int greatestLessTimeStampIndex=-1)
This method performs the interpolation.
int getGreatestLessTimeStampIndex ()
access the greatest index which is smaller than the inquired interpolation time
InterpolationType getInterpolationType () const
get the employed interpolation type
void changeInterpolationType (const InterpolationType &type)
change the interpolation type
int findIndex (const tpl::TimeArray< SCALAR > &timeArray, const SCALAR &enquiryTime)
find an index corresponding to a certain inquiry time
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteArray< Data_T, Alloc_Data > DiscreteArray_t
Protected Attributes
int index_
InterpolationType type_
Detailed Description
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double>
class ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >
Class that performs interpolation of data in time.
This class performs interpolation of a data array based on timestamps
Template Parameters
Data_T the data type for interpolation, e.g. a scalar or a StateVector
Alloc_Data An optional allocator for the data type
Alloc_Time An optional allocator for the time data type
Examples:
InterpolationTest.cpp.
Constructor & Destructor Documentation
Interpolation() [1/2]
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::Interpolation (const InterpolationType & type = LIN) inline
Default constructor.
Warning
This does not initialize the underlying data or time series and thus all evaluating calls will fail.
Parameters
type The interpolation strategy to use
Interpolation() [2/2]
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::Interpolation (const Interpolation< Data_T, Alloc_Data, SCALAR > & arg) inline
Copy Constructor.
Member Function Documentation
interpolate()
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> void ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::interpolate (const tpl::TimeArray< SCALAR > & timeArray, const DiscreteArray_t & dataArray, const SCALAR & enquiryTime, Data_T & enquiryData, int greatestLessTimeStampIndex = -1) inline
This method performs the interpolation.
Parameters
timeArray timing information of the data points
dataArray the data points in form of a DiscreteArray
enquiryTime the time where to evaluate the interpolation
enquiryData the result of the interpolation
greatestLessTimeStampIndex the smallest index corresponding to a time smaller than the inquired Time
Referenced by ct::core::DiscreteTrajectoryBase< STATE_DIM, CONTROL_DIM, SCALAR >::eval(), and TEST().
getGreatestLessTimeStampIndex()
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> int ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::getGreatestLessTimeStampIndex () inline
access the greatest index which is smaller than the inquired interpolation time
getInterpolationType()
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> InterpolationType ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::getInterpolationType () const inline
get the employed interpolation type
Referenced by ct::core::DiscreteTrajectoryBase< STATE_DIM, CONTROL_DIM, SCALAR >::operator=().
changeInterpolationType()
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> void ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::changeInterpolationType (const InterpolationType & type) inline
change the interpolation type
Referenced by ct::core::DiscreteTrajectoryBase< STATE_DIM, CONTROL_DIM, SCALAR >::operator=(), and ct::core::DiscreteTrajectoryBase< STATE_DIM, CONTROL_DIM, SCALAR >::setInterpolationType().
findIndex()
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> int ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::findIndex (const tpl::TimeArray< SCALAR > & timeArray, const SCALAR & enquiryTime) inline
find an index corresponding to a certain inquiry time
Referenced by ct::core::DiscreteTrajectoryBase< STATE_DIM, CONTROL_DIM, SCALAR >::getIndexFromTime(), and ct::core::Interpolation< CONTROL_DIM, SCALAR, double >::interpolate().
Member Data Documentation
DiscreteArray_t
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteArray<Data_T, Alloc_Data> ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::DiscreteArray_t
index_
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> int ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::index_ protected
Referenced by ct::core::Interpolation< CONTROL_DIM, SCALAR, double >::findIndex(), ct::core::Interpolation< CONTROL_DIM, SCALAR, double >::getGreatestLessTimeStampIndex(), and ct::core::Interpolation< CONTROL_DIM, SCALAR, double >::interpolate().
type_
template<typename Data_T, class Alloc_Data = Eigen::aligned_allocator<Data_T>, typename SCALAR = double> InterpolationType ct::core::Interpolation< Data_T, Alloc_Data, SCALAR >::type_ protected
Referenced by ct::core::Interpolation< CONTROL_DIM, SCALAR, double >::changeInterpolationType(), ct::core::Interpolation< CONTROL_DIM, SCALAR, double >::getInterpolationType(), and ct::core::Interpolation< CONTROL_DIM, SCALAR, double >::interpolate().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/common/Interpolation.h