testing::TestInfo Class Reference
testing::TestInfo Class Reference
#include <gtest.h>
Public Member Functions
~TestInfo ()
const char * test_suite_name () const
const char * test_case_name () const
const char * name () const
const char * type_param () const
const char * value_param () const
const char * file () const
int line () const
bool is_in_another_shard () const
bool should_run () const
bool is_reportable () const
const TestResult * result () const
Friends
class Test
class TestSuite
class internal::UnitTestImpl
class internal::StreamingListenerTest
TestInfo * internal::MakeAndRegisterTestInfo (const char *test_suite_name, const char *name, const char *type_param, const char *value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc, internal::TestFactoryBase *factory)
Constructor & Destructor Documentation
testing::TestInfo::~TestInfo ()
Member Function Documentation
const char* testing::TestInfo::test_suite_name () const inline
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestStart(), and testing::internal::ReportFailureInUnknownLocation().
const char* testing::TestInfo::test_case_name () const inline
Referenced by testing::TEST_F().
const char* testing::TestInfo::name () const inline
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::TestInfoTest::GetTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestStart(), testing::internal::ReportFailureInUnknownLocation(), testing::internal::ReportInvalidTestSuiteType(), testing::internal::ShouldRunTestOnShard(), and testing::TEST_F().
const char* testing::TestInfo::type_param () const inline
Referenced by testing::internal::ColoredPrintf(), testing::internal::FormatEpochTimeInMillisAsIso8601(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
const char* testing::TestInfo::value_param () const inline
Referenced by testing::internal::ColoredPrintf(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), and testing::internal::ShouldRunTestOnShard().
const char* testing::TestInfo::file () const inline
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
int testing::TestInfo::line () const inline
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
bool testing::TestInfo::is_in_another_shard () const inline
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601().
bool testing::TestInfo::should_run () const inline
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
bool testing::TestInfo::is_reportable () const inline
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
const TestResult* testing::TestInfo::result () const inline
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::TestInfoTest::GetTestResult(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), and testing::internal::FinalSuccessChecker::TearDown().
Friends And Related Function Documentation
friend class Test friend
friend class TestSuite friend
friend class internal::UnitTestImpl friend
friend class internal::StreamingListenerTest friend
TestInfo* internal::MakeAndRegisterTestInfo (const char * test_suite_name, const char * name, const char * type_param, const char * value_param, internal::CodeLocation code_location, internal::TypeId fixture_class_id, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc, internal::TestFactoryBase * factory) friend
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/include/gtest/gtest.h
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc