ct::core::generated::TestForwardZero Class Reference
ct::core::generated::TestForwardZero Class Reference
#include <TestForwardZero.h>
Public Types
typedef Eigen::Matrix< double, 3, 1 > X_TYPE
Public Types inherited from ct::core::Derivatives< 3, 2, double >
typedef Eigen::Matrix< double, IN_DIM, 1 > IN_TYPE
function input vector type
typedef Eigen::Matrix< double, OUT_DIM, 1 > OUT_TYPE
function output vector type
typedef Eigen::Matrix< double, OUT_DIM, IN_DIM > JAC_TYPE
typedef Eigen::Matrix< double, IN_DIM, IN_DIM > HES_TYPE
Public Member Functions
TestForwardZero ()
TestForwardZero (const TestForwardZero &other)
virtual ~TestForwardZero ()
TestForwardZero * clone () const override
deep copy for derived classes
OUT_TYPE forwardZero (const Eigen::VectorXd &x_in) override
Evaluates the method itself.
Public Member Functions inherited from ct::core::Derivatives< 3, 2, double >
Derivatives ()
virtual ~Derivatives ()
default destructor
virtual JAC_TYPE jacobian (const Eigen::VectorXd &x)
Evaluates the jacobian with respect to the input.
virtual void sparseJacobian (const Eigen::VectorXd &x, Eigen::VectorXd &jac, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
Returns the evaluated jacobian in sparse format.
virtual Eigen::VectorXd sparseJacobianValues (const Eigen::VectorXd &x)
Returns the non zero values of the jacobian.
virtual HES_TYPE hessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Evaluates the hessian (2nd order derivatives with respect to input) of the method. In case of a vector valued function, the method returns the weighted sum of the hessians with weights w.
virtual void sparseHessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda, Eigen::VectorXd &hes, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
Returns the weighted sum of hessian of the problem in sparse format.
virtual Eigen::VectorXd sparseHessianValues (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Returns the non zero elements of the hessian of the problem.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix< double, 2, 1 > OUT_TYPE
Member Typedef Documentation
X_TYPE
typedef Eigen::Matrix<double, 3, 1> ct::core::generated::TestForwardZero::X_TYPE
Constructor & Destructor Documentation
TestForwardZero() [1/2]
ct::core::generated::TestForwardZero::TestForwardZero () inline
Referenced by clone().
TestForwardZero() [2/2]
ct::core::generated::TestForwardZero::TestForwardZero (const TestForwardZero & other) inline
~TestForwardZero()
virtual ct::core::generated::TestForwardZero::~TestForwardZero () inline virtual
Member Function Documentation
clone()
TestForwardZero* ct::core::generated::TestForwardZero::clone () const inline override virtual
deep copy for derived classes
Implements ct::core::Derivatives< 3, 2, double >.
References forwardZero(), and TestForwardZero().
forwardZero()
TestForwardZero::OUT_TYPE ct::core::generated::TestForwardZero::forwardZero (const Eigen::VectorXd & x) override virtual
Evaluates the method itself.
Parameters
[in] x The point of evaluation
Returns
The evalution of the method
Reimplemented from ct::core::Derivatives< 3, 2, double >.
Referenced by clone().
Member Data Documentation
OUT_TYPE
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix<double, 2, 1> ct::core::generated::TestForwardZero::OUT_TYPE
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/generated/TestForwardZero.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/generated/TestForwardZero.cpp