ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME > Class Template Reference
ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME > Class Template Reference
Computes the linearization of a system dynamics function through autodiff.
#include <DynamicsLinearizerAD.h>
Public Types
typedef Base::OUT_SCALAR OUT_SCALAR
scalar type of resulting linear system
typedef Base::state_vector_t state_vector_t
state vector type
typedef Base::control_vector_t control_vector_t
control vector type
typedef Base::state_matrix_t state_matrix_t
state Jacobian type (A)
typedef Base::state_control_matrix_t state_control_matrix_t
control Jacobian type (B)
typedef Base::dynamics_fct_t dynamics_fct_t
dynamics function signature
Public Types inherited from ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >
typedef std::conditional<(std::is_same< SCALAR, CppAD::AD< double >>::value)||(std::is_same< SCALAR, CppAD::AD< CppAD::cg::CG< double >>>::value), double, float >::type OUT_SCALAR
scalar type of resulting linear system
typedef StateVector< STATE_DIM, OUT_SCALAR > state_vector_t
typedef ControlVector< CONTROL_DIM, OUT_SCALAR > control_vector_t
typedef StateVector< STATE_DIM, SCALAR > state_vector_ad_t
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_ad_t
typedef StateMatrix< STATE_DIM, OUT_SCALAR > state_matrix_t
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, OUT_SCALAR > state_control_matrix_t
typedef std::function< void(const state_vector_ad_t &, const TIME &, const control_vector_ad_t &, state_vector_ad_t &)> dynamics_fct_t
dynamics function signature
Public Member Functions
DynamicsLinearizerAD (dynamics_fct_t dyn)
default constructor
DynamicsLinearizerAD (const DynamicsLinearizerAD &rhs)
copy constructor
const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const TIME t=TIME(0))
const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const TIME t=TIME(0))
Public Member Functions inherited from ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >
DynamicsLinearizerADBase (dynamics_fct_t dyn)
default constructor
DynamicsLinearizerADBase (const DynamicsLinearizerADBase &arg)
copy constructor
template<typename T = std::string>
std::enable_if< std::is_same< OUT_SCALAR, double >::value, T >::type getOutScalarType () const
template<typename T = std::string>
std::enable_if< std::is_same< OUT_SCALAR, float >::value, T >::type getOutScalarType () const
virtual ~DynamicsLinearizerADBase ()
destructor
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME > Base
Public Attributes inherited from ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
void computeA (const state_vector_t &x, const control_vector_t &u)
compute the state Jacobian
void computeB (const state_vector_t &x, const control_vector_t &u)
compute the input Jacobian
Protected Member Functions inherited from ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >
void initialize ()
initialize all utilities
void recordTerms ()
record the model
void setupSparsityA ()
setup the sparsity of the state Jacobian
void setupSparsityB ()
setup the sparsity of the input Jacobian
Protected Attributes
dynamics_fct_t dynamics_fct_
function handle to system dynamics
state_matrix_t dFdx_
Jacobian wrt state.
state_control_matrix_t dFdu_
Jacobian wrt input.
Protected Attributes inherited from ct::core::internal::DynamicsLinearizerADBase< STATE_DIM, CONTROL_DIM, SCALAR, TIME >
const size_t A_entries = STATE_DIM * STATE_DIM
number of entries in the state Jacobian
const size_t B_entries = STATE_DIM * CONTROL_DIM
number of entries in the input Jacobian
const size_t FullJac_entries
number of entries in the stacked Jacobian
dynamics_fct_t dynamics_fct_
function handle to system dynamics
CppAD::ADFun< typename SCALAR::value_type > f_
Auto-Diff function.
SparsityPattern sparsityA_
sparsity pattern of the state Jacobian
SparsityPattern sparsityB_
sparsity pattern of the input Jacobian
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME>
class ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >
Computes the linearization of a system dynamics function through autodiff.
This class takes a function handle representing system dynamics of the form or where the last argument is the result of the evaluation in each case. It then computes the linearization around a given point , .
Template Parameters
STATE_DIM dimension of state vector
CONTROL_DIM dimension of control vector
SCALAR scalar type
TIME type of time variable of dynamics
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef Base::OUT_SCALAR ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::OUT_SCALAR
scalar type of resulting linear system
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef Base::state_vector_t ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::state_vector_t
state vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef Base::control_vector_t ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::control_vector_t
control vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef Base::state_matrix_t ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::state_matrix_t
state Jacobian type (A)
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef Base::state_control_matrix_t ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::state_control_matrix_t
control Jacobian type (B)
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> typedef Base::dynamics_fct_t ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::dynamics_fct_t
dynamics function signature
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::DynamicsLinearizerAD (dynamics_fct_t dyn) inline
default constructor
Parameters
dyn function handle to system dynamics
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::DynamicsLinearizerAD (const DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME > & rhs) inline
copy constructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> const state_matrix_t& ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const TIME t = TIME(0)) inline
Referenced by ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), and ct::core::AutoDiffLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> const state_control_matrix_t& ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const TIME t = TIME(0)) inline
Referenced by ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), and ct::core::AutoDiffLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> void ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::computeA (const state_vector_t & x, const control_vector_t & u) inline protected
compute the state Jacobian
Parameters
x state to linearize around
u input to linearize around
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::getDerivativeState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> void ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::computeB (const state_vector_t & x, const control_vector_t & u) inline protected
compute the input Jacobian
Parameters
x state to linearize around
u input to linearize around
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::getDerivativeControl().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef internal::DynamicsLinearizerADBase<STATE_DIM, CONTROL_DIM, SCALAR, TIME> ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::Base
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> dynamics_fct_t ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::dynamics_fct_ protected
function handle to system dynamics
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> state_matrix_t ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::dFdx_ protected
Jacobian wrt state.
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeA(), and ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::getDerivativeState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR, typename TIME> state_control_matrix_t ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::dFdu_ protected
Jacobian wrt input.
Referenced by ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::computeB(), and ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int >::getDerivativeControl().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/systems/linearizer/DynamicsLinearizerAD.h