ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference abstract
A general, non-linear discrete dynamic system with a control input.
#include <DiscreteControlledSystem.h>
Public Types
typedef DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::time_t time_t
Public Types inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef int time_t
the type of the time variable
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Member Functions
DiscreteControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
DiscreteControlledSystem (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
DiscreteControlledSystem (const ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > &arg)
copy constructor
virtual ~DiscreteControlledSystem ()=default
destructor
virtual DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override=0
deep copy
void setController (const std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void propagateDynamics (const state_vector_t &state, const time_t n, state_vector_t &stateNext) override
propagates the system dynamics forward by one step
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext)=0
propagates the controlled system dynamics forward by one step
Public Member Functions inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteSystem (const SYSTEM_TYPE &type=GENERAL)
constructor
virtual ~DiscreteSystem ()
desctructor
virtual void propagateDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t n, StateVector< STATE_DIM, SCALAR > &stateNext)=0
propagates the system dynamics forward by one step
SYSTEM_TYPE getType () const
get the type of system
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
Protected Attributes
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
Protected Attributes inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
A general, non-linear discrete dynamic system with a control input.
This describes a general, non-linear discrete dynamic system of the following form
where is the state, the control input and the time index.
For implementing your own ControlledSystem, derive from this class.
We generally assume that the Controller is a state and time index dependent function which allows any ControlledSystem to be re-written as a System of the form
which can be forward propagated directly.
Template Parameters
STATE_DIM dimension of state vector
CONTROL_DIM dimension of input vector
SCALAR scalar type
Member Typedef Documentation
Base
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DiscreteSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::Base
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_vector_t ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::control_vector_t ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
time_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::time_t ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::time_t
Constructor & Destructor Documentation
DiscreteControlledSystem() [1/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteControlledSystem (const SYSTEM_TYPE & type = SYSTEM_TYPE::GENERAL) inline
default constructor
Parameters
type system type
DiscreteControlledSystem() [2/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteControlledSystem (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE & type = SYSTEM_TYPE::GENERAL) inline
constructor
Parameters
controller controller
type system type
DiscreteControlledSystem() [3/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteControlledSystem (const ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > & arg) inline
copy constructor
~DiscreteControlledSystem()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::~DiscreteControlledSystem () virtual default
destructor
Referenced by ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >::DiscreteControlledSystem().
Member Function Documentation
clone()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual DiscreteControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR>* ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const override pure virtual
deep copy
Reimplemented from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
Implemented in ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::SystemDiscretizer< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >, ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::SensitivityApproximation< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >, ct::core::SwitchedDiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::DiscreteLinearSystem< 2, 1, float >, ct::core::DiscreteLinearSystem< 2, 1, double >, ct::core::Sensitivity< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::tpl::TestDiscreteNonlinearSystem< SCALAR >, ct::core::generated::TestDiscreteNonlinearSystemLinearized, ct::core::generated::TestDiscreteNonlinearSystemLinearizedDouble, and ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat.
Referenced by ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >::DiscreteControlledSystem().
setController()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::setController (const std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> & controller) inline
set a new controller
Parameters
controller new controller
getController() [1/2]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getController (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> & controller) const inline
get the controller instance
Todo:
remove this function (duplicate of getController() below)
Parameters
controller controller instance
getController() [2/2]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> std::shared_ptr<DiscreteController<STATE_DIM, CONTROL_DIM, SCALAR> > ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getController () inline
get the controller instace
Returns
controller instance
propagateDynamics()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::propagateDynamics (const state_vector_t & state, const time_t n, state_vector_t & stateNext) inline override virtual
propagates the system dynamics forward by one step
evaluates at a given state and index
Parameters
state start state to propagate from
n time index to propagate the dynamics at
stateNext the resulting propagated state
propagateControlledDynamics()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::propagateControlledDynamics (const state_vector_t & state, const time_t n, const control_vector_t & control, state_vector_t & stateNext) pure virtual
propagates the controlled system dynamics forward by one step
evaluates at a given state, control and index
Parameters
state start state to propagate from
control the control input to apply. This is a constant control input applied to the continuous-time dynamics
n time index to propagate the dynamics at
stateNext the resulting propagated state
Implemented in ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::SwitchedDiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::DiscreteLinearSystem< 2, 1, float >, ct::core::DiscreteLinearSystem< 2, 1, double >, and ct::core::tpl::TestDiscreteNonlinearSystem< SCALAR >.
Referenced by ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >::propagateDynamics().
Member Data Documentation
Ptr
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr<DiscreteControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR> > ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::Ptr
controller_
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> std::shared_ptr<DiscreteController<STATE_DIM, CONTROL_DIM, SCALAR> > ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::controller_ protected
the controller instance
Referenced by ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >::DiscreteControlledSystem(), ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >::getController(), ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >::propagateDynamics(), and ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, double >::setController().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/systems/discrete_time/DiscreteControlledSystem.h