ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference abstract
interface class for a general linear system or linearized system
#include <LinearSystem.h>
Public Types
typedef Base::time_t time_t
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
state vector type
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
input vector type
typedef StateMatrix< STATE_DIM, SCALAR > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, SCALAR >
typedef SCALAR time_t
the type of the time variable
Public Member Functions
LinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~LinearSystem ()
destructor
virtual LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override=0
deep cloning
virtual void computeControlledDynamics (const state_vector_t &state, const time_t &t, const control_vector_t &control, state_vector_t &derivative) override
compute the system dynamics
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
get the A matrix of a linear system
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
get the B matrix of a linear system
virtual void getDerivatives (state_matrix_t &A, state_control_matrix_t &B, const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))
Get both linear system matrices A and B in one call.
Public Member Functions inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
ControlledSystem (const ControlledSystem &arg)
copy constructor
virtual ~ControlledSystem ()
destructor
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative) override
compute the dynamics of the system
virtual void computeControlledDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< STATE_DIM, SCALAR > &derivative)=0
ControlVector< CONTROL_DIM, SCALAR > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, SCALAR >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
System (const System &other)
copy constructor
virtual ~System ()
destructor
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative)=0
computes the system dynamics
SYSTEM_TYPE getType () const
get the type of system
virtual bool isSymplectic () const
Determines if the system is in symplectic form.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, SCALAR > Base
Public Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef SCALAR S
the scalar type
Additional Inherited Members
Protected Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
ControlVector< CONTROL_DIM, SCALAR > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
interface class for a general linear system or linearized system
Defines the interface for a linear system
Template Parameters
STATE_DIM size of state vector
CONTROL_DIM size of input vector
Member Typedef Documentation
time_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::time_t ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::time_t
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef StateVector<STATE_DIM, SCALAR> ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
state vector type
control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef ControlVector<CONTROL_DIM, SCALAR> ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
input vector type
state_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef StateMatrix<STATE_DIM, SCALAR> ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
state Jacobian type
state_control_matrix_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef StateControlMatrix<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::state_control_matrix_t
input Jacobian type
Constructor & Destructor Documentation
LinearSystem()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::LinearSystem (const ct::core::SYSTEM_TYPE & type = ct::core::SYSTEM_TYPE::GENERAL) inline
default constructor
Parameters
type system type
~LinearSystem()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::~LinearSystem () inline virtual
destructor
Member Function Documentation
clone()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual LinearSystem<STATE_DIM, CONTROL_DIM, SCALAR>* ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const override pure virtual
deep cloning
Implements ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
Implemented in ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >, LinearizedOscillator, ct::core::LTISystem< STATE_DIM, CONTROL_DIM >, ct::core::generated::TestNonlinearSystemLinearized, ct::optcon::example::DiehlSystemLinear, ct::optcon::example::LinearizedSystem, ct::optcon::example::LinearizedSystem, ct::optcon::example::tpl::LinearOscillatorLinear< class >, LinkedMasses, ct::optcon::example::MIMOIntegratorLinear< state_dim, control_dim >, ct::optcon::example::SpringLoadedMassLinear, ct::models::HyA::HyALinearizedForward, ct::models::HyA::HyALinearizedReverse, ct::models::HyQ::HyQBareModelLinearizedForward, ct::models::HyQ::HyQBareModelLinearizedReverse, ct::models::HyQ::HyQWithContactModelLinearizedForward, ct::models::HyQ::HyQWithContactModelLinearizedReverse, ct::models::InvertedPendulum::InvertedPendulumActDynLinearizedForward, and ct::models::QuadrotorLinear.
Referenced by ct::core::LinearSystem< 2, 1 >::~LinearSystem().
computeControlledDynamics()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::computeControlledDynamics (const state_vector_t & state, const time_t & t, const control_vector_t & control, state_vector_t & derivative) inline override virtual
compute the system dynamics
This computes the system dynamics
Parameters
state current state
t current time
control control input
derivative state derivative
getDerivativeState()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual const state_matrix_t& ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const time_t t = time_t(0.0)) pure virtual
get the A matrix of a linear system
Parameters
x state vector (required for linearizing non-linear systems, ignored for pure linear system)
u input vector (required for linearizing non-linear systems, ignored for pure linear system)
t current time
Returns
A matrix
Implemented in ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::core::LinearSystem< 2, 1 >::computeControlledDynamics(), and ct::core::LinearSystem< 2, 1 >::getDerivatives().
getDerivativeControl()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual const state_control_matrix_t& ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const time_t t = time_t(0.0)) pure virtual
get the B matrix of a linear system
Parameters
x state vector (required for linearizing non-linear systems, ignored for pure linear system)
u input vector (required for linearizing non-linear systems, ignored for pure linear system)
t current time
Returns
B matrix
Implemented in ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >, and ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by ct::core::LinearSystem< 2, 1 >::computeControlledDynamics(), and ct::core::LinearSystem< 2, 1 >::getDerivatives().
getDerivatives()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivatives (state_matrix_t & A, state_control_matrix_t & B, const state_vector_t & x, const control_vector_t & u, const time_t t = time_t(0.0)) inline virtual
Get both linear system matrices A and B in one call.
Motvation: For certain derived instances, it may be more efficient to compute A and B simulatenously. In that case, this method can be overloaded for maximum efficiency. As default case, it simply calls above methods independently.
Parameters
A matrix A of linear system
B matrix B of linear system
x the current state
u the current input
t the current time
Member Data Documentation
Base
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::LinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::Base
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/systems/continuous_time/linear/LinearSystem.h