testing::gmock_nice_strict_test::MockBaz Class Reference
testing::gmock_nice_strict_test::MockBaz Class Reference
Classes
class MoveOnly
Public Member Functions
MockBaz (MoveOnly)
Constructor & Destructor Documentation
testing::gmock_nice_strict_test::MockBaz::MockBaz (MoveOnly) inline
References testing::internal::CaptureStdout(), testing::gmock_nice_strict_test::Foo::DoThat(), testing::gmock_nice_strict_test::Foo::DoThis(), EXPECT_EQ, EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, testing::internal::GetCapturedStdout(), GMOCK_FLAG, testing::Invoke(), ON_CALL, testing::gmock_nice_strict_test::TEST(), and verbose.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/test/gmock-nice-strict_test.cc