testing::internal::Random Class Reference
testing::internal::Random Class Reference
#include <gtest-internal.h>
Public Member Functions
Random (UInt32 seed)
void Reseed (UInt32 seed)
UInt32 Generate (UInt32 range)
Static Public Attributes
static const UInt32 kMaxRange = 1u << 31
Constructor & Destructor Documentation
testing::internal::Random::Random (UInt32 seed) inline explicit
Member Function Documentation
void testing::internal::Random::Reseed (UInt32 seed) inline
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
Referenced by testing::internal::TestSuiteNameIs::operator()(), and operator<<().
UInt32 testing::internal::Random::Generate (UInt32 range)
References testing::TestSuite::Failed(), testing::internal::GetArgvs(), GTEST_CHECK_, i, testing::TestSuite::Passed(), and testing::TestSuite::should_run().
Referenced by operator<<().
Member Data Documentation
const UInt32 testing::internal::Random::kMaxRange = 1u << 31 static
Referenced by operator<<().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/include/gtest/internal/gtest-internal.h
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc