ct::core::ControlSimulator< CONTROLLED_SYSTEM > Class Template Reference
ct::core::ControlSimulator< CONTROLLED_SYSTEM > Class Template Reference
A class for simulating controlled systems in a general way.
#include <ControlSimulator.h>
Public Types
using SCALAR = typename CONTROLLED_SYSTEM::SCALAR
Public Member Functions
ControlSimulator ()=default
default constructor
ControlSimulator (Time sim_dt, Time control_dt, const StateVector< STATE_DIM > &x0, std::shared_ptr< CONTROLLED_SYSTEM > controlled_system, bool verbose=false)
constructor
ControlSimulator (const ControlSimulator &arg)
copy constructor
virtual ~ControlSimulator ()
destructor
virtual void finishSystemIteration (Time sim_time)
Gets called after the integrator step.
virtual void prepareControllerIteration (Time sim_time)
During controller update, this method does processing before the state measurement arrives.
virtual void finishControllerIteration (Time sim_time)
During controller update, this method does processing once the state measurement arrives.
void simulate (Time duration, const IntegrationType &intType=IntegrationType::EULERCT)
spawns the two threads in a nonblocking way
void finish ()
waits for the simulation threads to finish
void stop ()
stops the simulation
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t STATE_DIM = CONTROLLED_SYSTEM::STATE_DIM
static const size_t CONTROL_DIM = CONTROLLED_SYSTEM::CONTROL_DIM
Protected Member Functions
virtual void simulateSystem (Time duration, const IntegrationType &intType=IntegrationType::EULERCT)
run by the thread that simulates the system
virtual void simulateController (Time duration)
run by the thread that updates the controller
Protected Attributes
Time sim_dt_
Time control_dt_
std::shared_ptr< CONTROLLED_SYSTEM > system_
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
std::chrono::time_point< std::chrono::high_resolution_clock > sim_start_time_
StateVector< STATE_DIM > x0_
StateVector< STATE_DIM > x_
std::thread sys_thread_
std::thread control_thread_
std::mutex state_mtx_
std::mutex control_mtx_
std::atomic< bool > stop_
bool verbose_
Detailed Description
template<class CONTROLLED_SYSTEM>
class ct::core::ControlSimulator< CONTROLLED_SYSTEM >
A class for simulating controlled systems in a general way.
This runs two threads - one that integrates the controlled system by applying the defined control, and one that updates the control if needed.
Template Parameters
CONTROLLED_SYSTEM the controlled system that we wish to simulate
Member Typedef Documentation
SCALAR
template<class CONTROLLED_SYSTEM > using ct::core::ControlSimulator< CONTROLLED_SYSTEM >::SCALAR = typename CONTROLLED_SYSTEM::SCALAR
Constructor & Destructor Documentation
ControlSimulator() [1/3]
template<class CONTROLLED_SYSTEM > ct::core::ControlSimulator< CONTROLLED_SYSTEM >::ControlSimulator () default
default constructor
ControlSimulator() [2/3]
template<class CONTROLLED_SYSTEM > ct::core::ControlSimulator< CONTROLLED_SYSTEM >::ControlSimulator (Time sim_dt, Time control_dt, const StateVector< STATE_DIM > & x0, std::shared_ptr< CONTROLLED_SYSTEM > controlled_system, bool verbose = false) inline
constructor
References ct::core::ControlSimulator< CONTROLLED_SYSTEM >::control_dt_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::controller_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sim_dt_, and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::system_.
ControlSimulator() [3/3]
template<class CONTROLLED_SYSTEM > ct::core::ControlSimulator< CONTROLLED_SYSTEM >::ControlSimulator (const ControlSimulator< CONTROLLED_SYSTEM > & arg) inline
copy constructor
References ct::core::ControlSimulator< CONTROLLED_SYSTEM >::controller_, and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::system_.
~ControlSimulator()
template<class CONTROLLED_SYSTEM > virtual ct::core::ControlSimulator< CONTROLLED_SYSTEM >::~ControlSimulator () inline virtual
destructor
References ct::core::ControlSimulator< CONTROLLED_SYSTEM >::finish().
Member Function Documentation
finishSystemIteration()
template<class CONTROLLED_SYSTEM > virtual void ct::core::ControlSimulator< CONTROLLED_SYSTEM >::finishSystemIteration (Time sim_time) inline virtual
Gets called after the integrator step.
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem().
prepareControllerIteration()
template<class CONTROLLED_SYSTEM > virtual void ct::core::ControlSimulator< CONTROLLED_SYSTEM >::prepareControllerIteration (Time sim_time) inline virtual
During controller update, this method does processing before the state measurement arrives.
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateController().
finishControllerIteration()
template<class CONTROLLED_SYSTEM > virtual void ct::core::ControlSimulator< CONTROLLED_SYSTEM >::finishControllerIteration (Time sim_time) inline virtual
During controller update, this method does processing once the state measurement arrives.
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateController().
simulate()
template<class CONTROLLED_SYSTEM > void ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate (Time duration, const IntegrationType & intType = IntegrationType::EULERCT) inline
spawns the two threads in a nonblocking way
References ct::core::ControlSimulator< CONTROLLED_SYSTEM >::control_thread_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sim_start_time_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateController(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::stop_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sys_thread_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::x0_, and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::x_.
finish()
template<class CONTROLLED_SYSTEM > void ct::core::ControlSimulator< CONTROLLED_SYSTEM >::finish () inline
waits for the simulation threads to finish
References ct::core::ControlSimulator< CONTROLLED_SYSTEM >::control_thread_, and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sys_thread_.
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::~ControlSimulator().
stop()
template<class CONTROLLED_SYSTEM > void ct::core::ControlSimulator< CONTROLLED_SYSTEM >::stop () inline
stops the simulation
References ct::core::ControlSimulator< CONTROLLED_SYSTEM >::stop_.
simulateSystem()
template<class CONTROLLED_SYSTEM > virtual void ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem (Time duration, const IntegrationType & intType = IntegrationType::EULERCT) inline protected virtual
run by the thread that simulates the system
References ct::core::ControlSimulator< CONTROLLED_SYSTEM >::control_dt_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::finishSystemIteration(), ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sim_dt_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sim_start_time_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::state_mtx_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::stop_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::system_, ct::core::ControlSimulator< CONTROLLED_SYSTEM >::verbose_, and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::x_.
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate().
simulateController()
template<class CONTROLLED_SYSTEM > virtual void ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateController (Time duration) inline protected virtual
run by the thread that updates the controller
References ct::core::ControlSimulator< CONTROLLED_SYSTEM >::finishControllerIteration(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::prepareControllerIteration(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sim_start_time_, and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::stop_.
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate().
Member Data Documentation
STATE_DIM
template<class CONTROLLED_SYSTEM > EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t ct::core::ControlSimulator< CONTROLLED_SYSTEM >::STATE_DIM = CONTROLLED_SYSTEM::STATE_DIM static
CONTROL_DIM
template<class CONTROLLED_SYSTEM > const size_t ct::core::ControlSimulator< CONTROLLED_SYSTEM >::CONTROL_DIM = CONTROLLED_SYSTEM::CONTROL_DIM static
sim_dt_
template<class CONTROLLED_SYSTEM > Time ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sim_dt_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::ControlSimulator(), and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem().
control_dt_
template<class CONTROLLED_SYSTEM > Time ct::core::ControlSimulator< CONTROLLED_SYSTEM >::control_dt_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::ControlSimulator(), and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem().
system_
template<class CONTROLLED_SYSTEM > std::shared_ptr<CONTROLLED_SYSTEM> ct::core::ControlSimulator< CONTROLLED_SYSTEM >::system_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::ControlSimulator(), and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem().
controller_
template<class CONTROLLED_SYSTEM > std::shared_ptr<Controller<STATE_DIM, CONTROL_DIM, SCALAR> > ct::core::ControlSimulator< CONTROLLED_SYSTEM >::controller_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::ControlSimulator().
sim_start_time_
template<class CONTROLLED_SYSTEM > std::chrono::time_point<std::chrono::high_resolution_clock> ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sim_start_time_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateController(), and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem().
x0_
template<class CONTROLLED_SYSTEM > StateVector<STATE_DIM> ct::core::ControlSimulator< CONTROLLED_SYSTEM >::x0_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate().
x_
template<class CONTROLLED_SYSTEM > StateVector<STATE_DIM> ct::core::ControlSimulator< CONTROLLED_SYSTEM >::x_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate(), and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem().
sys_thread_
template<class CONTROLLED_SYSTEM > std::thread ct::core::ControlSimulator< CONTROLLED_SYSTEM >::sys_thread_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::finish(), and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate().
control_thread_
template<class CONTROLLED_SYSTEM > std::thread ct::core::ControlSimulator< CONTROLLED_SYSTEM >::control_thread_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::finish(), and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate().
state_mtx_
template<class CONTROLLED_SYSTEM > std::mutex ct::core::ControlSimulator< CONTROLLED_SYSTEM >::state_mtx_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem().
control_mtx_
template<class CONTROLLED_SYSTEM > std::mutex ct::core::ControlSimulator< CONTROLLED_SYSTEM >::control_mtx_ protected
stop_
template<class CONTROLLED_SYSTEM > std::atomic<bool> ct::core::ControlSimulator< CONTROLLED_SYSTEM >::stop_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulate(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateController(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem(), and ct::core::ControlSimulator< CONTROLLED_SYSTEM >::stop().
verbose_
template<class CONTROLLED_SYSTEM > bool ct::core::ControlSimulator< CONTROLLED_SYSTEM >::verbose_ protected
Referenced by ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/simulation/ControlSimulator.h