ct::core::tpl::TestSymplecticSystem< SCALAR > Class Template Reference
ct::core::tpl::TestSymplecticSystem< SCALAR > Class Template Reference
#include <TestSymplecticSystem.h>
Public Member Functions
TestSymplecticSystem ()=delete
TestSymplecticSystem (SCALAR w_n, std::shared_ptr< Controller< 2, 1, SCALAR >> controller=nullptr)
TestSymplecticSystem (const TestSymplecticSystem &arg)
virtual ~TestSymplecticSystem ()=default
TestSymplecticSystem * clone () const override
Creates a new instance of the object with same properties than original.
virtual void computePdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > &x, const StateVector< VEL_DIM, SCALAR > &v, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< POS_DIM, SCALAR > &pDot) override
need to override this method for a symplectic system
virtual void computeVdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > &x, const StateVector< POS_DIM, SCALAR > &p, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< VEL_DIM, SCALAR > &vDot) override
need to override this method for a symplectic system
Public Member Functions inherited from ct::core::SymplecticSystem< 1, 1, 1, SCALAR >
SymplecticSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
Constructor.
SymplecticSystem (std::shared_ptr< ct::core::Controller< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
Constructor.
SymplecticSystem (const SymplecticSystem &arg)
Copy constructor.
virtual ~SymplecticSystem ()
Destructor.
virtual bool isSymplectic () const override
Determines if the system is in symplectic form.
virtual void computeControlledDynamics (const StateVector< POS_DIM+VEL_DIM, SCALAR > &state, const time_t &t, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< POS_DIM+VEL_DIM, SCALAR > &derivative) override
void computePdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > &x, const StateVector< VEL_DIM, SCALAR > &v, StateVector< POS_DIM, SCALAR > &pDot)
Computes the derivative of the position.
void computeVdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > &x, const StateVector< POS_DIM, SCALAR > &p, StateVector< VEL_DIM, SCALAR > &vDot)
Computes the derivative of the velocity.
Public Member Functions inherited from ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
ControlledSystem (const ControlledSystem &arg)
copy constructor
virtual ~ControlledSystem ()
destructor
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative) override
compute the dynamics of the system
virtual void computeControlledDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< STATE_DIM, SCALAR > &derivative)=0
ControlVector< CONTROL_DIM, SCALAR > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, SCALAR >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
System (const System &other)
copy constructor
virtual ~System ()
destructor
SYSTEM_TYPE getType () const
get the type of system
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t STATE_DIM = 2
static const size_t CONTROL_DIM = 1
static const size_t POS_DIM = 1
static const size_t VEL_DIM = 1
Additional Inherited Members
Public Types inherited from ct::core::SymplecticSystem< 1, 1, 1, SCALAR >
typedef Base::time_t time_t
Public Types inherited from ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, SCALAR >
typedef SCALAR time_t
the type of the time variable
Public Attributes inherited from ct::core::SymplecticSystem< 1, 1, 1, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, SCALAR > Base
Public Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef SCALAR S
the scalar type
Protected Attributes inherited from ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
ControlVector< CONTROL_DIM, SCALAR > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<typename SCALAR>
class ct::core::tpl::TestSymplecticSystem< SCALAR >
This is a simple second-order oscillator without damping, which can easily be formulated as symplectic system.
Constructor & Destructor Documentation
TestSymplecticSystem() [1/3]
template<typename SCALAR > ct::core::tpl::TestSymplecticSystem< SCALAR >::TestSymplecticSystem () delete
Referenced by ct::core::tpl::TestSymplecticSystem< SCALAR >::clone().
TestSymplecticSystem() [2/3]
template<typename SCALAR > ct::core::tpl::TestSymplecticSystem< SCALAR >::TestSymplecticSystem (SCALAR w_n, std::shared_ptr< Controller< 2, 1, SCALAR >> controller = nullptr) inline
TestSymplecticSystem() [3/3]
template<typename SCALAR > ct::core::tpl::TestSymplecticSystem< SCALAR >::TestSymplecticSystem (const TestSymplecticSystem< SCALAR > & arg) inline
References ct::core::tpl::TestSymplecticSystem< SCALAR >::~TestSymplecticSystem().
~TestSymplecticSystem()
template<typename SCALAR > virtual ct::core::tpl::TestSymplecticSystem< SCALAR >::~TestSymplecticSystem () virtual default
Referenced by ct::core::tpl::TestSymplecticSystem< SCALAR >::TestSymplecticSystem().
Member Function Documentation
clone()
template<typename SCALAR > TestSymplecticSystem* ct::core::tpl::TestSymplecticSystem< SCALAR >::clone () const inline override virtual
Creates a new instance of the object with same properties than original.
Returns
Copy of this object.
Implements ct::core::SymplecticSystem< 1, 1, 1, SCALAR >.
References ct::core::tpl::TestSymplecticSystem< SCALAR >::TestSymplecticSystem().
computePdot()
template<typename SCALAR > virtual void ct::core::tpl::TestSymplecticSystem< SCALAR >::computePdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > & x, const StateVector< VEL_DIM, SCALAR > & v, const ControlVector< CONTROL_DIM, SCALAR > & control, StateVector< POS_DIM, SCALAR > & pDot) inline override virtual
need to override this method for a symplectic system
Implements ct::core::SymplecticSystem< 1, 1, 1, SCALAR >.
computeVdot()
template<typename SCALAR > virtual void ct::core::tpl::TestSymplecticSystem< SCALAR >::computeVdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > & x, const StateVector< POS_DIM, SCALAR > & p, const ControlVector< CONTROL_DIM, SCALAR > & control, StateVector< VEL_DIM, SCALAR > & vDot) inline override virtual
need to override this method for a symplectic system
Implements ct::core::SymplecticSystem< 1, 1, 1, SCALAR >.
Member Data Documentation
STATE_DIM
template<typename SCALAR > EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t ct::core::tpl::TestSymplecticSystem< SCALAR >::STATE_DIM = 2 static
CONTROL_DIM
template<typename SCALAR > const size_t ct::core::tpl::TestSymplecticSystem< SCALAR >::CONTROL_DIM = 1 static
POS_DIM
template<typename SCALAR > const size_t ct::core::tpl::TestSymplecticSystem< SCALAR >::POS_DIM = 1 static
VEL_DIM
template<typename SCALAR > const size_t ct::core::tpl::TestSymplecticSystem< SCALAR >::VEL_DIM = 1 static
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/test/system/TestSymplecticSystem.h