Masspoint Class Reference
Masspoint Class Reference
#include <Masspoint.h>
Public Member Functions
Masspoint (double mass, double d)
Masspoint (const Masspoint &other)
~Masspoint ()=default
Masspoint * clone () const override
deep copy
void computeDynamics (const ct::core::StateVector< STATE_DIM > &x, const ct::core::Time &t, ct::core::StateVector< STATE_DIM > &derivative) override
Public Member Functions inherited from ct::core::System< 2 >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
System (const System &other)
copy constructor
virtual ~System ()
destructor
virtual void computeDynamics (const StateVector< STATE_DIM, double > &state, const time_t &t, StateVector< STATE_DIM, double > &derivative)=0
computes the system dynamics
SYSTEM_TYPE getType () const
get the type of system
virtual bool isSymplectic () const
Determines if the system is in symplectic form.
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t STATE_DIM = 2
Additional Inherited Members
Public Types inherited from ct::core::System< 2 >
typedef double time_t
the type of the time variable
Public Attributes inherited from ct::core::System< 2 >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef double S
the scalar type
Protected Attributes inherited from ct::core::System< 2 >
SYSTEM_TYPE type_
type of system
Detailed Description
Examples:
Masspoint.h, and MasspointIntegration.cpp.
Constructor & Destructor Documentation
Masspoint() [1/2]
Masspoint::Masspoint (double mass, double d) inline
Examples:
Masspoint.h.
Referenced by clone().
Masspoint() [2/2]
Masspoint::Masspoint (const Masspoint & other) inline
References ~Masspoint().
~Masspoint()
Masspoint::~Masspoint () default
Examples:
Masspoint.h.
Referenced by Masspoint().
Member Function Documentation
clone()
Masspoint* Masspoint::clone () const inline override virtual
deep copy
Reimplemented from ct::core::System< 2 >.
Examples:
Masspoint.h.
References Masspoint().
computeDynamics()
void Masspoint::computeDynamics (const ct::core::StateVector< STATE_DIM > & x, const ct::core::Time & t, ct::core::StateVector< STATE_DIM > & derivative) inline override
Examples:
Masspoint.h.
Member Data Documentation
STATE_DIM
EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t Masspoint::STATE_DIM = 2 static
Examples:
Masspoint.h, and MasspointIntegration.cpp.
Referenced by main().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/examples/include/ct/core/examples/Masspoint.h