ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR > Class Template Reference abstract
The base class for the implementation of a symplectic system. In a symplectic system, the position and the velocity update can be separated. During integration, the velocity gets update first and the position update uses the updated velocity.
#include <SymplecticSystem.h>
Public Types
typedef Base::time_t time_t
Public Types inherited from ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, SCALAR >
typedef SCALAR time_t
the type of the time variable
Public Member Functions
SymplecticSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
Constructor.
SymplecticSystem (std::shared_ptr< ct::core::Controller< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
Constructor.
SymplecticSystem (const SymplecticSystem &arg)
Copy constructor.
virtual ~SymplecticSystem ()
Destructor.
virtual SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR > * clone () const override=0
Creates a new instance of the object with same properties than original.
virtual bool isSymplectic () const override
Determines if the system is in symplectic form.
virtual void computeControlledDynamics (const StateVector< POS_DIM+VEL_DIM, SCALAR > &state, const time_t &t, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< POS_DIM+VEL_DIM, SCALAR > &derivative) override
void computePdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > &x, const StateVector< VEL_DIM, SCALAR > &v, StateVector< POS_DIM, SCALAR > &pDot)
Computes the derivative of the position.
void computeVdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > &x, const StateVector< POS_DIM, SCALAR > &p, StateVector< VEL_DIM, SCALAR > &vDot)
Computes the derivative of the velocity.
virtual void computePdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > &x, const StateVector< VEL_DIM, SCALAR > &v, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< POS_DIM, SCALAR > &pDot)=0
Computes the derivative of the position.
virtual void computeVdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > &x, const StateVector< POS_DIM, SCALAR > &p, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< VEL_DIM, SCALAR > &vDot)=0
Computes the derivative of the velocity.
Public Member Functions inherited from ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
ControlledSystem (const ControlledSystem &arg)
copy constructor
virtual ~ControlledSystem ()
destructor
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void computeDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, StateVector< STATE_DIM, SCALAR > &derivative) override
compute the dynamics of the system
virtual void computeControlledDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t &t, const ControlVector< CONTROL_DIM, SCALAR > &control, StateVector< STATE_DIM, SCALAR > &derivative)=0
ControlVector< CONTROL_DIM, SCALAR > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, SCALAR >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
System (const System &other)
copy constructor
virtual ~System ()
destructor
SYSTEM_TYPE getType () const
get the type of system
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, SCALAR > Base
Public Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef SCALAR S
the scalar type
Additional Inherited Members
Protected Attributes inherited from ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
ControlVector< CONTROL_DIM, SCALAR > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >
The base class for the implementation of a symplectic system. In a symplectic system, the position and the velocity update can be separated. During integration, the velocity gets update first and the position update uses the updated velocity.
Template Parameters
POS_DIM The position dimension
VEL_DIM The velocity dimension
CONTROL_DIM The control dimension
SCALAR The scalar type
Member Typedef Documentation
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::time_t ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::time_t
Constructor & Destructor Documentation
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::SymplecticSystem (const SYSTEM_TYPE & type = SYSTEM_TYPE::GENERAL) inline
Constructor.
Parameters
[in] type The type of the system
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::SymplecticSystem (std::shared_ptr< ct::core::Controller< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE & type = SYSTEM_TYPE::GENERAL) inline
Constructor.
Parameters
[in] controller The controller used when integrating the system
[in] type The type of the system
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::SymplecticSystem (const SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR > & arg) inline
Copy constructor.
Parameters
[in] arg The argument
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::~SymplecticSystem () inline virtual
Destructor.
Member Function Documentation
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual SymplecticSystem<POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR>* ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::clone () const override pure virtual
Creates a new instance of the object with same properties than original.
Returns
Copy of this object.
Implements ct::core::ControlledSystem< POS_DIM+VEL_DIM, CONTROL_DIM, SCALAR >.
Implemented in ct::core::tpl::TestSymplecticSystem< SCALAR >.
Referenced by ct::core::SymplecticSystem< 1, 1, 1, SCALAR >::~SymplecticSystem().
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual bool ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::isSymplectic () const inline override virtual
Determines if the system is in symplectic form.
Returns
True if symplectic, False otherwise.
Reimplemented from ct::core::System< STATE_DIM, SCALAR >.
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::computeControlledDynamics (const StateVector< POS_DIM+VEL_DIM, SCALAR > & state, const time_t & t, const ControlVector< CONTROL_DIM, SCALAR > & control, StateVector< POS_DIM+VEL_DIM, SCALAR > & derivative) inline override virtual
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::computePdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > & x, const StateVector< VEL_DIM, SCALAR > & v, StateVector< POS_DIM, SCALAR > & pDot) inline
Computes the derivative of the position.
Parameters
[in] x The full state vector
[in] v The updated velocity
[out] pDot The derivative of the position
Referenced by ct::core::SymplecticSystem< 1, 1, 1, SCALAR >::computeControlledDynamics(), ct::core::SymplecticSystem< 1, 1, 1, SCALAR >::computePdot(), and ct::core::SymplecticSystem< 1, 1, 1, SCALAR >::computeVdot().
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::computeVdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > & x, const StateVector< POS_DIM, SCALAR > & p, StateVector< VEL_DIM, SCALAR > & vDot) inline
Computes the derivative of the velocity.
Parameters
[in] x The full state vector
[in] p The position
[out] vDot The derivative of the velocity
Referenced by ct::core::SymplecticSystem< 1, 1, 1, SCALAR >::computeControlledDynamics(), and ct::core::SymplecticSystem< 1, 1, 1, SCALAR >::computeVdot().
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::computePdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > & x, const StateVector< VEL_DIM, SCALAR > & v, const ControlVector< CONTROL_DIM, SCALAR > & control, StateVector< POS_DIM, SCALAR > & pDot) pure virtual
Computes the derivative of the position.
Parameters
[in] x The full state vector
[in] v The updated velocity
[in] control The control input
[out] pDot The derivative of the position
Implemented in ct::core::tpl::TestSymplecticSystem< SCALAR >.
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::computeVdot (const StateVector< POS_DIM+VEL_DIM, SCALAR > & x, const StateVector< POS_DIM, SCALAR > & p, const ControlVector< CONTROL_DIM, SCALAR > & control, StateVector< VEL_DIM, SCALAR > & vDot) pure virtual
Computes the derivative of the velocity.
Parameters
[in] x The full state vector
[in] p The position
[in] control The control input
[out] vDot The derivative of the velocity
Implemented in ct::core::tpl::TestSymplecticSystem< SCALAR >.
Member Data Documentation
template<size_t POS_DIM, size_t VEL_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem<POS_DIM + VEL_DIM, CONTROL_DIM, SCALAR> ct::core::SymplecticSystem< POS_DIM, VEL_DIM, CONTROL_DIM, SCALAR >::Base
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/systems/continuous_time/SymplecticSystem.h