ct::core::tpl::PeriodicActivation< SCALAR, TRAIT > Class Template Reference
ct::core::tpl::PeriodicActivation< SCALAR, TRAIT > Class Template Reference
#include <PeriodicActivation.hpp>
Public Member Functions
PeriodicActivation ()
PeriodicActivation (const SCALAR active_percentage, const SCALAR period, const SCALAR activation_offset, const SCALAR period_offset)
virtual ~PeriodicActivation ()
PeriodicActivation (const PeriodicActivation &arg)
virtual void loadConfigFile (const std::string &filename, const std::string &termName, bool verbose=false) override
load activations from file
virtual bool isActive (const SCALAR t) override
return if term is active
template<typename S = SCALAR>
std::enable_if< std::is_same< S, double >::value, bool >::type isActiveSpecialized (const SCALAR t)
template<typename S = SCALAR>
std::enable_if<!std::is_same< S, double >::value, bool >::type isActiveSpecialized (const SCALAR t)
virtual SCALAR computeActivation (const SCALAR t) override
compute activation multiplier based on scalar input
virtual void printInfo () override
print to console
Public Member Functions inherited from ct::core::tpl::ActivationBase< SCALAR >
ActivationBase ()=default
constructor
virtual ~ActivationBase ()=default
destructor
virtual SCALAR firstOrderDerivative (const SCALAR s)
first order derivative of this activation
virtual SCALAR secondOrderDerivative (const SCALAR s)
second order derivative of this activation
Constructor & Destructor Documentation
PeriodicActivation() [1/3]
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::PeriodicActivation () inline
PeriodicActivation() [2/3]
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::PeriodicActivation (const SCALAR active_percentage, const SCALAR period, const SCALAR activation_offset, const SCALAR period_offset) inline
~PeriodicActivation()
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> virtual ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::~PeriodicActivation () inline virtual
PeriodicActivation() [3/3]
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::PeriodicActivation (const PeriodicActivation< SCALAR, TRAIT > & arg) inline
Member Function Documentation
loadConfigFile()
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> virtual void ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::loadConfigFile (const std::string & filename, const std::string & termName, bool verbose = false) inline override virtual
load activations from file
Reimplemented from ct::core::tpl::ActivationBase< SCALAR >.
References ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::printInfo(), and verbose.
isActive()
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> virtual bool ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::isActive (const SCALAR s) inline override virtual
return if term is active
Reimplemented from ct::core::tpl::ActivationBase< SCALAR >.
References ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::isActiveSpecialized().
isActiveSpecialized() [1/2]
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> template<typename S = SCALAR> std::enable_if<std::is_same<S, double>::value, bool>::type ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::isActiveSpecialized (const SCALAR t) inline
Referenced by ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::isActive().
isActiveSpecialized() [2/2]
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> template<typename S = SCALAR> std::enable_if<!std::is_same<S, double>::value, bool>::type ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::isActiveSpecialized (const SCALAR t) inline
computeActivation()
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> virtual SCALAR ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::computeActivation (const SCALAR s) inline override virtual
compute activation multiplier based on scalar input
Reimplemented from ct::core::tpl::ActivationBase< SCALAR >.
printInfo()
template<typename SCALAR , typename TRAIT = typename ct::core::tpl::TraitSelector<SCALAR>::Trait> virtual void ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::printInfo () inline override virtual
print to console
Reimplemented from ct::core::tpl::ActivationBase< SCALAR >.
Referenced by ct::core::tpl::PeriodicActivation< SCALAR, TRAIT >::loadConfigFile().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/common/activations/PeriodicActivation.hpp