testing::internal::XmlUnitTestResultPrinter Class Reference
testing::internal::XmlUnitTestResultPrinter Class Reference
Public Member Functions
XmlUnitTestResultPrinter (const char *output_file)
void OnTestIterationEnd (const UnitTest &unit_test, int iteration) override
void ListTestsMatchingFilter (const std::vector< TestSuite * > &test_suites)
Public Member Functions inherited from testing::EmptyTestEventListener
void OnTestProgramStart (const UnitTest &) override
void OnTestIterationStart (const UnitTest &, int) override
void OnEnvironmentsSetUpStart (const UnitTest &) override
void OnEnvironmentsSetUpEnd (const UnitTest &) override
void OnTestSuiteStart (const TestSuite &) override
void OnTestCaseStart (const TestCase &) override
void OnTestStart (const TestInfo &) override
void OnTestPartResult (const TestPartResult &) override
void OnTestEnd (const TestInfo &) override
void OnTestSuiteEnd (const TestSuite &) override
void OnTestCaseEnd (const TestCase &) override
void OnEnvironmentsTearDownStart (const UnitTest &) override
void OnEnvironmentsTearDownEnd (const UnitTest &) override
void OnTestProgramEnd (const UnitTest &) override
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
Static Public Member Functions
static void PrintXmlTestsList (std::ostream *stream, const std::vector< TestSuite * > &test_suites)
Constructor & Destructor Documentation
testing::internal::XmlUnitTestResultPrinter::XmlUnitTestResultPrinter (const char * output_file) explicit
References GTEST_LOG_.
Member Function Documentation
void testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) override virtual
Reimplemented from testing::EmptyTestEventListener.
References FILE, and testing::internal::StringStreamToString().
void testing::internal::XmlUnitTestResultPrinter::ListTestsMatchingFilter (const std::vector< TestSuite * > & test_suites)
References ch, FILE, testing::internal::String::FormatByte(), testing::Message::GetString(), i, gmock_output_test::output, PrintXmlTestsList(), and testing::internal::StringStreamToString().
void testing::internal::XmlUnitTestResultPrinter::PrintXmlTestsList (std::ostream * stream, const std::vector< TestSuite * > & test_suites) static
References testing::Message::GetString(), testing::TestResult::GetTestProperty(), i, testing::internal::StreamableToString(), testing::TestResult::test_property_count(), and testing::TestSuite::total_test_count().
Referenced by ListTestsMatchingFilter(), and testing::internal::ShouldRunTestOnShard().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc