testing::gmock_generated_function_mockers_test::MockFoo Class Reference
testing::gmock_generated_function_mockers_test::MockFoo Class Reference
Public Member Functions
MockFoo ()
MOCK_METHOD1 (VoidReturning, void(int n))
MOCK_METHOD0 (Nullary, int())
MOCK_METHOD1 (Unary, bool(int))
MOCK_METHOD2 (Binary, long(short, int))
MOCK_METHOD10 (Decimal, int(bool, char, short, int, long, float, double, unsigned, char *, const std::string &str))
MOCK_METHOD1 (TakesNonConstReference, bool(int &))
MOCK_METHOD1 (TakesConstReference, std::string(const int &))
MOCK_METHOD1 (TakesConst, bool(const int))
MOCK_METHOD0 (ReturnTypeWithComma, std::map< int, std::string >())
MOCK_CONST_METHOD1 (ReturnTypeWithComma, std::map< int, std::string >(int))
MOCK_METHOD0 (OverloadedOnArgumentNumber, int())
MOCK_METHOD1 (OverloadedOnArgumentNumber, int(int))
MOCK_METHOD1 (OverloadedOnArgumentType, int(int))
MOCK_METHOD1 (OverloadedOnArgumentType, char(char))
MOCK_METHOD0 (OverloadedOnConstness, int())
MOCK_CONST_METHOD0 (OverloadedOnConstness, char())
MOCK_METHOD1 (TypeWithHole, int(int(*)()))
MOCK_METHOD1 (TypeWithComma, int(const std::map< int, std::string > &))
MOCK_METHOD1 (TypeWithTemplatedCopyCtor, int(const TemplatedCopyable< int > &))
Public Member Functions inherited from testing::gmock_generated_function_mockers_test::FooInterface
virtual ~FooInterface ()
virtual void VoidReturning (int x)=0
virtual int Nullary ()=0
virtual bool Unary (int x)=0
virtual long Binary (short x, int y)=0
virtual int Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char *j, const std::string &k)=0
virtual bool TakesNonConstReference (int &n)=0
virtual std::string TakesConstReference (const int &n)=0
virtual bool TakesConst (const int x)=0
virtual int OverloadedOnArgumentNumber ()=0
virtual int OverloadedOnArgumentNumber (int n)=0
virtual int OverloadedOnArgumentType (int n)=0
virtual char OverloadedOnArgumentType (char c)=0
virtual int OverloadedOnConstness ()=0
virtual char OverloadedOnConstness () const =0
virtual int TypeWithHole (int(*func)())=0
virtual int TypeWithComma (const std::map< int, std::string > &a_map)=0
virtual int TypeWithTemplatedCopyCtor (const TemplatedCopyable< int > &a_vector)=0
Constructor & Destructor Documentation
testing::gmock_generated_function_mockers_test::MockFoo::MockFoo () inline
References testing::gmock_generated_actions_test::Binary(), GTEST_DISALLOW_COPY_AND_ASSIGN_, i, MOCK_CONST_METHOD0, MOCK_CONST_METHOD1, MOCK_CONST_METHOD1_WITH_CALLTYPE, MOCK_METHOD0, MOCK_METHOD0_WITH_CALLTYPE, MOCK_METHOD1, MOCK_METHOD10, MOCK_METHOD10_WITH_CALLTYPE, MOCK_METHOD1_WITH_CALLTYPE, MOCK_METHOD2, n, testing::gmock_generated_actions_test::Nullary(), and testing::gmock_more_actions_test::Unary().
Member Function Documentation
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (VoidReturning , void(int n))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD0 (Nullary , int())
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (Unary , bool(int))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD2 (Binary , long(short, int))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD10 (Decimal , int(bool, char, short, int, long, float, double, unsigned, char *, const std::string &str))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (TakesNonConstReference , bool(int &))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (TakesConstReference , std::string(const int &))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (TakesConst , bool(const int))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD0 (ReturnTypeWithComma , std::map< int, std::string > ())
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_CONST_METHOD1 (ReturnTypeWithComma , std::map< int, std::string > int)
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD0 (OverloadedOnArgumentNumber , int())
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (OverloadedOnArgumentNumber , int(int))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (OverloadedOnArgumentType , int(int))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (OverloadedOnArgumentType , char(char))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD0 (OverloadedOnConstness , int())
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_CONST_METHOD0 (OverloadedOnConstness , char())
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (TypeWithHole , int(int(*)()))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (TypeWithComma , int(const std::map< int, std::string > &))
testing::gmock_generated_function_mockers_test::MockFoo::MOCK_METHOD1 (TypeWithTemplatedCopyCtor , int(const TemplatedCopyable< int > &))
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/test/gmock-generated-function-mockers_test.cc