ct::core::LTISystem< STATE_DIM, CONTROL_DIM > Class Template Reference
ct::core::LTISystem< STATE_DIM, CONTROL_DIM > Class Template Reference
Linear time-invariant system.
#include <LTISystem.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW LTISystem (const Eigen::Matrix< double, STATE_DIM, STATE_DIM > &A, const Eigen::Matrix< double, STATE_DIM, CONTROL_DIM > &B, const Eigen::Matrix< double, STATE_DIM, STATE_DIM > &C=Eigen::Matrix< double, STATE_DIM, STATE_DIM >::Identity(), const Eigen::Matrix< double, STATE_DIM, CONTROL_DIM > D=Eigen::Matrix< double, STATE_DIM, CONTROL_DIM >::Zero())
Constructs a linear time invariant system.
LTISystem (const LTISystem &arg)
copy constructor
LTISystem< STATE_DIM, CONTROL_DIM > * clone () const override
deep clone
virtual ~LTISystem ()
virtual const Eigen::Matrix< double, STATE_DIM, STATE_DIM > & getDerivativeState (const StateVector< STATE_DIM > &x, const ControlVector< CONTROL_DIM > &u, const double t=0.0) override
get A matrix
virtual const Eigen::Matrix< double, STATE_DIM, CONTROL_DIM > & getDerivativeControl (const StateVector< STATE_DIM > &x, const ControlVector< CONTROL_DIM > &u, const double t=0.0) override
get B matrix
Eigen::Matrix< double, STATE_DIM, STATE_DIM > & A ()
get A matrix
Eigen::Matrix< double, STATE_DIM, CONTROL_DIM > & B ()
get B matrix
Eigen::Matrix< double, STATE_DIM, STATE_DIM > & C ()
get C matrix
Eigen::Matrix< double, STATE_DIM, CONTROL_DIM > & D ()
get D matrix
void computeControlledDynamics (const Eigen::Matrix< double, STATE_DIM, 1 > &state, const Time &t, const Eigen::Matrix< double, CONTROL_DIM, 1 > &control, Eigen::Matrix< double, STATE_DIM, 1 > &derivative)
computes the system dynamics
void computeOutput (const Eigen::Matrix< double, STATE_DIM, 1 > &state, const Time &t, const Eigen::Matrix< double, CONTROL_DIM, 1 > &control, Eigen::Matrix< double, STATE_DIM, 1 > &output)
computes the system output (measurement)
void computeControllabilityMatrix (Eigen::Matrix< double, STATE_DIM, STATE_DIM *CONTROL_DIM > &CO)
computes the controllability matrix
bool isControllable ()
checks if system is fully controllable
void computeObservabilityMatrix (Eigen::Matrix< double, STATE_DIM, STATE_DIM *STATE_DIM > &O)
computes the observability matrix
bool isObservable ()
checks if system is fully observable
Public Member Functions inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM >
LinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~LinearSystem ()
destructor
virtual void computeControlledDynamics (const state_vector_t &state, const time_t &t, const control_vector_t &control, state_vector_t &derivative) override
compute the system dynamics
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
get the A matrix of a linear system
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
get the B matrix of a linear system
virtual void getDerivatives (state_matrix_t &A, state_control_matrix_t &B, const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))
Get both linear system matrices A and B in one call.
Public Member Functions inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, double >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
ControlledSystem (const ControlledSystem &arg)
copy constructor
virtual ~ControlledSystem ()
destructor
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double >> &controller)
set a new controller
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double >> &controller) const
get the controller instance
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double > > getController ()
get the controller instace
virtual void computeDynamics (const StateVector< STATE_DIM, double > &state, const time_t &t, StateVector< STATE_DIM, double > &derivative) override
compute the dynamics of the system
ControlVector< CONTROL_DIM, double > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, double >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
System (const System &other)
copy constructor
virtual ~System ()
destructor
virtual void computeDynamics (const StateVector< STATE_DIM, double > &state, const time_t &t, StateVector< STATE_DIM, double > &derivative)=0
computes the system dynamics
SYSTEM_TYPE getType () const
get the type of system
virtual bool isSymplectic () const
Determines if the system is in symplectic form.
Additional Inherited Members
Public Types inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM >
typedef Base::time_t time_t
typedef StateVector< STATE_DIM, double > state_vector_t
state vector type
typedef ControlVector< CONTROL_DIM, double > control_vector_t
input vector type
typedef StateMatrix< STATE_DIM, double > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, double > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, double > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, double >
typedef double time_t
the type of the time variable
Public Attributes inherited from ct::core::LinearSystem< STATE_DIM, CONTROL_DIM >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem< STATE_DIM, CONTROL_DIM, double > Base
Public Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, double > Base
Public Attributes inherited from ct::core::System< STATE_DIM, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef double S
the scalar type
Protected Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double > > controller_
the controller instance
ControlVector< CONTROL_DIM, double > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, double >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM>
class ct::core::LTISystem< STATE_DIM, CONTROL_DIM >
Linear time-invariant system.
This defines a general linear time-invariant system of the form
Template Parameters
STATE_DIM size of state vector
CONTROL_DIM size of control vector
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM> EIGEN_MAKE_ALIGNED_OPERATOR_NEW ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::LTISystem (const Eigen::Matrix< double, STATE_DIM, STATE_DIM > & A, const Eigen::Matrix< double, STATE_DIM, CONTROL_DIM > & B, const Eigen::Matrix< double, STATE_DIM, STATE_DIM > & C = Eigen::Matrix<double, STATE_DIM, STATE_DIM>::Identity(), const Eigen::Matrix< double, STATE_DIM, CONTROL_DIM > D = Eigen::Matrix<double, STATE_DIM, CONTROL_DIM>::Zero()) inline
Constructs a linear time invariant system.
Parameters
A A matrix
B B matrix
C C matrix
D D matrix
Returns
instance of the LTI system
template<size_t STATE_DIM, size_t CONTROL_DIM> ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::LTISystem (const LTISystem< STATE_DIM, CONTROL_DIM > & arg) inline
copy constructor
template<size_t STATE_DIM, size_t CONTROL_DIM> virtual ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::~LTISystem () inline virtual
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM> LTISystem<STATE_DIM, CONTROL_DIM>* ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::clone () const inline override virtual
deep clone
Implements ct::core::LinearSystem< STATE_DIM, CONTROL_DIM >.
template<size_t STATE_DIM, size_t CONTROL_DIM> virtual const Eigen::Matrix<double, STATE_DIM, STATE_DIM>& ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::getDerivativeState (const StateVector< STATE_DIM > & x, const ControlVector< CONTROL_DIM > & u, const double t = 0.0) inline override virtual
get A matrix
template<size_t STATE_DIM, size_t CONTROL_DIM> virtual const Eigen::Matrix<double, STATE_DIM, CONTROL_DIM>& ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::getDerivativeControl (const StateVector< STATE_DIM > & x, const ControlVector< CONTROL_DIM > & u, const double t = 0.0) inline override virtual
get B matrix
template<size_t STATE_DIM, size_t CONTROL_DIM> Eigen::Matrix<double, STATE_DIM, STATE_DIM>& ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::A () inline
get A matrix
template<size_t STATE_DIM, size_t CONTROL_DIM> Eigen::Matrix<double, STATE_DIM, CONTROL_DIM>& ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::B () inline
get B matrix
template<size_t STATE_DIM, size_t CONTROL_DIM> Eigen::Matrix<double, STATE_DIM, STATE_DIM>& ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::C () inline
get C matrix
template<size_t STATE_DIM, size_t CONTROL_DIM> Eigen::Matrix<double, STATE_DIM, CONTROL_DIM>& ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::D () inline
get D matrix
template<size_t STATE_DIM, size_t CONTROL_DIM> void ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::computeControlledDynamics (const Eigen::Matrix< double, STATE_DIM, 1 > & state, const Time & t, const Eigen::Matrix< double, CONTROL_DIM, 1 > & control, Eigen::Matrix< double, STATE_DIM, 1 > & derivative) inline
computes the system dynamics
Computes
Parameters
state current state x
t time (gets ignored)
control control input
derivative state derivative
template<size_t STATE_DIM, size_t CONTROL_DIM> void ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::computeOutput (const Eigen::Matrix< double, STATE_DIM, 1 > & state, const Time & t, const Eigen::Matrix< double, CONTROL_DIM, 1 > & control, Eigen::Matrix< double, STATE_DIM, 1 > & output) inline
computes the system output (measurement)
Computes
Parameters
state current state x
t time (gets ignored)
control control input
output system output (measurement)
template<size_t STATE_DIM, size_t CONTROL_DIM> void ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::computeControllabilityMatrix (Eigen::Matrix< double, STATE_DIM, STATE_DIM *CONTROL_DIM > & CO) inline
computes the controllability matrix
Computes the controllability matrix to assess controllability. See isControllable() for the full test.
Todo:
Move to LinearSystem
Parameters
CO controllability matrix
References i.
Referenced by ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::isControllable().
template<size_t STATE_DIM, size_t CONTROL_DIM> bool ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::isControllable () inline
checks if system is fully controllable
Todo:
Move to LinearSystem
Returns
true if fully controllable, false if only partially or non-controllable
References ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::computeControllabilityMatrix().
template<size_t STATE_DIM, size_t CONTROL_DIM> void ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::computeObservabilityMatrix (Eigen::Matrix< double, STATE_DIM, STATE_DIM *STATE_DIM > & O) inline
computes the observability matrix
Todo:
Move to LinearSystem
Computes the observability matrix to assess observability. See isObservable() for the full test.
Parameters
O observability matrix
References i.
Referenced by ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::isObservable().
template<size_t STATE_DIM, size_t CONTROL_DIM> bool ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::isObservable () inline
checks if system is fully observable
Todo:
Move to LinearSystem
Returns
true if fully observable, false if only partially or non-observable
References ct::core::LTISystem< STATE_DIM, CONTROL_DIM >::computeObservabilityMatrix().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/systems/continuous_time/linear/LTISystem.h