ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
Computes the linearization of a general non-linear DiscreteControlledSystem using numerical differentiation.
#include <DiscreteSystemLinearizer.h>
Public Types
typedef DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > system_t
type of system to be linearized
typedef Base::state_vector_t state_vector_t
state vector type
typedef Base::control_vector_t control_vector_t
control vector type
typedef Base::state_matrix_t state_matrix_t
state Jacobian type (A)
typedef Base::state_control_matrix_t state_control_matrix_t
Public Types inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef Base::time_t time_t
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef StateMatrix< STATE_DIM, SCALAR > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::time_t time_t
Public Types inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef int time_t
the type of the time variable
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Member Functions
DiscreteSystemLinearizer (std::shared_ptr< system_t > nonlinearSystem, bool doubleSidedDerivative=true)
control Jacobian type (B)
DiscreteSystemLinearizer (const DiscreteSystemLinearizer &arg)
copy constructor
virtual ~DiscreteSystemLinearizer ()
destructor
DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override
deep cloning
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const int n=0)
get the Jacobian with respect to the state
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const int n=0)
get the Jacobian with respect to the input
virtual void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t numSteps, state_matrix_t &A, state_control_matrix_t &B) override
retrieve discrete-time linear system matrices A and B.
Public Member Functions inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteLinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~DiscreteLinearSystem ()
destructor
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext) override
compute the system dynamics
void getAandB (const state_vector_t &x, const control_vector_t &u, const int n, state_matrix_t &A, state_control_matrix_t &B)
Public Member Functions inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
DiscreteControlledSystem (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
DiscreteControlledSystem (const ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > &arg)
copy constructor
virtual ~DiscreteControlledSystem ()=default
destructor
void setController (const std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void propagateDynamics (const state_vector_t &state, const time_t n, state_vector_t &stateNext) override
propagates the system dynamics forward by one step
Public Member Functions inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteSystem (const SYSTEM_TYPE &type=GENERAL)
constructor
virtual ~DiscreteSystem ()
desctructor
virtual void propagateDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t n, StateVector< STATE_DIM, SCALAR > &stateNext)=0
propagates the system dynamics forward by one step
SYSTEM_TYPE getType () const
get the type of system
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
Protected Attributes
std::shared_ptr< system_t > nonlinearSystem_
instance of non-linear system
DynamicsLinearizerNumDiff< STATE_DIM, CONTROL_DIM, SCALAR, int > linearizer_
instance of numerical-linearizer
state_matrix_t dFdx_
Jacobian wrt state.
state_control_matrix_t dFdu_
Jacobian wrt input.
Protected Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
Protected Attributes inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >
Computes the linearization of a general non-linear DiscreteControlledSystem using numerical differentiation.
This class takes a non-linear DiscreteControlledSystem and computes the linearization around a certain point , .
where
Examples for using the SystemLinearizer (and the Auto-diff Linearizer) can be found in AutoDiffLinearizerTest.cpp
Note
In case your ControlledSystem is templated on scalar type, we suggest using the DiscreteSystemLinearizerAD for highest efficiency and accuracy.
Template Parameters
dimension of state vector
dimension of control vector
SCALAR underlying scalar type of the system
Examples:
AutoDiffLinearizerTest.cpp.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DiscreteControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::system_t
type of system to be linearized
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_vector_t ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
state vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::control_vector_t ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
control vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_matrix_t ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
state Jacobian type (A)
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_control_matrix_t ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::state_control_matrix_t
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteSystemLinearizer (std::shared_ptr< system_t > nonlinearSystem, bool doubleSidedDerivative = true) inline
control Jacobian type (B)
default constructor
Initializes the linearizer with a non-linear system.
Parameters
nonlinearSystem non-linear system to linearize
doubleSidedDerivative if true, double sided numerical differentiation is used
References ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_, and ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteSystemLinearizer (const DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR > & arg) inline
copy constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::~DiscreteSystemLinearizer () inline virtual
destructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> DiscreteSystemLinearizer<STATE_DIM, CONTROL_DIM, SCALAR>* ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const inline override virtual
deep cloning
Implements ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual const state_matrix_t& ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const int n = 0) inline virtual
get the Jacobian with respect to the state
This computes the linearization of the system with respect to the state at a given point , , i.e. it computes
Parameters
x state to linearize at
u control to linearize at
n index
Returns
Jacobian wrt state
References ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_, ct::core::DynamicsLinearizerNumDiff< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeState(), ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_, and n.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual const state_control_matrix_t& ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const int n = 0) inline virtual
get the Jacobian with respect to the input
This computes the linearization of the system with respect to the input at a given point , , i.e. it computes
Parameters
x state to linearize at
u control to linearize at
n index
Returns
Jacobian wrt input
References ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_, ct::core::DynamicsLinearizerNumDiff< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeControl(), ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_, and n.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB (const state_vector_t & x, const control_vector_t & u, const state_vector_t & x_next, const int n, size_t numSteps, state_matrix_t & A, state_control_matrix_t & B) inline override virtual
retrieve discrete-time linear system matrices A and B.
This computes matrices A and B such that
Note that the inputs x_next and subSteps are being ignored
Parameters
x the state setpoint at n
u the control setpoint at n
n the time setpoint
x_next -> ignored
subSteps -> ignored
A the resulting linear system matrix A
B the resulting linear system matrix B
Implements ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_, ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_, ct::core::DynamicsLinearizerNumDiff< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeControl(), ct::core::DynamicsLinearizerNumDiff< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeState(), and ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_.
Referenced by TEST().
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteLinearSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::Base
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> std::shared_ptr<system_t> ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::nonlinearSystem_ protected
instance of non-linear system
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> DynamicsLinearizerNumDiff<STATE_DIM, CONTROL_DIM, SCALAR, int> ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_ protected
instance of numerical-linearizer
Referenced by ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), and ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> state_matrix_t ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_ protected
Jacobian wrt state.
Referenced by ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteSystemLinearizer(), ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), and ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> state_control_matrix_t ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_ protected
Jacobian wrt input.
Referenced by ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteSystemLinearizer(), ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), and ct::core::DiscreteSystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/systems/discrete_time/linear/DiscreteSystemLinearizer.h