ct::core::EventHandler< STATE_DIM, SCALAR > Class Template Reference
ct::core::EventHandler< STATE_DIM, SCALAR > Class Template Reference abstract
Interface for an event handler for an Integrator.
#include <EventHandler.h>
Public Member Functions
EventHandler ()
Default constructor.
virtual ~EventHandler ()
destructor
virtual bool callOnSubsteps ()=0
virtual void reset ()=0
reset event handler
virtual bool checkEvent (const StateVector< STATE_DIM, SCALAR > &state, const SCALAR &t)=0
check if an event has happened
virtual void handleEvent (const StateVector< STATE_DIM, SCALAR > &state, const SCALAR &t)=0
handle the event
Detailed Description
template<size_t STATE_DIM, typename SCALAR = double>
class ct::core::EventHandler< STATE_DIM, SCALAR >
Interface for an event handler for an Integrator.
An Integrator can call an EventHandler after each integration step to check or log current states etc. This is useful for terminating integrators or checking for events such as system dynamic switches in hybrid systems.
Derive from this class to implement your custom event handler.
Template Parameters
STATE_DIM dimensionality of the state vector
Constructor & Destructor Documentation
EventHandler()
template<size_t STATE_DIM, typename SCALAR = double> ct::core::EventHandler< STATE_DIM, SCALAR >::EventHandler () inline
Default constructor.
~EventHandler()
template<size_t STATE_DIM, typename SCALAR = double> virtual ct::core::EventHandler< STATE_DIM, SCALAR >::~EventHandler () inline virtual
destructor
Member Function Documentation
callOnSubsteps()
template<size_t STATE_DIM, typename SCALAR = double> virtual bool ct::core::EventHandler< STATE_DIM, SCALAR >::callOnSubsteps () pure virtual
Implemented in ct::core::SubstepRecorder< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::MaxStepsEventHandler< STATE_DIM >, and ct::core::KillIntegrationEventHandler< STATE_DIM >.
Referenced by ct::core::EventHandler< STATE_DIM >::~EventHandler().
reset()
template<size_t STATE_DIM, typename SCALAR = double> virtual void ct::core::EventHandler< STATE_DIM, SCALAR >::reset () pure virtual
reset event handler
Implemented in ct::core::SubstepRecorder< STATE_DIM, CONTROL_DIM, SCALAR >, ct::core::KillIntegrationEventHandler< STATE_DIM >, and ct::core::MaxStepsEventHandler< STATE_DIM >.
Referenced by ct::core::EventHandler< STATE_DIM >::~EventHandler().
checkEvent()
template<size_t STATE_DIM, typename SCALAR = double> virtual bool ct::core::EventHandler< STATE_DIM, SCALAR >::checkEvent (const StateVector< STATE_DIM, SCALAR > & state, const SCALAR & t) pure virtual
check if an event has happened
checks if an event has happened and whether handleEvent() needs to be called
Parameters
state current state of the system
t current time
Returns
true if an event has happened
Referenced by ct::core::EventHandler< STATE_DIM >::~EventHandler().
handleEvent()
template<size_t STATE_DIM, typename SCALAR = double> virtual void ct::core::EventHandler< STATE_DIM, SCALAR >::handleEvent (const StateVector< STATE_DIM, SCALAR > & state, const SCALAR & t) pure virtual
handle the event
does something with an event that just occurred
Parameters
state current state of the system
t current time
Referenced by ct::core::EventHandler< STATE_DIM >::~EventHandler().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/integration/EventHandler.h