testing::internal::FinalSuccessChecker Class Reference
testing::internal::FinalSuccessChecker Class Reference
Protected Member Functions
void TearDown () override
Additional Inherited Members
Public Member Functions inherited from testing::Environment
virtual ~Environment ()
virtual void SetUp ()
Member Function Documentation
void testing::internal::FinalSuccessChecker::TearDown () inline override protected virtual
Reimplemented from testing::Environment.
References ASSERT_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, testing::UnitTest::Failed(), testing::UnitTest::failed_test_count(), testing::UnitTest::failed_test_suite_count(), testing::internal::UnitTestHelper::FindTestSuite(), testing::UnitTest::GetInstance(), testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::UnitTestHelper::GetSortedTestSuites(), testing::TestResult::GetTestProperty(), testing::internal::IsNull(), testing::UnitTest::Passed(), testing::TestInfo::result(), testing::UnitTest::successful_test_count(), testing::UnitTest::successful_test_suite_count(), and testing::UnitTest::total_test_suite_count().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/gtest-unittest-api_test.cc