testing::internal::PrettyUnitTestResultPrinter Class Reference
testing::internal::PrettyUnitTestResultPrinter Class Reference
Public Member Functions
PrettyUnitTestResultPrinter ()
void OnTestProgramStart (const UnitTest &) override
void OnTestIterationStart (const UnitTest &unit_test, int iteration) override
void OnEnvironmentsSetUpStart (const UnitTest &unit_test) override
void OnEnvironmentsSetUpEnd (const UnitTest &) override
void OnTestCaseStart (const TestSuite &test_suite) override
void OnTestStart (const TestInfo &test_info) override
void OnTestPartResult (const TestPartResult &result) override
void OnTestEnd (const TestInfo &test_info) override
void OnTestCaseEnd (const TestSuite &test_suite) override
void OnEnvironmentsTearDownStart (const UnitTest &unit_test) override
void OnEnvironmentsTearDownEnd (const UnitTest &) override
void OnTestIterationEnd (const UnitTest &unit_test, int iteration) override
void OnTestProgramEnd (const UnitTest &) override
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
virtual void OnTestSuiteStart (const TestSuite &)
virtual void OnTestCaseStart (const TestCase &)
virtual void OnTestSuiteEnd (const TestSuite &)
virtual void OnTestCaseEnd (const TestCase &)
Static Public Member Functions
static void PrintTestName (const char *test_suite, const char *test)
Constructor & Destructor Documentation
testing::internal::PrettyUnitTestResultPrinter::PrettyUnitTestResultPrinter () inline
Member Function Documentation
static void testing::internal::PrettyUnitTestResultPrinter::PrintTestName (const char * test_suite, const char * test) inline static
void testing::internal::PrettyUnitTestResultPrinter::OnTestProgramStart (const UnitTest &) inline override virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart (const UnitTest & unit_test, int iteration) override virtual
Implements testing::TestEventListener.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_YELLOW, testing::internal::ColoredPrintf(), testing::internal::posix::GetEnv(), GTEST_FLAG, GTEST_NAME_, testing::internal::Int32FromEnvOrDie(), testing::UnitTest::random_seed(), testing::internal::ShouldShard(), testing::UnitTest::test_suite_to_run_count(), and testing::UnitTest::test_to_run_count().
void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsSetUpStart (const UnitTest & unit_test) override virtual
Implements testing::TestEventListener.
References testing::internal::COLOR_GREEN, and testing::internal::ColoredPrintf().
void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsSetUpEnd (const UnitTest &) inline override virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart (const TestSuite & test_suite) override
References testing::internal::COLOR_GREEN, testing::internal::ColoredPrintf(), testing::TestSuite::name(), testing::TestSuite::test_to_run_count(), and testing::TestSuite::type_param().
void testing::internal::PrettyUnitTestResultPrinter::OnTestStart (const TestInfo & test_info) override virtual
Implements testing::TestEventListener.
References testing::internal::COLOR_GREEN, testing::internal::ColoredPrintf(), testing::TestInfo::name(), and testing::TestInfo::test_suite_name().
void testing::internal::PrettyUnitTestResultPrinter::OnTestPartResult (const TestPartResult & result) override virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestEnd (const TestInfo & test_info) override virtual
Implements testing::TestEventListener.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::TestResult::elapsed_time(), testing::TestResult::Failed(), GTEST_FLAG, testing::TestInfo::name(), testing::TestResult::Passed(), testing::TestInfo::result(), testing::TestResult::Skipped(), testing::internal::StreamableToString(), and testing::TestInfo::test_suite_name().
void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd (const TestSuite & test_suite) override
References testing::internal::COLOR_GREEN, testing::internal::ColoredPrintf(), testing::TestSuite::elapsed_time(), GTEST_FLAG, testing::TestSuite::name(), testing::internal::StreamableToString(), and testing::TestSuite::test_to_run_count().
void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart (const UnitTest & unit_test) override virtual
Implements testing::TestEventListener.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::TestResult::Failed(), testing::TestSuite::failed_test_count(), testing::UnitTest::failed_test_count(), testing::TestSuite::GetTestInfo(), testing::UnitTest::GetTestSuite(), i, testing::TestInfo::name(), testing::TestSuite::name(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::TestSuite::should_run(), testing::TestResult::Skipped(), testing::TestSuite::skipped_test_count(), testing::UnitTest::skipped_test_count(), testing::TestSuite::total_test_count(), and testing::UnitTest::total_test_suite_count().
void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownEnd (const UnitTest &) inline override virtual
Implements testing::TestEventListener.
void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) override virtual
Implements testing::TestEventListener.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::COLOR_YELLOW, testing::internal::ColoredPrintf(), testing::UnitTest::elapsed_time(), testing::TestSuite::failed_test_count(), testing::UnitTest::failed_test_count(), GTEST_FLAG, testing::UnitTest::Passed(), testing::UnitTest::reportable_disabled_test_count(), testing::TestSuite::skipped_test_count(), testing::UnitTest::skipped_test_count(), testing::internal::StreamableToString(), testing::UnitTest::successful_test_count(), testing::UnitTest::test_suite_to_run_count(), and testing::UnitTest::test_to_run_count().
void testing::internal::PrettyUnitTestResultPrinter::OnTestProgramEnd (const UnitTest &) inline override virtual
Implements testing::TestEventListener.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc