ct::core::Integrator< STATE_DIM, SCALAR > Class Template Reference
ct::core::Integrator< STATE_DIM, SCALAR > Class Template Reference
Standard Integrator.
#include <Integrator.h>
Public Types
typedef std::vector< EventHandlerPtr, Eigen::aligned_allocator< EventHandlerPtr > > EventHandlerPtrVector
Public Member Functions
Integrator (const std::shared_ptr< System< STATE_DIM, SCALAR >> &system, const IntegrationType &intType=IntegrationType::EULERCT, const EventHandlerPtrVector &eventHandlers=EventHandlerPtrVector(0))
constructor
Integrator (const std::shared_ptr< System< STATE_DIM, SCALAR >> &system, const IntegrationType &intType, const EventHandlerPtr &eventHandler)
void changeIntegrationType (const IntegrationType &intType)
Changes the integration type.
void setApadativeErrorTolerances (const SCALAR absErrTol, const SCALAR &relErrTol)
Sets the adaptive error tolerances.
void integrate_n_steps (StateVector< STATE_DIM, SCALAR > &state, const SCALAR &startTime, size_t numSteps, SCALAR dt, StateVectorArray< STATE_DIM, SCALAR > &stateTrajectory, tpl::TimeArray< SCALAR > &timeTrajectory)
Equidistant integration based on number of time steps and step length.
void integrate_n_steps (StateVector< STATE_DIM, SCALAR > &state, const SCALAR &startTime, size_t numSteps, SCALAR dt)
Equidistant integration based on number of time steps and step length.
void integrate_const (StateVector< STATE_DIM, SCALAR > &state, const SCALAR &startTime, const SCALAR &finalTime, SCALAR dt, StateVectorArray< STATE_DIM, SCALAR > &stateTrajectory, tpl::TimeArray< SCALAR > &timeTrajectory)
Equidistant integration based on initial and final time as well as step length.
void integrate_const (StateVector< STATE_DIM, SCALAR > &state, const SCALAR &startTime, const SCALAR &finalTime, SCALAR dt)
Equidistant integration based on initial and final time as well as step length.
void integrate_adaptive (StateVector< STATE_DIM, SCALAR > &state, const SCALAR &startTime, const SCALAR &finalTime, StateVectorArray< STATE_DIM, SCALAR > &stateTrajectory, tpl::TimeArray< SCALAR > &timeTrajectory, const SCALAR dtInitial=SCALAR(0.01))
integrate forward from an initial to a final time using an adaptive scheme
void integrate_adaptive (StateVector< STATE_DIM, SCALAR > &state, const SCALAR &startTime, const SCALAR &finalTime, SCALAR dtInitial=SCALAR(0.01))
integrate forward from an initial to a final time using an adaptive scheme
void integrate_times (StateVector< STATE_DIM, SCALAR > &state, const tpl::TimeArray< SCALAR > &timeTrajectory, StateVectorArray< STATE_DIM, SCALAR > &stateTrajectory, SCALAR dtInitial=SCALAR(0.01))
Integrate system using a given time trajectory.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< EventHandler< STATE_DIM, SCALAR > > EventHandlerPtr
Detailed Description
template<size_t STATE_DIM, typename SCALAR = double>
class ct::core::Integrator< STATE_DIM, SCALAR >
Standard Integrator.
A standard Integrator for numerically solving Ordinary Differential Equations (ODEs) of the form
Unit test IntegrationTest.cpp illustrates the use of Integrator.h
Template Parameters
STATE_DIM the size of the state vector
SCALAR The scalar type
Examples:
DampedOscillator.cpp, DampedOscillatorCustomController.cpp, and MasspointIntegration.cpp.
Member Typedef Documentation
EventHandlerPtrVector
template<size_t STATE_DIM, typename SCALAR = double> typedef std::vector<EventHandlerPtr, Eigen::aligned_allocator<EventHandlerPtr> > ct::core::Integrator< STATE_DIM, SCALAR >::EventHandlerPtrVector
Constructor & Destructor Documentation
Integrator() [1/2]
template<size_t STATE_DIM, typename SCALAR > ct::core::Integrator< STATE_DIM, SCALAR >::Integrator (const std::shared_ptr< System< STATE_DIM, SCALAR >> & system, const IntegrationType & intType = IntegrationType::EULERCT, const EventHandlerPtrVector & eventHandlers = EventHandlerPtrVector(0))
constructor
Creates a standard integrator
Parameters
system the system (ODE)
eventHandlers optional event handler
absErrTol optional absolute error tolerance (for variable step solvers)
relErrTol optional relative error tolerance (for variable step solvers)
References ct::core::Integrator< STATE_DIM, SCALAR >::changeIntegrationType().
Integrator() [2/2]
template<size_t STATE_DIM, typename SCALAR > ct::core::Integrator< STATE_DIM, SCALAR >::Integrator (const std::shared_ptr< System< STATE_DIM, SCALAR >> & system, const IntegrationType & intType, const EventHandlerPtr & eventHandler)
References ct::core::Integrator< STATE_DIM, SCALAR >::changeIntegrationType().
Member Function Documentation
changeIntegrationType()
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::changeIntegrationType (const IntegrationType & intType)
Changes the integration type.
Parameters
[in] intType The new integration type
Referenced by ct::core::Integrator< STATE_DIM, SCALAR >::Integrator().
setApadativeErrorTolerances()
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::setApadativeErrorTolerances (const SCALAR absErrTol, const SCALAR & relErrTol)
Sets the adaptive error tolerances.
Parameters
[in] absErrTol The absolute error tolerance
[in] relErrTol The relative error tolerance
integrate_n_steps() [1/2]
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps (StateVector< STATE_DIM, SCALAR > & state, const SCALAR & startTime, size_t numSteps, SCALAR dt, StateVectorArray< STATE_DIM, SCALAR > & stateTrajectory, tpl::TimeArray< SCALAR > & timeTrajectory)
Equidistant integration based on number of time steps and step length.
Integrates n steps forward from the current state recording the state and time trajectory. For a recording free version, see the function below.
Warning
Overrides the initial state
Parameters
state initial state, contains the final state after integration
startTime start time of the integration
numSteps number of steps to integrate forward
dt step size (fixed also for variable step solvers)
stateTrajectory state evolution over time
timeTrajectory time trajectory corresponding to state trajectory
Referenced by main(), ct::core::ControlSimulator< CONTROLLED_SYSTEM >::simulateSystem(), TEST(), and testSensitivities().
integrate_n_steps() [2/2]
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps (StateVector< STATE_DIM, SCALAR > & state, const SCALAR & startTime, size_t numSteps, SCALAR dt)
Equidistant integration based on number of time steps and step length.
Warning
Overrides the initial state
Parameters
state initial state, contains the final state after integration
startTime start time of the integration
numSteps number of steps to integrate forward
dt step size (fixed also for variable step solvers)
integrate_const() [1/2]
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::integrate_const (StateVector< STATE_DIM, SCALAR > & state, const SCALAR & startTime, const SCALAR & finalTime, SCALAR dt, StateVectorArray< STATE_DIM, SCALAR > & stateTrajectory, tpl::TimeArray< SCALAR > & timeTrajectory)
Equidistant integration based on initial and final time as well as step length.
Integrates forward from the current state recording the state and time trajectory. For a recording free version, see the function below.
Warning
Overrides the initial state
Parameters
state initial state, contains the final state after integration
startTime start time of the integration
finalTime the final time of the integration
dt step size (fixed also for variable step solvers)
stateTrajectory state evolution over time
timeTrajectory time trajectory corresponding to state trajectory
integrate_const() [2/2]
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::integrate_const (StateVector< STATE_DIM, SCALAR > & state, const SCALAR & startTime, const SCALAR & finalTime, SCALAR dt)
Equidistant integration based on initial and final time as well as step length.
Warning
Overrides the initial state
Parameters
state initial state, contains the final state after integration
startTime start time of the integration
finalTime the final time of the integration
dt step size (fixed also for variable step solvers)
integrate_adaptive() [1/2]
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::integrate_adaptive (StateVector< STATE_DIM, SCALAR > & state, const SCALAR & startTime, const SCALAR & finalTime, StateVectorArray< STATE_DIM, SCALAR > & stateTrajectory, tpl::TimeArray< SCALAR > & timeTrajectory, const SCALAR dtInitial = SCALAR(0.01))
integrate forward from an initial to a final time using an adaptive scheme
Integrates forward in time from an initial to a final time. If an adaptive stepper is used, the time step is adjusted according to the tolerances set in the constructor. If a fixed step integrator is used, this function will do fixed step integration.
Records state and time evolution. For a recording free version see function below
Warning
Overrides the initial state
Parameters
state initial state, contains the final state after integration
startTime start time of the integration
finalTime the final time of the integration
stateTrajectory state evolution over time
timeTrajectory time trajectory corresponding to state trajectory
dtInitial step size (initial guess, for fixed step integrators it is fixed)
integrate_adaptive() [2/2]
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::integrate_adaptive (StateVector< STATE_DIM, SCALAR > & state, const SCALAR & startTime, const SCALAR & finalTime, SCALAR dtInitial = SCALAR(0.01))
integrate forward from an initial to a final time using an adaptive scheme
Integrates forward in time from an initial to a final time. If an adaptive stepper is used, the time step is adjusted according to the tolerances set in the constructor. If a fixed step integrator is used, this function will do fixed step integration.
Warning
Overrides the initial state
Parameters
state initial state, contains the final state after integration
startTime start time of the integration
finalTime the final time of the integration
dtInitial step size (initial guess, for fixed step integrators it is fixed)
integrate_times()
template<size_t STATE_DIM, typename SCALAR > void ct::core::Integrator< STATE_DIM, SCALAR >::integrate_times (StateVector< STATE_DIM, SCALAR > & state, const tpl::TimeArray< SCALAR > & timeTrajectory, StateVectorArray< STATE_DIM, SCALAR > & stateTrajectory, SCALAR dtInitial = SCALAR(0.01))
Integrate system using a given time trajectory.
Integrates a system using a given time sequence
Warning
Overrides the initial state
Parameters
state initial state, contains the final state after integration
timeTrajectory sequence of time stamps to perform the integration
stateTrajectory the resulting state trajectory corresponding to the times provided
dtInitial an initial guess for a time step (fixed for fixed step integrators)
References ct::core::EULERCT, ct::core::RK4CT, ct::core::DiscreteArray< SCALAR >::swap(), ct::core::DiscreteArray< T, Alloc >::swap(), t, and x.
Member Data Documentation
EventHandlerPtr
template<size_t STATE_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr<EventHandler<STATE_DIM, SCALAR> > ct::core::Integrator< STATE_DIM, SCALAR >::EventHandlerPtr
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/integration/Integrator.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/integration/Integrator-impl.h