googletest-shuffle-test.GTestShuffleUnitTest Class Reference
googletest-shuffle-test.GTestShuffleUnitTest Class Reference
Public Member Functions
def setUp (self)
def testShufflePreservesNumberOfTests (self)
def testShuffleChangesTestOrder (self)
def testShuffleChangesTestCaseOrder (self)
def testShuffleDoesNotRepeatTest (self)
def testShuffleDoesNotCreateNewTest (self)
def testShuffleIncludesAllTests (self)
def testShuffleLeavesDeathTestsAtFront (self)
def testShuffleDoesNotInterleaveTestCases (self)
def testShuffleRestoresOrderAfterEachIteration (self)
def testShuffleGeneratesNewOrderInEachIteration (self)
def testShuffleShardedTestsPreservesPartition (self)
Detailed Description
Tests test shuffling.
Member Function Documentation
def googletest-shuffle-test.GTestShuffleUnitTest.setUp (self)
References googletest-shuffle-test.CalculateTestLists().
def googletest-shuffle-test.GTestShuffleUnitTest.testShufflePreservesNumberOfTests (self)
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleChangesTestOrder (self)
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleChangesTestCaseOrder (self)
References googletest-shuffle-test.GetTestCases().
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleDoesNotRepeatTest (self)
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleDoesNotCreateNewTest (self)
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleIncludesAllTests (self)
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleLeavesDeathTestsAtFront (self)
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleDoesNotInterleaveTestCases (self)
References googletest-shuffle-test.GTestShuffleUnitTest._VerifyTestCasesDoNotInterleave().
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleRestoresOrderAfterEachIteration (self)
References googletest-shuffle-test.GetTestsForAllIterations(), googletest-shuffle-test.RandomSeedFlag(), googletest-shuffle-test.RepeatFlag(), and googletest-shuffle-test.ShuffleFlag().
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration (self)
References googletest-shuffle-test.GetTestsForAllIterations(), googletest-shuffle-test.RandomSeedFlag(), googletest-shuffle-test.RepeatFlag(), and googletest-shuffle-test.ShuffleFlag().
def googletest-shuffle-test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition (self)
References googletest-shuffle-test.GetTestsForAllIterations(), gtest_test_utils.Main(), googletest-shuffle-test.RandomSeedFlag(), and googletest-shuffle-test.ShuffleFlag().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/googletest-shuffle-test.py