testing::internal::TestSuiteNameIs Class Reference
testing::internal::TestSuiteNameIs Class Reference
Public Member Functions
TestSuiteNameIs (const std::string &name)
bool operator() (const TestSuite *test_suite) const
Constructor & Destructor Documentation
testing::internal::TestSuiteNameIs::TestSuiteNameIs (const std::string & name) inline explicit
Member Function Documentation
bool testing::internal::TestSuiteNameIs::operator() (const TestSuite * test_suite) const inline
References testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::internal::g_help_flag, testing::TestResult::GetTestPartResult(), testing::internal::GetTimeInMillis(), GTEST_FLAG, GTEST_INIT_GOOGLE_TEST_NAME_, GTEST_NAME_, testing::Test::HasFatalFailure(), testing::Test::IsSkipped(), testing::TestSuite::name(), testing::TestEventListener::OnEnvironmentsSetUpEnd(), testing::TestEventListener::OnEnvironmentsSetUpStart(), testing::TestEventListener::OnEnvironmentsTearDownEnd(), testing::TestEventListener::OnEnvironmentsTearDownStart(), testing::TestEventListener::OnTestIterationEnd(), testing::TestEventListener::OnTestIterationStart(), testing::TestEventListener::OnTestProgramEnd(), testing::TestEventListener::OnTestProgramStart(), testing::internal::Random::Reseed(), RunAllTests(), testing::Environment::SetUp(), testing::internal::ShouldShard(), testing::Environment::TearDown(), testing::TestEventListeners::TestSuite, testing::TestResult::total_part_count(), and testing::internal::WriteToShardStatusFileIfNeeded().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc