ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat Class Reference
ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat Class Reference
#include <TestDiscreteNonlinearSystemLinearizedFloat.h>
Public Types
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::state_matrix_t state_matrix_t
typedef Base::state_control_matrix_t state_control_matrix_t
Public Types inherited from ct::core::DiscreteLinearSystem< 2, 1, float >
typedef Base::time_t time_t
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef StateMatrix< STATE_DIM, float > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, float > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, float >
typedef DiscreteSystem< STATE_DIM, CONTROL_DIM, float > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::time_t time_t
Public Types inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, float >
typedef int time_t
the type of the time variable
typedef StateVector< STATE_DIM, float > state_vector_t
typedef ControlVector< CONTROL_DIM, float > control_vector_t
Public Member Functions
TestDiscreteNonlinearSystemLinearizedFloat (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
TestDiscreteNonlinearSystemLinearizedFloat (const TestDiscreteNonlinearSystemLinearizedFloat &other)
virtual ~TestDiscreteNonlinearSystemLinearizedFloat ()
virtual TestDiscreteNonlinearSystemLinearizedFloat * clone () const override
deep cloning
void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t numSteps, state_matrix_t &A, state_control_matrix_t &B) override
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const int t=0)
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const int t=0)
Public Member Functions inherited from ct::core::DiscreteLinearSystem< 2, 1, float >
DiscreteLinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~DiscreteLinearSystem ()
destructor
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext) override
compute the system dynamics
virtual void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t subSteps, state_matrix_t &A, state_control_matrix_t &B)=0
retrieve discrete-time linear system matrices A and B.
void getAandB (const state_vector_t &x, const control_vector_t &u, const int n, state_matrix_t &A, state_control_matrix_t &B)
Public Member Functions inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, float >
DiscreteControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
DiscreteControlledSystem (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, float >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
DiscreteControlledSystem (const ControlledSystem< STATE_DIM, CONTROL_DIM, float > &arg)
copy constructor
virtual ~DiscreteControlledSystem ()=default
destructor
void setController (const std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, float >> &controller)
set a new controller
void getController (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, float >> &controller) const
get the controller instance
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, float > > getController ()
get the controller instace
virtual void propagateDynamics (const state_vector_t &state, const time_t n, state_vector_t &stateNext) override
propagates the system dynamics forward by one step
Public Member Functions inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, float >
DiscreteSystem (const SYSTEM_TYPE &type=GENERAL)
constructor
virtual ~DiscreteSystem ()
desctructor
SYSTEM_TYPE getType () const
get the type of system
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::DiscreteLinearSystem< 2, 1, float > Base
Public Attributes inherited from ct::core::DiscreteLinearSystem< 2, 1, float >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, float > Base
Public Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, float >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, float > > Ptr
Additional Inherited Members
Protected Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, float >
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, float > > controller_
the controller instance
Protected Attributes inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, float >
SYSTEM_TYPE type_
type of system
Member Typedef Documentation
typedef Base::state_vector_t ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::state_vector_t
typedef Base::control_vector_t ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::control_vector_t
typedef Base::state_matrix_t ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::state_matrix_t
typedef Base::state_control_matrix_t ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::state_control_matrix_t
Constructor & Destructor Documentation
ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::TestDiscreteNonlinearSystemLinearizedFloat (const ct::core::SYSTEM_TYPE & type = ct::core::SYSTEM_TYPE::GENERAL) inline
Referenced by clone().
ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::TestDiscreteNonlinearSystemLinearizedFloat (const TestDiscreteNonlinearSystemLinearizedFloat & other) inline
virtual ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::~TestDiscreteNonlinearSystemLinearizedFloat () inline virtual
Member Function Documentation
virtual TestDiscreteNonlinearSystemLinearizedFloat* ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::clone () const inline override virtual
deep cloning
Implements ct::core::DiscreteLinearSystem< 2, 1, float >.
References TestDiscreteNonlinearSystemLinearizedFloat().
void ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::getAandB (const state_vector_t & x, const control_vector_t & u, const state_vector_t & x_next, const int n, size_t numSteps, state_matrix_t & A, state_control_matrix_t & B) inline override
References getDerivativeControl(), getDerivativeState(), t, u, and x.
const TestDiscreteNonlinearSystemLinearizedFloat::state_matrix_t & ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const int t = 0) virtual
Referenced by getAandB().
const TestDiscreteNonlinearSystemLinearizedFloat::state_control_matrix_t & ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const int t = 0) virtual
Referenced by getAandB().
Member Data Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::DiscreteLinearSystem<2, 1, float> ct::core::generated::TestDiscreteNonlinearSystemLinearizedFloat::Base
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/generated/TestDiscreteNonlinearSystemLinearizedFloat.h
/home/adrl/code/src/control-toolbox/ct_core/generated/TestDiscreteNonlinearSystemLinearizedFloat_A.cpp
/home/adrl/code/src/control-toolbox/ct_core/generated/TestDiscreteNonlinearSystemLinearizedFloat_B.cpp