testing::gmock_function_mocker_test::FooInterface Class Reference
testing::gmock_function_mocker_test::FooInterface Class Reference abstract
Public Member Functions
virtual ~FooInterface ()
virtual void VoidReturning (int x)=0
virtual int Nullary ()=0
virtual bool Unary (int x)=0
virtual long Binary (short x, int y)=0
virtual int Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char *j, const std::string &k)=0
virtual bool TakesNonConstReference (int &n)=0
virtual std::string TakesConstReference (const int &n)=0
virtual bool TakesConst (const int x)=0
virtual int OverloadedOnArgumentNumber ()=0
virtual int OverloadedOnArgumentNumber (int n)=0
virtual int OverloadedOnArgumentType (int n)=0
virtual char OverloadedOnArgumentType (char c)=0
virtual int OverloadedOnConstness ()=0
virtual char OverloadedOnConstness () const =0
virtual int TypeWithHole (int(*func)())=0
virtual int TypeWithComma (const std::map< int, std::string > &a_map)=0
virtual int TypeWithTemplatedCopyCtor (const TemplatedCopyable< int > &)=0
Constructor & Destructor Documentation
virtual testing::gmock_function_mocker_test::FooInterface::~FooInterface () inline virtual
References testing::gmock_generated_actions_test::Binary(), i, n, testing::gmock_generated_actions_test::Nullary(), testing::gmock_more_actions_test::Unary(), x, and y.
Member Function Documentation
virtual void testing::gmock_function_mocker_test::FooInterface::VoidReturning (int x) pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::Nullary () pure virtual
virtual bool testing::gmock_function_mocker_test::FooInterface::Unary (int x) pure virtual
virtual long testing::gmock_function_mocker_test::FooInterface::Binary (short x, int y) pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::Decimal (bool b, char c, short d, int e, long f, float g, double h, unsigned i, char * j, const std::string & k) pure virtual
virtual bool testing::gmock_function_mocker_test::FooInterface::TakesNonConstReference (int & n) pure virtual
virtual std::string testing::gmock_function_mocker_test::FooInterface::TakesConstReference (const int & n) pure virtual
virtual bool testing::gmock_function_mocker_test::FooInterface::TakesConst (const int x) pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::OverloadedOnArgumentNumber () pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::OverloadedOnArgumentNumber (int n) pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::OverloadedOnArgumentType (int n) pure virtual
virtual char testing::gmock_function_mocker_test::FooInterface::OverloadedOnArgumentType (char c) pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::OverloadedOnConstness () pure virtual
virtual char testing::gmock_function_mocker_test::FooInterface::OverloadedOnConstness () const pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::TypeWithHole (int(*)() func) pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::TypeWithComma (const std::map< int, std::string > & a_map) pure virtual
virtual int testing::gmock_function_mocker_test::FooInterface::TypeWithTemplatedCopyCtor (const TemplatedCopyable< int > &) pure virtual
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/test/gmock-function-mocker_test.cc