ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
Computes the linearization of a general non-linear DiscreteControlledSystem using Automatic Differentiation (without code generation)
#include <DiscreteSystemLinearizerAD.h>
Public Types
typedef CppAD::AD< SCALAR > ADScalar
typedef DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, ADScalar > system_t
type of system to be linearized
typedef DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, ADScalar, int > linearizer_t
type of linearizer to be used
typedef Base::state_vector_t state_vector_t
state vector type
typedef Base::control_vector_t control_vector_t
control vector type
typedef Base::state_matrix_t state_matrix_t
state Jacobian type (A)
typedef Base::state_control_matrix_t state_control_matrix_t
Public Types inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef Base::time_t time_t
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef StateMatrix< STATE_DIM, SCALAR > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, SCALAR > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::time_t time_t
Public Types inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef int time_t
the type of the time variable
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Member Functions
DiscreteSystemLinearizerAD (std::shared_ptr< system_t > nonlinearSystem)
control Jacobian type (B)
DiscreteSystemLinearizerAD (const DiscreteSystemLinearizerAD &arg)
copy constructor
virtual ~DiscreteSystemLinearizerAD ()
destructor
DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override
deep cloning
const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const int t=0)
get the Jacobian with respect to the state
const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const int t=0)
get the Jacobian with respect to the input
void getAandB (const state_vector_t &x, const control_vector_t &u, const state_vector_t &x_next, const int n, size_t numSteps, state_matrix_t &A, state_control_matrix_t &B) override
retrieve discrete-time linear system matrices A and B.
Public Member Functions inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteLinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~DiscreteLinearSystem ()
destructor
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext) override
compute the system dynamics
void getAandB (const state_vector_t &x, const control_vector_t &u, const int n, state_matrix_t &A, state_control_matrix_t &B)
Public Member Functions inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
DiscreteControlledSystem (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
DiscreteControlledSystem (const ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > &arg)
copy constructor
virtual ~DiscreteControlledSystem ()=default
destructor
void setController (const std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void propagateDynamics (const state_vector_t &state, const time_t n, state_vector_t &stateNext) override
propagates the system dynamics forward by one step
Public Member Functions inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteSystem (const SYSTEM_TYPE &type=GENERAL)
constructor
virtual ~DiscreteSystem ()
desctructor
virtual void propagateDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t n, StateVector< STATE_DIM, SCALAR > &stateNext)=0
propagates the system dynamics forward by one step
SYSTEM_TYPE getType () const
get the type of system
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
Public Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
Protected Attributes
state_matrix_t dFdx_
state_control_matrix_t dFdu_
std::shared_ptr< system_t > nonlinearSystem_
instance of non-linear system
linearizer_t linearizer_
instance of ad-linearizer
Protected Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
Protected Attributes inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >
Computes the linearization of a general non-linear DiscreteControlledSystem using Automatic Differentiation (without code generation)
This class takes a non-linear DiscreteControlledSystem and computes the linearization around a certain point , .
where
Note
This is generally the most accurate way to generate the linearization of system dynamics together with DiscreteSystemLinearizerADCG. However, the latter is much faster. Consider using the latter for production code.
Unit test AutoDiffLinearizerTest.cpp illustrates the use of this class.
Warning
You should ensure that your DiscreteControlledSystem is templated on the scalar type and does not contain branching (if/else statements, switch cases etc.)
This function still has some issues with pure time dependency
Todo:
Make time an Auto-Diff parameter
Template Parameters
STATE_DIM dimension of state vector
CONTROL_DIM dimension of control vector
SCALAR primitive type of resultant linear system
Examples:
AutoDiffLinearizerTest.cpp.
Member Typedef Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef CppAD::AD<SCALAR> ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::ADScalar
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DiscreteControlledSystem<STATE_DIM, CONTROL_DIM, ADScalar> ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::system_t
type of system to be linearized
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DynamicsLinearizerAD<STATE_DIM, CONTROL_DIM, ADScalar, int> ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_t
type of linearizer to be used
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_vector_t ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
state vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::control_vector_t ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
control vector type
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_matrix_t ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_matrix_t
state Jacobian type (A)
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_control_matrix_t ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::state_control_matrix_t
Constructor & Destructor Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteSystemLinearizerAD (std::shared_ptr< system_t > nonlinearSystem) inline
control Jacobian type (B)
default constructor
Parameters
nonlinearSystem non-linear system instance to linearize
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::DiscreteSystemLinearizerAD (const DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR > & arg) inline
copy constructor
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::~DiscreteSystemLinearizerAD () inline virtual
destructor
Member Function Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> DiscreteSystemLinearizerAD<STATE_DIM, CONTROL_DIM, SCALAR>* ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const inline override virtual
deep cloning
Implements ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_matrix_t& ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const int t = 0) inline
get the Jacobian with respect to the state
This computes the linearization of the system with respect to the state at a given point , , i.e. it computes
Parameters
x state to linearize at
u control to linearize at
t time
Returns
Jacobian wrt state
References ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_, ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeState(), ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_, and t.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> const state_control_matrix_t& ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const int t = 0) inline
get the Jacobian with respect to the input
This computes the linearization of the system with respect to the input at a given point , , i.e. it computes
Parameters
x state to linearize at
u control to linearize at
t time
Returns
Jacobian wrt input
References ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_, ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeControl(), ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_, and t.
Referenced by TEST().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> void ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB (const state_vector_t & x, const control_vector_t & u, const state_vector_t & x_next, const int n, size_t numSteps, state_matrix_t & A, state_control_matrix_t & B) inline override virtual
retrieve discrete-time linear system matrices A and B.
This computes matrices A and B such that
Note that the inputs x_next and subSteps are being ignored
Parameters
x the state setpoint at n
u the control setpoint at n
n the time setpoint
x_next -> ignored
subSteps -> ignored
A the resulting linear system matrix A
B the resulting linear system matrix B
Implements ct::core::DiscreteLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_, ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_, ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeControl(), ct::core::DynamicsLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR, TIME >::getDerivativeState(), and ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_.
Member Data Documentation
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef DiscreteLinearSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::Base
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> state_matrix_t ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::dFdx_ protected
Referenced by ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), and ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> state_control_matrix_t ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::dFdu_ protected
Referenced by ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), and ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl().
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> std::shared_ptr<system_t> ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::nonlinearSystem_ protected
instance of non-linear system
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> linearizer_t ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::linearizer_ protected
instance of ad-linearizer
Referenced by ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getAandB(), ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), and ct::core::DiscreteSystemLinearizerAD< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/include/ct/core/systems/discrete_time/linear/DiscreteSystemLinearizerAD.h