testing::Test Class Reference
testing::Test Class Reference abstract
#include <gtest.h>
Public Member Functions
virtual ~Test ()
Static Public Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
static void TearDownTestCase ()
static void SetUpTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool IsSkipped ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Protected Member Functions
Test ()
virtual void SetUp ()
virtual void TearDown ()
Friends
class TestInfo
Constructor & Destructor Documentation
Test::~Test () virtual
Test::Test () protected
Referenced by TEST_P().
Member Function Documentation
static void testing::Test::SetUpTestSuite () inline static
static void testing::Test::TearDownTestSuite () inline static
static void testing::Test::TearDownTestCase () inline static
static void testing::Test::SetUpTestCase () inline static
bool Test::HasFatalFailure () static
Referenced by testing::internal::HandleExceptionsInMethodIfSupported(), testing::internal::TestSuiteNameIs::operator()(), testing::internal::ReportInvalidTestSuiteType(), TEST(), and TryTestSubroutine().
bool Test::HasNonfatalFailure () static
Referenced by TEST().
bool Test::IsSkipped () static
Referenced by testing::internal::HandleExceptionsInMethodIfSupported(), testing::internal::TestSuiteNameIs::operator()(), and testing::internal::ReportInvalidTestSuiteType().
static bool testing::Test::HasFailure () inline static
References GTEST_DISALLOW_COPY_AND_ASSIGN_, googletest-break-on-failure-unittest::Run(), and value.
Referenced by TEST().
void Test::RecordProperty (const std::string & key, const std::string & value) static
References testing::UnitTest::GetInstance().
Referenced by ExternalUtilityThatCallsRecordProperty(), main(), RecordProperty(), PropertyOne::SetUp(), PropertyTwo::SetUp(), PropertyTwo::TearDown(), PropertyOne::TearDown(), and TEST_F().
void Test::RecordProperty (const std::string & key, int value) static
References testing::Message::GetString(), RecordProperty(), and value.
void Test::SetUp () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, testing::ParseFlagsTest, testing::SetUpTestSuiteTest, testing::SetUpTestCaseTest, Predicate5Test, Predicate4Test, DynamicFixture, Predicate3Test, TestGenerationTest, Predicate2Test, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, testing::internal::ListenerTest, Predicate1Test, CommonTest< T >, PropertyOne, and PropertyTwo.
Referenced by testing::internal::HandleExceptionsInMethodIfSupported(), ProtectedFixtureMethodsTest::SetUp(), and TEST().
void Test::TearDown () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, Predicate5Test, Predicate4Test, DynamicFixture, Predicate3Test, TestGenerationTest, Predicate2Test, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, testing::internal::ListenerTest, Predicate1Test, CommonTest< T >, PropertyOne, and PropertyTwo.
Referenced by testing::internal::HandleExceptionsInMethodIfSupported(), ProtectedFixtureMethodsTest::TearDown(), TEST(), and testing::TEST_F().
Friends And Related Function Documentation
friend class TestInfo friend
Referenced by testing::internal::MakeAndRegisterTestInfo().
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/include/gtest/gtest.h
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc