ct::core::generated::TestNonlinearSystemLinearized Class Reference
ct::core::generated::TestNonlinearSystemLinearized Class Reference
#include <TestNonlinearSystemLinearized.h>
Public Types
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::state_matrix_t state_matrix_t
typedef Base::state_control_matrix_t state_control_matrix_t
Public Types inherited from ct::core::LinearSystem< 2, 1, double >
typedef Base::time_t time_t
typedef StateVector< STATE_DIM, double > state_vector_t
state vector type
typedef ControlVector< CONTROL_DIM, double > control_vector_t
input vector type
typedef StateMatrix< STATE_DIM, double > state_matrix_t
state Jacobian type
typedef StateControlMatrix< STATE_DIM, CONTROL_DIM, double > state_control_matrix_t
input Jacobian type
Public Types inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
typedef std::shared_ptr< ControlledSystem< STATE_DIM, CONTROL_DIM, double > > Ptr
typedef Base::time_t time_t
Public Types inherited from ct::core::System< STATE_DIM, double >
typedef double time_t
the type of the time variable
Public Member Functions
TestNonlinearSystemLinearized (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
TestNonlinearSystemLinearized (const TestNonlinearSystemLinearized &other)
virtual ~TestNonlinearSystemLinearized ()
virtual TestNonlinearSystemLinearized * clone () const override
deep cloning
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const double t=double(0.0)) override
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const double t=double(0.0)) override
Public Member Functions inherited from ct::core::LinearSystem< 2, 1, double >
LinearSystem (const ct::core::SYSTEM_TYPE &type=ct::core::SYSTEM_TYPE::GENERAL)
default constructor
virtual ~LinearSystem ()
destructor
virtual void computeControlledDynamics (const state_vector_t &state, const time_t &t, const control_vector_t &control, state_vector_t &derivative) override
compute the system dynamics
virtual const state_matrix_t & getDerivativeState (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
get the A matrix of a linear system
virtual const state_control_matrix_t & getDerivativeControl (const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))=0
get the B matrix of a linear system
virtual void getDerivatives (state_matrix_t &A, state_control_matrix_t &B, const state_vector_t &x, const control_vector_t &u, const time_t t=time_t(0.0))
Get both linear system matrices A and B in one call.
Public Member Functions inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
ControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
ControlledSystem (std::shared_ptr< ct::core::Controller< STATE_DIM, CONTROL_DIM, double >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
ControlledSystem (const ControlledSystem &arg)
copy constructor
virtual ~ControlledSystem ()
destructor
void setController (const std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double >> &controller)
set a new controller
void getController (std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double >> &controller) const
get the controller instance
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double > > getController ()
get the controller instace
virtual void computeDynamics (const StateVector< STATE_DIM, double > &state, const time_t &t, StateVector< STATE_DIM, double > &derivative) override
compute the dynamics of the system
ControlVector< CONTROL_DIM, double > getLastControlAction ()
Public Member Functions inherited from ct::core::System< STATE_DIM, double >
System (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
System (const System &other)
copy constructor
virtual ~System ()
destructor
virtual void computeDynamics (const StateVector< STATE_DIM, double > &state, const time_t &t, StateVector< STATE_DIM, double > &derivative)=0
computes the system dynamics
SYSTEM_TYPE getType () const
get the type of system
virtual bool isSymplectic () const
Determines if the system is in symplectic form.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::LinearSystem< 2, 1, double > Base
Public Attributes inherited from ct::core::LinearSystem< 2, 1, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ControlledSystem< STATE_DIM, CONTROL_DIM, double > Base
Public Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef System< STATE_DIM, double > Base
Public Attributes inherited from ct::core::System< STATE_DIM, double >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef double S
the scalar type
Additional Inherited Members
Protected Attributes inherited from ct::core::ControlledSystem< STATE_DIM, CONTROL_DIM, double >
std::shared_ptr< Controller< STATE_DIM, CONTROL_DIM, double > > controller_
the controller instance
ControlVector< CONTROL_DIM, double > controlAction_
Protected Attributes inherited from ct::core::System< STATE_DIM, double >
SYSTEM_TYPE type_
type of system
Member Typedef Documentation
typedef Base::state_vector_t ct::core::generated::TestNonlinearSystemLinearized::state_vector_t
typedef Base::control_vector_t ct::core::generated::TestNonlinearSystemLinearized::control_vector_t
typedef Base::state_matrix_t ct::core::generated::TestNonlinearSystemLinearized::state_matrix_t
typedef Base::state_control_matrix_t ct::core::generated::TestNonlinearSystemLinearized::state_control_matrix_t
Constructor & Destructor Documentation
ct::core::generated::TestNonlinearSystemLinearized::TestNonlinearSystemLinearized (const ct::core::SYSTEM_TYPE & type = ct::core::SYSTEM_TYPE::GENERAL) inline
Referenced by clone().
ct::core::generated::TestNonlinearSystemLinearized::TestNonlinearSystemLinearized (const TestNonlinearSystemLinearized & other) inline
virtual ct::core::generated::TestNonlinearSystemLinearized::~TestNonlinearSystemLinearized () inline virtual
Member Function Documentation
virtual TestNonlinearSystemLinearized* ct::core::generated::TestNonlinearSystemLinearized::clone () const inline override virtual
deep cloning
Implements ct::core::LinearSystem< 2, 1, double >.
References getDerivativeControl(), getDerivativeState(), t, TestNonlinearSystemLinearized(), u, and x.
const TestNonlinearSystemLinearized::state_matrix_t & ct::core::generated::TestNonlinearSystemLinearized::getDerivativeState (const state_vector_t & x, const control_vector_t & u, const double t = double(0.0)) override virtual
Referenced by clone().
const TestNonlinearSystemLinearized::state_control_matrix_t & ct::core::generated::TestNonlinearSystemLinearized::getDerivativeControl (const state_vector_t & x, const control_vector_t & u, const double t = double(0.0)) override virtual
Referenced by clone().
Member Data Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ct::core::LinearSystem<2, 1, double> ct::core::generated::TestNonlinearSystemLinearized::Base
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/generated/TestNonlinearSystemLinearized.h
/home/adrl/code/src/control-toolbox/ct_core/generated/TestNonlinearSystemLinearized.cpp