testing::TestResult Class Reference
testing::TestResult Class Reference
#include <gtest.h>
Public Member Functions
TestResult ()
~TestResult ()
int total_part_count () const
int test_property_count () const
bool Passed () const
bool Skipped () const
bool Failed () const
bool HasFatalFailure () const
bool HasNonfatalFailure () const
TimeInMillis elapsed_time () const
const TestPartResult & GetTestPartResult (int i) const
const TestProperty & GetTestProperty (int i) const
Friends
class TestInfo
class TestSuite
class UnitTest
class internal::DefaultGlobalTestPartResultReporter
class internal::ExecDeathTest
class internal::TestResultAccessor
class internal::UnitTestImpl
class internal::WindowsDeathTest
class internal::FuchsiaDeathTest
Constructor & Destructor Documentation
testing::TestResult::TestResult ()
testing::TestResult::~TestResult ()
Member Function Documentation
int testing::TestResult::total_part_count () const
Referenced by Failed(), testing::internal::FormatEpochTimeInMillisAsIso8601(), GetTestPartResult(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), and testing::internal::TestSuiteNameIs::operator()().
int testing::TestResult::test_property_count () const
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), GetTestProperty(), testing::internal::JsonUnitTestResultPrinter::PrintJsonTestList(), and testing::internal::XmlUnitTestResultPrinter::PrintXmlTestsList().
bool testing::TestResult::Passed () const inline
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd().
bool testing::TestResult::Skipped () const
References Failed().
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
bool testing::TestResult::Failed () const
References GetTestPartResult(), i, and total_part_count().
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), Skipped(), and TEST_F().
bool testing::TestResult::HasFatalFailure () const
bool testing::TestResult::HasNonfatalFailure () const
TimeInMillis testing::TestResult::elapsed_time () const inline
References i.
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), and testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd().
const TestPartResult & testing::TestResult::GetTestPartResult (int i) const
References testing::internal::posix::Abort(), and total_part_count().
Referenced by Failed(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd(), and testing::internal::TestSuiteNameIs::operator()().
const TestProperty & testing::TestResult::GetTestProperty (int i) const
References testing::internal::posix::Abort(), testing::TestProperty::key(), test_property_count(), and testing::TestProperty::value().
Referenced by testing::internal::JsonUnitTestResultPrinter::PrintJsonTestList(), testing::internal::XmlUnitTestResultPrinter::PrintXmlTestsList(), and testing::internal::FinalSuccessChecker::TearDown().
Friends And Related Function Documentation
friend class TestInfo friend
friend class TestSuite friend
friend class UnitTest friend
friend class internal::DefaultGlobalTestPartResultReporter friend
friend class internal::ExecDeathTest friend
friend class internal::TestResultAccessor friend
friend class internal::UnitTestImpl friend
friend class internal::WindowsDeathTest friend
friend class internal::FuchsiaDeathTest friend
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/include/gtest/gtest.h
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc