ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > Class Template Reference
A general, switched non-linear discrete dynamic system with a control input.
#include <SwitchedDiscreteControlledSystem.h>
Public Types
typedef std::shared_ptr< DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > SystemPtr
typedef Switched< SystemPtr > SwitchedSystems
typedef DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::time_t time_t
Public Types inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR > Base
typedef Base::state_vector_t state_vector_t
typedef Base::control_vector_t control_vector_t
typedef Base::time_t time_t
Public Types inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
typedef int time_t
the type of the time variable
typedef StateVector< STATE_DIM, SCALAR > state_vector_t
typedef ControlVector< CONTROL_DIM, SCALAR > control_vector_t
Public Member Functions
SwitchedDiscreteControlledSystem (const SwitchedSystems &switchedSystems, const DiscreteModeSequence &discreteModeSequence, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
SwitchedDiscreteControlledSystem (const SwitchedSystems &switchedSystems, const DiscreteModeSequence &discreteModeSequence, std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
SwitchedDiscreteControlledSystem (const SwitchedDiscreteControlledSystem &arg)
copy constructor
virtual ~SwitchedDiscreteControlledSystem ()
destructor
virtual SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > * clone () const override
deep copy
virtual void propagateControlledDynamics (const state_vector_t &state, const time_t n, const control_vector_t &control, state_vector_t &stateNext) override
propagates the controlled system dynamics forward by one step
Public Member Functions inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteControlledSystem (const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
default constructor
DiscreteControlledSystem (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE &type=SYSTEM_TYPE::GENERAL)
constructor
DiscreteControlledSystem (const ControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > &arg)
copy constructor
virtual ~DiscreteControlledSystem ()=default
destructor
void setController (const std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller)
set a new controller
void getController (std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> &controller) const
get the controller instance
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > getController ()
get the controller instace
virtual void propagateDynamics (const state_vector_t &state, const time_t n, state_vector_t &stateNext) override
propagates the system dynamics forward by one step
Public Member Functions inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
DiscreteSystem (const SYSTEM_TYPE &type=GENERAL)
constructor
virtual ~DiscreteSystem ()
desctructor
virtual void propagateDynamics (const StateVector< STATE_DIM, SCALAR > &state, const time_t n, StateVector< STATE_DIM, SCALAR > &stateNext)=0
propagates the system dynamics forward by one step
SYSTEM_TYPE getType () const
get the type of system
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
Public Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr< DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > > Ptr
Protected Attributes
SwitchedSystems switchedSystems_
switched system container
DiscreteModeSequence discreteModeSequence_
the prespecified mode sequence
Protected Attributes inherited from ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR > > controller_
the controller instance
Protected Attributes inherited from ct::core::DiscreteSystem< STATE_DIM, CONTROL_DIM, SCALAR >
SYSTEM_TYPE type_
type of system
Detailed Description
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double>
class ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >
A general, switched non-linear discrete dynamic system with a control input.
This describes a general, switched non-linear discrete dynamic system of the following form
where is the state, the control input and the time index. refers to the dynamics in a specific mode. Modes are prespecified as a function of time.
For implementing your own SwitchedDiscreteControlledSystem, provide a vector of Discrete systems and a prespecified mode sequence.
We generally assume that the Controller is a state and time index dependent function which allows any ControlledSystem to be re-written as a System of the form
which can be forward propagated directly.
Template Parameters
STATE_DIM dimension of state vector
CONTROL_DIM dimension of input vector
SCALAR scalar type
Member Typedef Documentation
SystemPtr
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef std::shared_ptr<DiscreteControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR> > ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SystemPtr
SwitchedSystems
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Switched<SystemPtr> ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedSystems
Base
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef DiscreteSystem<STATE_DIM, CONTROL_DIM, SCALAR> ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::Base
state_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::state_vector_t ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::state_vector_t
control_vector_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::control_vector_t ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::control_vector_t
time_t
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> typedef Base::time_t ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::time_t
Constructor & Destructor Documentation
SwitchedDiscreteControlledSystem() [1/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedDiscreteControlledSystem (const SwitchedSystems & switchedSystems, const DiscreteModeSequence & discreteModeSequence, const SYSTEM_TYPE & type = SYSTEM_TYPE::GENERAL) inline
default constructor
Parameters
type system type
Referenced by ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::clone().
SwitchedDiscreteControlledSystem() [2/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedDiscreteControlledSystem (const SwitchedSystems & switchedSystems, const DiscreteModeSequence & discreteModeSequence, std::shared_ptr< DiscreteController< STATE_DIM, CONTROL_DIM, SCALAR >> controller, const SYSTEM_TYPE & type = SYSTEM_TYPE::GENERAL) inline
constructor
Parameters
controller controller
type system type
SwitchedDiscreteControlledSystem() [3/3]
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedDiscreteControlledSystem (const SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR > & arg) inline
copy constructor
References ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::switchedSystems_.
~SwitchedDiscreteControlledSystem()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::~SwitchedDiscreteControlledSystem () inline virtual
destructor
Member Function Documentation
clone()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual SwitchedDiscreteControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR>* ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::clone () const inline override virtual
deep copy
Implements ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedDiscreteControlledSystem().
propagateControlledDynamics()
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> virtual void ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::propagateControlledDynamics (const state_vector_t & state, const time_t n, const control_vector_t & control, state_vector_t & stateNext) inline override virtual
propagates the controlled system dynamics forward by one step
evaluates at a given state, control, index, and mode
Parameters
state start state to propagate from
control the control input to apply. This is a constant control input applied to the continuous-time dynamics
n time index to propagate the dynamics at
stateNext the resulting propagated state
Implements ct::core::DiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >.
References ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::discreteModeSequence_, ct::core::PhaseSequence< Phase, Time >::getPhaseFromTime(), and ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::switchedSystems_.
Member Data Documentation
Ptr
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef std::shared_ptr<SwitchedDiscreteControlledSystem<STATE_DIM, CONTROL_DIM, SCALAR> > ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::Ptr
switchedSystems_
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> SwitchedSystems ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::switchedSystems_ protected
switched system container
Referenced by ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::propagateControlledDynamics(), and ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::SwitchedDiscreteControlledSystem().
discreteModeSequence_
template<size_t STATE_DIM, size_t CONTROL_DIM, typename SCALAR = double> DiscreteModeSequence ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::discreteModeSequence_ protected
the prespecified mode sequence
Referenced by ct::core::SwitchedDiscreteControlledSystem< STATE_DIM, CONTROL_DIM, SCALAR >::propagateControlledDynamics().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/systems/discrete_time/SwitchedDiscreteControlledSystem.h