ct::core::generated::TestJacobian Class Reference
ct::core::generated::TestJacobian Class Reference
#include <TestJacobian.h>
Public Types
typedef Eigen::Matrix< double, 3, 1 > X_TYPE
Public Types inherited from ct::core::Derivatives< 3, 2, double >
typedef Eigen::Matrix< double, IN_DIM, 1 > IN_TYPE
function input vector type
typedef Eigen::Matrix< double, OUT_DIM, 1 > OUT_TYPE
function output vector type
typedef Eigen::Matrix< double, OUT_DIM, IN_DIM > JAC_TYPE
typedef Eigen::Matrix< double, IN_DIM, IN_DIM > HES_TYPE
Public Member Functions
TestJacobian ()
TestJacobian (const TestJacobian &other)
virtual ~TestJacobian ()
TestJacobian * clone () const override
deep copy for derived classes
JAC_TYPE jacobian (const Eigen::VectorXd &x_in) override
Evaluates the jacobian with respect to the input.
Public Member Functions inherited from ct::core::Derivatives< 3, 2, double >
Derivatives ()
virtual ~Derivatives ()
default destructor
virtual OUT_TYPE forwardZero (const Eigen::VectorXd &x)
Evaluates the method itself.
virtual void sparseJacobian (const Eigen::VectorXd &x, Eigen::VectorXd &jac, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
Returns the evaluated jacobian in sparse format.
virtual Eigen::VectorXd sparseJacobianValues (const Eigen::VectorXd &x)
Returns the non zero values of the jacobian.
virtual HES_TYPE hessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Evaluates the hessian (2nd order derivatives with respect to input) of the method. In case of a vector valued function, the method returns the weighted sum of the hessians with weights w.
virtual void sparseHessian (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda, Eigen::VectorXd &hes, Eigen::VectorXi &iRow, Eigen::VectorXi &jCol)
Returns the weighted sum of hessian of the problem in sparse format.
virtual Eigen::VectorXd sparseHessianValues (const Eigen::VectorXd &x, const Eigen::VectorXd &lambda)
Returns the non zero elements of the hessian of the problem.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix< double, 2, 3 > JAC_TYPE
Member Typedef Documentation
typedef Eigen::Matrix<double, 3, 1> ct::core::generated::TestJacobian::X_TYPE
Constructor & Destructor Documentation
ct::core::generated::TestJacobian::TestJacobian () inline
Referenced by clone().
ct::core::generated::TestJacobian::TestJacobian (const TestJacobian & other) inline
virtual ct::core::generated::TestJacobian::~TestJacobian () inline virtual
Member Function Documentation
TestJacobian* ct::core::generated::TestJacobian::clone () const inline override virtual
deep copy for derived classes
Implements ct::core::Derivatives< 3, 2, double >.
References jacobian(), and TestJacobian().
TestJacobian::JAC_TYPE TestJacobian::jacobian (const Eigen::VectorXd & x) override virtual
Evaluates the jacobian with respect to the input.
Parameters
[in] x The point of evaluation
Returns
The evaluated jacobian
Reimplemented from ct::core::Derivatives< 3, 2, double >.
Referenced by clone().
Member Data Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix<double, 2, 3> ct::core::generated::TestJacobian::JAC_TYPE
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_core/generated/TestJacobian.h
/home/adrl/code/src/control-toolbox/ct_core/generated/TestJacobian.cpp