testing::internal::JsonUnitTestResultPrinter Class Reference
testing::internal::JsonUnitTestResultPrinter Class Reference
Public Member Functions
JsonUnitTestResultPrinter (const char *output_file)
void OnTestIterationEnd (const UnitTest &unit_test, int iteration) override
Public Member Functions inherited from testing::EmptyTestEventListener
void OnTestProgramStart (const UnitTest &) override
void OnTestIterationStart (const UnitTest &, int) override
void OnEnvironmentsSetUpStart (const UnitTest &) override
void OnEnvironmentsSetUpEnd (const UnitTest &) override
void OnTestSuiteStart (const TestSuite &) override
void OnTestCaseStart (const TestCase &) override
void OnTestStart (const TestInfo &) override
void OnTestPartResult (const TestPartResult &) override
void OnTestEnd (const TestInfo &) override
void OnTestSuiteEnd (const TestSuite &) override
void OnTestCaseEnd (const TestCase &) override
void OnEnvironmentsTearDownStart (const UnitTest &) override
void OnEnvironmentsTearDownEnd (const UnitTest &) override
void OnTestProgramEnd (const UnitTest &) override
Public Member Functions inherited from testing::TestEventListener
virtual ~TestEventListener ()
Static Public Member Functions
static void PrintJsonTestList (::std::ostream *stream, const std::vector< TestSuite * > &test_suites)
Constructor & Destructor Documentation
testing::internal::JsonUnitTestResultPrinter::JsonUnitTestResultPrinter (const char * output_file) explicit
References GTEST_LOG_.
Member Function Documentation
void testing::internal::JsonUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) override virtual
Reimplemented from testing::EmptyTestEventListener.
References testing::TestSuite::ad_hoc_test_result(), testing::UnitTest::ad_hoc_test_result(), ch, testing::TestResult::elapsed_time(), testing::TestSuite::elapsed_time(), testing::UnitTest::elapsed_time(), testing::TestSuite::failed_test_count(), testing::UnitTest::failed_test_count(), FILE, testing::TestInfo::file(), testing::internal::String::FormatByte(), testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::String::FormatIntWidth2(), testing::Message::GetString(), testing::TestSuite::GetTestInfo(), testing::TestResult::GetTestPartResult(), testing::UnitTest::GetTestSuite(), GTEST_CHECK_, GTEST_FLAG, i, testing::TestInfo::is_reportable(), testing::TestInfo::line(), googletest-output-test::message, testing::TestInfo::name(), testing::TestSuite::name(), testing::UnitTest::random_seed(), testing::TestSuite::reportable_disabled_test_count(), testing::UnitTest::reportable_disabled_test_count(), testing::TestSuite::reportable_test_count(), testing::UnitTest::reportable_test_count(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::TestResult::Skipped(), testing::UnitTest::start_timestamp(), testing::internal::StreamableToString(), testing::internal::StringStreamToString(), testing::TestResult::total_part_count(), testing::TestSuite::total_test_count(), testing::UnitTest::total_test_suite_count(), testing::TestInfo::type_param(), and testing::TestInfo::value_param().
void testing::internal::JsonUnitTestResultPrinter::PrintJsonTestList (::std::ostream * stream, const std::vector< TestSuite * > & test_suites) static
References ch, testing::internal::String::FormatByte(), testing::Message::GetString(), testing::TestResult::GetTestProperty(), GTEST_CHECK_, GTEST_FLAG, GTEST_LOCK_EXCLUDED_, GTEST_LOG_, GTEST_NAME_, i, testing::TestResult::test_property_count(), and testing::TestSuite::total_test_count().
Referenced by testing::internal::ShouldRunTestOnShard().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/src/gtest.cc