/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/include/gmock/gmock-matchers.h File Reference
gmock-matchers.h File Reference
#include <math.h>
#include <algorithm>
#include <initializer_list>
#include <iterator>
#include <limits>
#include <memory>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
#include "gmock/internal/gmock-internal-utils.h"
#include "gmock/internal/gmock-port.h"
#include "gtest/gtest.h"
#include "gmock/internal/custom/gmock-matchers.h"
Macros
#define GMOCK_MAYBE_5046_
#define ASSERT_THAT(value, matcher)
#define EXPECT_THAT(value, matcher)
Functions
GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4251 GMOCK_MAYBE_5046_) namespace testing
Macro Definition Documentation
#define GMOCK_MAYBE_5046_
#define ASSERT_THAT (value, matcher)
Value:
ASSERT_PRED_FORMAT1(\
    ::testing::internal::MakePredicateFormatterFromMatcher(matcher), value)
#define EXPECT_THAT (value, matcher)
Value:
EXPECT_PRED_FORMAT1(\
    ::testing::internal::MakePredicateFormatterFromMatcher(matcher), value)
Referenced by testing::gmock_nice_strict_test::MockBaz::MockBaz(), testing::gmock_nice_strict_test::TEST(), and TEST_F().
Function Documentation
GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4251 GMOCK_MAYBE_5046_)
References testing::internal::ArrayAwareFind(), testing::AssertionFailure(), testing::AssertionSuccess(), count, testing::internal::FindMaxBipartiteMatching(), testing::internal::FormatMatcherDescription(), testing::internal::GetRawPointer(), testing::internal::GetTypeName(), GMOCK_KIND_OF_, GTEST_API_, GTEST_CHECK_, GTEST_COMPILE_ASSERT_, GTEST_DISABLE_MSC_WARNINGS_POP_, GTEST_DISALLOW_ASSIGN_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOG_, GTEST_REMOVE_CONST_, GTEST_REMOVE_REFERENCE_, GTEST_REMOVE_REFERENCE_AND_CONST_, GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_, i, testing::Invoke(), testing::internal::IsNull(), gen_gtest_pred_impl::Iter(), testing::internal::kOther, n, p, testing::gtest_printers_test::Print(), testing::PrintToString(), googletest-break-on-failure-unittest::Run(), pump::StartsWith(), testing::StaticAssertTypeEq(), t, upload::type, testing::internal::UniversalPrint(), value, and x.