/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googlemock/include/gmock/gmock-spec-builders.h File Reference
gmock-spec-builders.h File Reference
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
#include "gmock/gmock-actions.h"
#include "gmock/gmock-cardinalities.h"
#include "gmock/gmock-matchers.h"
#include "gmock/internal/gmock-internal-utils.h"
#include "gmock/internal/gmock-port.h"
#include "gtest/gtest.h"
Macros
#define GMOCK_ON_CALL_IMPL_(mock_expr, Setter, call)
#define ON_CALL(obj, call) GMOCK_ON_CALL_IMPL_(obj, InternalDefaultActionSetAt, call)
#define EXPECT_CALL(obj, call) GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
Functions
GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4251) namespace testing
Macro Definition Documentation
#define GMOCK_ON_CALL_IMPL_ (mock_expr, Setter, call)
Value:
((mock_expr).gmock_##call)(::testing::internal::GetWithoutMatchers(), \
                             nullptr)                                   \
      .Setter(__FILE__, __LINE__, #mock_expr, #call)
#define ON_CALL (obj, call) GMOCK_ON_CALL_IMPL_(obj, InternalDefaultActionSetAt, call)
Referenced by testing::gmock_nice_strict_test::MockBaz::MockBaz(), testing::gmock_nice_strict_test::TEST(), TEST(), and TEST_F().
#define EXPECT_CALL (obj, call) GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
Referenced by testing::internal::ExpectationTester::SetCallCount(), testing::gmock_nice_strict_test::TEST(), TEST(), testing::gmock_function_mocker_test::TEST(), testing::gmock_generated_function_mockers_test::TEST(), TEST_F(), testing::gmock_function_mocker_test::TEST_F(), testing::gmock_generated_function_mockers_test::TEST_F(), and TestCatchesLeakedMocksInAdHocTests().
Function Documentation
GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4251)
References upload::action, testing::internal::Assert(), testing::AtLeast(), count, testing::DoDefault(), testing::Exactly(), testing::internal::Expect(), F, testing::internal::FormatFileLocation(), testing::internal::g_gmock_implicit_sequence, GTEST_API_, GTEST_ATTRIBUTE_UNUSED_, GTEST_DECLARE_STATIC_MUTEX_, GTEST_DISABLE_MSC_WARNINGS_POP_, GTEST_DISALLOW_ASSIGN_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_EXCLUSIVE_LOCK_REQUIRED_, GTEST_LOCK_EXCLUDED_, i, testing::Invoke(), testing::internal::kInfo, testing::internal::kWarning, testing::internal::Log(), testing::internal::LogWithLocation(), googletest-output-test::message, n, testing::internal::operator!=(), testing::internal::operator==(), testing::gtest_printers_test::Print(), testing::internal::ReportUninterestingCall(), testing::internal::UniversalPrint(), value, and x.