/home/adrl/code/src/control-toolbox/ct_core/build/test/googletest-src/googletest/test/googletest-list-tests-unittest_.cc File Reference
googletest-list-tests-unittest_.cc File Reference
#include "gtest/gtest.h"
Classes
class FooTest
class MyType
class ValueParamTest
class VeryLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogName
class TypedTest< T >
class MyArray< T, kSize >
class TypeParamTest< T >
Typedefs
typedef testing::Types< VeryLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogName, int *, MyArray< bool, 42 > > MyTypes
Functions
TEST (Foo, Bar1)
TEST (Foo, Bar2)
TEST (Foo, DISABLED_Bar3)
TEST (Abc, Xyz)
TEST (Abc, Def)
TEST (FooBar, Baz)
TEST_F (FooTest, Test1)
TEST_F (FooTest, DISABLED_Test2)
TEST_F (FooTest, Test3)
TEST (FooDeathTest, Test1)
void PrintTo (const MyType &x, std::ostream *os)
TEST_P (ValueParamTest, TestA)
TEST_P (ValueParamTest, TestB)
INSTANTIATE_TEST_SUITE_P (MyInstantiation, ValueParamTest, testing::Values(MyType("one line"), MyType("two\nlines"), MyType("a very\nloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong line")))
TYPED_TEST_SUITE (TypedTest, MyTypes)
TYPED_TEST (TypedTest, TestA)
TYPED_TEST (TypedTest, TestB)
TYPED_TEST_SUITE_P (TypeParamTest)
TYPED_TEST_P (TypeParamTest, TestA)
TYPED_TEST_P (TypeParamTest, TestB)
REGISTER_TYPED_TEST_SUITE_P (TypeParamTest, TestA, TestB)
INSTANTIATE_TYPED_TEST_SUITE_P (My, TypeParamTest, MyTypes)
int main (int argc, char **argv)
Typedef Documentation
typedef testing::Types<VeryLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogName, int*, MyArray<bool, 42> > MyTypes
Function Documentation
TEST (Foo , Bar1)
TEST (Foo , Bar2)
TEST (Foo , DISABLED_Bar3)
TEST (Abc , Xyz)
TEST (Abc , Def)
TEST (FooBar , Baz)
TEST_F (FooTest , Test1)
TEST_F (FooTest , DISABLED_Test2)
TEST_F (FooTest , Test3)
TEST (FooDeathTest , Test1)
void PrintTo (const MyType & x, std::ostream * os)
References MyType::value().
TEST_P (ValueParamTest , TestA)
TEST_P (ValueParamTest , TestB)
References INSTANTIATE_TEST_SUITE_P(), and testing::Values().
INSTANTIATE_TEST_SUITE_P (MyInstantiation , ValueParamTest , testing::Values(MyType("one line"), MyType("two\nlines"), MyType("a very\nloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong line")))
Referenced by TEST_P().
TYPED_TEST_SUITE (TypedTest , MyTypes)
Referenced by TEST_P().
TYPED_TEST (TypedTest , TestA)
Referenced by TEST_P().
TYPED_TEST (TypedTest , TestB)
TYPED_TEST_SUITE_P (TypeParamTest)
Referenced by TEST_P().
TYPED_TEST_P (TypeParamTest , TestA)
Referenced by TEST_P().
TYPED_TEST_P (TypeParamTest , TestB)
References INSTANTIATE_TYPED_TEST_SUITE_P(), and REGISTER_TYPED_TEST_SUITE_P().
REGISTER_TYPED_TEST_SUITE_P (TypeParamTest , TestA , TestB)
Referenced by TEST_P(), and TYPED_TEST_P().
INSTANTIATE_TYPED_TEST_SUITE_P (My , TypeParamTest , MyTypes)
Referenced by TEST_P(), and TYPED_TEST_P().
int main (int argc, char ** argv)
References testing::InitGoogleTest(), and RUN_ALL_TESTS().