/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/test/integration/IntegrationTest.h File Reference
IntegrationTest.h File Reference
#include <gtest/gtest.h>
#include <cmath>
#include <memory>
Functions
double uniformRandomNumber (double min, double max)
void plotResults (std::vector< StateVectorArray< stateSize >> &stateTrajectories, std::vector< TimeArray > &timeTrajectories)
TEST (IntegrationTest, derivativeTest)
Variables
const size_t stateSize = 2
bool plotResult = false
std::vector< std::string > integratorNames = {"euler", "rk4", "rk78", "rk5 variable", "ode45", "modified midpoint"}
std::vector< std::string > integratorCalls = {"const", "nSteps", "adaptive", "times"}
Function Documentation
uniformRandomNumber()
double uniformRandomNumber (double min, double max)
Referenced by TEST().
plotResults()
void plotResults (std::vector< StateVectorArray< stateSize >> & stateTrajectories, std::vector< TimeArray > & timeTrajectories)
References ct::core::plot::figure(), i, integratorCalls, integratorNames, ct::core::plot::ion(), ct::core::plot::plot(), ct::core::plot::show(), ct::core::plot::subplot(), and ct::core::plot::title().
Referenced by TEST().
TEST()
TEST (IntegrationTest , derivativeTest)
References dt, ct::core::EULER, i, ct::core::MODIFIED_MIDPOINT, ct::core::ODE45, plotResult, plotResults(), ct::core::RK4, ct::core::RK5VARIABLE, ct::core::RK78, ct::core::plot::show(), t, uniformRandomNumber(), w_n, and zeta.
Variable Documentation
stateSize
const size_t stateSize = 2
Examples:
SecondOrderSystemTest.cpp.
Referenced by TEST().
plotResult
bool plotResult = false
Examples:
IntegrationTest.cpp.
Referenced by main(), and TEST().
integratorNames
std::vector<std::string> integratorNames = {"euler", "rk4", "rk78", "rk5 variable", "ode45", "modified midpoint"}
Referenced by plotResults().
integratorCalls
std::vector<std::string> integratorCalls = {"const", "nSteps", "adaptive", "times"}
Referenced by plotResults().