ct::core::plot Namespace Reference
ct::core::plot Namespace Reference
Functions
bool ion ()
Enable interactive mode.
bool figure (std::string i="")
Create a new figure.
bool hist (const Eigen::Ref< const Eigen::VectorXd > &x, const double bins=10, const std::string histtype="bar")
Histogram.
bool boxplot (const Eigen::Ref< const Eigen::MatrixXd > &x, const std::vector< std::string > &labels)
Every row of X is the data for a box.
bool boxplot (const Eigen::Ref< const Eigen::MatrixXd > &x, std::initializer_list< const std::string > labels)
bool boxplot (const Eigen::Ref< const Eigen::MatrixXd > &x)
bool subplot (const size_t nrows, const size_t ncols, const size_t plot_number)
Create a subplot.
bool plot (const Eigen::Ref< const Eigen::MatrixXd > &x, const Eigen::Ref< const Eigen::MatrixXd > &y, const std::map< std::string, std::string > &keywords)
Create an x/y plot with properties as map.
bool plot (const Eigen::Ref< const Eigen::MatrixXd > &x, const Eigen::Ref< const Eigen::MatrixXd > &y, const std::string &s="")
Create an x/y plot with properties in string.
bool labelPlot (const std::string &name, const Eigen::Ref< const Eigen::MatrixXd > &x, const Eigen::Ref< const Eigen::MatrixXd > &y, const std::string &format="")
Create an x/y plot with name as label.
bool labelPlot (const std::string &name, const Eigen::Ref< const Eigen::MatrixXd > &y, const std::string &format="")
bool plot (const Eigen::Ref< const Eigen::MatrixXd > &x, const std::string &format="")
void warn ()
std::vector wrappers.
template<typename ALLOC >
bool plot (const std::vector< double, ALLOC > &y, const std::string &format="")
template<typename ALLOC , typename ALLOC2 >
bool plot (const std::vector< double, ALLOC > &x, const std::vector< double, ALLOC2 > &y, const std::map< std::string, std::string > &keywords)
bool plot (const std::vector< double > &x, const Eigen::Ref< const Eigen::MatrixXd > &y, const std::map< std::string, std::string > &keywords)
template<typename ALLOC , typename ALLOC2 >
bool plot (const std::vector< double, ALLOC > &x, const std::vector< double, ALLOC2 > &y, const std::string &s="")
bool plot (const std::vector< double > &x, const Eigen::Ref< const Eigen::MatrixXd > &y, const std::string &s="")
bool labelPlot (const std::string &name, const std::vector< double > &x, const std::vector< double > &y, const std::string &format="")
bool labelPlot (const std::string &name, const std::vector< double > &x, const Eigen::Ref< const Eigen::MatrixXd > &y, const std::string &format="")
Plot settings.
void legend ()
void ylim (double min, double max)
void xlim (double xmin, double xmax)
void title (const std::string &titlestr)
void axis (const std::string &axisstr)
void xlabel (const std::string &str)
void ylabel (const std::string &str)
void grid (bool flag)
void show (bool block=true)
void save (const std::string &filename)
Function Documentation
ion()
bool ct::core::plot::ion ()
Enable interactive mode.
References warn().
Referenced by plotResults().
figure()
bool ct::core::plot::figure (std::string i = "")
Create a new figure.
References warn().
Referenced by main(), and plotResults().
hist()
bool ct::core::plot::hist (const Eigen::Ref< const Eigen::VectorXd > & x, const double bins = 10, const std::string histtype = "bar")
Histogram.
References warn().
Referenced by main().
boxplot() [1/3]
bool ct::core::plot::boxplot (const Eigen::Ref< const Eigen::MatrixXd > & x, const std::vector< std::string > & labels)
Every row of X is the data for a box.
References warn().
Referenced by main().
boxplot() [2/3]
bool ct::core::plot::boxplot (const Eigen::Ref< const Eigen::MatrixXd > & x, std::initializer_list< const std::string > labels)
References warn().
boxplot() [3/3]
bool ct::core::plot::boxplot (const Eigen::Ref< const Eigen::MatrixXd > & x)
References warn().
subplot()
bool ct::core::plot::subplot (const size_t nrows, const size_t ncols, const size_t plot_number)
Create a subplot.
References warn().
Referenced by main(), and plotResults().
plot() [1/8]
bool ct::core::plot::plot (const Eigen::Ref< const Eigen::MatrixXd > & x, const Eigen::Ref< const Eigen::MatrixXd > & y, const std::map< std::string, std::string > & keywords)
Create an x/y plot with properties as map.
References warn().
Referenced by main(), and plotResults().
plot() [2/8]
bool ct::core::plot::plot (const Eigen::Ref< const Eigen::MatrixXd > & x, const Eigen::Ref< const Eigen::MatrixXd > & y, const std::string & s = "")
Create an x/y plot with properties in string.
References warn().
labelPlot() [1/4]
bool ct::core::plot::labelPlot (const std::string & name, const Eigen::Ref< const Eigen::MatrixXd > & x, const Eigen::Ref< const Eigen::MatrixXd > & y, const std::string & format = "")
Create an x/y plot with name as label.
References warn().
Referenced by main().
labelPlot() [2/4]
bool ct::core::plot::labelPlot (const std::string & name, const Eigen::Ref< const Eigen::MatrixXd > & y, const std::string & format = "")
References warn().
plot() [3/8]
bool ct::core::plot::plot (const Eigen::Ref< const Eigen::MatrixXd > & x, const std::string & format = "")
References warn().
plot() [4/8]
template<typename ALLOC > bool ct::core::plot::plot (const std::vector< double, ALLOC > & y, const std::string & format = "")
plot() [5/8]
template<typename ALLOC , typename ALLOC2 > bool ct::core::plot::plot (const std::vector< double, ALLOC > & x, const std::vector< double, ALLOC2 > & y, const std::map< std::string, std::string > & keywords)
plot() [6/8]
bool ct::core::plot::plot (const std::vector< double > & x, const Eigen::Ref< const Eigen::MatrixXd > & y, const std::map< std::string, std::string > & keywords)
References warn().
plot() [7/8]
template<typename ALLOC , typename ALLOC2 > bool ct::core::plot::plot (const std::vector< double, ALLOC > & x, const std::vector< double, ALLOC2 > & y, const std::string & s = "")
plot() [8/8]
bool ct::core::plot::plot (const std::vector< double > & x, const Eigen::Ref< const Eigen::MatrixXd > & y, const std::string & s = "")
References warn().
labelPlot() [3/4]
bool ct::core::plot::labelPlot (const std::string & name, const std::vector< double > & x, const std::vector< double > & y, const std::string & format = "")
References warn().
labelPlot() [4/4]
bool ct::core::plot::labelPlot (const std::string & name, const std::vector< double > & x, const Eigen::Ref< const Eigen::MatrixXd > & y, const std::string & format = "")
References warn().
legend()
void ct::core::plot::legend ()
References warn().
ylim()
void ct::core::plot::ylim (double min, double max)
References warn().
xlim()
void ct::core::plot::xlim (double xmin, double xmax)
References warn().
title()
void ct::core::plot::title (const std::string & titlestr)
References warn().
Referenced by plotResults().
axis()
void ct::core::plot::axis (const std::string & axisstr)
References warn().
xlabel()
void ct::core::plot::xlabel (const std::string & str)
References warn().
ylabel()
void ct::core::plot::ylabel (const std::string & str)
References warn().
grid()
void ct::core::plot::grid (bool flag)
References warn().
show()
void ct::core::plot::show (bool block = true)
References warn().
Referenced by main(), plotResults(), and TEST().
save()
void ct::core::plot::save (const std::string & filename)
References warn().
warn()
void ct::core::plot::warn ()
Referenced by axis(), boxplot(), figure(), grid(), hist(), ion(), labelPlot(), legend(), plot(), plot(), save(), show(), subplot(), title(), xlabel(), xlim(), ylabel(), and ylim().