gmock_output_test Namespace Reference
gmock_output_test Namespace Reference
Classes
class GMockOutputTest
Functions
def ToUnixLineEnding (s)
def RemoveReportHeaderAndFooter (output)
def RemoveLocations (output)
def NormalizeErrorMarker (output)
def RemoveMemoryAddresses (output)
def RemoveTestNamesOfLeakedMocks (output)
def GetLeakyTests (output)
def GetNormalizedOutputAndLeakyTests (output)
def GetShellCommandOutput (cmd)
def GetNormalizedCommandOutputAndLeakyTests (cmd)
Variables
string GENGOLDEN_FLAG = '--gengolden'
PROGRAM_PATH = gmock_test_utils.GetTestExecutablePath('gmock_output_test_')
list COMMAND = [PROGRAM_PATH, '--gtest_stack_trace_depth=0', '--gtest_print_time=0']
string GOLDEN_NAME = 'gmock_output_test_golden.txt'
GOLDEN_PATH = os.path.join(gmock_test_utils.GetSourceDir(), GOLDEN_NAME)
output
golden_file = open(GOLDEN_PATH, 'wb')
Function Documentation
def gmock_output_test.ToUnixLineEnding (s)
Changes all Windows/Mac line endings in s to UNIX line endings.
Referenced by GetNormalizedOutputAndLeakyTests().
def gmock_output_test.RemoveReportHeaderAndFooter (output)
Removes Google Test result report's header and footer from the output.
Referenced by GetNormalizedOutputAndLeakyTests().
def gmock_output_test.RemoveLocations (output)
Removes all file location info from a Google Test program's output.
Args:
     output:  the output of a Google Test program.
Returns:
     output with all file location info (in the form of
     'DIRECTORY/FILE_NAME:LINE_NUMBER: 'or
     'DIRECTORY\\FILE_NAME(LINE_NUMBER): ') replaced by
     'FILE:#: '.
Referenced by GetNormalizedOutputAndLeakyTests().
def gmock_output_test.NormalizeErrorMarker (output)
Normalizes the error marker, which is different on Windows vs on Linux.
Referenced by GetNormalizedOutputAndLeakyTests().
def gmock_output_test.RemoveMemoryAddresses (output)
Removes memory addresses from the test output.
Referenced by GetNormalizedOutputAndLeakyTests().
def gmock_output_test.RemoveTestNamesOfLeakedMocks (output)
Removes the test names of leaked mock objects from the test output.
Referenced by GetNormalizedOutputAndLeakyTests().
def gmock_output_test.GetLeakyTests (output)
Returns a list of test names that leak mock objects.
Referenced by GetNormalizedOutputAndLeakyTests().
def gmock_output_test.GetNormalizedOutputAndLeakyTests (output)
Normalizes the output of gmock_output_test_.
Args:
  output: The test output.
Returns:
  A tuple (the normalized test output, the list of test names that have
  leaked mocks).
References GetLeakyTests(), NormalizeErrorMarker(), RemoveLocations(), RemoveMemoryAddresses(), RemoveReportHeaderAndFooter(), RemoveTestNamesOfLeakedMocks(), and ToUnixLineEnding().
Referenced by GetNormalizedCommandOutputAndLeakyTests().
def gmock_output_test.GetShellCommandOutput (cmd)
Runs a command in a sub-process, and returns its STDOUT in a string.
References gmock_test_utils.Subprocess.
Referenced by GetNormalizedCommandOutputAndLeakyTests().
def gmock_output_test.GetNormalizedCommandOutputAndLeakyTests (cmd)
Runs a command and returns its normalized output and a list of leaky tests.
Args:
  cmd:  the shell command.
References GetNormalizedOutputAndLeakyTests(), and GetShellCommandOutput().
Referenced by gmock_output_test.GMockOutputTest.testOutput().
Variable Documentation
string gmock_output_test.GENGOLDEN_FLAG = '--gengolden'
gmock_output_test.PROGRAM_PATH = gmock_test_utils.GetTestExecutablePath('gmock_output_test_')
list gmock_output_test.COMMAND = [PROGRAM_PATH, '--gtest_stack_trace_depth=0', '--gtest_print_time=0']
Referenced by find_package(), if(), and macro().
string gmock_output_test.GOLDEN_NAME = 'gmock_output_test_golden.txt'
gmock_output_test.GOLDEN_PATH = os.path.join(gmock_test_utils.GetSourceDir(), GOLDEN_NAME)
gmock_output_test.output
Referenced by testing::ParseFlagsTest.CheckFlags(), testing::internal.CopyElements(), testing::internal.GetCurrentExecutableName(), GTEST_DISABLE_MSC_WARNINGS_PUSH_(), testing::internal::XmlUnitTestResultPrinter.ListTestsMatchingFilter(), testing::Flags.Output(), testing::internal.ParseInt32Flag(), testing.PrintFlag(), set(), testing::ParseFlagsTest.SetUp(), ct::core::DerivativesCppadJIT< STATE_DIM+CONTROL_DIM+1, 1 >.sparseHessian(), ct::core::DerivativesCppadJIT< STATE_DIM+CONTROL_DIM+1, 1 >.sparseHessianValues(), ct::core::DerivativesCppadJIT< STATE_DIM+CONTROL_DIM+1, 1 >.sparseJacobian(), ct::core::DerivativesCppadJIT< STATE_DIM+CONTROL_DIM+1, 1 >.sparseJacobianValues(), and TEST().
gmock_output_test.golden_file = open(GOLDEN_PATH, 'wb')