googletest-break-on-failure-unittest Namespace Reference
googletest-break-on-failure-unittest Namespace Reference
Classes
class GTestBreakOnFailureUnitTest
Functions
def Run (command)
Variables
string IS_WINDOWS = 'nt'
string BREAK_ON_FAILURE_ENV_VAR = 'GTEST_BREAK_ON_FAILURE'
string BREAK_ON_FAILURE_FLAG = 'gtest_break_on_failure'
string THROW_ON_FAILURE_ENV_VAR = 'GTEST_THROW_ON_FAILURE'
string CATCH_EXCEPTIONS_ENV_VAR = 'GTEST_CATCH_EXCEPTIONS'
EXE_PATH
environ = gtest_test_utils.environ
SetEnvVar = gtest_test_utils.SetEnvVar
Function Documentation
def googletest-break-on-failure-unittest.Run (command)
Runs a command; returns 1 if it was killed by a signal, or 0 otherwise.
Referenced by testing::internal.CheckedDowncastToActualType(), GTEST_DISABLE_MSC_WARNINGS_PUSH_(), testing::Test.HasFailure(), and googletest-break-on-failure-unittest.GTestBreakOnFailureUnitTest.RunAndVerify().
Variable Documentation
string googletest-break-on-failure-unittest.IS_WINDOWS = 'nt'
string googletest-break-on-failure-unittest.BREAK_ON_FAILURE_ENV_VAR = 'GTEST_BREAK_ON_FAILURE'
string googletest-break-on-failure-unittest.BREAK_ON_FAILURE_FLAG = 'gtest_break_on_failure'
string googletest-break-on-failure-unittest.THROW_ON_FAILURE_ENV_VAR = 'GTEST_THROW_ON_FAILURE'
string googletest-break-on-failure-unittest.CATCH_EXCEPTIONS_ENV_VAR = 'GTEST_CATCH_EXCEPTIONS'
googletest-break-on-failure-unittest.EXE_PATH
Initial value:
 = gtest_test_utils.GetTestExecutablePath(
     'googletest-break-on-failure-unittest_')
googletest-break-on-failure-unittest.environ = gtest_test_utils.environ
googletest-break-on-failure-unittest.SetEnvVar = gtest_test_utils.SetEnvVar
Referenced by googletest-break-on-failure-unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), googletest-break-on-failure-unittest.GTestBreakOnFailureUnitTest.testBreakOnFailureOverridesThrowOnFailure(), and googletest-break-on-failure-unittest.GTestBreakOnFailureUnitTest.testCatchExceptionsDoesNotInterfere().