ct::core::plotQwt Namespace Reference
ct::core::plotQwt Namespace Reference
Namespaces
detail
Classes
class Figure
Typedefs
typedef std::shared_ptr< Figure > FigurePtr
Functions
FigurePtr createFigure ()
void render ()
Typedef Documentation
FigurePtr
typedef std::shared_ptr<Figure> ct::core::plotQwt::FigurePtr
Function Documentation
createFigure()
FigurePtr ct::core::plotQwt::createFigure ()
References ct::core::plotQwt::detail::_application::createFigure(), and ct::core::plotQwt::detail::_interpreter::get().
Referenced by main().
render()
void ct::core::plotQwt::render ()
References ct::core::plotQwt::detail::_application::exec(), and ct::core::plotQwt::detail::_interpreter::get().
Referenced by main().