googletest-output-test Namespace Reference
googletest-output-test Namespace Reference
Classes
class GTestOutputTest
Functions
def ToUnixLineEnding (s)
def RemoveLocations (test_output)
def RemoveStackTraceDetails (output)
def RemoveStackTraces (output)
def RemoveTime (output)
def RemoveTypeInfoDetails (test_output)
def NormalizeToCurrentPlatform (test_output)
def RemoveTestCounts (output)
def RemoveMatchingTests (test_output, pattern)
def NormalizeOutput (output)
def GetShellCommandOutput (env_cmd)
def GetCommandOutput (env_cmd)
def GetOutputOfAllCommands ()
Variables
string GENGOLDEN_FLAG = '--gengolden'
string CATCH_EXCEPTIONS_ENV_VAR_NAME = 'GTEST_CATCH_EXCEPTIONS'
string NO_STACKTRACE_SUPPORT_FLAG = '--no_stacktrace_support'
string IS_LINUX = 'posix'
string IS_WINDOWS = 'nt'
string GOLDEN_NAME = 'googletest-output-test-golden-lin.txt'
PROGRAM_PATH = gtest_test_utils.GetTestExecutablePath('googletest-output-test_')
tuple COMMAND_LIST_TESTS = ({}, [PROGRAM_PATH, '--gtest_list_tests'])
tuple COMMAND_WITH_COLOR = ({}, [PROGRAM_PATH, '--gtest_color=yes'])
tuple COMMAND_WITH_TIME
tuple COMMAND_WITH_DISABLED
tuple COMMAND_WITH_SHARDING
GOLDEN_PATH = os.path.join(gtest_test_utils.GetSourceDir(), GOLDEN_NAME)
test_list = GetShellCommandOutput(COMMAND_LIST_TESTS)
string SUPPORTS_DEATH_TESTS = 'DeathTest'
string SUPPORTS_TYPED_TESTS = 'TypedTest'
string SUPPORTS_THREADS = 'ExpectFailureWithThreadsTest'
SUPPORTS_STACK_TRACES = NO_STACKTRACE_SUPPORT_FLAGnotinsys.argv
tuple CAN_GENERATE_GOLDEN_FILE
output = GetOutputOfAllCommands()
golden_file = open(GOLDEN_PATH, 'wb')
tuple message
Function Documentation
def googletest-output-test.ToUnixLineEnding (s)
Changes all Windows/Mac line endings in s to UNIX line endings.
Referenced by NormalizeOutput(), and googletest-output-test.GTestOutputTest.testOutput().
def googletest-output-test.RemoveLocations (test_output)
Removes all file location info from a Google Test program's output.
Args:
     test_output:  the output of a Google Test program.
Returns:
     output with all file location info (in the form of
     'DIRECTORY/FILE_NAME:LINE_NUMBER: 'or
     'DIRECTORY\\FILE_NAME(LINE_NUMBER): ') replaced by
     'FILE_NAME:#: '.
Referenced by NormalizeOutput().
def googletest-output-test.RemoveStackTraceDetails (output)
Removes all stack traces from a Google Test program's output.
Referenced by NormalizeOutput().
def googletest-output-test.RemoveStackTraces (output)
Removes all traces of stack traces from a Google Test program's output.
Referenced by googletest-output-test.GTestOutputTest.RemoveUnsupportedTests().
def googletest-output-test.RemoveTime (output)
Removes all time information from a Google Test program's output.
Referenced by NormalizeOutput().
def googletest-output-test.RemoveTypeInfoDetails (test_output)
Removes compiler-specific type info from Google Test program's output.
Args:
     test_output:  the output of a Google Test program.
Returns:
     output with type information normalized to canonical form.
Referenced by googletest-output-test.GTestOutputTest.testOutput().
def googletest-output-test.NormalizeToCurrentPlatform (test_output)
Normalizes platform specific output details for easier comparison.
Referenced by googletest-output-test.GTestOutputTest.testOutput().
def googletest-output-test.RemoveTestCounts (output)
Removes test counts from a Google Test program's output.
Referenced by googletest-output-test.GTestOutputTest.testOutput().
def googletest-output-test.RemoveMatchingTests (test_output, pattern)
Removes output of specified tests from a Google Test program's output.
This function strips not only the beginning and the end of a test but also
all output in between.
Args:
  test_output:       A string containing the test output.
  pattern:           A regex string that matches names of test cases or
                     tests to remove.
Returns:
  Contents of test_output with tests whose names match pattern removed.
Referenced by googletest-output-test.GTestOutputTest.RemoveUnsupportedTests().
def googletest-output-test.NormalizeOutput (output)
Normalizes output (the output of googletest-output-test_.exe).
References RemoveLocations(), RemoveStackTraceDetails(), RemoveTime(), and ToUnixLineEnding().
Referenced by GetCommandOutput().
def googletest-output-test.GetShellCommandOutput (env_cmd)
Runs a command in a sub-process, and returns its output in a string.
Args:
  env_cmd: The shell command. A 2-tuple where element 0 is a dict of extra
           environment variables to set, and element 1 is a string with
           the command and any flags.
Returns:
  A string with the command's combined standard and diagnostic output.
Referenced by GetCommandOutput().
def googletest-output-test.GetCommandOutput (env_cmd)
Runs a command and returns its output with all file location
info stripped off.
Args:
  env_cmd:  The shell command. A 2-tuple where element 0 is a dict of extra
            environment variables to set, and element 1 is a string with
            the command and any flags.
References GetShellCommandOutput(), and NormalizeOutput().
Referenced by GetOutputOfAllCommands().
def googletest-output-test.GetOutputOfAllCommands ()
Returns concatenated output from several representative commands.
References GetCommandOutput().
Referenced by googletest-output-test.GTestOutputTest.testOutput().
Variable Documentation
string googletest-output-test.GENGOLDEN_FLAG = '--gengolden'
string googletest-output-test.CATCH_EXCEPTIONS_ENV_VAR_NAME = 'GTEST_CATCH_EXCEPTIONS'
string googletest-output-test.NO_STACKTRACE_SUPPORT_FLAG = '--no_stacktrace_support'
string googletest-output-test.IS_LINUX = 'posix'
string googletest-output-test.IS_WINDOWS = 'nt'
string googletest-output-test.GOLDEN_NAME = 'googletest-output-test-golden-lin.txt'
googletest-output-test.PROGRAM_PATH = gtest_test_utils.GetTestExecutablePath('googletest-output-test_')
tuple googletest-output-test.COMMAND_LIST_TESTS = ({}, [PROGRAM_PATH, '--gtest_list_tests'])
tuple googletest-output-test.COMMAND_WITH_COLOR = ({}, [PROGRAM_PATH, '--gtest_color=yes'])
tuple googletest-output-test.COMMAND_WITH_TIME
Initial value:
 = ({}, [PROGRAM_PATH,
                           '--gtest_print_time',
                           'internal_skip_environment_and_ad_hoc_tests',
                           '--gtest_filter=FatalFailureTest.*:LoggingTest.*'])
tuple googletest-output-test.COMMAND_WITH_DISABLED
Initial value:
 = (
     {}, [PROGRAM_PATH,
          '--gtest_also_run_disabled_tests',
          'internal_skip_environment_and_ad_hoc_tests',
          '--gtest_filter=*DISABLED_*'])
tuple googletest-output-test.COMMAND_WITH_SHARDING
Initial value:
 = (
     {'GTEST_SHARD_INDEX': '1', 'GTEST_TOTAL_SHARDS': '2'},
     [PROGRAM_PATH,
      'internal_skip_environment_and_ad_hoc_tests',
      '--gtest_filter=PassingTest.*'])
googletest-output-test.GOLDEN_PATH = os.path.join(gtest_test_utils.GetSourceDir(), GOLDEN_NAME)
googletest-output-test.test_list = GetShellCommandOutput(COMMAND_LIST_TESTS)
string googletest-output-test.SUPPORTS_DEATH_TESTS = 'DeathTest'
string googletest-output-test.SUPPORTS_TYPED_TESTS = 'TypedTest'
string googletest-output-test.SUPPORTS_THREADS = 'ExpectFailureWithThreadsTest'
googletest-output-test.SUPPORTS_STACK_TRACES = NO_STACKTRACE_SUPPORT_FLAGnotinsys.argv
tuple googletest-output-test.CAN_GENERATE_GOLDEN_FILE
Initial value:
 = (SUPPORTS_DEATH_TESTS and
                             SUPPORTS_TYPED_TESTS and
                             SUPPORTS_THREADS and
                             SUPPORTS_STACK_TRACES)
googletest-output-test.output = GetOutputOfAllCommands()
googletest-output-test.golden_file = open(GOLDEN_PATH, 'wb')
tuple googletest-output-test.message
Initial value:
 = (
           )
Referenced by testing.AssertionFailure(), GTEST_DISABLE_MSC_WARNINGS_PUSH_(), testing::UnitTest.listeners(), testing::internal.Log(), testing::internal::EventRecordingListener.OnTestIterationEnd(), testing::internal::EventRecordingListener2.OnTestIterationEnd(), testing::internal::JsonUnitTestResultPrinter.OnTestIterationEnd(), SequenceTestingListener.OnTestIterationEnd(), testing::internal::EventRecordingListener.OnTestIterationStart(), testing::internal::EventRecordingListener2.OnTestIterationStart(), testing::internal.ReportFailureInUnknownLocation(), testing::ScopedTrace.ScopedTrace(), set(), and TEST().