testing::gmock_function_mocker_test Namespace Reference
testing::gmock_function_mocker_test Namespace Reference
Classes
class FooInterface
class MockB
class MockFoo
class MockMethodFunctionMockerTest
struct MockMethodSizes0
struct MockMethodSizes1
struct MockMethodSizes2
struct MockMethodSizes3
struct MockMethodSizes4
class MockOverloadedOnArgNumber
class MockOverloadedOnConstness
class MockStack
class StackInterface
class TemplatedCopyable
Functions
TEST_F (MockMethodFunctionMockerTest, MocksVoidFunction)
TEST_F (MockMethodFunctionMockerTest, MocksNullaryFunction)
TEST_F (MockMethodFunctionMockerTest, MocksUnaryFunction)
TEST_F (MockMethodFunctionMockerTest, MocksBinaryFunction)
TEST_F (MockMethodFunctionMockerTest, MocksDecimalFunction)
TEST_F (MockMethodFunctionMockerTest, MocksFunctionWithNonConstReferenceArgument)
TEST_F (MockMethodFunctionMockerTest, MocksFunctionWithConstReferenceArgument)
TEST_F (MockMethodFunctionMockerTest, MocksFunctionWithConstArgument)
TEST_F (MockMethodFunctionMockerTest, MocksFunctionsOverloadedOnArgumentNumber)
TEST_F (MockMethodFunctionMockerTest, MocksFunctionsOverloadedOnArgumentType)
TEST_F (MockMethodFunctionMockerTest, MocksFunctionsOverloadedOnConstnessOfThis)
TEST_F (MockMethodFunctionMockerTest, MocksReturnTypeWithComma)
TEST_F (MockMethodFunctionMockerTest, MocksTypeWithTemplatedCopyCtor)
TEST (MockMethodExpectCallTest, UnmentionedFunctionCanBeCalledAnyNumberOfTimes)
TEST (MockMethodTemplateMockTest, Works)
TEST (MockMethodTemplateMockTest, MethodWithCommaInReturnTypeWorks)
TEST (MockMethodOverloadedMockMethodTest, CanOverloadOnArgNumberInMacroBody)
TEST (MockMethodOverloadedMockMethodTest, CanOverloadOnConstnessInMacroBody)
TEST (MockMethodMockFunctionTest, WorksForVoidNullary)
TEST (MockMethodMockFunctionTest, WorksForNonVoidNullary)
TEST (MockMethodMockFunctionTest, WorksForVoidUnary)
TEST (MockMethodMockFunctionTest, WorksForNonVoidBinary)
TEST (MockMethodMockFunctionTest, WorksFor10Arguments)
TEST (MockMethodMockFunctionTest, AsStdFunction)
TEST (MockMethodMockFunctionTest, AsStdFunctionReturnsReference)
TEST (MockMethodMockFunctionTest, AsStdFunctionWithReferenceParameter)
TEST (MockMethodMockFunctionTest, MockMethodSizeOverhead)
Function Documentation
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksVoidFunction)
References EXPECT_CALL.
Referenced by TEST_F().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksNullaryFunction)
References testing::DoDefault(), EXPECT_CALL, EXPECT_EQ, testing::gmock_generated_actions_test::Nullary(), and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksUnaryFunction)
References EXPECT_CALL, EXPECT_FALSE, EXPECT_TRUE, testing::Return(), and testing::gmock_more_actions_test::Unary().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksBinaryFunction)
References testing::gmock_generated_actions_test::Binary(), EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksDecimalFunction)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksFunctionWithNonConstReferenceArgument)
References EXPECT_CALL, EXPECT_TRUE, and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksFunctionWithConstReferenceArgument)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksFunctionWithConstArgument)
References testing::DoDefault(), EXPECT_CALL, and EXPECT_FALSE.
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksFunctionsOverloadedOnArgumentNumber)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksFunctionsOverloadedOnArgumentType)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksFunctionsOverloadedOnConstnessOfThis)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksReturnTypeWithComma)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST_F (MockMethodFunctionMockerTest , MocksTypeWithTemplatedCopyCtor)
References EXPECT_CALL, EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::Return(), and TEST_F().
testing::gmock_function_mocker_test::TEST (MockMethodExpectCallTest , UnmentionedFunctionCanBeCalledAnyNumberOfTimes)
Referenced by TEST().
testing::gmock_function_mocker_test::TEST (MockMethodTemplateMockTest , Works)
References testing::AnyNumber(), EXPECT_CALL, EXPECT_EQ, testing::gmock_function_mocker_test::StackInterface< T >::GetSize(), testing::gmock_function_mocker_test::StackInterface< T >::GetTop(), n, testing::gmock_function_mocker_test::StackInterface< T >::Pop(), testing::gmock_function_mocker_test::StackInterface< T >::Push(), testing::Return(), and testing::ReturnRef().
testing::gmock_function_mocker_test::TEST (MockMethodTemplateMockTest , MethodWithCommaInReturnTypeWorks)
References testing::AnyNumber(), EXPECT_CALL, EXPECT_EQ, GTEST_DISALLOW_COPY_AND_ASSIGN_, MOCK_METHOD, n, testing::Return(), testing::ReturnRef(), TEST(), and value.
testing::gmock_function_mocker_test::TEST (MockMethodOverloadedMockMethodTest , CanOverloadOnArgNumberInMacroBody)
References EXPECT_CALL, EXPECT_EQ, EXPECT_TRUE, and testing::Return().
testing::gmock_function_mocker_test::TEST (MockMethodOverloadedMockMethodTest , CanOverloadOnConstnessInMacroBody)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , WorksForVoidNullary)
References EXPECT_CALL.
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , WorksForNonVoidNullary)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , WorksForVoidUnary)
References EXPECT_CALL.
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , WorksForNonVoidBinary)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , WorksFor10Arguments)
References EXPECT_CALL, EXPECT_EQ, and testing::Return().
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , AsStdFunction)
References EXPECT_CALL, EXPECT_EQ, i, and testing::Return().
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , AsStdFunctionReturnsReference)
References EXPECT_CALL, EXPECT_EQ, testing::ReturnRef(), and value.
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , AsStdFunctionWithReferenceParameter)
References EXPECT_CALL, EXPECT_EQ, i, and testing::Return().
testing::gmock_function_mocker_test::TEST (MockMethodMockFunctionTest , MockMethodSizeOverhead)
References EXPECT_EQ.