googletest-color-test Namespace Reference
googletest-color-test Namespace Reference
Classes
class GTestColorTest
Functions
def SetEnvVar (env_var, value)
def UsesColor (term, color_env_var, color_flag)
Variables
string IS_WINDOWS = 'nt'
string COLOR_ENV_VAR = 'GTEST_COLOR'
string COLOR_FLAG = 'gtest_color'
COMMAND = gtest_test_utils.GetTestExecutablePath('googletest-color-test_')
Function Documentation
def googletest-color-test.SetEnvVar (env_var, value)
Sets the env variable to 'value'; unsets it when 'value' is None.
Referenced by UsesColor().
def googletest-color-test.UsesColor (term, color_env_var, color_flag)
Runs googletest-color-test_ and returns its exit code.
References SetEnvVar().
Referenced by googletest-color-test.GTestColorTest.testAliasesOfYesAndNo(), googletest-color-test.GTestColorTest.testEnvVarAndFlag(), googletest-color-test.GTestColorTest.testEnvVarOnly(), googletest-color-test.GTestColorTest.testFlagOnly(), and googletest-color-test.GTestColorTest.testNoEnvVarNoFlag().
Variable Documentation
string googletest-color-test.IS_WINDOWS = 'nt'
string googletest-color-test.COLOR_ENV_VAR = 'GTEST_COLOR'
string googletest-color-test.COLOR_FLAG = 'gtest_color'
googletest-color-test.COMMAND = gtest_test_utils.GetTestExecutablePath('googletest-color-test_')