/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/include/ct/core/plot/plot-impl.h File Reference
plot-impl.h File Reference
Functions
template<typename ALLOC >
bool plot (const std::vector< double, ALLOC > &y, const std::string &format)
template<typename ALLOC , typename ALLOC2 >
bool plot (const std::vector< double, ALLOC > &x, const std::vector< double, ALLOC2 > &y, const std::map< std::string, std::string > &keywords)
template<typename ALLOC , typename ALLOC2 >
bool plot (const std::vector< double, ALLOC > &x, const std::vector< double, ALLOC2 > &y, const std::string &s)
Function Documentation
plot() [1/3]
template<typename ALLOC > bool plot (const std::vector< double, ALLOC > & y, const std::string & format)
References ct::core::plot::warn().
plot() [2/3]
template<typename ALLOC , typename ALLOC2 > bool plot (const std::vector< double, ALLOC > & x, const std::vector< double, ALLOC2 > & y, const std::map< std::string, std::string > & keywords)
References ct::core::plot::warn().
plot() [3/3]
template<typename ALLOC , typename ALLOC2 > bool plot (const std::vector< double, ALLOC > & x, const std::vector< double, ALLOC2 > & y, const std::string & s)
References ct::core::plot::warn().