/home/adrl/code/src/control-toolbox/ct_core/test/switching/SwitchedControlledSystemTest.cpp File Reference
SwitchedControlledSystemTest.cpp File Reference
#include <ct/core/core.h>
#include "../system/TestNonlinearSystem.h"
#include <gtest/gtest.h>
Functions
TEST (SwitchedControlledSystemTest, SwitchedControlledSystem)
int main (int argc, char **argv)
Function Documentation
TEST (SwitchedControlledSystemTest , SwitchedControlledSystem)
References ct::core::PhaseSequence< Phase, Time >::addPhase(), ASSERT_EQ, ASSERT_TRUE, dt, ct::core::EULER, ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), ct::core::PhaseSequence< Phase, Time >::getStartTimeFromIdx(), ct::core::PhaseSequence< Phase, Time >::getTotalDuration(), ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::core::SwitchedLinearSystem< STATE_DIM, CONTROL_DIM, SCALAR >::LinearSystemPtr, t, u, and x.
int main (int argc, char ** argv)
SwitchingControlledSystemTest.cpp
Test basic functionality of switching continuous controlled systems
References testing::InitGoogleTest(), and RUN_ALL_TESTS().