/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/test/switching/SwitchingTest.cpp File Reference
SwitchingTest.cpp File Reference
#include <ct/core/core.h>
#include <gtest/gtest.h>
Functions
TEST (SwitchingTest, ContinuousModeSequence)
TEST (SwitchingTest, SwitchedSystem)
int main (int argc, char **argv)
Function Documentation
TEST() [1/2]
TEST (SwitchingTest , ContinuousModeSequence)
References ct::core::PhaseSequence< Phase, Time >::addPhase(), ct::core::PhaseSequence< Phase, Time >::getEndTimeFromIdx(), ct::core::PhaseSequence< Phase, Time >::getIdxFromTime(), ct::core::PhaseSequence< Phase, Time >::getNumPhases(), ct::core::PhaseSequence< Phase, Time >::getNumSwitches(), ct::core::PhaseSequence< Phase, Time >::getPhaseFromIdx(), ct::core::PhaseSequence< Phase, Time >::getStartTimeFromIdx(), ct::core::PhaseSequence< Phase, Time >::getSwitchEventFromIdx(), and ct::core::PhaseSequence< Phase, Time >::getTotalDuration().
TEST() [2/2]
TEST (SwitchingTest , SwitchedSystem)
References ct::core::PhaseSequence< Phase, Time >::addPhase(), ct::core::PhaseSequence< Phase, Time >::getPhaseFromTime(), ct::core::PhaseSequence< Phase, Time >::getTotalDuration(), and t.
main()
int main (int argc, char ** argv)
SwitchingTest.cpp
Test basic functionality of switching logic