/home/adrl/code/src/control-toolbox/ct_core/test/integration/SymplecticIntegrationTest.cpp File Reference
SymplecticIntegrationTest.cpp File Reference
#include <gtest/gtest.h>
#include <ct/core/core.h>
#include "../system/TestSymplecticSystem.h"
Functions
double uniformRandomNumber (double min, double max)
TEST (SymplecticIntegrationTest, simpleSymplecticTest)
int main (int argc, char **argv)
Variables
const size_t state_dim = 2
const size_t p_dim = 1
const size_t v_dim = 1
const size_t control_dim = 1
Function Documentation
double uniformRandomNumber (double min, double max)
Referenced by TEST().
TEST (SymplecticIntegrationTest , simpleSymplecticTest)
References ASSERT_NEAR, dt, FAIL, i, and uniformRandomNumber().
int main (int argc, char ** argv)
References testing::InitGoogleTest(), and RUN_ALL_TESTS().
Variable Documentation
const size_t state_dim = 2
Examples:
AutoDiffLinearizerTest.cpp, DampedOscillator.cpp, DampedOscillatorCustomController.cpp, and MasspointIntegration.cpp.
Referenced by main(), and TEST().
const size_t p_dim = 1
const size_t v_dim = 1
const size_t control_dim = 1
Examples:
AutoDiffLinearizerTest.cpp, and DampedOscillatorCustomController.cpp.
Referenced by main(), and TEST().