/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_core/test/integration/SystemDiscretizerTest.h File Reference
SystemDiscretizerTest.h File Reference
#include <gtest/gtest.h>
Functions
double uniformRandomNumber (double min, double max)
TEST (SystemDiscretizerTest, IntegratorComparison)
Function Documentation
uniformRandomNumber()
double uniformRandomNumber (double min, double max)
Referenced by TEST().
TEST()
TEST (SystemDiscretizerTest , IntegratorComparison)
References control_dim, dt, ct::core::EULER, i, ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::core::SystemDiscretizer< STATE_DIM, CONTROL_DIM, P_DIM, V_DIM, SCALAR >::propagateControlledDynamics(), ct::core::RK4, state_dim, uniformRandomNumber(), w_n, and zeta.