ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR > Class Template Reference
ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR > Class Template Reference final
Inverse Kinematics cost evaluator for NLP.
#include <IKCostEvaluator.h>
Public Member Functions
IKCostEvaluator (size_t eeInd, const Eigen::Matrix3d &Qpos=Eigen::Matrix3d::Identity(), const double &Qrot=1.0)
IKCostEvaluator (const std::string &costFunctionPath, const std::string &termTaskspaceName, const bool verbose=false)
IKCostEvaluator (const std::string &costFunctionPath, const std::string &termTaskspaceName, const std::string &termJointPosName, const bool verbose=false)
~IKCostEvaluator () override=default
void setOptVector (std::shared_ptr< ct::optcon::tpl::OptVector< SCALAR >> optVector)
opt vector needs to be set by NLP solver
void setRegularizer (std::shared_ptr< IKRegularizerBase > reg)
ct::rbd::RigidBodyPose getTargetPose ()
void setTargetPose (const ct::rbd::RigidBodyPose &rbdPose)
void setTargetPose (const core::StateVector< 3 > &w_pos_des, const Eigen::Quaterniond &w_q_des)
void setTargetPose (const core::StateVector< 3 > &w_pos_des, const Eigen::Matrix3d &eulerXyz)
virtual SCALAR eval () override
evaluate cost function
virtual void evalGradient (size_t grad_length, Eigen::Map< Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 >> &grad) override
retrieve first-order derivative
virtual void getSparsityPatternHessian (Eigen::VectorXi &iRow, Eigen::VectorXi &jCol) override
create sparsity pattern for the hessian (simply fill up completely)
void sparseHessianValues (const Eigen::VectorXd &jointAngles, const Eigen::VectorXd &obj_fac, Eigen::VectorXd &hes) override
retrieve second order derivative
Public Member Functions inherited from ct::optcon::tpl::DiscreteCostEvaluatorBase< SCALAR >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW DiscreteCostEvaluatorBase ()=default
virtual ~DiscreteCostEvaluatorBase ()=default
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t NJOINTS = KINEMATICS_AD::NJOINTS
Detailed Description
template<typename KINEMATICS_AD, typename SCALAR = double>
class ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >
Inverse Kinematics cost evaluator for NLP.
Warning
currently this works only with fix-base systems
Constructor & Destructor Documentation
template<typename KINEMATICS_AD , typename SCALAR = double> ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::IKCostEvaluator (size_t eeInd, const Eigen::Matrix3d & Qpos = Eigen::Matrix3d::Identity(), const double & Qrot = 1.0) inline
template<typename KINEMATICS_AD , typename SCALAR = double> ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::IKCostEvaluator (const std::string & costFunctionPath, const std::string & termTaskspaceName, const bool verbose = false) inline
template<typename KINEMATICS_AD , typename SCALAR = double> ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::IKCostEvaluator (const std::string & costFunctionPath, const std::string & termTaskspaceName, const std::string & termJointPosName, const bool verbose = false) inline
References ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::~IKCostEvaluator().
template<typename KINEMATICS_AD , typename SCALAR = double> ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::~IKCostEvaluator () override default
Referenced by ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::IKCostEvaluator().
Member Function Documentation
template<typename KINEMATICS_AD , typename SCALAR = double> void ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::setOptVector (std::shared_ptr< ct::optcon::tpl::OptVector< SCALAR >> optVector) inline
opt vector needs to be set by NLP solver
template<typename KINEMATICS_AD , typename SCALAR = double> void ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::setRegularizer (std::shared_ptr< IKRegularizerBase > reg) inline
template<typename KINEMATICS_AD , typename SCALAR = double> ct::rbd::RigidBodyPose ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::getTargetPose () inline
template<typename KINEMATICS_AD , typename SCALAR = double> void ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::setTargetPose (const ct::rbd::RigidBodyPose & rbdPose) inline
References ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationQuaternion(), and ct::rbd::tpl::RigidBodyPose< SCALAR >::position().
template<typename KINEMATICS_AD , typename SCALAR = double> void ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::setTargetPose (const core::StateVector< 3 > & w_pos_des, const Eigen::Quaterniond & w_q_des) inline
template<typename KINEMATICS_AD , typename SCALAR = double> void ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::setTargetPose (const core::StateVector< 3 > & w_pos_des, const Eigen::Matrix3d & eulerXyz) inline
template<typename KINEMATICS_AD , typename SCALAR = double> virtual SCALAR ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::eval () inline override virtual
evaluate cost function
Implements ct::optcon::tpl::DiscreteCostEvaluatorBase< SCALAR >.
template<typename KINEMATICS_AD , typename SCALAR = double> virtual void ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::evalGradient (size_t grad_length, Eigen::Map< Eigen::Matrix< SCALAR, Eigen::Dynamic, 1 >> & grad) inline override virtual
retrieve first-order derivative
Implements ct::optcon::tpl::DiscreteCostEvaluatorBase< SCALAR >.
template<typename KINEMATICS_AD , typename SCALAR = double> virtual void ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::getSparsityPatternHessian (Eigen::VectorXi & iRow, Eigen::VectorXi & jCol) inline override virtual
create sparsity pattern for the hessian (simply fill up completely)
Reimplemented from ct::optcon::tpl::DiscreteCostEvaluatorBase< SCALAR >.
References i, and ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::NJOINTS.
template<typename KINEMATICS_AD , typename SCALAR = double> void ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::sparseHessianValues (const Eigen::VectorXd & jointAngles, const Eigen::VectorXd & obj_fac, Eigen::VectorXd & hes) inline override virtual
retrieve second order derivative
Reimplemented from ct::optcon::tpl::DiscreteCostEvaluatorBase< SCALAR >.
References ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::NJOINTS.
Member Data Documentation
template<typename KINEMATICS_AD , typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::NJOINTS = KINEMATICS_AD::NJOINTS static
Referenced by ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::getSparsityPatternHessian(), and ct::rbd::IKCostEvaluator< KINEMATICS_AD, SCALAR >::sparseHessianValues().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/robot/kinematics/ik_nlp/IKCostEvaluator.h