ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM > Class Template Reference
ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM > Class Template Reference
A costfunction term that defines a cost on a task-space pose, uses code-generation internally and allows to have end-effector position and orientation as parameters in auto-diff.
#include <TermTaskspacePoseCG.hpp>
Public Types
using BASE = optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >
using DerivativesCppadJIT = core::DerivativesCppadJIT< AD_PARAMETER_DIM, 1 >
using CGScalar = typename DerivativesCppadJIT::CG_SCALAR
using RBDStateTpl = ct::rbd::RBDState< KINEMATICS::NJOINTS, CGScalar >
using state_matrix_t = Eigen::Matrix< double, STATE_DIM, STATE_DIM >
using control_matrix_t = Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM >
using control_state_matrix_t = Eigen::Matrix< double, CONTROL_DIM, STATE_DIM >
Public Types inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >
typedef Eigen::Matrix< double, STATE_DIM, STATE_DIM > state_matrix_t
typedef Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< double, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef Eigen::Matrix< double, STATE_DIM, STATE_DIM > state_matrix_double_t
typedef Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM > control_matrix_double_t
typedef Eigen::Matrix< double, CONTROL_DIM, STATE_DIM > control_state_matrix_double_t
Public Member Functions
TermTaskspacePoseCG ()=default
default constructor
TermTaskspacePoseCG (size_t eeInd, const Eigen::Matrix3d &Qpos, const double &Qrot, const core::StateVector< 3 > &w_pos_des, const Eigen::Quaterniond &w_q_des, const std::string &name="TermTaskSpace", bool evalControlDerivatives=true)
constructor using a quaternion for orientation
TermTaskspacePoseCG (size_t eeInd, const Eigen::Matrix3d &Qpos, const double &Qrot, const ct::rbd::RigidBodyPose &rbdPose, const std::string &name="TermTaskSpace", bool evalControlDerivatives=true)
constructor taking a full RigidBodyPose
TermTaskspacePoseCG (size_t eeInd, const Eigen::Matrix3d &Qpos, const double &Qrot, const core::StateVector< 3 > &w_pos_des, const Eigen::Matrix3d &eulerXyz, const std::string &name="TermTaskSpace", bool evalControlDerivatives=true)
constructor using Euler angles for orientation
TermTaskspacePoseCG (size_t eeInd, const Eigen::Matrix3d &Qpos, const double &Qrot, const std::string &name="TermTaskSpace", bool evalControlDerivatives=false)
constructor which sets the target pose to dummy values
TermTaskspacePoseCG (const std::string &configFile, const std::string &termName, bool verbose=false)
construct this term with info loaded from a configuration file
TermTaskspacePoseCG (const TermTaskspacePoseCG &arg)
copy constructor
virtual ~TermTaskspacePoseCG ()
destructor
virtual TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM > * clone () const override
deep cloning
void setup ()
setup the AD Derivatives
void setCurrentStateAndControl (const Eigen::Matrix< double, STATE_DIM, 1 > &x, const Eigen::Matrix< double, CONTROL_DIM, 1 > &u, const double &t)
virtual double evaluate (const Eigen::Matrix< double, STATE_DIM, 1 > &x, const Eigen::Matrix< double, CONTROL_DIM, 1 > &u, const double &t) override
evaluate
virtual core::StateVector< STATE_DIM > stateDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute derivative of this cost term w.r.t. the state
virtual core::ControlVector< CONTROL_DIM > controlDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute derivative of this cost term w.r.t. the control input
virtual state_matrix_t stateSecondDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute second order derivative of this cost term w.r.t. the state
virtual control_matrix_t controlSecondDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute second order derivative of this cost term w.r.t. the control input
virtual control_state_matrix_t stateControlDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute the cross-term derivative (state-control) of this cost function term
void loadConfigFile (const std::string &filename, const std::string &termName, bool verbose=false) override
load term information from configuration file (stores data in member variables)
const Eigen::Matrix< double, 3, 1 > getReferencePosition () const
retrieve reference position in world frame
void setReferencePosition (Eigen::Matrix< double, 3, 1 > w_p_ref)
set the end-effector reference position
const Eigen::Quaterniond getReferenceOrientation () const
retrieve reference ee orientation in world frame
void setReferenceOrientation (const Eigen::Matrix< double, 3, 3 > &w_R_ref)
set desired end-effector orientation in world frame
void setReferenceOrientation (const Eigen::Quaterniond &w_q_des)
set desired end-effector orientation in world frame
const ct::rbd::RigidBodyPose getReferencePose () const
return the reference pose as RigidBodyPose
Public Member Functions inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >
TermBase (std::string name="Unnamed")
TermBase (const TermBase &arg)
virtual ~TermBase ()
virtual ct::core::ADCGScalar evaluateCppadCg (const core::StateVector< STATE_DIM, ct::core::ADCGScalar > &x, const core::ControlVector< CONTROL_DIM, ct::core::ADCGScalar > &u, ct::core::ADCGScalar t)
double eval (const Eigen::Matrix< double, STATE_DIM, 1 > &x, const Eigen::Matrix< double, CONTROL_DIM, 1 > &u, const double &t)
virtual bool isActiveAtTime (doublet)
double computeActivation (doublet)
virtual core::StateVector< STATE_DIM, double > stateDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual state_matrix_t stateSecondDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual core::ControlVector< CONTROL_DIM, double > controlDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual control_matrix_t controlSecondDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual control_state_matrix_t stateControlDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
void setTimeActivation (std::shared_ptr< ct::core::tpl::ActivationBase< double >> c_i, bool verbose=false)
void loadTimeActivation (const std::string &filename, const std::string &termName, bool verbose=false)
const std::string & getName () const
void setName (const std::string &termName)
virtual void updateReferenceState (const Eigen::Matrix< double, STATE_DIM, 1 > &newRefState)
virtual void updateReferenceControl (const Eigen::Matrix< double, CONTROL_DIM, 1 > &newRefControl)
virtual Eigen::Matrix< double, STATE_DIM, 1 > getReferenceState () const
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t AD_PARAMETER_DIM = STATE_DIM + CONTROL_DIM + 3 + 9 + 1
Protected Member Functions
virtual RBDStateTpl setStateFromVector (const Eigen::Matrix< CGScalar, STATE_DIM, 1 > &x)
Additional Inherited Members
Protected Attributes inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >
std::string name_
std::shared_ptr< ct::core::tpl::ActivationBase< double > > c_i_
Detailed Description
template<class KINEMATICS, bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM>
class ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >
A costfunction term that defines a cost on a task-space pose, uses code-generation internally and allows to have end-effector position and orientation as parameters in auto-diff.
This term is desigend as term for "ct::optcon::CostFunctionAnalytic", but uses AD internally.
Warning
this term implements a flag which allows to rid of the evaluation of the control-derivatives (they are zero) and just set them to zero. The reason for this flag is that it is the only way to avoid multiple evaluations of the Jacobians and Hessians. If the jacobians and hessians were member variables, the overhead of evaluating them multiple times could be avoided. NOTE: setting this flag is not a good idea for purely kinematic systems!
Template Parameters
KINEMATICS kinematics of the system
FLOATING_BASE true if system is a floating base robot
STATE_DIM state dimensionality of the system
CONTROL_DIM control dimensionality of the system
Member Typedef Documentation
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::BASE = optcon::TermBase<STATE_DIM, CONTROL_DIM, double, double>
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::DerivativesCppadJIT = core::DerivativesCppadJIT<AD_PARAMETER_DIM, 1>
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::CGScalar = typename DerivativesCppadJIT::CG_SCALAR
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::RBDStateTpl = ct::rbd::RBDState<KINEMATICS::NJOINTS, CGScalar>
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::state_matrix_t = Eigen::Matrix<double, STATE_DIM, STATE_DIM>
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::control_matrix_t = Eigen::Matrix<double, CONTROL_DIM, CONTROL_DIM>
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::control_state_matrix_t = Eigen::Matrix<double, CONTROL_DIM, STATE_DIM>
Constructor & Destructor Documentation
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG () default
default constructor
Referenced by ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::clone().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG (size_t eeInd, const Eigen::Matrix3d & Qpos, const double & Qrot, const core::StateVector< 3 > & w_pos_des, const Eigen::Quaterniond & w_q_des, const std::string & name = "TermTaskSpace", bool evalControlDerivatives = true) inline
constructor using a quaternion for orientation
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferenceOrientation(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferencePosition(), and ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setup().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG (size_t eeInd, const Eigen::Matrix3d & Qpos, const double & Qrot, const ct::rbd::RigidBodyPose & rbdPose, const std::string & name = "TermTaskSpace", bool evalControlDerivatives = true) inline
constructor taking a full RigidBodyPose
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG (size_t eeInd, const Eigen::Matrix3d & Qpos, const double & Qrot, const core::StateVector< 3 > & w_pos_des, const Eigen::Matrix3d & eulerXyz, const std::string & name = "TermTaskSpace", bool evalControlDerivatives = true) inline
constructor using Euler angles for orientation
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG (size_t eeInd, const Eigen::Matrix3d & Qpos, const double & Qrot, const std::string & name = "TermTaskSpace", bool evalControlDerivatives = false) inline
constructor which sets the target pose to dummy values
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferenceOrientation(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferencePosition(), and ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setup().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG (const std::string & configFile, const std::string & termName, bool verbose = false) inline
construct this term with info loaded from a configuration file
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::loadConfigFile(), and verbose.
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG (const TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM > & arg) inline
copy constructor
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::~TermTaskspacePoseCG () inline virtual
destructor
Member Function Documentation
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual TermTaskspacePoseCG<KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM>* ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::clone () const inline override virtual
deep cloning
Implements ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >.
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setup () inline
setup the AD Derivatives
References ct::core::DerivativesCppadSettings::createForwardZero_.
Referenced by ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::loadConfigFile(), and ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setCurrentStateAndControl (const Eigen::Matrix< double, STATE_DIM, 1 > & x, const Eigen::Matrix< double, CONTROL_DIM, 1 > & u, const double & t) inline
Referenced by ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::controlDerivative(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::controlSecondDerivative(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::evaluate(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::stateControlDerivative(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::stateDerivative(), and ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::stateSecondDerivative().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual double ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::evaluate (const Eigen::Matrix< double, STATE_DIM, 1 > & x, const Eigen::Matrix< double, CONTROL_DIM, 1 > & u, const double & t) inline override virtual
evaluate
Implements ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >.
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setCurrentStateAndControl().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual core::StateVector<STATE_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::stateDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute derivative of this cost term w.r.t. the state
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setCurrentStateAndControl().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual core::ControlVector<CONTROL_DIM> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::controlDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute derivative of this cost term w.r.t. the control input
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setCurrentStateAndControl().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual state_matrix_t ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::stateSecondDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute second order derivative of this cost term w.r.t. the state
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setCurrentStateAndControl().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual control_matrix_t ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::controlSecondDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute second order derivative of this cost term w.r.t. the control input
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setCurrentStateAndControl().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual control_state_matrix_t ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::stateControlDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute the cross-term derivative (state-control) of this cost function term
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setCurrentStateAndControl().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::loadConfigFile (const std::string & filename, const std::string & termName, bool verbose = false) inline override virtual
load term information from configuration file (stores data in member variables)
Reimplemented from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >.
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::getReferencePosition(), ct::optcon::loadMatrixCF(), ct::optcon::loadScalarCF(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferenceOrientation(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferencePosition(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setup(), and verbose.
Referenced by ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> const Eigen::Matrix<double, 3, 1> ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::getReferencePosition () const inline
retrieve reference position in world frame
Referenced by ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::getReferencePose(), and ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::loadConfigFile().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferencePosition (Eigen::Matrix< double, 3, 1 > w_p_ref) inline
set the end-effector reference position
Referenced by ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::loadConfigFile(), and ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> const Eigen::Quaterniond ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::getReferenceOrientation () const inline
retrieve reference ee orientation in world frame
Referenced by ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::getReferencePose().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferenceOrientation (const Eigen::Matrix< double, 3, 3 > & w_R_ref) inline
set desired end-effector orientation in world frame
Referenced by ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::loadConfigFile(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferenceOrientation(), and ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferenceOrientation (const Eigen::Quaterniond & w_q_des) inline
set desired end-effector orientation in world frame
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setReferenceOrientation().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> const ct::rbd::RigidBodyPose ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::getReferencePose () const inline
return the reference pose as RigidBodyPose
References ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::getReferenceOrientation(), and ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::getReferencePosition().
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> virtual RBDStateTpl ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::setStateFromVector (const Eigen::Matrix< CGScalar, STATE_DIM, 1 > & x) inline protected virtual
setStateFromVector transforms your (custom) state vector x into a RBDState. Is virtual to allow for easy overloading of this term for custom systems
Parameters
x your state vector
Returns
a full rigid body state
References ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::joints(), and x.
Member Data Documentation
template<class KINEMATICS , bool FLOATING_BASE, size_t STATE_DIM, size_t CONTROL_DIM> EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::AD_PARAMETER_DIM = STATE_DIM + CONTROL_DIM + 3 + 9 + 1 static
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/robot/costfunction/TermTaskspacePoseCG.hpp