iit::testirb4600::LinkDataMap< T > Class Template Reference
iit::testirb4600::LinkDataMap< T > Class Template Reference
#include <link_data_map.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW LinkDataMap ()
LinkDataMap (const T &defaultValue)
LinkDataMap (const LinkDataMap &rhs)
LinkDataMap & operator= (const LinkDataMap &rhs)
LinkDataMap & operator= (const T &rhs)
T & operator[] (LinkIdentifiers which)
const T & operator[] (LinkIdentifiers which) const
Detailed Description
template<typename T>
class iit::testirb4600::LinkDataMap< T >
A very simple container to associate a generic data item to each link
Constructor & Destructor Documentation
template<typename T > EIGEN_MAKE_ALIGNED_OPERATOR_NEW iit::testirb4600::LinkDataMap< T >::LinkDataMap () inline
References iit::testirb4600::LinkDataMap< T >::operator=(), and iit::testirb4600::LinkDataMap< T >::operator[]().
template<typename T > iit::testirb4600::LinkDataMap< T >::LinkDataMap (const T & defaultValue) inline
template<typename T > iit::testirb4600::LinkDataMap< T >::LinkDataMap (const LinkDataMap< T > & rhs) inline
Member Function Documentation
template<typename T > LinkDataMap< T > & iit::testirb4600::LinkDataMap< T >::operator= (const LinkDataMap< T > & rhs) inline
Referenced by iit::testirb4600::LinkDataMap< T >::LinkDataMap().
template<typename T > LinkDataMap< T > & iit::testirb4600::LinkDataMap< T >::operator= (const T & rhs) inline
template<typename T > T & iit::testirb4600::LinkDataMap< T >::operator[] (LinkIdentifiers which) inline
Referenced by iit::testirb4600::LinkDataMap< T >::LinkDataMap().
template<typename T > const T & iit::testirb4600::LinkDataMap< T >::operator[] (LinkIdentifiers which) const inline
References iit::testirb4600::LINK0, iit::testirb4600::LINK1, iit::testirb4600::LINK2, iit::testirb4600::LINK3, iit::testirb4600::LINK4, iit::testirb4600::LINK5, and iit::testirb4600::LINK6.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_rbd/test/models/testIrb4600/generated/link_data_map.h