ct::rbd::IDControllerFB< Dynamics > Class Template Reference
ct::rbd::IDControllerFB< Dynamics > Class Template Reference
#include <IDControllerFB.h>
Public Member Functions
IDControllerFB (std::shared_ptr< Dynamics > dynamics=std::shared_ptr< Dynamics >(new Dynamics()), const RBDState &desState=RBDState(), const Eigen::Matrix< double, 6, 1 > &Kp=Eigen::Matrix< double, 6, 1 >::Zero(), const Eigen::Matrix< double, 6, 1 > &Kd=Eigen::Matrix< double, 6, 1 >::Zero())
void setDesiredState (const RBDState &desState)
void setPoseGains (const Eigen::Matrix< double, 6, 1 > &Kp)
void setTwistGains (const Eigen::Matrix< double, 6, 1 > &Kd)
Dynamics::RBDAcceleration_t computeDesiredAcceleration (const RBDState &currBaseState)
Dynamics::control_vector_t computeTorque (const RBDState &currState, const typename Dynamics::EE_in_contact_t &eeInContact, bool gravityCompensation=true)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Dynamics::RBDState_t RBDState
Constructor & Destructor Documentation
template<class Dynamics > ct::rbd::IDControllerFB< Dynamics >::IDControllerFB (std::shared_ptr< Dynamics > dynamics = std::shared_ptr<Dynamics>(new Dynamics()), const RBDState & desState = RBDState(), const Eigen::Matrix< double, 6, 1 > & Kp = Eigen::Matrix<double, 6, 1>::Zero(), const Eigen::Matrix< double, 6, 1 > & Kd = Eigen::Matrix<double, 6, 1>::Zero()) inline
Member Function Documentation
template<class Dynamics > void ct::rbd::IDControllerFB< Dynamics >::setDesiredState (const RBDState & desState) inline
template<class Dynamics > void ct::rbd::IDControllerFB< Dynamics >::setPoseGains (const Eigen::Matrix< double, 6, 1 > & Kp) inline
template<class Dynamics > void ct::rbd::IDControllerFB< Dynamics >::setTwistGains (const Eigen::Matrix< double, 6, 1 > & Kd) inline
template<class Dynamics > Dynamics::RBDAcceleration_t ct::rbd::IDControllerFB< Dynamics >::computeDesiredAcceleration (const RBDState & currBaseState) inline
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::base(), ct::rbd::RBDState< NJOINTS, SCALAR >::base(), ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::fromVector6d(), ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationQuaternion(), ct::rbd::tpl::RigidBodyPose< SCALAR >::position(), ct::rbd::tpl::RigidBodyPose< SCALAR >::rotateInertiaToBase(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::setZero(), and ct::rbd::tpl::RigidBodyState< SCALAR >::velocities().
Referenced by ct::rbd::IDControllerFB< Dynamics >::computeTorque().
template<class Dynamics > Dynamics::control_vector_t ct::rbd::IDControllerFB< Dynamics >::computeTorque (const RBDState & currState, const typename Dynamics::EE_in_contact_t & eeInContact, bool gravityCompensation = true) inline
References ct::rbd::IDControllerFB< Dynamics >::computeDesiredAcceleration().
Member Data Documentation
template<class Dynamics > EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Dynamics::RBDState_t ct::rbd::IDControllerFB< Dynamics >::RBDState
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/robot/control/IDControllerFB.h