ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR > Class Template Reference
ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR > Class Template Reference
#include <SEADynamicsFirstOrder.h>
Public Member Functions
SEADynamicsFirstOrder (double k_spring, double gear_ratio)
constructor assuming unit amplification
virtual ~SEADynamicsFirstOrder ()
destructor
virtual SEADynamicsFirstOrder< NJOINTS, SCALAR > * clone () const override
deep cloning
virtual void computeActuatorDynamics (const JointState< NJOINTS, SCALAR > &robotJointState, const ct::core::StateVector< NJOINTS, SCALAR > &state, const SCALAR &t, const ct::core::ControlVector< NJOINTS, SCALAR > &control, ct::core::StateVector< NJOINTS, SCALAR > &derivative) override
virtual core::ControlVector< NJOINTS, SCALAR > computeControlOutput (const JointState< NJOINTS, SCALAR > &robotJointState, const typename BASE::act_state_vector_t &actState) override
virtual ct::core::StateVector< NJOINTS, SCALAR > computeStateFromOutput (const JointState< NJOINTS, SCALAR > &refRobotJointState, const core::ControlVector< NJOINTS, SCALAR > &refControl) override
reconstruct actuator state from a desired control output and robot joint state (e.g. for initialization)
Public Member Functions inherited from ct::rbd::ActuatorDynamics< NJOINTS, NJOINTS, SCALAR >
ActuatorDynamics ()
virtual ~ActuatorDynamics ()
virtual void computeActuatorDynamics (const JointState< NJOINTS, SCALAR > &robotJointState, const ct::core::StateVector< ACT_STATE_DIMS, SCALAR > &actuatorState, const SCALAR &t, const ct::core::ControlVector< NJOINTS, SCALAR > &control, ct::core::StateVector< ACT_STATE_DIMS, SCALAR > &derivative)=0
virtual core::ControlVector< NJOINTS, SCALAR > computeControlOutput (const JointState< NJOINTS, SCALAR > &robotJointState, const act_state_vector_t &actState)=0
output equation of the actuator
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ActuatorDynamics< NJOINTS, NJOINTS, SCALAR > BASE
Additional Inherited Members
Public Types inherited from ct::rbd::ActuatorDynamics< NJOINTS, NJOINTS, SCALAR >
typedef ct::core::StateVector< ACT_STATE_DIMS, SCALAR > act_state_vector_t
typedef ct::core::ControlVector< NJOINTS, SCALAR > act_control_vector_t
Static Public Attributes inherited from ct::rbd::ActuatorDynamics< NJOINTS, NJOINTS, SCALAR >
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t ACT_STATE_DIM
static const size_t ACT_CONTROL_DIM
Detailed Description
template<size_t NJOINTS, typename SCALAR = double>
class ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >
Series-elastic actuator dynamics modeled as a series of motor, gearbox and a spring.
Control Input: Motor Velocity Actuator State: Gear Position Actuator State Derivative: Gear Velocity
Note
The advantage of choosing the the gear position as state is that no calibration on the motor position is required. In a SEA, the gear position is typically known anyway.
Constructor & Destructor Documentation
template<size_t NJOINTS, typename SCALAR > ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::SEADynamicsFirstOrder (double k_spring, double gear_ratio)
constructor assuming unit amplification
Referenced by ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::clone().
template<size_t NJOINTS, typename SCALAR > ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::~SEADynamicsFirstOrder () virtual
destructor
Member Function Documentation
template<size_t NJOINTS, typename SCALAR > SEADynamicsFirstOrder< NJOINTS, SCALAR > * ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::clone () const override virtual
deep cloning
Implements ct::rbd::ActuatorDynamics< NJOINTS, NJOINTS, SCALAR >.
References ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::SEADynamicsFirstOrder().
template<size_t NJOINTS, typename SCALAR > void ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::computeActuatorDynamics (const JointState< NJOINTS, SCALAR > & robotJointState, const ct::core::StateVector< NJOINTS, SCALAR > & state, const SCALAR & t, const ct::core::ControlVector< NJOINTS, SCALAR > & control, ct::core::StateVector< NJOINTS, SCALAR > & derivative) override virtual
template<size_t NJOINTS, typename SCALAR > core::ControlVector< NJOINTS, SCALAR > ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::computeControlOutput (const JointState< NJOINTS, SCALAR > & robotJointState, const typename BASE::act_state_vector_t & actState) override virtual
References ct::rbd::JointState< NJOINTS, SCALAR >::getPositions().
template<size_t NJOINTS, typename SCALAR > ct::core::StateVector< NJOINTS, SCALAR > ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::computeStateFromOutput (const JointState< NJOINTS, SCALAR > & refRobotJointState, const core::ControlVector< NJOINTS, SCALAR > & refControl) override virtual
reconstruct actuator state from a desired control output and robot joint state (e.g. for initialization)
Returns
the actuator state resulting in the desired control output
Implements ct::rbd::ActuatorDynamics< NJOINTS, NJOINTS, SCALAR >.
References ct::rbd::JointState< NJOINTS, SCALAR >::getPositions(), and ct::core::ControlVector< CONTROL_DIM, SCALAR >::toImplementation().
Member Data Documentation
template<size_t NJOINTS, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef ActuatorDynamics<NJOINTS, NJOINTS, SCALAR> ct::rbd::SEADynamicsFirstOrder< NJOINTS, SCALAR >::BASE
The documentation for this class was generated from the following files:
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/robot/actuator/SEADynamicsFirstOrder.h
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/robot/actuator/SEADynamicsFirstOrder-impl.h