iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
#include <inertia_properties.h>
Public Types
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > IMatrix
typedef Eigen::Matrix< SCALAR, 3, 1 > Vec3d
Public Member Functions
InertiaProperties ()
~InertiaProperties ()
const IMatrix & getTensor_link1 () const
const IMatrix & getTensor_link2 () const
const IMatrix & getTensor_link3 () const
const IMatrix & getTensor_link4 () const
const IMatrix & getTensor_link5 () const
const IMatrix & getTensor_link6 () const
SCALAR getMass_link1 () const
SCALAR getMass_link2 () const
SCALAR getMass_link3 () const
SCALAR getMass_link4 () const
SCALAR getMass_link5 () const
SCALAR getMass_link6 () const
const Vec3d & getCOM_link1 () const
const Vec3d & getCOM_link2 () const
const Vec3d & getCOM_link3 () const
const Vec3d & getCOM_link4 () const
const Vec3d & getCOM_link5 () const
const Vec3d & getCOM_link6 () const
SCALAR getTotalMass () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar SCALAR
Member Typedef Documentation
IMatrix
template<typename TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::IMatrix
Vec3d
template<typename TRAIT> typedef Eigen::Matrix<SCALAR, 3, 1> iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::Vec3d
Constructor & Destructor Documentation
InertiaProperties()
template<typename TRAIT > iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::InertiaProperties ()
~InertiaProperties()
template<typename TRAIT > iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::~InertiaProperties () inline
Member Function Documentation
getTensor_link1()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link1 () const inline
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::update().
getTensor_link2()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link2 () const inline
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::update().
getTensor_link3()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link3 () const inline
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::update().
getTensor_link4()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link4 () const inline
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::update().
getTensor_link5()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link5 () const inline
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::update().
getTensor_link6()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link6 () const inline
getMass_link1()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getMass_link1 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_link2()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getMass_link2 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_link3()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getMass_link3 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_link4()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getMass_link4 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_link5()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getMass_link5 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getMass_link6()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getMass_link6 () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
getCOM_link1()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getCOM_link1 () const inline
getCOM_link2()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getCOM_link2 () const inline
getCOM_link3()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getCOM_link3 () const inline
getCOM_link4()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getCOM_link4 () const inline
getCOM_link5()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getCOM_link5 () const inline
getCOM_link6()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getCOM_link6 () const inline
getTotalMass()
template<typename TRAIT > InertiaProperties< TRAIT >::SCALAR iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTotalMass () const inline
Member Data Documentation
SCALAR
template<typename TRAIT> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::SCALAR
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testIrb4600/generated/inertia_properties.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testIrb4600/generated/inertia_properties.impl.h