ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM > Class Template Reference
ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM > Class Template Reference
A costfunction term that defines a cost on a task-space pose, for fix-base robots only.
#include <TermTaskspaceGeometricJacobian.hpp>
Public Types
using BASE = optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >
using RBDState = ct::rbd::RBDState< KINEMATICS::NJOINTS >
using state_matrix_t = Eigen::Matrix< double, STATE_DIM, STATE_DIM >
using control_matrix_t = Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM >
using control_state_matrix_t = Eigen::Matrix< double, CONTROL_DIM, STATE_DIM >
Public Types inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >
typedef Eigen::Matrix< double, STATE_DIM, STATE_DIM > state_matrix_t
typedef Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< double, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef Eigen::Matrix< double, STATE_DIM, STATE_DIM > state_matrix_double_t
typedef Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM > control_matrix_double_t
typedef Eigen::Matrix< double, CONTROL_DIM, STATE_DIM > control_state_matrix_double_t
Public Member Functions
TermTaskspaceGeometricJacobian ()=default
default constructor
TermTaskspaceGeometricJacobian (size_t eeInd, const Eigen::Matrix3d &Qpos, const Eigen::Matrix3d &Qrot, const core::StateVector< 3 > &w_pos_des, const Eigen::Quaterniond &w_q_des, const std::string &name="TermTaskSpace")
constructor using a quaternion for orientation
TermTaskspaceGeometricJacobian (size_t eeInd, const Eigen::Matrix3d &Qpos, const Eigen::Matrix3d &Qrot, const ct::rbd::RigidBodyPose &rbdPose, const std::string &name="TermTaskSpace")
constructor taking a full RigidBodyPose
TermTaskspaceGeometricJacobian (size_t eeInd, const Eigen::Matrix3d &Qpos, const Eigen::Matrix3d &Qrot, const core::StateVector< 3 > &w_pos_des, const Eigen::Matrix3d &eulerXyz, const std::string &name="TermTaskSpace")
constructor using Euler angles for orientation
TermTaskspaceGeometricJacobian (size_t eeInd, const Eigen::Matrix3d &Qpos, const Eigen::Matrix3d &Qrot, const std::string &name="TermTaskSpace")
constructor which sets the target pose to dummy values
TermTaskspaceGeometricJacobian (const std::string &configFile, const std::string &termName, bool verbose=false)
construct this term with info loaded from a configuration file
TermTaskspaceGeometricJacobian (const TermTaskspaceGeometricJacobian &arg)
copy constructor
virtual ~TermTaskspaceGeometricJacobian ()=default
destructor
virtual TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM > * clone () const override
deep cloning
virtual double evaluate (const Eigen::Matrix< double, STATE_DIM, 1 > &x, const Eigen::Matrix< double, CONTROL_DIM, 1 > &u, const double &t) override
evaluate
virtual core::StateVector< STATE_DIM > stateDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute derivative of this cost term w.r.t. the state
virtual core::ControlVector< CONTROL_DIM > controlDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute derivative of this cost term w.r.t. the control input
virtual state_matrix_t stateSecondDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute second order derivative of this cost term w.r.t. the state
virtual control_matrix_t controlSecondDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute second order derivative of this cost term w.r.t. the control input
virtual control_state_matrix_t stateControlDerivative (const core::StateVector< STATE_DIM > &x, const core::ControlVector< CONTROL_DIM > &u, const double &t) override
compute the cross-term derivative (state-control) of this cost function term
void loadConfigFile (const std::string &filename, const std::string &termName, bool verbose=false) override
load term information from configuration file (stores data in member variables)
const Eigen::Matrix< double, 3, 1 > getReferencePosition () const
retrieve reference position in world frame
void setReferencePosition (Eigen::Matrix< double, 3, 1 > p_ref)
set the end-effector reference position (in base coordinates)
const Eigen::Quaterniond getReferenceOrientation () const
retrieve reference ee orientation in world frame
void setReferenceOrientation (const Eigen::Matrix< double, 3, 3 > &w_R_ref)
set desired end-effector orientation in world frame
void setReferenceOrientation (const Eigen::Quaterniond &w_q_des)
set desired end-effector orientation in world frame
const ct::rbd::RigidBodyPose getReferencePose () const
return the reference pose as RigidBodyPose
Public Member Functions inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >
TermBase (std::string name="Unnamed")
TermBase (const TermBase &arg)
virtual ~TermBase ()
double eval (const Eigen::Matrix< double, STATE_DIM, 1 > &x, const Eigen::Matrix< double, CONTROL_DIM, 1 > &u, const double &t)
virtual bool isActiveAtTime (double t)
double computeActivation (double t)
virtual core::StateVector< STATE_DIM, double > stateDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual state_matrix_t stateSecondDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual core::ControlVector< CONTROL_DIM, double > controlDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual control_matrix_t controlSecondDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual control_state_matrix_t stateControlDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
void setTimeActivation (std::shared_ptr< ct::core::tpl::ActivationBase< double >> c_i, bool verbose=false)
void loadTimeActivation (const std::string &filename, const std::string &termName, bool verbose=false)
const std::string & getName () const
void setName (const std::string &termName)
virtual void updateReferenceState (const Eigen::Matrix< double, STATE_DIM, 1 > &newRefState)
virtual void updateReferenceControl (const Eigen::Matrix< double, CONTROL_DIM, 1 > &newRefControl)
virtual Eigen::Matrix< double, STATE_DIM, 1 > getReferenceState () const
Additional Inherited Members
Protected Attributes inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >
std::string name_
std::shared_ptr< ct::core::tpl::ActivationBase< double > > c_i_
Detailed Description
template<class KINEMATICS, size_t STATE_DIM, size_t CONTROL_DIM>
class ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >
A costfunction term that defines a cost on a task-space pose, for fix-base robots only.
Template Parameters
KINEMATICS kinematics of the system
STATE_DIM state dimensionality of the system
CONTROL_DIM control dimensionality of the system
Member Typedef Documentation
BASE
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::BASE = optcon::TermBase<STATE_DIM, CONTROL_DIM, double, double>
RBDState
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::RBDState = ct::rbd::RBDState<KINEMATICS::NJOINTS>
state_matrix_t
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::state_matrix_t = Eigen::Matrix<double, STATE_DIM, STATE_DIM>
control_matrix_t
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::control_matrix_t = Eigen::Matrix<double, CONTROL_DIM, CONTROL_DIM>
control_state_matrix_t
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::control_state_matrix_t = Eigen::Matrix<double, CONTROL_DIM, STATE_DIM>
Constructor & Destructor Documentation
TermTaskspaceGeometricJacobian() [1/7]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian () default
default constructor
Referenced by ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::clone().
TermTaskspaceGeometricJacobian() [2/7]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian (size_t eeInd, const Eigen::Matrix3d & Qpos, const Eigen::Matrix3d & Qrot, const core::StateVector< 3 > & w_pos_des, const Eigen::Quaterniond & w_q_des, const std::string & name = "TermTaskSpace") inline
constructor using a quaternion for orientation
References ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferenceOrientation(), and ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferencePosition().
TermTaskspaceGeometricJacobian() [3/7]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian (size_t eeInd, const Eigen::Matrix3d & Qpos, const Eigen::Matrix3d & Qrot, const ct::rbd::RigidBodyPose & rbdPose, const std::string & name = "TermTaskSpace") inline
constructor taking a full RigidBodyPose
TermTaskspaceGeometricJacobian() [4/7]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian (size_t eeInd, const Eigen::Matrix3d & Qpos, const Eigen::Matrix3d & Qrot, const core::StateVector< 3 > & w_pos_des, const Eigen::Matrix3d & eulerXyz, const std::string & name = "TermTaskSpace") inline
constructor using Euler angles for orientation
TermTaskspaceGeometricJacobian() [5/7]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian (size_t eeInd, const Eigen::Matrix3d & Qpos, const Eigen::Matrix3d & Qrot, const std::string & name = "TermTaskSpace") inline
constructor which sets the target pose to dummy values
References ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferenceOrientation(), and ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferencePosition().
TermTaskspaceGeometricJacobian() [6/7]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian (const std::string & configFile, const std::string & termName, bool verbose = false) inline
construct this term with info loaded from a configuration file
References ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::loadConfigFile(), and verbose.
TermTaskspaceGeometricJacobian() [7/7]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian (const TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM > & arg) inline
copy constructor
References ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::~TermTaskspaceGeometricJacobian().
~TermTaskspaceGeometricJacobian()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> virtual ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::~TermTaskspaceGeometricJacobian () virtual default
destructor
Referenced by ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian().
Member Function Documentation
clone()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> virtual TermTaskspaceGeometricJacobian<KINEMATICS, STATE_DIM, CONTROL_DIM>* ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::clone () const inline override virtual
deep cloning
Implements ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >.
References ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian().
evaluate()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> virtual double ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::evaluate (const Eigen::Matrix< double, STATE_DIM, 1 > & x, const Eigen::Matrix< double, CONTROL_DIM, 1 > & u, const double & t) inline override virtual
evaluate
Implements ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >.
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), and ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions().
stateDerivative()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> virtual core::StateVector<STATE_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::stateDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute derivative of this cost term w.r.t. the state
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), and ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions().
controlDerivative()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> virtual core::ControlVector<CONTROL_DIM> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::controlDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute derivative of this cost term w.r.t. the control input
stateSecondDerivative()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> virtual state_matrix_t ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::stateSecondDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute second order derivative of this cost term w.r.t. the state
References ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions().
controlSecondDerivative()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> virtual control_matrix_t ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::controlSecondDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute second order derivative of this cost term w.r.t. the control input
stateControlDerivative()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> virtual control_state_matrix_t ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::stateControlDerivative (const core::StateVector< STATE_DIM > & x, const core::ControlVector< CONTROL_DIM > & u, const double & t) inline override virtual
compute the cross-term derivative (state-control) of this cost function term
loadConfigFile()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::loadConfigFile (const std::string & filename, const std::string & termName, bool verbose = false) inline override virtual
load term information from configuration file (stores data in member variables)
Reimplemented from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, double >.
References ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::getReferencePosition(), ct::optcon::loadMatrixCF(), ct::optcon::loadScalarCF(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferenceOrientation(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferencePosition(), and verbose.
Referenced by ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian().
getReferencePosition()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> const Eigen::Matrix<double, 3, 1> ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::getReferencePosition () const inline
retrieve reference position in world frame
Referenced by ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::getReferencePose(), and ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::loadConfigFile().
setReferencePosition()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferencePosition (Eigen::Matrix< double, 3, 1 > p_ref) inline
set the end-effector reference position (in base coordinates)
Referenced by ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::loadConfigFile(), and ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian().
getReferenceOrientation()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> const Eigen::Quaterniond ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::getReferenceOrientation () const inline
retrieve reference ee orientation in world frame
Referenced by ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::getReferencePose().
setReferenceOrientation() [1/2]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferenceOrientation (const Eigen::Matrix< double, 3, 3 > & w_R_ref) inline
set desired end-effector orientation in world frame
Referenced by ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::loadConfigFile(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferenceOrientation(), and ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian().
setReferenceOrientation() [2/2]
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferenceOrientation (const Eigen::Quaterniond & w_q_des) inline
set desired end-effector orientation in world frame
References ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::setReferenceOrientation().
getReferencePose()
template<class KINEMATICS , size_t STATE_DIM, size_t CONTROL_DIM> const ct::rbd::RigidBodyPose ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::getReferencePose () const inline
return the reference pose as RigidBodyPose
References ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::getReferenceOrientation(), and ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::getReferencePosition().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/robot/costfunction/TermTaskspaceGeometricJacobian.hpp