ct::rbd::WholeBodyController< NJOINTS > Class Template Reference
ct::rbd::WholeBodyController< NJOINTS > Class Template Reference
#include <WholeBodyController.h>
Public Member Functions
WholeBodyController ()
virtual ~WholeBodyController ()
virtual WholeBodyController< NJOINTS > * clone () const override
virtual void computeControl (const core::StateVector< STATE_DIM > &state, const core::Time &t, core::ControlVector< NJOINTS > &control) override
JointPositionPIDController< NJOINTS > & getJointController ()
Public Member Functions inherited from ct::core::Controller< 2 *6+2 *NJOINTS, NJOINTS >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW Controller ()
Controller (const Controller &other)
virtual ~Controller ()
virtual void computeControl (const StateVector< 2 *6+2 *NJOINTS, SCALAR > &state, const SCALAR &t, ControlVector< NJOINTS, SCALAR > &controlAction)=0
virtual ControlMatrix< NJOINTS, SCALAR > getDerivativeU0 (const StateVector< 2 *6+2 *NJOINTS, SCALAR > &state, const SCALAR time)
virtual ControlMatrix< NJOINTS, SCALAR > getDerivativeUf (const StateVector< 2 *6+2 *NJOINTS, SCALAR > &state, const SCALAR time)
Static Public Attributes
static const size_t STATE_DIM = 2 * 6 + 2 * NJOINTS
Protected Attributes
JointPositionPIDController< NJOINTS > jointController_
Constructor & Destructor Documentation
WholeBodyController()
template<size_t NJOINTS> ct::rbd::WholeBodyController< NJOINTS >::WholeBodyController ()
~WholeBodyController()
template<size_t NJOINTS> ct::rbd::WholeBodyController< NJOINTS >::~WholeBodyController () virtual
Member Function Documentation
clone()
template<size_t NJOINTS> WholeBodyController< NJOINTS > * ct::rbd::WholeBodyController< NJOINTS >::clone () const override virtual
Implements ct::core::Controller< 2 *6+2 *NJOINTS, NJOINTS >.
computeControl()
template<size_t NJOINTS> void ct::rbd::WholeBodyController< NJOINTS >::computeControl (const core::StateVector< STATE_DIM > & state, const core::Time & t, core::ControlVector< NJOINTS > & control) override virtual
References ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::joints(), ct::rbd::JointState< NJOINTS, SCALAR >::toImplementation(), and x.
getJointController()
template<size_t NJOINTS> JointPositionPIDController< NJOINTS > & ct::rbd::WholeBodyController< NJOINTS >::getJointController ()
Member Data Documentation
STATE_DIM
template<size_t NJOINTS> const size_t ct::rbd::WholeBodyController< NJOINTS >::STATE_DIM = 2 * 6 + 2 * NJOINTS static
jointController_
template<size_t NJOINTS> JointPositionPIDController<NJOINTS> ct::rbd::WholeBodyController< NJOINTS >::jointController_ protected
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/robot/control/WholeBodyController.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/robot/control/WholeBodyController-impl.h