iit::testirb4600::dyn::tpl::JSIM< TRAIT > Class Template Reference
iit::testirb4600::dyn::tpl::JSIM< TRAIT > Class Template Reference
#include <jsim.h>
Public Types
typedef TRAIT::Scalar SCALAR
typedef Base::Index Index
typedef Eigen::Matrix< SCALAR, 6, 6 > MatrixType
typedef InertiaProperties< TRAIT > IProperties
typedef iit::testirb4600::tpl::ForceTransforms< TRAIT > FTransforms
typedef iit::rbd::tpl::InertiaMatrixDense< SCALAR > InertiaMatrix
Public Types inherited from iit::rbd::StateDependentMatrix< iit::testirb4600::JointState, 6, 6, JSIM< TRAIT > >
typedef Base::Index Index
typedef Base MatrixType
Public Member Functions
JSIM (IProperties &, FTransforms &)
~JSIM ()
const JSIM & update (const iit::testirb4600::JointState &)
void computeL ()
void computeInverse ()
const MatrixType & getL () const
const MatrixType & getInverse () const
Public Member Functions inherited from iit::rbd::StateDependentMatrix< iit::testirb4600::JointState, 6, 6, JSIM< TRAIT > >
StateDependentMatrix ()
~StateDependentMatrix ()
StateDependentMatrix & operator= (const MatrixBase< OtherDerived > &other)
Public Member Functions inherited from iit::rbd::StateDependentBase< iit::testirb4600::JointState, JSIM< TRAIT > >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW const JSIM< TRAIT > & operator() (iit::testirb4600::JointState const &state)
const JSIM< TRAIT > & update (iit::testirb4600::JointState const &state)
Protected Member Functions
void computeLInverse ()
Additional Inherited Members
Public Attributes inherited from iit::rbd::StateDependentMatrix< iit::testirb4600::JointState, 6, 6, JSIM< TRAIT > >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Base::Scalar Scalar
Detailed Description
template<class TRAIT>
class iit::testirb4600::dyn::tpl::JSIM< TRAIT >
The type of the Joint Space Inertia Matrix (JSIM) of the robot testirb4600.
Member Typedef Documentation
SCALAR
template<class TRAIT> typedef TRAIT::Scalar iit::testirb4600::dyn::tpl::JSIM< TRAIT >::SCALAR
Index
template<class TRAIT> typedef Base::Index iit::testirb4600::dyn::tpl::JSIM< TRAIT >::Index
MatrixType
template<class TRAIT> typedef Eigen::Matrix<SCALAR,6,6> iit::testirb4600::dyn::tpl::JSIM< TRAIT >::MatrixType
IProperties
template<class TRAIT> typedef InertiaProperties<TRAIT> iit::testirb4600::dyn::tpl::JSIM< TRAIT >::IProperties
FTransforms
template<class TRAIT> typedef iit::testirb4600::tpl::ForceTransforms<TRAIT> iit::testirb4600::dyn::tpl::JSIM< TRAIT >::FTransforms
InertiaMatrix
template<class TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<SCALAR> iit::testirb4600::dyn::tpl::JSIM< TRAIT >::InertiaMatrix
Constructor & Destructor Documentation
JSIM()
template<typename TRAIT > iit::testirb4600::dyn::tpl::JSIM< TRAIT >::JSIM (IProperties & inertiaProperties, FTransforms & forceTransforms)
~JSIM()
template<class TRAIT> iit::testirb4600::dyn::tpl::JSIM< TRAIT >::~JSIM () inline
References iit::testirb4600::dyn::tpl::JSIM< TRAIT >::computeInverse(), iit::testirb4600::dyn::tpl::JSIM< TRAIT >::computeL(), iit::testirb4600::dyn::tpl::JSIM< TRAIT >::computeLInverse(), iit::testirb4600::dyn::tpl::JSIM< TRAIT >::getInverse(), iit::testirb4600::dyn::tpl::JSIM< TRAIT >::getL(), and iit::testirb4600::dyn::tpl::JSIM< TRAIT >::update().
Member Function Documentation
update()
template<typename TRAIT > const iit::testirb4600::dyn::tpl::JSIM< TRAIT > & iit::testirb4600::dyn::tpl::JSIM< TRAIT >::update (const iit::testirb4600::JointState & state)
References iit::rbd::AZ, DATA, F, iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link1(), iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link2(), iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link3(), iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link4(), iit::testirb4600::dyn::tpl::InertiaProperties< TRAIT >::getTensor_link5(), iit::testirb4600::JA, iit::testirb4600::JB, iit::testirb4600::JC, iit::testirb4600::JD, iit::testirb4600::JE, iit::testirb4600::JF, and iit::rbd::transformInertia().
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::~JSIM().
computeL()
template<typename TRAIT > void iit::testirb4600::dyn::tpl::JSIM< TRAIT >::computeL ()
Computes and saves the matrix L of the L^T L factorization of this JSIM.
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::~JSIM().
computeInverse()
template<typename TRAIT > void iit::testirb4600::dyn::tpl::JSIM< TRAIT >::computeInverse ()
Computes and saves the inverse of this JSIM. This function assumes that computeL() has been called already, since it uses L to compute the inverse. The algorithm takes advantage of the branch induced sparsity of the robot, if any.
References iit::testirb4600::dyn::tpl::JSIM< TRAIT >::computeLInverse().
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::~JSIM().
getL()
template<class TRAIT > const JSIM< TRAIT >::MatrixType & iit::testirb4600::dyn::tpl::JSIM< TRAIT >::getL () const inline
Returns an unmodifiable reference to the matrix L. See also computeL()
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::~JSIM().
getInverse()
template<class TRAIT > const JSIM< TRAIT >::MatrixType & iit::testirb4600::dyn::tpl::JSIM< TRAIT >::getInverse () const inline
Returns an unmodifiable reference to the inverse of this JSIM
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::~JSIM().
computeLInverse()
template<typename TRAIT > void iit::testirb4600::dyn::tpl::JSIM< TRAIT >::computeLInverse () protected
Computes and saves the inverse of the matrix L. See also computeL()
Referenced by iit::testirb4600::dyn::tpl::JSIM< TRAIT >::computeInverse(), and iit::testirb4600::dyn::tpl::JSIM< TRAIT >::~JSIM().
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testIrb4600/generated/jsim.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testIrb4600/generated/jsim.impl.h