ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM > Class Template Reference
ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM > Class Template Reference
A costfunction term that defines a cost on a task-space pose.
#include <TermTaskspacePose.hpp>
Public Types
using SCALAR = ct::core::ADCGScalar
using BASE = optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >
using RBDStateTpl = ct::rbd::RBDState< KINEMATICS::NJOINTS, SCALAR >
Public Types inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >
typedef Eigen::Matrix< double, STATE_DIM, STATE_DIM > state_matrix_t
typedef Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< double, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef Eigen::Matrix< double, STATE_DIM, STATE_DIM > state_matrix_double_t
typedef Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM > control_matrix_double_t
typedef Eigen::Matrix< double, CONTROL_DIM, STATE_DIM > control_state_matrix_double_t
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW TermTaskspacePose ()
the trivial constructor is explicitly forbidden
TermTaskspacePose (size_t eeInd, const Eigen::Matrix< double, 3, 3 > &Qpos, const double &Qrot, const ct::rbd::RigidBodyPose &rbdPose, const std::string &name="TermTaskSpace")
constructor taking a full RigidBodyPose
TermTaskspacePose (size_t eeInd, const Eigen::Matrix< double, 3, 3 > &Qpos, const double &Qrot, const core::StateVector< 3, double > &w_pos_des, const Eigen::Quaternion< double > &w_q_des, const std::string &name="TermTaskSpace")
constructor using a quaternion for orientation
TermTaskspacePose (size_t eeInd, const Eigen::Matrix< double, 3, 3 > &Qpos, const double &Qrot, const core::StateVector< 3, double > &w_pos_des, const Eigen::Matrix< double, 3, 1 > &eulerXyz, const std::string &name="TermTaskSpace")
constructor using euler angles for orientation
TermTaskspacePose (std::string &configFile, const std::string &termName, bool verbose=false)
construct this term with info loaded from a configuration file
TermTaskspacePose (const TermTaskspacePose &arg)
copy constructor
virtual ~TermTaskspacePose ()
destructor
virtual TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM > * clone () const override
deep cloning
virtual SCALAR evaluate (const Eigen::Matrix< SCALAR, STATE_DIM, 1 > &x, const Eigen::Matrix< SCALAR, CONTROL_DIM, 1 > &u, const SCALAR &t) override
evaluate
virtual ct::core::ADCGScalar evaluateCppadCg (const core::StateVector< STATE_DIM, ct::core::ADCGScalar > &x, const core::ControlVector< CONTROL_DIM, ct::core::ADCGScalar > &u, ct::core::ADCGScalar t) override
we overload the evaluateCppadCg method
void loadConfigFile (const std::string &filename, const std::string &termName, bool verbose=false) override
load term information from configuration file (stores data in member variables)
const Eigen::Matrix< double, 3, 1 > & getReferencePosition () const
retrieve reference position in world frame
const Eigen::Quaterniond getReferenceOrientation () const
retrieve reference ee orientation in world frame
void setReferencePosition (const Eigen::Matrix< double, 3, 1 > &w_p_ref)
set the endeffector reference position
void setReferenceOrientation (const Eigen::Matrix< double, 3, 3 > w_R_ref)
set the endeffector reference orientation
const ct::rbd::RigidBodyPose getReferencePose () const
return the reference pose as RigidBodyPose
Public Member Functions inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >
TermBase (std::string name="Unnamed")
TermBase (const TermBase &arg)
virtual ~TermBase ()
double eval (const Eigen::Matrix< double, STATE_DIM, 1 > &x, const Eigen::Matrix< double, CONTROL_DIM, 1 > &u, const double &t)
virtual bool isActiveAtTime (doublet)
double computeActivation (doublet)
virtual core::StateVector< STATE_DIM, double > stateDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual state_matrix_t stateSecondDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual core::ControlVector< CONTROL_DIM, double > controlDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual control_matrix_t controlSecondDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual control_state_matrix_t stateControlDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
void setTimeActivation (std::shared_ptr< ct::core::tpl::ActivationBase< double >> c_i, bool verbose=false)
void loadTimeActivation (const std::string &filename, const std::string &termName, bool verbose=false)
const std::string & getName () const
void setName (const std::string &termName)
virtual void updateReferenceState (const Eigen::Matrix< double, STATE_DIM, 1 > &newRefState)
virtual void updateReferenceControl (const Eigen::Matrix< double, CONTROL_DIM, 1 > &newRefControl)
virtual Eigen::Matrix< double, STATE_DIM, 1 > getReferenceState () const
Protected Member Functions
virtual RBDStateTpl setStateFromVector (const Eigen::Matrix< SCALAR, STATE_DIM, 1 > &x)
Additional Inherited Members
Protected Attributes inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >
std::string name_
std::shared_ptr< ct::core::tpl::ActivationBase< double > > c_i_
Detailed Description
template<class KINEMATICS, bool FB, size_t STATE_DIM, size_t CONTROL_DIM>
class ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >
A costfunction term that defines a cost on a task-space pose.
Todo:
add velocity to term
Template Parameters
KINEMATICS kinematics of the system
FB true if system is a floating base robot
STATE_DIM state dimensionality of the system
CONTROL_DIM control dimensionality of the system
Member Typedef Documentation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::SCALAR = ct::core::ADCGScalar
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::BASE = optcon::TermBase<STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar>
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::RBDStateTpl = ct::rbd::RBDState<KINEMATICS::NJOINTS, SCALAR>
Constructor & Destructor Documentation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> EIGEN_MAKE_ALIGNED_OPERATOR_NEW ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose () inline
the trivial constructor is explicitly forbidden
Referenced by ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::clone().
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose (size_t eeInd, const Eigen::Matrix< double, 3, 3 > & Qpos, const double & Qrot, const ct::rbd::RigidBodyPose & rbdPose, const std::string & name = "TermTaskSpace") inline
constructor taking a full RigidBodyPose
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose (size_t eeInd, const Eigen::Matrix< double, 3, 3 > & Qpos, const double & Qrot, const core::StateVector< 3, double > & w_pos_des, const Eigen::Quaternion< double > & w_q_des, const std::string & name = "TermTaskSpace") inline
constructor using a quaternion for orientation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose (size_t eeInd, const Eigen::Matrix< double, 3, 3 > & Qpos, const double & Qrot, const core::StateVector< 3, double > & w_pos_des, const Eigen::Matrix< double, 3, 1 > & eulerXyz, const std::string & name = "TermTaskSpace") inline
constructor using euler angles for orientation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose (std::string & configFile, const std::string & termName, bool verbose = false) inline
construct this term with info loaded from a configuration file
References ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::loadConfigFile(), and verbose.
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose (const TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM > & arg) inline
copy constructor
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> virtual ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::~TermTaskspacePose () inline virtual
destructor
Member Function Documentation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> virtual TermTaskspacePose<KINEMATICS, FB, STATE_DIM, CONTROL_DIM>* ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::clone () const inline override virtual
deep cloning
Implements ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >.
References ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose().
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> virtual SCALAR ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::evaluate (const Eigen::Matrix< SCALAR, STATE_DIM, 1 > & x, const Eigen::Matrix< SCALAR, CONTROL_DIM, 1 > & u, const SCALAR & t) inline override virtual
evaluate
Implements ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >.
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> virtual ct::core::ADCGScalar ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::evaluateCppadCg (const core::StateVector< STATE_DIM, ct::core::ADCGScalar > & x, const core::ControlVector< CONTROL_DIM, ct::core::ADCGScalar > & u, ct::core::ADCGScalar t) inline override virtual
we overload the evaluateCppadCg method
Reimplemented from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >.
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::loadConfigFile (const std::string & filename, const std::string & termName, bool verbose = false) inline override virtual
load term information from configuration file (stores data in member variables)
Reimplemented from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >.
References ct::optcon::loadMatrixCF(), ct::optcon::loadScalarCF(), and verbose.
Referenced by ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose().
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> const Eigen::Matrix<double, 3, 1>& ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::getReferencePosition () const inline
retrieve reference position in world frame
Referenced by ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::getReferencePose().
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> const Eigen::Quaterniond ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::getReferenceOrientation () const inline
retrieve reference ee orientation in world frame
Referenced by ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::getReferencePose().
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::setReferencePosition (const Eigen::Matrix< double, 3, 1 > & w_p_ref) inline
set the endeffector reference position
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::setReferenceOrientation (const Eigen::Matrix< double, 3, 3 > w_R_ref) inline
set the endeffector reference orientation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> const ct::rbd::RigidBodyPose ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::getReferencePose () const inline
return the reference pose as RigidBodyPose
References ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::getReferenceOrientation(), and ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::getReferencePosition().
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> virtual RBDStateTpl ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::setStateFromVector (const Eigen::Matrix< SCALAR, STATE_DIM, 1 > & x) inline protected virtual
setStateFromVector transforms your (custom) state vector x into a RBDState. Is virtual to allow for easy overloading of this term for custom systems
Parameters
x your state vector
Returns
a full rigid body state
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), ct::rbd::RBDState< NJOINTS, SCALAR >::joints(), t, u, and x.
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/robot/costfunction/TermTaskspacePose.hpp