ct::rbd::RBDDataMap< T, N > Class Template Reference
ct::rbd::RBDDataMap< T, N > Class Template Reference
A very simple container to associate N generic data item T.
#include <RBDDataMap.h>
Public Member Functions
RBDDataMap ()
RBDDataMap (const T &defaultValue)
RBDDataMap (const RBDDataMap &rhs)
RBDDataMap & operator= (const RBDDataMap &rhs)
RBDDataMap & operator= (const T &rhs)
T & operator[] (size_t which)
const T & operator[] (size_t which) const
Detailed Description
template<typename T, size_t N>
class ct::rbd::RBDDataMap< T, N >
A very simple container to associate N generic data item T.
Constructor & Destructor Documentation
template<typename T, size_t N> ct::rbd::RBDDataMap< T, N >::RBDDataMap () inline
Referenced by ct::rbd::RBDDataMap< bool, NEE >::RBDDataMap().
template<typename T, size_t N> ct::rbd::RBDDataMap< T, N >::RBDDataMap (const T & defaultValue) inline
template<typename T, size_t N> ct::rbd::RBDDataMap< T, N >::RBDDataMap (const RBDDataMap< T, N > & rhs) inline
Member Function Documentation
template<typename T , size_t N> RBDDataMap< T, N > & ct::rbd::RBDDataMap< T, N >::operator= (const RBDDataMap< T, N > & rhs) inline
Referenced by ct::rbd::RBDDataMap< bool, NEE >::RBDDataMap().
template<typename T, size_t N> RBDDataMap< T, N > & ct::rbd::RBDDataMap< T, N >::operator= (const T & rhs) inline
template<typename T , size_t N> T & ct::rbd::RBDDataMap< T, N >::operator[] (size_t which) inline
Referenced by ct::rbd::RBDDataMap< bool, NEE >::RBDDataMap().
template<typename T , size_t N> const T & ct::rbd::RBDDataMap< T, N >::operator[] (size_t which) const inline
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/robot/kinematics/RBDDataMap.h