ct::rbd::JointAcceleration< NJOINTS, SCALAR > Class Template Reference
ct::rbd::JointAcceleration< NJOINTS, SCALAR > Class Template Reference
State
joint acceleration
#include <JointAcceleration.h>
Public Types
enum NDOFS { NDOFS = NJOINTS }
typedef Eigen::Matrix< SCALAR, NJOINTS, 1 > Acceleration
Public Member Functions
JointAcceleration ()
JointAcceleration (const Eigen::Matrix< SCALAR, NJOINTS, 1 > &acceleration)
size_t getSize ()
get number of degrees of freedom
SCALAR & operator() (size_t i)
get i-th joint acceleration
Eigen::Matrix< SCALAR, NJOINTS, 1 > & getAcceleration ()
get joint acceleration
const Eigen::Matrix< SCALAR, NJOINTS, 1 > & getAcceleration () const
get constant joint acceleration
void setAcceleration (const Eigen::Matrix< SCALAR, NJOINTS, 1 > &acceleration)
set joint acceleration
void setZero ()
set joint acceleration to zero
Static Public Member Functions
static JointAcceleration< NJOINTS, SCALAR > Zero ()
Protected Attributes
Acceleration acceleration_
Detailed Description
template<size_t NJOINTS, typename SCALAR = double>
class ct::rbd::JointAcceleration< NJOINTS, SCALAR >
joint acceleration
Member Typedef Documentation
Acceleration
template<size_t NJOINTS, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, NJOINTS, 1> ct::rbd::JointAcceleration< NJOINTS, SCALAR >::Acceleration
Member Enumeration Documentation
NDOFS
template<size_t NJOINTS, typename SCALAR = double> enum ct::rbd::JointAcceleration::NDOFS
Enumerator
NDOFS
Constructor & Destructor Documentation
JointAcceleration() [1/2]
template<size_t NJOINTS, typename SCALAR = double> ct::rbd::JointAcceleration< NJOINTS, SCALAR >::JointAcceleration () inline
References ct::rbd::JointAcceleration< NJOINTS, SCALAR >::setZero().
JointAcceleration() [2/2]
template<size_t NJOINTS, typename SCALAR = double> ct::rbd::JointAcceleration< NJOINTS, SCALAR >::JointAcceleration (const Eigen::Matrix< SCALAR, NJOINTS, 1 > & acceleration) inline
Member Function Documentation
getSize()
template<size_t NJOINTS, typename SCALAR = double> size_t ct::rbd::JointAcceleration< NJOINTS, SCALAR >::getSize () inline
get number of degrees of freedom
operator()()
template<size_t NJOINTS, typename SCALAR = double> SCALAR& ct::rbd::JointAcceleration< NJOINTS, SCALAR >::operator() (size_t i) inline
get i-th joint acceleration
References ct::rbd::JointAcceleration< NJOINTS, SCALAR >::acceleration_.
getAcceleration() [1/2]
template<size_t NJOINTS, typename SCALAR = double> Eigen::Matrix<SCALAR, NJOINTS, 1>& ct::rbd::JointAcceleration< NJOINTS, SCALAR >::getAcceleration () inline
get joint acceleration
References ct::rbd::JointAcceleration< NJOINTS, SCALAR >::acceleration_.
Referenced by ct::rbd::Dynamics< RBD, NEE >::FixBaseForwardDynamics(), ct::rbd::Dynamics< RBD, NEE >::FixBaseID(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseFullyActuatedID(), and ct::rbd::Dynamics< RBD, NEE >::FloatingBaseID().
getAcceleration() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const Eigen::Matrix<SCALAR, NJOINTS, 1>& ct::rbd::JointAcceleration< NJOINTS, SCALAR >::getAcceleration () const inline
get constant joint acceleration
References ct::rbd::JointAcceleration< NJOINTS, SCALAR >::acceleration_.
setAcceleration()
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::JointAcceleration< NJOINTS, SCALAR >::setAcceleration (const Eigen::Matrix< SCALAR, NJOINTS, 1 > & acceleration) inline
set joint acceleration
References ct::rbd::JointAcceleration< NJOINTS, SCALAR >::acceleration_.
setZero()
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::JointAcceleration< NJOINTS, SCALAR >::setZero () inline
set joint acceleration to zero
References ct::rbd::JointAcceleration< NJOINTS, SCALAR >::acceleration_.
Referenced by ct::rbd::JointAcceleration< NJOINTS, SCALAR >::JointAcceleration(), and ct::rbd::JointAcceleration< NJOINTS, SCALAR >::Zero().
Zero()
template<size_t NJOINTS, typename SCALAR = double> static JointAcceleration<NJOINTS, SCALAR> ct::rbd::JointAcceleration< NJOINTS, SCALAR >::Zero () inline static
References ct::rbd::JointAcceleration< NJOINTS, SCALAR >::setZero().
Referenced by ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::Zero().
Member Data Documentation
acceleration_
template<size_t NJOINTS, typename SCALAR = double> Acceleration ct::rbd::JointAcceleration< NJOINTS, SCALAR >::acceleration_ protected
Referenced by ct::rbd::JointAcceleration< NJOINTS, SCALAR >::getAcceleration(), ct::rbd::JointAcceleration< NJOINTS, SCALAR >::operator()(), ct::rbd::JointAcceleration< NJOINTS, SCALAR >::setAcceleration(), and ct::rbd::JointAcceleration< NJOINTS, SCALAR >::setZero().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/state/JointAcceleration.h