iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT > Class Template Reference
#include <inertia_properties.h>
Public Types
typedef iit::rbd::Core< Scalar > CoreS
typedef iit::rbd::tpl::InertiaMatrixDense< Scalar > IMatrix
typedef CoreS::Vector3 Vec3d
Public Member Functions
InertiaProperties ()
~InertiaProperties ()
const IMatrix & getTensor_trunk () const
const IMatrix & getTensor_LF_hipassembly () const
const IMatrix & getTensor_LF_upperleg () const
const IMatrix & getTensor_LF_lowerleg () const
const IMatrix & getTensor_RF_hipassembly () const
const IMatrix & getTensor_RF_upperleg () const
const IMatrix & getTensor_RF_lowerleg () const
const IMatrix & getTensor_LH_hipassembly () const
const IMatrix & getTensor_LH_upperleg () const
const IMatrix & getTensor_LH_lowerleg () const
const IMatrix & getTensor_RH_hipassembly () const
const IMatrix & getTensor_RH_upperleg () const
const IMatrix & getTensor_RH_lowerleg () const
Scalar getMass_trunk () const
Scalar getMass_LF_hipassembly () const
Scalar getMass_LF_upperleg () const
Scalar getMass_LF_lowerleg () const
Scalar getMass_RF_hipassembly () const
Scalar getMass_RF_upperleg () const
Scalar getMass_RF_lowerleg () const
Scalar getMass_LH_hipassembly () const
Scalar getMass_LH_upperleg () const
Scalar getMass_LH_lowerleg () const
Scalar getMass_RH_hipassembly () const
Scalar getMass_RH_upperleg () const
Scalar getMass_RH_lowerleg () const
const Vec3d & getCOM_trunk () const
const Vec3d & getCOM_LF_hipassembly () const
const Vec3d & getCOM_LF_upperleg () const
const Vec3d & getCOM_LF_lowerleg () const
const Vec3d & getCOM_RF_hipassembly () const
const Vec3d & getCOM_RF_upperleg () const
const Vec3d & getCOM_RF_lowerleg () const
const Vec3d & getCOM_LH_hipassembly () const
const Vec3d & getCOM_LH_upperleg () const
const Vec3d & getCOM_LH_lowerleg () const
const Vec3d & getCOM_RH_hipassembly () const
const Vec3d & getCOM_RH_upperleg () const
const Vec3d & getCOM_RH_lowerleg () const
Scalar getTotalMass () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar Scalar
Member Typedef Documentation
CoreS
template<typename TRAIT> typedef iit::rbd::Core<Scalar> iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::CoreS
IMatrix
template<typename TRAIT> typedef iit::rbd::tpl::InertiaMatrixDense<Scalar> iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::IMatrix
Vec3d
template<typename TRAIT> typedef CoreS::Vector3 iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::Vec3d
Constructor & Destructor Documentation
InertiaProperties()
template<typename TRAIT > iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::InertiaProperties ()
~InertiaProperties()
template<typename TRAIT > iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::~InertiaProperties () inline
Member Function Documentation
getTensor_trunk()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_trunk () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_LF_hipassembly()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_LF_hipassembly () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_LF_upperleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_LF_upperleg () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_LF_lowerleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_LF_lowerleg () const inline
getTensor_RF_hipassembly()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_RF_hipassembly () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_RF_upperleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_RF_upperleg () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_RF_lowerleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_RF_lowerleg () const inline
getTensor_LH_hipassembly()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_LH_hipassembly () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_LH_upperleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_LH_upperleg () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_LH_lowerleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_LH_lowerleg () const inline
getTensor_RH_hipassembly()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_RH_hipassembly () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_RH_upperleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_RH_upperleg () const inline
Referenced by iit::TestHyQ::dyn::tpl::JSIM< TRAIT >::update().
getTensor_RH_lowerleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::IMatrix & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTensor_RH_lowerleg () const inline
getMass_trunk()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_trunk () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_LF_hipassembly()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LF_hipassembly () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_LF_upperleg()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LF_upperleg () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_LF_lowerleg()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LF_lowerleg () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_RF_hipassembly()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RF_hipassembly () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_RF_upperleg()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RF_upperleg () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_RF_lowerleg()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RF_lowerleg () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_LH_hipassembly()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LH_hipassembly () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_LH_upperleg()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LH_upperleg () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_LH_lowerleg()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LH_lowerleg () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_RH_hipassembly()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RH_hipassembly () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_RH_upperleg()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RH_upperleg () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getMass_RH_lowerleg()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RH_lowerleg () const inline
References iit::rbd::tpl::InertiaMatrixDense< SCALAR >::getMass().
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_trunk()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_trunk () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_LF_hipassembly()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LF_hipassembly () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_LF_upperleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LF_upperleg () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_LF_lowerleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LF_lowerleg () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_RF_hipassembly()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RF_hipassembly () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_RF_upperleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RF_upperleg () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_RF_lowerleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RF_lowerleg () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_LH_hipassembly()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LH_hipassembly () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_LH_upperleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LH_upperleg () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_LH_lowerleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LH_lowerleg () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_RH_hipassembly()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RH_hipassembly () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_RH_upperleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RH_upperleg () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getCOM_RH_lowerleg()
template<typename TRAIT > const InertiaProperties< TRAIT >::Vec3d & iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RH_lowerleg () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
getTotalMass()
template<typename TRAIT > InertiaProperties< TRAIT >::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTotalMass () const inline
Referenced by iit::TestHyQ::getWholeBodyCOM().
Member Data Documentation
Scalar
template<typename TRAIT> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef TRAIT::Scalar iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::Scalar
The documentation for this class was generated from the following files:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testhyq/generated/inertia_properties.h
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testhyq/generated/inertia_properties.impl.h