iit::TestHyQ::LinkDataMap< T > Class Template Reference
iit::TestHyQ::LinkDataMap< T > Class Template Reference
#include <link_data_map.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW LinkDataMap ()
LinkDataMap (const T &defaultValue)
LinkDataMap (const LinkDataMap &rhs)
LinkDataMap & operator= (const LinkDataMap &rhs)
LinkDataMap & operator= (const T &rhs)
T & operator[] (LinkIdentifiers which)
const T & operator[] (LinkIdentifiers which) const
Detailed Description
template<typename T>
class iit::TestHyQ::LinkDataMap< T >
A very simple container to associate a generic data item to each link
Constructor & Destructor Documentation
LinkDataMap() [1/3]
template<typename T > EIGEN_MAKE_ALIGNED_OPERATOR_NEW iit::TestHyQ::LinkDataMap< T >::LinkDataMap () inline
References iit::TestHyQ::LinkDataMap< T >::operator=(), and iit::TestHyQ::LinkDataMap< T >::operator[]().
LinkDataMap() [2/3]
template<typename T > iit::TestHyQ::LinkDataMap< T >::LinkDataMap (const T & defaultValue) inline
LinkDataMap() [3/3]
template<typename T > iit::TestHyQ::LinkDataMap< T >::LinkDataMap (const LinkDataMap< T > & rhs) inline
Member Function Documentation
operator=() [1/2]
template<typename T > LinkDataMap< T > & iit::TestHyQ::LinkDataMap< T >::operator= (const LinkDataMap< T > & rhs) inline
Referenced by iit::TestHyQ::LinkDataMap< T >::LinkDataMap().
operator=() [2/2]
template<typename T > LinkDataMap< T > & iit::TestHyQ::LinkDataMap< T >::operator= (const T & rhs) inline
operator[]() [1/2]
template<typename T > T & iit::TestHyQ::LinkDataMap< T >::operator[] (LinkIdentifiers which) inline
Referenced by iit::TestHyQ::LinkDataMap< T >::LinkDataMap().
operator[]() [2/2]
template<typename T > const T & iit::TestHyQ::LinkDataMap< T >::operator[] (LinkIdentifiers which) const inline
References iit::TestHyQ::LF_HIPASSEMBLY, iit::TestHyQ::LF_LOWERLEG, iit::TestHyQ::LF_UPPERLEG, iit::TestHyQ::LH_HIPASSEMBLY, iit::TestHyQ::LH_LOWERLEG, iit::TestHyQ::LH_UPPERLEG, iit::TestHyQ::RF_HIPASSEMBLY, iit::TestHyQ::RF_LOWERLEG, iit::TestHyQ::RF_UPPERLEG, iit::TestHyQ::RH_HIPASSEMBLY, iit::TestHyQ::RH_LOWERLEG, iit::TestHyQ::RH_UPPERLEG, and iit::TestHyQ::TRUNK.
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testhyq/generated/link_data_map.h