ct::rbd::RBDState< NJOINTS, SCALAR > Class Template Reference
ct::rbd::RBDState< NJOINTS, SCALAR > Class Template Reference
State
joint states and base states
#include <RBDState.h>
Public Types
using RigidBodyState_t = tpl::RigidBodyState< SCALAR >
using RigidBodyPose_t = tpl::RigidBodyPose< SCALAR >
typedef ct::core::StateVector< NSTATE_QUAT, SCALAR > state_vector_quat_t
typedef ct::core::StateVector< NSTATE, SCALAR > state_vector_euler_t
typedef ct::core::StateVector< NDOF, SCALAR > coordinate_vector_t
Public Member Functions
RBDState (typename RigidBodyPose_t::STORAGE_TYPE storage=RigidBodyPose_t::EULER)
RBDState (const RBDState &other)
RBDState (const RigidBodyState_t &baseState, const JointState< NJOINTS, SCALAR > &jointState)
virtual ~RBDState ()=default
bool operator!= (const RBDState &other) const
bool isApprox (const RBDState &rhs, const SCALAR &tol=1e-10)
RigidBodyState_t & base ()
get base states
const RigidBodyState_t & base () const
get constant base states
RigidBodyPose_t & basePose ()
get base pose
const RigidBodyPose_t & basePose () const
get constant base states
tpl::RigidBodyVelocities< SCALAR > & baseVelocities ()
get base velocities
const tpl::RigidBodyVelocities< SCALAR > & baseVelocities () const
get constant base velocities
kindr::LocalAngularVelocity< SCALAR > & baseLocalAngularVelocity ()
get base local angular velocity
const kindr::LocalAngularVelocity< SCALAR > & baseLocalAngularVelocity () const
get constant base local angular velocity
kindr::Velocity< SCALAR, 3 > & baseLinearVelocity ()
get base linear velocity
const kindr::Velocity< SCALAR, 3 > & baseLinearVelocity () const
get constant base local angular velocity
JointState< NJOINTS, SCALAR > & joints ()
get joint states
const JointState< NJOINTS, SCALAR > & joints () const
get constant joint states
JointState< NJOINTS, SCALAR >::JointPositionBlock jointPositions ()
get joint positions
const JointState< NJOINTS, SCALAR >::JointPositionBlockConst jointPositions () const
get constant joint positions
JointState< NJOINTS, SCALAR >::JointPositionBlock jointVelocities ()
get joint velocities
const JointState< NJOINTS, SCALAR >::JointPositionBlockConst jointVelocities () const
get constant joint velocities
state_vector_quat_t toStateVectorQuaternion () const
coordinate_vector_t toCoordinatePositionUnique () const
coordinate_vector_t toCoordinatePosition () const
coordinate_vector_t toCoordinateVelocity () const
state_vector_euler_t toStateVectorEulerXyzUnique () const
state_vector_euler_t toStateVectorEulerXyz () const
void fromStateVectorQuaternion (const state_vector_quat_t &state)
void fromStateVectorEulerXyz (const state_vector_euler_t &state)
void fromStateVectorRaw (const state_vector_quat_t &state)
void fromStateVectorRaw (const state_vector_euler_t &state)
virtual void setDefault ()
void setZero ()
void setRandom ()
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t NDOF = NJOINTS + 6
static const size_t NSTATE = 2 * (NJOINTS + 6)
static const size_t NSTATE_QUAT = NSTATE + 1
Protected Attributes
RigidBodyState_t baseState_
JointState< NJOINTS, SCALAR > jointState_
Detailed Description
template<size_t NJOINTS, typename SCALAR = double>
class ct::rbd::RBDState< NJOINTS, SCALAR >
joint states and base states
Member Typedef Documentation
RigidBodyState_t
template<size_t NJOINTS, typename SCALAR = double> using ct::rbd::RBDState< NJOINTS, SCALAR >::RigidBodyState_t = tpl::RigidBodyState<SCALAR>
RigidBodyPose_t
template<size_t NJOINTS, typename SCALAR = double> using ct::rbd::RBDState< NJOINTS, SCALAR >::RigidBodyPose_t = tpl::RigidBodyPose<SCALAR>
state_vector_quat_t
template<size_t NJOINTS, typename SCALAR = double> typedef ct::core::StateVector<NSTATE_QUAT, SCALAR> ct::rbd::RBDState< NJOINTS, SCALAR >::state_vector_quat_t
state_vector_euler_t
template<size_t NJOINTS, typename SCALAR = double> typedef ct::core::StateVector<NSTATE, SCALAR> ct::rbd::RBDState< NJOINTS, SCALAR >::state_vector_euler_t
coordinate_vector_t
template<size_t NJOINTS, typename SCALAR = double> typedef ct::core::StateVector<NDOF, SCALAR> ct::rbd::RBDState< NJOINTS, SCALAR >::coordinate_vector_t
Constructor & Destructor Documentation
RBDState() [1/3]
template<size_t NJOINTS, typename SCALAR = double> ct::rbd::RBDState< NJOINTS, SCALAR >::RBDState (typename RigidBodyPose_t::STORAGE_TYPE storage = RigidBodyPose_t::EULER) inline
RBDState() [2/3]
template<size_t NJOINTS, typename SCALAR = double> ct::rbd::RBDState< NJOINTS, SCALAR >::RBDState (const RBDState< NJOINTS, SCALAR > & other) inline
RBDState() [3/3]
template<size_t NJOINTS, typename SCALAR = double> ct::rbd::RBDState< NJOINTS, SCALAR >::RBDState (const RigidBodyState_t & baseState, const JointState< NJOINTS, SCALAR > & jointState) inline
~RBDState()
template<size_t NJOINTS, typename SCALAR = double> virtual ct::rbd::RBDState< NJOINTS, SCALAR >::~RBDState () virtual default
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::RBDState().
Member Function Documentation
operator!=()
template<size_t NJOINTS, typename SCALAR = double> bool ct::rbd::RBDState< NJOINTS, SCALAR >::operator!= (const RBDState< NJOINTS, SCALAR > & other) const inline
isApprox()
template<size_t NJOINTS, typename SCALAR = double> bool ct::rbd::RBDState< NJOINTS, SCALAR >::isApprox (const RBDState< NJOINTS, SCALAR > & rhs, const SCALAR & tol = 1e-10) inline
Referenced by TEST().
base() [1/2]
template<size_t NJOINTS, typename SCALAR = double> RigidBodyState_t& ct::rbd::RBDState< NJOINTS, SCALAR >::base () inline
get base states
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::baseLinearVelocity(), ct::rbd::RBDState< NJOINTS, Scalar >::baseLocalAngularVelocity(), ct::rbd::RBDState< NJOINTS, Scalar >::basePose(), ct::rbd::RBDState< NJOINTS, Scalar >::baseVelocities(), ct::rbd::IDControllerFB< Dynamics >::computeDesiredAcceleration(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorQuaternion(), ct::rbd::Kinematics< RBD, NEE >::getEEVelocityInBase(), ct::rbd::Kinematics< RBD, NEE >::getEEVelocityInWorld(), ct::rbd::RBDState< NJOINTS, Scalar >::isApprox(), ct::rbd::RBDState< NJOINTS, Scalar >::operator!=(), testFunctionRBDState(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinatePosition(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinatePositionUnique(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinateVelocity(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion(), and ct::rbd::RBDState< NJOINTS, Scalar >::toStateVectorQuaternion().
base() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const RigidBodyState_t& ct::rbd::RBDState< NJOINTS, SCALAR >::base () const inline
get constant base states
basePose() [1/2]
template<size_t NJOINTS, typename SCALAR = double> RigidBodyPose_t& ct::rbd::RBDState< NJOINTS, SCALAR >::basePose () inline
get base pose
Referenced by ct::rbd::EEContactModel< Kinematics >::computeContactForces(), ct::rbd::IDControllerFB< Dynamics >::computeDesiredAcceleration(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::evaluate(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseForwardDynamics(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseFullyActuatedID(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseID(), ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedDynamics(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::rbdStateFromVector(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::stateDerivative(), TEST(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toRBDState(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion(), and ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::update().
basePose() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const RigidBodyPose_t& ct::rbd::RBDState< NJOINTS, SCALAR >::basePose () const inline
get constant base states
baseVelocities() [1/2]
template<size_t NJOINTS, typename SCALAR = double> tpl::RigidBodyVelocities<SCALAR>& ct::rbd::RBDState< NJOINTS, SCALAR >::baseVelocities () inline
get base velocities
Referenced by ct::rbd::Dynamics< RBD, NEE >::FloatingBaseForwardDynamics(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseFullyActuatedID(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseID(), ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedDynamics(), and TEST().
baseVelocities() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const tpl::RigidBodyVelocities<SCALAR>& ct::rbd::RBDState< NJOINTS, SCALAR >::baseVelocities () const inline
get constant base velocities
baseLocalAngularVelocity() [1/2]
template<size_t NJOINTS, typename SCALAR = double> kindr::LocalAngularVelocity<SCALAR>& ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity () inline
get base local angular velocity
Referenced by ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedDynamics(), TEST(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion(), and ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::update().
baseLocalAngularVelocity() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const kindr::LocalAngularVelocity<SCALAR>& ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity () const inline
get constant base local angular velocity
baseLinearVelocity() [1/2]
template<size_t NJOINTS, typename SCALAR = double> kindr::Velocity<SCALAR, 3>& ct::rbd::RBDState< NJOINTS, SCALAR >::baseLinearVelocity () inline
get base linear velocity
Referenced by TEST(), and ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::update().
baseLinearVelocity() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const kindr::Velocity<SCALAR, 3>& ct::rbd::RBDState< NJOINTS, SCALAR >::baseLinearVelocity () const inline
get constant base local angular velocity
joints() [1/2]
template<size_t NJOINTS, typename SCALAR = double> JointState<NJOINTS, SCALAR>& ct::rbd::RBDState< NJOINTS, SCALAR >::joints () inline
get joint states
Referenced by ct::rbd::WholeBodyController< NJOINTS >::computeControl(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseForwardDynamics(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseFullyActuatedID(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseID(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorQuaternion(), ct::rbd::RBDState< NJOINTS, Scalar >::isApprox(), ct::rbd::RBDState< NJOINTS, Scalar >::jointPositions(), ct::rbd::RBDState< NJOINTS, Scalar >::jointVelocities(), ct::rbd::RBDState< NJOINTS, Scalar >::operator!=(), ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedDynamics(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::rbdStateFromVector(), testFunctionRBDState(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinatePosition(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinatePositionUnique(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinateVelocity(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toRBDState(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion(), and ct::rbd::RBDState< NJOINTS, Scalar >::toStateVectorQuaternion().
joints() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const JointState<NJOINTS, SCALAR>& ct::rbd::RBDState< NJOINTS, SCALAR >::joints () const inline
get constant joint states
jointPositions() [1/2]
template<size_t NJOINTS, typename SCALAR = double> JointState<NJOINTS, SCALAR>::JointPositionBlock ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions () inline
get joint positions
Referenced by ct::rbd::EEContactModel< Kinematics >::computeContactForces(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::evaluate(), ct::rbd::Kinematics< RBD, NEE >::getEEVelocityInBase(), ct::rbd::Kinematics< RBD, NEE >::getJacobianBaseEEbyId(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::stateDerivative(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::stateSecondDerivative(), TEST(), and ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::update().
jointPositions() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const JointState<NJOINTS, SCALAR>::JointPositionBlockConst ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions () const inline
get constant joint positions
jointVelocities() [1/2]
template<size_t NJOINTS, typename SCALAR = double> JointState<NJOINTS, SCALAR>::JointPositionBlock ct::rbd::RBDState< NJOINTS, SCALAR >::jointVelocities () inline
get joint velocities
Referenced by ct::rbd::Kinematics< RBD, NEE >::getEEVelocityInBase(), TEST(), and ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::update().
jointVelocities() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const JointState<NJOINTS, SCALAR>::JointPositionBlockConst ct::rbd::RBDState< NJOINTS, SCALAR >::jointVelocities () const inline
get constant joint velocities
toStateVectorQuaternion()
template<size_t NJOINTS, typename SCALAR = double> state_vector_quat_t ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorQuaternion () const inline
Referenced by TEST(), and ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVectorQuaternion().
toCoordinatePositionUnique()
template<size_t NJOINTS, typename SCALAR = double> coordinate_vector_t ct::rbd::RBDState< NJOINTS, SCALAR >::toCoordinatePositionUnique () const inline
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::toStateVectorEulerXyzUnique().
toCoordinatePosition()
template<size_t NJOINTS, typename SCALAR = double> coordinate_vector_t ct::rbd::RBDState< NJOINTS, SCALAR >::toCoordinatePosition () const inline
Referenced by ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >::getPositions(), and ct::rbd::RBDState< NJOINTS, Scalar >::toStateVectorEulerXyz().
toCoordinateVelocity()
template<size_t NJOINTS, typename SCALAR = double> coordinate_vector_t ct::rbd::RBDState< NJOINTS, SCALAR >::toCoordinateVelocity () const inline
Referenced by ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >::getAccelerations(), ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >::getVelocities(), ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedDynamics(), ct::rbd::RBDState< NJOINTS, Scalar >::toStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, Scalar >::toStateVectorEulerXyzUnique(), and ct::rbd::OperationalModel< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::update().
toStateVectorEulerXyzUnique()
template<size_t NJOINTS, typename SCALAR = double> state_vector_euler_t ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorEulerXyzUnique () const inline
Referenced by TEST(), and ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVectorEulerXyzUnique().
toStateVectorEulerXyz()
template<size_t NJOINTS, typename SCALAR = double> state_vector_euler_t ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorEulerXyz () const inline
Referenced by TEST(), testFunctionRBDState(), and ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVectorEulerXyz().
fromStateVectorQuaternion()
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorQuaternion (const state_vector_quat_t & state) inline
Referenced by ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVectorQuaternion(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorRaw(), and TEST().
fromStateVectorEulerXyz()
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorEulerXyz (const state_vector_euler_t & state) inline
Referenced by ct::rbd::WholeBodyController< NJOINTS >::computeControl(), ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorRaw(), and TEST().
fromStateVectorRaw() [1/2]
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorRaw (const state_vector_quat_t & state) inline
fromStateVectorRaw() [2/2]
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorRaw (const state_vector_euler_t & state) inline
setDefault()
template<size_t NJOINTS, typename SCALAR = double> virtual void ct::rbd::RBDState< NJOINTS, SCALAR >::setDefault () inline virtual
setZero()
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::RBDState< NJOINTS, SCALAR >::setZero () inline
Referenced by ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::rbdStateFromVector(), ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::setZero(), TEST(), and ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toRBDState().
setRandom()
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom () inline
Referenced by TEST().
Member Data Documentation
NDOF
template<size_t NJOINTS, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW const size_t ct::rbd::RBDState< NJOINTS, SCALAR >::NDOF = NJOINTS + 6 static
NSTATE
template<size_t NJOINTS, typename SCALAR = double> const size_t ct::rbd::RBDState< NJOINTS, SCALAR >::NSTATE = 2 * (NJOINTS + 6) static
Referenced by ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVectorEulerXyz().
NSTATE_QUAT
template<size_t NJOINTS, typename SCALAR = double> const size_t ct::rbd::RBDState< NJOINTS, SCALAR >::NSTATE_QUAT = NSTATE + 1 static
Referenced by ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVectorQuaternion().
baseState_
template<size_t NJOINTS, typename SCALAR = double> RigidBodyState_t ct::rbd::RBDState< NJOINTS, SCALAR >::baseState_ protected
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::base(), ct::rbd::RBDState< NJOINTS, Scalar >::RBDState(), ct::rbd::RBDState< NJOINTS, Scalar >::setDefault(), ct::rbd::RBDState< NJOINTS, Scalar >::setRandom(), and ct::rbd::RBDState< NJOINTS, Scalar >::setZero().
jointState_
template<size_t NJOINTS, typename SCALAR = double> JointState<NJOINTS, SCALAR> ct::rbd::RBDState< NJOINTS, SCALAR >::jointState_ protected
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::joints(), ct::rbd::RBDState< NJOINTS, Scalar >::RBDState(), ct::rbd::RBDState< NJOINTS, Scalar >::setDefault(), ct::rbd::RBDState< NJOINTS, Scalar >::setRandom(), and ct::rbd::RBDState< NJOINTS, Scalar >::setZero().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/state/RBDState.h