ct::rbd::tpl::RigidBodyAcceleration< SCALAR > Class Template Reference
ct::rbd::tpl::RigidBodyAcceleration< SCALAR > Class Template Reference
State
acceleration of a rigid body
#include <RigidBodyAcceleration.h>
Public Types
typedef kindr::AngularAcceleration< SCALAR, 3 > AngularAcceleration
Public Member Functions
RigidBodyAcceleration ()
RigidBodyAcceleration (LinearAcceleration &transAcceleration, AngularAcceleration &anglAcceleration)
RigidBodyAcceleration (const Eigen::Matrix< SCALAR, 6, 1 > &in)
void fromVector6d (const Eigen::Matrix< SCALAR, 6, 1 > &in)
const Eigen::Matrix< SCALAR, 6, 1 > getVector6d () const
LinearAcceleration & getTranslationalAcceleration ()
get translatory acceleration
const LinearAcceleration & getTranslationalAcceleration () const
get constant translatory acceleration
AngularAcceleration & getAngularAcceleration ()
get angular acceleration
const AngularAcceleration & getAngularAcceleration () const
get constant angular acceleration
Eigen::Matrix< SCALAR, 6, 1 > accelerations ()
get accelerations as a "Twist"
void setTranslatoryAcceleration (LinearAcceleration &transAcceleration)
set translatory acceleration
void setAngularAcceleration (AngularAcceleration &anglAcceleration)
set angular acceleration
void setZero ()
set acceleration to zero
Static Public Member Functions
static RigidBodyAcceleration Zero ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef kindr::Acceleration< SCALAR, 3 > LinearAcceleration
Protected Attributes
AngularAcceleration anglAcceleration_
LinearAcceleration transAcceleration_
Detailed Description
template<typename SCALAR>
class ct::rbd::tpl::RigidBodyAcceleration< SCALAR >
acceleration of a rigid body
Member Typedef Documentation
AngularAcceleration
template<typename SCALAR > typedef kindr::AngularAcceleration<SCALAR, 3> ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::AngularAcceleration
Constructor & Destructor Documentation
RigidBodyAcceleration() [1/3]
template<typename SCALAR > ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::RigidBodyAcceleration () inline
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setZero().
RigidBodyAcceleration() [2/3]
template<typename SCALAR > ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::RigidBodyAcceleration (LinearAcceleration & transAcceleration, AngularAcceleration & anglAcceleration) inline
RigidBodyAcceleration() [3/3]
template<typename SCALAR > ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::RigidBodyAcceleration (const Eigen::Matrix< SCALAR, 6, 1 > & in) inline
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::fromVector6d().
Member Function Documentation
fromVector6d()
template<typename SCALAR > void ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::fromVector6d (const Eigen::Matrix< SCALAR, 6, 1 > & in) inline
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::anglAcceleration_, and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::transAcceleration_.
Referenced by ct::rbd::IDControllerFB< Dynamics >::computeDesiredAcceleration(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseForwardDynamics(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseID(), ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedForwardDynamics(), and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::RigidBodyAcceleration().
getVector6d()
template<typename SCALAR > const Eigen::Matrix<SCALAR, 6, 1> ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getVector6d () const inline
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::anglAcceleration_, and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::transAcceleration_.
getTranslationalAcceleration() [1/2]
template<typename SCALAR > LinearAcceleration& ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getTranslationalAcceleration () inline
get translatory acceleration
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::transAcceleration_.
Referenced by ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toCoordinateAcceleration(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz(), and ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion().
getTranslationalAcceleration() [2/2]
template<typename SCALAR > const LinearAcceleration& ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getTranslationalAcceleration () const inline
get constant translatory acceleration
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::transAcceleration_.
getAngularAcceleration() [1/2]
template<typename SCALAR > AngularAcceleration& ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getAngularAcceleration () inline
get angular acceleration
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::anglAcceleration_.
Referenced by ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toCoordinateAcceleration(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz(), and ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion().
getAngularAcceleration() [2/2]
template<typename SCALAR > const AngularAcceleration& ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getAngularAcceleration () const inline
get constant angular acceleration
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::anglAcceleration_.
accelerations()
template<typename SCALAR > Eigen::Matrix<SCALAR, 6, 1> ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::accelerations () inline
get accelerations as a "Twist"
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::anglAcceleration_, and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::transAcceleration_.
setTranslatoryAcceleration()
template<typename SCALAR > void ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setTranslatoryAcceleration (LinearAcceleration & transAcceleration) inline
set translatory acceleration
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::transAcceleration_.
setAngularAcceleration()
template<typename SCALAR > void ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setAngularAcceleration (AngularAcceleration & anglAcceleration) inline
set angular acceleration
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::anglAcceleration_.
setZero()
template<typename SCALAR > void ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setZero () inline
set acceleration to zero
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::anglAcceleration_, ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::LinearAcceleration, and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::transAcceleration_.
Referenced by ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::RigidBodyAcceleration(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::setZero(), and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::Zero().
Zero()
template<typename SCALAR > static RigidBodyAcceleration ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::Zero () inline static
References ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setZero().
Referenced by ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::Zero().
Member Data Documentation
LinearAcceleration
template<typename SCALAR > EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef kindr::Acceleration<SCALAR, 3> ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::LinearAcceleration
Referenced by ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setZero().
anglAcceleration_
template<typename SCALAR > AngularAcceleration ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::anglAcceleration_ protected
Referenced by ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::accelerations(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::fromVector6d(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getAngularAcceleration(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getVector6d(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setAngularAcceleration(), and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setZero().
transAcceleration_
template<typename SCALAR > LinearAcceleration ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::transAcceleration_ protected
Referenced by ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::accelerations(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::fromVector6d(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getTranslationalAcceleration(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getVector6d(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setTranslatoryAcceleration(), and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setZero().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/state/RigidBodyAcceleration.h