iit::testirb4600::JointDataMap< T > Class Template Reference
iit::testirb4600::JointDataMap< T > Class Template Reference
#include <joint_data_map.h>
Public Member Functions
JointDataMap ()
JointDataMap (const T &defaultValue)
JointDataMap (const JointDataMap &rhs)
JointDataMap & operator= (const JointDataMap &rhs)
JointDataMap & operator= (const T &rhs)
T & operator[] (JointIdentifiers which)
const T & operator[] (JointIdentifiers which) const
Detailed Description
template<typename T>
class iit::testirb4600::JointDataMap< T >
A very simple container to associate a generic data item to each joint
Constructor & Destructor Documentation
JointDataMap() [1/3]
template<typename T > iit::testirb4600::JointDataMap< T >::JointDataMap () inline
References iit::testirb4600::JointDataMap< T >::operator=(), and iit::testirb4600::JointDataMap< T >::operator[]().
JointDataMap() [2/3]
template<typename T > iit::testirb4600::JointDataMap< T >::JointDataMap (const T & defaultValue) inline
JointDataMap() [3/3]
template<typename T > iit::testirb4600::JointDataMap< T >::JointDataMap (const JointDataMap< T > & rhs) inline
Member Function Documentation
operator=() [1/2]
template<typename T > JointDataMap< T > & iit::testirb4600::JointDataMap< T >::operator= (const JointDataMap< T > & rhs) inline
Referenced by iit::testirb4600::JointDataMap< T >::JointDataMap().
operator=() [2/2]
template<typename T > JointDataMap< T > & iit::testirb4600::JointDataMap< T >::operator= (const T & rhs) inline
operator[]() [1/2]
template<typename T > T & iit::testirb4600::JointDataMap< T >::operator[] (JointIdentifiers which) inline
Referenced by iit::testirb4600::JointDataMap< T >::JointDataMap().
operator[]() [2/2]
template<typename T > const T & iit::testirb4600::JointDataMap< T >::operator[] (JointIdentifiers which) const inline
References iit::testirb4600::JA, iit::testirb4600::JB, iit::testirb4600::JC, iit::testirb4600::JD, iit::testirb4600::JE, and iit::testirb4600::JF.
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testIrb4600/generated/joint_data_map.h