ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR > Class Template Reference
ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR > Class Template Reference
State
whole fix base robot state, i.e. Joint state, Actuator Dynamics (and fix-base pose)
#include <FixBaseRobotState.h>
Public Types
using RigidBodyPose_t = tpl::RigidBodyPose< SCALAR >
using JointState_t = JointState< NJOINTS, SCALAR >
using RBDState_t = RBDState< NJOINTS, SCALAR >
using actuator_state_vector_t = ct::core::StateVector< ACT_STATE_DIM, SCALAR >
using state_vector_t = ct::core::StateVector< NSTATE, SCALAR >
Public Member Functions
FixBaseRobotState ()
constructor
FixBaseRobotState (const JointState_t &joints, const actuator_state_vector_t &actState=actuator_state_vector_t::Zero())
constructor
FixBaseRobotState (const state_vector_t &robotState)
constructor
FixBaseRobotState (const FixBaseRobotState &other)
constructor
~FixBaseRobotState ()
destructor
actuator_state_vector_t & actuatorState ()
accessor to actuator state
const actuator_state_vector_t & actuatorState () const
accessor to actuator state
SCALAR & actuatorState (size_t i)
accessor to single element of actuator state
const SCALAR & actuatorState (size_t i) const
accessor to single element of actuator state
JointState_t & joints ()
accessor to joint state
const JointState_t & joints () const
accessor to joint state
void setZero ()
template<typename T = void>
std::enable_if<(ACT_STATE_DIM==0), T >::type fromStateVector (const state_vector_t &robotState)
conversion from dense state vector to a RobotState
template<typename T = void>
std::enable_if<(ACT_STATE_DIM > 0), T >::type fromStateVector (const state_vector_t &robotState)
template<typename T = state_vector_t>
std::enable_if<(ACT_STATE_DIM==0), T >::type toStateVector () const
conversion from RobotState to dense state vector
template<typename T = state_vector_t>
std::enable_if<(ACT_STATE_DIM > 0), T >::type toStateVector () const
RBDState_t toRBDState (const RigidBodyPose_t &basePose=RigidBodyPose_t())
transform full robot state to RBDState
Static Public Member Functions
static const JointState_t jointStateFromVector (const state_vector_t &robotState)
full state vector to JointState (static)
static const RBDState_t rbdStateFromVector (const state_vector_t &robotState, const RigidBodyPose_t &basePose=RigidBodyPose_t())
transform full robot state to RBDState (static)
static const actuator_state_vector_t actuatorStateFromVector (const state_vector_t &robotState)
transform full robot state to a actuator state (static)
static const state_vector_t toFullState (const ct::core::StateVector< 2 *NJOINTS, SCALAR > &jointState, const actuator_state_vector_t &x_act=actuator_state_vector_t::Zero())
transform from joint and actuator state to full state
Static Public Attributes
static const size_t NDOF = NJOINTS
static const size_t NSTATE = 2 * NJOINTS + ACT_STATE_DIM
Protected Attributes
JointState_t joints_
the joint state
actuator_state_vector_t act_state_
the actuator state vector
Detailed Description
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double>
class ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >
whole fix base robot state, i.e. Joint state, Actuator Dynamics (and fix-base pose)
Note
a base pose is not included on purpose, since that would rather be part of the "output equation" than of the state
Parameters
NJOINTS the number of robot joints
ACT_STATE_DIM the state dimension of the actuator
SCALAR the scalar type
Member Typedef Documentation
RigidBodyPose_t
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> using ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::RigidBodyPose_t = tpl::RigidBodyPose<SCALAR>
JointState_t
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> using ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::JointState_t = JointState<NJOINTS, SCALAR>
RBDState_t
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> using ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::RBDState_t = RBDState<NJOINTS, SCALAR>
actuator_state_vector_t
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> using ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuator_state_vector_t = ct::core::StateVector<ACT_STATE_DIM, SCALAR>
state_vector_t
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> using ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::state_vector_t = ct::core::StateVector<NSTATE, SCALAR>
Constructor & Destructor Documentation
FixBaseRobotState() [1/4]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::FixBaseRobotState () inline
constructor
FixBaseRobotState() [2/4]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::FixBaseRobotState (const JointState_t & joints, const actuator_state_vector_t & actState = actuator_state_vector_t::Zero()) inline
constructor
FixBaseRobotState() [3/4]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::FixBaseRobotState (const state_vector_t & robotState) inline
constructor
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVector().
FixBaseRobotState() [4/4]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::FixBaseRobotState (const FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR > & other) inline
constructor
~FixBaseRobotState()
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::~FixBaseRobotState () inline
destructor
Member Function Documentation
jointStateFromVector()
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> static const JointState_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::jointStateFromVector (const state_vector_t & robotState) inline static
full state vector to JointState (static)
References ct::rbd::JointState< NJOINTS, SCALAR >::getPositions(), and ct::rbd::JointState< NJOINTS, SCALAR >::getVelocities().
Referenced by ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::rbdStateFromVector(), and TEST().
rbdStateFromVector()
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> static const RBDState_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::rbdStateFromVector (const state_vector_t & robotState, const RigidBodyPose_t & basePose = RigidBodyPose_t()) inline static
transform full robot state to RBDState (static)
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::RBDState< NJOINTS, SCALAR >::joints(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::jointStateFromVector(), and ct::rbd::RBDState< NJOINTS, SCALAR >::setZero().
actuatorStateFromVector()
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> static const actuator_state_vector_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuatorStateFromVector (const state_vector_t & robotState) inline static
transform full robot state to a actuator state (static)
Referenced by TEST().
toFullState()
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> static const state_vector_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toFullState (const ct::core::StateVector< 2 *NJOINTS, SCALAR > & jointState, const actuator_state_vector_t & x_act = actuator_state_vector_t::Zero()) inline static
transform from joint and actuator state to full state
actuatorState() [1/4]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> actuator_state_vector_t& ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuatorState () inline
accessor to actuator state
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::act_state_.
Referenced by ct::rbd::FixBaseFDSystem< RBDDynamics, ACT_STATE_DIM, EE_ARE_CONTROL_INPUTS >::computeActuatorDynamics(), and ct::rbd::FixBaseNLOC< FIX_BASE_FD_SYSTEM >::initializeDirectInterpolation().
actuatorState() [2/4]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> const actuator_state_vector_t& ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuatorState () const inline
accessor to actuator state
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::act_state_.
actuatorState() [3/4]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> SCALAR& ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuatorState (size_t i) inline
accessor to single element of actuator state
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::act_state_.
actuatorState() [4/4]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> const SCALAR& ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuatorState (size_t i) const inline
accessor to single element of actuator state
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::act_state_.
joints() [1/2]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> JointState_t& ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints () inline
accessor to joint state
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_.
Referenced by ct::rbd::FixBaseFDSystem< RBDDynamics, ACT_STATE_DIM, EE_ARE_CONTROL_INPUTS >::computeActuatorDynamics(), ct::rbd::FixBaseFDSystem< RBDDynamics, ACT_STATE_DIM, EE_ARE_CONTROL_INPUTS >::computeControlledDynamics(), ct::rbd::FixBaseNLOC< FIX_BASE_FD_SYSTEM >::initializeDirectInterpolation(), and ct::rbd::FixBaseNLOC< FIX_BASE_FD_SYSTEM >::initializeSteadyPose().
joints() [2/2]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> const JointState_t& ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints () const inline
accessor to joint state
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_.
setZero()
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> void ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::setZero () inline
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::act_state_, ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_, and ct::rbd::JointState< NJOINTS, SCALAR >::setZero().
fromStateVector() [1/2]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> template<typename T = void> std::enable_if<(ACT_STATE_DIM == 0), T>::type ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVector (const state_vector_t & robotState) inline
conversion from dense state vector to a RobotState
References ct::rbd::JointState< NJOINTS, SCALAR >::getPositions(), ct::rbd::JointState< NJOINTS, SCALAR >::getVelocities(), and ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_.
Referenced by ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::FixBaseRobotState().
fromStateVector() [2/2]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> template<typename T = void> std::enable_if<(ACT_STATE_DIM > 0), T>::type ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVector (const state_vector_t & robotState) inline
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::act_state_, ct::rbd::JointState< NJOINTS, SCALAR >::getPositions(), ct::rbd::JointState< NJOINTS, SCALAR >::getVelocities(), and ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_.
toStateVector() [1/2]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> template<typename T = state_vector_t> std::enable_if<(ACT_STATE_DIM == 0), T>::type ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVector () const inline
conversion from RobotState to dense state vector
References ct::rbd::JointState< NJOINTS, SCALAR >::getPositions(), ct::rbd::JointState< NJOINTS, SCALAR >::getVelocities(), and ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_.
Referenced by ct::rbd::FixBaseNLOC< FIX_BASE_FD_SYSTEM >::initializeDirectInterpolation(), and ct::rbd::FixBaseNLOC< FIX_BASE_FD_SYSTEM >::initializeSteadyPose().
toStateVector() [2/2]
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> template<typename T = state_vector_t> std::enable_if<(ACT_STATE_DIM > 0), T>::type ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVector () const inline
References ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::act_state_, ct::rbd::JointState< NJOINTS, SCALAR >::getPositions(), ct::rbd::JointState< NJOINTS, SCALAR >::getVelocities(), and ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_.
toRBDState()
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> RBDState_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toRBDState (const RigidBodyPose_t & basePose = RigidBodyPose_t()) inline
transform full robot state to RBDState
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::RBDState< NJOINTS, SCALAR >::joints(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_, and ct::rbd::RBDState< NJOINTS, SCALAR >::setZero().
Member Data Documentation
NDOF
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> const size_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::NDOF = NJOINTS static
NSTATE
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> const size_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::NSTATE = 2 * NJOINTS + ACT_STATE_DIM static
Referenced by TEST().
joints_
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> JointState_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints_ protected
the joint state
Referenced by ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVector(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::joints(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::setZero(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toRBDState(), and ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVector().
act_state_
template<size_t NJOINTS, size_t ACT_STATE_DIM = 0, typename SCALAR = double> actuator_state_vector_t ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::act_state_ protected
the actuator state vector
Referenced by ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuatorState(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVector(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::setZero(), and ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVector().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/state/FixBaseRobotState.h