ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR > Class Template Reference
ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR > Class Template Reference
OperationalSpace
This is a class for expressing the RBD equations of an articulated robot as an operational model. It uses the RBDContainer class as an interface to access the generated code for an articulated robot.
#include <OperationalModelRBD.h>
Public Types
typedef Eigen::Matrix< SCALAR, 3, 1 > Vector3s
typedef std::shared_ptr< OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS > > ptr
typedef OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS > Base
typedef Base::state_t state_t
Public Types inherited from ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >
typedef std::shared_ptr< OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS > > ptr
typedef CoordinateBase< NUM_OUTPUTS, NUM_JOINTS >::ptr coordinate_class_ptr_t
typedef OperationalJacobianBase< NUM_OUTPUTS, NUM_JOINTS >::ptr jacobian_class_ptr_t
typedef OperationalJacobianBase< NUM_OUTPUTS, NUM_JOINTS >::jacobian_t jacobian_t
typedef OperationalJacobianBase< NUM_OUTPUTS, NUM_JOINTS >::jacobian_inv_t jacobian_inv_t
typedef RBDState< NUM_JOINTS > state_t
typedef Eigen::Matrix< double, NUM_OUTPUTS, NUM_OUTPUTS > M_t
typedef Eigen::Matrix< double, NUM_OUTPUTS, 1 > C_t
typedef Eigen::Matrix< double, NUM_OUTPUTS, 1 > G_t
typedef Eigen::Matrix< double, NUM_JOINTS, NUM_OUTPUTS > S_t
typedef Eigen::Matrix< double, 3, NUM_OUTPUTS > Jc_t
Public Member Functions
OperationalModelRBD (const typename RBDContainer::Ptr_t &rbdContainerPtr, const std::array< EndEffector< NUM_JOINTS >, NUM_CONTACTPOINTS > &endEffectorArray)
~OperationalModelRBD ()
void update (const state_t &state) override
Public Member Functions inherited from ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >
OperationalModelBase (const jacobian_class_ptr_t &jacobianPtr=nullptr, const coordinate_class_ptr_t &coordinatePtr=nullptr)
virtual ~OperationalModelBase ()
const M_t & M () const
Get the inertia matrix: M.
const M_t & MInverse () const
Get the inertia matrix inverse: M^{-1}.
const C_t & C () const
Get the Coriolis force vector: C.
const G_t & G () const
Get the gravity force vector: G.
const S_t & S () const
Get the selection matrix: S.
const std::array< Jc_t, NUM_CONTACTPOINTS > & AllJc () const
Get all of the contact Jacobians: Jc.
const Jc_t & Jc (size_t i) const
Get the ith contact Jacobian: Jc[i].
Eigen::Matrix< double, NUM_OUTPUTS, 1 > getPositions ()
Get the coordinate position.
Eigen::Matrix< double, NUM_OUTPUTS, 1 > getVelocities ()
Get the coordinate velocity.
Eigen::Matrix< double, NUM_OUTPUTS, 1 > getAccelerations (Eigen::Matrix< double, NUM_JOINTS+6, 1 > qdd)
Get the coordinate acceleration.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix< SCALAR, 3, 3 > Matrix3s
Additional Inherited Members
Protected Attributes inherited from ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >
jacobian_class_ptr_t jacobianPtr_
coordinate_class_ptr_t coordinatePtr_
state_t state_
M_t M_
M_t MInverse_
C_t C_
G_t G_
S_t S_
std::array< Jc_t, NUM_CONTACTPOINTS > AllJc_
Detailed Description
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double>
class ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >
This is a class for expressing the RBD equations of an articulated robot as an operational model. It uses the RBDContainer class as an interface to access the generated code for an articulated robot.
Member Typedef Documentation
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, 3, 1> ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::Vector3s
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> typedef std::shared_ptr<OperationalModelRBD<RBDContainer, NUM_CONTACTPOINTS> > ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::ptr
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> typedef OperationalModelBase<NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS> ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::Base
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> typedef Base::state_t ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::state_t
Member Enumeration Documentation
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> anonymous enum
Enumerator
NUM_OUTPUTS
NUM_JOINTS
Constructor & Destructor Documentation
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::OperationalModelRBD (const typename RBDContainer::Ptr_t & rbdContainerPtr, const std::array< EndEffector< NUM_JOINTS >, NUM_CONTACTPOINTS > & endEffectorArray) inline
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::~OperationalModelRBD () inline
Member Function Documentation
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> void ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::update (const state_t & state) inline override virtual
This method updates the class member variables using the current state.
Parameters
state The current state
Implements ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >.
References ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::AllJc_, ct::rbd::RBDState< NJOINTS, SCALAR >::baseLinearVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::C_, ct::rbd::tpl::RigidBodyPose< SCALAR >::computeGravityB6D(), ct::rbd::tpl::FrameJacobian< NUM_JOINTS, SCALAR >::FromBaseJacToInertiaJacTranslation(), ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::G_, ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationMatrix(), ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), ct::rbd::RBDState< NJOINTS, SCALAR >::jointVelocities(), ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::M_, ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::MInverse_, ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::S_, and ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::state_.
Referenced by TEST().
Member Data Documentation
template<class RBDContainer, size_t NUM_CONTACTPOINTS, typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Eigen::Matrix<SCALAR, 3, 3> ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::Matrix3s
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/operationalSpace/rigid_body/OperationalModelRBD.h