iit::TestHyQ::JointDataMap< T > Class Template Reference
iit::TestHyQ::JointDataMap< T > Class Template Reference
#include <joint_data_map.h>
Public Member Functions
JointDataMap ()
JointDataMap (const T &defaultValue)
JointDataMap (const JointDataMap &rhs)
JointDataMap & operator= (const JointDataMap &rhs)
JointDataMap & operator= (const T &rhs)
T & operator[] (JointIdentifiers which)
const T & operator[] (JointIdentifiers which) const
Detailed Description
template<typename T>
class iit::TestHyQ::JointDataMap< T >
A very simple container to associate a generic data item to each joint
Constructor & Destructor Documentation
JointDataMap() [1/3]
template<typename T > iit::TestHyQ::JointDataMap< T >::JointDataMap () inline
References iit::TestHyQ::JointDataMap< T >::operator=(), and iit::TestHyQ::JointDataMap< T >::operator[]().
JointDataMap() [2/3]
template<typename T > iit::TestHyQ::JointDataMap< T >::JointDataMap (const T & defaultValue) inline
JointDataMap() [3/3]
template<typename T > iit::TestHyQ::JointDataMap< T >::JointDataMap (const JointDataMap< T > & rhs) inline
Member Function Documentation
operator=() [1/2]
template<typename T > JointDataMap< T > & iit::TestHyQ::JointDataMap< T >::operator= (const JointDataMap< T > & rhs) inline
Referenced by iit::TestHyQ::JointDataMap< T >::JointDataMap().
operator=() [2/2]
template<typename T > JointDataMap< T > & iit::TestHyQ::JointDataMap< T >::operator= (const T & rhs) inline
operator[]() [1/2]
template<typename T > T & iit::TestHyQ::JointDataMap< T >::operator[] (JointIdentifiers which) inline
Referenced by iit::TestHyQ::JointDataMap< T >::JointDataMap().
operator[]() [2/2]
template<typename T > const T & iit::TestHyQ::JointDataMap< T >::operator[] (JointIdentifiers which) const inline
References iit::TestHyQ::LF_HAA, iit::TestHyQ::LF_HFE, iit::TestHyQ::LF_KFE, iit::TestHyQ::LH_HAA, iit::TestHyQ::LH_HFE, iit::TestHyQ::LH_KFE, iit::TestHyQ::RF_HAA, iit::TestHyQ::RF_HFE, iit::TestHyQ::RF_KFE, iit::TestHyQ::RH_HAA, iit::TestHyQ::RH_HFE, and iit::TestHyQ::RH_KFE.
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/models/testhyq/generated/joint_data_map.h