ct::rbd::SpatialForceVector< SCALAR > Class Template Reference
ct::rbd::SpatialForceVector< SCALAR > Class Template Reference
A spatial force vector This vector contains a torque (angular) in the upper three rows and a linear force in the lower three rows.
#include <SpatialForceVector.h>
Public Types
typedef Eigen::Matrix< SCALAR, 6, 1 > spatial_force_vector_t
special vector type
typedef Eigen::VectorBlock< spatial_force_vector_t, 3 > ForceTorqueBlock
3D force or torque block inside of the spacial vector
typedef Eigen::VectorBlock< const spatial_force_vector_t, 3 > ForceTorqueBlockConst
const 3D force or torque block inside of the spacial vector
Public Member Functions
SpatialForceVector ()
Default constructor.
SpatialForceVector (const spatial_force_vector_t &vector6)
Copy constructor.
spatial_force_vector_t & toImplementation ()
Returns the Eigen implementation.
const spatial_force_vector_t & toImplementation () const
Returns the Eigen implementation.
SpatialForceVector & setZero ()
Sets all entries to zero.
bool operator== (const spatial_force_vector_t &rhs) const
Comparison operator (exact, subject to floating point rounding)
bool operator!= (const spatial_force_vector_t &rhs) const
Comparison operator (exact, subject to floating point rounding)
spatial_force_vector_t operator+ (const spatial_force_vector_t &rhs) const
Sums two spatial forces component-wise.
spatial_force_vector_t operator- (const spatial_force_vector_t &rhs) const
Substracts two spatial forces component-wise.
spatial_force_vector_t operator* (const SCALAR &scalar) const
Scales a spatial forces component-wise.
spatial_force_vector_t operator/ (const SCALAR &scalar) const
Divides a spatial forces component-wise.
ForceTorqueBlock torque ()
Get the torque block (upper 3D block)
const ForceTorqueBlockConst torque () const
Get the torque block (upper 3D block)
ForceTorqueBlock force ()
Get the force block (lower 3D block)
const ForceTorqueBlockConst force () const
Get the force block (lower 3D block)
Detailed Description
template<typename SCALAR = double>
class ct::rbd::SpatialForceVector< SCALAR >
A spatial force vector This vector contains a torque (angular) in the upper three rows and a linear force in the lower three rows.
Member Typedef Documentation
spatial_force_vector_t
template<typename SCALAR = double> typedef Eigen::Matrix<SCALAR, 6, 1> ct::rbd::SpatialForceVector< SCALAR >::spatial_force_vector_t
special vector type
ForceTorqueBlock
template<typename SCALAR = double> typedef Eigen::VectorBlock<spatial_force_vector_t, 3> ct::rbd::SpatialForceVector< SCALAR >::ForceTorqueBlock
3D force or torque block inside of the spacial vector
ForceTorqueBlockConst
template<typename SCALAR = double> typedef Eigen::VectorBlock<const spatial_force_vector_t, 3> ct::rbd::SpatialForceVector< SCALAR >::ForceTorqueBlockConst
const 3D force or torque block inside of the spacial vector
Constructor & Destructor Documentation
SpatialForceVector() [1/2]
template<typename SCALAR = double> ct::rbd::SpatialForceVector< SCALAR >::SpatialForceVector () inline
Default constructor.
SpatialForceVector() [2/2]
template<typename SCALAR = double> ct::rbd::SpatialForceVector< SCALAR >::SpatialForceVector (const spatial_force_vector_t & vector6) inline
Copy constructor.
Member Function Documentation
toImplementation() [1/2]
template<typename SCALAR = double> spatial_force_vector_t& ct::rbd::SpatialForceVector< SCALAR >::toImplementation () inline
Returns the Eigen implementation.
toImplementation() [2/2]
template<typename SCALAR = double> const spatial_force_vector_t& ct::rbd::SpatialForceVector< SCALAR >::toImplementation () const inline
Returns the Eigen implementation.
setZero()
template<typename SCALAR = double> SpatialForceVector& ct::rbd::SpatialForceVector< SCALAR >::setZero () inline
Sets all entries to zero.
operator==()
template<typename SCALAR = double> bool ct::rbd::SpatialForceVector< SCALAR >::operator== (const spatial_force_vector_t & rhs) const inline
Comparison operator (exact, subject to floating point rounding)
operator!=()
template<typename SCALAR = double> bool ct::rbd::SpatialForceVector< SCALAR >::operator!= (const spatial_force_vector_t & rhs) const inline
Comparison operator (exact, subject to floating point rounding)
operator+()
template<typename SCALAR = double> spatial_force_vector_t ct::rbd::SpatialForceVector< SCALAR >::operator+ (const spatial_force_vector_t & rhs) const inline
Sums two spatial forces component-wise.
operator-()
template<typename SCALAR = double> spatial_force_vector_t ct::rbd::SpatialForceVector< SCALAR >::operator- (const spatial_force_vector_t & rhs) const inline
Substracts two spatial forces component-wise.
operator*()
template<typename SCALAR = double> spatial_force_vector_t ct::rbd::SpatialForceVector< SCALAR >::operator* (const SCALAR & scalar) const inline
Scales a spatial forces component-wise.
operator/()
template<typename SCALAR = double> spatial_force_vector_t ct::rbd::SpatialForceVector< SCALAR >::operator/ (const SCALAR & scalar) const inline
Divides a spatial forces component-wise.
torque() [1/2]
template<typename SCALAR = double> ForceTorqueBlock ct::rbd::SpatialForceVector< SCALAR >::torque () inline
Get the torque block (upper 3D block)
Referenced by ct::rbd::Kinematics< RBD, NEE >::mapForceFromEEToLink(), and ct::rbd::Kinematics< RBD, NEE >::mapForceFromWorldToLink().
torque() [2/2]
template<typename SCALAR = double> const ForceTorqueBlockConst ct::rbd::SpatialForceVector< SCALAR >::torque () const inline
Get the torque block (upper 3D block)
force() [1/2]
template<typename SCALAR = double> ForceTorqueBlock ct::rbd::SpatialForceVector< SCALAR >::force () inline
Get the force block (lower 3D block)
Referenced by ct::rbd::Kinematics< RBD, NEE >::mapForceFromEEToLink(), ct::rbd::Kinematics< RBD, NEE >::mapForceFromWorldToLink(), and ct::rbd::Kinematics< RBD, NEE >::mapForceFromWorldToLink3d().
force() [2/2]
template<typename SCALAR = double> const ForceTorqueBlockConst ct::rbd::SpatialForceVector< SCALAR >::force () const inline
Get the force block (lower 3D block)
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/common/SpatialForceVector.h