ct::rbd::RBDAcceleration< NJOINTS, SCALAR > Class Template Reference
ct::rbd::RBDAcceleration< NJOINTS, SCALAR > Class Template Reference
State
joint acceleration and base acceleration
#include <RBDAcceleration.h>
Public Types
enum DIMS { NDOF = NJOINTS + 6, NSTATE = 2 * NDOF }
typedef Eigen::Matrix< SCALAR, NDOF, 1 > coordinate_vector_t
typedef tpl::RigidBodyAcceleration< SCALAR > RigidBodyAcceleration_t
Public Member Functions
RBDAcceleration ()
RBDAcceleration (const RigidBodyAcceleration_t &baseStateDerivative, const JointAcceleration< NJOINTS, SCALAR > &jointStateDerivative)
RigidBodyAcceleration_t & base ()
get base acceleration
const RigidBodyAcceleration_t & base () const
get constant base acceleration
JointAcceleration< NJOINTS, SCALAR > & joints ()
get joint acceleration
const JointAcceleration< NJOINTS, SCALAR > & joints () const
get constant joint acceleration
RBDState< NJOINTS, SCALAR >::state_vector_quat_t toStateUpdateVectorQuaternion (const RBDState< NJOINTS, SCALAR > &state) const
RBDState< NJOINTS, SCALAR >::state_vector_euler_t toStateUpdateVectorEulerXyz (const RBDState< NJOINTS, SCALAR > &state) const
coordinate_vector_t toCoordinateAcceleration () const
void setZero ()
Static Public Member Functions
static RBDAcceleration< NJOINTS, SCALAR > Zero ()
Protected Attributes
RigidBodyAcceleration_t baseStateDerivative_
JointAcceleration< NJOINTS, SCALAR > jointStateDerivative_
Detailed Description
template<size_t NJOINTS, typename SCALAR = double>
class ct::rbd::RBDAcceleration< NJOINTS, SCALAR >
joint acceleration and base acceleration
Member Typedef Documentation
coordinate_vector_t
template<size_t NJOINTS, typename SCALAR = double> typedef Eigen::Matrix<SCALAR, NDOF, 1> ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::coordinate_vector_t
RigidBodyAcceleration_t
template<size_t NJOINTS, typename SCALAR = double> typedef tpl::RigidBodyAcceleration<SCALAR> ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::RigidBodyAcceleration_t
Member Enumeration Documentation
DIMS
template<size_t NJOINTS, typename SCALAR = double> enum ct::rbd::RBDAcceleration::DIMS
Enumerator
NDOF
NSTATE
position/velocity of (joints + base)
Constructor & Destructor Documentation
RBDAcceleration() [1/2]
template<size_t NJOINTS, typename SCALAR = double> ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::RBDAcceleration () inline
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::setZero().
RBDAcceleration() [2/2]
template<size_t NJOINTS, typename SCALAR = double> ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::RBDAcceleration (const RigidBodyAcceleration_t & baseStateDerivative, const JointAcceleration< NJOINTS, SCALAR > & jointStateDerivative) inline
Member Function Documentation
base() [1/2]
template<size_t NJOINTS, typename SCALAR = double> RigidBodyAcceleration_t& ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::base () inline
get base acceleration
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::baseStateDerivative_.
Referenced by ct::rbd::IDControllerFB< Dynamics >::computeDesiredAcceleration(), ct::rbd::Dynamics< RBD, NEE >::FloatingBaseForwardDynamics(), ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedForwardDynamics(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toCoordinateAcceleration(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz(), and ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion().
base() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const RigidBodyAcceleration_t& ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::base () const inline
get constant base acceleration
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::baseStateDerivative_.
joints() [1/2]
template<size_t NJOINTS, typename SCALAR = double> JointAcceleration<NJOINTS, SCALAR>& ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::joints () inline
get joint acceleration
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::jointStateDerivative_.
Referenced by ct::rbd::Dynamics< RBD, NEE >::FloatingBaseForwardDynamics(), ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedForwardDynamics(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toCoordinateAcceleration(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz(), and ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion().
joints() [2/2]
template<size_t NJOINTS, typename SCALAR = double> const JointAcceleration<NJOINTS, SCALAR>& ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::joints () const inline
get constant joint acceleration
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::jointStateDerivative_.
toStateUpdateVectorQuaternion()
template<size_t NJOINTS, typename SCALAR = double> RBDState<NJOINTS, SCALAR>::state_vector_quat_t ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorQuaternion (const RBDState< NJOINTS, SCALAR > & state) const inline
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::base(), ct::rbd::RBDState< NJOINTS, SCALAR >::base(), ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getAngularAcceleration(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getTranslationalAcceleration(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::joints(), and ct::rbd::RBDState< NJOINTS, SCALAR >::joints().
toStateUpdateVectorEulerXyz()
template<size_t NJOINTS, typename SCALAR = double> RBDState<NJOINTS, SCALAR>::state_vector_euler_t ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toStateUpdateVectorEulerXyz (const RBDState< NJOINTS, SCALAR > & state) const inline
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::base(), ct::rbd::RBDState< NJOINTS, SCALAR >::base(), ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getAngularAcceleration(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getTranslationalAcceleration(), ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::joints(), ct::rbd::RBDState< NJOINTS, SCALAR >::joints(), and ct::core::StateVector< STATE_DIM, SCALAR >::toImplementation().
toCoordinateAcceleration()
template<size_t NJOINTS, typename SCALAR = double> coordinate_vector_t ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::toCoordinateAcceleration () const inline
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::base(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getAngularAcceleration(), ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::getTranslationalAcceleration(), and ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::joints().
Referenced by ct::rbd::ProjectedDynamics< RBD, NEE >::ProjectedDynamics().
setZero()
template<size_t NJOINTS, typename SCALAR = double> void ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::setZero () inline
References ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::baseStateDerivative_, ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::jointStateDerivative_, and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::setZero().
Referenced by ct::rbd::IDControllerFB< Dynamics >::computeDesiredAcceleration(), and ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::RBDAcceleration().
Zero()
template<size_t NJOINTS, typename SCALAR = double> static RBDAcceleration<NJOINTS, SCALAR> ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::Zero () inline static
References ct::rbd::JointAcceleration< NJOINTS, SCALAR >::Zero(), and ct::rbd::tpl::RigidBodyAcceleration< SCALAR >::Zero().
Member Data Documentation
baseStateDerivative_
template<size_t NJOINTS, typename SCALAR = double> RigidBodyAcceleration_t ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::baseStateDerivative_ protected
Referenced by ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::base(), and ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::setZero().
jointStateDerivative_
template<size_t NJOINTS, typename SCALAR = double> JointAcceleration<NJOINTS, SCALAR> ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::jointStateDerivative_ protected
Referenced by ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::joints(), and ct::rbd::RBDAcceleration< NJOINTS, SCALAR >::setZero().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/state/RBDAcceleration.h