ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM > Class Template Reference
ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM > Class Template Reference
A costfunction term that defines a cost on a taskspace position.
#include <TermTaskspacePosition.hpp>
Public Types
using SCALAR = ct::core::ADCGScalar
Public Types inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >
typedef Eigen::Matrix< double, STATE_DIM, STATE_DIM > state_matrix_t
typedef Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM > control_matrix_t
typedef Eigen::Matrix< double, CONTROL_DIM, STATE_DIM > control_state_matrix_t
typedef Eigen::Matrix< double, STATE_DIM, STATE_DIM > state_matrix_double_t
typedef Eigen::Matrix< double, CONTROL_DIM, CONTROL_DIM > control_matrix_double_t
typedef Eigen::Matrix< double, CONTROL_DIM, STATE_DIM > control_state_matrix_double_t
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW TermTaskspacePosition ()=delete
the trivial constructor is explicitly forbidden
TermTaskspacePosition (size_t eeInd, const Eigen::Matrix< double, 3, 3 > &Q, const core::StateVector< 3, double > &pos_des, const std::string &name="TermTaskSpace")
constructor
TermTaskspacePosition (std::string &configFile, const std::string &termName, bool verbose=false)
construct this term with info loaded from a configuration file
TermTaskspacePosition (const TermTaskspacePosition &arg)
copy constructor
virtual ~TermTaskspacePosition ()
destructor
TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM > * clone () const override
deep cloning
virtual SCALAR evaluate (const Eigen::Matrix< SCALAR, STATE_DIM, 1 > &x, const Eigen::Matrix< SCALAR, CONTROL_DIM, 1 > &u, const SCALAR &t) override
virtual ct::core::ADCGScalar evaluateCppadCg (const core::StateVector< STATE_DIM, ct::core::ADCGScalar > &x, const core::ControlVector< CONTROL_DIM, ct::core::ADCGScalar > &u, ct::core::ADCGScalar t) override
we overload the evaluateCppadCg method
void loadConfigFile (const std::string &filename, const std::string &termName, bool verbose=false) override
load term information from configuration file (stores data in member variables)
Public Member Functions inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >
TermBase (std::string name="Unnamed")
TermBase (const TermBase &arg)
virtual ~TermBase ()
double eval (const Eigen::Matrix< double, STATE_DIM, 1 > &x, const Eigen::Matrix< double, CONTROL_DIM, 1 > &u, const double &t)
virtual bool isActiveAtTime (doublet)
double computeActivation (doublet)
virtual core::StateVector< STATE_DIM, double > stateDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual state_matrix_t stateSecondDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual core::ControlVector< CONTROL_DIM, double > controlDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual control_matrix_t controlSecondDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
virtual control_state_matrix_t stateControlDerivative (const core::StateVector< STATE_DIM, double > &x, const core::ControlVector< CONTROL_DIM, double > &u, const double &t)
void setTimeActivation (std::shared_ptr< ct::core::tpl::ActivationBase< double >> c_i, bool verbose=false)
void loadTimeActivation (const std::string &filename, const std::string &termName, bool verbose=false)
const std::string & getName () const
void setName (const std::string &termName)
virtual void updateReferenceState (const Eigen::Matrix< double, STATE_DIM, 1 > &newRefState)
virtual void updateReferenceControl (const Eigen::Matrix< double, CONTROL_DIM, 1 > &newRefControl)
virtual Eigen::Matrix< double, STATE_DIM, 1 > getReferenceState () const
Additional Inherited Members
Protected Attributes inherited from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >
std::string name_
std::shared_ptr< ct::core::tpl::ActivationBase< double > > c_i_
Detailed Description
template<class KINEMATICS, bool FB, size_t STATE_DIM, size_t CONTROL_DIM>
class ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >
A costfunction term that defines a cost on a taskspace position.
Warning
This term does not consider orientations. For a full pose cost function, see TermTaskspacePose.h
This cost function adds a quadratic penalty on the position offset of an endeffector to a desired position
Todo:
add velocity to term
Template Parameters
KINEMATICS kinematics of the system
FB true if system is a floating base robot
STATE_DIM state dimensionality of the system
CONTROL_DIM control dimensionality of the system
Member Typedef Documentation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> using ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::SCALAR = ct::core::ADCGScalar
Constructor & Destructor Documentation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> EIGEN_MAKE_ALIGNED_OPERATOR_NEW ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePosition () delete
the trivial constructor is explicitly forbidden
Referenced by ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::clone().
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePosition (size_t eeInd, const Eigen::Matrix< double, 3, 3 > & Q, const core::StateVector< 3, double > & pos_des, const std::string & name = "TermTaskSpace") inline
constructor
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePosition (std::string & configFile, const std::string & termName, bool verbose = false) inline
construct this term with info loaded from a configuration file
References ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::loadConfigFile(), and verbose.
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePosition (const TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM > & arg) inline
copy constructor
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> virtual ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::~TermTaskspacePosition () inline virtual
destructor
Member Function Documentation
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> TermTaskspacePosition<KINEMATICS, FB, STATE_DIM, CONTROL_DIM>* ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::clone () const inline override virtual
deep cloning
Implements ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >.
References ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePosition().
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> virtual SCALAR ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::evaluate (const Eigen::Matrix< SCALAR, STATE_DIM, 1 > & x, const Eigen::Matrix< SCALAR, CONTROL_DIM, 1 > & u, const SCALAR & t) inline override virtual
Implements ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >.
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> virtual ct::core::ADCGScalar ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::evaluateCppadCg (const core::StateVector< STATE_DIM, ct::core::ADCGScalar > & x, const core::ControlVector< CONTROL_DIM, ct::core::ADCGScalar > & u, ct::core::ADCGScalar t) inline override virtual
we overload the evaluateCppadCg method
Reimplemented from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >.
template<class KINEMATICS , bool FB, size_t STATE_DIM, size_t CONTROL_DIM> void ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::loadConfigFile (const std::string & filename, const std::string & termName, bool verbose = false) inline override virtual
load term information from configuration file (stores data in member variables)
Reimplemented from ct::optcon::TermBase< STATE_DIM, CONTROL_DIM, double, ct::core::ADCGScalar >.
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), ct::rbd::RBDState< NJOINTS, SCALAR >::joints(), ct::optcon::loadMatrixCF(), ct::optcon::loadScalarCF(), t, u, verbose, and x.
Referenced by ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePosition().
The documentation for this class was generated from the following file:
/home/adrl/code/src/control-toolbox/ct_rbd/include/ct/rbd/robot/costfunction/TermTaskspacePosition.hpp