ct::rbd::tpl::RigidBodyState< SCALAR > Class Template Reference
ct::rbd::tpl::RigidBodyState< SCALAR > Class Template Reference
State
State (pose and velocities) of a single rigid body.
#include <RigidBodyState.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW RigidBodyState (typename RigidBodyPose< SCALAR >::STORAGE_TYPE storage=RigidBodyPose< SCALAR >::EULER)
RigidBodyState (const RigidBodyState< SCALAR > &arg)
copy constructor
virtual ~RigidBodyState ()
destructor
RigidBodyPose< SCALAR > & pose ()
return the rigid body pose
const RigidBodyPose< SCALAR > & pose () const
return the rigid body pose (const)
RigidBodyVelocities< SCALAR > & velocities ()
return the rigid body velocities
const RigidBodyVelocities< SCALAR > & velocities () const
return the rigid body velocities (const)
bool isApprox (const RigidBodyState &rhs, const double &tol=1e-10)
numerically comparing two rigid body states
const kindr::Velocity< SCALAR, 3 > computeTranslationalVelocityW () const
get translational velocity
kindr::Velocity< SCALAR, 3 > computeTranslationalVelocityW ()
void setIdentity ()
void setRandom ()
Detailed Description
template<typename SCALAR = double>
class ct::rbd::tpl::RigidBodyState< SCALAR >
State (pose and velocities) of a single rigid body.
Constructor & Destructor Documentation
RigidBodyState() [1/2]
template<typename SCALAR = double> EIGEN_MAKE_ALIGNED_OPERATOR_NEW ct::rbd::tpl::RigidBodyState< SCALAR >::RigidBodyState (typename RigidBodyPose< SCALAR >::STORAGE_TYPE storage = RigidBodyPose<SCALAR>::EULER) inline
RigidBodyState() [2/2]
template<typename SCALAR = double> ct::rbd::tpl::RigidBodyState< SCALAR >::RigidBodyState (const RigidBodyState< SCALAR > & arg) inline
copy constructor
~RigidBodyState()
template<typename SCALAR = double> virtual ct::rbd::tpl::RigidBodyState< SCALAR >::~RigidBodyState () inline virtual
destructor
Member Function Documentation
pose() [1/2]
template<typename SCALAR = double> RigidBodyPose<SCALAR>& ct::rbd::tpl::RigidBodyState< SCALAR >::pose () inline
return the rigid body pose
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::basePose(), ct::rbd::tpl::RigidBodyState< double >::computeTranslationalVelocityW(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorQuaternion(), ct::rbd::tpl::RigidBodyState< double >::isApprox(), ct::rbd::tpl::RigidBodyState< double >::setIdentity(), ct::rbd::tpl::RigidBodyState< double >::setRandom(), testFunctionRBDState(), testFunctionRigidBodyState(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinatePosition(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinatePositionUnique(), and ct::rbd::RBDState< NJOINTS, Scalar >::toStateVectorQuaternion().
pose() [2/2]
template<typename SCALAR = double> const RigidBodyPose<SCALAR>& ct::rbd::tpl::RigidBodyState< SCALAR >::pose () const inline
return the rigid body pose (const)
velocities() [1/2]
template<typename SCALAR = double> RigidBodyVelocities<SCALAR>& ct::rbd::tpl::RigidBodyState< SCALAR >::velocities () inline
return the rigid body velocities
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::baseLinearVelocity(), ct::rbd::RBDState< NJOINTS, Scalar >::baseLocalAngularVelocity(), ct::rbd::RBDState< NJOINTS, Scalar >::baseVelocities(), ct::rbd::IDControllerFB< Dynamics >::computeDesiredAcceleration(), ct::rbd::tpl::RigidBodyState< double >::computeTranslationalVelocityW(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, Scalar >::fromStateVectorQuaternion(), ct::rbd::tpl::RigidBodyState< double >::isApprox(), ct::rbd::tpl::RigidBodyState< double >::setIdentity(), ct::rbd::tpl::RigidBodyState< double >::setRandom(), testFunctionRBDState(), testFunctionRigidBodyState(), ct::rbd::RBDState< NJOINTS, Scalar >::toCoordinateVelocity(), and ct::rbd::RBDState< NJOINTS, Scalar >::toStateVectorQuaternion().
velocities() [2/2]
template<typename SCALAR = double> const RigidBodyVelocities<SCALAR>& ct::rbd::tpl::RigidBodyState< SCALAR >::velocities () const inline
return the rigid body velocities (const)
isApprox()
template<typename SCALAR = double> bool ct::rbd::tpl::RigidBodyState< SCALAR >::isApprox (const RigidBodyState< SCALAR > & rhs, const double & tol = 1e-10) inline
numerically comparing two rigid body states
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::isApprox().
computeTranslationalVelocityW() [1/2]
template<typename SCALAR = double> const kindr::Velocity<SCALAR, 3> ct::rbd::tpl::RigidBodyState< SCALAR >::computeTranslationalVelocityW () const inline
get translational velocity
computeTranslationalVelocityW() [2/2]
template<typename SCALAR = double> kindr::Velocity<SCALAR, 3> ct::rbd::tpl::RigidBodyState< SCALAR >::computeTranslationalVelocityW () inline
setIdentity()
template<typename SCALAR = double> void ct::rbd::tpl::RigidBodyState< SCALAR >::setIdentity () inline
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::RBDState(), ct::rbd::RBDState< NJOINTS, Scalar >::setDefault(), and ct::rbd::RBDState< NJOINTS, Scalar >::setZero().
setRandom()
template<typename SCALAR = double> void ct::rbd::tpl::RigidBodyState< SCALAR >::setRandom () inline
Referenced by ct::rbd::RBDState< NJOINTS, Scalar >::setRandom().
The documentation for this class was generated from the following file:
/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/include/ct/rbd/state/RigidBodyState.h