/home/adrl/code/src/control-toolbox/ct_rbd/test/robot/kinematics/EEKinematicsTest.cpp File Reference
EEKinematicsTest.cpp File Reference
#include <ct/rbd/rbd.h>
#include <memory>
#include <gtest/gtest.h>
#include <ct/rbd/state/RBDState.h>
#include "../../models/testhyq/RobCoGenTestHyQ.h"
Typedefs
typedef RBDState< 12 > RBDStateHyQ
Functions
TEST (EEKinematicsTest, testFootVelocityBaseAngularVelocity)
TEST (EEKinematicsTest, testFootVelocityBaseZRotation)
TEST (EEKinematicsTest, testFootVelocityBaseLinearVelocity)
TEST (EEKinematicsTest, testFootPositionVaryingBase)
TEST (EEKinematicsTest, testFootPositionStraightBase)
TEST (EEKinematicsTest, forceMappingTest)
TEST (EEKinematicsTest, forceMagnitudeTest)
TEST (EEKinematicsTest, torqueMappingTest)
int main (int argc, char **argv)
Variables
const size_t nFeet = 4
Typedef Documentation
typedef RBDState<12> RBDStateHyQ
Function Documentation
TEST (EEKinematicsTest , testFootVelocityBaseAngularVelocity)
References ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity(), i, nFeet, and ct::rbd::RBDState< NJOINTS, SCALAR >::setZero().
TEST (EEKinematicsTest , testFootVelocityBaseZRotation)
References ct::rbd::RBDState< NJOINTS, SCALAR >::baseLinearVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::jointVelocities(), nFeet, ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromEulerAnglesXyz(), and ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom().
TEST (EEKinematicsTest , testFootVelocityBaseLinearVelocity)
References ct::rbd::RBDState< NJOINTS, SCALAR >::baseLinearVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::jointVelocities(), nFeet, ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromEulerAnglesXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), and t.
TEST (EEKinematicsTest , testFootPositionVaryingBase)
References i, ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), nFeet, ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), and t.
TEST (EEKinematicsTest , testFootPositionStraightBase)
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), nFeet, ct::rbd::tpl::RigidBodyPose< SCALAR >::position(), ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromEulerAnglesXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), and t.
TEST (EEKinematicsTest , forceMappingTest)
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), nFeet, ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromEulerAnglesXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), and t.
TEST (EEKinematicsTest , forceMagnitudeTest)
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), nFeet, ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), and t.
TEST (EEKinematicsTest , torqueMappingTest)
References ct::rbd::RBDState< NJOINTS, SCALAR >::basePose(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), nFeet, ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromEulerAnglesXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), and t.
int main (int argc, char ** argv)
Variable Documentation
const size_t nFeet = 4
Referenced by TEST().