/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/robot/kinematics/FixBaseIKTest.cpp File Reference
FixBaseIKTest.cpp File Reference
#include <ct/rbd/rbd.h>
#include "../../models/testIrb4600/RobCoGenTestIrb4600.h"
#include <gtest/gtest.h>
Typedefs
using Kinematics_t = ct::rbd::TestIrb4600::tpl::Kinematics< double >
using IKProblem = ct::rbd::IKNLP< Kinematics_t >
using IKNLPSolver = ct::rbd::IKNLPSolverIpopt< IKProblem, Kinematics_t >
Functions
TEST (FixBaseInverseKinematicsTest, DISABLED_NLPIKTest)
int main (int argc, char **argv)
Variables
const size_t njoints = ct::rbd::TestIrb4600::Kinematics::NJOINTS
Typedef Documentation
Kinematics_t
using Kinematics_t = ct::rbd::TestIrb4600::tpl::Kinematics<double>
IKProblem
using IKProblem = ct::rbd::IKNLP<Kinematics_t>
IKNLPSolver
using IKNLPSolver = ct::rbd::IKNLPSolverIpopt<IKProblem, Kinematics_t>
Function Documentation
TEST()
TEST (FixBaseInverseKinematicsTest , DISABLED_NLPIKTest)
References ct::rbd::IKNLPSolverIpopt< IKNLP, VALIDATION_KIN >::computeInverseKinematics(), ct::optcon::IpoptSettings::derivativeTest_, ct::optcon::IpoptSettings::hessian_approximation_, ct::optcon::IPOPT, ct::optcon::NlpSolverSettings::ipoptSettings_, ct::rbd::TestIrb4600::jointLowerLimit(), ct::rbd::TestIrb4600::jointUpperLimit(), ct::rbd::InverseKinematicsSettings::maxNumTrials_, ct::rbd::tpl::RigidBodyPose< SCALAR >::position(), ct::optcon::IpoptSettings::printLevel_, ct::rbd::InverseKinematicsSettings::randomizeInitialGuess_, ct::optcon::NlpSolverSettings::solverType_, and ct::rbd::InverseKinematicsSettings::validationTol_.
main()
int main (int argc, char ** argv)
Variable Documentation
njoints
const size_t njoints = ct::rbd::TestIrb4600::Kinematics::NJOINTS
Referenced by main(), and TEST().