/home/adrl/code/src/control-toolbox/ct_rbd/test/systems/FixBaseFDSystemTest.cpp File Reference
FixBaseFDSystemTest.cpp File Reference
#include <ct/rbd/rbd.h>
#include <memory>
#include <array>
#include <iostream>
#include <gtest/gtest.h>
#include "../models/testIrb4600/RobCoGenTestIrb4600.h"
Functions
TEST (FixBaseFDSystemTest, ForwardDynamicsTest)
TEST (FixBaseFDSystemTest, ActuatorDynamicsTest)
int main (int argc, char **argv)
Function Documentation
TEST (FixBaseFDSystemTest , ForwardDynamicsTest)
References ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), and ct::core::RK4.
TEST (FixBaseFDSystemTest , ActuatorDynamicsTest)
References actuator_state_dim, ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuatorStateFromVector(), ct::rbd::JointState< NJOINTS, SCALAR >::getPositions(), ct::rbd::JointState< NJOINTS, SCALAR >::getVelocities(), i, ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::jointStateFromVector(), njoints, ct::rbd::FixBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::NSTATE, ct::core::RK4, state_dim, w_n, and zeta.
int main (int argc, char ** argv)