RBD Core
RBD Core
Classes
struct iit::rbd::Core< SCALAR >
General matrix types
template<typename Derived >
using iit::rbd::MatrixBase = Eigen::MatrixBase< Derived >
template<typename Scalar , int R, int C>
using iit::rbd::PlainMatrix = Eigen::Matrix< Scalar, R, C >
template<typename XprType , int R, int C>
using iit::rbd::MatrixBlock = Eigen::Block< XprType, R, C >
template<typename Scalar >
using iit::rbd::SparseMatrix = Eigen::SparseMatrix< Scalar >
template<typename Scalar >
using iit::rbd::SparseVector = Eigen::SparseVector< Scalar >
Types with 'double' as the scalar type.
Explicit instantiation of all the various matrix types using the standard double as the scalar type. See Core
typedef Core< double > iit::rbd::Cored
using iit::rbd::Matrix33d = Cored::Matrix33
using iit::rbd::Vector3d = Cored::Vector3
using iit::rbd::Matrix66d = Cored::Matrix66
using iit::rbd::Vector6d = Cored::Vector6
using iit::rbd::Vector6D = Cored::Vector6D
using iit::rbd::VelocityVector = Cored::VelocityVector
using iit::rbd::ForceVector = Cored::ForceVector
using iit::rbd::Part3D = Cored::Part3D
using iit::rbd::Part3DConst = Cored::Part3DConst
using iit::rbd::Column6d = Cored::Column6D
using iit::rbd::SparseMatrixd = SparseMatrix< double >
using iit::rbd::SparseColumnd = SparseVector< double >
Part3D iit::rbd::angularPart (Vector6D &f)
Part3D iit::rbd::linearPart (Vector6D &f)
Part3DConst iit::rbd::angularPart (const Vector6D &f)
Part3DConst iit::rbd::linearPart (const Vector6D &f)
Vector coordinates
Constants to index either 6D or 3D coordinate vectors.
enum iit::rbd::Coords3D { iit::rbd::X =0, iit::rbd::Y, iit::rbd::Z }
To be used with 6D vectors. 'A' stands for angular, 'L' for linear.
enum iit::rbd::Coords6D {
iit::rbd::AX =0, iit::rbd::AY, iit::rbd::AZ, iit::rbd::LX,
iit::rbd::LY, iit::rbd::LZ
}
To be used with 6D vectors. 'A' stands for angular, 'L' for linear.
Detailed Description
Main, basic data types and functions
Typedef Documentation
MatrixBase
template<typename Derived > using iit::rbd::MatrixBase = typedef Eigen::MatrixBase< Derived >
PlainMatrix
template<typename Scalar , int R, int C> using iit::rbd::PlainMatrix = typedef Eigen::Matrix< Scalar, R, C >
MatrixBlock
template<typename XprType , int R, int C> using iit::rbd::MatrixBlock = typedef Eigen::Block< XprType, R, C >
SparseMatrix
template<typename Scalar > using iit::rbd::SparseMatrix = typedef Eigen::SparseMatrix<Scalar>
SparseVector
template<typename Scalar > using iit::rbd::SparseVector = typedef Eigen::SparseVector<Scalar>
Cored
typedef Core<double> iit::rbd::Cored
Matrix33d
using iit::rbd::Matrix33d = typedef Cored::Matrix33
Vector3d
using iit::rbd::Vector3d = typedef Cored::Vector3
Matrix66d
using iit::rbd::Matrix66d = typedef Cored::Matrix66
Vector6d
using iit::rbd::Vector6d = typedef Cored::Vector6
Vector6D
using iit::rbd::Vector6D = typedef Cored::Vector6D
VelocityVector
using iit::rbd::VelocityVector = typedef Cored::VelocityVector
ForceVector
using iit::rbd::ForceVector = typedef Cored::ForceVector
Part3D
using iit::rbd::Part3D = typedef Cored::Part3D
Part3DConst
using iit::rbd::Part3DConst = typedef Cored::Part3DConst
Column6d
using iit::rbd::Column6d = typedef Cored::Column6D
SparseMatrixd
using iit::rbd::SparseMatrixd = typedef SparseMatrix<double>
SparseColumnd
using iit::rbd::SparseColumnd = typedef SparseVector<double>
Enumeration Type Documentation
Coords3D
enum iit::rbd::Coords3D
To be used with 6D vectors. 'A' stands for angular, 'L' for linear.
Enumerator
X
Y
Z
Coords6D
enum iit::rbd::Coords6D
To be used with 6D vectors. 'A' stands for angular, 'L' for linear.
Enumerator
AX
AY
AZ
LX
LY
LZ
Function Documentation
angularPart() [1/2]
Part3D iit::rbd::angularPart (Vector6D & f) inline
References iit::rbd::Core< SCALAR >::angularPart().
Referenced by iit::rbd::Utils::randomGravity().
linearPart() [1/2]
Part3D iit::rbd::linearPart (Vector6D & f) inline
References iit::rbd::Core< SCALAR >::linearPart().
Referenced by iit::rbd::Utils::randomGravity().
angularPart() [2/2]
Part3DConst iit::rbd::angularPart (const Vector6D & f) inline
References iit::rbd::Core< SCALAR >::angularPart().
linearPart() [2/2]
Part3DConst iit::rbd::linearPart (const Vector6D & f) inline
References iit::rbd::Core< SCALAR >::linearPart(), iit::rbd::X, iit::rbd::Y, and iit::rbd::Z.