/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/state/JointStateTest.cpp File Reference
JointStateTest.cpp File Reference
#include <ct/core/core.h>
#include "ct/rbd/state/JointState.h"
#include <gtest/gtest.h>
Functions
std::vector< double > lowerLimitVector (nJoints, -1.0)
std::vector< double > upperLimitVector (nJoints, 1.0)
Eigen::Matrix< double, nJoints, 1 > lowerLimitEigen (lowerLimitVector.data())
Eigen::Matrix< double, nJoints, 1 > upperLimitEigen (upperLimitVector.data())
TEST (JointStateTest, jointLimitTest)
TEST (JointStateTest, toUniqueTest)
int main (int argc, char **argv)
Variables
const size_t nJoints = 4
JointState< nJoints > js
const double tolerance = 1e-3
Function Documentation
lowerLimitVector()
std::vector<double> lowerLimitVector (nJoints , -1. 0)
Referenced by TEST().
upperLimitVector()
std::vector<double> upperLimitVector (nJoints , 1. 0)
Referenced by TEST().
lowerLimitEigen()
Eigen::Matrix<double, nJoints, 1> lowerLimitEigen (lowerLimitVector. data())
Referenced by TEST().
upperLimitEigen()
Eigen::Matrix<double, nJoints, 1> upperLimitEigen (upperLimitVector. data())
Referenced by TEST().
TEST() [1/2]
TEST (JointStateTest , jointLimitTest)
References ct::rbd::JointState< NJOINTS, SCALAR >::checkPositionLimits(), ct::rbd::JointState< NJOINTS, SCALAR >::checkVelocityLimits(), ct::rbd::JointState< NJOINTS, SCALAR >::getPosition(), ct::rbd::JointState< NJOINTS, SCALAR >::getVelocity(), lowerLimitEigen(), lowerLimitVector(), ct::rbd::JointState< NJOINTS, SCALAR >::setZero(), tolerance, upperLimitEigen(), and upperLimitVector().
TEST() [2/2]
TEST (JointStateTest , toUniqueTest)
References ct::rbd::JointState< NJOINTS, SCALAR >::getPosition(), ct::rbd::JointState< NJOINTS, SCALAR >::isApprox(), js, lowerLimitEigen(), lowerLimitVector(), ct::rbd::JointState< NJOINTS, SCALAR >::setZero(), tolerance, ct::rbd::JointState< NJOINTS, SCALAR >::toUniquePosition(), and upperLimitEigen().
main()
int main (int argc, char ** argv)
Variable Documentation
nJoints
const size_t nJoints = 4
js
JointState<nJoints> js
Referenced by TEST().
tolerance
const double tolerance = 1e-3
Referenced by ct::rbd::JointState< NJOINTS, Scalar >::checkPositionLimits(), TEST(), and ct::rbd::JointState< NJOINTS, Scalar >::toUniquePosition().