iit::TestHyQ Namespace Reference
iit::TestHyQ Namespace Reference
Namespaces
dyn
tpl
Classes
class JointDataMap
class LinkDataMap
Typedefs
using Column12d = tpl::Column12d< double >
typedef Column12d JointState
typedef tpl::Traits< double > Traits
Enumerations
enum JointIdentifiers {
LF_HAA = 0, LF_HFE, LF_KFE, RF_HAA,
RF_HFE, RF_KFE, LH_HAA, LH_HFE,
LH_KFE, RH_HAA, RH_HFE, RH_KFE
}
enum LinkIdentifiers {
TRUNK = 0, LF_HIPASSEMBLY, LF_UPPERLEG, LF_LOWERLEG,
RF_HIPASSEMBLY, RF_UPPERLEG, RF_LOWERLEG, LH_HIPASSEMBLY,
LH_UPPERLEG, LH_LOWERLEG, RH_HIPASSEMBLY, RH_UPPERLEG,
RH_LOWERLEG
}
Functions
template<typename T >
std::ostream & operator<< (std::ostream &out, const JointDataMap< T > &map)
template<typename T >
std::ostream & operator<< (std::ostream &out, const LinkDataMap< T > &map)
Center of mass calculation
Computes the Center Of Mass (COM) position of the whole robot, in base coordinates.
Common parameters are the inertia properties of the robot and the set of homogeneous coordinate transforms. If a joint status variable is also passed, then the transforms are updated accordingly; otherwise, they are not modified before being used.
iit::rbd::Vector3d getWholeBodyCOM (const dyn::InertiaProperties &inertia, const HomogeneousTransforms &transforms)
iit::rbd::Vector3d getWholeBodyCOM (const dyn::InertiaProperties &inertia, const JointState &q, HomogeneousTransforms &transforms)
Typedef Documentation
Column12d
using iit::TestHyQ::Column12d = typedef tpl::Column12d<double>
JointState
typedef Column12d iit::TestHyQ::JointState
Traits
typedef tpl::Traits<double> iit::TestHyQ::Traits
Enumeration Type Documentation
JointIdentifiers
enum iit::TestHyQ::JointIdentifiers
Enumerator
LF_HAA
LF_HFE
LF_KFE
RF_HAA
RF_HFE
RF_KFE
LH_HAA
LH_HFE
LH_KFE
RH_HAA
RH_HFE
RH_KFE
LinkIdentifiers
enum iit::TestHyQ::LinkIdentifiers
Enumerator
TRUNK
LF_HIPASSEMBLY
LF_UPPERLEG
LF_LOWERLEG
RF_HIPASSEMBLY
RF_UPPERLEG
RF_LOWERLEG
LH_HIPASSEMBLY
LH_UPPERLEG
LH_LOWERLEG
RH_HIPASSEMBLY
RH_UPPERLEG
RH_LOWERLEG
Function Documentation
operator<<() [1/2]
template<typename T > std::ostream& iit::TestHyQ::operator<< (std::ostream & out, const JointDataMap< T > & map) inline
References LF_HAA, LF_HFE, LF_KFE, LH_HAA, LH_HFE, LH_KFE, RF_HAA, RF_HFE, RF_KFE, RH_HAA, RH_HFE, and RH_KFE.
operator<<() [2/2]
template<typename T > std::ostream& iit::TestHyQ::operator<< (std::ostream & out, const LinkDataMap< T > & map) inline
References LF_HIPASSEMBLY, LF_LOWERLEG, LF_UPPERLEG, LH_HIPASSEMBLY, LH_LOWERLEG, LH_UPPERLEG, RF_HIPASSEMBLY, RF_LOWERLEG, RF_UPPERLEG, RH_HIPASSEMBLY, RH_LOWERLEG, RH_UPPERLEG, and TRUNK.
getWholeBodyCOM() [1/2]
iit::rbd::Vector3d iit::TestHyQ::getWholeBodyCOM (const dyn::InertiaProperties & inertia, const HomogeneousTransforms & transforms)
Parameters
inertia the inertia properties of the links of the robot
transforms the homogeneous coordinate transforms of the robot
Returns
the position of the Center Of Mass of the whole robot, expressed in base coordinates
References iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LF_hipassembly(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LF_lowerleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LF_upperleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LH_hipassembly(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LH_lowerleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_LH_upperleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RF_hipassembly(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RF_lowerleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RF_upperleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RH_hipassembly(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RH_lowerleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_RH_upperleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getCOM_trunk(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LF_hipassembly(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LF_lowerleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LF_upperleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LH_hipassembly(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LH_lowerleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_LH_upperleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RF_hipassembly(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RF_lowerleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RF_upperleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RH_hipassembly(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RH_lowerleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_RH_upperleg(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getMass_trunk(), iit::TestHyQ::dyn::tpl::InertiaProperties< TRAIT >::getTotalMass(), and iit::rbd::Utils::transform().
Referenced by getWholeBodyCOM().
getWholeBodyCOM() [2/2]
iit::rbd::Vector3d iit::TestHyQ::getWholeBodyCOM (const dyn::InertiaProperties & inertia, const JointState & q, HomogeneousTransforms & transforms)
Parameters
inertia the inertia properties of the links of the robot
q the joint status vector describing the configuration of the robot
transforms the homogeneous coordinate transforms of the robot
Returns
the position of the Center Of Mass of the whole robot, expressed in base coordinates
References getWholeBodyCOM().