/home/adrl/code/src/control-toolbox/ct_rbd/test/operationalSpace/OperationalSpaceTest.cpp File Reference
OperationalSpaceTest.cpp File Reference
#include <memory>
#include <array>
#include <Eigen/Dense>
#include <gtest/gtest.h>
#include <ct/optcon/optcon.h>
#include <ct/rbd/robot/jacobian/OperationalJacobianBase.h>
#include <ct/rbd/operationalSpace/rigid_body/OperationalModel.h>
#include <ct/rbd/operationalSpace/rigid_body/OperationalModelRBD.h>
#include "../models/testhyq/RobCoGenTestHyQ.h"
Classes
class TestJacobian
Functions
TEST (OperationalSpaceTest, OperationalSpaceTest)
int main (int argc, char **argv)
Function Documentation
TEST (OperationalSpaceTest , OperationalSpaceTest)
References ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >::C(), ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::C(), ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >::G(), ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::G(), ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::getAccelerations(), i, ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::M(), ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >::MInverse(), ct::rbd::tpl::OperationalJacobianBase< NUM_OUTPUTS, NUM_JOINTS, SCALAR >::ptr, ct::rbd::OperationalModelBase< RBDContainer::NJOINTS+6, RBDContainer::NJOINTS, NUM_CONTACTPOINTS >::S(), ct::rbd::OperationalModelBase< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::S(), ct::rbd::OperationalModel< NUM_OUTPUTS, NUM_JOINTS, NUM_CONTACTPOINTS >::update(), and ct::rbd::tpl::OperationalModelRBD< RBDContainer, NUM_CONTACTPOINTS, SCALAR >::update().
int main (int argc, char ** argv)