/home/adrl/code/src/control-toolbox/ct_rbd/test/systems/ProjectedFDSystemTest.cpp File Reference
ProjectedFDSystemTest.cpp File Reference
#include <gtest/gtest.h>
#include <ct/rbd/rbd.h>
#include "../models/testhyq/RobCoGenTestHyQ.h"
Functions
TEST (ProjectedFDSystemTest, projected_forward_dynamics_test)
TEST (ProjectedFDSystemTest, projected_forward_dynamics_autodiff_test)
TEST (ProjectedFDSystemTest, projected_forward_dynamics_codegen_test)
int main (int argc, char **argv)
Function Documentation
TEST (ProjectedFDSystemTest , projected_forward_dynamics_test)
References dt, ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::fromStateVectorQuaternion(), i, ct::core::Integrator< STATE_DIM, SCALAR >::integrate_n_steps(), ct::rbd::RBDState< NJOINTS, SCALAR >::isApprox(), ct::core::RK4, ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorEulerXyz(), and ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorQuaternion().
TEST (ProjectedFDSystemTest , projected_forward_dynamics_autodiff_test)
References control_dim, ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::core::AutoDiffLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), ct::core::AutoDiffLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), state_dim, t, ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorEulerXyz(), u, and x.
TEST (ProjectedFDSystemTest , projected_forward_dynamics_codegen_test)
References control_dim, ct::core::ADCodegenLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::generateCode(), and state_dim.
int main (int argc, char ** argv)