/home/adrl/code/src/control-toolbox/ct_rbd/test/robot/costfunction/rbdJITtests.h File Reference
rbdJITtests.h File Reference
#include <gtest/gtest.h>
#include "../../models/testhyq/RobCoGenTestHyQ.h"
Typedefs
using size_type = ct::core::ADCGScalar
using KinTpl_t = TestHyQ::tpl::Kinematics< size_type >
Functions
std::shared_ptr< TermTaskspacePosition< KinTpl_t, true, hyqStateDim, hyqControlDim > > termTaskspace (new TermTaskspacePosition< KinTpl_t, true, hyqStateDim, hyqControlDim >(eeId, Qpos, Eigen::Vector3d::Random()))
std::shared_ptr< TermTaskspacePose< KinTpl_t, true, hyqStateDim, hyqControlDim > > termTaskspacePose (new TermTaskspacePose< KinTpl_t, true, hyqStateDim, hyqControlDim >(eeId, Qpos, Qrot, Eigen::Vector3d::Random(), Eigen::Vector3d::Random()))
template<typename SCALAR >
Eigen::Matrix< SCALAR, 1, 1 > testFunctionTaskSpacePosition (const Eigen::Matrix< SCALAR, hyqStateDim+hyqControlDim, 1 > xu)
test TermTaskSpacePosition term for JIT-compatibility
TEST (RBD_JIT_Tests, TaskspacePositionCostFunctionTest)
template<typename SCALAR >
Eigen::Matrix< SCALAR, 1, 1 > testFunctionTaskSpacePose (const Eigen::Matrix< SCALAR, hyqStateDim+hyqControlDim, 1 > xu)
test TermTaskSpacePose term for JIT-compatibility
TEST (RBD_JIT_Tests, TaskspacePoseCostFunctionTest)
template<typename SCALAR >
Eigen::Matrix< SCALAR, 1, 1 > testFunctionRBDPose (const Eigen::Matrix< SCALAR, 3+3, 1 > &xu)
test the RigidBodyPose class for JIT-compatibility
TEST (RBD_JIT_Tests, RigidBodyPoseTest)
template<typename SCALAR >
Eigen::Matrix< SCALAR, 1, 1 > testFunctionRigidBodyState (const Eigen::Matrix< SCALAR, 12, 1 > &state)
test the RigidBodyState class for JIT-compatibility
TEST (RBD_JIT_Tests, RigidBodyStateTest)
template<typename SCALAR >
Eigen::Matrix< SCALAR, 1, 1 > testFunctionRBDState (const Eigen::Matrix< SCALAR, hyqStateDim, 1 > &x)
test the RBDState class for JIT-compatibility
TEST (RBD_JIT_Tests, RBDStateTest)
Variables
bool verbose = true
const size_t hyqStateDim = 36
some global variables required for the TaskSpaceTerm test
const size_t hyqControlDim = 12
KinTpl_t kynTpl
size_t eeId = 1
const Eigen::Matrix< double, 3, 3 > Qpos = Eigen::Matrix<double, 3, 3>::Random()
double Qrot = 1.0
Typedef Documentation
using size_type = ct::core::ADCGScalar
using KinTpl_t = TestHyQ::tpl::Kinematics<size_type>
Function Documentation
std::shared_ptr<TermTaskspacePosition<KinTpl_t, true, hyqStateDim, hyqControlDim> > termTaskspace (new TermTaskspacePosition< KinTpl_t, true, hyqStateDim, hyqControlDim > eeId, Qpos, Eigen::Vector3d::Random())
Referenced by testFunctionTaskSpacePosition().
std::shared_ptr<TermTaskspacePose<KinTpl_t, true, hyqStateDim, hyqControlDim> > termTaskspacePose (new TermTaskspacePose< KinTpl_t, true, hyqStateDim, hyqControlDim > eeId, Qpos, Qrot, Eigen::Vector3d::Random(), Eigen::Vector3d::Random())
Referenced by testFunctionTaskSpacePose().
template<typename SCALAR > Eigen::Matrix<SCALAR, 1, 1> testFunctionTaskSpacePosition (const Eigen::Matrix< SCALAR, hyqStateDim+hyqControlDim, 1 > xu)
test TermTaskSpacePosition term for JIT-compatibility
References t, and termTaskspace().
TEST (RBD_JIT_Tests , TaskspacePositionCostFunctionTest)
References ct::core::DerivativesCppadJIT< IN_DIM, OUT_DIM >::compileJIT(), ct::core::DerivativesCppadSettings::createJacobian_, and verbose.
template<typename SCALAR > Eigen::Matrix<SCALAR, 1, 1> testFunctionTaskSpacePose (const Eigen::Matrix< SCALAR, hyqStateDim+hyqControlDim, 1 > xu)
test TermTaskSpacePose term for JIT-compatibility
References t, and termTaskspacePose().
TEST (RBD_JIT_Tests , TaskspacePoseCostFunctionTest)
References ct::core::DerivativesCppadJIT< IN_DIM, OUT_DIM >::compileJIT(), ct::core::DerivativesCppadSettings::createJacobian_, and verbose.
template<typename SCALAR > Eigen::Matrix<SCALAR, 1, 1> testFunctionRBDPose (const Eigen::Matrix< SCALAR, 3+3, 1 > & xu)
test the RigidBodyPose class for JIT-compatibility
References ct::rbd::tpl::RigidBodyPose< SCALAR >::getEulerAnglesXyz(), ct::rbd::tpl::RigidBodyPose< SCALAR >::position(), ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromEulerAnglesXyz(), and t.
TEST (RBD_JIT_Tests , RigidBodyPoseTest)
References ct::core::DerivativesCppadJIT< IN_DIM, OUT_DIM >::compileJIT(), ct::core::DerivativesCppadSettings::createJacobian_, and verbose.
template<typename SCALAR > Eigen::Matrix<SCALAR, 1, 1> testFunctionRigidBodyState (const Eigen::Matrix< SCALAR, 12, 1 > & state)
test the RigidBodyState class for JIT-compatibility
References ct::rbd::tpl::RigidBodyState< SCALAR >::pose(), t, and ct::rbd::tpl::RigidBodyState< SCALAR >::velocities().
TEST (RBD_JIT_Tests , RigidBodyStateTest)
References ct::core::DerivativesCppadJIT< IN_DIM, OUT_DIM >::compileJIT(), ct::core::DerivativesCppadSettings::createJacobian_, and verbose.
template<typename SCALAR > Eigen::Matrix<SCALAR, 1, 1> testFunctionRBDState (const Eigen::Matrix< SCALAR, hyqStateDim, 1 > & x)
test the RBDState class for JIT-compatibility
References ct::rbd::RBDState< NJOINTS, SCALAR >::base(), ct::rbd::RBDState< NJOINTS, SCALAR >::joints(), ct::rbd::tpl::RigidBodyState< SCALAR >::pose(), t, ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorEulerXyz(), and ct::rbd::tpl::RigidBodyState< SCALAR >::velocities().
TEST (RBD_JIT_Tests , RBDStateTest)
References ct::core::DerivativesCppadJIT< IN_DIM, OUT_DIM >::compileJIT(), ct::core::DerivativesCppadSettings::createJacobian_, and verbose.
Variable Documentation
bool verbose = true
Referenced by ct::rbd::SimpleArmTrajectoryGenerator< NJOINTS, SCALAR >::generateTrajectory(), ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::loadConfigFile(), ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::loadConfigFile(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::loadConfigFile(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::loadConfigFile(), main(), ct::rbd::TermTaskspaceGeometricJacobian< KINEMATICS, STATE_DIM, CONTROL_DIM >::TermTaskspaceGeometricJacobian(), ct::rbd::TermTaskspacePose< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePose(), ct::rbd::TermTaskspacePoseCG< KINEMATICS, FLOATING_BASE, STATE_DIM, CONTROL_DIM >::TermTaskspacePoseCG(), ct::rbd::TermTaskspacePosition< KINEMATICS, FB, STATE_DIM, CONTROL_DIM >::TermTaskspacePosition(), and TEST().
const size_t hyqStateDim = 36
some global variables required for the TaskSpaceTerm test
Referenced by TEST().
const size_t hyqControlDim = 12
Referenced by TEST().
KinTpl_t kynTpl
Referenced by TEST().
size_t eeId = 1
Referenced by ct::rbd::EEContactModel< Kinematics >::smoothing(), and TEST().
const Eigen::Matrix<double, 3, 3> Qpos = Eigen::Matrix<double, 3, 3>::Random()
Referenced by TEST().
double Qrot = 1.0
Referenced by TEST().