/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/systems/linear/RBDLinearizerTest.cpp File Reference
RBDLinearizerTest.cpp File Reference
#include <ct/rbd/rbd.h>
#include <memory>
#include <array>
#include <iostream>
#include <gtest/gtest.h>
#include <ct/rbd/systems/linear/RbdLinearizer.h>
#include "ct/rbd/systems/FixBaseFDSystem.h"
#include "ct/rbd/systems/FloatingBaseFDSystem.h"
#include "../../models/testIrb4600/RobCoGenTestIrb4600.h"
#include "../../models/testhyq/RobCoGenTestHyQ.h"
Functions
TEST (RBDLinearizerTest, NumDiffComparisonFixedBase)
TEST (RBDLinearizerTest, NumDiffComparisonFloatingBase)
int main (int argc, char **argv)
Function Documentation
TEST() [1/2]
TEST (RBDLinearizerTest , NumDiffComparisonFixedBase)
References ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeState(), i, u, and x.
TEST() [2/2]
TEST (RBDLinearizerTest , NumDiffComparisonFloatingBase)
References ct::rbd::FloatingBaseFDSystem< RBDDynamics, QUAT_INTEGRATION, EE_ARE_CONTROL_INPUTS >::CONTROL_DIM, ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeControl(), ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeControl(), ct::core::SystemLinearizer< STATE_DIM, CONTROL_DIM, SCALAR >::getDerivativeState(), ct::rbd::RbdLinearizer< SYSTEM >::getDerivativeState(), i, ct::rbd::FloatingBaseFDSystem< RBDDynamics, QUAT_INTEGRATION, EE_ARE_CONTROL_INPUTS >::STATE_DIM, u, and x.
main()
int main (int argc, char ** argv)