/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/state/RigidBodyPoseTest.cpp File Reference
RigidBodyPoseTest.cpp File Reference
#include <ct/rbd/rbd.h>
#include "ct/rbd/state/RigidBodyPose.h"
#include <memory>
#include <array>
#include <gtest/gtest.h>
Functions
void testEqual (const RigidBodyPose &pose1, const RigidBodyPose &pose2)
void testNotEqual (const RigidBodyPose &pose1, const RigidBodyPose &pose2)
TEST (RigidBodyPoseTest, storageTest)
TEST (RigidBodyPoseTest, asignmentTest)
TEST (RigidBodyPoseTest, conversionTest)
TEST (RigidBodyPoseTest, gravityTest)
TEST (RigidBodyPoseTest, rotationTest)
int main (int argc, char **argv)
Function Documentation
testEqual()
void testEqual (const RigidBodyPose & pose1, const RigidBodyPose & pose2)
References ct::rbd::tpl::RigidBodyPose< SCALAR >::computeGravityB(), ct::rbd::tpl::RigidBodyPose< SCALAR >::computeGravityB6D(), ct::rbd::tpl::RigidBodyPose< SCALAR >::getEulerAnglesXyz(), ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationMatrix(), ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationQuaternion(), ct::rbd::tpl::RigidBodyPose< SCALAR >::isNear(), and ct::rbd::tpl::RigidBodyPose< SCALAR >::position().
Referenced by TEST().
testNotEqual()
void testNotEqual (const RigidBodyPose & pose1, const RigidBodyPose & pose2)
References ct::rbd::tpl::RigidBodyPose< SCALAR >::computeGravityB(), ct::rbd::tpl::RigidBodyPose< SCALAR >::computeGravityB6D(), ct::rbd::tpl::RigidBodyPose< SCALAR >::getEulerAnglesXyz(), ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationMatrix(), ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationQuaternion(), and ct::rbd::tpl::RigidBodyPose< SCALAR >::isNear().
Referenced by TEST().
TEST() [1/5]
TEST (RigidBodyPoseTest , storageTest)
References ct::rbd::tpl::RigidBodyPose< double >::EULER, ct::rbd::tpl::RigidBodyPose< SCALAR >::getStorageType(), and ct::rbd::tpl::RigidBodyPose< double >::QUAT.
TEST() [2/5]
TEST (RigidBodyPoseTest , asignmentTest)
References ct::rbd::tpl::RigidBodyPose< double >::EULER, ct::rbd::tpl::RigidBodyPose< double >::QUAT, ct::rbd::tpl::RigidBodyPose< SCALAR >::setRandom(), testEqual(), and testNotEqual().
TEST() [3/5]
TEST (RigidBodyPoseTest , conversionTest)
References ct::rbd::tpl::RigidBodyPose< double >::EULER, ct::rbd::tpl::RigidBodyPose< SCALAR >::getEulerAnglesXyz(), ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationQuaternion(), ct::rbd::tpl::RigidBodyPose< SCALAR >::position(), ct::rbd::tpl::RigidBodyPose< double >::QUAT, ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromEulerAnglesXyz(), ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromRotationQuaternion(), ct::rbd::tpl::RigidBodyPose< SCALAR >::setIdentity(), ct::rbd::tpl::RigidBodyPose< SCALAR >::setRandom(), and testEqual().
TEST() [4/5]
TEST (RigidBodyPoseTest , gravityTest)
References ct::rbd::tpl::RigidBodyPose< SCALAR >::computeGravityB(), ct::rbd::tpl::RigidBodyPose< SCALAR >::computeGravityB6D(), ct::rbd::tpl::RigidBodyPose< double >::EULER, i, ct::rbd::tpl::RigidBodyPose< double >::QUAT, ct::rbd::tpl::RigidBodyPose< SCALAR >::setFromEulerAnglesXyz(), ct::rbd::tpl::RigidBodyPose< SCALAR >::setIdentity(), and ct::rbd::tpl::RigidBodyPose< SCALAR >::setRandom().
TEST() [5/5]
TEST (RigidBodyPoseTest , rotationTest)
References ct::rbd::tpl::RigidBodyPose< double >::EULER, ct::rbd::tpl::RigidBodyPose< SCALAR >::getRotationMatrix(), ct::rbd::tpl::RigidBodyPose< double >::QUAT, ct::rbd::tpl::RigidBodyPose< SCALAR >::rotateBaseToInertia(), and ct::rbd::tpl::RigidBodyPose< SCALAR >::rotateInertiaToBase().
main()
int main (int argc, char ** argv)