/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/state/RobotStateTest.cpp File Reference
RobotStateTest.cpp File Reference
#include <ct/rbd/rbd.h>
#include <gtest/gtest.h>
Functions
template<typename T >
bool areEqual (const T v1, const T v2)
TEST (RobotStateTest, FloatingBaseInstantiationTest)
TEST (RobotStateTest, FixBaseInstantiationTest)
TEST (RobotStateTest, FloatingBaseStateComparison)
int main (int argc, char **argv)
Function Documentation
areEqual()
template<typename T > bool areEqual (const T v1, const T v2)
Referenced by TEST().
TEST() [1/3]
TEST (RobotStateTest , FloatingBaseInstantiationTest)
References njoints.
TEST() [2/3]
TEST (RobotStateTest , FixBaseInstantiationTest)
References njoints.
TEST() [3/3]
TEST (RobotStateTest , FloatingBaseStateComparison)
References ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::actuatorState(), areEqual(), ct::rbd::RBDState< NJOINTS, SCALAR >::baseLinearVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::baseLocalAngularVelocity(), ct::rbd::RBDState< NJOINTS, SCALAR >::baseVelocities(), ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVectorEulerXyz(), ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::fromStateVectorQuaternion(), i, ct::rbd::RBDState< NJOINTS, SCALAR >::isApprox(), ct::rbd::RBDState< NJOINTS, SCALAR >::jointPositions(), ct::rbd::RBDState< NJOINTS, SCALAR >::jointVelocities(), njoints, ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::rbdState(), ct::rbd::RBDState< NJOINTS, SCALAR >::setRandom(), ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVectorEulerXyz(), ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorEulerXyz(), ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVectorEulerXyzUnique(), ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorEulerXyzUnique(), ct::rbd::FloatingBaseRobotState< NJOINTS, ACT_STATE_DIM, SCALAR >::toStateVectorQuaternion(), and ct::rbd::RBDState< NJOINTS, SCALAR >::toStateVectorQuaternion().
main()
int main (int argc, char ** argv)