/home/gim2rng/ct_devel_ws/src/control-toolbox/ct_rbd/test/robot/costfunction/TaskspaceCostFunctionTest.h File Reference
TaskspaceCostFunctionTest.h File Reference
#include <gtest/gtest.h>
#include "../../models/testhyq/RobCoGenTestHyQ.h"
Functions
template<size_t state_dim, size_t control_dim>
void compareCostFunctionOutput (CostFunctionQuadratic< state_dim, control_dim > &costFunction, CostFunctionQuadratic< state_dim, control_dim > &costFunction2)
This method is called from different unit tests in order to compare the cost, first and second order gradients of two cost functions.
TEST (TaskspaceCostFunctionTests, TestTaskSpacePositionTerm)
TEST (TaskspaceCostFunctionTests, TestTaskSpacePoseTerm)
TEST (TaskspaceCostFunctionTests, TestTaskSpacePoseTermCG)
Function Documentation
compareCostFunctionOutput()
template<size_t state_dim, size_t control_dim> void compareCostFunctionOutput (CostFunctionQuadratic< state_dim, control_dim > & costFunction, CostFunctionQuadratic< state_dim, control_dim > & costFunction2)
This method is called from different unit tests in order to compare the cost, first and second order gradients of two cost functions.
Parameters
costFunction the first cost function to be compared
costFunction2 the second cost function to be compared
Referenced by TEST().
TEST() [1/3]
TEST (TaskspaceCostFunctionTests , TestTaskSpacePositionTerm)
References compareCostFunctionOutput(), eeId, hyqControlDim, hyqStateDim, kynTpl, t, u, and x.
TEST() [2/3]
TEST (TaskspaceCostFunctionTests , TestTaskSpacePoseTerm)
References compareCostFunctionOutput(), eeId, hyqControlDim, hyqStateDim, kynTpl, Qpos, Qrot, t, u, and x.
TEST() [3/3]
TEST (TaskspaceCostFunctionTests , TestTaskSpacePoseTermCG)
References compareCostFunctionOutput(), eeId, hyqControlDim, hyqStateDim, Qpos, Qrot, t, u, and x.