/home/adrl/code/src/control-toolbox/ct_rbd/test/CMakeLists.txt File Reference
/home/adrl/code/src/control-toolbox/ct_rbd/test/CMakeLists.txt File Reference
Functions
macro (package_add_test TESTNAME) add_executable($
Function Documentation
macro (package_add_test TESTNAME)
References list, set_target_properties(), target_link_libraries(), and test().